### ISSUE TITLE
Allow events to be dragged and dropped

### ISSUE THREAD

**Issue by mattlewis92** [mattlewis92/angular-calendar#10]
- [x] month view
- [x] week view
- [x] day view

Remaining items
- [x] fix failing test
- [x] events cant be dragged back to their original positions
- [x] resizing and dragging of events is currently broken -> disable drag and drop when resizing
- [x] disable dragging outside of the calendar for the week and day views -> https://github.com/mattlewis92/angular-draggable-droppable/issues/10

**Comment by RamitAnandSharma** [comment]
I need this feature in my project. When is this feature available for use,

**Comment by mattlewis92** [comment]
It's open source so completely limited by my spare time available...

**Comment by sireneweb** [comment]
maybe we can help you ?

**Comment by mattlewis92** [comment]
That would be awesome! Happy to review a PR that adds this functionality. API wise it should replicate what's available in the ng1 version. The first thing to do is find or build a standalone drag and drop lib for angular 2 that has all the features required (AOT compatible, drop zones, validation, snap grids etc). Once that's done it should be pretty trivial to add this into this library.

**Comment by sireneweb** [comment]
Do you want to use ng2-dnd to do that ? or from scratch ?

**Comment by mattlewis92** [comment]
After giving it some more thought I've decided to just roll my own dnd directives to give the functionality that the calendar needs as there's quite a lot missing from the angular dnd library. I've created the repo here: https://github.com/mattlewis92/angular-draggable-droppable

and implemented a basic draggable directive + created issue stubs for the rest of the needed features: https://github.com/mattlewis92/angular-draggable-droppable/issues 

Feel free to contribute! 😄

**Comment by sireneweb** [comment]
i have try an another plugin who maybe help, it's ng2 dragula ? have you try it ?

**Comment by mattlewis92** [comment]
I did look at dragula, unfortunately it doesn't have any support for snap grids. I made some [good progress](https://github.com/mattlewis92/angular-draggable-droppable/issues/1#issuecomment-261782620) this weekend on building my own directive, I just need to implement a few extra features and then it should be good to go!

**Comment by sireneweb** [comment]
Great news :) Thanks for all you do for the community :dancing_men:

**Comment by mattlewis92** [comment]
No problem, happy to help! 😃

**Comment by RamitAnandSharma** [comment]
Any update on the release date of this feature

**Comment by sireneweb** [comment]
As say Jedi : Be patient :D, mattlewis92 create new repository to test this functionality
https://github.com/mattlewis92/angular-draggable-droppable

**Comment by mattlewis92** [comment]
I've built the low level directives to handle drag and drop: https://github.com/mattlewis92/angular-draggable-droppable

It's now just a case of hooking up the calendar to use them.

**Comment by mattlewis92** [comment]
Finally made some good progress with this today: https://github.com/mattlewis92/angular-calendar/tree/0.5.0

There are a few issues I've found with the drag and drop directive as I was implementing this that I need to fix first, but all are pretty minor and shouldn't take long to fix. I'll aim to get them done today! :)

**Comment by mattlewis92** [comment]
I think I've ironed out all the issues and I will cut a new release once I've finished the other issues in the 0.5.0 milestone. In the mean time if you want drag and drop _today_, you can install `0.5.0-beta.0` via `npm install angular-calendar@beta`. Let me know if there are any issues with it! 😃
