### ISSUE TITLE
Time difference is not correct. For eg: i choose a slot between 12:30 am to 3:00 am , then it calculates newEnd as 3:30am.

### ISSUE THREAD

**Issue by dollyshah-02** [mattlewis92/angular-calendar#1001]
**Describe the bug**

**Minimal reproduction of the problem with instructions**

**Screenshots**

**Versions**

- `@angular/core`:
- `angular-calendar`:
- Browser name and version:

**Comment by PlexusMark** [comment]
Can you create a minimal reproduction of this? I am unable to duplicate it myself.

**Comment by mattlewis92** [comment]
Yup, please make a repro, without one it's not possible to provide any further assistance. You can fork a starter from any of the demos by hitting the "Edit in stackblitz" button. Thanks!
