### ISSUE TITLE
Tooltip doesn't refresh when scaling down (resizing) a time slot in day view.

### ISSUE THREAD

**Issue by jeanft** [mattlewis92/angular-calendar#1002]
**Describe the bug**

When I create a new CalendarEvent (using mouse down, drag down/up, mouse up), the tooltip doesn't refresh when I scale down the event.

**Minimal reproduction of the problem with instructions**
Using CustomEventTitleFormatter, in dayTooltip function, return event.meta.durationInMinutes.
```
    dayTooltip(event: CalendarEvent): string {
        return event.meta.durationInMinutes;
    }
```
Create an event, scale up => tooltip updated. Scaled down => tooltip doesn't update.

**Versions**

- `@angular/core`: 7.2.2 
- `angular-calendar`: 0.27.9
- Browser name and version: Chrome 74.0.3729.169

**Comment by mattlewis92** [comment]
Hey, any chance you can make a stackblitz that reproduces your issue? You can fork one from any of the demos by hitting the "Edit in stackblitz" button. Thanks!

**Comment by jeanft** [comment]
https://stackblitz.com/edit/angular-yvt9me
app: https://angular-yvt9me.stackblitz.io

Create an event.
Drag to extend: see title and tooltip updating
Drag to scale down: see title updading **but** tooltip **not** updating

**Comment by mattlewis92** [comment]
Thanks for that! I'm still having trouble seeing the issue though, can you share a screen recording or something showing it?

**Comment by jeanft** [comment]
Look at the tooltip in this video.

[Screen recording.zip](https://github.com/mattlewis92/angular-calendar/files/3266739/Screen.recording.zip)

**Comment by mattlewis92** [comment]
Ahh, I see the issue now, please give the latest version a try! 😄

**Comment by jeanft** [comment]
Thank you very much for your responsiveness.
Keep up the good work!
