### ISSUE TITLE
Test case issues

### ISSUE THREAD

**Issue by pardhuangular** [mattlewis92/angular-calendar#1007]
**Describe the bug**
I integrated calendar component into my project.
Its runs successfully, but issue as shown below  Executing Test cases.
**Screenshots**

![image](https://user-images.githubusercontent.com/39066717/59231631-432eb300-8b96-11e9-806c-ee8565ed275b.png)
**Versions**

- `@angular/core`:7.3.5
- `angular-calendar`:0.27.8
- Browser name and version:

**Comment by pardhuangular** [comment]
My Spec file as shown below
import { ComponentFixture, TestBed } from '@angular/core/testing';
import { NO_ERRORS_SCHEMA } from '@angular/core';
import { CalendarView } from 'angular-calendar';
import { CalendarComponent } from '../app/shared/components/calendar/calendar.component';

fdescribe('CalendarComponent', () => {
  let component: CalendarComponent;
  let fixture: ComponentFixture<CalendarComponent>;
  beforeEach(() => {
    const calendarViewStub = {};
    TestBed.configureTestingModule({
      schemas: [NO_ERRORS_SCHEMA],
      declarations: [CalendarComponent],
      providers: [{ provide: CalendarView, useValue: calendarViewStub }]
    });
    fixture = TestBed.createComponent(CalendarComponent);
    component = fixture.componentInstance;
  });
  it('can load instance', () => {
    expect(component).toBeTruthy();
  });
  it('events defaults to: []', () => {
    expect(component.events).toEqual([]);
  });
  it('activeDayIsOpen defaults to: true', () => {
    expect(component.activeDayIsOpen).toEqual(true);
  });
  it('view defaults to: CalendarView.Month', () => {
    expect(component.view).toEqual(CalendarView.Month);
  });
  it('CalendarView defaults to: CalendarView', () => {
    expect(component.CalendarView).toEqual(CalendarView);
  });
  it('actions defaults to: []', () => {
    expect(component.actions).toEqual([]);
  });
  describe('ngOnInit', () => {
    it('makes expected calls', () => {
      spyOn(component, 'handleEvent').and.callThrough();
      component.ngOnInit();
      expect(component.handleEvent).toHaveBeenCalled();
    });
  });
});

**Comment by mattlewis92** [comment]
@pardhuangular you need to declare the `CalendarModule` in the `imports` of `TestBed.configureTestingModule`, otherwise angular doesn't know about any of the components or pipes provided by this lib:
```
TestBed.configureTestingModule({
schemas: [NO_ERRORS_SCHEMA],
declarations: [CalendarComponent],
providers: [{ provide: CalendarView, useValue: calendarViewStub }],
imports: [
  CalendarModule.forRoot({
      provide: DateAdapter,
      useFactory: adapterFactory
    })
]
});
```
