### ISSUE TITLE
window.clearTimeout 

### ISSUE THREAD

**Issue by GIOkafor** [mattlewis92/angular-calendar#1012]
**Describe the bug**

On the calendar - doesn't matter what view - when I try dragging an event to change it's date, I get an error saying "window.clearTimeout is not a function" 

**Minimal reproduction of the problem with instructions**

On the demos page of angular-calendar, on the kitchen sink example, select edit in stackblitz and try moving any event on the calendar around.

Here's a link to a stackblitz instance https://nrtgix.run.stackblitz.io

**Screenshots**

![draggable error](https://user-images.githubusercontent.com/7291283/59923099-8394f900-9400-11e9-9078-8e689d2e8af5.PNG)

**Versions**

- `@angular/core`: "8.0.0"
- `angular-calendar`: "0.27.11"
- Browser name and version: Google Chrome v 74.0.3729.169

**Comment by GIOkafor** [comment]
Just tested locally, for some reason this only happened when running the code on stackblitz.

**Comment by mattlewis92** [comment]
That's very weird, I think it's a stackblitz specific issue, but I think I found a workaround. Thanks for reporting! 😄

**Comment by GIOkafor** [comment]
> That's very weird, I think it's a stackblitz specific issue, but I think I found a workaround. Thanks for reporting! 😄

I thought so too 😂, glad you were able to find a workaround for it, however I think the workaround may have introduced a new issue 😭. 

Now whenever I click on one of the labels in the modal that pop up, it **always** triggers the dropped or resized event rather than the appropriate action attached to the label that was clicked - **unless** `draggable` is set to false.

This happens both locally and on stackblitz as well, but please take a look at this link to see it in action
https://jddlfw.run.stackblitz.io/

Thank you for the good work you do.

**Comment by mattlewis92** [comment]
I'm not able to reproduce that: https://stackblitz.com/edit/angular-jucd7w?file=demo/component.ts

I'm not able to load your stackblitz though, can you share the edit link instead?

**Comment by GIOkafor** [comment]
Here is a link: 
https://stackblitz.com/edit/angular-jucd7w

Pretty much your kitchen sink example

**Comment by mattlewis92** [comment]
Everything seems to work for me?

![Kapture 2019-06-27 at 10 21 44](https://user-images.githubusercontent.com/6425649/60274082-6f9c3c00-98c5-11e9-93cd-438ba325650e.gif)

**Comment by GIOkafor** [comment]
You're right it works fine on Microsoft edge, however when I switch to Google Chrome it comes back.

![https___angular-jucd7w stackblitz io](https://user-images.githubusercontent.com/7291283/60275943-a758b300-98c8-11e9-88bb-f4c377369377.gif)

What browser are you running it on?

**Comment by mattlewis92** [comment]
I'm using chrome 75 and it works for me there, can you try in private browsing in case it's a chrome extension?

**Comment by GIOkafor** [comment]
Hey @mattlewis92 it works now, had to restart my computer to get it to work correctly. Don't know why that happened in the first place but I'm glad it's resolved. 
THANKS a bunch❤❤

**Comment by mattlewis92** [comment]
Actually I think you might just be moving the mouse like 1px when dragging, can you give `0.27.12` a go which might fix it?

**Comment by GIOkafor** [comment]
Yea it works now with the latest update. 
Thanks a bunch ❤❤
