### ISSUE TITLE
mwl-calendar-open-day-events is getting duplicated on every week's row

### ISSUE THREAD

**Issue by spmorr01** [mattlewis92/angular-calendar#1014]
Describe the bug

With the latest version of Angular (v8), RxJS 6, and angular-calendar version 0.27.11, the day events that open up get duplicated on every single row of the month view.

If I go back to version 0.24.1 of angular-calendar and add in rxjs-compat, it works fine. There are absolutely no code changes made on my end. Simply updating it breaks it. 

It would be great to have this fix ASAP, as we are wanting to be able to fully pull away from relying on rxjs-compat.

**Minimal reproduction of the problem with instructions**

Just updating to the latest version of everything will break it.

**Screenshots**

![image](https://user-images.githubusercontent.com/12806561/59946977-abe91b80-9431-11e9-86b9-dc8b18a24933.png)

**Versions**

- `@angular/core`: 8.0.2
- `angular-calendar`: 0.27.11
- `RxJS`: 6.5.2
- Browser name and version: Chrome 74.0.3729.169

**Comment by spmorr01** [comment]
Like I mentioned, going back a version of angular-calendar (0.24.1) and adding in rxjs-compat, it works:

![image](https://user-images.githubusercontent.com/12806561/59947341-91637200-9432-11e9-9c04-8237f1bdbd4f.png)

**Comment by mattlewis92** [comment]
It sounds like you've been hit by a [breaking change](https://github.com/mattlewis92/angular-calendar/blob/master/CHANGELOG.md#breaking-changes-1). It's probably this one:

<img width="900" alt="Screenshot 2019-06-21 at 17 23 23" src="https://user-images.githubusercontent.com/6425649/59952190-4e60c900-9449-11e9-8b67-5f7e32adb66e.png">

Hope that helps! 😄

**Comment by spmorr01** [comment]
About to head out for the day, will try on Monday!

Thanks for the quick response! Stay tuned

**Comment by spmorr01** [comment]
We already had that wrapper, and I added that component metadata and still no luck.

Here's a screenshot of our template code:

![image](https://user-images.githubusercontent.com/12806561/60034409-39b24a00-9670-11e9-97b8-a84d77e8a7c0.png)

**Comment by mattlewis92** [comment]
Oh I see the issue, it should be `*ngIf="isOpen"` and not `*ngIf="activeDayIsOpen"` (as `activeDayIsOpen` will be true for all days hence why they all appear open). You also need to pass the `isOpen` local variable to the template like `let-isOpen="isOpen"`.

**Comment by spmorr01** [comment]
Awesome! That worked! I really appreciate it!

Do you have a link to the docs by chance where this is? I just want to keep a link to that for our docs. 

Also, is "activeDayIsOpen"a property from an earlier version? I didn't originally implement this into our app, so I was just curious.

Thanks again!

**Comment by mattlewis92** [comment]
There's no docs for each custom templates local variables as they would get out of date on every change, the best way is to copy the latest from the source code: https://github.com/mattlewis92/angular-calendar/blob/master/projects/angular-calendar/src/modules/month/calendar-open-day-events.component.ts#L32-L70

`activeDayIsOpen` is an input on the `mwl-calendar-month-view` component, and is used to tell the calendar to open whichever day corresponds to the `viewDate` input. Setting it to false will close the open days events.

**Comment by webdevelopersbc** [comment]
Hello @mattlewis92 could please help me i need to dispaly events subpoints on week and  day view ,like event location and time 
how to create custom ng-template for week and day view, can you please provide me code block for that

 here is the link of screen how i need to show 
https://prnt.sc/1c0xml4
