### ISSUE TITLE
TypeError: startOfDay is not a function

### ISSUE THREAD

**Issue by salondevguru** [mattlewis92/angular-calendar#1018]
**Describe the bug**
*Minimal reproduction of the problem with instructions**
CalendarComponent.html:84 ERROR TypeError: startOfDay is not a function
    at getDayViewHourGrid (calendar-utils.js:570)
    at CalendarUtils.getDayViewHourGrid (angular-calendar.js:1192)
    at CalendarDayViewComponent.refreshHourGrid (angular-calendar.js:3930)
    at CalendarDayViewComponent.ngOnChanges (angular-calendar.js:3745)
    at checkAndUpdateDirectiveInline (core.js:24499)
    at checkAndUpdateNodeInline (core.js:35163)
    at checkAndUpdateNode (core.js:35102)
    at debugCheckAndUpdateNode (core.js:36124)
    at debugCheckDirectivesFn (core.js:36067)
    at Object.eval [as updateDirectives] (CalendarComponent.html:85)
View_CalendarComponent_8 @ CalendarComponent.html:84
logError @ core.js:36342
handleError @ core.js:7239
(anonymous) @ core.js:32092
invoke @ zone-evergreen.js:359
run @ zone-evergreen.js:124
runOutsideAngular @ core.js:30830
tick @ core.js:32089
(anonymous) @ core.js:31927
invoke @ zone-evergreen.js:359
onInvoke @ core.js:30904
invoke @ zone-evergreen.js:358
run @ zone-evergreen.js:124
run @ core.js:30769
next @ core.js:31924
schedulerFn @ core.js:27846
__tryOrUnsub @ Subscriber.js:183
next @ Subscriber.js:122
_next @ Subscriber.js:72
next @ Subscriber.js:49
next @ Subject.js:39
emit @ core.js:27808
checkStable @ core.js:30847
onHasTask @ core.js:30924
hasTask @ zone-evergreen.js:411
_updateTaskCount @ zone-evergreen.js:431
_updateTaskCount @ zone-evergreen.js:264
runTask @ zone-evergreen.js:185
drainMicroTaskQueue @ zone-evergreen.js:559
invokeTask @ zone-evergreen.js:469
invokeTask @ zone-evergreen.js:1603
globalZoneAwareCallback @ zone-evergreen.js:1629
Show 2 more frames
CalendarComponent.html:84 ERROR CONTEXT DebugContext_ {view: {…}, nodeIndex: 1, nodeDef: {…}, elDef: {…}, elView: {…}}
View_CalendarComponent_8 @ CalendarComponent.html:84
logError @ core.js:36342
handleError @ core.js:7244
(anonymous) @ core.js:32092
invoke @ zone-evergreen.js:359
run @ zone-evergreen.js:124
runOutsideAngular @ core.js:30830
tick @ core.js:32089
(anonymous) @ core.js:31927
invoke @ zone-evergreen.js:359
onInvoke @ core.js:30904
invoke @ zone-evergreen.js:358
run @ zone-evergreen.js:124
run @ core.js:30769
next @ core.js:31924
schedulerFn @ core.js:27846
__tryOrUnsub @ Subscriber.js:183
next @ Subscriber.js:122
_next @ Subscriber.js:72
next @ Subscriber.js:49
next @ Subject.js:39
emit @ core.js:27808
checkStable @ core.js:30847
onHasTask @ core.js:30924
hasTask @ zone-evergreen.js:411
_updateTaskCount @ zone-evergreen.js:431
_updateTaskCount @ zone-evergreen.js:264
runTask @ zone-evergreen.js:185
drainMicroTaskQueue @ zone-evergreen.js:559
invokeTask @ zone-evergreen.js:469
invokeTask @ zone-evergreen.js:1603
globalZoneAwareCallback @ zone-evergreen.js:1629
Show 2 more frames
CalendarDayViewComponent.html:3 ERROR TypeError: Cannot read property 'allDayEvents' of undefined
    at Object.eval [as updateDirectives] (CalendarDayViewComponent.html:11)
    at Object.debugUpdateDirectives [as updateDirectives] (core.js:36055)
    at checkAndUpdateView (core.js:35067)
    at callViewAction (core.js:35433)
    at execComponentViewsAction (core.js:35361)
    at checkAndUpdateView (core.js:35074)
    at callViewAction (core.js:35433)
    at execEmbeddedViewsAction (core.js:35390)
    at checkAndUpdateView (core.js:35068)
    at callViewAction (core.js:35433)

**Screenshots**

![image](https://user-images.githubusercontent.com/48533526/60123174-6ebfb900-97a4-11e9-8efb-b5f51b82979c.png)

**Versions**

- `@angular/core`: "^8.0.1",
- `angular-calendar`:0.27.11

"dependencies": {
    "@angular/animations": "^8.0.1",
    "@angular/cdk": "^8.0.1",
    "@angular/common": "^8.0.1",
    "@angular/compiler": "^8.0.1",
    "@angular/core": "^8.0.1",
    "@angular/flex-layout": "^7.0.0-beta.24",
    "@angular/forms": "^8.0.1",
    "@angular/material": "^8.0.1",
    "@angular/material-moment-adapter": "^8.0.1",
    "@angular/platform-browser": "^8.0.1",
    "@angular/platform-browser-dynamic": "^8.0.1",
    "@angular/router": "^8.0.1",
    "@ng-bootstrap/ng-bootstrap": "^4.2.1",
    "@ng-select/ng-select": "^2.20.1",
    "@ngx-translate/core": "^11.0.1",
    "@ngx-translate/http-loader": "^4.0.0",
    "angular-calendar": "^0.27.11",
    "angular-draggable-droppable": "^4.3.1",
    "angular-resizable-element": "^3.2.4",
    "bootstrap": "^4.3.1",
    "calendar-utils": "^0.3.1",
    "core-js": "^3.1.4",
    "d3-time-format": "^2.1.3",
    "material-design-icons": "^3.0.1",
    "ngx-cookie-service": "^2.2.0",
    "rxjs": "~6.5.2",
    "tslib": "^1.10.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.800.2",
    "@angular-devkit/build-ng-packagr": "^0.800.2",
    "@angular/animations": "^8.0.0",
    "@angular/cdk": "^8.0.0",
    "@angular/cli": "^8.0.2",
    "@angular/common": "^8.0.0",
    "@angular/compiler": "^8.0.0",
    "@angular/compiler-cli": "^8.0.0",
    "@angular/core": "^8.0.0",
    "@angular/forms": "^8.0.0",
    "@angular/language-service": "^8.0.0",
    "@angular/platform-browser": "^8.0.0",
    "@angular/platform-browser-dynamic": "^8.0.0",
    "@angular/router": "^8.0.0",
    "@commitlint/cli": "^8.0.0",
    "@commitlint/config-conventional": "^8.0.0",
    "@commitlint/prompt": "^8.0.0",
    "@compodoc/compodoc": "^1.1.9",
    "@fortawesome/angular-fontawesome": "^0.4.0",
    "@fortawesome/fontawesome-free": "^5.9.0",
    "@fortawesome/fontawesome-svg-core": "^1.2.19",
    "@fortawesome/free-brands-svg-icons": "^5.9.0",
    "@fortawesome/free-regular-svg-icons": "^5.9.0",
    "@fortawesome/free-solid-svg-icons": "^5.9.0",
    "@ng-bootstrap/ng-bootstrap": "^4.2.1",
    "@stackblitz/sdk": "^1.3.0",
    "@types/chai": "^4.1.7",
    "@types/jasmine": "~3.3.13",
    "@types/jasminewd2": "~2.0.6",
    "@types/mocha": "^5.2.7",
    "@types/moment": "latest",
    "@types/moment-timezone": "^0.5.12",
    "@types/node": "^12.0.7",
    "@types/sinon": "^7.0.12",
    "@types/sinon-chai": "^3.2.2",
    "angular-cli-ghpages": "^0.5.3",
    "angulartics2": "^7.5.2",
    "angularx-flatpickr": "^6.1.0",
    "autoprefixer": "^9.6.0",
    "bootstrap-css-only": "^4.3.1",
    "chai": "^4.2.0",
    "codecov": "^3.5.0",
    "codelyzer": "^5.1.0",
    "commitizen": "^3.1.1",
    "copyfiles": "^2.1.0",
    "core-js": "^3.1.3",
    "css-loader": "^2.1.1",
    "date-fns": "^1.30.1",
    "flatpickr": "^4.6.1",
    "font-awesome": "^4.7.0",
    "hammerjs": "^2.0.8",
    "highlightjs-loader": "^0.2.3",
    "husky": "^2.4.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "^4.1.0",
    "karma-chrome-launcher": "^2.2.0",
    "karma-coverage-istanbul-reporter": "^2.0.5",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "karma-mocha": "^1.3.0",
    "karma-mocha-reporter": "^2.2.5",
    "mocha": "^6.1.4",
    "moment": "^2.24.0",
    "moment-timezone": "^0.5.25",
    "ng-packagr": "^5.3.0",
    "ngx-clipboard": "^12.1.0",
    "ngx-contextmenu": "^5.2.0",
    "ngx-perfect-scrollbar": "^7.2.1",
    "node-sass": "^4.12.0",
    "postcss-cli": "^6.1.2",
    "postcss-flexibility": "^2.0.0",
    "prettier": "^1.18.2",
    "pretty-quick": "^1.11.0",
    "protractor": "~5.4.2",
    "rrule": "^2.6.0",
    "rxjs": "^6.5.2",
    "sinon": "^7.3.2",
    "sinon-chai": "^3.3.0",
    "standard-version": "^6.0.1",
    "stylelint": "^10.1.0",
    "stylelint-config-prettier": "^5.2.0",
    "stylelint-config-standard": "^18.3.0",
    "ts-node": "^8.3.0",
    "tsickle": "^0.35.0",
    "tslib": "^1.9.0",
    "tslint": "^5.18.0",
    "tslint-config-mwl": "^0.6.0",
    "typescript": "~3.4.5",
    "zone.js": "~0.9.1"
  }
- Browser name and version:
Chrome Version 75.0.3770.100 (Official Build) (64-bit)

**Comment by mattlewis92** [comment]
Any chance you could make a minimal repo on github that reproduces your issue? Thanks! 😄
