### ISSUE TITLE
Touch screen click event on draggable event

### ISSUE THREAD

**Issue by cosf87** [mattlewis92/angular-calendar#1019]
**Describe the bug**

In touch screens or mobile devices, click event is not fired when I click on a draggable event. However, click event is fired if the event is not draggable. I am using a custom cell template from the month view.
On the other hand, I have no issues with click event on draggable items of Angular Material drag and drop module

**Minimal reproduction of the problem with instructions**

**Screenshots**

**Versions**

- `@angular/core`: 8.0.2
- `angular-calendar`: 0.27.11
- Browser name and version: Chrome 75.0.3770.100

**Comment by mattlewis92** [comment]
I'm not able to reproduce this on the demo on chrome on ios, can you make a repro that demonstrates your issue? Thanks! 😄

**Comment by cosf87** [comment]
https://stackblitz.com/edit/angular-v1lbt1?file=demo%2Fcomponent.ts

If you click an event you can see an alert and console.log, but if you toggle device to Ipad Pro in the javascript console, the click event is not fired

Thanks for your help

**Comment by mattlewis92** [comment]
Oh ok I can see the issue on the chrome emulator, but on a real device it works fine. Are you seeing this problem on real devices?

**Comment by cosf87** [comment]
Our customers have issues because of that, specially who are using touch screens or mobile devices

**Comment by mattlewis92** [comment]
But do you know specifically what device they are having troubles on?

**Comment by cosf87** [comment]
For instance, I have an iPad Air (model A1474). On the demo, click event is not fired on draggable items but if an event is not draggable click event is fired.

**Comment by mattlewis92** [comment]
What version of ios does it have?

**Comment by cosf87** [comment]
The last version iOS 12.3.1
I have also tested it on an iPad Pro and it works the same

**Comment by mattlewis92** [comment]
Weird, I have the same version and it works fine for me. Can you try the [demo](https://mattlewis92.github.io/angular-calendar/#/kitchen-sink) on your device and see if it works there? Also are you using hammerjs?

**Comment by cosf87** [comment]
Your default demo works fine on my iPad with draggable and not draggable events, but the demo which I shared with you doesn't work with draggable items. 
I am not using hammerjs. I think the only difference is I am using custom cell template to render custom events

**Comment by mattlewis92** [comment]
Ahh, there's your problem, you need to [include hammerjs](https://github.com/mattlewis92/angular-calendar#does-this-calendar-work-with-mobile) for touch events to work properly.

**Comment by cosf87** [comment]
You're right. I really appreciate your help.
Greetings

**Comment by wendlandreas** [comment]
Seem this issue re-appeared upgrading to Angular 9.
Found some hints that [hammerjs is optional in Angular 9](https://stackoverflow.com/questions/60138639/angular-when-update-from-8-to-9-hammerjs-angular-platform-browser-stopped). 
However, removing hammerjs also causes non-draggable events to stop working.
Any ideas?
