### ISSUE TITLE
Calendar month view open day behavior

### ISSUE THREAD

**Issue by thornblom** [mattlewis92/angular-calendar#1026]
**Is your feature request related to a problem? Please describe**

The default behavior on month view open day box is that you must click twice to open a new date. For example: A date is selected and the open day box is shown (as in the demo), when the user clicks on another date, the old date closes, but does not open the clicked date.

**Describe the solution you'd like**

The user should only need to click once to open a new date.

**Describe your use case for implementing this feature**

The angular-calendar with the month view is a core feature in our application, if this feature is possible it would enchant the user experience.

**Additional context**

If it is a possible way to achieve this without feature implementation, please describe how and close this feature request.

**Comment by mattlewis92** [comment]
This is definitely a bug, thanks for reporting! The issue actually lies in the demo code, so you'll need to adjust your apps code like so: https://github.com/mattlewis92/angular-calendar/commit/5d1ccaa7efd9d2dff2ad784032237fd6d775f799

**Comment by thornblom** [comment]
Thanks, got it!
