### ISSUE TITLE
Display custom template in the expanded view

### ISSUE THREAD

**Issue by TheParad0X** [mattlewis92/angular-calendar#1027]
**Is your feature request related to a problem? Please describe**

No.

**Describe the solution you'd like**

Is is possible to use a custom template for the expanded view?

**Describe your use case for implementing this feature**

I have a custom template that I would like to show in the expanded view of the calendar.

**Additional context**

![image](https://user-images.githubusercontent.com/17595640/60497400-106b6c80-9cb5-11e9-89d7-8db8fdcf5c74.png)

**Comment by mattlewis92** [comment]
You can use [this](https://github.com/mattlewis92/angular-calendar/blob/master/projects/angular-calendar/src/modules/month/calendar-open-day-events.component.ts#L45-L85) as the starting point and then you pass it to the month view though this [input](https://mattlewis92.github.io/angular-calendar/docs/components/CalendarMonthViewComponent.html#openDayEventsTemplate). Hope that helps! 😄
