### ISSUE TITLE
Click on external event

### ISSUE THREAD

**Issue by cosf87** [mattlewis92/angular-calendar#1028]
**Describe the bug**
Hi Matt. I am using hammerjs and click event on calendar item works fine on a touch screen or mobile device. However, click event is not fired when I click on a external event, so I can only drag it.

**Minimal reproduction of the problem with instructions**

**Screenshots**

**Versions**

- `@angular/core`: 8.0.2
- `angular-calendar`: 0.27.12
- Browser name and version: Chrome 75.0.3770.100

**Comment by mattlewis92** [comment]
Can you try using `(mwlClick)` on the events instead of `(click)`? It has a load of fixes to make it work better with hammerjs than the native click event. Thanks!

**Comment by cosf87** [comment]
Hi @mattlewis92, mwlClick event works like a charm. 
Thank you
