### ISSUE TITLE
Kitchen sink multiple open day rows and is always open.

### ISSUE THREAD

**Issue by thornblom** [mattlewis92/angular-calendar#1030]
**Describe the bug**

Month view opens "open day sink" on every row after update to Angular-Calendar 0.27.12 from 0.25.
Open day rows is always open and cannot be closed. 
Seems like the calendar component always wants all of them open, all the time.

**Minimal reproduction of the problem with instructions**

This was my case:
I used angular-calendar 0.25 and @angular/core 6.xx with no issues. 
Now updated to 0.27.12 and @angular/core 8.1.0, and this issue appeared.
No changes in calendar implementation what so ever.
Code is implemented as demo kitchen sink with but with custom templates.

**Screenshots**
![calendarissue](https://user-images.githubusercontent.com/15980818/60644306-fb6a1700-9e35-11e9-9805-2352497b2199.png)

**Versions**

- `@angular/core`: 8.1.0
- `angular-calendar`: 0.27.12
- Browser name and version: Google Chrome 72

**Comment by thornblom** [comment]
Found the breaking change: [@collapse] on custom templates

**Comment by Ashrob07** [comment]
how to show customized card in the kitchen-sink calendar?
