### ISSUE TITLE
Events display on week view 

### ISSUE THREAD

**Issue by osvaldo14** [mattlewis92/angular-calendar#1035]
When the mouse hover an event on calendar. This event come over other html elements

**Screenshots**
![image_2019-07-13_09-48-04](https://user-images.githubusercontent.com/14869063/61168796-a1630300-a553-11e9-9949-18c33fdb9302.png)

**Versions**

- `@angular/core`: 6
- `angular-calendar`: 6
- Browser name and version: latest version google chrome

**Comment by mattlewis92** [comment]
Thanks for opening an issue, would you mind making a stackblitz that reproduces your problem? You can fork a starter template from any of the demos by hitting "Edit in Stackblitz". Thanks! :slightly_smiling_face:

**Comment by osvaldo14** [comment]
Hello sorry for the late anwser. I found a way to fix this. The problem was that the calendar component was in my side bar navigation component. 

Exemple (with the problem) : 
`<mat-sidenav-content>
    <mat-toolbar color="primary">
      <button
        type="button"
        aria-label="Toggle sidenav"
        mat-icon-button
        (click)="drawer.toggle()"
        *ngIf="isHandset$ | async">
        <mat-icon aria-label="Side nav toggle icon">menu</mat-icon>
      </button>
      <span>HEPIA Resource Manager</span>
    </mat-toolbar>
    <app-calendar></app-calendar>
  </mat-sidenav-content>
</mat-sidenav-container>`

So I add a div around the calendar component and create a css class with the following propreties : 

- z-index : -1
- position : relative

And then it worked
