### ISSUE TITLE
How to know which day does my custom "event template" exist?

### ISSUE THREAD

**Issue by Khanbhai1990** [mattlewis92/angular-calendar#1039]
**Describe the bug**
I need to know which day of the week does my "event template" exist in order to do certain calculations. Right now the "event" object doesn't consist which day it belongs to, like in the "day" object past down by "cell template". Does anyone has a solution for this problem?

`<ng-template #eventTemplate let-weekEvent="weekEvent" let-locale="locale">
            {{weekEvent.event.title}}
        </ng-template>`

weekEvent object doesn't have a date object I could utilize for my project.

- `@angular/core`: 7
- `angular-calendar`: 6
- Browser name and version: chrome 
 
Cheer!!

**Comment by Khanbhai1990** [comment]
> Thanks so much for opening an issue! If you'd like me to give priority to answering your issue or would just like to support this project, then please consider [supporting me on Patreon](https://www.patreon.com/mattlewis92)

Done!

**Comment by mattlewis92** [comment]
> > Thanks so much for opening an issue! If you'd like me to give priority to answering your issue or would just like to support this project, then please consider [supporting me on Patreon](https://www.patreon.com/mattlewis92)
> 
> Done!

Thank you so much for backing this project! I really appreciate the donation ❤️ 

> I need to know which day of the week does my "event template" exist in order to do certain calculations. Right now the "event" object doesn't consist which day it belongs to, like in the "day" object past down by "cell template". Does anyone has a solution for this problem?

Just to be clear, this is for events that span multiple days on the week view? So like the one highlighted in red here:
![image](https://user-images.githubusercontent.com/6425649/61393674-65180580-a8b9-11e9-8df4-fe205f1dcef6.png)

**Comment by Khanbhai1990** [comment]
Yes! 
Would love to know if my custom ng template for event template is referring to July 18 or July 19

**Comment by mattlewis92** [comment]
I just added this in `0.27.14` for you! 😄 In your custom event template you can now do `<ng-template let-column="column"> {{ column.date }} </ng-template>`. Let me know if that works for you 😄
