### ISSUE TITLE
 calendar view  shows all the events of today automatically.

### ISSUE THREAD

**Issue by vinay13** [mattlewis92/angular-calendar#104]
When i open calendar view it shows all the events of today w/o clicking on it.

for ex: today is 17 dec and it open all the events of today and then when i move to next month it show all the events of 17 jan. I don't want my calendar to show all events automatically rather it shows events only when clicked.

How i can solve this problem?

**Comment by mattlewis92** [comment]
The open day is controlled through the `activeDayIsOpen` property. Assuming your code is based off the demo component, initialise it to false [here](https://github.com/mattlewis92/angular-calendar/blob/master/demo/demo.component.ts#L150) to set it to closed on load. Then on the increment / decrement / today functions also set it to false to close the open day when changing the date. Hope that helps! 😃
