### ISSUE TITLE
Saving in MatDialogRef is not updating the view

### ISSUE THREAD

**Issue by CharleyGui** [mattlewis92/angular-calendar#1045]
**Describe the bug**

Hello,

I've created another component to add new events though a Dialog.
Unfortunatly, I'm not able to display the new events after the form is submitted.

Here is the stackblitz: https://stackblitz.com/edit/angular-yyq6lr

So the only issue I am facing now is that the view is not refreshed when the new event is added, although the event is saved in the database.

Can you help me out?

Regards,

Charley

**Minimal reproduction of the problem with instructions**

https://stackblitz.com/edit/angular-yyq6lr

**Screenshots**

None

**Versions**

- `@angular/core`: 7.2.0
- `angular-calendar`: 0.27.9
- Browser name and version: Chrome -latest

**Comment by JaxonWright** [comment]
Your StackBlitz does not compile.

**Comment by echotech11** [comment]
Are you calling this.refresh.next() after you have updated the array containing the new event?

**Comment by mattlewis92** [comment]
Hey there, unfortunately with the information provided I wasn't able to reproduce this as the stackblitz doesn't run, if you can make a minimal working version then please reply here with it. Otherwise the advice given by @echotech11 is probably a good place to start 😄
