### ISSUE TITLE
Wrong week date range in calendar header when using week start as middle day of week

### ISSUE THREAD

**Issue by tvbishan** [mattlewis92/angular-calendar#1048]
**Describe the bug**

I am using below code to show week date range in week view header.
```
  <div class="col-md-4 text-center">
    <h3>{{ viewDate | calendarDate: view + 'ViewTitle':locale }}</h3>
  </div>
```
I have configured week view as below.

```
<mwl-calendar-week-view [hourSegments]="2" [weekStartsOn]="4" [viewDate]="viewDate"
	[events]="events" [dayStartHour]="6" [dayEndHour]="18">
</mwl-calendar-week-view>
```
Week start is Thursday and end is Wednesday. Week view calendar show the correct week start and end dates. But header component shows wrong date range for week.

Week range should be **Jul 18 - Jul 24, 2019**. But, as in the below image it displays as **Jul 21 - Jul 27, 2019**

How can I fix this?

**Minimal reproduction of the problem with instructions**

Here is the [Stackblitz](https://stackblitz.com/edit/angular-9hslyv)

**Screenshots**

![image](https://user-images.githubusercontent.com/12027448/61784685-c430c980-ae27-11e9-9bd0-17f9755bef25.png)

**Versions**

- `@angular/core`: 6.1.7
- `angular-calendar`: 0.27.14
- Browser name and version: Google Chrome Version 75.0.3770.142 (Official Build) (64-bit)

**Comment by JaxonWright** [comment]
It would be helpful if you could make a Stackblitz reproducing the issue. You can do so by starting with any of the demo pages, modifying it, and then saving a fork on Stackblitz

**Comment by tvbishan** [comment]
@JaxonWright Here is the [Stackblitz](https://angular-9hslyv.stackblitz.io/)

**Comment by JaxonWright** [comment]
The issue is probably somewhere in the [getWeekViewPeriod method seen here.](https://github.com/mattlewis92/angular-calendar/blob/6ee92ab5dbdc61eb5ccfd0995ea686f2f4ed601b/projects/angular-calendar/src/modules/common/util.ts#L140) I don't know exactly where, though. Will probably look into it more later. Thoughts @mattlewis92 ?

**Comment by mattlewis92** [comment]
You need to pass the `weekStartsOn` as an argument to the `calendarDate` pipe, so that it knows about it:
```
<h3>{{ viewDate | calendarDate:(view + 'ViewTitle'):'en':4 }}</h3>
```

I'll update the docs to make this more clear as it's come up a few times now and it's quite confusing.

**Comment by tvbishan** [comment]
Thanks for the update. With this modification, now show the correct week date range in the header.

**Comment by mattlewis92** [comment]
Awesome! Gonna leave this open for now as a reminder to myself to update the docs.
