### ISSUE TITLE
Angular 2.2.1 Build Issue

### ISSUE THREAD

**Issue by Chuckv01** [mattlewis92/angular-calendar#105]
When running ngc on angular 2.2.1 this error is killing the build:

```
Mac ~/v/app: ionic build --prod

[10:46:50]  ngc started ... 

can't resolve module ./components/day/calendarDayView.component from /Users/c/v/app/node_modules/angular-calendar/dist/esm/src/calendar.module.d.ts
[10:46:53]  build prod failed: Cannot read property 'CalendarDayViewComponent' of undefined, resolving symbol 
            CalendarModule in 
            /Users/c/v/app/node_modules/angular-calendar/dist/esm/src/calendar.module.d.ts, 
            resolving symbol CalendarModule in 
            /Users/c/v/app/node_modules/angular-calendar/dist/esm/src/calendar.module.d.ts 
[10:46:53]  ionic-app-script task: "build" 
[10:46:53]  Error: Cannot read property 'CalendarDayViewComponent' of undefined, resolving symbol CalendarModule in 
            /Users/c/v/app/node_modules/angular-calendar/dist/esm/src/calendar.module.d.ts, 
            resolving symbol CalendarModule in 
            /Users/c/v/app/node_modules/angular-calendar/dist/esm/src/calendar.module.d.ts 
```

Is it currently compatible with angular 2.2.1? Thank you for the work you've put into this!

**Comment by mattlewis92** [comment]
I think this is probably more an issue with the ionic app scripts, as this is working fine for me with normal AoT compilation. Would you be able to put together a minimal repo that reproduces your issue? Thanks!

Also what version of the library + ionic app scripts are you using?

**Comment by Chuckv01** [comment]
I'm running version 0.5.0 of angular-calendar. 0.0.47 on ionic app scripts.

Here my Ionic info:

```
Cordova CLI: 6.3.0 
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.47
ios-deploy version: 1.9.0 
ios-sim version: 5.0.8 
OS: macOS Sierra
Node Version: v6.7.0
Xcode version: Xcode 8.2 Build version 8C38
```

Sure I'll put together a repo for you. Thanks for the quick response!

**Comment by Chuckv01** [comment]
Here is the repo: https://github.com/Chuckv01/angular-calendar-ionic2-issue-repo

**Comment by Chuckv01** [comment]
I think you are right. This is related to Ionic 2's app-scripts. I see a ticket on that repo with a very similar error: https://github.com/driftyco/ionic-app-scripts/issues/550

Still have no idea what is causing it though. -_-

**Comment by mattlewis92** [comment]
I've added [a reply](https://github.com/driftyco/ionic-app-scripts/issues/550#issuecomment-268475701) to the ionic app scripts issue that should hopefully help point them in the right direction to fixing the problem. I'm closing this issue as there is nothing actionable for me here.

**Comment by Chuckv01** [comment]
@mattlewis92 Appreciate it! I've tried forking angular-calendar and manually adding the exports, but no luck yet, ngc keeps failing on the dependencies of the angular dragAndDrop module. I am at a loss as to how I can workaround this.

Would you by chance know what needs to be changed in app-scripts to get dependencies to resolve properly?

**Comment by Chuckv01** [comment]
Update: Well I added these exports to your `angular-draggable-droppable` index.js

```
export * from './droppable.directive';
export * from './draggable.directive';
```

And it now passes ngc compilation! Haaacky but it works!

**Comment by mattlewis92** [comment]
Looking at that issue you could solve it temporarily by downgrading to 0.0.45 of ionic-app-scripts rather than having to fork the repo and its dependencies.

**Comment by trabdin** [comment]
I'm using version 1.0.0 of ionic-app-scripts and am also getting this issue. I tried adding those two exports to angular-draggable-droppable but still got the same fail message. Any ideas of any possible workarounds for this issue? Thanks!

**Comment by mattlewis92** [comment]
The best workaround I can recommend is to downgrade ionic app scripts to 0.0.45 and bump the issue in the hopes that the ionic team fix it their end. This problem will affect all 3rd party so I can't imagine them not wanting to fix it.

**Comment by trabdin** [comment]
Thanks. I tried downgrading but got the following error when building with --prod:

can't resolve module ./components/day/calendarDayView.component

Any ideas?

**Comment by mattlewis92** [comment]
The only thing I can recommend is asking them to fix the issues in their build process.
