### ISSUE TITLE
+Show More events option in the month view day cell

### ISSUE THREAD

**Issue by preetscorp** [mattlewis92/angular-calendar#1051]
**Is your feature request related to a problem? Please describe**
I am using angular-calendar with a custom template as given here : https://mattlewis92.github.io/angular-calendar/#/custom-templates,

For the month - view i would like to have a "Show more" option which will load more events in the day cell. By default i want to have only 4 events listed on the day cell. Something similar to google calendar.

The main reason i want this , we expect more than 10 events to be loaded per day in the month view, and i am showing them all as is like in google calendar month view. When we have more events, the month view gets too crowded. Hence a +6 more events would help me in this case.

**Describe the solution you'd like**
A +6 more events would help me in this case. Something similar to the month view of google calendar

**Comment by JaxonWright** [comment]
This seems to be something that you should implement, and then consider contributing via pull request to the main library.

**Comment by zzmmbb** [comment]
By customizing the template, this is very simple

**Comment by mattlewis92** [comment]
I think this is something better to implement in userland with a custom template for the month cell, something like this: https://stackblitz.com/edit/angular-f1ag1e?file=demo/template.html

**Comment by TheInlineProject** [comment]
Hi mattlewis92,
But how do you distinguish between cell and cell?
If I add to the set of events, other events that happen on another day,
like 4 events: { start: addDays(startOfDay(new Date()), 1), title: 'different date' }
clicking on a specific date causes all dates to expand.

**Comment by DanielTalX** [comment]
Hi, but how do you distinguish between cell and cell?
If I add to the set of events, other events that happen on different date, clicking on a specific date causes all dates to expand.
4 events like: 
` {
      start: addDays(startOfDay(new Date()), 1),
      title: 'different date'
    }`

**Comment by preetscorp** [comment]
@DanielTalX 
You can try this that worked for me: https://stackoverflow.com/questions/57196544/angular-calendar-having-a-show-more-options-to-load-more-events-in-a-day-cell-of

**Comment by DanielTalX** [comment]
> @DanielTalX
> You can try this that worked for me: https://stackoverflow.com/questions/57196544/angular-calendar-having-a-show-more-options-to-load-more-events-in-a-day-cell-of

Thaks It's a good idea, but I wanted to I want to display the events on the calendar itself without popup.
I did it, and posted my answer on the link you sent me.
here: [https://stackoverflow.com/a/61025948/13218355](url)

**Comment by hockbeng97** [comment]
@DanielTalX 

Your way will show all the "more events" on all date, but not the particular date you clicked
