### ISSUE TITLE
Using CustomEventTitleFormatter in a day view scheduler correctly.

### ISSUE THREAD

**Issue by notsure** [mattlewis92/angular-calendar#1053]
Hi,

I am following this documentation:
https://mattlewis92.github.io/angular-calendar/#/day-view-scheduler

----

**What I would like to do:**

Display a days schedule for all people and their events. The look and feel should be like the week view, where each day is nicely separated by table like borders. Also I would like to restyle the event title template. Which is usually possible by using a "CustomEventTitleFormatter".

**What is the problem**

How to use the "CustomEventTitleFormatter" with the demo quoted above? The custom "DayViewSchedulerComponent" seems not to accept two providers or just doesn't trigger the correct behaviour

**Screenshots**

_How I assume the events should look:_
![Screen Shot 2019-07-30 at 11 32 18](https://user-images.githubusercontent.com/922237/62119578-30944880-b2c0-11e9-899a-1c749695d03c.png)

_How they actually look:_
![Screen Shot 2019-07-30 at 11 32 10](https://user-images.githubusercontent.com/922237/62119577-30944880-b2c0-11e9-93d4-b2ed388c4919.png)

**Versions**

- `@angular/core`: 7.1.0
- `angular-calendar`: 0.26.6

**Comment by tjoudeh** [comment]
Hello @notsure can you please guide me how you were able to customize the title, I want to have something similar to your design, like to have a title on a line, then another line which shows more information about the event (event details.)

Thank you

**Comment by gauravtmavens** [comment]
> Hello @notsure can you please guide me how you were able to customize the title, I want to have something similar to your design, like to have a title on a line, then another line which shows more information about the event (event details.)
> 
> Thank you

Hi tjoudeh, I'm facing the same issue have you solved this issue if yes then please help me with this issue.

Thank you

**Comment by notsure** [comment]
Hi folks,

sorry for kept you waiting. I was on holiday and somehow my notifications didn't send me an email...

here is a Link just add a CustomTitleFormatter to your component and you are ready to go. 

https://stackblitz.com/edit/angular-dfnhq3

Let me know if you got it working.
