### ISSUE TITLE
Not possible to change background cell color in month view?

### ISSUE THREAD

**Issue by JarLowrey** [mattlewis92/angular-calendar#1060]
**Describe the bug**

I have been reading old issues and haven't seen a way to change the background color of any given day's cell when in calendar month view. Even the weekend color isn't working when included at the top of my TS component.

   ```
@Component({
  selector: 'CMCalendar',
  templateUrl: './CMCalendar.component.html',
  styles: [`
    .cal-day-weekend {
      background-color: gray !important;
    }
  `]
})
```

**Versions**

- `@angular/core`: 7.1.3
- `angular-calendar`: 0.27.15
- Browser name and version: Chrome

**Comment by JarLowrey** [comment]
Looks like it can be done with `beforeViewRender`:  https://mattlewis92.github.io/angular-calendar/#/before-view-render

**Comment by abhisarvaiya21** [comment]
> Looks like it can be done with `beforeViewRender`: https://mattlewis92.github.io/angular-calendar/#/before-view-render

IT WORKS THANKS....
