### ISSUE TITLE
Issue when dropping data on line between timeslot

### ISSUE THREAD

**Issue by ALapaque** [mattlewis92/angular-calendar#1062]
**Describe the bug**

Hi @mattlewis92 first I wanted to thank you for such a great calendar !

I've experienced an issue when I'm dropping data into to the calendar, somehow people are able to trigger the drop on the line between two time slots and it creates two events.
How could we manage and avoid that ?

Here below you can see the reproduction of the issue

**Minimal reproduction of the problem with instructions**

Get dragable data and drop it on the line between two time slots

**Screenshots**

![timeSlots](https://user-images.githubusercontent.com/46450511/63149496-a4df2380-c004-11e9-96fb-e7292cf3f661.gif)

**Versions**

- `@angular/core`:7.2.2
- `angular-calendar`:0.27.7
- Browser name and version: Chrome Version 76.0.3809.100 (Build officiel) (64 bits)

**Comment by mattlewis92** [comment]
Oh how weird, I can't think of a nice solution to this right now, but in the meantime you could use a debounce on the function call to prevent it yourself: https://stackblitz.com/edit/angular-yg9dnf?file=demo/component.ts

**Comment by ALapaque** [comment]
Hi @mattlewis92,

Thank you for your answer I'll try that ASAP and of course I'll let you know if it fixed my issue.

**Comment by mattlewis92** [comment]
I managed to find a fix for this, and it's in the next beta, you can try it with:
```
npm i angular-calendar@next
```

Hope that helps! 😄

**Comment by ALapaque** [comment]
Hi @mattlewis92 

Well thank you very much for such a quick fix for this issue.
This works perfectly

Thanks :)

**Comment by ALapaque** [comment]
Any date for a next release ? :D

**Comment by mattlewis92** [comment]
The last thing to do before I release 0.28 as stable is https://github.com/mattlewis92/angular-calendar/issues/888, but there are no more changes planned for the component itself, so please consider the beta version as being stable 😄

**Comment by ALapaque** [comment]
Great ! thanks again :)
