### ISSUE TITLE
Upgrade to date-fns v2

### ISSUE THREAD

**Issue by mattlewis92** [mattlewis92/angular-calendar#1064]
As it ships ES modules we can finally remove all the deep imports and just import directly from `date-fns` 🎉

**Comment by Enngage** [comment]
Awesome! Just tried updating date-fns and came to this repo to see if there are any plans for this :-)

**Comment by mattlewis92** [comment]
I'll try and get a beta out with it this week 😄

**Comment by mattlewis92** [comment]
I just published a new beta with date-fns v2, please upgrade and try it today with:
```
npm i angular-calendar@next
```

**Comment by Enngage** [comment]
Just tried `0.28.0-beta.1` and it seems to work perfectly fine :-)

**Comment by mattlewis92** [comment]
Awesome, thanks for testing it @Enngage! 😄

**Comment by adisco4420** [comment]
> I just published a new beta with date-fns v2, please upgrade and try it today with:
> 
> ```
> npm i angular-calendar@next
> ```

I just tried if for Angular 7 and it working perfectly Thanks so much

**Comment by Danieliverant** [comment]
@mattlewis92 
Thanks!!! 
works perfectly on Angular 8.

if someone has errors using full-calendar v2 with date-fns v2 upgrade to the beta:
https://github.com/date-fns/date-fns/issues/1394

**Comment by sysmat** [comment]
I have problem with new date-fns.

* dependencies:

```
"@angular-devkit/core": "8.3.5",
"@angular-devkit/schematics": "8.3.5",
"@angular/common": "8.2.7",
"@angular/compiler": "8.2.7",
"@angular/core": "8.2.7",
"angular-calendar": "0.28.0-beta.4",
"date-fns": "2.2.1",
```
* devDependencies:

```
"@angular-devkit/build-angular": "0.803.5",
"@angular/cli": "8.3.5",
"@angular/compiler-cli": "8.2.7",

```

* NO IVY compiler
* app.module:

```
CalendarModule.forRoot({
      provide: DateAdapter,
      useFactory: adapterFactory
    })

```
* Error:
```

ERROR in Can't bind to 'eventWidth' since it isn't a known property of 'mwl-calendar-day-view'.
1. If 'mwl-calendar-day-view' is an Angular component and it has 'eventWidth' input, then verify that it is part of this module.
2. If 'mwl-calendar-day-view' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("    [viewDate]="viewDate"
                           [events]="events"
                           [ERROR ->][eventWidth]="900"
                           dayEndHour="20"
                           [refresh]=")
```

Regards, Tomaž

**Comment by mattlewis92** [comment]
@sysmat please check the breaking changes over at https://github.com/mattlewis92/angular-calendar/pull/1070, `eventWidth` was removed as events now fill the available width.

**Comment by sysmat** [comment]
@mattlewis92 thx it works with beta version

**Comment by tom-englert** [comment]
@mattlewis92 I had the same problem - shouldn't the date adapter implementations be shipped as a separate module, so angular-calendar has NO dependency to any date library?
This would solve all future conflicts, and users could use ANY version of any date library with the calendar.

**Comment by mattlewis92** [comment]
@tom-englert date adapters essentially are already separate modules, but just included in the `angular-calendar` package as sub modules for convenience so you don't have to npm install even more stuff e.g.

```
import { adapterFactory } from 'angular-calendar/date-adapters/date-fns';
```
and 
```
import { adapterFactory } from 'angular-calendar/date-adapters/moment';
```

The only real benefit having them as separate packages would get you is that you could add peer dependencies to date-fns and moment respectively, but that will mostly be solved with [optional peer dependencies](https://github.com/npm/cli/pull/224), and they would have separate versioning from the main package so I could have already released the date-fns v2 adapter as stable already (but you can already use the next version of the calendar with `npm i angular-calendar@next` that has date-fns v2.)

**Comment by tom-englert** [comment]
I see, I think I had missed a stale import of the date-fns adapter in my code, that's why I got the compile error.
