### ISSUE TITLE
Hide days in weekview which have no appointments

### ISSUE THREAD

**Issue by dmnktoe** [mattlewis92/angular-calendar#1068]
**Is your feature request related to a problem? Please describe**

Short question: I want to display available appointments via an API in my calendar. Is there anyway to just hide the days in the weekview which represent no appointments in general?

**Describe the solution you'd like**

**Describe your use case for implementing this feature**

**Additional context**

**Comment by mattlewis92** [comment]
Sure thing, you can use the `beforeViewRender` hook to then set `excludeDays` to be any days that don't have events. I put together a demo for you here: https://stackblitz.com/edit/angular-x2mhhh?file=demo/component.ts Hope that helps! 😄
