### ISSUE TITLE
Feature request: make dates selectable

### ISSUE THREAD

**Issue by ogix** [mattlewis92/angular-calendar#107]
Very nice library but I miss date selection in month view.

**Comment by mattlewis92** [comment]
Sorry I don't quite follow you, could you expand on your use case a bit more please? Thanks!

**Comment by ogix** [comment]
Thank you for your reply. I want to be able to select a date which does not have events yet so that I could show a button "add event" for example. It isn't possible now, right?

**Comment by mattlewis92** [comment]
Just so we're on the same page, you want to implement something like this?
<img width="1195" alt="screen shot 2016-12-23 at 22 41 55" src="https://cloud.githubusercontent.com/assets/6425649/21463438/154b8d7c-c961-11e6-8917-f3737cbd1526.png">

**Comment by ogix** [comment]
Yes, so if you click on 5th date it stays highlighted. I guess it should not be hard to implement this. Thanks again!

**Comment by mattlewis92** [comment]
You should be able to implement this using the [`dayClicked` output](https://mattlewis92.github.io/angular-calendar/docs/classes/calendarmonthviewcomponent.html#dayclicked):

```html
(dayClicked)="dayClicked($event.day)"
```

```typescript
dayClicked(day) {
  if (this.selectedDay) {
   delete this.selectedDay.cssClass;
  }
  day.cssClass = 'cal-day-selected';
  this.selectedDay = day;
}
```

// Make sure to apply this globally and not add it in your components styles.
```css
.cal-day-selected {
  background-color: green;
}
```

Hope that helps!

**Comment by ogix** [comment]
Thank you! This works but if I add `this.viewDate = day.date` then it does not add the class

**Comment by cynrichuys** [comment]
@mattlewis92 I'm actually having the same problem as @ogix. The function above works but as soon as the `viewDate` is updated as well the class disappears (in fact becomes `undefined` in the DOM). Any ideas about this?

**Comment by mattlewis92** [comment]
Good point, I've [updated the demo](https://mattlewis92.github.io/angular-calendar/#/selectable-month-day) to show how you can use the dayModifier option to re-select the class when the view updates.

**Comment by atejadac** [comment]
Sorry to bother you, @mattlewis92 , but I haven't found the **dayModifier** option you mention in your last answer. I have exactly the same problem as @cynrichuys and @ogix : when I do the _day.cssClass = "myClass"_ it works fine, but when I do _this.viewDate = day.Date_ it does not work.

Thank you in advance.
