### ISSUE TITLE
No click action available for calendar items in month and week view

### ISSUE THREAD

**Issue by timoberlin** [mattlewis92/angular-calendar#1078]
**Describe the bug**

We are using angular-calendar within our Angular 6 application. When using Firefox for PC (latest version), in a non-deterministic way, it is not possible to click on a calendar item. This problem in general occurs, when navigating between the app and opening the to-do-calendar again. 

Normal calendar view:
<img width="531" alt="normal_view" src="https://user-images.githubusercontent.com/2080312/64026382-f2987780-cb3e-11e9-8222-5002ef4bad43.png">

Calendar view not working:
<img width="331" alt="not_working" src="https://user-images.githubusercontent.com/2080312/64026429-0b089200-cb3f-11e9-9f53-ddbfb640f89c.png">

**Minimal reproduction of the problem with instructions**

**Screenshots**

**Versions**

- "@angular/core": "^6.1.10",
- "angular-calendar": "0.27.18",
- Browser name and version: Firefox PC 68.0.2

**Comment by mattlewis92** [comment]
Hey, sorry to hear you're having issues, I'm not able to reproduce this on the demo on firefox though, can you provide a minimal repro of the problem? Thanks!
