### ISSUE TITLE
Add an n-days view

### ISSUE THREAD

**Issue by vova1987** [mattlewis92/angular-calendar#1081]
**Is your feature request related to a problem? Please describe**

It is common in all existing calendar views (google-calendar, samsung-calendar) to have a view of n days - e.g. 3 days instead of a full week or a single day view.

**Describe the solution you'd like**

I would like a new view that would allow to display n days. 
Looking at the implementation of the week-view - I guess only minor modifications would be required
**Describe your use case for implementing this feature**
Since my application is a mobile app, the week view is a bit too large for me and the day view is too small - so a 3 day view would be a perfect middle ground.

**Additional context**

**Comment by mattlewis92** [comment]
Please have a look at the `daysInWeek` option on the week view which you can use to provide this functionality: https://mattlewis92.github.io/angular-calendar/docs/components/CalendarWeekViewComponent.html#daysInWeek

**Comment by vova1987** [comment]
I did try the daysInWeek option. It does not solve the problem since when
it is set we never see the rest of the days - even when moving
backwards/forwards.
e.g. if I set it to 3 - I will forever only see Sunday through Tudesay,
although the requirement is to see Sunday-Tuesday and then Wednesday-Friday

**Comment by mattlewis92** [comment]
Are you passing it to the previous and next view directives as well? e.g. like this: https://stackblitz.com/edit/angular-ztvd1z?file=demo%2Ftemplate.html
