### ISSUE TITLE
exclude hour segment of a day or multiple days

### ISSUE THREAD

**Issue by ALapaque** [mattlewis92/angular-calendar#1082]
**Is your feature request related to a problem? Please describe**

I'm facing a problem I need to be able to plan different start & end date for a day in a week view.

- Monday : 8am → 12am 1pm → 6pm
- Wednesday: 6am → 10am → 1pm → 3pm
- Friday: 9am → 1pm → 4pm → 9pm

![plage-horraire](https://user-images.githubusercontent.com/46450511/64097801-7764da80-cd65-11e9-86f8-d469b8bfdd8f.png)

**Describe the solution you'd like**

We already have the [excludeDays] which takes  a array of number to disable the display of the days.
But could we have something like [excludeHourSegmentPerDay] and this one will take an array with that following structure :

- [excludeHourSegmentPerDay] = 
     [{ dayNumber : x 'from 0 to 6'
           excludedSegment : [{
              startHour : 8,
              startMinute : 15,
              endHour : 9,
              endMinute : 45},{
              startHour : 12,
              startMinute : 15,
              endHour : 13,
              endMinute : 45
          },{ dayNumber : x 'from 0 to 6'
           excludedSegment : [{
              startHour : 8,
              startMinute : 15,
              endHour : 9,
              endMinute : 45},{
              startHour : 12,
              startMinute : 15,
              endHour : 13,
              endMinute : 45
     }];

**Describe your use case for implementing this feature**

Multiple agenda per person. and dispalying it at the sametime.

**Additional context**

What do you think about this ?

**Comment by mattlewis92** [comment]
I think you should already be able to do this with the `beforeViewRender` output: https://mattlewis92.github.io/angular-calendar/#/before-view-render Please let me know if that works for you 😄

**Comment by ALapaque** [comment]
great !

Thank you very much.

Le lun. 2 sept. 2019 à 13:41, Matt Lewis <notifications@github.com> a
écrit :
