### ISSUE TITLE
Change first and last day color of a multiple days event 

### ISSUE THREAD

**Issue by dmnktoe** [mattlewis92/angular-calendar#1084]
**Is your feature request related to a problem? Please describe**

Hey! Still in love with Angular Calendar and ran into another question, as the title says, is there any way to change first and last day background-color (in month view) of a multiple days event? 

**Describe the solution you'd like**

**Describe your use case for implementing this feature**

**Additional context**

**Comment by mattlewis92** [comment]
You can use the `beforeMonthViewRender` output to achieve this by looking at if the event spans multiple days and then modifying the event to change the background color, a bit like this: https://stackblitz.com/edit/angular-trrnxc?file=demo/component.ts

Hope that helps! 😄
