### ISSUE TITLE
Update date-fns to v2

### ISSUE THREAD

**Issue by bostondevin** [mattlewis92/angular-calendar#1090]
Update date-fns to use the latest v2

getting errors when updating date-fns using angular calendar

ERROR in C:/Users/de349/websites/mgx-ui/node_modules/calendar-utils/date-adapters/date-fns/index.js
Module not found: Error: Can't resolve 'date-fns/add_days/index' in 'C:\Users\de349\websites\mgx-ui\node_modules\calendar-utils\date-adapters\date-fns'
ERROR in C:/Users/de349/websites/mgx-ui/node_modules/calendar-utils/date-adapters/date-fns/index.js
Module not found: Error: Can't resolve 'date-fns/add_hours/index' in 'C:\Users\de349\websites\mgx-ui\node_modules\calendar-utils\date-adapters\date-fns'
ERROR in C:/Users/de349/websites/mgx-ui/node_modules/calendar-utils/date-adapters/date-fns/index.js
Module not found: Error: Can't resolve 'date-fns/add_minutes/index' in 'C:\Users\de349\websites\mgx-ui\node_modules\calendar-utils\date-adapters\date-fns'
ERROR in C:/Users/de349/websites/mgx-ui/node_modules/angular-calendar/date-adapters/date-fns/index.js
Module not found: Error: Can't resolve 'date-fns/add_months/index' in 'C:\Users\de349\websites\mgx-ui\node_modules\angular-calendar\date-adapters\date-fns'
ERROR in C:/Users/de349/websites/mgx-ui/node_modules/calendar-utils/date-adapters/date-fns/index.js
Module not found: Error: Can't resolve 'date-fns/add_seconds/index' in 'C:\Users\de349\websites\mgx-ui\node_modules\calendar-utils\date-adapters\date-fns'
ERROR in C:/Users/de349/websites/mgx-ui/node_modules/angular-calendar/date-adapters/date-fns/index.js
Module not found: Error: Can't resolve 'date-fns/add_weeks/index' in 'C:\Users\de349\websites\mgx-ui\node_modules\angular-calendar\date-adapters\date-fns'
ERROR in C:/Users/de349/websites/mgx-ui/node_modules/calendar-utils/date-adapters/date-fns/index.js
Module not found: Error: Can't resolve 'date-fns/difference_in_days/index' in 'C:\Users\de349\websites\mgx-ui\node_modules\calendar-utils\date-adapters\date-fns'
ERROR in C:/Users/de349/websites/mgx-ui/node_modules/calendar-utils/date-adapters/date-fns/index.js
Module not found: Error: Can't resolve 'date-fns/difference_in_minutes/index' in 'C:\Users\de349\websites\mgx-ui\node_modules\calendar-utils\date-adapters\date-fns'
ERROR in C:/Users/de349/websites/mgx-ui/node_modules/calendar-utils/date-adapters/date-fns/index.js
Module not found: Error: Can't resolve 'date-fns/difference_in_seconds/index' in 'C:\Users\de349\websites\mgx-ui\node_modules\calendar-utils\date-adapters\date-fns'
ERROR in C:/Users/de349/websites/mgx-ui/node_modules/calendar-utils/date-adapters/date-fns/index.js
Module not found: Error: Can't resolve 'date-fns/end_of_day/index' in 'C:\Users\de349\websites\mgx-ui\node_modules\calendar-utils\date-adapters\date-fns'
ERROR in C:/Users/de349/websites/mgx-ui/node_modules/calendar-utils/date-adapters/date-fns/index.js
Module not found: Error: Can't resolve 'date-fns/end_of_month/index' in 'C:\Users\de349\websites\mgx-ui\node_modules\calendar-utils\date-adapters\date-fns'
ERROR in C:/Users/de349/websites/mgx-ui/node_modules/calendar-utils/date-adapters/date-fns/index.js
Module not found: Error: Can't resolve 'date-fns/end_of_week/index' in 'C:\Users\de349\websites\mgx-ui\node_modules\calendar-utils\date-adapters\date-fns'
ERROR in C:/Users/de349/websites/mgx-ui/node_modules/angular-calendar/date-adapters/date-fns/index.js
Module not found: Error: Can't resolve 'date-fns/get_date/index' in 'C:\Users\de349\websites\mgx-ui\node_modules\angular-calendar\date-adapters\date-fns'
ERROR in C:/Users/de349/websites/mgx-ui/node_modules/calendar-utils/date-adapters/date-fns/index.js
Module not found: Error: Can't resolve 'date-fns/get_day/index' in 'C:\Users\de349\websites\mgx-ui\node_modules\calendar-utils\date-adapters\date-fns'
ERROR in C:/Users/de349/websites/mgx-ui/node_modules/calendar-utils/date-adapters/date-fns/index.js
Module not found: Error: Can't resolve 'date-fns/get_hours/index' in 'C:\Users\de349\websites\mgx-ui\node_modules\calendar-utils\date-adapters\date-fns'
ERROR in C:/Users/de349/websites/mgx-ui/node_modules/angular-calendar/date-adapters/date-fns/index.js
Module not found: Error: Can't resolve 'date-fns/get_iso_week/index' in 'C:\Users\de349\websites\mgx-ui\node_modules\angular-calendar\date-adapters\date-fns'
ERROR in C:/Users/de349/websites/mgx-ui/node_modules/calendar-utils/date-adapters/date-fns/index.js
Module not found: Error: Can't resolve 'date-fns/get_minutes/index' in 'C:\Users\de349\websites\mgx-ui\node_modules\calendar-utils\date-adapters\date-fns'
ERROR in C:/Users/de349/websites/mgx-ui/node_modules/calendar-utils/date-adapters/date-fns/index.js
Module not found: Error: Can't resolve 'date-fns/get_month/index' in 'C:\Users\de349\websites\mgx-ui\node_modules\calendar-utils\date-adapters\date-fns'
ERROR in C:/Users/de349/websites/mgx-ui/node_modules/angular-calendar/date-adapters/date-fns/index.js
Module not found: Error: Can't resolve 'date-fns/get_year/index' in 'C:\Users\de349\websites\mgx-ui\node_modules\angular-calendar\date-adapters\date-fns'
ERROR in C:/Users/de349/websites/mgx-ui/node_modules/calendar-utils/date-adapters/date-fns/index.js
Module not found: Error: Can't resolve 'date-fns/is_same_day/index' in 'C:\Users\de349\websites\mgx-ui\node_modules\calendar-utils\date-adapters\date-fns'
ERROR in C:/Users/de349/websites/mgx-ui/node_modules/calendar-utils/date-adapters/date-fns/index.js
Module not found: Error: Can't resolve 'date-fns/is_same_month/index' in 'C:\Users\de349\websites\mgx-ui\node_modules\calendar-utils\date-adapters\date-fns'
ERROR in C:/Users/de349/websites/mgx-ui/node_modules/calendar-utils/date-adapters/date-fns/index.js
Module not found: Error: Can't resolve 'date-fns/is_same_second/index' in 'C:\Users\de349\websites\mgx-ui\node_modules\calendar-utils\date-adapters\date-fns'
ERROR in C:/Users/de349/websites/mgx-ui/node_modules/angular-calendar/date-adapters/date-fns/index.js
Module not found: Error: Can't resolve 'date-fns/set_date/index' in 'C:\Users\de349\websites\mgx-ui\node_modules\angular-calendar\date-adapters\date-fns'
ERROR in C:/Users/de349/websites/mgx-ui/node_modules/calendar-utils/date-adapters/date-fns/index.js
Module not found: Error: Can't resolve 'date-fns/set_hours/index' in 'C:\Users\de349\websites\mgx-ui\node_modules\calendar-utils\date-adapters\date-fns'
ERROR in C:/Users/de349/websites/mgx-ui/node_modules/calendar-utils/date-adapters/date-fns/index.js
Module not found: Error: Can't resolve 'date-fns/set_minutes/index' in 'C:\Users\de349\websites\mgx-ui\node_modules\calendar-utils\date-adapters\date-fns'
ERROR in C:/Users/de349/websites/mgx-ui/node_modules/angular-calendar/date-adapters/date-fns/index.js
Module not found: Error: Can't resolve 'date-fns/set_month/index' in 'C:\Users\de349\websites\mgx-ui\node_modules\angular-calendar\date-adapters\date-fns'
ERROR in C:/Users/de349/websites/mgx-ui/node_modules/angular-calendar/date-adapters/date-fns/index.js
Module not found: Error: Can't resolve 'date-fns/set_year/index' in 'C:\Users\de349\websites\mgx-ui\node_modules\angular-calendar\date-adapters\date-fns'
ERROR in C:/Users/de349/websites/mgx-ui/node_modules/calendar-utils/date-adapters/date-fns/index.js
Module not found: Error: Can't resolve 'date-fns/start_of_day/index' in 'C:\Users\de349\websites\mgx-ui\node_modules\calendar-utils\date-adapters\date-fns'
ERROR in C:/Users/de349/websites/mgx-ui/node_modules/calendar-utils/date-adapters/date-fns/index.js
Module not found: Error: Can't resolve 'date-fns/start_of_minute/index' in 'C:\Users\de349\websites\mgx-ui\node_modules\calendar-utils\date-adapters\date-fns'
ERROR in C:/Users/de349/websites/mgx-ui/node_modules/calendar-utils/date-adapters/date-fns/index.js
Module not found: Error: Can't resolve 'date-fns/start_of_month/index' in 'C:\Users\de349\websites\mgx-ui\node_modules\calendar-utils\date-adapters\date-fns'
ERROR in C:/Users/de349/websites/mgx-ui/node_modules/calendar-utils/date-adapters/date-fns/index.js
Module not found: Error: Can't resolve 'date-fns/start_of_week/index' in 'C:\Users\de349\websites\mgx-ui\node_modules\calendar-utils\date-adapters\date-fns'
ERROR in C:/Users/de349/websites/mgx-ui/node_modules/angular-calendar/date-adapters/date-fns/index.js
Module not found: Error: Can't resolve 'date-fns/sub_days/index' in 'C:\Users\de349\websites\mgx-ui\node_modules\angular-calendar\date-adapters\date-fns'
ERROR in C:/Users/de349/websites/mgx-ui/node_modules/angular-calendar/date-adapters/date-fns/index.js
Module not found: Error: Can't resolve 'date-fns/sub_months/index' in 'C:\Users\de349\websites\mgx-ui\node_modules\angular-calendar\date-adapters\date-fns'
ERROR in C:/Users/de349/websites/mgx-ui/node_modules/angular-calendar/date-adapters/date-fns/index.js
Module not found: Error: Can't resolve 'date-fns/sub_weeks/index' in 'C:\Users\de349\websites\mgx-ui\node_modules\angular-calendar\date-adapters\date-fns'

**Describe the bug**

**Minimal reproduction of the problem with instructions**

**Screenshots**

**Versions**

- `@angular/core`:
- `angular-calendar`:
- Browser name and version:

**Comment by mattlewis92** [comment]
Please see https://github.com/mattlewis92/angular-calendar/issues/1064#issuecomment-524364809, thanks! 😄
