### ISSUE TITLE
bug on dayClicked 

### ISSUE THREAD

**Issue by PavelGorodetchi** [mattlewis92/angular-calendar#1091]
**Describe the bug**

when I click on cell (I call dayClicked method) I do http request to get data from db and after I got data, I set activeDayIsOpen as true; but my openDayEventsTemplate doesn't opening , but activeDayIsOpen is true already 

**Minimal reproduction of the problem with instructions**

**Screenshots**
![image](https://user-images.githubusercontent.com/42777048/64687709-b399e880-d493-11e9-98b2-00623b754b91.png)

**Versions**

- `@angular/core`: latest version
- `angular-calendar`: latest version
- Browser name and version: Chrome 76

**Comment by PavelGorodetchi** [comment]
openDayEventsTemplate is opening after I do click on cell second time

**Comment by mattlewis92** [comment]
Please can you provide a runnable stackblitz that demonstrates your problem (you can fork one from any of the demos), as without this it's impossible to know what the issue is. Thank you!

**Comment by PavelGorodetchi** [comment]
Sorry, i cant to show it on stackblitz, because i get data from the local server; Okey, i have next question: After i clicked on the cell day (i call dayClicked method), how i can to display template (openDayEventsTemplate) after some seconds (or some time)? If i use this method, it is not working: 

====================================== html
<div *ngIf="events$ | async; else loading; let events">
    <div [ngSwitch]="view">
      <mwl-calendar-month-view
        *ngSwitchCase="CalendarView.Month"
        [viewDate]="viewDate"
        [events]="events"
        [refresh]="refresh"
        [activeDayIsOpen]="activeDayIsOpen"
        [cellTemplate]="customCellTemplate"
        [openDayEventsTemplate]="customOpenDayEventsTemplate"
        (dayClicked)="dayClicked($event.day)"
        (eventTimesChanged)="eventTimesChanged($event)"
      >
      </mwl-calendar-month-view>
============================================ ts 

dayClicked({ date, events }: { date: Date; events: CalendarEvent[] }): void { 
    setTimeout(() => {
      this.activeDayIsOpen = true;
    }, 3000)
}


Thank you in advance

**Comment by PavelGorodetchi** [comment]
Demo example:

https://stackblitz.com/edit/angular6-calendar-qbqked?file=demo%2Fcomponent.ts

**Comment by mattlewis92** [comment]
Thanks for that, I see the problem now! When you use `OnPush` change detection, angular doesn't run change detection inside async events like setTimeout or http calls so you need to inject `ChangeDetectorRef` and run `this.cdr.markForCheck()` to manually run change detection. Heres your demo fixed: https://stackblitz.com/edit/angular6-calendar-wc9de8?file=demo/component.ts Hope that helps! 😄

**Comment by PavelGorodetchi** [comment]
Thank you very much 👍 It's working

**Comment by PavelGorodetchi** [comment]
I can to ask: How to create ( or build ) a javascript framework like this. I would like to try create a framework. There is any a guide book (how to create or build framework)?

**Comment by PavelGorodetchi** [comment]
Anyway, thank you very much for solution ))
