### ISSUE TITLE
Prevent viewRender

### ISSUE THREAD

**Issue by xavi-ortega** [mattlewis92/angular-calendar#1101]
**Is your feature request related to a problem? Please describe**
While I was using angular-calendar for a personal project, I ran into a dead end. I use it as an agenda, and I can add events, but I was trying to prevent switching months before the user have saved the events of the current month.

**Describe the solution you'd like**

I'd like to have de possibility to prevent the view rendering inside the beforeViewRender function. For example, if the function returns false, the month doesn't change.

**Describe your use case for implementing this feature**

As I said before, I want to prevent the user change the month before saving the current month to the database, clicking a save button. I am able to show a message, but not stopthe month change.

**Comment by mattlewis92** [comment]
Hey, thanks for opening an issue. You can already do this by not changing the `viewDate` that you pass to the month view, the calendar never changes that value except via the `mwlCalendarPreviousView`, `mwlCalendarToday` and `mwlCalendarNextView` buttons, so you could disable those buttons in your app until the user has saved the state. Hope that helps! 😄
