### ISSUE TITLE
Feature: Now indicator for week/day views

### ISSUE THREAD

**Issue by Kherat** [mattlewis92/angular-calendar#1102]
![60276244-ea844780-9903-11e9-8bc2-eee57ff91e73](https://user-images.githubusercontent.com/47124139/65715704-49de2900-e0a6-11e9-97e3-a71c07c41622.png)

**Is your feature request related to a problem? Please describe**

**Describe the solution you'd like**

**Describe your use case for implementing this feature**

**Additional context**

**Comment by mattlewis92** [comment]
Yeah I think this is a good idea of something to have by default, I just added it to the next version. Please give it a try with:

```
npm i angular-calendar@next
```

Please also take note of the breaking changes in that version: https://github.com/mattlewis92/angular-calendar/pull/1070

Let me know if that works for you 😄

**Comment by Kherat** [comment]
Thank you very much, it is work fine with me @mattlewis92

**Comment by JaxonWright** [comment]
This works well, but definitely need some documentation on how to customize this.

**Comment by mattlewis92** [comment]
@JaxonWright customise in what way? The color, width or just hiding it all together?

**Comment by JaxonWright** [comment]
@mattlewis92 all of the above

**Comment by mattlewis92** [comment]
Sure thing, I'll add a demo with all of that!

**Comment by mattlewis92** [comment]
Added a demo! Preview here: https://stackblitz.com/edit/angular-ui8hkn?file=demo/template.html

**Comment by flippy16** [comment]
Hey, How i can make a repeat on this calendar ? like repeat event in some of days, repeat event every week, month, and year ? could you help me ? i just get little bit confuse how to make some repeats for my events

Thanks

**Comment by JaxonWright** [comment]
@flippy16 that isn't really related to this issue, but this section in the docs should help you with that:

https://mattlewis92.github.io/angular-calendar/#/recurring-events

**Comment by flippy16** [comment]
Oh I'm very sorry, idk where to ask actually. Thank you so much @JaxonWright .
so if i have any questions, how can i ask that? sorry i am new
