### ISSUE TITLE
Feature: Agenda / List View

### ISSUE THREAD

**Issue by JaxonWright** [mattlewis92/angular-calendar#1104]
**Is your feature request related to a problem? Please describe**

Not really, but it is a view that many people would love to use.

**Describe the solution you'd like**

A common feature of various calendar applications is some sort of agenda or list view.  A new AgendaViewComponent that can be optionally used would be a very nice addition to this already-solid library.

It would scroll vertically and cluster events in a list day-by-day.

**Describe your use case for implementing this feature**

This is especially useful for mobile users, as the other views can get cramped no matter how hard you try to make it presentable. It also makes it much easier to see how many items you have to do on any given day without much (if any) scrolling required. 

**Additional context**

Here are a few examples of the feature in other products / projects:

* [Google Calendar Schedule View](https://imgur.com/oQhRsg6)
* [Apple Calendar List View](https://imgur.com/pWaznQa)
* [SyncFusion Agenda View](https://imgur.com/a0lCjLD)
* [FullCalendar.io List View](https://imgur.com/23RReY0)
* [MdBootstrap List View](https://imgur.com/tTazUzr)

I'm sure there are other examples, but those are what I found.

**Comment by JaxonWright** [comment]
@mattlewis92 thoughts on this?

**Comment by mattlewis92** [comment]
It's probably not something I would really want to have to build and maintain (I only just got rid of the day view code 😛), I think it's something that would be better suited to an extension library like `angular-calendar-list-view` (and I would be happy to link to it in the readme from this repo). This was actually one of the reasons why the utils, drag and drop, and resizable code are all in separate packages, so you can build additional views that suit your app's specific needs.

**Comment by JaxonWright** [comment]
For anybody who stumbles upon this issue, and wants the same thing... I just recently finished making a new Agenda View on top of this library. If there is a lot of interest, I could spend some time to turn it into an actual NPM library that can be used in conjunction with angular-calendar.

The basic concept is pretty simple: Create an `AgendaViewComponent` that extends `WeekViewComponent` and use the `view.hourColumns` to create daily group rows.  

One tricky part about it was getting all-day events to also be included. This required overriding the `refreshBody()` function, loop through each item in `view.hourColumns` and add to it a new array that uses `getEventsInPeriod()` to get allDay events on that day.

**Comment by fdx-alex** [comment]
@JaxonWright 
I would love to see this as an NPM library

**Comment by cbleu** [comment]
@JaxonWright I will also love to see a demo in a repository or an npm library if you have enough time for that!

**Comment by misgana96** [comment]
@JaxonWright I also love to see a demo of this feature. Thank you
