### ISSUE TITLE
Add eventClicked directly on MonthView

### ISSUE THREAD

**Issue by no-more** [mattlewis92/angular-calendar#111]
Hi,

First of all thanks for this great tool.

It's my first attempt to use it and I would like to know if it's possible to add a direct event click on the view without having to use the activeDayIsOpen option.

I know the current view with only a small point might not be ideal to handle the click, but this still should be possible, maybe with an option to enable it.

Thanks a lot.

**Comment by mattlewis92** [comment]
Sorry I don't quite follow you, would you mind explaining a bit more what you mean?

**Comment by no-more** [comment]
Of course,

In the calendar view if I want to trigger eventClick, I have to click on the day I want, then click on the event listed below.
I think it would be great to be able to click directly on an event without having to use this additional step.
Of course the small circles that are displayed is not really suited for this behavior, but this could still be useful in my case (and I might not be the only one).

As I've said I'm very new to this tool, but do you have some evolutions planned. Do some thing closer to the google calendar month view a possible evolution? I mean a way to view all events in one glance without having to open every days one by one.

Once again, thanks a lot.

**Comment by mattlewis92** [comment]
Ah ok I follow you now, I can add that in, in fact it's how the ng1 version already works.

As for expanding on the month view I have no plans to really change any of the UI/UX around it, if you want something like the google calendar month view then I'd suggest just building your own component for it - it's impossible to create an open source library that meets everyone's expectations / use cases.

**Comment by no-more** [comment]
ok great thanks.

About UI/UX it's fine for me and I completely agree with you.
Just one more question, do you think it's possible to add a custom view render over this component without having to create a fork. I currently don't aim to do so, but I was just wondering if this is possible or not.

**Comment by mattlewis92** [comment]
Not currently, but I'm working on it: https://github.com/mattlewis92/angular-calendar/issues/16
