### ISSUE TITLE
Event min height (Day view)

### ISSUE THREAD

**Issue by jeff755** [mattlewis92/angular-calendar#1110]
**Is your feature request related to a problem? Please describe**
Be able to control min events height (Day view)

**Describe the solution you'd like**
Have an input option for day view to input min event height

**Additional context**
If we have day event for example 12:15 - 12:17, its height is too small and makes some problems with layout so it'll be good if there is a way to control min height.

**Comment by mattlewis92** [comment]
Thanks for opening an issue, I think the cleanest way to solve this is to use a fake end date a bit like this: https://stackblitz.com/edit/angular-rxhz2u?file=demo/component.ts Let me know if that works for you! 😄
