### ISSUE TITLE
Customization for weeks in month view

### ISSUE THREAD

**Issue by Mattkins** [mattlewis92/angular-calendar#1115]
**Is your feature request related to a problem? Please describe**

Nope, probably just not a use case you've hit yet.

**Describe the solution you'd like**

Some way to customize a "week" template in `CalendarMonthViewComponent`

**Describe your use case for implementing this feature**

I am currently using `dayClicked` in `CalendarMonthViewComponent` to create what is basically a large date picker for our users. They click to select/deselect days on a form that lets them specify daily schedule windows. I've already added a "Select Month" capability to the control, but we've also been asked about a "Select Week" capability. I would like to put two buttons on the left side of each week in the month view, one to allow them to select all 7 days, and one to allow them to select only business days. I don't see any way to do this with the current API.

**Additional context**

I've dug around a little bit and have a few ideas on how to do this, and can put a PR together, but have to work a few other priorities first and would appreciate any input on potential solutions and pitfalls.

**Comment by mattlewis92** [comment]
So the way I'd recommend to do this is to extend the root month view component and override its template, and then you can customise it to fit your needs. A little like this: https://stackblitz.com/edit/angular-uykzy8?file=demo/custom-month-view.component.ts

Hope that helps! 😄
