### ISSUE TITLE
Drag and drop external event with no start value

### ISSUE THREAD

**Issue by cosf87** [mattlewis92/angular-calendar#1118]
**Describe the bug**

Hi Matt. Before 0.28 update, an external event could be dragged and dropped to calendar with no start value. Now, when I try to do that, newStart property of CalendarEventTimesChangedEvent returns an invalid date. 

**Minimal reproduction of the problem with instructions**

On 'Draggable external events' demo, yo have to change 'start' property of external events to null. Then, if you drag and drop an event to calendar, CalendarEventTimesChangedEvent 'newStart' property return Invalid Date

**Screenshots**

**Versions**

- `@angular/core`: ^8.2.12
- `angular-calendar`: 0.28.0-beta.9
- Browser name and version: 78.0.3904.70 (Build oficial) (64 bits)

**Comment by mattlewis92** [comment]
Ah, it looks like it was the date-fns upgrade that caused it, it got more strict about passing in null / undefined to each function. The event `start` on external events was always technically required (as per the [demo](https://mattlewis92.github.io/angular-calendar/#/draggable-external-events)), and the previous behaviour only really worked by chance. The way to solve it is to add `start: new Date()` to all your external events and everything should then work properly 😄

**Comment by GermanAngarita** [comment]
Hi Matt before something let me say thank you for all your work whit this library. Right now i have a error when i try to use the external drop in the Day view scheduler.

<img width="579" alt="Captura de pantalla 2024-10-22 a la(s) 5 25 00 p  m" src="https://github.com/user-attachments/assets/856ad625-8ff7-4f3c-805a-55b13f0d9602">

This is the externaldrop zone

`<div class="col-lg-12 mb-2">
      <div
        class="border rounded shadow row" 
        mwlDroppable
        (drop)="externalDrop($event.dropData.event)"
        dragOverClass="drag-over"
        >
        <div *ngIf="externalEvents.length == 0">
          No hay operaciones detenidas
        </div>
        <div
          class="col-lg-1 fs-6" 
          *ngFor="let event of externalEvents"
          mwlDraggable
          [dropData]="{event: event}"
          [touchStartLongPress]="{ delay: 300, delta: 30 }"
          dragActiveClass="drag-active">

          <app-tarjeta-seguimiento-operacion
            class="p-1 fs-6"
            href="javascript:;"
            (hacerClick)="handleEvent($event.event, $event.operacion)" 
            [vistaSmall]="true"
            [operacion]="event">
          </app-tarjeta-seguimiento-operacion>

          
        </div>
      </div>
    </div>`

and this is the day-view-shceduler 
`

    <div *ngIf="!horario.cerrado" class="col-lg-12 mb-3">
      <mwl-day-view-scheduler
        [dayStartHour]="horario.apertura.hour"
        [dayEndHour]="horario.cierre.hour+4"
        [viewDate]="viewDate"
        [hourDuration]="30"
        [hourSegments]="4"
        [eventTemplate]="eventWeekTemplate"
        [users]="users"
        [events]="events"
        [refresh]="refresh"
        [snapDraggedEvents]="false"
        (eventTimesChanged)="eventDropped($event)"
        (userChanged)="userChanged($event)"
      >
      </mwl-day-view-scheduler>
    </div>`

i need drag items from external zone and drop in the day-view-scheduler zone, can somebody help me?
