### ISSUE TITLE
Allow extra parameters to events

### ISSUE THREAD

**Issue by no-more** [mattlewis92/angular-calendar#112]
Hi,

maybe it's possible to achieve this in another way but I wasn't able to find a clean way to do this : how could I had some extra data/properties to an event.
Mainly I would like to be able to add an id, and perhaps a description. This way on the event click I could find the corresponding event in my database easily.

Thanks.

**Comment by mattlewis92** [comment]
You can do this via extending the interface: https://github.com/mattlewis92/angular-calendar/issues/110#issuecomment-269202627
