### ISSUE TITLE
[Bug] Drag to create events with weekStartsOn Monday

### ISSUE THREAD

**Issue by Mineyuki** [mattlewis92/angular-calendar#1121]
**Describe the bug**

The feature to drag to create events didn't work well in the column Sunday when weekStartsOn Monday. It seems the calendar don't recognize the drag but recognize only the click.

**Minimal reproduction of the problem with instructions**

In the demo [https://stackblitz.com/run?embed=1&file=demo/template.html](url) (demo to drag) : 
- Add in DemoComponent : `weekStartsOn: number = DAYS_OF_WEEK.MONDAY;`
- Import also DAYS_OF_WEEK : `import { DayViewHourSegment, DAYS_OF_WEEK } from 'calendar-utils';`
- Add in template, the directive in mwl-calendar-week-view :   [hourSegmentTemplate]="weekViewHourSegmentTemplate" 
```
<mwl-calendar-week-view
  [viewDate]="viewDate"
  [events]="events"
  [hourSegmentTemplate]="weekViewHourSegmentTemplate"
>
</mwl-calendar-week-view>
```
Try to drag on Sunday and Monday. You will see the difference. 

**Screenshots**

**Versions**

- `@angular/core`: 8.2.2
- `angular-calendar`: 0.27.20
- Browser name and version: Chrome Version 78.0.3904.87

**Comment by mattlewis92** [comment]
Ah, I see the issue, you need to pass the week start variable to this line in your code: https://github.com/mattlewis92/angular-calendar/blob/master/projects/demos/app/demo-modules/drag-to-create-events/component.ts#L84 like this: `const endOfView = endOfWeek(this.viewDate, {startOfWeek: this.startOfWeek});`. I'll update the demo to make this more clear.

**Comment by Mineyuki** [comment]
Hello,
It works ! Thank you very much !
