### ISSUE TITLE
New Module/View - Schedule view similar to google calendar

### ISSUE THREAD

**Issue by GenuineRex** [mattlewis92/angular-calendar#1122]
**Is your feature request related to a problem? Please describe**

I want to show a vertical scrolling calendar schedule similar to google calendar

**Describe the solution you'd like**

ideally a new module and template similar to the ones that exist now

**Describe your use case for implementing this feature**

This would be another option for the customer to view their calendar/schedule data.

**Additional context**

Google has a great working schedule view

**Comment by mattlewis92** [comment]
Hey, thanks for opening an issue, it's probably not something I would really want to have to build and maintain, I think it's something that would be better suited to an extension library like angular-calendar-schedule-view (and I would be happy to link to it in the readme from this repo). This was actually one of the reasons why the utils, drag and drop, and resizable code are all in separate packages, so you can [build additional views](https://github.com/mattlewis92/angular-calendar#the-month-week-or-day-view-doesnt-meet-my-project-requirements-but-the-other-views-do) that suit your app's specific needs.
