### ISSUE TITLE
Calendar overflow auto

### ISSUE THREAD

**Issue by hypertextdevelopers** [mattlewis92/angular-calendar#1124]
**Is your feature request related to a problem? Please describe**

I have an extremely long calendar (the width), so I was insisted to set the calendar-wrapper to overflow auto in case of well scaling depending on window width. I have also connected with that calendar a menu with events that should be dragged in. Menu is positioned absolutely and it is above the whole calendar, it covers it on the right like the video instance. The issue is that when we are dragging the event over it's menu not apparently going out this, the event is placed in the calendar, even though the menu covers the day where the event has jumped in. And the event is placed under the menu.

**Describe the solution you'd like**

Prevent that behaviour maybe by discerning the event which is already on calendar and the external event.

**Describe your use case for implementing this feature**

Pretty long calendar which has to be set to overflow auto to be scrollable, then implementation of menu with events which is on the calendar.

**Additional context**

demo to that issue (try to drag the event over the green menu not going out and just drop it, the event will be placed under the menu, user is unable to fetch where the event has jumped in):
https://ler4vg.run.stackblitz.io

[Angular 6.0+ calendar - Google Chrome 2019-11-12 07-37-22.zip](https://github.com/mattlewis92/angular-calendar/files/3834746/Angular.6.0%2B.calendar.-.Google.Chrome.2019-11-12.07-37-22.zip)

**Comment by mattlewis92** [comment]
I actually had the same problem in my app as well and could never find a way to solve it out the box, it's tricky to solve as the element under the cursor is the item being dragged and not the droppable element. But with a few lines you can solve it in your app, if you add this to your external drop area:
```
(dragEnter)="externalDragActive = true"
(dragLeave)="externalDragActive = false"
```

and then don't allow dropping on the calendar when that flag is active. I put together a demo for you here: https://stackblitz.com/edit/angular-5lugsc?file=demo/component.ts

Hope that helps! 😄
