### ISSUE TITLE
Problem with loading data from server

### ISSUE THREAD

**Issue by kianliang-iium** [mattlewis92/angular-calendar#113]
Hi. 
I'm still learning to use this great plugin.
When I tried to load data from firebase, I ran into this issue:
 Type '{ "start": string; "title": string; "color": string; }' is not assignable to type 'CalendarEvent[]'.

My firebase data is as follow:
-K_-eHIGzkx1qZubawp0
 color: "colors.yellow"
 end: ""2016-12-28T00:00:00.000+08:00"
 id: "-K_-eHIGzkx1qZubawp0"
 start: "2016-12-28T00:00:00.000+08:00"
 title: "pm"

How do I solve this? 
Thanks.

**Comment by mattlewis92** [comment]
It's a warning from typescript because the types don't match. If you click on the `CalendarEvent` definition in your IDE it should take you through to it. The event structure you need to match is:

```
interface EventColor {
  primary: string;
  secondary: string;
}

interface EventAction {
  label: string;
  cssClass?: string;
  onClick({event}: {event: CalendarEvent}): any;
}

interface CalendarEvent {
  start: Date;
  end?: Date;
  title: string;
  color: EventColor;
  actions?: EventAction[];
  allDay?: boolean;
  cssClass?: string;
  resizable?: {
    beforeStart?: boolean;
    afterEnd?: boolean;
  };
  draggable?: boolean;
}
```
