### ISSUE TITLE
Disable dragging event on the next day

### ISSUE THREAD

**Issue by KirillTovpinets** [mattlewis92/angular-calendar#1130]
**Is your feature request related to a problem? Please describe**

**Describe the solution you'd like**

**Describe your use case for implementing this feature**

**Additional context**

Hi. It's a very cool angular calendar I've ever used!

But it would be great if you can add a feature of disabling dragging an event on the next day in week view. Like an event within one day long. I've checked all the api documentation but don't see any interfaces to implement this.

Thank you in advance.

**Comment by mattlewis92** [comment]
Hi there, thanks for opening an issue, you have a few options for implementing this. You can either:

1/ Check in the `eventTimesChanged` output if the user dragged the event to another day and show an alert to them saying they can't drag events to another date

2/ [Extend the week view component](https://stackblitz.com/edit/angular-ukwpj8?file=demo%2Fcustom-week-view.component.ts) and set the `dragAxis` property to disable dragging time events across days
```
[dragAxis]="{x: false, y: timeEvent.event.draggable && timeEventResizes.size === 0}"
```

Hope that helps! 😄

**Comment by ramu533** [comment]
Hi, i am start up angular developer  i was struggle  to drag and drop in angular-calender  please help me i wan print start time and endtime 



import { Component, OnInit, Inject, ChangeDetectionStrategy, ChangeDetectorRef, ViewEncapsulation, ViewChild, TemplateRef, Injectable, Input, OnDestroy, ElementRef } from '@angular/core';
import { CalendarEvent, CalendarEventTitleFormatter, CalendarView, CalendarEventAction, CalendarEventTimesChangedEvent, CalendarMonthViewDay, CalendarWeekViewBeforeRenderEvent, CalendarMonthViewBeforeRenderEvent } from 'angular-calendar';
import { DayViewHourSegment } from 'calendar-utils';
import { Subject, fromEvent, Observable } from 'rxjs';
import { finalize, takeUntil, reduce } from 'rxjs/operators';
import { addDays, addMinutes, endOfWeek, addHours, startOfDay, endOfDay, subDays, endOfMonth, isSameDay, isSameMonth, getDate } from 'date-fns';
import { NgbAccordionConfig } from '@ng-bootstrap/ng-bootstrap';
import { Interview, TimeZones, InterviewTypes, ChangeStatusItem, ScheduledSlotList } from '../interview/interview';
import { InterviewService } from '../interview/interview.service';
import { NgbModalConfig, NgbModal } from '@ng-bootstrap/ng-bootstrap';
import { DOCUMENT } from '@angular/common';
import { NgbDropdownConfig } from '@ng-bootstrap/ng-bootstrap';
import { CloneVisitor } from '@angular/compiler/src/i18n/i18n_ast';
import { DatePipe, formatDate } from '@angular/common';
import { ActivatedRoute, Params } from '@angular/router';
import { Http, Response, Headers, RequestOptions, URLSearchParams, ResponseContentType } from '@angular/http';
import { ClientService } from '../client/client.service';
import { ConfirmationDialogService } from '../confirmation-dialog/confirmation-dialog.service';
import { Contact } from '../confirmation-dialog/confirmation';
import { ContactService } from '../confirmation-dialog/contact.service';
import { jsonpFactory } from '@angular/http/src/http_module';
import { CustomAlertService } from '../customalert/customalert.service';
import * as moment from 'moment-timezone';
import { ConfirmInterviewService } from '../confirminterview/confirminterview.service';

function floorToNearest(amount: number, precision: number) { return Math.floor(amount / precision) * precision; }
function ceilToNearest(amount: number, precision: number) { return Math.ceil(amount / precision) * precision; }
export class CustomEventTitleFormatter extends CalendarEventTitleFormatter { }

@Component({
  selector: 'app-candidate-interview',
  templateUrl: './candidate-interview.component.html',
  styleUrls: ['./candidate-interview.component.css'],
  providers: [DatePipe, NgbAccordionConfig, NgbModalConfig, NgbModal, NgbDropdownConfig, {
    provide: CalendarEventTitleFormatter,
    useClass: CustomEventTitleFormatter
  }],
  styles: [
    `
      .disable-hover {
        pointer-events: none;
      }
    `
  ],
  encapsulation: ViewEncapsulation.None
})
export class CandidateInterviewComponent {
 
  //Global varaible and objects declaration here //
  @ViewChild('modalContent') modalContent: TemplateRef<any>;
  public scheduleInterviewList: Interview[];
  timeZoneList: TimeZones[];
  InterviewTypeList: InterviewTypes[];
  timeZoneDefaultName = 'Select Time Zone';
  interviewDefaultType = 'Select Interview Type';
  timeZoneRequired: boolean;
  typeRequired: boolean;
  instructionRequired: boolean;
  slotRequired: boolean;
  feedbackList: ChangeStatusItem[];
  radioSelected = 'Selected';
  radioSelectedString: string;
  minimumDate = new Date();

  events: CalendarEvent[] = [];
  refresh: Subject<any> = new Subject();
  view: CalendarView = CalendarView.Week;
  CalendarView = CalendarView;
  viewDate: Date = new Date();
  dragToCreateActive = false;
  activeDayIsOpen: boolean = true;
  ScheduleID: string;
  RandomID: number;
  SelectedCandidateID: string = "";

  SelTimeZoneID: string = "0";
  SelIntTypeID: string = "";
  StrContactperson: string = "";
  StrAddress: string = "";
  StrNotes: string = "";
  ShowPrevSlots: Boolean = false;
  IsReschedule: Number = 0;
  SlotIDforReschedule: string = "";
  StrContactEmailAddress: string = "";
  contacts: Contact[] = [];
  strInterviewerName: string = "";

  weekStartsOn: 0 = 0;



  public PreviousSlotList: ScheduledSlotList[] = [];
  public ScheduleSlots: Array<{ Id: any, Starttime: string, Endtime: string }> = [];

  public SelectedContactList: Array<{ contactId: any, Email: string, IsPrimary: any }> = [];

  constructor(config: NgbAccordionConfig, private _Interviewservice: InterviewService, private modalService: NgbModal, private datePipe: DatePipe,
    @Inject(DOCUMENT) private document: Document, ngbDropdownConfig: NgbDropdownConfig, private cdr: ChangeDetectorRef, private _ClientService: ClientService
    , private confirmationDialogService: ConfirmationDialogService, private _ContactServices: ContactService, private _customAlertService: CustomAlertService
  ) {
    // customize default values of accordions used by this component tree
    config.closeOthers = true;
    // config.type = 'info';
    this.events = [];
    this.RandomID = 0;
    this.contacts = [];
    
  }

  ngOnInit() {
    this.events = [];
    this.RandomID = 0;
    this.getInterviewSchedule();
    this.contacts = [];
    this.loadScript('assets/jquery.js');
    
  }

  getInterviewSchedule() {
    this._Interviewservice.scheduleInterviewList().subscribe(postdata => { this.scheduleInterviewList = postdata });
    this._Interviewservice.getPrimaryContact().subscribe(postdata => {
      if (postdata.length > 0) {
        this.StrContactperson = postdata[0].ContactPerson;
        this.StrContactEmailAddress = postdata[0].ContactEmailAddress;
      }
    })
    this._Interviewservice.getTimeZone().subscribe(postdata => { this.timeZoneList = postdata });
    this._Interviewservice.getInterviewTypes().subscribe(postdata => { this.InterviewTypeList = postdata });
  }
  private segmentIsValid(date:any): boolean {
    let pastdate:Date = new Date(this.datePipe.transform(date, "MM/dd/yyyy HH:mm:ss"));
    let currtentday:Date = new Date(moment().tz('America/New_York').format("MM/DD/YYYY HH:mm:ss").toString());
    return pastdate >=  currtentday ;
  }

  beforeViewRender(body: CalendarWeekViewBeforeRenderEvent): void {
    body.hourColumns.forEach(hourCol => {
      hourCol.hours.forEach(hour => {
        hour.segments.forEach(segment => {
          if (!this.segmentIsValid(segment.date)) { 
            segment.cssClass = 'disabled-date';
          }
        })
      })
    });
  }

  startDragToCreate(segment: DayViewHourSegment, mouseDownEvent: MouseEvent, segmentElement: HTMLElement) {
    var d = new Date();
    var n = d.getMilliseconds();
    this.RandomID = Math.floor(Math.random() * 15) + 5 + n;
    const dragToSelectEvent: CalendarEvent = {
      id:this.events.length,
      title: '',
      start: segment.date,
      end: addDays(addMinutes(segment.date, 30), 0),
      meta: {
        tmpEvent: true,
      },
      //  resizable: {
      //       beforeStart: true,
      //       afterEnd: true,
      //    },
      //     draggable: true,  actions: [{
      //     label: '<i class="fa fa-times">x</i>',
      //     onClick: ({ event }: { event: CalendarEvent }): void => {
      //       this.ScheduleSlots = this.ScheduleSlots.filter(item => item.Id !== dragToSelectEvent.id);
      //       this.events = this.events.filter(iEvent => iEvent !== event);
      //       this.refresh.next();
      //     }
      //   }]
    };
    this.events = [...this.events, dragToSelectEvent];

    const segmentPosition = segmentElement.getBoundingClientRect();
    this.dragToCreateActive = true;
    const endOfView = endOfWeek(this.viewDate, {
      weekStartsOn: this.weekStartsOn,
    });
    

    // fromEvent(document, 'mousemove',)
    //   .pipe(
    //     finalize(() => {
    //       delete dragToSelectEvent.meta.tmpEvent;
    //       this.dragToCreateActive = false;
    //       this.refresh.next();
    //     }),
    //     takeUntil(fromEvent(document, 'mouseup').pipe(
    //       finalize(() => {
    //         delete dragToSelectEvent.meta.tmpEvent;
    //         this.dragToCreateActive = false;
    //         this.refresh.next();

    //     }),
    //     )
    //     )
    //   )

  
     fromEvent(document,'mouseup').pipe(
          finalize(() => {
            delete dragToSelectEvent.meta.tmpEvent;
            this.dragToCreateActive = false;
            this.refresh.next();
          }),
      )
      
      .subscribe((mouseMoveEvent: MouseEvent) => {
        const minutesDiff = ceilToNearest(
          mouseMoveEvent.clientY - segmentPosition.top,
          30
        );
        const daysDiff =
          floorToNearest(
            mouseMoveEvent.clientX - segmentPosition.left,
            segmentPosition.width
          ) / segmentPosition.width;

        const newEnd = addDays(addMinutes(segment.date, minutesDiff), daysDiff);

        if (newEnd > segment.date && newEnd < endOfView) {
          dragToSelectEvent.end = newEnd;
          console.log(segment.date);
          console.log(newEnd);
          console.log(dragToSelectEvent.id);
          this.ScheduleSlots.push({ Id:dragToSelectEvent.id, Starttime: this.datePipe.transform(segment.date, "MMM d, y h:mm a"),Endtime: this.datePipe.transform(dragToSelectEvent.end, "MMM d, y h:mm a")  });
        }
        this.refresh.next();

      });
      
  }

  
  // getData() {
  //   this.events = [...this.events];
  

  //   for (var i = 0; i < this.events.length; i++) {
  //     let startTime:string = this.datePipe.transform(this.events[i].start,"MMM d, y h:mm a");
  //     let endTime:string = this.datePipe.transform(this.events[i].end,"MMM d, y h:mm a")
  //     if(startTime != undefined && endTime != undefined){
  //       this.ScheduleSlots.push({ Id: this.events[i].id, Starttime:startTime,Endtime:endTime  });
  //     }
  //     return false;
  
  //   }
  
  // }
  // startDragToCreate(segment: DayViewHourSegment, mouseDownEvent: MouseEvent, segmentElement: HTMLElement) {
  //   var d = new Date();
  //   var n = d.getMilliseconds();
  //   this.RandomID = Math.floor(Math.random() * 15) + 5 + n;
  //   if (this.events.length > 4) {
  //     this._customAlertService.confirm('Alert', 'You can select maximum of 5 slots per interview.')
  //       .then((confirmed) => console.log(''))
  //       .catch(() => console.log(''));
  //   } else {
  //     const dragToSelectEvent: CalendarEvent = {
  //       id: this.RandomID,
  //       title: '',
  //       start: segment.date,
  //       meta: { tmpEvent: true },
  //       resizable: { beforeStart: true, afterEnd: true },
  //       draggable: true,
  //       actions: [{
  //         label: '<i class="fa fa-times">x</i>',
  //         onClick: ({ event }: { event: CalendarEvent }): void => {
  //           this.ScheduleSlots = this.ScheduleSlots.filter(item => item.Id !== dragToSelectEvent.id);
  //           this.events = this.events.filter(iEvent => iEvent !== event);
  //           this.refresh.next();
  //         }
  //       }]
  //     };

  //     this.events = [...this.events, dragToSelectEvent];
  //     const segmentPosition = segmentElement.getBoundingClientRect();
  //     this.dragToCreateActive = true;
  //     const endOfView = endOfWeek(this.viewDate);

  //     fromEvent(document, 'mousemove').pipe(finalize(() => {
  //       delete dragToSelectEvent.meta.tmpEvent;
  //       this.dragToCreateActive = false;
  //       this.refresh.next();
  //     }),
  //       takeUntil(fromEvent(document, 'mouseup'))).subscribe((mouseMoveEvent: MouseEvent) => {
  //         const minutesDiff = 30;
  //         const daysDiff = 0;
  //         const newEnd = addDays(addMinutes(segment.date, minutesDiff), daysDiff);
  //         if (newEnd > segment.date && newEnd < endOfView) {
  //           dragToSelectEvent.end = newEnd;
  //         }
  //         this.refresh.next();
  //       });
  //     this.ScheduleSlots.push({ Id: dragToSelectEvent.id, Starttime: this.datePipe.transform(segment.date, "MMM d, y h:mm a") });
  //   }
  // }
  clickTimeZoneItem(timezoneID: string, timezone: string): void {
    this.timeZoneDefaultName = timezone;
    this.SelTimeZoneID = timezoneID;
    this.timeZoneRequired = false;
  }
  instructionClick(event: Event): void {
    this.instructionRequired = false;
  }

  clickInterviewType(InterviewTypeID: string, type: string): void {
    this.interviewDefaultType = type;
    this.SelIntTypeID = InterviewTypeID;
    this.typeRequired = false;
  }

  openVerticallyCentered(schedulePopup, id: number) {
    this.modalService.open(schedulePopup, { centered: true });
    this.document.body.classList.add('ScheduleInterview');
  }

  removeClassName() {
    this.document.body.classList.remove('ScheduleInterview');
    this.document.body.classList.remove('changeStatus');
  }

  onChange(event: Event) {
    if (this.StrNotes !== '') {
      this.instructionRequired = false;
    }
    if (this.StrNotes == '') {
      this.instructionRequired = true;
    }
  }

  ScheduleInterview() {
    if (this.timeZoneDefaultName === 'Select Time Zone') {
      this.timeZoneRequired = true;
    } else if (this.interviewDefaultType === 'Select Interview Type') {
      this.typeRequired = true;
    } else if (this.StrContactEmailAddress == "") {
      this._customAlertService.confirm('Alert', 'You cannot schedule interview as there is no email address associated with the primary contact, please contact respective account manager of this job.')
        .then((confirmed) => console.log(''))
        .catch(() => console.log(''));
    } else if (this.StrNotes == "") {
      this.instructionRequired = true;
    }
    else {
      if (this.events.length > 0) {
        var DateSlot1 = ""
        var DateSlot2 = ""
        var DateSlot3 = ""
        var DateSlot4 = ""
        var DateSlot5 = ""
        var StartTimeSlot1 = ""
        var StartTimeSlot2 = ""
        var StartTimeSlot3 = ""
        var StartTimeSlot4 = ""
        var StartTimeSlot5 = ""

        if (this.events.length == 1) {
          DateSlot1 = this.datePipe.transform(this.events[0].start, "MM/dd/yyyy");
          StartTimeSlot1 = this.datePipe.transform(this.events[0].start, "HH:mm:ss");
        }
        else if (this.events.length == 2) {
          DateSlot1 = this.datePipe.transform(this.events[0].start, "MM/dd/yyyy");
          StartTimeSlot1 = this.datePipe.transform(this.events[0].start, "HH:mm:ss");

          DateSlot2 = this.datePipe.transform(this.events[1].start, "MM/dd/yyyy");
          StartTimeSlot2 = this.datePipe.transform(this.events[1].start, "HH:mm:ss");

        }
        else if (this.events.length == 3) {
          DateSlot1 = this.datePipe.transform(this.events[0].start, "MM/dd/yyyy");
          StartTimeSlot1 = this.datePipe.transform(this.events[0].start, "HH:mm:ss");

          DateSlot2 = this.datePipe.transform(this.events[1].start, "MM/dd/yyyy");
          StartTimeSlot2 = this.datePipe.transform(this.events[1].start, "HH:mm:ss");

          DateSlot3 = this.datePipe.transform(this.events[2].start, "MM/dd/yyyy");
          StartTimeSlot3 = this.datePipe.transform(this.events[2].start, "HH:mm:ss")
        }
        if (this.events.length == 4) {
          DateSlot1 = this.datePipe.transform(this.events[0].start, "MM/dd/yyyy");
          StartTimeSlot1 = this.datePipe.transform(this.events[0].start, "HH:mm:ss");

          DateSlot2 = this.datePipe.transform(this.events[1].start, "MM/dd/yyyy");
          StartTimeSlot2 = this.datePipe.transform(this.events[1].start, "HH:mm:ss");

          DateSlot3 = this.datePipe.transform(this.events[2].start, "MM/dd/yyyy");
          StartTimeSlot3 = this.datePipe.transform(this.events[2].start, "HH:mm:ss")


          DateSlot4 = this.datePipe.transform(this.events[3].start, "MM/dd/yyyy");
          StartTimeSlot4 = this.datePipe.transform(this.events[3].start, "HH:mm:ss")
        }
        else if (this.events.length == 5) {
          DateSlot1 = this.datePipe.transform(this.events[0].start, "MM/dd/yyyy");
          StartTimeSlot1 = this.datePipe.transform(this.events[0].start, "HH:mm:ss");

          DateSlot2 = this.datePipe.transform(this.events[1].start, "MM/dd/yyyy");
          StartTimeSlot2 = this.datePipe.transform(this.events[1].start, "HH:mm:ss");

          DateSlot3 = this.datePipe.transform(this.events[2].start, "MM/dd/yyyy");
          StartTimeSlot3 = this.datePipe.transform(this.events[2].start, "HH:mm:ss")


          DateSlot4 = this.datePipe.transform(this.events[3].start, "MM/dd/yyyy");
          StartTimeSlot4 = this.datePipe.transform(this.events[3].start, "HH:mm:ss")


          DateSlot5 = this.datePipe.transform(this.events[4].start, "MM/dd/yyyy");
          StartTimeSlot5 = this.datePipe.transform(this.events[4].start, "HH:mm:ss")
        }

        this.confirmationDialogService.confirm('Select Contacts', 'Confirm', 'Cancel', 'sm', 1)
          .then((confirmed) => {
            if (confirmed === true) {
              this.contacts = this._ContactServices.contactelected;
              var ContctIDList = "";
              var ISpriamry = "";
              var SelectedContactID = "";
              if (this.contacts.length > 0) {
                for (let i = 0; i < this.contacts.length; i++) {
                  if (this.contacts[i].Contactid) {
                    SelectedContactID = this.contacts[i].Contactid.toString();
                  }
                  if (this.contacts[i].Isprimary) {
                    ISpriamry = this.contacts[i].Isprimary;
                  }
                  if (ContctIDList) {
                    ContctIDList = ContctIDList + "^|" + SelectedContactID + '^*' + ISpriamry;
                  } else {
                    ContctIDList = ContctIDList + SelectedContactID + '^*' + ISpriamry;
                  }

                }
              }
              if (this.IsReschedule == 0) {
                var URLParams = "JobID=" + this._ClientService.JobID + "&CandidateID=" + this._ClientService.CandidateSelected + "&ClientID=" + this._ClientService.ClientID + "&TimeZoneID=" + this.SelTimeZoneID + "&InterviewTypeID=" + this.SelIntTypeID + "&ContactPerson=" + this.StrContactperson + "&AddressDetails=" + this.StrAddress + "&Notes=" + encodeURIComponent(this.StrNotes) + "&InterviewDateSlot1=" + DateSlot1 + "&InterviewStartTime1=" + StartTimeSlot1 + "&InterviewEndTime1=" + "&InterviewDateSlot2=" + DateSlot2 + "&InterviewStartTime2=" + StartTimeSlot2 + "&InterviewEndTime2=" + "&InterviewDateSlot3=" + DateSlot3 + "&InterviewStartTime3=" + StartTimeSlot3 + "&InterviewEndTime3=" + "&InterviewDateSlot4=" + DateSlot4 + "&InterviewStartTime4=" + StartTimeSlot4 + "&InterviewEndTime4=" + "&InterviewDateSlot5=" + DateSlot5 + "&InterviewStartTime5=" + StartTimeSlot5 + "&InterviewEndTime5=" + "&comments=" + "&InterviewStatusID=1&CandidateInterviewSlotAvailabilityID=0&ContactEmailAddress=" + this.StrContactEmailAddress + "&ContactListID=" + ContctIDList + "&InterviewerName=" + this.strInterviewerName+"&IsCreatedBy=1";
              } else if (this.IsReschedule > 0 && this.SlotIDforReschedule != "") {
                var URLParams = "JobID=" + this._ClientService.JobID + "&CandidateID=" + this._ClientService.CandidateSelected + "&ClientID=" + this._ClientService.ClientID + "&TimeZoneID=" + this.SelTimeZoneID + "&InterviewTypeID=" + this.SelIntTypeID + "&ContactPerson=" + this.StrContactperson + "&AddressDetails=" + this.StrAddress + "&Notes=" + encodeURIComponent(this.StrNotes) + "&InterviewDateSlot1=" + DateSlot1 + "&InterviewStartTime1=" + StartTimeSlot1 + "&InterviewEndTime1=" + "&InterviewDateSlot2=" + DateSlot2 + "&InterviewStartTime2=" + StartTimeSlot2 + "&InterviewEndTime2=" + "&InterviewDateSlot3=" + DateSlot3 + "&InterviewStartTime3=" + StartTimeSlot3 + "&InterviewEndTime3=" + "&InterviewDateSlot4=" + DateSlot4 + "&InterviewStartTime4=" + StartTimeSlot4 + "&InterviewEndTime4=" + "&InterviewDateSlot5=" + DateSlot5 + "&InterviewStartTime5=" + StartTimeSlot5 + "&InterviewEndTime5=" + "&comments=" + "&InterviewStatusID=5&CandidateInterviewSlotAvailabilityID=" + this.SlotIDforReschedule + "&ContactEmailAddress=" + this.StrContactEmailAddress + "&ContactListID=" + ContctIDList + "&InterviewerName=" + this.strInterviewerName+"&IsCreatedBy=1";
              }
              this._Interviewservice.InsertInteviewSlots(URLParams);
              DateSlot1 = ""
              DateSlot2 = ""
              DateSlot3 = ""
              DateSlot4 = ""
              DateSlot5 = ""
              StartTimeSlot1 = ""
              StartTimeSlot2 = ""
              StartTimeSlot3 = ""
              StartTimeSlot4 = ""
              StartTimeSlot5 = ""

              this.SelTimeZoneID = "";
              this.SelIntTypeID = "";
              this.StrContactperson = "";
              this.StrAddress = "";
              this.StrNotes = "";
              this.ShowPrevSlots = false;
              this.IsReschedule = 0;
              this.SlotIDforReschedule = "";
              this.modalService.dismissAll();
              this.removeClassName();
              this.events = [];

            }
          })
          .catch(() => console.log('User Dismissed the dialog'));

      }
      else {

        var DateSlot1 = ""
        var DateSlot2 = ""
        var DateSlot3 = ""
        var DateSlot4 = ""
        var DateSlot5 = ""
        var StartTimeSlot1 = ""
        var StartTimeSlot2 = ""
        var StartTimeSlot3 = ""
        var StartTimeSlot4 = ""
        var StartTimeSlot5 = ""


        this._customAlertService.confirm('Alert', 'You did not specify your availability, please select your available time slots from calendar, you can select maximum 5 slots.')
          .then((confirmed) => console.log(''))
          .catch(() => console.log(''));
      }

    }
  }
  private loadScript(scriptUrl: string) {
    return new Promise((resolve, reject) => {
      const scriptElement = document.createElement('script');
      scriptElement.src = scriptUrl;
      scriptElement.onload = resolve;
      document.body.appendChild(scriptElement);
    });
  }
}
