### ISSUE TITLE
DayViewHour has no export member

### ISSUE THREAD

**Issue by hamzapoly** [mattlewis92/angular-calendar#1131]
**Describe the bug**

I have just added the library angular-calendar and angular-calendar-scheduler, but I'm facing a compilation issue in utils.d.ts

**Minimal reproduction of the problem with instructions**

**Screenshots**

![image](https://user-images.githubusercontent.com/13818732/69009753-d85d8100-0958-11ea-8dc7-b6ea5cd6adac.png)

**Versions**

- `@angular/core`:"^7.2.14"
- `angular-calendar`:"^0.26.0"
- Browser name and version: Google Chrome Version 78.0.3904.97

**Comment by mattlewis92** [comment]
It sounds like you're on a newer version of `calendar-utils` that has breaking changes, if you do `npm i calendar-utils@0.2` I think it should fix your problem. Hope that helps! 😄
