### ISSUE TITLE
Unable to get x and y co ordinates on dayClicked event

### ISSUE THREAD

**Issue by ntummalapalli** [mattlewis92/angular-calendar#1132]
**Is your feature request related to a problem? Please describe**

**Describe the solution you'd like**

**Describe your use case for implementing this feature**

**Additional context**

**Comment by ntummalapalli** [comment]
I'm unable to get the x and y coordinates of the cell while using dayClicked event because this is not being considered as a click event.

**Comment by ntummalapalli** [comment]
Or else please help me to get the date of the cell clicked by using click event

**Comment by mattlewis92** [comment]
As of `0.28.0` this should be possible to do now:

To get the coordinates:
```
(dayClicked)="logCoordinates($event.sourceEvent.clientX, $event.sourceEvent.clientY)"
```

To get the date clicked:
```
(dayClicked)="logDate($event.day.date)"
```

Hope that helps! 😄

**Comment by ntummalapalli** [comment]
Hi,
I'm getting an error "Cannot read property 'clientX' of undefined". Please help me solve this.

<mwl-calendar-month-view
  *ngSwitchCase="CalendarView.Month"
  [viewDate]="viewDate"
  [events]="events"
  (dayClicked)="dayClicked(content, $event.day.date, $event.sourceEvent.clientX, $event.sourceEvent.clientY)"
  >
</mwl-calendar-month-view>

**Comment by mattlewis92** [comment]
Are you on version `0.28.0` of `angular-calendar`?

**Comment by ntummalapalli** [comment]
Thanks a lot !! Its working after updating the version. Thanks to you !!
