### ISSUE TITLE
(eventClicked) eventEmitted type differences between local and delpoyment

### ISSUE THREAD

**Issue by ALapaque** [mattlewis92/angular-calendar#1134]
**Describe the bug**

Hi, I've used on the (eventClicked) for the month/day/week view the eventEmitted by your calendar which is normally typed as  eventClicked: EventEmitter<{
        event: CalendarEvent<any>;
        sourceEvent: MouseEvent | KeyboardEvent;
    }>;
but when I'm deploying my sollution I'm having trouble with the type of the sourceEvent which is no longer a MousEvent neither  a KeyboardEvent.
All of this is only in order to be able to trigger a CTRL click on the event...

As you can see below 2 screenshots of the events between localhost and deployed

**Minimal reproduction of the problem with instructions**

Add a test for a CTRL + click on an event

**Screenshots**
### DEPLOYED event received

![image](https://user-images.githubusercontent.com/46450511/69321720-e0147280-0c43-11ea-90d1-c20dfb5fc97d.png)
![image](https://user-images.githubusercontent.com/46450511/69321755-f3274280-0c43-11ea-9c42-51099b389f3b.png)

### LOCAL event received

![image](https://user-images.githubusercontent.com/46450511/69321566-a479a880-0c43-11ea-8397-00100aa5ac1b.png)

**Versions**

 "@angular/animations": "^7.2.2",
    "@angular/cdk": "^7.3.7",
    "@angular/common": "^7.2.2",
    "@angular/compiler": "^7.2.2",
    "@angular/core": "^7.2.2",
    "@angular/flex-layout": "^7.0.0-beta.23",
    "@angular/forms": "^7.2.2",
    "@angular/http": "^7.2.2",
    "@angular/material": "^7.2.2",
    "@angular/material-moment-adapter": "^7.2.2",
    "@angular/platform-browser": "^7.2.2",
    "@angular/platform-browser-dynamic": "^7.2.2",
    "@angular/pwa": "^0.12.3",
    "@angular/router": "^7.2.2",
    "@angular/service-worker": "^7.2.2",
    "angular-calendar": "^0.28.0-beta.3",
"angular-resize-event": "^1.1.0",
    "core-js": "^2.6.3",
 "rrule": "^2.6.2",
    "rxjs": "^6.5.3",
    "stream": "0.0.2",

- `@angular/core`: "^7.2.2
- `angular-calendar`:  "^0.28.0-beta.3"
- Browser name and version: CHROME Version 78.0.3904.97 (64 bits)
FIREFOX Version 70.0.1 (64 bits)

**Comment by mattlewis92** [comment]
I think it's hammerjs, if you upgrade to `0.28.0` final then it should fix the issue as I removed it completely and now it just uses `(click)` events.

**Comment by ALapaque** [comment]
> I think it's hammerjs, if you upgrade to `0.28.0` final then it should fix the issue as I removed it completely and now it just uses `(click)` events.

I think you meant the version "hammerjs": "^2.0.8", and I'm already at the latest.

**Comment by mattlewis92** [comment]
Sorry I meant of `angular-calendar`, not hammerjs
