### ISSUE TITLE
Bug with dragging a calendar event

### ISSUE THREAD

**Issue by KirillTovpinets** [mattlewis92/angular-calendar#1135]
**Describe the bug**

**Minimal reproduction of the problem with instructions**

**Screenshots**

**Versions**

- `@angular/core` - 8.2.6:
- `angular-calendar` - 0.26.6:
- Browser name and version - Chrome 78:

Hi there.
I accidentally face a bug, when the event in "Sunday" column cannot be resized and dragged within column

https://monosnap.com/file/Fd2ZInT6sRKd7W8yhDPccunJnYsuc2

This bug is reproduced when the user reduces the browser view scale. Futhemore some of the cells of the caledar hasn't got different borders.
This bug is connected with the width of the caledar and the scale of the browser view. 

If you need some more context, please let me know. Thank you in advance

**Comment by mattlewis92** [comment]
Hey there, please can you provide a minimal runnable repro on stackblitz or something, as without that it's pretty impossible to really know what's going on. Thanks! 😄
