### ISSUE TITLE
Change the height of the cells

### ISSUE THREAD

**Issue by Loperso** [mattlewis92/angular-calendar#1136]
**Describe the bug**

I am trying to modify the height of the cells (min-height) of the month view but no changes are reflected.

I even modified the 'angular-calendar.css' style file but it also doesn't take those changes. Another thing I tried was to place '! Important' on each line within my custom style file but it didn't work.

However, when I change it in the browser (F12), it does change the height of the calendar.

I am applying the following style:

```
.cal-month-view .cal-day-cell {
  min-height: 0;
}

.cal-month-view .cal-day-cell {
  min-height: 0; 
}
```

**Minimal reproduction of the problem with instructions**

Here is the reference code on what I am doing:

https://stackblitz.com/github/Loperso/tablas

**Screenshots**
I have this:
![image](https://user-images.githubusercontent.com/41653783/69387490-f2b69800-0c93-11ea-836d-52e088980224.png)

I need this:
![image](https://user-images.githubusercontent.com/41653783/69388132-f5b28800-0c95-11ea-92ca-dfc6642cc194.png)

**Versions**

- `@angular/core`: 8.3.14
- `angular-calendar`: 0.28.2
- Browser name and version: Chrome 78.0.3904.108

**Comment by mattlewis92** [comment]
Hi there, there's a couple issues here:

1/ component styles in angular are by default scoped to the component in which they're declared, so your changes won't take effect in other components. To add global styles which will effect the calendar, you can either add:
```
encapsulation: ViewEncapsulation.None
```

to your components metadata in the `@Component` declaration or add to the global [`src/styles.css` file](https://github.com/mattlewis92/angular-calendar/blob/master/build-tool-examples/angular-cli/src/styles.css) that's designed for adding global styles (recommended).

Secondly you also need to override the min-height for the inner `.cal-cell-top` element as well:

https://github.com/mattlewis92/angular-calendar/blob/master/projects/angular-calendar/src/modules/month/calendar-month-view.scss#L84

That should give you the behaviour you're after. Hope that helps! 😄
