### ISSUE TITLE
Is y-axis timeline support in v0.24.1 with Angular 5 version?

### ISSUE THREAD

**Issue by Priya1815** [mattlewis92/angular-calendar#1138]
**Describe the bug**

My project is in the Angular 5 version. We have integrated angular-calendar with version 0.24.1 but it is not displaying y-axis timeline inside week/day view.
We can not upgrade the angular version so can you please tell me how can we get the timeline in Angular 5 version?

**Screenshots**

![image](https://user-images.githubusercontent.com/55442070/69403883-c184a900-0d21-11ea-9af8-d07420037ecf.png)

**Versions**

- `@angular/core`: 5.2.0
- `angular-calendar`: 0.24.1
- Browser name and version: Chrome

**Comment by mattlewis92** [comment]
Sorry there's no support for this in older versions, the only way to add support is to upgrade your angular version to v6.
