### ISSUE TITLE
Set start and end time for Day View Scheduler, refresh after retrieving events from API & show all users in top row

### ISSUE THREAD

**Issue by cfvilla91** [mattlewis92/angular-calendar#1143]
**Is your feature request related to a problem? Please describe**

Hello
First, great library, i have been using it on my project and i love it.

In a part of my app i'm using the Day View Scheduler as shown in your examples (https://mattlewis92.github.io/angular-calendar/#/day-view-scheduler), but i can't seem to achieve certain things
1-. I store the data and retrieve it via API, but when i set the events to the ones i received from the API, the view doesn't show this changes. When i click anywhere in the scheduler it refreshes, and show the data i retrieved, but i can't make it refresh automatically.
2-. I'm trying to set the start and end time, with no luck.
3-. I'm also trying to show every user in the top row, even if it doesn't have any events yet. The only way i've achieved this is by adding "ghost events" to every user and hiding them via CSS (Hacky AF)

Thanks again for this awesome library.

**Describe the solution you'd like**

1-. A method that i can call to refresth the scheduler view
2-. A way to set start and end times in day view scheduler
3-. A way to show every user in the top row, even when the user has no assigned events yet

**Describe your use case for implementing this feature**

I'm using this as a part of my app, to schedule client sessions with the users in the app.

**Additional context**

Sorry for any grammar problems, english isn't my main language
Thanks again

**Comment by mattlewis92** [comment]
Hey there, here's how to do these things, hope that helps! 😄 

1/ https://mattlewis92.github.io/angular-calendar/#/refreshing-the-view
2/ https://mattlewis92.github.io/angular-calendar/#/day-view-start-end
3/ https://stackblitz.com/edit/angular-iv32be?file=demo/day-view-scheduler.component.html
