### ISSUE TITLE
Change day view column header and hour segment header in day-view scheduler calendar

### ISSUE THREAD

**Issue by Hema12** [mattlewis92/angular-calendar#1146]
Hi,

I am following this documentation:
https://mattlewis92.github.io/angular-calendar/#/day-view-scheduler

**What I would like to do:**
Thank you so musch for this plugin all functions are working fine. I am trying to set hour segment as column headers and users list as row headers which means interchange rows and column headers.

**Screenshots**
![screenshots](https://user-images.githubusercontent.com/13760164/69795548-6a377a80-11f2-11ea-9a92-19d70e534ce7.png)
Versions

@angular/core: 8.2.2
angular-calendar: 0.28.6

**Comment by mattlewis92** [comment]
Sorry there's no way of doing this easily, you'll need to create a custom component to implement this.

**Comment by vamsi98ya** [comment]
Hi.. I want to change the hours column into a column containing some items. How can I do that?
