### ISSUE TITLE
Make the look&feel more similar to FullCalendar.io

### ISSUE THREAD

**Issue by alexsintoni** [mattlewis92/angular-calendar#1153]
**Is your feature request related to a problem? Please describe**

I really like this component, but I could not use it for different projects because the user experience is not like the usual interface that normal users are used to.
Most of the normal users, not computers experts, are used to work with schedulers and calendars with graphical interfaces similar to the one offered by [FullCalendar](https://fullcalendar.io/) component which is also similar to the one offered by Outlook or Google Calendar.

The interface offered by this component is confusing for normal users and it is not very easy to understand when events/appointments last for few days. The current interface offers dots in different day to show such events and users cannot understand it.

For this reason, I could not use this component and I had to use the FullCalendar one for my projects.

**Describe the solution you'd like**

I would be very happy to use this one if it would change the graphical interface with something more standard (Outlook or Google Calendar).

**Describe your use case for implementing this feature**

**Additional context**

**Comment by darshanrampatel** [comment]
Looks related to #758

**Comment by alexsintoni** [comment]
Dear @darshanrampatel 

I think you are correct :)

I close this ticket as duplicated of #758
