### ISSUE TITLE
User hiding in Day View Scheduler.

### ISSUE THREAD

**Issue by abhishek0196** [mattlewis92/angular-calendar#1159]
**Describe the bug**
The bug is in a particular module of the angular calendar, the module is Day View Scheduler([link](https://mattlewis92.github.io/angular-calendar/#/day-view-scheduler)), in the demo if a user is having no events that user is getting removed and in the code given I'm not sure how to disable it. Moreover, if the day is changed the user is no more there.
Please look into it.

**Minimal reproduction of the problem with instructions**
Stackblitz [link](https://stackblitz.com/edit/angular-2jahez), steps for the bug to just drag Another Event under Jane Doe to John Smith and then the user Jane Doe will disappear.

**Screenshots**
![image](https://user-images.githubusercontent.com/13505029/72131805-59f2ed80-33a3-11ea-957d-35fb0d458667.png)
![image](https://user-images.githubusercontent.com/13505029/72131821-64ad8280-33a3-11ea-9ed5-faced26823bc.png)

**Versions**

- `@angular/core`:  "8.2.14"
- `angular-calendar`: "0.28.1"
- Browser name and version: Chrome Version 79.0.3945.88 (Official Build) (64-bit)

**Comment by mattlewis92** [comment]
Hey there, I just updated the demo code and it should fix your issue. All users are now visible regardless of if they have events. Please give it a go and let me know if it works for you 😄
