### ISSUE TITLE
Can't build projects when Ivy compiler is enabled.

### ISSUE THREAD

**Issue by santam85** [mattlewis92/angular-calendar#1161]
**Describe the bug**

Getting the following error when attempting to build a project depending on angular-calendar with ivy enabled:
`Can't bind to 'ngTemplateOutlet' since it isn't a known property of 'ng-template'.`

I think I identified the issue already, fix is on the way

**Minimal reproduction of the problem with instructions**

Go to https://stackblitz.com/edit/angular-ltrkfm?file=demo/component.ts and enable Ivy

**Versions**

angular-calendar: 0.26.2
@angular/core: 8.2.14
@angular/cli: 8.3.21
@angular-devkit/build-angular: 0.803.22

- `@angular/core`: 8.2.14
- `angular-calendar`: 0.28.2
- @angular/cli: 8.3.21
- @angular-devkit/build-angular: 0.803.22
- Browser name and version: not relevant

**Comment by mattlewis92** [comment]
Closing now v9 stable is out: https://github.com/mattlewis92/angular-calendar/pull/1162#issuecomment-592943765
