### ISSUE TITLE
day-view-scheduler visual issues

### ISSUE THREAD

**Issue by ALapaque** [mattlewis92/angular-calendar#1163]
**Describe the bug**

Hi I do have some issues with the view day-view-scheduler below are the description:

### First issue :
In my case I have 8 different users to display in the day-view-scheduler and the day-view-column-header resize the column instead of keeping the same size for the container and add a overflow-x
![scheduler-view-issue1](https://user-images.githubusercontent.com/46450511/72426017-3952db00-3789-11ea-9406-9a7d8547ece9.gif)

## Second issue : 
If you drag and event overlapping an other one this will hide one of the event. could we do something like in the other views ?
![scheduler-view-issue2](https://user-images.githubusercontent.com/46450511/72426413-edecfc80-3789-11ea-82e8-595961922cac.gif)

solution :
![scheduler-view-issue2-solution](https://user-images.githubusercontent.com/46450511/72426449-00ffcc80-378a-11ea-9f63-b21cd6bdfca6.gif)

Thank your for your help :)

**Minimal reproduction of the problem with instructions**

**Screenshots**

**Versions**

- `@angular/core`:7.2.2
- `angular-calendar`:0.28.2
- Browser name and version: Chrome v79.0.3945.117

**Comment by ALapaque** [comment]
@mattlewis92 any news about this ?

**Comment by mattlewis92** [comment]
I'm going to rewrite the day view scheduler as it's full of problem like this and others https://github.com/mattlewis92/angular-calendar/issues/1159 https://github.com/mattlewis92/angular-calendar/pull/1139

I've got some plans that should fix all these issues, I will try my best to get it done next weekend! 😄

**Comment by ALapaque** [comment]
@mattlewis92 That's perfect ! :)
Thanks a lot for your support and your help.

**Comment by mattlewis92** [comment]
Hey there, I just updated the demo code and it should fix your issues. The day view scheduler now behaves exactly like the week view, except each column is a users events rather than a day. Please give it a go and let me know if it works for you 😄

**Comment by ALapaque** [comment]
@mattlewis92 Hi,
thanks for the amazing work. looks like it's working perfectly.
I'm just having something is when I'm calling the component it's not recognizing the attribute from CalendarWeekViewComponent any idea on how to fix this ?
This might be a dumb question, but I'm only a java developer since june 2019 :(

![image](https://user-images.githubusercontent.com/46450511/76312607-b30fcc80-62d3-11ea-9258-134043af7438.png)

Thanks :)

**Comment by ALapaque** [comment]
Also, I think I've found a little issue.

I'm using the attribute (beforeViewRender) to check my segment and my unavailabilitiesPeriods in order to add a class to a segment and display a background like that if it's an unavailable period
![image](https://user-images.githubusercontent.com/46450511/76314842-d2a8f400-62d7-11ea-9ef8-38338db1f08e.png)
It's working for the dayView weekView but  when i'm inspecting in the schedulerView it's not adding my custom-class to the hour-segment.

- it should render like this :

![image](https://user-images.githubusercontent.com/46450511/76314961-0d129100-62d8-11ea-97ba-24821c5b171f.png)

- and it's rendering like this :

![image](https://user-images.githubusercontent.com/46450511/76315270-a477e400-62d8-11ea-905f-fe13d691dae3.png)

- and this is an exemple of this function in weekView :

![image](https://user-images.githubusercontent.com/46450511/76315314-bfe2ef00-62d8-11ea-8b48-83b11166430f.png)

Thanks :)

**Comment by mattlewis92** [comment]
Hey, I'm glad to hear it's working nicely for you 😄 

> I'm just having something is when I'm calling the component it's not recognizing the attribute from CalendarWeekViewComponent any idea on how to fix this ?

I get the same thing, it's a bug with webstorm or the angular language service, it doesn't detect the inheritance. 



> Also, I think I've found a little issue.
> 
> I'm using the attribute (beforeViewRender) to check my segment and my unavailabilitiesPeriods in order to add a class to a segment and display a background like that if it's an unavailable period
> ![image](https://user-images.githubusercontent.com/46450511/76314842-d2a8f400-62d7-11ea-9ef8-38338db1f08e.png)
> It's working for the dayView weekView but when i'm inspecting in the schedulerView it's not adding my custom-class to the hour-segment.
> 
> * it should render like this :
> 
> ![image](https://user-images.githubusercontent.com/46450511/76314961-0d129100-62d8-11ea-97ba-24821c5b171f.png)
> 
> * and it's rendering like this :
> 
> ![image](https://user-images.githubusercontent.com/46450511/76315270-a477e400-62d8-11ea-905f-fe13d691dae3.png)
> 
> * and this is an exemple of this function in weekView :
> 
> ![image](https://user-images.githubusercontent.com/46450511/76315314-bfe2ef00-62d8-11ea-8b48-83b11166430f.png)
> 
> Thanks :)

Can you give this a try? https://github.com/mattlewis92/angular-calendar/commit/4cd268c98313455e96b47c67ad41d1b07c3fb077

**Comment by ALapaque** [comment]
@mattlewis92 works perfectly :)

Thank you

**Comment by kyleabens** [comment]
@mattlewis92 can you release this latest change as a new version?  Thanks!

**Comment by mattlewis92** [comment]
@kyleabens the day view scheduler isn't part of the `angular-calendar` package, it's just a demo: https://mattlewis92.github.io/angular-calendar/#/day-view-scheduler so there's nothing to release on npm

**Comment by hunghnguyen2016** [comment]
Thanks so much for this. I'm trying to display an image instead of user name. Can you advise how to do it?
