### ISSUE TITLE
Commenting the sorting have no effect in the day view scheduler.

### ISSUE THREAD

**Issue by abhishek0196** [mattlewis92/angular-calendar#1164]
**Describe the bug**

The issue which I am facing is that in the [day view scheduler](https://mattlewis92.github.io/angular-calendar/#/day-view-scheduler)  particularly in the file **day-view-scheduler.component.ts** line number **27** even if am commenting the line it has no effect on the sorting.

**Versions**

- `@angular/core`:  "8.2.14"
- `angular-calendar`: "0.28.1"
- Browser name and version: Chrome Version 79.0.3945.88 (Official Build) (64-bit)

**Comment by ALapaque** [comment]
Hey there I had the same issue if I wanted to sort my user on lastName so I did this 

>         view.users.sort((a, b) => {
>             return a.lastName > b.lastName ? 1 : -1;
>         });

and also this line is just a sort for your column order.
