### ISSUE TITLE
Events not showing on first load

### ISSUE THREAD

**Issue by charlenebuena** [mattlewis92/angular-calendar#1170]
**I am using the month view and not all events are showing on first load (Only 1 event showed).**

**When I trigger the calendar like selecting any month on my datepicker, that's the time it shows everything. It only happens on first load. I've used `refresh.next()`, `this.events = [...this.events]`, and I even used subscription but still doesn't work**

ParentComponent
```
<app-creator-profile-calendar [viewDate]="selectedMonth"></app-creator-profile-calendar>

```

CreatorProfileCalendarComponent: 
```
<mwl-calendar-month-view 
        [viewDate]="viewDate"
        [events]="events"
        (dayClicked)="dayClicked($event.day)"
        [refresh]="refresh"
        [cellTemplate]="customCellTemplate"
    >
</mwl-calendar-month-view>

<ng-template #customCellTemplate let-day="day" let-locale="locale">
    <div class="cal-cell-top custom-class" [matTooltip]="day.events[0]?.title" [class]="day.events[0]?.cssClass"
    >
        <span class="cal-day-number">
            {{ day.date | calendarDate:'monthViewDayNumber':locale }}
        </span>
    </div>
</ng-template>
```
Getting of events happen in the CreatorProfileCalendarComponent not in the ParentComponent. But selected date / view date comes from ParentComponent.

```
this.creatorProfileService.getCalendarStatus(this.args).subscribe(
        resp => {
            if (resp['data'].success) {
                for (let item of resp['data'].schedules) {
                    this.events.push({
                        start: new Date(moment(item.date).format('YYYY-MM-DD')),
                        title: item.status,
                        cssClass: item.status.toLowerCase(),
                    });
                }
            }
            this.refresh.next();
    },
```

**Versions**

- `@angular/core`: ~8.2.9
- `angular-calendar`: ^0.28.2

**Comment by ALapaque** [comment]
Hi there, 

could you please create a little stackblitz in order to reporduce the issue and try to debug it for you ?

Kind regards,

**Comment by charlenebuena** [comment]
I'm sorry. It was my mistake. I was passing the current date and not the first day of the month in loading events, which is why it was only showing 1 event. I'm closing this issue. `refresh.next()` really did help
