### ISSUE TITLE
ISSUE drag&drop and context-menu within angular-calendar

### ISSUE THREAD

**Issue by ALapaque** [mattlewis92/angular-calendar#1171]
**Describe the bug**

Hi there, 

I'm using your library which include angular-draggable-droppable and I'm facing an issue.
as the lib angular-draggable-droppable allows to drag and drop with every click of a mouse.
 I'm having dom issues with right click which trigger drag and context-menu. I know this issue is quite hard to trigger and tricky.

Is there a way to only allow the draggable droppable mode on the left click as it's a native way to do it.
See angular material and interactjs for example drag&drop library.
Here below you have a minimal reproduction of the issue. you'll see the ashed segment disapear because of a dom error, and also you'll see context-menu having difficulties to open while dragging etc...

**Minimal reproduction of the problem with instructions**

 I can't create a stackblitz as I'll have to implement all the features behind that...

**Screenshots**

![week-view-conflict-context-and-drag](https://user-images.githubusercontent.com/46450511/73248404-34dbe880-41b3-11ea-8cc0-cff661e0e435.gif)

**Versions**

    "@angular/core": "^7.2.2",
    "angular-calendar": "^0.28.0-beta.3",
- Browser name and version: Google Chrome Version 79.0.3945.130 (Officla build) (64 bits)

Thanks for your great work and support

**Comment by ALapaque** [comment]
@mattlewis92 any news about that ?

**Comment by mattlewis92** [comment]
Hey there, sorry about the late reply, I've been away travelling the past couple months and just catching up now. I just cut a new release of the drag and drop library so that it only fires when using the left click. If you do:
```
npm update angular-draggable-droppable --depth 2
```

Then it should pull in the latest version. Let me know if that works for you! 

p.s. thanks for jumping on some of the issues when I've been away, I really appreciate it! 😄

**Comment by ALapaque** [comment]
Hi, Wow you're my hero haha.
I was displayed unavailabilities hashed period and because of that it was hidding I suppose because of a DOM error... and thanks to that fix it works perfectly.

**Comment by mattlewis92** [comment]
Awesome, I'm glad that it fixed it for you 😄
