### ISSUE TITLE
npm description is outdated, could you update it? 

### ISSUE THREAD

**Issue by haexyh** [mattlewis92/angular-calendar#1172]
**Is your feature request related to a problem? Please describe**

**Describe the solution you'd like**

**Describe your use case for implementing this feature**

**Additional context**

**Comment by mattlewis92** [comment]
Sorry I'm not sure what you mean by your comment, the description is up to date? https://github.com/mattlewis92/angular-calendar/blob/master/package.json#L4

https://www.npmjs.com/package/angular-calendar
