### ISSUE TITLE
draggable AllDay events in WeekView unmovable after dragging bottom most event of stacked events

### ISSUE THREAD

**Issue by lancescape** [mattlewis92/angular-calendar#1173]
**Describe the Bug**
In weekView after drag, the drag feature is frozen until manual browser refresh.  This is due to mouse drop actually being off zone (mwlDroppable) after execution of redraw of the #allDayEventsContainer.   This is only when dragging the bottom most all-day event in a stack.

Due to error, the draggable functionality no longer works until browser refresh is executed. 

**Minimal reproduction of the problem with instructions**
Super simple to replicate.  I only added two stacked draggable allDay events to demo code.

https://stackblitz.com/edit/angular-16bn3j

2) Header drag error - When any all-day event is accidentally dragged in to the header and dropped, the event start/end time is changed.  The start becomes the dropped date, and the end is null .  Not sure if this is a feature or error.

3) Timeslot drag error - Similarly when an all-day event is accidentally dragged to **mwl-calendar-week-view-hour-segment** area of another day, the event end date is set to null.  and this is done on the dragEnter state... so if you drag back to the all-day area, it still sets end time as null.

4) Toast - if you put a toast above the calendar, thus re-positioning the calendar temporarily, drag is not enabled until post disapprears.

**Versions**
current 

I tried various versions of  angular-draggable-droppable it is not related to that.

![allDayBug](https://user-images.githubusercontent.com/961806/73983732-f39eb380-48eb-11ea-9614-c9bc21049594.gif)

![allDayBug](https://user-images.githubusercontent.com/961806/73983603-a3bfec80-48eb-11ea-9193-653103227a02.gif)

**Comment by lancescape** [comment]
Updated the issue report with clearer text and gif of bug

**Comment by mattlewis92** [comment]
Hey, thanks so much for making such a detailed bug report, I really appreciate it. I will take a look at this next weekend and see if I can find a solution 😄

**Comment by JonasJW** [comment]
Hey, I'm having an issue that might be related to this. I tried making the allDay Event Bar larger with these css classes:

```
.cal-week-view .cal-all-day-events .cal-event {
    height: 60px !important;
}

.cal-all-day-events {
    height: 65px;
}
```

This way, the drag features stops working with just one allDay event.

**Comment by mattlewis92** [comment]
Hey there, I'm so sorry about the delay with getting to this, please give `0.28.9` a try, this should be fixed now 😄

**Comment by lancescape** [comment]
Hey Awesome job!    argh I should have figured it was just the drop event in the hour grid.  
It works perfectly now!
