### ISSUE TITLE
angular 5 documentation

### ISSUE THREAD

**Issue by webspecialist** [mattlewis92/angular-calendar#1175]
on GitHub: https://github.com/mattlewis92/angular-calendar/tree/v0.24.1

Where can I find documentation for angular 5? What I saw until now is for v 6+.
My purpose is to integrate to IONIC 3 that works with 5 version.

**Comment by mattlewis92** [comment]
Unfortunately there is no way of viewing older versions with the documentation tool I use for making the docs. What you can do is checkout the repo locally on that git tag and run `npm run compodoc` which will generate the docs locally in the `docs` folder.
