### ISSUE TITLE
Moment adapter do not implements < weekStartsOn > option 

### ISSUE THREAD

**Issue by mohamed-badaoui** [mattlewis92/angular-calendar#1176]
" weekStartsOn " option allow to start the calendar by an another day than sunday.

This works only with date-fns adapter. It is not implemented on moment adapter.

**Comment by mattlewis92** [comment]
This is because moment doesn't have an api that supports this, you have to set it globally like:

```
moment.updateLocale('en', {
  week: {
    dow: DAYS_OF_WEEK.MONDAY,
    doy: 0
  }
});
```
