### ISSUE TITLE
Angular Calendar - Positioning SSR Issue

### ISSUE THREAD

**Issue by pisix** [mattlewis92/angular-calendar#1177]
**Describe the bug**

I am trying to run SSR on my project, but I am facing the problem below which is related to the angular-calendar library

```
)(window, function() {
   ^
ReferenceError: window is not defined
    at Object../node_modules/angular-calendar/node_modules/positioning/dist/umd/positioning.js (main.js:216360:4)
    at __webpack_require__ (main.js:20:30)
    at Module../node_modules/angular-calendar/__ivy_ngcc__/fesm2015/angular-calendar.js (main.js:211113:69)
    at __webpack_require__ (main.js:20:30)
    at Object../src/app/pro/agenda/agenda.component.ts (main.js:472512:28)
    at __webpack_require__ (server/main.js:20:30)
    at Object../src/app/pro/pro.module.ts (main.js:478761:28)
    at __webpack_require__ (main.js:20:30)
    at Object../src/app/app.module.ts (main.js:460489:22)
    at __webpack_require__ (main.js:20:30)
```

A server error has occurred.

**Screenshots**

**Versions**

- `@angular/core`: 9.0.0
- `angular-calendar`: 0.28.2"
- Browser name and version: Chrome

**Comment by smokinguns** [comment]
looks like past versions have worked with SSR. Hoping this will be resolved.

**Comment by pisix** [comment]
which version for example.

**Comment by smokinguns** [comment]
#997 is closed, but shows where they got it working

**Comment by mattlewis92** [comment]
Please can you give `0.28.3` a try, this should be fixed now 😄

**Comment by smokinguns** [comment]
@mattlewis92 haven't verified, but sent you a thank you via pay pal. Hopefully it's enough for a pint ;)

**Comment by smokinguns** [comment]
@mattlewis92 does this require the domino package mentioned in #997 for SSR? Now I'm getting window not defined.

**Comment by mattlewis92** [comment]
> @mattlewis92 haven't verified, but sent you a thank you via pay pal. Hopefully it's enough for a pint ;)

Thank you so much! ❤️ 



> @mattlewis92 does this require the domino package mentioned in #997 for SSR? Now I'm getting window not defined.

You might need to patch your webpack server config like this for it to work: https://github.com/mattlewis92/angular-calendar/issues/997#issuecomment-502455889

If that still doesn't work, would you be able to make me a minimal repro on github that shows your issue and I can debug further? Thanks! 😄

**Comment by smokinguns** [comment]
@mattlewis92 ok, got it to build. Should it be able to render SSR. Sorry this is my first attempt at SSR. When I put in page, the request never returns.  I pushed up sample repo. I appreciate your help.

https://github.com/smokinguns/bug-free-potato

**Comment by mattlewis92** [comment]
Thanks so much for taking the time to put up a repro it really helped, the issue was specific to the day and week view which was why it was working for me (I was testing on the month view). I just released `0.28.4` with a fix and it appears to be working nicely on your repo now 😄

**Comment by smokinguns** [comment]
works... you saved my timeline... another token coming your way

**Comment by mattlewis92** [comment]
Awesome, that's great to hear, and thank you! I really appreciate it 😄
