### ISSUE TITLE
Getting duration when resizing an event (resizing event?)

### ISSUE THREAD

**Issue by jeanft** [mattlewis92/angular-calendar#1178]
Hi,

First, thanks for developing this calendar. We are still evaluating if it is a good fit for our new app.
Is it possible to get the duration of a Calendar Event when resizing? 
We would like to display the total hours of a day during resizing a single Calendar Event and we want to sum it live, while the user do the resizing.

Thanks

**Comment by ALapaque** [comment]
@jeanft Hi there I guess you can have every thing you want by using a custom template on the event and by this you'll trigger the action of resize and so. After that if the angular-resizable doesn't throw event well @mattlewis92 will be the best to answer that

**Comment by jeanft** [comment]
Thank you @ALapaque , exactly what I'm looking for.
