### ISSUE TITLE
viewDateChange fired before viewDate is updated

### ISSUE THREAD

**Issue by ricardosaracino** [mattlewis92/angular-calendar#1179]
changing the order of these yeilds the wrong date

```
    <div
        class="btn btn-primary"
        mwlCalendarPreviousView
        (viewDateChange)="fetchEvents()"
        [(viewDate)]="viewDate"
        [view]="view"
      >
        Previous
      </div>
```
Hit next and check console log

https://stackblitz.com/edit/angular-kcqaxw?file=demo%2Fcomponent.ts

**Screenshots**
![image](https://user-images.githubusercontent.com/759253/74745180-764f3900-5231-11ea-8c89-b96f4b1c07c2.png)

**Versions**

    "angular-calendar": "0.28.1",
    "angular-calendar": "0.28.1",
chrome 79

**Comment by ricardosaracino** [comment]
work around ... ` setTimeout(() => console.log('delay', this.viewDate), 10);`

**Comment by mjtrjk** [comment]
> work around ... ` setTimeout(() => console.log('delay', this.viewDate), 10);`

you could even change the order to
```
[(viewDate)]="viewDate"
(viewDateChange)="fetchEvents()"
```

this is caused by Angular´s banana-in-a-box syntax sugar -> https://angular.io/guide/template-syntax#two-way-binding-

**Comment by ricardosaracino** [comment]
> > work around ... ` setTimeout(() => console.log('delay', this.viewDate), 10);`
> 
> you could even change the order to
> 
> ```
> [(viewDate)]="viewDate"
> (viewDateChange)="fetchEvents()"
> ```
> 
> this is caused by Angular´s banana-in-a-box syntax sugar -> https://angular.io/guide/template-syntax#two-way-binding-

Code formater rearranges order so this is problematic assuming order

**Comment by mjtrjk** [comment]
> 
> 
> > > work around ... ` setTimeout(() => console.log('delay', this.viewDate), 10);`
> > 
> > 
> > you could even change the order to
> > ```
> > [(viewDate)]="viewDate"
> > (viewDateChange)="fetchEvents()"
> > ```
> > 
> > 
> > this is caused by Angular´s banana-in-a-box syntax sugar -> https://angular.io/guide/template-syntax#two-way-binding-
> 
> Code formater rearranges order so this is problematic assuming order

You can then de-sugar it yourself.
```html
[viewDate]="viewDate"
(viewDateChange)="viewDate = $event; fetchEvents()"
```

**Comment by mattlewis92** [comment]
This is just how angular works, there's nothing I can do my end to fix this. Another possible workaround is to do `(viewDateChange)="fetchEvents($event)"` where $event will contain the new date
