### ISSUE TITLE
demo.component.ts (20,8): Cannot find module './../src'.)     at _checkDiagnostics at node_modules/@ngtools/webpack/src/loader.js:116:15

### ISSUE THREAD

**Issue by anarinsky** [mattlewis92/angular-calendar#118]
I have an angular-cli application and installed  demo.component.ts into the src/app directory.

At Running got the error:
ERROR in ./src/app/demo.component.ts
Module build failed: Error: /Users/anarinsky/Dropbox/rentapp/Angular/cli/my1/src/app/demo.component.ts (20,8): Cannot find module './../src'.)
    at _checkDiagnostics (/Users/anarinsky/Dropbox/rentapp/Angular/cli/my1/node_modules/@ngtools/webpack/src/loader.js:116:15)
    at /Users/anarinsky/Dropbox/rentapp/Angular/cli/my1/node_modules/@ngtools/webpack/src/loader.js:141:17
 @ ./src/app/app.module.ts 16:0-49
 @ ./src/main.ts
 @ multi main

**Comment by mattlewis92** [comment]
The import should be from 'angular-calendar' and not from the src which only exists in this repo.
