### ISSUE TITLE
Cannot read property 'rowOffsets' of undefined

### ISSUE THREAD

**Issue by shachar583** [mattlewis92/angular-calendar#1184]
Hello,
I've been using angular-calendar a year ago and it all worked just perfect.
Ever since, I've updated some of the packages and it doesn't work anymore.
The errors I get is:
ERROR TypeError: Cannot read property 'rowOffsets' of undefined

@angular/core: 8.1.1
angular-calendar: 0.28.2
@angular/cli: 8.1.1
@angular-devkit/build-angular: 0.801.1

Thanks!

**Comment by ALapaque** [comment]
@shachar583 Hi there, could you put a minimal reproduction on stackblitz in order to check your packages and so ?

**Comment by shachar583** [comment]
@ALapaque Hi, here is the link for the stackblitz:
https://stackblitz.com/edit/calendar-min-test

Thank you!

**Comment by mattlewis92** [comment]
Thanks for taking the time to make a repro, that really helped me find your issue 😄 

The problem is caused by:
```
        CalendarModule.forRoot({
            provide: DateAdapter,
            useFactory: NativeDateModule
          }),
```

You're passing a module from angular material which won't work with the calendar. You need to pass the calendar own date adapter like this:

```
import { adapterFactory } from 'angular-calendar/date-adapters/date-fns';

  CalendarModule.forRoot({
            provide: DateAdapter,
            useFactory: adapterFactory
          }),
```

Hope that helps! 😄

**Comment by shachar583** [comment]
@mattlewis92 Thank you so much, it works!

**Comment by deepeshSharma-jvs** [comment]
Hi @mattlewis92
this same issue i am getting when I am working on a project to upgrade angular version .

"@agm/core": "^1.1.0",
"@angular-devkit/build-ng-packagr": "^0.1002.0",
"@angular-redux/store": "^9.0.0",
"@angular/animations": "^11.0.7",
"@angular/cdk": "^11.0.3",
"@angular/common": "^11.0.7",
"@angular/compiler": "^11.0.7",
"@angular/core": "^11.0.7",
"@angular/forms": "^11.0.7",
"angular-calendar": "^0.28.21",

In case of month i am getting this issue also Cannot read property 'rowOffsets' of undefined.
please help to solve this issue asap.

![image](https://user-images.githubusercontent.com/88198285/127668796-36dd27d4-b180-493b-98af-998f4a8c1078.png)

![image](https://user-images.githubusercontent.com/88198285/127668838-92dd0a6a-f4d9-46be-a5e4-98f0c51e6373.png)

**Comment by deepeshSharma-jvs** [comment]
> Hi @mattlewis92
> this same issue i am getting when I am working on a project to upgrade angular version .
> 
> "@agm/core": "^1.1.0",
> "@angular-devkit/build-ng-packagr": "^0.1002.0",
> "@angular-redux/store": "^9.0.0",
> "@angular/animations": "^11.0.7",
> "@angular/cdk": "^11.0.3",
> "@angular/common": "^11.0.7",
> "@angular/compiler": "^11.0.7",
> "@angular/core": "^11.0.7",
> "@angular/forms": "^11.0.7",
> "angular-calendar": "^0.28.21",
> 
> In case of month i am getting this issue also Cannot read property 'rowOffsets' of undefined.
> please help to solve this issue asap.
> 
> ![image](https://user-images.githubusercontent.com/88198285/127668796-36dd27d4-b180-493b-98af-998f4a8c1078.png)
> 
> ![image](https://user-images.githubusercontent.com/88198285/127668838-92dd0a6a-f4d9-46be-a5e4-98f0c51e6373.png)
