### ISSUE TITLE
Issue with loading data on page load

### ISSUE THREAD

**Issue by dev7asp** [mattlewis92/angular-calendar#1185]
I am using the calendar to display appointments in "day view scheduler", getting records from server end and binding event to calendar but I am facing a issue to load data in view when page loads or when I insert new event and it is showing if i do next or previous but not first time when data load. I have tried to figure out it with the help of this.refresh.next() or by calling change detector when data loads and add to calendar events but no luck.
Please suggest me any event or the way so that I can able to see my data in calendar view on page loads or whenever new data added.
Thanks

**Comment by ahmedfatnassi** [comment]
i'am facing same problem ,well ,  the data is loaded in the view when i used this.refresh .next() in ngOnInit   ,but  in the other methods i'am having the same problem 
thanks for helping  me .

**Comment by ALapaque** [comment]
@dev7asp && @ahmedfatnassi 
I don't recommend you to use this view as there's a fews issues already posted about it...

#1159 
#1163

**Comment by mattlewis92** [comment]
This issue has been closed as it did not follow the issue template, please **open a new issue** that follows the bug report or feature request template.<br><br>
If you would like to submit a support issue or get a faster reply, please consider [sponsoring me](https://github.com/users/mattlewis92/sponsorship).<br><br>
Thank you! ✌️
