### ISSUE TITLE
Become a sponsor on Github to ask questions

### ISSUE THREAD

**Issue by vickymartineee** [mattlewis92/angular-calendar#1186]
Hi,I want to know how I could add the title of the events to display on the month view.,

**Comment by mattlewis92** [comment]
This issue has been closed as it did not follow the issue template, please **open a new issue** that follows the bug report or feature request template.<br><br>
If you would like to submit a support issue or get a faster reply, please consider [sponsoring me](https://github.com/users/mattlewis92/sponsorship).<br><br>
Thank you! ✌️
