### ISSUE TITLE
 mwl-calendar-month-view viewDate not updating after view initialization

### ISSUE THREAD

**Issue by sarikonda1** [mattlewis92/angular-calendar#1187]
I am using mwl-calendar-month-view component for calendar. when i update viewDate the after some api call/setTimeout the date is not highlighting. Even i tried with refresh.next() this will change the calendar month only still not highlighting particular date.. let me know anyone have solution for this one ?

**Comment by mattlewis92** [comment]
This issue has been closed as it did not follow the issue template, please **open a new issue** that follows the bug report or feature request template.<br><br>
If you would like to submit a support issue or get a faster reply, please consider [sponsoring me](https://github.com/users/mattlewis92/sponsorship).<br><br>
Thank you! ✌️
