### ISSUE TITLE
How to set that week starts from monday, instead of sunday .

### ISSUE THREAD

**Issue by arvind-das** [mattlewis92/angular-calendar#119]
Hi,

I was trying out this cool calendar and needed some functionality with is, with the original bootstrap calendar, I could set the starting day of week as monday, how can I do that here ?

In the original plugin it is available as 

```
var defaults_extended = {
		first_day: 2
}

```

in calendar.js file, setting it to 1 will start week from Monday, how can I perform same here ?
Please help.

Thanks

**Comment by no-more** [comment]
Hi,

you can add `weekStartsOn="1"` on the component.

**Comment by mattlewis92** [comment]
^ what @no-more said, docs are here: https://mattlewis92.github.io/angular-calendar/docs/classes/calendarmonthviewcomponent.html#weekstartson

**Comment by anhdx** [comment]
on view [weekStartsOn]="1"
