### ISSUE TITLE
Short events are almost invisible in weekly/daily view

### ISSUE THREAD

**Issue by tadzik** [mattlewis92/angular-calendar#1192]
With the event short enough (15 minutes or less) it becomes almost invisible, and certainly unreadable in weekly/daily view with default styling.

Stackblitz example: https://stackblitz.com/edit/angular-bshxze?file=demo%2Fcomponent.ts (forked off of kitchen-sink demo).

**Screenshots**

![2020-03-11-161926_1515x479_scrot](https://user-images.githubusercontent.com/86378/76433070-16712b80-63b4-11ea-81e4-92ad680e5d63.png)

**Versions**

Reproducible on 0.28.5 (latest at the time of writing) on both Angular 8 and 9.

**Comment by mattlewis92** [comment]
Hey there, thanks for opening an issue. It's certainly a bit of a weird UX, I think there should be an option to set the minimum height of events on the day and week view and this is something I'll work on adding. 

In the meantime you can use a fake end date like this to set a minimum height of 30 pixels: https://stackblitz.com/edit/angular-bshxze-wccw8h?file=demo/component.ts 

You could also use the `hourSegments` option to make each segment bigger: https://mattlewis92.github.io/angular-calendar/#/day-view-hour-split

Let me know if that works for you 😄

**Comment by tadzik** [comment]
We already use fake end dates extensively for ical integration, so [this](https://github.com/runbox/runbox7/pull/492/commits/0c4a437578c01bbe16b26c79c1101859f8c77585) feels right at home ;)

Thanks, and let me know if a builtin solution becomes available :)

**Comment by mattlewis92** [comment]
Hey there, I just released a beta of `0.29` with this fix. You can find instructions on how to update to it here: https://github.com/mattlewis92/angular-calendar/pull/1249 Please can you give it a try and let me know if it works for you, thanks! 😄

**Comment by tadzik** [comment]
Yep, this fixes it for us :)

**Comment by mattlewis92** [comment]
Awesome, that's great to hear! 😄
