### ISSUE TITLE
Week view allday events don't show

### ISSUE THREAD

**Issue by TheLamed** [mattlewis92/angular-calendar#1194]
**Describe the bug**
Hello!
all day events don't show in week view. But in month they are visible.
![image](https://user-images.githubusercontent.com/56411527/76540622-0ed08600-648b-11ea-8d6a-6ee15de17471.png)
![image](https://user-images.githubusercontent.com/56411527/76540642-142dd080-648b-11ea-97d1-927a61aacd69.png)

**Minimal reproduction of the problem with instructions**
```
this.events = [ 
  new CalendarEventModel({
    startDate: moment("10/03/2020", "DD/MM/YYYY"), 
    startTime: "01:00", 
    endDate: moment("17/03/2020", "DD/MM/YYYY"),
    endTime: "01:00", 
    allDay: true 
  }), 
];
```
As I see it
![image](https://user-images.githubusercontent.com/56411527/76609140-8ea83000-651f-11ea-80c1-0471efa94e87.png)
component doesn't count this event.

BUT if i don't set end date it's works good.

**Screenshots**
![image](https://user-images.githubusercontent.com/56411527/76540691-2a3b9100-648b-11ea-946b-9f12088e1339.png)

Do you have any solution to fix this?
(We are using class witch implements CalendarEvent, mabe problem in it?)

Also i try to change versions and this didn't help.

**Versions**

- `@angular/core`:  1.0.0
- `angular-calendar`: 0.28.5, 0.27. ..., 0.26. ...
- Browser name and version: Chrome

**Comment by mattlewis92** [comment]
Hey there, I wasn't able to reproduce your problem: https://stackblitz.com/edit/angular-uncqii?file=demo/component.ts Please could you make a minimal repro on stackblitz or something that shows your issue, as without that it's pretty much impossible to tell what's going wrong. Thank you! 😄

**Comment by wlr** [comment]
I have still this issue, check this bug, i modified the lib and it worked, but you should provide the fix:
https://github.com/mattlewis92/angular-calendar/issues/1149

**Comment by wlr** [comment]
ok guys, i found the problem, check the date-fns lib, it should be > 2.0, i was using the 1.x version somehow! very thx to mattlewis92, i checked the package.js :) stupid bug :(
