### ISSUE TITLE
How to show some dates differently (month view)

### ISSUE THREAD

**Issue by no-more** [mattlewis92/angular-calendar#120]
Hi,

Is it possible to show some date differently, for example public holidays could be with a different background color, or weekend's days could be grayed (or even disabled completely) ?

Thanks

**Comment by mattlewis92** [comment]
Some helper classes are already added to each cell: https://github.com/mattlewis92/angular-calendar/blob/master/src/components/month/calendarMonthCell.component.ts#L30-L36

For everything else use the `dayModifier` input, to add CSS classes: https://mattlewis92.github.io/angular-calendar/docs/classes/calendarmonthviewcomponent.html#daymodifier
