### ISSUE TITLE
All day event on day view scheduler

### ISSUE THREAD

**Issue by kyleabens** [mattlewis92/angular-calendar#1200]
**Is your feature request related to a problem? Please describe**
After implementing the day view scheduler and switching an event to all day it is no longer displayed on the day view scheduler. https://mattlewis92.github.io/angular-calendar/#/day-view-scheduler

**Describe the solution you'd like**
I would like for all day events to appear just like on the day view except under each column header being users in my case that are assigned to certain tasks.

**Describe your use case for implementing this feature**
I use the day view scheduler to assign tasks to users and these tasks can span multiple days so I give my users the ability to change an event to an all day event so their calendar isn't so crowded.

**Additional context**

**Comment by mattlewis92** [comment]
Yeah I think this makes sense, I just added it to the demo. Let me know if that works for you 😄 https://github.com/mattlewis92/angular-calendar/commit/faaa709af51449a68279c8c766b4f046e1df425f
