### ISSUE TITLE
Right/Left drag move opposite in RTL

### ISSUE THREAD

**Issue by yaniv14** [mattlewis92/angular-calendar#1203]
**Describe the bug**

When using angular-calendar in RTL the dragable event is moving opposite direction on mouse drag.
move mouse right drag the event left and other way.
up and down dragging working properly 

**Minimal reproduction of the problem with instructions**

Set body dir attribute to rtl or css style direction: rtl

**Versions**

- `@angular/core`: 9.0.7
- `angular-calendar`: 0.28.5
- Browser name and version: Chrome 80.0.3987.149 on Ubuntu 18.04

**Comment by mattlewis92** [comment]
Hey there, right now there is no support for RTL calendars, if this is something you would be interested in working on I would happily accept a pull request that makes the calendar support RTL 😄

**Comment by yaniv14** [comment]
Hi,

Can you please point me to where should I start?

**Comment by mattlewis92** [comment]
Sure thing! In the `ngAfterViewInit` event of the [week view component](https://github.com/mattlewis92/angular-calendar/blob/master/projects/angular-calendar/src/modules/week/calendar-week-view.component.ts) you can add:
```
this.isRtl = getComputedStyle(this.element.nativeElement).direction === 'rtl'
```

and then change [this](https://github.com/mattlewis92/angular-calendar/blob/master/projects/angular-calendar/src/modules/week/calendar-week-view.component.ts#L136) to `marginRight` if `isRtl` and the same in this [place](https://github.com/mattlewis92/angular-calendar/blob/master/projects/angular-calendar/src/modules/week/calendar-week-view.component.ts#L272)

and then you'll probably need to adjust the logic for [all day event resizing](https://github.com/mattlewis92/angular-calendar/blob/master/projects/angular-calendar/src/modules/week/calendar-week-view.component.ts#L865-L872) and for [time event resizing](https://github.com/mattlewis92/angular-calendar/blob/master/projects/angular-calendar/src/modules/week/calendar-week-view.component.ts#L1267-L1297)

and then to fix drag and drop you'll probably need to flip [this logic](https://github.com/mattlewis92/angular-calendar/blob/master/projects/angular-calendar/src/modules/week/calendar-week-view.component.ts#L1159) to something like 

```
const daysDragged = (roundToNearest(dragEndEvent.x, dayWidth) / dayWidth) * (this.isRtl ? -1 : 1);
```

Let me know if you need any more guidance 😄

**Comment by yaniv14** [comment]
Hi,
As for guidance, you could not do it better.
But I am wondering if RTL support is not something that you consider adding to the project.
I know I am using is with Hebrew lang only, but also Arabic lang is RTL and its quite common language.
If by any chance you will decide to create a separate branch for RTL I will be more than happy to run tests on it.

**Comment by mattlewis92** [comment]
Hey there, I spent a while playing around with it today and I think I managed to add full support for RTL out of the box, please can you give it a go? You can test it out by doing:
```
npm i angular-calendar@next
```

Thanks! 😄

**Comment by yaniv14** [comment]
All looking perfect on my tests.
I did get a small warning regarding mismatch number of arguments between super and constructor, see attach image.
![Screenshot from 2020-05-16 21-35-08](https://user-images.githubusercontent.com/3071129/82127618-b8026800-97bd-11ea-978a-1839583e031a.png)

Thanks for everything, you project is amazing, and your support is flawless.

**Comment by mattlewis92** [comment]
> All looking perfect on my tests.

That's great to hear! 😄 (and thanks for your donation, I really appreciate it! ❤️ )

> I did get a small warning regarding mismatch number of arguments between super and constructor, see attach image.

You'll need to update your code like this:
![image](https://user-images.githubusercontent.com/6425649/82140528-0bf56700-9827-11ea-9a3c-8f208d84941a.png)

**Comment by rmfogel** [comment]
How do I use the rtl mode?

**Comment by aseemkatoch001** [comment]
Hey I have face issue in week view my event is showing wrong day.
For Example (suppose if  I have  some event on 17 sept that is show in 13 sept in week view but in moth view its show on 17th)

This issue in Arabic language English its working fine 

kindly help me on this  its very needful.
