### ISSUE TITLE
angular-calendar - "window is not defined". Angular 9 SSR

### ISSUE THREAD

**Issue by rysal32** [mattlewis92/angular-calendar#1211]
**Describe the bug**

I installed your plugin to my project which is in Angular 9 and I have an issue because when I wrote "npm run serve:ssr", it always came up with this error, "window is not defined". In server.ts, I already added those two lines of codes:

global['window'] = {};
global['KeyboardEvent'] = null;

However, it didn't solve everything. I have checked everywhere to find the solution.

Can you please help me to resolve this issue?

Thank you.

**Versions**

- `@angular/core`: "~9.1.0"
- `angular-calendar`: ""^0.28.5"

**Comment by nulee** [comment]
Seems like this issue is not specific to Angular 9. It also occurs while using `@angular/core`: "~8.2.4".
`npm run serve:ssr` fails with the following error: _TypeError: window.addEventListener is not a function_

**Comment by mattlewis92** [comment]
Thanks for opening an issue, I've managed to find a way to make SSR work out the box without any hacks, please can you update to `0.28.7` and let me know if that works for you. Thanks! 😄

**Comment by rysal32** [comment]
> Thanks for opening an issue, I've managed to find a way to make SSR work out the box without any hacks, please can you update to `0.28.7` and let me know if that works for you. Thanks! 😄

Thank you very very much @mattlewis92. You saved my day!! :) 👍 👍 👍

**Comment by mattlewis92** [comment]
Awesome, I'm glad to hear that it's fixed for you 😄
