### ISSUE TITLE
Error while building within ng 9

### ISSUE THREAD

**Issue by marcio199226** [mattlewis92/angular-calendar#1214]
Hi I have some issues while adding your module & build it with ng 9

```
    ERROR in node_modules/angular-calendar/modules/calendar.module.d.ts:23:75 - error NG6005: CalendarModule.forRoot returns a ModuleWithProviders type without a generic type argument. Please add a generic type argument to the ModuleWithProviders type. If this occurrence is in library code you don't control, please contact the library authors.
    
    23     static forRoot(dateAdapter: Provider, config?: CalendarModuleConfig): ModuleWithProviders;
```

This error is self-explainable, you should only add default type to forRoot method as described [here](https://angular.io/guide/deprecations#modulewithproviders-type-without-a-generic)

I hope that adding default return type to forRoot would turn into ng9 compatibility

**Versions**
```
Angular CLI: 9.0.5
Node: 12.16.1
OS: linux x64

Angular: 9.0.5
... animations, cli, common, compiler, compiler-cli, core
... elements, forms, language-service, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.5
@angular-devkit/build-angular      0.900.5
@angular-devkit/build-optimizer    0.900.5
@angular-devkit/build-webpack      0.900.5
@angular-devkit/core               9.0.5
@angular-devkit/schematics         9.0.5
@angular/cdk                       9.1.1
@angular/flex-layout               9.0.0-beta.29
@angular/http                      7.2.7
@angular/material                  9.1.1
@angular/material-moment-adapter   9.1.1
@ngtools/webpack                   9.0.5
@schematics/angular                9.0.5
@schematics/update                 0.900.5
rxjs                               6.5.4
typescript                         3.7.5
webpack                            4.41.2
```

**Comment by mattlewis92** [comment]
Hey there, thanks for opening an issue and sending a PR. It's really strange because I'm using the calendar in several apps with ivy and not getting this error. But should be fixed now in `0.28.6` 😄

**Comment by rysal32** [comment]
> Hey there, thanks for opening an issue and sending a PR. It's really strange because I'm using the calendar in several apps with ivy and not getting this error. But should be fixed now in `0.28.6` 😄

Thank you very very much @mattlewis92. You saved my day!! :) 👍 👍 👍

**Comment by marcio199226** [comment]
Hey I'm think is not related to ivy but to some version above 9.0.x which introduces [this](https://angular.io/guide/deprecations#modulewithproviders-type-without-a-generic)

**Comment by mattlewis92** [comment]
> Hey I'm think is not related to ivy but to some version above 9.0.x which introduces [this](https://angular.io/guide/deprecations#modulewithproviders-type-without-a-generic)

It's very odd as I'm not able to reproduce at all in my app and I've been using every version of 9.x as it's released 🤷‍♂️ Luckily the fix is pretty straightforward 😄
