### ISSUE TITLE
Before view render demo

### ISSUE THREAD

**Issue by abritopach** [mattlewis92/angular-calendar#1219]
**Describe the bug**

If you modify the beforeWeekViewRender method and select the first day of the week that appears (in this case Sunday) the hours column is painted as shown in the attached image

```
beforeWeekViewRender(renderEvent: CalendarWeekViewBeforeRenderEvent) {
    renderEvent.hourColumns.forEach((hourColumn) => {
      hourColumn.hours.forEach((hour) => {
        hour.segments.forEach((segment) => {
          if (
            segment.date.getHours() >= 2 &&
            segment.date.getHours() <= 5 &&
            segment.date.getDay() === 0
          ) {
            segment.cssClass = 'bg-pink';
          }
        });
      });
    });
  }
```

**Minimal reproduction of the problem with instructions**

Before view render stackblitz

**Screenshots**

<img width="1439" alt="Screenshot 2020-04-10 at 13 54 49" src="https://user-images.githubusercontent.com/2934069/78989394-ccef3a00-7b33-11ea-916f-3dd5e3155036.png">

**Comment by mattlewis92** [comment]
Hey there, thanks for opening an issue, I just fixed the demo code styling to avoid this issue. Let me know if that works ok for you 😄

**Comment by abritopach** [comment]
@mattlewis92  Fixed! Thank you
