### ISSUE TITLE
I've updated from version 0.24.1 to 0.28.8 and it's giving me an error

### ISSUE THREAD

**Issue by Foundation29hub** [mattlewis92/angular-calendar#1223]
**Describe the bug**

I've updated from version 0.24.1 to 0.28.8 and it's giving me an error

> ERROR in src/app/user/calendar/calendar.component.ts:78:7 - error TS2322: Type '({ event }: { event: MyEvent; }) => void' is not assignable to type '({ event, sourceEvent, }: { event: CalendarEvent; sourceEvent: MouseEvent | KeyboardEvent; }) => any'.
Types of parameters '__0' and '__0' are incompatible.
Type '{ event: CalendarEvent; sourceEvent: MouseEvent | KeyboardEvent; }' is not assignable to type '{ event: MyEvent; }'.
Types of property 'event' are incompatible.
Type 'CalendarEvent' is missing the following properties from type 'MyEvent': _id, GUID, type, duracion, and 14 more.

```
`interface MyEvent extends CalendarEvent { _id: any; GUID: any; type: any; ... }

actions: CalendarEventAction[] = [ { label: '', onClick: ({ event }: { event: MyEvent }): void => { this.handleEvent('Edit this event', event); } }, { label: '', onClick: ({ event }: { event: MyEvent }): void => { this.events = this.events.filter(iEvent => iEvent !== event); this.eliminarSeizure(event); //this.handleEvent('This event is deleted!', event); } } ];`
```
 

**Minimal reproduction of the problem with instructions**

**Screenshots**

**Versions**

- `@angular/core`: 9.0.2
- `angular-calendar`: 0.28.8
- Browser name and version: Firefox 75.0

**Comment by mattlewis92** [comment]
Hi there, sorry to hear you're experiencing issues, please would you mind putting together a minimal reproduction of your problem on stackblitz, as without that it's impossible to really know what's going on. Thank you! 😄
