### ISSUE TITLE
Build error with Angular v9

### ISSUE THREAD

**Issue by abhishekbadola** [mattlewis92/angular-calendar#1225]
**Describe the bug**
Hi Matt,
It is throwing build error after updating my project to angular version 9. It shows template errors in my custom template which is being passed to angular-calendar. I have attached screenshots for reference.

**Minimal reproduction of the problem with instructions**

Just tried after upgrading to angular latest version (9.1.1). Worked with angular 7.

**Screenshots**

![image](https://user-images.githubusercontent.com/19638346/79259736-cef62780-7eaa-11ea-8a7b-bd58fd233a12.png)

![image](https://user-images.githubusercontent.com/19638346/79259465-6313bf00-7eaa-11ea-8f09-ad6ac0209be2.png)

**Versions**

- `@angular/core`: 9.1.1
- `angular-calendar`: 0.28.8

**Comment by mattlewis92** [comment]
Hi there, sorry to hear you're experiencing issues, please would you mind putting together a minimal reproduction of your problem on stackblitz, as without that it's impossible to really know what's going on. Thank you! 😄

**Comment by abhishekbadola** [comment]
Sure Matt, I will try to produce a minimal reproduction if possible. Thanks.
