### ISSUE TITLE
Events either draggable or clickable exclusively?

### ISSUE THREAD

**Issue by haffla** [mattlewis92/angular-calendar#123]
### Versions

Angular: 2.2.3
Calendar library: 0.6.1
Browser name and version: Chrome 55.0.2883.87 (64-bit)

Hi,

are events either draggable OR clickable? Both works fine, but not together. With `draggable: true` a click on the event does nothing and then the event is actually not draggable anymore.
In fact the example in the demos page demonstrates this:

https://mattlewis92.github.io/angular-calendar/demos/#/draggable-events

Or am I missing something? Sorry, if so.

**Comment by mattlewis92** [comment]
Ah yeah that does seem like a bug, will get that fixed up in the next release!

**Comment by awsaunier** [comment]
When is the next release estimated to be released?

**Comment by mattlewis92** [comment]
I'll try and get to it tomorrow or this weekend, it's completely limited by my spare time 😃

**Comment by mattlewis92** [comment]
Should be fixed now in 0.6.2, thanks for reporting! 😃

**Comment by haffla** [comment]
Thanks so much
