### ISSUE TITLE
Drag and drop on same day does not update time in custom title formatter

### ISSUE THREAD

**Issue by tim-faase** [mattlewis92/angular-calendar#1238]
**Describe the bug**

Dragging an event on week view within the same day does not update the time shown in custom title formatter.

**Minimal reproduction of the problem with instructions**

https://stackblitz.com/edit/angular-wm4ozr

**Screenshots**

![Edit Schedule _ DASH - Testing](https://user-images.githubusercontent.com/7435810/79931339-23426e00-848e-11ea-9c95-e596f74a0bfe.gif)

**Versions**

- `@angular/core`: 9.1.1
- `angular-calendar`: 0.28.8
- Browser name and version: Version 81.0.4044.122 (Official Build) (64-bit)

**Comment by mattlewis92** [comment]
Hey, thanks for reporting! I'm kind of amazed this has never come up before, I will do my best to find a way of fixing it 😄

**Comment by mattlewis92** [comment]
Please can you give `0.28.13` a go, it should be fixed now, thanks for reporting! 😄

**Comment by tim-faase** [comment]
Thank you matt! It look me a few hours to find the cause,  our app wasn't working but Stackblitz example did, this fix works with `snapDraggedEvents` property set to true, with it set to false it doesn't work I'm afraid.
Appreciate all your work on this open source component.

**Comment by mattlewis92** [comment]
Ahh I didn't consider that, it's because the drag and drop library uses cloneNode on the element so it won't be updated while dragging, I think I can fix it pretty easily

**Comment by mattlewis92** [comment]
Please give `0.28.15` a go, it should be fixed now 😄

**Comment by tim-faase** [comment]
If you weren't so nice I might not be post this! 😄 it has occurred to me twice; that a mismatch of `@angular/core` to your latest release causes drag and drop to stop working in --prod. `ng serve` is fine but once I build it to production with the flag the cells don't accept an eternal event.

**Comment by mattlewis92** [comment]
> If you weren't so nice I might not be posting this! 😄 it has occurred to me twice; that a mismatch of `@angular/core` to your latest release causes drag and drop to stop working in --prod. `ng serve` is fine but once I build it to production with the flag the cells don't accept an eternal event.

Sounds more like a bug with angular itself rather than anything this library is doing, but if you can make a minimal repro on github that shows the problem then I can investigate further. Thanks!

**Comment by manmohanagarwal** [comment]
Hi Mat,

I am resizing the event, after resizing I don't want it resize then I close the popup then it should be come in previous state it does not update end time in custom title formatter.
I am attaching the video please find the attachments.

https://user-images.githubusercontent.com/88666919/164648838-8d1cd2ff-3d7d-47bd-9bb8-ee6c4fb7dabb.mp4
