### ISSUE TITLE
mwl-calendar-header

### ISSUE THREAD

**Issue by melamudv** [mattlewis92/angular-calendar#124]
Hi
First at all thanks very cool calendar to angular2
Thanks.
I have question about fitcher 
'mwl-calendar-header'
In version angular1 was implementation of this .

Thanks.

**Comment by mattlewis92** [comment]
Do you mean the equivalent of this directive? https://github.com/mattlewis92/angular-bootstrap-calendar/blob/master/src/directives/mwlDateModifier.js
