### ISSUE TITLE
Improve display of events that span more than one day

### ISSUE THREAD

**Issue by gtandersen** [mattlewis92/angular-calendar#1242]
Allow calendar events that span more than one day to have a single line crossing through the days rather than an entry for each day. 

Example screenshot attached.

<img width="805" alt="79395604-e3512780-7f71-11ea-873e-ed8d8808fead" src="https://user-images.githubusercontent.com/1620058/80550584-6b253180-8975-11ea-9bc2-7f9860b6568a.png">

**Comment by mattlewis92** [comment]
Hey Geir! This is something I'm actively working on, it's just a bit tricky to get right, especially with resizing and drag and drop. I reckon I'll have something ready in the next month or so and will reach out to you as soon as I do 😄  I'm going to close this issue for now in favour of https://github.com/mattlewis92/angular-calendar/issues/758 as it's already tracked there. Thanks!

**Comment by babaprincedaouda71** [comment]
@mattlewis92 is it completed?
