### ISSUE TITLE
Very slow on rendering week view

### ISSUE THREAD

**Issue by davidecampello** [mattlewis92/angular-calendar#1243]
**Describe the bug**

Hi, I'm using angular-calendar successfully in some projects (using both angular 8 or 9) but with the last project I'm working (using angular 9.1.3 and last version of angular-calendar) I started copying the Kitchen sink module but I find that is very slow every time that i change month, especially in Week view.
I can't provide anything to reproduce because i created a new stackblitz example and It's working normally so i have no idea.
I tried also to add the same dependencies of my project but nothing is changing.

Any idea on what I can try?

Thanks
Davide

**Comment by mattlewis92** [comment]
Hey there, I'm sorry to hear you're having issues. It sounds like something specific to your app if you're unable to reproduce it outside of it, I would recommend using the [chrome devtools](https://developers.google.com/web/tools/chrome-devtools/evaluate-performance/timeline-tool) to profile it and that should help you find the problem. If you find a way to make a minimal reproduction outside of your app that you can share on github or stackblitz I would be more than happy to investigate further but without that unfortunately there's not much else I can do. Thanks! 😄
