### ISSUE TITLE
How to add multi day events?

### ISSUE THREAD

**Issue by lakhvir1994** [mattlewis92/angular-calendar#1252]
Hello,
I am adding events for multiple days. I wanted to create a single event for 3 days with starting time 12:00 AM 12-05-2020 and ending time 11:59 PM 15-05-2020 (3 full days).

This is how I try to create event,
{
	start: Tuesday, May 12, 2020 0:00:00 ,
	end:  Thursday, May 14, 2020 11:59:00 ,
	title: 'This is test title',
	color: {
		primary: '#4a772f',
		secondary: '#4a772f'
	},
	resizable: {
		beforeStart: true,
		afterEnd: true
	},
	draggable: true,
	allDay: true,
}

Please let me know how can I create this type of events.

**Minimal reproduction of the problem with instructions**

**Screenshots**

https://nimb.ws/dtYb8m
https://nimb.ws/1gIkFy

**Versions**

    @angular/core: 8.2.14
    angular-calendar: 0.26.6
    Browser name and version: Mozilla Firefox - 76.0 (64-bit)

**Comment by mattlewis92** [comment]
Hey there, there's no support for this right now, but I do have plans to add it sometime in the near future. Going to close this issue for now as it's already tracked here: https://github.com/mattlewis92/angular-calendar/issues/758
