### ISSUE TITLE
ng add angular-calendar failing

### ISSUE THREAD

**Issue by lkhatkar** [mattlewis92/angular-calendar#1253]
**ng add angular-calendar failing**

**Minimal reproduction of the problem with instructions**
1. Open terminal and navigate to your project dir
2. Type command: ng add angular-calendar ->hit enter
3. Error

**Console Log**
D:\git\schedular>ng add angular-calendar
Installing packages for tooling via npm.
Installed packages for tooling via npm.
An unhandled exception occurred: Cannot read property 'moment' of undefined
See "C:\Users\ADMINI~1\AppData\Local\Temp\ng-TSSC2e\angular-errors.log" for further details.

**Versions**

- `@angular/core`:
- `angular-calendar`:
- Package.json:
{
  "name": "schedular",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve --open",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~9.1.1",
    "@angular/cdk": "^9.2.3",
    "@angular/common": "~9.1.1",
    "@angular/compiler": "~9.1.1",
    "@angular/core": "~9.1.1",
    "@angular/forms": "~9.1.1",
    "@angular/material": "^9.2.3",
    "@angular/platform-browser": "~9.1.1",
    "@angular/platform-browser-dynamic": "~9.1.1",
    "@angular/router": "~9.1.1",
    "angular-calendar": "^0.28.13",
    "moment": "^2.25.3",
    "rxjs": "~6.5.4",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.901.1",
    "@angular/cli": "~9.1.1",
    "@angular/compiler-cli": "~9.1.1",
    "@angular/language-service": "~9.1.1",
    "@types/node": "^12.11.1",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^5.1.2",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.4.1",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~2.1.0",
    "karma-jasmine": "~3.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "protractor": "~5.4.3",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~3.8.3"
  }
}

**Comment by mattlewis92** [comment]
Sorry about that, should be fixed in the latest version, thanks for reporting! 😄
