### ISSUE TITLE
Disabling 2 events in the same timespot

### ISSUE THREAD

**Issue by ursedaniel** [mattlewis92/angular-calendar#1256]
**Is your feature request related to a problem? Please describe**

Hello, is there any way to disable having 2 events in the same time?
And if so what event should be triggered or what can i do to achieve that?
I only want to have at a time 1 event max, so the expand/drag&dropping another one in that spot should trigger something to me.

**Describe the solution you'd like**

An event/handler to tell me that I overdragged or modified an event over another one.

**Describe your use case for implementing this feature**

I'm developing an app that tracks some things and I can't have 2 events occuring in the same time.

**Additional context**

**Comment by mattlewis92** [comment]
Hey there, right now this isn't possible but this feature should allow you to do it: https://github.com/mattlewis92/angular-calendar/issues/1183 I'm aiming to get a beta release out with it added in the next couple of weeks. I'm going to close this issue for now as a duplicate. Thanks! 😄
