### ISSUE TITLE
Calendar is not rendering correctly in Safari browser 5.1.7 on Windows 10

### ISSUE THREAD

**Issue by gautamkulkarni** [mattlewis92/angular-calendar#1258]
Calendar is not rendering correctly in Safari browser

I checked with demo link [https://angular-calendar.com/#/kitchen-sink] on Safari browser. Calendar is not rendering cleanly. Lots of CSS issues.

**Minimal reproduction of the problem with instructions**
Hit the demo link (https://angular-calendar.com/#/kitchen-sink) on Safari browser. CSS problems are surfaced

**Screenshots**
![issue](https://user-images.githubusercontent.com/65658403/82440780-84c02180-9aba-11ea-8c14-984b48337762.png)

**Versions**

- `@angular/core`: Latest version (9.1.3)
- `angular-calendar`: 0.28.11
- Browser name and version: Safari 5.1.7 on windows 10

**Comment by mattlewis92** [comment]
Hey there, it looks like safari on windows isn't supported anymore: https://apple.stackexchange.com/a/68837 It's so old that it doesn't support flexbox which is a requirement by the calendar, so there's no way that I can support it.
