### ISSUE TITLE
Unexpected value 'DragAndDropModule' imported by the module 'CalendarMonthModule'. Please add an @NgModule annotation.

### ISSUE THREAD

**Issue by matasgra** [mattlewis92/angular-calendar#1266]
**Describe the bug**

Hi! Some issues are experienced when importing CalendarModule into test files, running latest version of Angular (with Ivy):

`Unexpected value 'DragAndDropModule' imported by the module 'CalendarMonthModule'. Please add an @NgModule annotation.`

Might be related to the circularity in angular-draggable-droppable as mentioned here: https://github.com/mattlewis92/angular-draggable-droppable/issues/107

**Minimal reproduction of the problem with instructions**

<img width="244" alt="Screenshot 2020-05-28 at 18 39 25" src="https://user-images.githubusercontent.com/42931572/83168957-99339800-a112-11ea-8e7e-7cfce7574289.png">

**Screenshots**

<img width="1170" alt="Screenshot 2020-05-28 at 18 33 40" src="https://user-images.githubusercontent.com/42931572/83168665-1f031380-a112-11ea-9cbd-a879c9852382.png">

**Versions**

- `@angular/core`: 9.1.9
- `angular-calendar`: 0.28.15
- Browser name and version: Chrome 81.0.4044.138

**Comment by mattlewis92** [comment]
Hi there, sorry to hear you've having issues, please can you provide a minimal runnable repo on github that demonstrates your issue as without that it's pretty much impossible to know what's going on, thank you!

**Comment by matasgra** [comment]
Hi Matt!

Please find a link to the repository here: https://github.com/matasgra/bug-angular-calendar

Run `npm install && npm run test`.

P.S. Also note the console output of `ngcc` being run postinstall:
`Warning: Unable to fully load /Users/matas/bug-angular-calendar/node_modules/angular-draggable-droppable/bundles/angular-draggable-droppable.umd.js for source-map flattening: Circular source file mapping dependency: /Users/matas/bug-angular-calendar/node_modules/angular-draggable-droppable/bundles/angular-draggable-droppable.umd.js.map -> /Users/matas/bug-angular-calendar/node_modules/angular-draggable-droppable/bundles/angular-draggable-droppable.umd.js.map`.

**Comment by mattlewis92** [comment]
Thanks for sharing that! I fixed the sourcemap warning, but that turned out to be a red herring and didn't actually fix it. But I found a workaround, if you change your postinstall script to:
```
"postinstall": "ngcc --properties es2015 module"
```

and then remove your node_modules folder and `npm install` again it then starts working 😄
