### ISSUE TITLE
Arrangement of external dragged events is jumping when drag them to top of day view

### ISSUE THREAD

**Issue by EFritzsche90** [mattlewis92/angular-calendar#1269]
**Describe the bug**

I want to use the external events to plan tasks in a day view. Dragging and dropping works like a charm, but arrangement seems to be buggy. When you try to drag an event to the top there seems to be a point where it jumps directly to the top (all day event?) and then into the nowhere. 

**Reproduction**

You can see the bug directly into your public demo: https://angular-calendar.com/#/draggable-external-events

**Used browser**

Google Chrome for MacOS
Version 81.0.4044.138 (Offizieller Build) (64-Bit)

**Screenshot**

![bug_report](https://user-images.githubusercontent.com/53464225/83406924-ffb8fe80-a40f-11ea-9690-3174636742d6.gif)

**Comment by mattlewis92** [comment]
Hey, thanks for reporting, I can reproduce in the demo as well, I will get that fixed up in the next release! 😄

**Comment by mattlewis92** [comment]
So sorry about the delay in getting to this one, it should be fixed now in `0.28.20` 😄
