### ISSUE TITLE
header modifier

### ISSUE THREAD

**Issue by abdulqadir93** [mattlewis92/angular-calendar#127]
Hello,
I'm using this library in an Ionic 2 application. It works great!
I have a feature request for month view. There's a day modifier in which we could pass a function. The function then gets called with the day object. Can we have something similar for header as well? In my particular case, I had to show the initials of weekdays so just 'M' for Monday. As of now, I'm directly manipulating DOM
1. hide header row
2. change innerHTML of cells with weekday initials
3. show header row

I could also work on a PR if you think that's a valid use-case. Thanks!

Also, there's one related problem I've faced. I cached the objects passed to dayModifier function and added day.cssClass later (after an ajax call). But the class never applied. I'm sure I'm doing it the wrong way!

**Comment by mattlewis92** [comment]
Hi!

You can actually implement this today with the current API. There's a demo that gets you 90% of the way here: https://mattlewis92.github.io/angular-calendar/demos/#/customise-date-formats

You would need to do this to only use the first letter of the day in the header:
```
public monthViewColumnHeader({date, locale}: DateFormatterParams): string {
  return new Intl.DateTimeFormat(locale, {weekday: 'short'}).format(date).substr(0, 1);
}
```

To apply the cssClass after an ajax call you can just trigger a round of change detection once the ajax request is completed:
```
constructor(private cdr: ChangeDetectorRef) {
  this.cdr.markForCheck(); // call this to trigger a DOM update
}
```

Hope that helps! 😄

**Comment by abdulqadir93** [comment]
Oh! Thanks a lot ... I feel so dumb that I missed it from the docs ... I'll have to refactor the code before someone notices what I did!!!

**Comment by mattlewis92** [comment]
I only put those docs up a few days ago, and there are a lot demos to sort through 😃

**Comment by impactotecnologico** [comment]
Hi @abdulqadir93 can you explain me how add the monthViewColumnHeader feature commented above? I don't know where is the right place to put this code
