### ISSUE TITLE
eventTimesChanged is not working in production but works locally.

### ISSUE THREAD

**Issue by Virendra8Satva** [mattlewis92/angular-calendar#1270]
<mwl-calendar-day-view *ngIf="isCalendarEventLoaded" id="calendar" [viewDate]="currentDate"                            [tooltipTemplate]="tooltipTemplate" [events]="events" [refresh]="refresh" [hourSegments]="4"                            [snapDraggedEvents]="false" **(eventTimesChanged)="eventDropped($event)"**                        (eventClicked)="handleEvent('Clicked', $event.event)"></mwl-calendar-day-view>

**Describe the bug**

**Minimal reproduction of the problem with instructions**
I have put (eventTimesChanged)="eventDropped($event) in mwl-calendar.  In localhost it calls **eventDropped({ event, newStart, newEnd, allDay }: CalendarEventTimesChangedEvent | any)** method and consoles in that method are executed. But in production method is not  getting executed.

**Versions**
"@angular/core": "^8.0.2",
"angular-calendar": "^0.28.15",
Google Chrome - Version 83.0.4103.61 (Official Build) (64-bit)

**Comment by mattlewis92** [comment]
Hey there, sorry to hear you're having problems, would you be able to make a small repo on github that reproduces your problem and then I can dig deeper and see if I can find the problem. Thank you! 😄

**Comment by Virendra8Satva** [comment]
@mattlewis92 I have hosted site on Azure where it is not working but in development machine it is working fine. **Please note when I drag and drop external event into Calendar that time it is not working.**

**Comment by mattlewis92** [comment]
I'm afraid without a repo with some code showing how to reproduce your issue there's not really a lot I can do as I'm not able to reproduce this issue myself.
