### ISSUE TITLE
Drag Events on iOS does not block parent scrolling if moved too quickly

### ISSUE THREAD

**Issue by AlwinEgger** [mattlewis92/angular-calendar#1271]
**[Draggable external events](https://angular-calendar.com/#/draggable-external-events)** does not work as expected on iOS devices (tested on iPad). If the item is touched and moved very quickly, the scrolling of the parent-pane is not stopped and the item may only be dragged horizontally. If the item is hold a little longer, the dragging works as expected. 

![ezgif-6-7212ec7d1ab0](https://user-images.githubusercontent.com/4997364/84050816-880a4700-a9ae-11ea-98b8-ae623fdf9ed0.gif)

I've tried different values on `touchStartLongPress`. If I set delay to > 700, the effect disappears. But of course, the handling is more edgy, since the user needs to hold the item for almost a second before start dragging.

This effect is reproducable ton the [Draggable external events](https://angular-calendar.com/#/draggable-external-events) demo page.

**Versions**

- `@angular/core`: `^6.1.10`
- `angular-calendar`: `v0.28.16`
- Safari on iPad (iOS 13)

**Comment by mattlewis92** [comment]
Hey there, it sounds like you already solved your issue and landed on the suggestions I would have recommended.

1/ You can either set `[touchStartLongPress]="{ delay: 300, delta: 30 }"` which will allow scrolling when touching an event. and then you'll need to long press it to start dragging
2/ You can add `(touchmove)="$event.preventDefault()"` on the events container so you can immediately start dragging an event, but that won't let you scroll the page when tapping on that area. If you have a long list of events that take up a lot of the page it might not be the best UX for users.

I've updated the demo to add the solution for number 1 so it's consistent with the rest of the calendar. Thanks for letting me know! 😄
