### ISSUE TITLE
EventClicked is also triggered by clicking on eventactions

### ISSUE THREAD

**Issue by nperdu** [mattlewis92/angular-calendar#1272]
Hi

The setup is as follows: 
* as subscription on (eventClicked) 
* custom template for [eventActionsTemplate]="eventActionsTemplate" with buttons and their own click events
* customt template [eventTitleTemplate]="weekAndDayTitleTemplate" with visualization of the data

When I click on the button, first the button action is triggered and after that the eventClicked is triggered. I expected that the event clicked would only be triggered when clicking on the eventTitleTemplate.

Thanks

**Versions**

- `@angular/core`: 8.2.14
- `angular-calendar`: 0.28.16
- Browser name and version: chrome 83.0.4103.97

**Comment by mattlewis92** [comment]
Hey there, unfortunately I wasn't able to reproduce your issue: https://stackblitz.com/edit/angular-51b3qr?file=demo/template.html If you're still having issues would you mind making a minimal repro on stackblitz that shows your problem, thanks! 😄
