### ISSUE TITLE
[WeekStartsOn] is not working on mwl-calendar-month-view

### ISSUE THREAD

**Issue by Flacipe** [mattlewis92/angular-calendar#1273]
**Describe the bug**
Everything's in the title, weekStartsOn isn't working on my project. I've looked in other issues, including Issue #930.  If it can help you, here is my HTML : 

  <mwl-calendar-month-view
    [weekStartsOn]="5"
    [viewDate]="viewDate"
    [refresh]="refresh"
    [locale]="locale"
    [events]="eventsExample"
    (dayClicked)="dayClicked($event.day)"
    [activeDayIsOpen]="activeDayIsOpen"
    (eventClicked)="eventClick($event.event)"
  >
  </mwl-calendar-month-view>

And here is my typescript : 

 todaysDate = new Date();
  event2Date: moment.Moment = moment().add(3, 'days');
  view = CalendarView.Month;
  viewDate = new Date();
  refresh: Subject<any> = new Subject();
  activeDayIsOpen = false;
  openedEvent = undefined;
  descriptionText: string = undefined;
  weekStartsOn: number = DAYS_OF_WEEK.MONDAY;
  weekendDays: number[] = [DAYS_OF_WEEK.SATURDAY, DAYS_OF_WEEK.SUNDAY];
  locale: string = 'fr';
  selectedMonth: any;

eventsExample: any = [
    {id: 1, title: 'Entrainement #1, 2 enregistrements', description: 'Entrainement du jour', start: this.todaysDate, end: this.todaysDate,
     content: [{name: 'Contre Attaque', date: this.todaysDate, duration: '00:11:30'},
        {name: '3 contre 2', date: this.todaysDate, duration: '00:26:35'}]},
    {id: 3, title: 'Entrainement #3, 1 enregistrements',  description: 'Entrainement du jour', start: this.todaysDate, end: this.todaysDate,
      content: [{date: this.todaysDate, duration: '00:20:30'}]},
    {id: 2, title: 'Entrainement #2', start: this.event2Date,
      end: this.event2Date, content: [{date: this.event2Date, duration: '00:20:30'}]},
  ];

  dayClicked({ date, events }: { date: Date; events: CalendarEvent[] }): void {
    if (isSameMonth(date, this.viewDate)) {
      if (
        (isSameDay(this.viewDate, date) && this.activeDayIsOpen === true) ||
        events.length === 0
      ) {
        this.activeDayIsOpen = false;
      } else {
        this.activeDayIsOpen = true;
      }
      this.viewDate = date;
    }
  }

  eventClick(event) {
    this.openedEvent = event;
    this.descriptionText = this.openedEvent.description;
    console.log(event);
  }

**Comment by Flacipe** [comment]
My error is that I was using momentjs, fixed it using https://angular-calendar.com/#/moment

**Comment by mattlewis92** [comment]
Glad you got it sorted! I added a note to the docs as well which should hopefully make it a bit more clear why it doesn't appear to do anything 😄
