### ISSUE TITLE
plugin updated 0.28.16 - day events are not loaded

### ISSUE THREAD

**Issue by shalini-github** [mattlewis92/angular-calendar#1277]
**Describe the bug**

Hi @mattlewis92 I've updated the plugin and the events on day view calendar is not played.

**Minimal reproduction of the problem with instructions**

It gives me the below error on click of next button event (next day is having custom day events on my calendar) I tried my best to fix this and searched on your git issues list but no luck. Please suggest.

**Screenshots**

![image](https://user-images.githubusercontent.com/25053785/85022062-56129500-b1a5-11ea-9a9c-361f8478dda0.png)

**Versions**

previous plugin version angular-calendar : 0.24.1

- `@angular/core`: 6.1.10
- `angular-calendar`: ^0.28.16
- Browser name and version: Chrome 83.0

**Comment by shalini-github** [comment]
Hi @mattlewis92 need your help.

**Comment by mattlewis92** [comment]
Hey there, I'm not able to reproduce the problem you're having on my end, if you're still facing issues would you mind putting together a runnable stackblitz that demonstrates the issue you're having. You can fork a starter from any of the demos by hitting the "Edit in stackblitz" button. Thanks! 🙌
