### ISSUE TITLE
Scrolling in Month and Week view

### ISSUE THREAD

**Issue by awsaunier** [mattlewis92/angular-calendar#128]
### Feature request:

Scrollable month and week view would be nice.  If that is implemented have the option so when you scroll, will either change what month is currently displaying (similar to the small calendar in the upper left corner in the calendar app in windows) or scroll will allow you to have the calendar between months. (Similar to the calendar app in windows).  Thank you for the work you have done already.

-Adam

**Comment by mattlewis92** [comment]
While I do like the idea, writing and maintaining this feature would be non-trivial. I think it's also outside of the scope of this library itself. In theory it should be possible though to create a component that wraps this libraries components that gives you the functionality you need.
