### ISSUE TITLE
Get start and end of the displayed period

### ISSUE THREAD

**Issue by lippomano** [mattlewis92/angular-calendar#1282]
**Is your feature request related to a problem? Please describe**

I am using mwlCalendarPreviousView, mwlCalendarNextView and viewDateChange output event to get the Date.
But with this method, I only have a single date, I don't see ways to get the current total period of time, for example in month view I see the current month and also some days of the previous and next month.

**Describe the solution you'd like**

I need the start and the end of the current displayed period, especially for month view.
Or something similar

**Describe your use case for implementing this feature**

I load items for calendar based on the current view so for example in week view I only load the events for 7 days.
So it is important for me to get all the displayed period to load the correct events.

**Comment by mattlewis92** [comment]
Hey there, to do this you can use the `beforeViewRender` output, and then `$event.period.start` and `$event.period.end` properties should have the date range that you need. Hope that helps! 😄

**Comment by borkoArsovic** [comment]
Hey, I use beforeViewRender to get start and end dates. But when I get some results from the backend and when I want to create an event based on that data, I run into an infinite loop.

**Comment by massimo-petrillo** [comment]
beforeViewRender is not fired when changing the view. Is there another way to get the displayed period ?
