### ISSUE TITLE
Not getting cssClass for Sunday in CalendarWeekViewBeforeRenderEvent for header 

### ISSUE THREAD

**Issue by PoonamChoudhari** [mattlewis92/angular-calendar#1286]
**Describe the bug**

beforeWeekViewRender(renderEvent: CalendarWeekViewBeforeRenderEvent){
    renderEvent.header.forEach(header => {
      console.log(header);
      if(this.headerDate){
        if(header.day == this.headerDate){
          header.cssClass = 'cal-day-segment-disabled';
        }
        if(header.day != this.headerDate){
          header.cssClass = 'cal-day-segment-white';
        }
      }
    });
  }

In above function, when click on header having day Sunday, header object does not contain cssClass in it. But it is working fine with other days.
I am not understanding why it is not working for sunday.
please help me. I am stuck.

**Versions**

- `@angular/core`: 7.2.11
- `angular-calendar`:0.27.2
- Browser name and version: Chrome

**Comment by mattlewis92** [comment]
Hey there, I'm not able to reproduce the problem you're having on my end, if you're still facing issues would you mind putting together a runnable stackblitz that demonstrates the issue you're having. You can fork a starter from any of the demos by hitting the "Edit in stackblitz" button. Thanks! 🙌
