### ISSUE TITLE
change template

### ISSUE THREAD

**Issue by felek000** [mattlewis92/angular-calendar#129]
Hello,
I want to change template of element: CalendarEventTitleComponent, Can it be overide in some (not in node modules core files in plugin).

Also is it possible to create year view ? so days will be as columns as very long row ?

**Comment by mattlewis92** [comment]
There is currently no way of overriding templates, there is an issue for tracking this here: https://github.com/mattlewis92/angular-calendar/issues/16

If it's just the event title html you need to change then maybe you can override the formatter service which supports adding html to event titles, there is a demo of that here: https://mattlewis92.github.io/angular-calendar/demos/#/show-dates-on-titles

There is no year view as part of this library, but you could build your own year view component that complements the components that are part of this library. However it's not something I plan on building and maintaining as part of this library.

Hope that helps!

**Comment by felek000** [comment]
It worked for override drop down thx.
Is there similar way to override box in calendar ?

**Comment by mattlewis92** [comment]
Afraid not, for that you'll need to wait for https://github.com/mattlewis92/angular-calendar/issues/16 to land
