### ISSUE TITLE
Option to fix the header position

### ISSUE THREAD

**Issue by ALapaque** [mattlewis92/angular-calendar#1290]
**Is your feature request related to a problem? Please describe**

**Describe the solution you'd like**

In the different views of the calendar could we have the posibility to fix the header is shown in the below example

![fix header](https://user-images.githubusercontent.com/46450511/85853901-99778f80-b7b3-11ea-8e31-fea5d79d84ed.gif)

that could be a create features :)

**Describe your use case for implementing this feature**

This could help users to remind the day or the users (for the scheduler view)
I guess it's all about css and display flex (that's how I did for the example)

**Additional context**

Thanks for your amazin work @mattlewis92

**Comment by mattlewis92** [comment]
The way I would suggest to solve this is with a couple of lines of css and using `position: sticky`: https://stackblitz.com/edit/angular-6uhkld?file=index.html 

It's hard to provide anything that works out of the box as you don't know what element will be the scroll container (maybe it's the document itself, maybe a wrapper div around the calendar), so I think adding a few lines of css in your own app is a good tradeoff here. Hope that helps! 😄

**Comment by jas75** [comment]
Drag & drop is dead using this solution
