### ISSUE TITLE
Remove badge from calendar

### ISSUE THREAD

**Issue by hassanthegooner** [mattlewis92/angular-calendar#130]
Hi,

Is there anyway that I could remove all badges from the calendar? I've been trying it myself for a while but just cant figure it out

Regards

**Comment by mattlewis92** [comment]
You can either hide it with a global CSS rule
```
.cal-day-badge {
  display: none;
}
```

or make the badge total 0 by adapting the code from this demo: https://mattlewis92.github.io/angular-calendar/demos/#/month-view-badge-total

Hope that helps!
