### ISSUE TITLE
Cannot properly import any Today/Previous/Next directive in an Angular unit test

### ISSUE THREAD

**Issue by martijn19811** [mattlewis92/angular-calendar#1301]
**Describe the bug**

Jest 26, running on Angular10, cannot properly import any Angular Calendar directive. Whenever I try to import CalendarTodayDirective in a .spec.ts file, it errors in jest --watch with the following message

`Cannot find module 'angular-calendar/modules/common/calendar-today.directive' from <location of my component>`

`at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:308:11)
      at Object.<anonymous> `

It then exits the test.

The same goes for the Next and Previous directive. Can these actually be properly be exported and if so, which path should I choose then?

**Minimal reproduction of the problem with instructions**

**Screenshots**
<a href="https://ibb.co/D75H1w9"><img src="https://i.ibb.co/30B9TSp/Untitled.png" alt="Untitled" border="0"></a>

**Versions**

- `@angular/core`: 10.0.2
- `angular-calendar`: 0.28.16
- `jest`: 26.1.0
- Browser name and version: headless Jest browser.

**Comment by mattlewis92** [comment]
Glad you got it sorted! 😄
