### ISSUE TITLE
Drag drop not working

### ISSUE THREAD

**Issue by Jeshal2013** [mattlewis92/angular-calendar#1304]
**Minimal reproduction of the problem with instructions**
we have old version ^0.27.11 for calender and it's working drag and drop functionality.
but if we update version of anguler caleder for ^0.28.16 than it's not woking after released on azure but working on local machine.  

**Versions**

- `@angular/core`:^8.0.2
-"@angular-calendar": "^0.28.16",

- Browser name and version:

**Comment by Jeshal2013** [comment]
drag & drop not working (scroll issue is working with current time) (localhost in working Drag & drop)
- `@angular/core`:  8.0.2
- `angular-calendar`:  0.28.16
- Browser name and version:  Google Chrome Version 84.0.4147.89 (Official Build) (64-bit)

scroll issue is not working with current time (drag & drop is working fine ) 
- `@angular/core`:  8.0.2
- `angular-calendar`:  0.27.11
- Browser name and version:  Google Chrome Version 84.0.4147.89 (Official Build) (64-bit)


issue after updating version and issue only after released on server local machine it's work.

**Comment by mattlewis92** [comment]
Hey there, sorry to hear you're having problems, I'm not too sure why it might be happening. If you can make a minimal github repo that reproduces your problem I would be happy to debug further, but unfortunately without that there's not much I can do 😞

**Comment by Jeshal2013** [comment]
Hi 
it's version issue resolved.  Thannks. @mattlewis92

**Comment by mattlewis92** [comment]
Awesome, great to hear!
