### ISSUE TITLE
Maximum and Minimum date 

### ISSUE THREAD

**Issue by RamitAnandSharma** [mattlewis92/angular-calendar#131]
I want to specify Maximum and Minimum date on the Calendar.
Is it possible to restrict Calendar to display dates within a date range.

For ex- Today is 18 Jan i want to only show dates 60 days before and 90 days after the current date.

**Comment by mattlewis92** [comment]
As you're in control over when the current date and view changes you can just disable the prev / next buttons. I've added an example of how to do that here: https://mattlewis92.github.io/angular-calendar/demos/#/min-max-date

Hope that helps!

**Comment by RamitAnandSharma** [comment]
Thanks Matt  for the quick response.

**Comment by RamitAnandSharma** [comment]
There is a bug in Min max date demo 
Steps to reproduce
-----
Click on Next Button till it reached the max date.
Click Today Button. Calendar now shows the current date
Previous button is still disabled.

Same can be reproduced for Previous Button
