### ISSUE TITLE
Dynamic adding/removing slots in week/day view

### ISSUE THREAD

**Issue by karthick0125** [mattlewis92/angular-calendar#1312]
**Describe the bug**

I have a business scenario to add or remove slots( hoursegment) in week/day view. I have filtered week/day hour rows by using "beforeViewRender" and achieved desired view. But it seems filtered rows are not removed from DOM.
I am able to drop events on void area.

    beforeWeekOrDayViewRender(event: CalendarWeekViewBeforeRenderEvent,{ header }: { header: WeekDay[]}) {
        console.log(header);

        console.log(event);
        this.hourColumns = event.hourColumns;

        this.hourColumns.forEach((hourColumn) => {

            hourColumn.hours = hourColumn.hours.filter((hour) => {

                const segment = hour.segments[0];
                let hours = segment.date.getHours()

                if (this.hourSlotMap.has(hours)) {
                    return true;
                } else {
                    hour.segments.forEach((seg)=>{
                        delete seg.cssClass;
                        seg.cssClass='red-cell';
                    })
                    return false;
                }

            });

        });
        event.hourColumns = [...this.hourColumns];
    }

Could you please help regarding how to render this view
![event_dragging](https://user-images.githubusercontent.com/36404516/89421730-076b8b00-d752-11ea-9471-9bd7175b782d.png)

**Minimal reproduction of the problem with instructions**

**Screenshots**

**Versions**

- `@angular/core`:
- `angular-calendar`:
- Browser name and version:

**Comment by ALapaque** [comment]
Hi @karthick0125 can you please provide a minimal reproduction of this ?
I do use myself the beforeWeekViewRender and I don't have any problem with it.

**Comment by mattlewis92** [comment]
Hi there, unfortunately due to the way drag and drop and resizing works this isn't easy to implement and would require rewriting a lot of code. The best way I could suggest to solve it is by making certain time slots appear as disabled like on this demo: https://angular-calendar.com/#/before-view-render

**Comment by jarmm** [comment]
i have the same problem, someone has solved this issue ? @mattlewis92 @karthick0125
