### ISSUE TITLE
Increase the number of hourSegments

### ISSUE THREAD

**Issue by martijn19811** [mattlewis92/angular-calendar#1314]
**Is your feature request related to a problem? Please describe**

I'm always frustrated when someone wants to setup a 5 minute appointment, but I cannot increase the hourSegments number to 12. I'd love to make sure that a person can click a 5-minute row and be done with. This is not the case at the moment unfortunately

**Describe the solution you'd like**

I'd like to make sure that the hourSegments input decorator accepts numbers greater than 6. Perhaps make it completely dynamically. Then we can accommodate for 5 minute appointments, which we cannot do at the moment.

**Describe your use case for implementing this feature**

A calendar will be setup for someone who wants to make very short, quick appointments. 5 minutes and you're done. I'd like to see that I can set the hourSegments to 12, so that that person can immediately click on the 5 minutes row.

**Additional context**

No additional context needed, I think. Please contact me if you have any more questions.

**Comment by martijn19811** [comment]
Wait, @mattlewis92 : it seems this has already been solved? I've changed the hourSegments number to 12 in the meantime and it seems to work perfectly. Each row covering five minutes. The docs say you can only use a maximum number of 6 though...

**Comment by mattlewis92** [comment]
Ah I think the docs are just wrong, it should allow any number that divides equally into 60 and not less than 6. I've updated the docs now to reflect this, thanks for letting me know! 😄
