### ISSUE TITLE
Highlight selected day with custom class

### ISSUE THREAD

**Issue by no-more** [mattlewis92/angular-calendar#1317]
**Is your feature request related to a problem? Please describe**

It's currently not possible to customize the selected day in monthView. Only option is to use :focus which is not enough as cell can loose focus while the selected day is still the same.

**Describe the solution you'd like**

There's already lots of helpfull classes, it would be great to add .cal-selected to the currently selected day.

**Describe your use case for implementing this feature**

Easily visualize currently selected day even if focus is lost.

**Additional context**

**Comment by ALapaque** [comment]
@no-more you can do it by yourself using a custom header template and then trigger the fact that it's the day you've selected

**Comment by mattlewis92** [comment]
Hey there, if you take a look at this demo it should do what you're after: https://angular-calendar.com/#/selectable-period Hope that helps! 😄
