### ISSUE TITLE
Tooltip stay visible after route change on mobile

### ISSUE THREAD

**Issue by no-more** [mattlewis92/angular-calendar#1323]
**Describe the bug**

Context: 
- Full page calendar view, on event click navigate to subroute, calendar is not visible but still there.
- Tooltip is visible on the top-left corner of the screen

I've tried to set focus with js on another element, but the tooltip remains active.
Would be great to have a service to force closing tooltip or to automatically close it on navigation start

**Minimal reproduction of the problem with instructions**

**Screenshots**

![image](https://user-images.githubusercontent.com/3856871/90951402-b9ea6000-e46b-11ea-99a1-6c00edd9b38b.png)

**Versions**

- `@angular/core`: 10
- `angular-calendar`: 0.28.16
- Browser name and version: Chrome lates 84.0.4147.135

**Comment by mattlewis92** [comment]
Hey there, sorry to hear you're having troubles, there's a couple options I can think of that should resolve your issue:

1/ Set `[tooltipAppendToBody]="false"` on the month / week / day components which will stop the tooltips getting appending to the body element and hide them when the parent is hidden
2/ Use an `*ngIf` on the month / week / day components to remove the components from the dom when hidden which should destroy the tooltips

Hope that helps! 😄

**Comment by no-more** [comment]
Hi,

Thanks for your response.
Option 2 is not an option in my case as the element is only hidden by CSS according to screen size
I will try option 1, as was not aware of this parameter which looks very interesting.

Thanks again
