### ISSUE TITLE
Time line grouping feature

### ISSUE THREAD

**Issue by Suresh918** [mattlewis92/angular-calendar#1328]
**Is your feature request related to a problem? Please describe**
There is no way to have resources in one axis and time line in another axis so that i can look and compare resource events easily.

**Describe the solution you'd like**
We need to have resources in one axis as hierarchical and time line in another axis as shown in the below image,
![image](https://user-images.githubusercontent.com/6056573/91962115-63eba700-ed0c-11ea-82f2-57e660eb3a21.png)

**Describe your use case for implementing this feature**
It is the mostly used feature in schedulers

**Additional context**

**Comment by mattlewis92** [comment]
Hey there, thanks for the feature suggestion, but I think a timeline view is out of scope for this project. I think it would make a great complimentary component to the month / week / day views provided but it's not something I have the resources to build or maintain myself.

**Comment by nayfin** [comment]
@mattlewis92 we need this feature as well. We already used your calendar in our app and now we need a timeline, so our options are: 
- switch to another library that offers a timeline as well as a, in which case we'd also need to switch to our current calendar code
- if your interested providing some guidance we could contribute to a timeline feature to this project

We'd prefer to contribute to your project, we use your calendar heavily and it seems like you have a lot of the structure in place to build out a timeline and our devs love contributing to open source projects. 

Please let me know what you think, and thanks for creating such a great product

**Comment by mattlewis92** [comment]
> @mattlewis92 we need this feature as well. We already use your calendar in our app and now we need a timeline, so our options are:
> 
> * switch to another library that offers a timeline as well as a calendar, in which case we'd also need to update all of the calendars we've already implemented
> * if your interested providing some guidance we could contribute a timeline feature to this project
> 
> We'd prefer to contribute to your project, we use your calendar heavily and it seems like you have a lot of the structure in place to build out a timeline, and our devs love contributing to open source projects.
> 
> Please let me know what you think, and thanks for creating such a great product

Hey there! You can absolutely build a timeline component on top of these calendar packages, as this is exactly what I did already for [ClickUp](https://app.clickup.com/). If you signup for a free account and make a timeline view, using the devtools you can see how it works under the hood. 

There is a header component that's generated using the `getWeekViewHeader` function from `calendar-utils`
![CleanShot 2022-03-07 at 15 55 50](https://user-images.githubusercontent.com/6425649/157069650-e1e7ea1b-6d9f-4ee2-93d0-48a593d105ce.png)
 
And then a component for each grouping row in the timeline that `extends CalendarWeekViewComponent` to inherit all the drag, drop and resizing utilities, and uses the `getAllDayWeekEvents` helper from `calendar-utils` to generate the layout for events. 

Putting that all together this is roughly what you get:
![CleanShot 2022-03-07 at 15 59 12](https://user-images.githubusercontent.com/6425649/157070424-c08b2209-d9ef-4b17-8896-624922e83871.png)

Unfortunately I'm unable to easily open source this as we made a lot of additional customisations on top of it that means it's very tightly coupled to the ClickUp codebase, and I'm also not really working much on the frontend anymore.

The way I would picture this working if open sourced is actually as a separate package that just has `angular-calendar` / `calendar-utils` as dependencies and then builds out a new timeline component based on all the existing pieces. While it's not something I have the time or energy to commit to maintaining myself, I would love to see it be created by someone!

Let me know if that makes sense or you have any questions! 😄

**Comment by nayfin** [comment]
This is great, that gives us a lot to run with once we start working this feature. We're using an Nx workspace so it will be easy to develop it as a lib internally, then publish a library after we get it nailed down.  Thanks for the insight!

**Comment by Sirioxstar** [comment]
HI @nayfin,
did you implement a solution?

**Comment by Sirioxstar** [comment]
any updates?
