### ISSUE TITLE
Event scheduled after 3 AM is not resizable

### ISSUE THREAD

**Issue by Virendra8Satva** [mattlewis92/angular-calendar#1329]
**Describe the bug**
When event is scheduled **after 3 AM**, it is not resizable (even if that event has resizable{beforeStart:  true, afterEnd: true}). Please note that event scheduled **before 3 AM** is resizable.

**Minimal reproduction of the problem with instructions**
1.Schedule event before 3 AM and then resize,It works.
2.Schedule event after 3 AM or at 3 AM and then resize. It will not be resized.

  <mwl-calendar-day-view *ngIf="isCalendarEventLoaded" id="calendar" [viewDate]="currentDate" [tooltipTemplate]="tooltipTemplate" [events]="events" [refresh]="refresh" [hourSegments]="4" [snapDraggedEvents]="false" (eventTimesChanged)="eventDropped($event)"
(eventClicked)="handleEvent('Clicked', $event.event)">
 </mwl-calendar-day-view>

 
**Versions**

 - `@angular/core`: ^8.0.2
- `angular-calendar`: ^0.28.10
- Browser name and version: Google Chrome Version 85.0.4183.83 (Official Build) (64-bit)

**Comment by mattlewis92** [comment]
Hey there, I'm not able to reproduce the problem you're having on my end, if you're still facing issues would you mind putting together a runnable stackblitz that demonstrates the issue you're having. You can fork a starter from any of the demos by hitting the "Edit in stackblitz" button. Thanks! 🙌
