### ISSUE TITLE
How to overlap multiple events scheduled on the same time?

### ISSUE THREAD

**Issue by Virendra8Satva** [mattlewis92/angular-calendar#1332]
**Is your feature request related to a problem? Please describe**
How to **overlap** multiple events scheduled in the same time? Please check snapshot.
 
![image](https://user-images.githubusercontent.com/49708669/92565607-88a9c680-f298-11ea-99c5-556de8993aa2.png)

**Describe the solution you'd like**
Events should be **overlapped** when scheduled at the same time.

**Describe your use case for implementing this feature**
**Schedule multiple events at the same time.**

**Comment by mattlewis92** [comment]
Hey there, if you take a look at this demo I think it can do what you want it to do: https://angular-calendar.com/#/group-similar-events Hope that helps!

**Comment by Virendra8Satva** [comment]
Hi @mattlewis92 , Thank you for the link above but I need to **overlap events**, I don't want to group similar events. is that possible?

**Comment by mattlewis92** [comment]
Ah ok, there's no support for this out of the box, but you could use the `beforeViewRender` output to modify the `left` and `width` positioning of events to achieve this. I put together an example of how to do this here: https://stackblitz.com/edit/angular-pilzbv?file=demo/component.ts

**Comment by Virendra8Satva** [comment]
Hi @mattlewis92 , Thank you so much. It worked 👍
