### ISSUE TITLE
Display the start of the hour in week/day view regardless of dayStartMinute/dayEndMinute

### ISSUE THREAD

**Issue by kyleabens** [mattlewis92/angular-calendar#1333]
**Is your feature request related to a problem? Please describe**

When setting the dayStartMinute to something like 30, the times that are displayed in the week/day view are 9:30, 10:30, 11:30 etc.

**Describe the solution you'd like**

It would be great if we could always display the beginning of each hour instead (E.g. 10, 11, 12) even if the dayStartMinute isn't 0

**Describe your use case for implementing this feature**

Some of my users hours of operation start on a time other than the beginning of an hour but still want to see the times listed as the beginning of each hour.  Hope this makes sense.

**Comment by mattlewis92** [comment]
Hey there, sorry I'm a bit confused as this seems to be the existing behaviour? https://stackblitz.com/edit/angular-qlibhu?file=demo/template.html Please could you make a small repro on stackblitz showing what you mean? Thanks! 😄

**Comment by kyleabens** [comment]
@mattlewis92 Here is an image showing what the time column looks like if you set your hours/minutes from say 9:30 AM to 9:30 PM.  The times displayed are not the beginning of each hour but instead the middle of each hour.  I feel like it would make more sense to display the beginning of each our (E.g. 10:00, 11:00, 12:00, 1:00 etc.).

<img width="1131" alt="Screen Shot 2020-09-14 at 11 01 43 AM" src="https://user-images.githubusercontent.com/25699262/93102920-fb8cb600-f679-11ea-85d5-7d60a833612a.png">
)

**Comment by mattlewis92** [comment]
> @mattlewis92 Here is an image showing what the time column looks like if you set your hours/minutes from say 9:30 AM to 9:30 PM. The times displayed are not the beginning of each hour but instead the middle of each hour. I feel like it would make more sense to display the beginning of each our (E.g. 10:00, 11:00, 12:00, 1:00 etc.).

That is the default behaviour of the calendar though? Are you using a date formatter to override the defaults maybe?

![image](https://user-images.githubusercontent.com/6425649/93110513-58559400-f6ad-11ea-866a-f3999f6ec855.png)

**Comment by kyleabens** [comment]
I am using a date formatter for international formatting purposes.  If I remove it it only lists the beginning of each hour however if you click in a 9 AM time slot in your example it will be 9:30 AM which isn't correct since you would expect that to be 9 AM.  In your example there would need to be an empty row first for 9:30 AM then the next would be 10 AM and it would display 10 AM in the left hand column.  Does that make sense?

**Comment by mattlewis92** [comment]
Ohh I think I get it now, is this what you mean?

https://stackblitz.com/edit/angular-mcw1ng?file=index.html

**Comment by kyleabens** [comment]
Yep, that's exactly what I'm looking for

**Comment by kyleabens** [comment]
How did you do that?

**Comment by kyleabens** [comment]
I just decided to display the time in every row regardless of start time and increments.

**Comment by mattlewis92** [comment]
> I see you were able to accomplish this with css. How can I make this dynamically change based on what's set for dayStartMinute?

You can add a class to the parent component and apply the styles conditionally that way:

```
<mwl-calendar-week-view [class.cal-week-view-swap-hours]="dayStartMinute === 30" [dayStartMinute]="dayStartMinute">
```

```
.cal-week-view-swap-hours .cal-week-view .cal-hour-segment.cal-hour-start .cal-time {
  display: none;
}

.cal-week-view-swap-hours .cal-week-view .cal-hour-segment.cal-after-hour-start .cal-time {
  display: inline-block;
}
```

Hope that helps! 😄
