### ISSUE TITLE
Stackblitz Demo For Drag to Create Event is too slow for switching b/w weeks

### ISSUE THREAD

**Issue by Harshit31** [mattlewis92/angular-calendar#1338]
**Describe the bug**

I was playing around with the official stackblitz demo and found out that the drag to create event module updates after a lot of lag when I tried to switch b/w different weeks.

**Minimal reproduction of the problem with instructions**

https://angular-calendar.com/#/drag-to-create-events

**Screenshots**

Not Applicable

**Versions**

- `@angular/core`: NA
- `angular-calendar`: NA
- Browser name and version: NA

**Comment by mattlewis92** [comment]
Thanks for letting me know! There was just a small bug in the demo code, should be fixed now 😄
