### ISSUE TITLE
ERROR TypeError: getLocalePluralCase(...) is not a function

### ISSUE THREAD

**Issue by LucaDaniele99** [mattlewis92/angular-calendar#1339]
**Describe the bug**

When calendar gets loaded, this error throws multiple times. The events are added dinamically to the objects used by the calendar and then this.refresh.next() gets called to refresh the calendar. I've copied the demo from the website and just added the part of code that manage the events dinamically, am I doing something wrong?

**Screenshots**

![image](https://user-images.githubusercontent.com/24780756/93718713-28f7c900-fb7e-11ea-8357-1c3de0b0a32c.png)

**Versions**

- `@angular/core`: 9.0.0
- `angular-calendar`: 0.28.16
- Browser name and version: Chrome 85

**Comment by mattlewis92** [comment]
Hey there, I'm not able to reproduce the problem you're having on my end, if you're still facing issues would you mind putting together a runnable stackblitz or a repo on github that demonstrates the issue you're having. You can fork a starter from any of the demos by hitting the "Edit in stackblitz" button. Thanks! 🙌
