### ISSUE TITLE
When the calendar use intertionalisation there is an hour shift in the day view on Mozilla only.

### ISSUE THREAD

**Issue by antarius73** [mattlewis92/angular-calendar#1341]
**Describe the bug**

Hello,

When the calendar use intertionalisation (for french for exemple) there is an hour shift in the day view on Mozilla only.

the shift is present on min ,max hour and on all event present in the calendar.

you can correct this in Mozilla with a modification of the config file, parameter "privacy.resistFingerprinting" set to true.

But this is not a viable solution for production.

**Minimal reproduction of the problem with instructions**

This can be reproduce directly in your demo here : https://angular-calendar.com/#/i18n

**Screenshots**

this is the result with Chrome :
![image](https://user-images.githubusercontent.com/17497070/93851347-38772f00-fcb0-11ea-98da-99b2f64fc82c.png)

and this is the result with Mozilla :
![image](https://user-images.githubusercontent.com/17497070/93851394-52187680-fcb0-11ea-842a-bd099b43c67f.png)

**Versions**

- `@angular/core`: repro on Demo site directly
- `angular-calendar`: repro on Demo site directly
- Browser name and version: Version 85.0.4183.102 (Build officiel) (64 bits) , Firefox 80.01 (64 bits)

**Comment by mattlewis92** [comment]
Hey there, I'm not able to reproduce my end, when I open the demo in firefox it shows correctly for me:

![image](https://user-images.githubusercontent.com/6425649/93875420-da0c7980-fccc-11ea-9d81-1d59088d1ee6.png)

I tried setting the `privacy.resistFingerprinting` to true and false and it made no difference. 

Can you try in incognito mode and see if it helps? Maybe it's an extension causing issues.

Could you also let me know what timezone you're in? That might be why I can't reproduce. Thanks!

**Comment by antarius73** [comment]
Thanks for your quick response,

using the incognito mode doesn't change the result.

I'm on "Paris" (UTC+2) timezone.

i think you're right, it's certainly your location that makes the behavior
different.



Le mar. 22 sept. 2020 à 13:15, Matt Lewis <notifications@github.com> a
écrit :

**Comment by mattlewis92** [comment]
Ah yes it was the timezone change, I just pushed up a fix to the demo code. To fix it in your custom date formatter you need to change `new DatePipe(locale).transform` to `formatDate`. Hope that helps and thanks for reporting!

**Comment by antarius73** [comment]
oki, it's works now,

thanks for your efficiency

Le mar. 22 sept. 2020 à 15:23, Matt Lewis <notifications@github.com> a
écrit :
