### ISSUE TITLE
Issue for adding the component to a another brand new project

### ISSUE THREAD

**Issue by JMariaccia** [mattlewis92/angular-calendar#1342]
**Describe the bug**
[
![image](https://user-images.githubusercontent.com/25175087/93896310-10f48680-fcf1-11ea-84b0-547e81248044.png)
](url)
)

I wanted to add your angular-calendar in my new project so after using the ng add angular-calendar command i added your angular-calendar to my app and after making all the import and using <mwl-calendar-week-view></mwl-calendar-week-view>
on my app module i ended up with this error

**Minimal reproduction of the problem with instructions**

**Screenshots**
[
![image](https://user-images.githubusercontent.com/25175087/93897130-01297200-fcf2-11ea-886f-a80c5192f6f6.png)
](url)

**Versions**

- `@angular/core`: 8.2.7
- `angular-calendar`: 0.28.20
- Browser name and version: Chrome  Version 85.0.4183.102

**Comment by mattlewis92** [comment]
Hey there, I'm not able to reproduce the problem you're having on my end, if you're still facing issues would you mind putting together a runnable stackblitz that demonstrates the issue you're having. You can fork a starter from any of the demos by hitting the "Edit in stackblitz" button. Thanks! 🙌
