### ISSUE TITLE
weekView dragEnter & dragLeave event on segment

### ISSUE THREAD

**Issue by ALapaque** [mattlewis92/angular-calendar#1343]
**Is your feature request related to a problem? Please describe**

Hey there @mattlewis92 :)
Thanks for your great work !

I'm looking to display the segment hour when i'm hovering a segment in the different views. As shown below
![hover_tooltip](https://user-images.githubusercontent.com/46450511/94162715-48953700-fe87-11ea-9013-52663551a7af.gif)

but the problem is not the hover but the dragOver, I'd like to display the same thing but when I'm hovering an hour segment while dragging something. → example below

![hover_tooltip_drag](https://user-images.githubusercontent.com/46450511/94235297-9ce1fa80-ff0b-11ea-8ff8-f8ab463f112f.gif)

**Describe the solution you'd like**

Could it be possible to drigger the fact that we dragEnter and dragLeave an hourSegment ?

I've been able to do it in my day view as I use the day-view-scheduler and we have access to the component mwl-calendar-week-view-hour-segment in the html here is the code I've added

```
<mwl-calendar-week-view-hour-segment
                    *ngFor="let segment of hour.segments; trackBy: trackByHourSegment"
                    [style.height.px]="hourSegmentHeight"
                    [segment]="segment"
                    [segmentHeight]="hourSegmentHeight"
                    [locale]="locale"
                    [customTemplate]="hourSegmentTemplate"
                    (mwlClick)="hourSegmentClicked.emit({ date: segment.date,
                                                              sourceEvent: $event})"
                    [clickListenerDisabled]="hourSegmentClicked.observers.length === 0"
                    mwlDroppable
                    [dragOverClass]="!dragActive || !snapDraggedEvents ? 'cal-drag-over' : null"
                    dragActiveClass="cal-drag-active"
                    [matTooltip]="segment.displayDate | calendarDate: 'weekViewHour':locale"
                    [matTooltipClass]="'segment-tooltip'"
                    [matTooltipShowDelay]="100"
                    #segmentTooltip="matTooltip"
                    (dragLeave)="segmentTooltip.hide()"
                    (dragEnter)="segmentTooltip.show()"
                    (drop)="eventDropped($event, segment.date, false)">
</mwl-calendar-week-view-hour-segment>
```

and here is the result

![hover_tooltip_drag_day_view](https://user-images.githubusercontent.com/46450511/94236084-e8e16f00-ff0c-11ea-9999-6d9342c9e8fc.gif)

**Describe your use case for implementing this feature**

When I'm dragging something on my calendar it's sometimes hard to see which timeslot i'm dropping the event

**Additional context**

Thanks for your help @mattlewis92 :)

**Comment by mattlewis92** [comment]
Hey @ALapaque! I think you can do this already by using the `hourSegmentTemplate` and putting the events on the inner div there like so:

```
    mwlDroppable
    (dragLeave)="showTooltip(false)"
    (dragEnter)="showTooltip(true)"
```

I put together a quick demo here: https://stackblitz.com/edit/angular-kt6nvt?file=demo%2Ftemplate.html

Let me know if that works for you! 😄

**Comment by ALapaque** [comment]
Hi there @mattlewis92,

Thanks for your answer unfortunately, I had already try this solution but it isn't working.

Here below you can find my customHourSegmentTemplate

```
<ng-template #customHourSegmentTemplate
             let-segment="segment"
             let-locale="locale"
             let-segmentHeight="segmentHeight"
             let-isTimeLabel="isTimeLabel">
  <div class="cal-hour-segment"
       [style.height.px]="segmentHeight"
       [class.cal-hour-start]="segment.isStart"
       [class.cal-after-hour-start]="!segment.isStart"
       [ngClass]="segment.cssClass"
       #segmentTooltip="matTooltip"
       [matTooltip]="segment.displayDate | calendarDate: 'weekViewHour':locale"
       [matTooltipClass]="'tooltip tooltip--segment'"
       [matTooltipShowDelay]="100"
       (dragleave)="segmentTooltip.hide()"
       (dragenter)="segmentTooltip.show()">
    <div class="cal-time" *ngIf="isTimeLabel">
      {{ segment.displayDate | calendarDate: "weekViewHour":locale }}
    </div>
    <span class="now-line"
          *ngIf="!isTimeLabel && segment && isCurrentHourSegment(segment)"
          [style.top]="getCurrentHourSegmentOffset(segment, segmentHeight)">
    </span>
  </div>
</ng-template>
```

**Comment by mattlewis92** [comment]
Ah, I see the issue, you need to change:
```
   (dragleave)="segmentTooltip.hide()"
   (dragenter)="segmentTooltip.show()"
```

to 

```
    mwlDroppable
    (dragLeave)="showTooltip(false)"
    (dragEnter)="showTooltip(true)"
```

**Comment by ALapaque** [comment]
@mattlewis92 Yay !

Here is the mix I did :)

```
<!-- CUSTOM AGENDA SEGMENT -->
<ng-template #customHourSegmentTemplate
             let-segment="segment"
             let-locale="locale"
             let-segmentHeight="segmentHeight"
             let-isTimeLabel="isTimeLabel">
  <div class="cal-hour-segment"
       [style.height.px]="segmentHeight"
       [class.cal-hour-start]="segment.isStart"
       [class.cal-after-hour-start]="!segment.isStart"
       [ngClass]="segment.cssClass"
       #segmentTooltip="matTooltip"
       [matTooltip]="segment.displayDate | calendarDate: 'weekViewHour':locale"
       [matTooltipClass]="'tooltip tooltip--segment'"
       [matTooltipShowDelay]="100"
       mwlDroppable
       (dragLeave)="segmentTooltip.hide()"
       (dragEnter)="segmentTooltip.show()">
    <div class="cal-time" *ngIf="isTimeLabel">
      {{ segment.displayDate | calendarDate: "weekViewHour":locale }}
    </div>
    <span class="now-line"
          *ngIf="!isTimeLabel && segment && isCurrentHourSegment(segment)"
          [style.top]="getCurrentHourSegmentOffset(segment, segmentHeight)">
    </span>
  </div>
</ng-template>
```

in order to be able to display the tooltip from angular-material and it works well 👍 
Can you explain to a me a bit the direction mwlDroppable what does it do there ?

Does it allow to trigger the events on the dragLeave and dragEnter on the element marked ?

**Comment by mattlewis92** [comment]
> Does it allow to trigger the events on the dragLeave and dragEnter on the element marked ?
Yep that's right! They are defined in the `mwlDroppable` directive: https://github.com/mattlewis92/angular-draggable-droppable/blob/master/projects/angular-draggable-droppable/src/lib/droppable.directive.ts#L50-L58

**Comment by ALapaque** [comment]
Ok I see now :) @mattlewis92 thanks again for your help :)
