### ISSUE TITLE
Set dayStartHour and dayEndHour for each day

### ISSUE THREAD

**Issue by kyleabens** [mattlewis92/angular-calendar#1344]
**Is your feature request related to a problem? Please describe**

Some of my users hours of operation differ on specific days.

**Describe the solution you'd like**

I would love to have the ability to set start and end hours for each day.  I know this is difficult when it comes to the week view so maybe take whatever the earliest and latest times are throughout the week then simply disable the time slots in each day column to match what is set.

**Describe your use case for implementing this feature**

A preference for businesses to set their hours of operation for each day

**Comment by ALapaque** [comment]
Hi @kyleabens 

I've myself a dynamic view depending on placement of events and availability periods working on weekView. I'm just calling a method which will calculate the startHour & endHour and the display days.

so for the day view you could do the same by storing an object containing the day (ISO format) the startHour and the endHour. and when you _init your component you _init the view parameters and so on.

**Comment by kyleabens** [comment]
@ALapaque So are you able to display for example 9 am to 5 pm on Monday - Friday and 10 am to 1 pm on Saturday - Sunday?

**Comment by ALapaque** [comment]
@ALapaque visually you're not really able to hide timeslots in the weekView but you could display a pattern which will means that this timeslot is unavailable. and you could disable the click event on it.

But mainly the startDayhour and endDayHour would be the minimum start and the maximum end of your week.

**Comment by ALapaque** [comment]
@kyleabens here's a little sceenshot of what you can do
the x will be the timeslot unclickable

![image](https://user-images.githubusercontent.com/46450511/95066776-227f5a80-0703-11eb-8005-61624927c4bd.png)

here what I've been able to do in my calendar component (sorry i'm from belgium so the hours and days are in french)

![image](https://user-images.githubusercontent.com/46450511/95073900-e56c9580-070d-11eb-87b4-603d0d3fd6ee.png)

**Comment by mattlewis92** [comment]
Hey there, I would recommend doing exactly what @ALapaque said to. So you can use the `beforeViewRender` output to add some disabled css classes to the hours + days you want to be disabled. And then if you upgrade to the [next version of the calendar](https://github.com/mattlewis92/angular-calendar/pull/1249) there is [a new api](https://github.com/mattlewis92/angular-calendar/issues/1183#issuecomment-633054038) where you can control where users can drag and resize events to, so you can block them from putting events on those times and days. Let me know if you need any other help! 😄

**Comment by stefanomiccoli** [comment]
Hi @mattlewis92 although the use of beforeViewRender by itself works fine to "disable" the cells, it does not play well with the "drag to create events" scenario. 

While dragging, everytime the cursor changes cell, and thus the event gets bigger, the `beforeViewRender` is triggered, and all the cells (all days, all hours, all segments) have to be iterated to assign the "disable" class. The faster the user drags, the worse the ux is, as you see from the console that the calls to `beforeViewRender` cant keep the pace.

If it was possible to either disable the cells or assign the class only when the view changes (expecting the component to retain such class) would definitely give a boost

**Comment by dvdnhm** [comment]
in my case, the calendar is read-only. I just display events on the day & week view. 

Would I break anything if I set display: none to with the "disable" class?
