### ISSUE TITLE
Set start hour so the view automatically scrolls to that value on init

### ISSUE THREAD

**Issue by Venipa** [mattlewis92/angular-calendar#1345]
**Is your feature request related to a problem? Please describe**
No.

**Describe the solution you'd like**
Scroll to cal-current-time-marker or scroll to a HH:mm/Hour start value

**Describe your use case for implementing this feature**
set the start view to 6am but having it still be scrollable to < 6am

**Additional context**
week-view (scrollable)

**Comment by mattlewis92** [comment]
Hey there, as the calendar doesn't actually make any elements scrollable it's not something that can be baked in, but you can implement it yourself fairly easily. The trick is that each hour is 60 pixels in height, so to get the correct scrollTop, it's just the difference in minutes between midnight and where you want to scroll to. I put together a demo showing how to do that here, hope that helps!

https://angular-calendar.com/#/scroll-to-current-time
