### ISSUE TITLE
pb with displaying events (DST issue)

### ISSUE THREAD

**Issue by pjv03** [mattlewis92/angular-calendar#1348]
**Describe the bug**
Hi.
Found issue when displaying slots on calendar on 25th of October for Europe/London (for instance).
Same issue on your demo https://angular-calendar.com/#/kitchen-sink, try to add event on 25th of October

Can you fix it?

Thx.

**Minimal reproduction of the problem with instructions**

**Screenshots**
<img width="1388" alt="Снимок экрана 2020-10-06 в 19 03 04" src="https://user-images.githubusercontent.com/23629322/95227698-18468480-0807-11eb-98d8-7a9e4a8e33d7.png">

**Versions**

- `@angular/core`: 10.1.4
- `angular-calendar`: 0.28.20
- Browser name and version: all

**Comment by pjv03** [comment]
Other linked issue. When try to create event on this date (DST issue) from 00 to 04 AM and from 04AM to 05AM (for instance), displayed not ok and displayed date inside event not ok too. 
<img width="1370" alt="Снимок экрана 2020-10-16 в 14 04 52" src="https://user-images.githubusercontent.com/23629322/96251415-1b850180-0fb9-11eb-8a88-f1c093df3bfd.png">
<img width="1377" alt="Снимок экрана 2020-10-16 в 14 04 44" src="https://user-images.githubusercontent.com/23629322/96251419-1cb62e80-0fb9-11eb-8d15-4ca7e88c171b.png">

**Comment by mattlewis92** [comment]
Oh no, I thought all the DST issues were finally fixed, I will do my best to get that fixed up in the next version! 😄

**Comment by pjv03** [comment]
thx, waiting!

**Comment by mattlewis92** [comment]
Should be fixed now in `0.28.21`, thanks for letting me know! 😄

**Comment by pjv03** [comment]
@mattlewis92 issue fixed, thx a lot :)
