### ISSUE TITLE
How to use it with Ionic 2?

### ISSUE THREAD

**Issue by alexandretok** [mattlewis92/angular-calendar#135]
Hi, can you explain a little bit how one would implement this on a ionic 2 project?

Thanks

**Comment by mattlewis92** [comment]
This lib is more focused on desktop usage, for mobile the UX isn't that great. I'd recommend using a component that's specifically designed for ionic, a quick google found these:
https://github.com/twinssbc/Ionic2-Calendar
https://market.ionic.io/themes/ioniccalendar
