### ISSUE TITLE
Conditional disabling of tooltips

### ISSUE THREAD

**Issue by davidbauman** [mattlewis92/angular-calendar#1351]
**Is your feature request related to a problem? Please describe**

When implementing angular-calendar in an Ionic PWA and showing a modal component on top of the calendar view for instance when double clicking an event, the tooltip is visible on top of the modal component.

**Describe the solution you'd like**

One pssible solution to the issue would be to be able to conditionally disable tooltips, so that tooltip can be disabled when double clicking on an event while still be visible on single click. For example, [tooltipDisabled] = "customCondition" could be added when using mwl-calendar-week-view and/or mwl-calendar-day-view selector.

**Describe your use case for implementing this feature**

My html would be able to use it the following way:

<mwl-calendar-week-view
      [viewDate]="viewDate"
      [events]="events"
      [dayStartHour]="6"
      [dayEndHour]="23"
      [hourSegments]="1"
      [daysInWeek]="daysInWeek"
      [excludeDays]="[]"
      [hourSegmentHeight]="25"
      [weekStartsOn]="1"
      [refresh]="refresh"
      [tooltipDisabled]="customTooltipCondition"
      locale="en"
      (dayHeaderClicked)="openEventModal($event.day.date, true, true)"
      (hourSegmentClicked)="openEventModal($event.date, true, false)"
      (eventClicked)="eventClicked($event)"
      >
    </mwl-calendar-week-view>

**Additional context**

**Comment by mattlewis92** [comment]
Hey there! I put together an example based off the [disabled tooltips demo](https://angular-calendar.com/#/disable-tooltips) to show you how you can toggle tooltips conditionally, I hope that works ok for you! 😄 https://stackblitz.com/edit/angular-hnbosl?file=demo%2Fcomponent.ts
