### ISSUE TITLE
How to show events by a users list in the Week/Month View

### ISSUE THREAD

**Issue by issemgane** [mattlewis92/angular-calendar#1354]
**Is your feature request related to a problem? Please describe**

**Describe the solution you'd like**
Show events by a users list in the Week/month view

**Describe your use case for implementing this feature**

currently i want to change the way of showng events in the calendar by showing events by a users list in the both views Week and Month , and this is what i want to show
**Additional context**

![image](https://user-images.githubusercontent.com/9163364/95724083-36343f00-0c76-11eb-94fe-5bda78b60882.png)

![image](https://user-images.githubusercontent.com/9163364/95723952-0ab15480-0c76-11eb-8e6b-ae464a3cbd9f.png)

**Comment by mattlewis92** [comment]
Hey there, there's no support for this kind of functionality but you could [build your own components](https://github.com/mattlewis92/angular-calendar#the-month-week-or-day-view-doesnt-meet-my-project-requirements-but-the-other-views-do) that work like this, using the `calendar-utils`, `angular-draggable-droppable` and `angular-resizable-element` packages to do a lot of the heavy lifting. The [day view scheduler](https://angular-calendar.com/#/day-view-scheduler) demo gives an example of how this can be done. Hope that helps! 😄
