### ISSUE TITLE
Calendar does not show 31th of October

### ISSUE THREAD

**Issue by EFritzsche90** [mattlewis92/angular-calendar#1355]
**Describe the bug**

There is a day missing in the calendar view. For my implementation and also within the demo it is not possible to show the 31th of October 2020

**Minimal reproduction of the problem with instructions**

1. Open calendar view
2. Navigate to October 2020

**Screenshots**

<img width="1358" alt="Bildschirmfoto 2020-10-13 um 00 38 54" src="https://user-images.githubusercontent.com/53464225/95796270-be552b80-0cec-11eb-9041-7f309406a32a.png">

**Versions**

- `@angular/core`: 9.1.0
- `angular-calendar`: 0.28.20
- Browser name and version: Chrome

**Comment by mattlewis92** [comment]
Hey there, your issue is caused because you're setting the `excludeDays` option to hide weekends, and as 31st of october 🎃 is on a saturday it doesn't display.
