### ISSUE TITLE
Current time marker not showing in Day View Scheduler

### ISSUE THREAD

**Issue by fzs1994** [mattlewis92/angular-calendar#1357]
**Describe the bug**
The current time marker (Red Marker line) is not showing in Day View Scheduler. 

**Minimal reproduction of the problem with instructions**
https://angular-calendar.com/#/day-view-scheduler

**Screenshots**

**Versions**

- `@angular/core`: ^9.1.6
- `angular-calendar`: ^0.28.15
- Browser name and version: Chrome v86.0.4240.75

**Comment by mattlewis92** [comment]
Fixed now, thanks for letting me know! 😄

**Comment by fzs1994** [comment]
Thanks a lot! @mattlewis92
