### ISSUE TITLE
Drag all day event to a certain time in week or day view

### ISSUE THREAD

**Issue by captainmorgan0** [mattlewis92/angular-calendar#1358]
**Is your feature request related to a problem? Please describe**

We have the calendar that has jobs on it. Sometimes users create an all day job, then decide to change it to a job at a certain time in the day. They can't drag/drop the all day job to that time.

**Describe the solution you'd like**

In Week and Day view, it would be great if users can drag the all day job to a certain time.

**Describe your use case for implementing this feature**

Our employees will sometimes be unsure of when the start time of a job is, so when they initially create the job, they just set the day and have the job as all day. When they know th start time, they want to drag the all day job to that start time.

**Additional context**

**Comment by mattlewis92** [comment]
Hey there, you can actually already do this by setting the `[snapDraggedEvents]="false"` input on the day and week views. There is a demo showing it working here: https://angular-calendar.com/#/draggable-external-events

![CleanShot 2020-10-21 at 10 41 41](https://user-images.githubusercontent.com/6425649/96702834-0ed22600-138a-11eb-8517-b27e77ec31da.gif)

Hope that helps! 😄
