### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by avanerk** [mattlewis92/angular-calendar#136]
I couldn't find anything about localization besides this issue: https://github.com/mattlewis92/angular-calendar/issues/84
However, the links don't work anymore. Is there an updated version somewhere?

**Comment by mattlewis92** [comment]
The docs have [moved here](https://mattlewis92.github.io/angular-calendar/docs/components/CalendarMonthViewComponent.html), the options you want are `locale` and `weekStartsOn`. There is an e2e demo of it [working here](https://mattlewis92.github.io/angular-calendar/demos/#/i18n). Hope that helps!
