### ISSUE TITLE
is there any way to set an appointment/event only on marked available date/time?

### ISSUE THREAD

**Issue by ermarkar** [mattlewis92/angular-calendar#1361]
**Is your feature request related to a problem? Please describe**

is there any way to set an appointment/event only on marked available date/time?
Suppose I want to share the calendar between doctor and patient.

Doctor can mark availability of visiting, patient can make booking only on available dates.

Is it possible?

**Comment by mattlewis92** [comment]
Hey there, you can use the `beforeViewRender` output to make certain times appear as disabled which I think does what you're after: https://angular-calendar.com/#/before-view-render Hope that helps!
