### ISSUE TITLE
Drag and Drop issue

### ISSUE THREAD

**Issue by shreyshahh** [mattlewis92/angular-calendar#1362]
**Describe the bug**

Hi, I am having an issue in drag and drop in calendar, when I drag any event the mouse pointer and event are on different places. I’ve kept screen shot describing that. 

I am using Nebular, An angular library and in this library when I use this calendar on NbFlipCard component, then I am facing this issue and if I use NbCard then it works fine. Below is the link regarding the Nebular Angular UI library
https://akveo.github.io/nebular/docs/components/flip-card/overview#nbflipcardcomponent. 

**Edit:** 
This is working fine in Day and Week pages, only in month it is not showing properly.
Also tried using this calendar in ngx-flip (https://www.npmjs.com/package/ngx-flip), still this issue occurs

Any help on  how to  solve that issue? Thanks.

**Screenshots**
![98210F4B-2FA5-4186-BA1B-383466CBF0A2](https://user-images.githubusercontent.com/59005332/97134428-330b7980-1773-11eb-9cdf-87856459ae6f.jpeg)

**Versions**

- `@angular/core`: 9.1.0
- `angular-calendar`: 0.28.16

**Comment by mattlewis92** [comment]
Hey there, I'm not able to reproduce the problem you're having on my end, if you're still facing issues would you mind putting together a runnable stackblitz that demonstrates the issue you're having. You can fork a starter from any of the demos by hitting the "Edit in stackblitz" button. Thanks! 🙌

**Comment by shreyshahh** [comment]
Hi, thanks for the reply this is runnable stackblitz to demonstrate the issue,

https://angular-3qjm3h.stackblitz.io

If you don't see any issue while drag and drop, scroll down the calendar to the bottom of the page and then try dragging the event you will got to see the issue.

![WhatsApp Image 2020-10-27 at 11 29 35 AM](https://user-images.githubusercontent.com/59005332/97262983-ff4e5380-1847-11eb-8dae-aa02e424edfd.jpeg)

**Comment by mattlewis92** [comment]
Awesome, thanks! I can reproduce now 😄

**Comment by mattlewis92** [comment]
Hey there, I couldn't find a way of making this work out of the box but I did find a workaround for your specific issue. When dragging an event I apply a css class that disables the CSS applied by ngx-flip which causes the issue by applying these global styles:
```

<style>

  ngx-flip.disable-flip {
    perspective: none !important;
  }

  .disable-flip .flipper {
    transform-style: flat !important;
  }

  .disable-flip .front {
    transform: none !important;
  }

</style>
```

and that seems to work pretty well, [there's a demo here](https://stackblitz.com/edit/angular-3qjm3h-zjxbew?file=index.html) showing it in action. Hope that helps! 😄

**Comment by shreyshahh** [comment]
Hi, thanks for the solution, any idea on what styling I need to use if I use [Nebular Flip Card] instead of Ngx Flip (https://akveo.github.io/nebular/next/docs/components/flip-card/overview#nbflipcardcomponent)

**Comment by mattlewis92** [comment]
I haven't tested it, but I think this will work:

```
<style>

  nb-flip-card.disable-flip, .disable-flip .front-container {
    perspective: none !important;
  }

  .disable-flip .flipcard-body {
    transform-style: flat !important;
  }
</style>
```

If it doesn't work, all I did was go through each element with the chrome devtools and unchecked css properties until it started working:
![image](https://user-images.githubusercontent.com/6425649/98654047-b57c6780-2335-11eb-83cb-f78b29999f45.png)

**Comment by shreyshahh** [comment]
Awesome, Thank You! it is working properly. 👍 :)
