### ISSUE TITLE
Context menu on right click of event.

### ISSUE THREAD

**Issue by Sushma-tiwari** [mattlewis92/angular-calendar#1365]
**Is your feature request related to a problem? Please describe**
Context menu on right click of the event.

I need a context menu on the right-click of the event, not on the hour segment.

**Describe the solution you'd like**
When right-click on the event it should open the context menu(not on right click of hour segments).

I need a context menu on the right-click of the event, not on the hour segment.

I need a context menu on the right-click of the event, not on the hour segment.
**Describe your use case for implementing this feature**
I need a context menu on the right-click of the event, not on the hour segment.

I need a context menu on the right-click of the event, not on the hour segment.

![image](https://user-images.githubusercontent.com/66738000/97443856-84715f80-1951-11eb-9536-62b23f2beff0.png)

**Comment by mattlewis92** [comment]
Hey there, you can achieve this by passing a custom `eventTemplate` to the week view based off [this template](https://github.com/mattlewis92/angular-calendar/blob/master/projects/angular-calendar/src/modules/week/calendar-week-view-event.component.ts#L18-L71) following [this guide](https://github.com/mattlewis92/angular-calendar#how-do-i-use-a-custom-template) and then use another library like `ngx-contextmenu` to add context menus to the custom template. Hope that helps!

**Comment by Sushma-tiwari** [comment]
> Hey there, you can achieve this by passing a custom `eventTemplate` to the week view based off [this template](https://github.com/mattlewis92/angular-calendar/blob/master/projects/angular-calendar/src/modules/week/calendar-week-view-event.component.ts#L18-L71) following [this guide](https://github.com/mattlewis92/angular-calendar#how-do-i-use-a-custom-template) and then use another library like `ngx-contextmenu` to add context menus to the custom template. Hope that helps!

It working fine thank you 👍

**Comment by calldeludo** [comment]
> > Hey there, you can achieve this by passing a custom `eventTemplate` to the week view based off [this template](https://github.com/mattlewis92/angular-calendar/blob/master/projects/angular-calendar/src/modules/week/calendar-week-view-event.component.ts#L18-L71) following [this guide](https://github.com/mattlewis92/angular-calendar#how-do-i-use-a-custom-template) and then use another library like `ngx-contextmenu` to add context menus to the custom template. Hope that helps!
> 
> It working fine thank you 👍

Could you share your solution? i have ngx-contextmenu installed but i still cant open it properly over my event... thanks in advance.
