### ISSUE TITLE
I would like to inform you that the year(Buddhist calendar) is wrong

### ISSUE THREAD

**Issue by Mintnsrtt** [mattlewis92/angular-calendar#1372]
**Describe the bug**

Hello
I'd like to inform you that the year(Buddhist calendar) is still wrong because it should +543. , just like in [this example](https://stackblitz.com/edit/angular-hhe4vg?file=demo%2Fmodule.ts)

For example 
2020 ---> 2563
2021 ---> 2564

Thank you!
Nisarat

**Screenshots**
![1605516715408](https://user-images.githubusercontent.com/28251012/99231846-bfb1d080-2823-11eb-83d0-48f9d3b71c20.jpg)

**Versions**
- `@angular/core`:^7.2.1
- `angular-calendar`:^0.28.22
- Browser name and version:Google Chrome v.86.0.4240.193

**Comment by mattlewis92** [comment]
Hey there, thanks for opening an issue. While multiple languages are supported, the calendar only works with gregorian calendars out of the box. But you can use a custom date formatter to adjust the years in each title to work with the buddhist calendar. I put together an example for you of how to do that [here](https://stackblitz.com/edit/angular-c4h7g5?file=demo/custom-date-formatter.provider.ts). Hope that helps! 😄
