### ISSUE TITLE
Add option text color to the Event

### ISSUE THREAD

**Issue by alexsintoni** [mattlewis92/angular-calendar#1375]
**Is your feature request related to a problem? Please describe**

It would be great to have the possibility to configure the color of the text in the EventColor interface inside CalendarEvent interface together with primary and secondary colors. The reason is that the primary color can conflict with the text one and it is not possible to read the title in the scheduler.

**Describe the solution you'd like**

Add in the EventColor interface text as it is possible for primary and secondary colors.

**Describe your use case for implementing this feature**

Users have the possibility to select the primary color of an event using a color picker component that offer all possible colors.
If the user are not paying attention to the color chosen, the title is not visible anymore in the scheduler. Therefore, it would be great to have the possibility to select the color of the text as well.

**Comment by mattlewis92** [comment]
Thanks to @angelaki, this has now been implemented in `0.30.0` 🥳
