### ISSUE TITLE
Tooltip for event actions

### ISSUE THREAD

**Issue by FelixLAntony** [mattlewis92/angular-calendar#1380]
Is there a way to show tooltip for the event actions using the default configuration? Since they are hyperlinks, the title property can be used, right behind the scenes. I want to do it without using custom templates.

**Describe the bug**

**Minimal reproduction of the problem with instructions**

**Screenshots**

**Versions**

- `@angular/core`:
- `angular-calendar`:
- Browser name and version:

**Comment by billyjov** [comment]
This can be archieve if you built a custom template
