### ISSUE TITLE
Click on empty cell in day view scheduler and get column header

### ISSUE THREAD

**Issue by emilyr-oos** [mattlewis92/angular-calendar#1381]
**Is your feature request related to a problem? Please describe**

When implementing the day view scheduler as seen [here](https://angular-calendar.com/#/day-view-scheduler) I can't find a way to get the column header when clicking an empty cell.

**Describe the solution you'd like**

I've implemented the day view scheduler as well as a click event for empty cells that fires from hourSegmentClicked but I would like to be able to have the column headers title passed through in this click event. I can't find a way to access this information. 

**Describe your use case for implementing this feature**

I would like the header information for the column clicked on to be passed through so that I can have a popup for a new event to be created that auto-fills the user from the column in addition to the date and time. 

**Additional context**

![Screenshot (49)_LI](https://user-images.githubusercontent.com/72626389/101416300-2bc9a680-38af-11eb-9d89-f86ef628b086.jpg)

When clicking on the red box here is it possible for it to pass through the user's name (John Smith)?

**Comment by ALapaque** [comment]
@emilyr-oos I did this by overriding some interfaces and settings my user in the meta.

**Comment by billyjov** [comment]
>@emilyr-oos I did this by overriding some interfaces and settings my user in the meta.

@emilyr-oos you can take a look on the suggested solution

**Comment by abdulrahman5020** [comment]
@emilyr-oos  Did you find a solution? Can you share it ?

**Comment by pablooliveira01** [comment]
<mwl-calendar-week-view [events]="events" (mwlClick)="onEmptySlotClicked($event)">

`onEmptySlotClicked(mouseEvent: any) {
    const rowxcol = mouseEvent.target.closest(".cal-hour");
    let rowxcolIndex = ([...rowxcol?.parentElement?.children].indexOf(rowxcol) - 2);
    let rowDate = mouseEvent?.target?.offsetParent?.__ngContext__[35][rowxcolIndex];
}`

You can reach out the data related to the empty clicked cell by the code above. That's not a great solution, because we're accessing the ngContext by a fixed index. Anyway, you can debug the code above and try to adapt it for your problem.

That's worked in my case. 👍
