### ISSUE TITLE
Passing a custom openDayEventsTemplate with the [@collapse] could not be found

### ISSUE THREAD

**Issue by RRGT19** [mattlewis92/angular-calendar#1384]
**Describe the bug**

I would like to pass a custom `openDayEventsTemplate` to the `mwl-calendar-month-view` to show the events with my custom style.

For the custom template that I'm passing, I'm using the same [example here](https://github.com/mattlewis92/angular-calendar/blob/a5fe1f975ecf332c96797326f48081e5d02d264d/projects/angular-calendar/src/modules/month/calendar-open-day-events.component.ts) to test it first.

Then, I receives the following errors in console:
```
ERROR Error: Found the synthetic property @collapse. Please include either "BrowserAnimationsModule" or "NoopAnimationsModule" in your application.
    at checkNoSyntheticProp (platform-browser.js:778)
    at EmulatedEncapsulationDomRenderer2.setProperty (platform-browser.js:760)
    at BaseAnimationRenderer.setProperty (animations.js:299)
    at elementPropertyInternal (core.js:9681)
    at Module.ɵɵproperty (core.js:14419)
```

Inside of my `app.module` I have the `BrowserAnimationsModule` in `imports`, but the error persist. This situation causes that if you click on another day locating in a different row, no animation is present and no events are shown.

**Minimal reproduction of the problem with instructions**

Just do a fresh install of an Angular project, install the library following the [instructions](https://github.com/mattlewis92/angular-calendar#getting-started) and add this in the template of your component _(component logic is omitted, it's the same as the official [example](https://angular-calendar.com/#/async-events))_:

```html
<mwl-calendar-month-view
[viewDate]="viewDate"
[events]="events"
[cellTemplate]="customCellTemplate"
[openDayEventsTemplate]="customOpenDayEventsTemplate" <!-- added here -->
[activeDayIsOpen]="activeDayIsOpen"
(dayClicked)="dayClicked($event.day)">
</mwl-calendar-month-view>
  
<ng-template
  #customOpenDayEventsTemplate
  let-events="events"
  let-isOpen="isOpen">

<!-- The [@collapse] is causing the error. -->
  <div class="cal-open-day-events" [@collapse] *ngIf="isOpen">
    <div *ngFor="let event of events" [ngClass]="event?.cssClass">
      <span class="cal-event" [style.backgroundColor]="event.color?.primary"></span>
      <mwl-calendar-event-title [event]="event"
                                view="month">
      </mwl-calendar-event-title>
    </div>
  </div>

</ng-template>
```

I'm not sure if this is a bug or I'm trying to implement a custom template in the wrong way. It appears that the only way to keep the animations is having the `[@collapse]` present, but even with it, it is not working.

**Screenshots**

None.

**Versions**

- `@angular/core`: 11.0.2
- `angular-calendar`: 0.28.22
- Browser name and version: Google Chrome v87.0.4280.88

**Comment by ChaviBon** [comment]
I've ran into the same issue, however when you disable the slide animation as explained here https://angular-calendar.com/#/disable-slide-animation , I was able to simply remove the [@collapse] and have the 'Open Day Events' functionality working with my custom template. There's no animation, yet I prefer it this way anyway.

**Comment by KarthikSamyak** [comment]
Declare this in your own component.ts where you are writing your custom template

`export const collapseAnimation: AnimationTriggerMetadata = trigger('collapse', [
   transition('void => *', [
    style({ height: 0, overflow: 'hidden' }),
    animate('150ms', style({ height: '*' }))
  ]),
  transition('* => void', [
    style({ height: '*', overflow: 'hidden' }),
    animate('150ms', style({ height: 0 }))
  ])
]);`

`@Component({
  selector: 'app-month-view',
  templateUrl: './month-view.component.html',
  styleUrls: ['./month-view.component.css'],
  animations: [collapseAnimation]
})`

**Comment by mattlewis92** [comment]
👆 Exactly what @Lesmian said!
