### ISSUE TITLE
Adapter for DayJs

### ISSUE THREAD

**Issue by lippomano** [mattlewis92/angular-calendar#1387]
**Is your feature request related to a problem? Please describe**

I have just switched from momentjs to dayjs but I see that your calendar does not have an adapter for [dayjs](https://day.js.org/);
Do you plan to implement it or is there any workaround to use dayjs?

**Comment by mattlewis92** [comment]
Thanks to the great work by @lukaonik and @xigolle this is now possible! There's a demo showing how to use dayjs with the calendar here: https://angular-calendar.com/#/dayjs You just need to make sure you're on the latest version of calendar-utils by doing `npm update calendar-utils --depth 2` 🥳

**Comment by basstune** [comment]
Hi, we're trying to migrate from moment to dayjs as well. @mattlewis92 can you please update the link to the demo here?

**Comment by mattlewis92** [comment]
Here ya go! https://mattlewis92.github.io/angular-calendar/#/dayjs

**Comment by dominikbrazdil** [comment]
Worth to mention that in order for the timezone to work you need to pass dayjs.tz to adapterFactory and MOMENT (which is not included in the demo)
