### ISSUE TITLE
ActiveDayIsOpen does not work for days without events

### ISSUE THREAD

**Issue by hassanthegooner** [mattlewis92/angular-calendar#139]
I've noticed that setting activeDayIsOpen to true only works when there are events. Thus, while today's date is shown clearly, there is no way to have it in a _selected_ state when first viewing the calendar and if today's date has no events in it. 

Is there a way to have today's day selected when viewing the calendar even if there are no events for that day?

**Comment by mattlewis92** [comment]
The calendar makes no assumptions about what to do if there are no events or not, that logic is up to you. Assuming you've copied the demo code, you need to remove this line: https://github.com/mattlewis92/angular-calendar/blob/master/demos/demo-modules/kitchen-sink/component.ts#L107

Working plunker: http://plnkr.co/edit/nJ0FKVRXbmh7dTQXymDK?p=preview

Hope that helps!
