### ISSUE TITLE
calendar current marker real time update.

### ISSUE THREAD

**Issue by Sushma-tiwari** [mattlewis92/angular-calendar#1400]
**Is your feature request related to a problem? Please describe**

I m using an angular calendar for my application and also have a current time marker and auto-scroll to the current time marker when the first time comes to the calendar.
But now I need the current time marker should update real-time like if I see the calendar I see the calendar at 5:00 pm and at 5:10 pm still I am on the calendar page then it should auto-scroll with the template marker at 5:10 pm in the calendar.
**Describe the solution you'd like**

I m using an angular calendar for my application and also have a current time marker and auto-scroll to the current time marker when the first time comes to the calendar.
But now I need the current time marker should update real-time like if I see the calendar I see the calendar at 5:00 pm and at 5:10 pm still I am on the calendar page then it should auto-scroll with the template marker at 5:10 pm in the calendar.
**Describe your use case for implementing this feature**

**Additional context**
![image](https://user-images.githubusercontent.com/66738000/106449317-daeabe80-64a9-11eb-9ed8-0422310b906b.png)

**Comment by Sushma-tiwari** [comment]
Urgent help needed if anyone has any desire solution please provide it.

**Comment by billyjov** [comment]
@Sushma-tiwari real time update is actually not supported. Feel free to open a new issue with a feature proposal and a description of a possible solution
