### ISSUE TITLE
Cannot access dayEvent variable in custom event Template for <mwl-calendar-day-view>

### ISSUE THREAD

**Issue by nguyendo** [mattlewis92/angular-calendar#1405]
**Describe the bug**

Cannot access dayEvent variable in custom event Template for `<mwl-calendar-day-view>`.
Is there something that I'm missing? 
Thanks.

**Minimal reproduction of the problem with instructions**

Please use Stackblitz link below for minimal reproduction of the problem. 

[Stackblitz](https://stackblitz.com/edit/angular-xabjbw-3ipwrr?file=demo/template.html)

**Screenshots**

Please refer to screenshot below where it illustrates the issue of dayEvent being undefined.

![Screen Shot 2021-02-12 at 3 51 09 PM](https://user-images.githubusercontent.com/1015785/107834150-4f471c80-6d4a-11eb-8703-64ba06978762.png)

**Versions**

- `@angular/core`: 9.1.12 and 8.2.3
- `angular-calendar`: 0.28.22
- Browser name and version: Chrome 88.0.4324.146

**Comment by Myerden** [comment]
Hi, you should use weekEvent for day view.

Here is [example](https://stackblitz.com/edit/angular-xabjbw-o9yyyj?file=demo/template.html);

![image](https://user-images.githubusercontent.com/15304742/109114242-67596b80-774e-11eb-9fc2-25cc0bd613f6.png)

**Comment by nguyendo** [comment]
That works!
Thanks @Myerden.
