### ISSUE TITLE
When click on date, show event time also.

### ISSUE THREAD

**Issue by vinay13** [mattlewis92/angular-calendar#141]
When clicked on particular date of monthly view calendar , Event title show in just below the date here i want to add event time and want to style a bit .
How can i do this? 
Thanks in advance.

**Comment by mattlewis92** [comment]
See the demo for how to do this: https://mattlewis92.github.io/angular-calendar/demos/#/show-dates-on-titles

**Comment by vinay13** [comment]
import error while importing "CalendarEventTitleFormatter".

**Comment by vinay13** [comment]
no .. does it required.

**Comment by mattlewis92** [comment]
Yes as it was only added in 0.5.0: https://github.com/mattlewis92/angular-calendar/blob/master/CHANGELOG.md#breaking-changes-1 The upgrade process should be pretty smooth though.

**Comment by bachinas** [comment]
Hi mattlewis92

When i'm trying to use the calendar view to add event which are coming from API and i would like to add time slots along with start and end timings on the event,  is it possible to add such kind of events while adding evens. (I want this to be viewed the time slots on the day view). if it is possible what is the date format i need to provide for event?

Thanks in advance.
