### ISSUE TITLE
Sorting events problem

### ISSUE THREAD

**Issue by BloodOfEden** [mattlewis92/angular-calendar#1413]
Hi, I'm trying to create something nice with your calendar(I think you did great job with it) but I have a problem with sorting elements when events are parallel. I have few parallel items with different colors but they are not in the same columns.

image
![image](https://user-images.githubusercontent.com/19238179/108242431-31642800-714d-11eb-9542-951baba49def.png)

Is there any option to have all red events on the left side?

**Screenshots**

**Versions**

- "angular-calendar": "0.28.22"
- "@angular/core": "7.2.16"

**Comment by billyjov** [comment]
@BloodOfEden Can you provide a few more infos. I cannot really understand your issue

**Comment by pzurawskisii** [comment]
@billyjov I want to have e.g. all red events on the left, on the middle green and on the right blue. Do you know maybe how can I do it?
