### ISSUE TITLE
Unit tests breaking

### ISSUE THREAD

**Issue by Nostrus** [mattlewis92/angular-calendar#1416]
**Describe the bug**

Our unit tests (using Jest) started breaking after adding this package. Seems like module exports are not done in an expected way. 

The errors I get when running on node 14.16.0 are:
- `Unexpected value 'DragAndDropModule' imported by the module 'CalendarMonthModule'. Please add an @NgModule annotation.`
- `Importing DragAndDropModule which does not have a ɵmod property`

**Versions**

- `@angular/core`: 10.2.3
- `angular-calendar`: 0.28.22

**Comment by mattlewis92** [comment]
Hey there! Please could you provide a minimal runnable repro on github that reproduces the issue and I'll take a look into it 😄

**Comment by Nostrus** [comment]
Hi @mattlewis92 ! Managed to create a small repo now, let me know if it is enough for you to reproduce the issue or need more info: https://github.com/Nostrus/angular-calendar-test

**Comment by Nostrus** [comment]
Did you have a chance to check it out @mattlewis92 ?

**Comment by mattlewis92** [comment]
Hey, sorry about the late reply, I did some digging and couldn't figure out a solution, no matter what I tried I always seem to get that `which does not have a ɵmod property` error

**Comment by billyjov** [comment]
@Nostrus Do you really need to import `CalendarModule` in your tests ? I assume not. I just took a look at your Repository and i could fix your tests by removing the Module import from `spec` file.

```ts

describe('AppComponent', () => {
  beforeEach(async () => {
    await TestBed.configureTestingModule({
      declarations: [AppComponent],
      imports: [
        // CalendarModule.forRoot({
        //   provide: DateAdapter,
        //   useFactory: momentAdapterFactory,
        // }),
      ],
      schemas: [
        NO_ERRORS_SCHEMA
      ]
    }).compileComponents();
  });

```

**Comment by Nostrus** [comment]
> @Nostrus Do you really need to import `CalendarModule` in your tests ? I assume not. I just took a look at your Repository and i could fix your tests by removing the Module import from `spec` file.
> 
> ```ts
> describe('AppComponent', () => {
>   beforeEach(async () => {
>     await TestBed.configureTestingModule({
>       declarations: [AppComponent],
>       imports: [
>         // CalendarModule.forRoot({
>         //   provide: DateAdapter,
>         //   useFactory: momentAdapterFactory,
>         // }),
>       ],
>       schemas: [
>         NO_ERRORS_SCHEMA
>       ]
>     }).compileComponents();
>   });
> ```

Well, my example repo's only purpose was to show the error, but it's not really a real-life scenario. In our production app CalendarModule was part of a bigger shared module, so couldn't just remove it without restructuring the app. Even if that works (thanks for the suggestion, could be one way to go), feels like a workaround rather than an actual solution to the error.

**Comment by mattlewis92** [comment]
I just shipped a new version of the next version of the calendar and can confirm that it fixes the issue on the sample repo provided! 🥳 

Instructions on how to install and migrate on the PR here! https://github.com/mattlewis92/angular-calendar/pull/1249

**Comment by ethan-massie-vectorsolutions** [comment]
> I just shipped a new version of the next version of the calendar and can confirm that it fixes the issue on the sample repo provided! 🥳
> 
> Instructions on how to install and migrate on the PR here! #1249

I updated and that fixed my testing problems!

**Comment by mattlewis92** [comment]
Closing this out now that 0.29.0 is released as stable 😄
