### ISSUE TITLE
Cannot retrieve data from server

### ISSUE THREAD

**Issue by andy200486** [mattlewis92/angular-calendar#142]
Hi,

I've a service which get data from server by doing a get request : 
```
getUserCalendar(): Observable<Activity[]> {
        return this.http.get(urlServer)
           .map((activity: Response) => {
                return activity.json();
            });
    }
```
Then in my component I got this : 
```
events: Activity[] = [];
constructor(private calendarService: CalendarService) {}

    ngOnInit() {
        this.getUserCalendar();
    }

    getUserCalendar(): void {
        this.calendarService.getUserCalendar().subscribe(
            activity => {
for (let i = 0; i < activity.length; i++) {
                    this.events.push({                      
                        start: new Date(activity[i].start),
                        end: new Date(activity[i].end),
                        title: activity[i].title,
                        color: {
                            primary: '',
                            secondary: ''
                        }
                    });
                }
            },
            err => {
                console.log(err);
            });                
    }
```

On the first load, I don't see the data in the calendar.
I have to change from day or month to see my data in the calendar.
I've tried to follow the Async example but I can't achieve it.
Could you give me some example/help to resolve this ?

Thanks

**Comment by mattlewis92** [comment]
Your issue is caused because the events array never changed so change detection never kicks in. The simplest fix would be to create a new array by using the map operator:
```
getUserCalendar(): void {
        this.calendarService.getUserCalendar().subscribe(activities => {
              this.events = activities.map(activity => {
                return {                      
                  start: new Date(activity.start),
                  end: new Date(activity.end),
                  title: activity.title,
                  color: {
                    primary: '',
                    secondary: ''
                  }
                }
              });
            }, err => {
                console.log(err);
            });                
    }
```

Hope that helps!

**Comment by andy200486** [comment]
Thanks for your help. 
I've done what you say but it seems that my problem is still there.
Do you have an another idea ?

Thanks

**Comment by mattlewis92** [comment]
You could try using the `[refresh]` option to force the calendar to refresh. There's a demo of that in action here: https://mattlewis92.github.io/angular-calendar/demos/#/kitchen-sink

**Comment by andy200486** [comment]
Hi,
I try but doesn't change anything. I saw also in your async example that you set in the template : 
`[events]="(events | async) || []"`
If I set that too, I got this error : 

> EXCEPTION: Uncaught (in promise): Error: Error in ./CalendarComponent class CalendarComponent - inline template:84:8 caused by: Invalid argument '' for pipe 'AsyncPipe'

Thanks

**Comment by mattlewis92** [comment]
Have you initialised the `events` variable to be an observable?

**Comment by andy200486** [comment]
Hi,

Yes, I've been able to achieve it!

Thanks for the help.

**Comment by mattlewis92** [comment]
Glad you got it sorted 😄

**Comment by huny** [comment]
Hi,

I'm facing the same issue.
Could you please tell how the issue is resolved for you, as I'm not able to resolve it. I've tried all the options above.
