### ISSUE TITLE
Add <fa-icon> to actions --> label

### ISSUE THREAD

**Issue by Violetafm** [mattlewis92/angular-calendar#1426]
**Is your feature request related to a problem? Please describe**

Hi! I´m trying to add a editable/deletable event like in this example:
https://angular-calendar.com/#/editable-deletable-events

But instead of adding:
"label: < i class="fas fa-fw fa-pencil-alt">,"

I want to add something like this( I have tried many ways to write it):
"label : < fa-icon icon="faPlus">,"

**Describe the solution you'd like**

I would like add a fa-icon tag in the "label".
Something like this:
![Captura de pantalla 2021-03-22 a las 19 49 11](https://user-images.githubusercontent.com/6587888/112044066-a7432100-8b49-11eb-9c37-93ac0ad58f4e.png)

**Describe your use case for implementing this feature**

When I add a "fa-icon" and I inspect the html, there was not the "fa-icon" tag.

![Captura de pantalla 2021-03-22 a las 19 48 51](https://user-images.githubusercontent.com/6587888/112044103-b1fdb600-8b49-11eb-9b89-3bd71f590e5e.png)

Thanks :)

**Comment by sapabg** [comment]
@Violetafm 
I just ran into the problem.
You need to make a custom template for the event actions.
It is described here: https://github.com/mattlewis92/angular-calendar#how-do-i-use-a-custom-template
Basically you need to setup a custom template for openDayEventsTemplate of the month view and eventActionsTemplate for the actions buttons. Something like this:

`
<ng-template
  #customCellTemplate
  let-events="events"
  let-eventClicked="eventClicked"
  let-isOpen="isOpen">
  <div class="cal-open-day-events" *ngIf="isOpen">
    <div
      *ngFor="let event of events;"
      [ngClass]="event?.cssClass"
      mwlDraggable
      [class.cal-draggable]="event.draggable"
      dragActiveClass="cal-drag-active"
      [dropData]="{event: event}"
      [dragAxis]="{x: event.draggable, y: event.draggable}">
      <span
        class="cal-event"
        [style.backgroundColor]="event.color?.primary">
      </span>
      
      <mwl-calendar-event-title
        [event]="event"
        view="month"
        (mwlClick)="eventClicked.emit({event: event})">
      </mwl-calendar-event-title>
      
      <mwl-calendar-event-actions
        [event]="event"
        [customTemplate]="eventActionsTemplate">
      </mwl-calendar-event-actions>
    </div>
  </div>
</ng-template>

<ng-template #eventActionsTemplate let-event="event">
  <ion-buttons>
    <ion-button size="small" (click)="onEdit({event: event})">
      <ion-icon name="create-outline" slot="icon-only"></ion-icon>
    </ion-button>
    <ion-button size="small" (click)="deleteEvent({event: event})">
      <ion-icon name="trash-outline" slot="icon-only"></ion-icon>
    </ion-button>
  </ion-buttons>
</ng-template>

<mwl-calendar-month-view
    *ngSwitchCase="CalendarView.Month"
    [viewDate]="viewDate"
    [events]="events"
    [refresh]="refresh"
    [openDayEventsTemplate]="customCellTemplate"
    [activeDayIsOpen]="activeDayIsOpen"
    (dayClicked)="dayClicked($event.day)"
    (eventClicked)="handleEvent($event.event)"
    (eventTimesChanged)="eventTimesChanged($event)">
`

**Comment by sapabg** [comment]
@Violetafm 
You need to make a custom template:
https://github.com/mattlewis92/angular-calendar#how-do-i-use-a-custom-template

`<ng-template
  #customCellTemplate
  let-events="events"
  let-eventClicked="eventClicked"
  let-isOpen="isOpen">
  <div class="cal-open-day-events" *ngIf="isOpen">
    <div
      *ngFor="let event of events;"
      [ngClass]="event?.cssClass"
      mwlDraggable
      [class.cal-draggable]="event.draggable"
      dragActiveClass="cal-drag-active"
      [dropData]="{event: event}"
      [dragAxis]="{x: event.draggable, y: event.draggable}">
      <span
        class="cal-event"
        [style.backgroundColor]="event.color?.primary">
      </span>
      
      <mwl-calendar-event-title
        [event]="event"
        view="month"
        (mwlClick)="eventClicked.emit({event: event})">
      </mwl-calendar-event-title>
      
      <mwl-calendar-event-actions
        [event]="event"
        [customTemplate]="eventActionsTemplate">
      </mwl-calendar-event-actions>
    </div>
  </div>
</ng-template>

<ng-template #eventActionsTemplate let-event="event">
  <ion-buttons>
    <ion-button size="small" (click)="onEdit({event: event})">
      <ion-icon name="create-outline" slot="icon-only"></ion-icon>
    </ion-button>
    <ion-button size="small" (click)="deleteEvent({event: event})">
      <ion-icon name="trash-outline" slot="icon-only"></ion-icon>
    </ion-button>
  </ion-buttons>
</ng-template>

  <mwl-calendar-month-view
    *ngSwitchCase="CalendarView.Month"
    [viewDate]="viewDate"
    [events]="events$ | async"
    [refresh]="refresh"
    [openDayEventsTemplate]="customCellTemplate"
    [activeDayIsOpen]="activeDayIsOpen"
    (dayClicked)="dayClicked($event.day)"
    (eventClicked)="handleEvent($event.event)"
    (eventTimesChanged)="eventTimesChanged($event)">
  </mwl-calendar-month-view>`

**Comment by billyjov** [comment]
@Violetafm as @sapabg  this can be archieve with a custom template
