### ISSUE TITLE
long press event

### ISSUE THREAD

**Issue by Sirioxstar** [mattlewis92/angular-calendar#1427]
Hi,
i should modify the calendar as in the following gif. By long pressing, resize and drag and drop must be enabled.

Can you help me? thank you

![video](https://user-images.githubusercontent.com/6033302/112455181-c6180200-8d59-11eb-897b-4d9b32aa4c5d.gif)

**Is your feature request related to a problem? Please describe**

**Describe the solution you'd like**

**Describe your use case for implementing this feature**

**Additional context**

**Comment by billyjov** [comment]
@Sirioxstar this is not related to `angular-calendar`.

BTW. if you want to reponse to a long press you can check native event for keyboard.

Here is an example for long press events: https://stackblitz.com/edit/long-press
