### ISSUE TITLE
When click on date, 'mwl-calendar-open-day-events' below the calendar

### ISSUE THREAD

**Issue by vinay13** [mattlewis92/angular-calendar#143]
I'm required to change the selected date title or 'mwl-calendar-open-day-events' which is coming jus below the clicked date.
What i want is to show 'mwl-calendar-open-day-events' below the calendar.
Is there any examples available?

**Comment by mattlewis92** [comment]
Just so we're on the same page, you always want to display the events list below the calendar like this, regardless of which date is selected?
<img width="907" alt="screen shot 2017-02-10 at 12 52 38" src="https://cloud.githubusercontent.com/assets/6425649/22827443/d9ea0cae-ef8f-11e6-9aa4-cd8f1de24d98.png">

**Comment by vinay13** [comment]
Yes.

**Comment by mattlewis92** [comment]
You can abuse the internal components to achieve this. For example: http://plnkr.co/edit/39WsgQNI9gOjcQK3Ewd9?p=preview

**Comment by hello123456734** [comment]
Hi ..I would like the events list in the form of a table with multiple columns ...how should I go about doing the same? Also is it possible to use a datepicker to pick the date and have the month calender change according to the given date?

**Comment by sanmittal** [comment]
how to edit the event and upade latest event timing using a edit icon

**Comment by sanmittal** [comment]
edit icon should not work correctly in your code bro update the edit in project
