### ISSUE TITLE
Show day name with each date in month view?

### ISSUE THREAD

**Issue by lakhvirsingh41094** [mattlewis92/angular-calendar#1435]
**Is your feature request related to a problem? Please describe**

I'm always frustrated when I go to responsive view, it is very difficult to check the day in month view. 

**Describe the solution you'd like**

There should be some direct way that we can show the day name with each date in month view.

**Describe your use case for implementing this feature**
In my application, we need to show bookings on month view but when we open it on mobile it is difficult to detect the day of the date.

**Additional context**

This is how I want it https://nimb.ws/PrpwtW

**Comment by billyjov** [comment]
@lakhvirsingh41094 You can play with css for your need. 

e.g

Also you can define a custom header with an `ng-template` and deal with your custom header: 


```html

<ng-template #headerTemplate let-days="days" let-dayClicked="dayClicked"
  let-eventDropped="eventDropped">
  <div class="cal-cell-row cal-header">
    <div class="classes" *ngFor="let day of days">
      <div class="class-for-small-view">
        <!--  label for small view-->
      </div>
      <div class="class-for-large-view">
       <!--  label for large view-->
      </div>
    </div>
  </div>
</ng-template>

...
<mwl-calendar-month-view  
    [headerTemplate]="headerTemplate"
  </mwl-calendar-month-view>

```
