### ISSUE TITLE
Changing active border for focused event elements

### ISSUE THREAD

**Issue by johnzondr** [mattlewis92/angular-calendar#1436]
**Is your feature request related to a problem? Please describe**
When a user clicks on an event, there is a bold dark blue border that appears around the event. Is there a way to change the border styling?

<img width="281" alt="Screen Shot 2021-04-03 at 1 36 06 AM" src="https://user-images.githubusercontent.com/12823947/113443954-21628800-941d-11eb-8acc-bc28957b899e.png">

Thank you!

**Describe the solution you'd like**

**Describe your use case for implementing this feature**

**Additional context**

**Comment by billyjov** [comment]
@johnzondr You can just change the focus of event with a custom css
