### ISSUE TITLE
No Hour Segment in Week / Day view

### ISSUE THREAD

**Issue by jlaverdure-talis** [mattlewis92/angular-calendar#1437]
Hello,

I'm meeting an issue concerning the hour appearing of the calendar for the DAY / WEEK view.

I don't see any left branch for hour segments and I don't understand why it's not appearing since I've absolutely 0 console error.
The events also do not appear in it at all.

**Screenshots**
![image](https://user-images.githubusercontent.com/29701905/114053530-50e71980-988f-11eb-8a09-47eeb2fd3d84.png)

As you can see, the events do not appear and the hour on the left are not appearing as well.
The ascensor belongs to the main page.

I'm currently using Angular 6 version with the latest angular-calendar version.
I applied the procedure from a to z, from the import statement, to the style references. I took the exact same example of Kitchen sink for the CSS / TS / HTML / Module files : https://angular-calendar.com/#/kitchen-sink

I want the hour segments to appear but I have no clue what is the actual problem. I tried previous angular-calendar versions but I had issues with the Angular 6 environment. I pursued lots of possibilities but I'm quite blocked at the moment.

**Do someone has met this problem ? Did you find a solution ? Any hypothesis ?**
I'd really appreciate some help, this module is awesome.

(EDIT : I tried putting the code into the post but it didn't work. It's actually the same than Kitchen Sink without the possibility to modify the type of calendar / the event managing for demo purpose.)

PACKAGE.JSON : 
```json
"devDependencies": {
    "@angular-devkit/build-angular": "~0.8.0",
    "@angular/animations": "^6.1.9",
    "@angular/cdk": "^7.0.0-rc.0",
    "@angular/cli": "^6.2.4",
    "@angular/common": "6.1.9",
    "@angular/compiler": "6.1.9",
    "@angular/compiler-cli": "6.1.9",
    "@angular/core": "6.1.9",
    "@angular/forms": "6.1.9",
    "@angular/http": "6.1.9",
    "@angular/language-service": "6.1.9",
    "@angular/material": "^7.0.0-rc.0",
    "@angular/platform-browser": "6.1.9",
    "@angular/platform-browser-dynamic": "6.1.9",
    "@angular/router": "6.1.9",
    "@angular/tsc-wrapped": "^4.3.3",
    "@ng-bootstrap/ng-bootstrap": "^2.2.2",
    "@ngtools/json-schema": "^1.1.0",
    "@ngx-translate/core": "^10.0.2",
    "@ngx-translate/http-loader": "^3.0.1",
    "@types/hammerjs": "^2.0.36",
    "@types/leaflet": "^1.2.11",
    "awesome-typescript-loader": "^5.2.1",
    "codelyzer": "^4.5.0",
    "firebase": "^5.5.3",
    "jspdf": "^1.4.1",
    "jspdf-autotable": "^2.3.5",
    "ng2-tree": "^2.0.0-rc.11",
    "ngx-cookie": "^4.0.1",
    "ngx-toastr": "^9.1.0",
    "protractor": "^5.4.1",
    "rxjs": "^6.3.3",
    "tslint": "^5.11.0",
    "typescript": "^2.9.2",
    "uglifyjs-webpack-plugin": "^2.0.1"
  },
  "dependencies": {
    "@types/leaflet.markercluster": "^1.0.3",
    "@types/node": "^8.0.0",
    "angular": "^1.6.7",
    "angular-bootstrap-md": "^6.2.6",
    "angular-calendar": "^0.28.22",
    "angular-font-awesome": "^3.1.2",
    "angular2-cookie-law": "^6.0.4",
    "angular2-csv": "^0.2.9",
    "angular5-data-table": "^1.0.3",
    "angularx-flatpickr": "^6.5.2",
    "async-listener": "^0.6.9",
    "bootstrap": "^4.1.3",
    "chart.js": "^2.7.3",
    "continuation-local-storage": "^3.2.1",
    "date-fns": "^1.30.1",
    "flatpickr": "^4.6.9",
    "font-awesome": "^4.7.0",
    "leaflet": "^1.5.1",
    "leaflet-control-geocoder": "^1.6.0",
    "leaflet-easyprint": "^2.1.9",
    "leaflet-fullscreen": "^1.0.2",
    "leaflet.markercluster": "^1.4.1",
    "moment": "^2.22.2",
    "moment-timezone": "^0.5.21",
    "ng-material-multilevel-menu": "^4.0.8",
    "ng-pick-daterange": "^1.0.0",
    "ng2-file-upload": "^1.3.0",
    "ngx-cookie-service": "^1.0.10",
    "ngx-gallery": "^5.6.2",
    "ngx-mat-select-search": "^1.4.2",
    "rxjs-compat": "^6.3.3",
    "zone.js": "^0.8.26"
  }
```

**Versions**
    "@angular/core": "6.1.9",
    "angular-calendar": "^0.28.22",
- Browser name and version: Chrome : Latest version

**Comment by billyjov** [comment]
@jlaverdure-talis Can you provide a repository to reproduce the issue ?
