### ISSUE TITLE
Internalization doesn't work correctly

### ISSUE THREAD

**Issue by andy200486** [mattlewis92/angular-calendar#144]
Hi,

In the week view, internalization doesn't work correctly.
You can view that in your example too.
For example, in french it would be "Semaine 7 en 2017" and for now, it write "Week 7 of 2017"

**Comment by mattlewis92** [comment]
Ah yeah that's a weird edge case, as there are other words in the title beyond just the date. I've updated the demo to show you how to work around that. Thanks for reporting! 😄

**Comment by andy200486** [comment]
Where have you made your changes ? I don't see it.

Thanks

**Comment by mattlewis92** [comment]
No API change was needed, the demo was just wrong. See the commit for what changed: https://github.com/mattlewis92/angular-calendar/commit/e27d1f7a3991059337ba07dd88a53beb48fe5f69

and the full e2e demo: https://mattlewis92.github.io/angular-calendar/demos/#/i18n (sometimes github caching is a bit slow and can take time to update)

**Comment by andy200486** [comment]
Thanks for the workaround but I got this error when compiling : 

> Module ''date-fns/get_iso_week'' has no default export.

Do you have it also ?

**Comment by mattlewis92** [comment]
Ah I have to do some weird hack stuff in order to get this lib to work with rollup, I've fixed the demo now. You should either do
```
import { getISOWeek } from 'date-fns';
```

Or
```
import * as getISOWeek from 'date-fns/get_iso_week';
```

**Comment by andy200486** [comment]
Thanks!
