### ISSUE TITLE
Drag to create a event on same time

### ISSUE THREAD

**Issue by Julian-B90** [mattlewis92/angular-calendar#1447]
**Is your feature request related to a problem? Please describe**

We want to create a event per Drag on the same time. But current it is not possible.

**Describe the solution you'd like**

**Describe your use case for implementing this feature**

**Additional context**

<img width="756" alt="Bildschirmfoto 2021-04-20 um 11 59 53" src="https://user-images.githubusercontent.com/4377396/115377824-43eff180-a1d0-11eb-80a4-3df3c25197ca.png">
<img width="706" alt="Bildschirmfoto 2021-04-20 um 12 00 18" src="https://user-images.githubusercontent.com/4377396/115377828-44888800-a1d0-11eb-9a8b-ec68c0cb717e.png">

**Comment by mattlewis92** [comment]
Closing this one out as it can be resolved with CSS 😄 

```
.cal-week-view .cal-time-events .cal-events-container {
  width: 90%;
}
```
