### ISSUE TITLE
Build Failed: Type ModuleWithProviders is not generic

### ISSUE THREAD

**Issue by hockbeng97** [mattlewis92/angular-calendar#1462]
I have met the below error when trying to build

**Type 'ModuleWithProviders' is not generic**

It will not make the compile failed in local. But, it makes the build failed in the live environment.

**Versions**
- `@angular/core`: 6.0.2
- `angular-calendar`: 0.28.24
- Browser name and version: Chrome and latest version

**Comment by billyjov** [comment]
@hockbeng97 Can you pls provide a small repository to reproduce this issue?
