### ISSUE TITLE
[FEATURE] Year view

### ISSUE THREAD

**Issue by vogloblinsky** [mattlewis92/angular-calendar#147]
### Feature request:

Is a year view in the roadmap ?

**Comment by mattlewis92** [comment]
I purposefully didn't implement it in the angular 2 version as I don't believe it adds much value, as there's normally so many events in each month. Every project I've ever used the angular 1 version in, one of the first requests has always been to remove the year view. There's nothing to stop you building your own year view component and using it alongside the month / week / day components, but it's not something I really want to maintain as part of this lib.

**Comment by fergalddaly** [comment]
@mattlewis92 - from a user perspective it would be very useful in some circumstances. 
I expect that a lot of people will have done this themselves already (and I am not considering doing it as I need it but it's not available). Anyone wish to share code on an example of this working already ?
