### ISSUE TITLE
NG Add on Angular 12 not working

### ISSUE THREAD

**Issue by ThePatzen** [mattlewis92/angular-calendar#1471]
**Describe the bug**
NG install does fail

**Minimal reproduction of the problem with instructions**
on angular 12 execute ng add angular-calendar
```

i Using package manager: npm
√ Found compatible package version: angular-calendar@0.28.24.
√ Package information loaded.

The package angular-calendar@0.28.24 will be installed and executed.
Would you like to proceed? Yes
√ Package successfully installed.
An unhandled exception occurred: Cannot find module '@schematics/angular/utility/config'

```

**Versions**
- `@angular/core`: 12.0.3
- `angular-calendar`: 0.28.24
- Browser name and version: - unimportant -

**Comment by pwbuys** [comment]
A workaround is installing earlier version of schematics -the same one the library uses.

`npm install @schematics/angular@9.1.12.`

**Comment by ThePatzen** [comment]
ok thx!

**Comment by mattlewis92** [comment]
Thank you for reporting the issue, this is now fixed in `0.28.26`! 🎉

**Comment by mknookppw** [comment]
This is ineed solved for version 0.28.26, but seems to be broken again on 0.28.28

**Comment by mattlewis92** [comment]
> This is ineed solved for version 0.28.26, but seems to be broken again on 0.28.28

It works for me on the latest angular version, can you give more details please, maybe a minimal reproduction on github? 😄 

```
npm i -g @angular/cli@12
ng new calendar-test-ng12
cd calendar-test-ng12
ng add angular-calendar

ℹ Using package manager: npm
✔ Found compatible package version: angular-calendar@0.28.28.
✔ Package information loaded.
 
The package angular-calendar@0.28.28 will be installed and executed.
Would you like to proceed? Yes
✔ Package successfully installed.
? What date adapter would you like to use? date-fns        [ https://date-fns.org/ ]
? Please enter a path to the NgModule that will use the calendar. It should be relative to the root project directory, for example src/app/app.module.ts (optional, will use the root app module if not spe
cified) 
? Please enter the name of the project that will use the calendar (optional, will use the default project if not specified) 
    Added "angular-calendar" into dependencies
    Added "date-fns" into dependencies
    Installing angular calendar dependencies...
    Add modules imports options...
UPDATE package.json (1143 bytes)
UPDATE src/app/app.module.ts (534 bytes)
UPDATE angular.json (3422 bytes)
✔ Packages installed successfully.
```

**Comment by mknookppw** [comment]
> > This is ineed solved for version 0.28.26, but seems to be broken again on 0.28.28
> 
> It works for me on the latest angular version, can you give more details please, maybe a minimal reproduction on github? 😄
> 
> ```
> npm i -g @angular/cli@12
> ng new calendar-test-ng12
> cd calendar-test-ng12
> ng add angular-calendar
> 
> ℹ Using package manager: npm
> ✔ Found compatible package version: angular-calendar@0.28.28.
> ✔ Package information loaded.
>  
> The package angular-calendar@0.28.28 will be installed and executed.
> Would you like to proceed? Yes
> ✔ Package successfully installed.
> ? What date adapter would you like to use? date-fns        [ https://date-fns.org/ ]
> ? Please enter a path to the NgModule that will use the calendar. It should be relative to the root project directory, for example src/app/app.module.ts (optional, will use the root app module if not spe
> cified) 
> ? Please enter the name of the project that will use the calendar (optional, will use the default project if not specified) 
>     Added "angular-calendar" into dependencies
>     Added "date-fns" into dependencies
>     Installing angular calendar dependencies...
>     Add modules imports options...
> UPDATE package.json (1143 bytes)
> UPDATE src/app/app.module.ts (534 bytes)
> UPDATE angular.json (3422 bytes)
> ✔ Packages installed successfully.
> ```

Currently on "@angular/core": "~12.2.0"
Also updated my global angular cli, local angular cli is on 12.2.4

**Comment by mattlewis92** [comment]
> > > This is ineed solved for version 0.28.26, but seems to be broken again on 0.28.28
> > 
> > 
> > It works for me on the latest angular version, can you give more details please, maybe a minimal reproduction on github? 😄
> > ```
> > npm i -g @angular/cli@12
> > ng new calendar-test-ng12
> > cd calendar-test-ng12
> > ng add angular-calendar
> > 
> > ℹ Using package manager: npm
> > ✔ Found compatible package version: angular-calendar@0.28.28.
> > ✔ Package information loaded.
> >  
> > The package angular-calendar@0.28.28 will be installed and executed.
> > Would you like to proceed? Yes
> > ✔ Package successfully installed.
> > ? What date adapter would you like to use? date-fns        [ https://date-fns.org/ ]
> > ? Please enter a path to the NgModule that will use the calendar. It should be relative to the root project directory, for example src/app/app.module.ts (optional, will use the root app module if not spe
> > cified) 
> > ? Please enter the name of the project that will use the calendar (optional, will use the default project if not specified) 
> >     Added "angular-calendar" into dependencies
> >     Added "date-fns" into dependencies
> >     Installing angular calendar dependencies...
> >     Add modules imports options...
> > UPDATE package.json (1143 bytes)
> > UPDATE src/app/app.module.ts (534 bytes)
> > UPDATE angular.json (3422 bytes)
> > ✔ Packages installed successfully.
> > ```
> 
> Currently on "@angular/core": "~12.2.0" Also updated my global angular cli, local angular cli is on 12.2.4

What error message are you getting?

**Comment by mknookppw** [comment]
> > > > This is ineed solved for version 0.28.26, but seems to be broken again on 0.28.28
> > > 
> > > 
> > > It works for me on the latest angular version, can you give more details please, maybe a minimal reproduction on github? 😄
> > > ```
> > > npm i -g @angular/cli@12
> > > ng new calendar-test-ng12
> > > cd calendar-test-ng12
> > > ng add angular-calendar
> > > 
> > > ℹ Using package manager: npm
> > > ✔ Found compatible package version: angular-calendar@0.28.28.
> > > ✔ Package information loaded.
> > >  
> > > The package angular-calendar@0.28.28 will be installed and executed.
> > > Would you like to proceed? Yes
> > > ✔ Package successfully installed.
> > > ? What date adapter would you like to use? date-fns        [ https://date-fns.org/ ]
> > > ? Please enter a path to the NgModule that will use the calendar. It should be relative to the root project directory, for example src/app/app.module.ts (optional, will use the root app module if not spe
> > > cified) 
> > > ? Please enter the name of the project that will use the calendar (optional, will use the default project if not specified) 
> > >     Added "angular-calendar" into dependencies
> > >     Added "date-fns" into dependencies
> > >     Installing angular calendar dependencies...
> > >     Add modules imports options...
> > > UPDATE package.json (1143 bytes)
> > > UPDATE src/app/app.module.ts (534 bytes)
> > > UPDATE angular.json (3422 bytes)
> > > ✔ Packages installed successfully.
> > > ```
> > 
> > 
> > Currently on "@angular/core": "~12.2.0" Also updated my global angular cli, local angular cli is on 12.2.4
> 
> What error message are you getting?

I was getting
`An unhandled exception occurred: Cannot find module '@angular-devkit/schematics'`

**Comment by mattlewis92** [comment]
> I was getting
An unhandled exception occurred: Cannot find module '@angular-devkit/schematics'

hmm that's odd, it should be installed. What package manager are you using? If you run `npm ls @angular-devkit/schematics` what does it give you?

**Comment by mknookppw** [comment]
I'm using npm
Result:
`C:\Users\ppw-user\Documents\Werk\Biqs\servRent_Start_Files
`-- (empty)`

**Comment by mattlewis92** [comment]
> I'm using npm Result: `C:\Users\ppw-user\Documents\Werk\Biqs\servRent_Start_Files `-- (empty)`

What about `npm ls @angular/cli`?

**Comment by mknookppw** [comment]
Oh i was in the wrong directory wait.
This is for the schematics:
`serv-rent@0.0.0 C:\Users\ppw-user\Documents\Werk\Biqs\servRent_Start_Files\servrent\resources\frontend
+-- @angular/cli@12.2.4
| +-- @angular-devkit/schematics@12.2.4
| `-- @schematics/angular@12.2.4
|   `-- @angular-devkit/schematics@12.2.4  deduped
`-- @schematics/angular@9.1.12
  `-- @angular-devkit/schematics@9.1.12
`

**Comment by mattlewis92** [comment]
> Oh i was in the wrong directory wait. This is for the schematics: `serv-rent@0.0.0 C:\Users\ppw-user\Documents\Werk\Biqs\servRent_Start_Files\servrent\resources\frontend +-- @angular/cli@12.2.4 | +-- @angular-devkit/schematics@12.2.4 | `-- @schematics/angular@12.2.4 | `-- @angular-devkit/schematics@12.2.4 deduped `-- @schematics/angular@9.1.12 `-- @angular-devkit/schematics@9.1.12 `
> 
> I was in the right directory when using ng add

That looks right to me, although you probably want to upgrade your angular schematics to v12 via `npm i -D @schematics/angular@12`. Without a reproduction it's hard to really know what's going on, I would recommend just following the [manual install step](https://github.com/mattlewis92/angular-calendar#manual-setup-ng-add-will-do-this-all-for-you) instead to install the package.
