### ISSUE TITLE
Drag & Drop event loses focus when scrolling with calendar or mouse wheel.

### ISSUE THREAD

**Issue by Julian-B90** [mattlewis92/angular-calendar#1478]
**Describe the bug**

Thanks for your great work, I noticed that the drag event loses focus when I drag it across the border. the same happens when using the mouse wheel. I haven't found an issue regarding this yet. Do you plan to fix this at some point ?

**Screenshots**

https://user-images.githubusercontent.com/4377396/122545422-1b4c7280-d02e-11eb-9490-4f7f90ecefc3.mp4

**Versions**

- `@angular/core`: 11.2.14
- `angular-calendar`: 0.28.24
- Browser name and version: Firefox 89.0

**Comment by Gassa1999** [comment]
Hello, I also have the same problem. Please for support
