### ISSUE TITLE
Css problem (row hover effect) when using bootswatch superhero theme with angular-calendar

### ISSUE THREAD

**Issue by paulvanbladel** [mattlewis92/angular-calendar#148]
Matt,
Excellent library ! Thanks for your great work.

When I replace the regular bootstrap css with following one:
https://bootswatch.com/superhero/bootstrap.css
I get a very strange effect when hovering over the calendar.
You can see it over here in plunker (So, the kitchen sink is the base and the only change is replacing the regular css with the bootswatch css, which should be compatible):

https://plnkr.co/edit/06q0ScIEYcThLqWyUF52?p=preview

This is probably not related to angular-calendar and I don't want to waste your time on this, but I would be very happy in case you would know something related to this top of mind.

Cheers

paul.

**Comment by mattlewis92** [comment]
It's because of this CSS rule: https://github.com/mattlewis92/angular-calendar/blob/master/scss/month-view.scss#L7-L9

You'll need to add a CSS rule in your app to override it with a different color to match your app. Hope that helps!

**Comment by paulvanbladel** [comment]
Cool. Very much appreciated.
