### ISSUE TITLE
Drag and Drop (Month View w/ Custom cell template) not working

### ISSUE THREAD

**Issue by awolfson166** [mattlewis92/angular-calendar#1481]
**Describe the bug**
Hello,

This calendar is amazing. I am running into an issue whereby the drag and drop on the month view using a custom template does not seem to register at all (and not trigger the eventTimesChanged function. I was wondering if anyone else had this issue or could provide any guidance.

As an FYI, this works for me using the week view, but without a custom cell template
Thanks in advance

**Minimal reproduction of the problem with instructions**

**Screenshots**
Video recording:
https://drive.google.com/file/d/1t20Bf43gXH08MsVRmGSEaY04fx0-q-sP/view?usp=sharing

**Versions**

- `@angular/core`: 4.4.7
- `angular-calendar`: 0.22.3
- Browser name and version: Firefox (Latest)

**Comment by billyjov** [comment]
@awolfson166  Your video file is not available. 
Also it may be helpful to provides a repo or stackblitz(https://stackblitz.com/) for reproduction.
