### ISSUE TITLE
Make event cards for month view like in week view

### ISSUE THREAD

**Issue by haingdc** [mattlewis92/angular-calendar#1483]
**Is your feature request related to a problem? Please describe**

**Describe the solution you'd like**
I'm trying to create events in month view showing like this picture. See that week and day views support it. I don't how to apply same thing to month view.

**Describe your use case for implementing this feature**

**Additional context**
<img width="360" alt="image" src="https://user-images.githubusercontent.com/14939139/124583985-e9386e80-de7d-11eb-86a2-20b4fa3e5ac7.png">

Thanks for your good work

**Comment by billyjov** [comment]
@haingdc You can use custom templates to archieve this: https://angular-calendar.com/#/custom-templates

**Comment by haingdc** [comment]
thank so much for your help
