### ISSUE TITLE
Week and Day View is jumping after refocusing

### ISSUE THREAD

**Issue by poettl** [mattlewis92/angular-calendar#1489]
**Describe the bug**

Hello!

After clicking in the week view a event which is no fully visibile and closing the dialog the calendar is jumping up to event top which is not necessary.

Thanks :)

**Minimal reproduction of the problem with instructions**

https://stackblitz.com/edit/zr3x96--run?file=demo/component.ts

**Versions**

- `@angular/core`: 9.1.12
- `angular-calendar`: 0.28.26
- Browser name and version: Brave 1.26.77

**Comment by billyjov** [comment]
@poettl your Stackblitz link is not valid

**Comment by poettl** [comment]
Oh sorry.
You can also see it at the kitchen sink example
https://angular-calendar.com/#/kitchen-sink
