### ISSUE TITLE
Mouse move performace

### ISSUE THREAD

**Issue by ilianiv** [mattlewis92/angular-calendar#149]
### Bug description
Moving mouse over month view triggers very high CPU usage because of handling tons of mousemove events.

### For bugs only, a link to minimally working plunker that reproduces the issue (you can fork a starter from any of the demos)
1. Open chrome task manager.
2. Move mouse from date to date in the demo https://mattlewis92.github.io/angular-calendar/demos/#/kitchen-sink
3. Watch the CPU usage.

**Comment by mattlewis92** [comment]
Thanks for reporting, I think it should be possible to fix this by only registering one mouse move event and sharing + debouncing it via observables.

**Comment by mattlewis92** [comment]
Also relevant, [running the event listeners outside of the zone](https://blog.thoughtram.io/angular/2017/02/21/using-zones-in-angular-for-better-performance.html) should help a lot. To keep things working with universal angular provides a [nice API](https://angular.io/docs/js/latest/api/core/index/Renderer-class.html) for registering the event listeners manually.
