### ISSUE TITLE
Draggable external events with Week and Day Droppable

### ISSUE THREAD

**Issue by PierreDugue** [mattlewis92/angular-calendar#150]
### Bug description / Feature request:
Hello,
I'm unable to drag external events on weeks or days. I saw that you add the feature for AngularJS version, is it planed for Angular 2?

### Versions

Angular: v2.4.7

Calendar library: v0.7.2

Browser name and version: chrome

**Comment by mattlewis92** [comment]
Oh yes looks like I missed that feature off, I'll get it added in the next version! 😄

**Comment by PierreDugue** [comment]
Ok great thx for your answer!
