### ISSUE TITLE
In HourSegment 1 how can allow 15 min interval resizing?

### ISSUE THREAD

**Issue by Sushma-tiwari** [mattlewis92/angular-calendar#1501]
**Is your feature request related to a problem? Please describe**

In Angular calendar the segment is 1 hour now I m not able to resize the event
for 15min or 30 min interval it always resize the event on 1 segment 
please provide the any useful suggestion or document Thank you.
**Describe the solution you'd like**
Here the segment is 1 hour now i m not able to resize the event
for 15min or 30 min interval it always resize the event on 1 segment 
please provide the any useful suggestion or document Thank you.

**Describe your use case for implementing this feature**
When trying to resize the event it should be in 15 min interval resize like if event end time is 2 pm user will able to resize that event 2:15pm but in calendar 1 hour segment must displayed.

**Additional context**

![calenar_segment](https://user-images.githubusercontent.com/66738000/133227281-aa1c91c2-d6d9-4a0b-8be2-684ada6666d2.png)

**Comment by FrankL-git** [comment]
@Sushma-tiwari 
Did you try hourSegments input parameter?

    <mwl-calendar-week-view
    *ngSwitchCase="'week'"
    ... 

    [hourSegments]="4"
    >

**Comment by mattlewis92** [comment]
Hey there, I think the option you're looking for is [`eventSnapSize`](https://mattlewis92.github.io/angular-calendar/docs/components/CalendarWeekViewComponent.html#eventSnapSize), so setting `[eventSnapSize]="15"` should fix your issue. Hope that helps! 😄
