### ISSUE TITLE
Order in event

### ISSUE THREAD

**Issue by agermanique** [mattlewis92/angular-calendar#151]
Hi first of all, thanks for this amazing calendar.

I would like to know if it could be possible to order the dote representing the events with the start date in the calendar. I might missing something out, but it doesn't seem to work on my app and in the demo app.

Thanks !

Angular : 2.4.0

angular-calendar: 0.7.2

chrome: Version 56.0.2924.87

firefox : 51.0.1

### Versions

Angular: 

Calendar library: 

Browser name and version:

**Comment by mattlewis92** [comment]
The calendar makes no assumptions about your events and displays them in the order you give them. So if you sort the events array by start date they'll display in that order. Example plunker: http://plnkr.co/edit/v13Rj8djBP9JLPMCwE2a?p=preview (the trick is to use `events.sort((a, b) => a.start.getTime() - b.start.getTime())`). Hope that helps! 😄

**Comment by agermanique** [comment]
Ok that did the trick, thanks !

**Comment by JWess** [comment]
This does not seem to be the case anymore. I am using `<mwl-calendar-week-view [events]="eventData">`, and no matter what order `eventData` is in, each day-column on the calendar displays the events sorted by time from earliest to latest. I want to specify my own ordering, but I can't seem to.

**Comment by JWess** [comment]
@mattlewis92 Here is where the sorting seems to be happening. Is there any way to stop this from happening? Could configuration of this be a feature request?

[calendar-utils.ts](https://github.com/mattlewis92/calendar-utils/blob/master/src/calendar-utils.ts)


![image](https://user-images.githubusercontent.com/8697891/39075983-bc21611c-44c6-11e8-8386-f206a81c92d4.png)
