### ISSUE TITLE
Error de AOT. Function calls are not supported in decorators but 'CalendarModule' was called.

### ISSUE THREAD

**Issue by Askeiter** [mattlewis92/angular-calendar#1525]
**Describe the bug**

I have integrated angular calendar into my application following the examples in the demo and it works correctly. The problem appears when I try to compile for production with --prod it shows me the following error

I have followed the example of demo moment as the image shows

**ERROR: Error during template compile of 'SfmCalendarModule'   Function calls are not supported in decorators but 'CalendarModule' 
was called.**

**Minimal reproduction of the problem with instructions**

compile for production

**Screenshots**
 
![image](https://user-images.githubusercontent.com/1458540/141647309-b4067828-daeb-4475-8759-0737591f9b66.png)
![image](https://user-images.githubusercontent.com/1458540/141647313-1d76c9d4-cd1e-41bb-91b5-f27eeeb70b95.png)
![image](https://user-images.githubusercontent.com/1458540/141647318-06ea1066-9733-4945-8df5-854e32f20d3f.png)

**Versions**

- `@angular/core`: 10.2.3
- `angular-calendar`:0.28.28
- Browser name and version:Chrome Version 94.0.4606.81 (Official Build) (64-bit)

**Comment by mattlewis92** [comment]
Hey there, if you're still running into problems please could you make a minimal reproduction on github that shows your issue, as without it it's impossible to know what the issue is. Thank you!
