### ISSUE TITLE
Change Icon

### ISSUE THREAD

**Issue by misisriddle** [mattlewis92/angular-calendar#153]
Thank you so much for this awesome calendar! Is there a way for me to change the icon (colored circle) of the event in the calendar's month view?

Many thanks.

### Versions

Angular: 

Calendar library: 

Browser name and version:

**Comment by mattlewis92** [comment]
Depending on your use case you can use CSS to style it, or if you need more finer control of the markup then you'll have to wait until I get round to implementing custom templates: https://github.com/mattlewis92/angular-calendar/issues/16 Hope that helps! 😄

**Comment by misisriddle** [comment]
Thanks @mattlewis92 :)
