### ISSUE TITLE
Separate Month from Year on view

### ISSUE THREAD

**Issue by misisriddle** [mattlewis92/angular-calendar#154]
I want to display the text of current year only in a separate div and if possible, give the user an option to change by year. Is there a way to do this? Also, is there a way to have the calendar's header have separated current Month and Year? Right now it's Month Year

Thank you!

**Comment by mattlewis92** [comment]
Sorry I'm not quite sure I follow you, could you explain a bit more? Maybe with a rough sketch / annotated screenshot of what you mean?

**Comment by misisriddle** [comment]
![image](https://cloud.githubusercontent.com/assets/24520523/23606437/ace30e3a-029b-11e7-8d26-6d356b519665.png)

On the screenshot, I want to move the year on the upper left side. But retain the month on center. Is this possible?

**Comment by mattlewis92** [comment]
The header isn't part of this component so you can do whatever you want to it: http://plnkr.co/edit/o8mk9rg3rPRQNVbDw14k?p=preview

**Comment by misisriddle** [comment]
Thanks! This is exactly what I needed:
{{ viewDate | date:'y' }}

**Comment by XhensildaAllka** [comment]
That helped me too. Thanks! 
I am trying to do a dropdown list for months and increase decrease for years, but till now I haven't done it.
Is it possible to do in angular?
