### ISSUE TITLE
Additional Row or Summary at the end of the row

### ISSUE THREAD

**Issue by jhonmacaraig** [mattlewis92/angular-calendar#1540]
**Is your feature request related to a problem? Please describe**
  Just an inquiry , is it possible to add addtional row on the last row rendered for the weekview and dayview
 more like a footer or summary at the bottom part.
**Describe the solution you'd like**
 ability to add a footer summary
  
**Describe your use case for implementing this feature**
 ability to add a footer summary

**Additional context**
![image](https://user-images.githubusercontent.com/1201350/145165930-c3e03728-2815-4030-b156-ff51bb2827d5.png)

Thank you

**Comment by mattlewis92** [comment]
Hey there, you can add an extra footer element at the bottom of the calendar like so: https://stackblitz.com/edit/angular-jq57fq?file=demo%2Fcomponent.ts

Hope that answers your question 😄
