### ISSUE TITLE
Disable clicking of event dots

### ISSUE THREAD

**Issue by kianliang-iium** [mattlewis92/angular-calendar#156]
Thank you for this great calendar library.
Is there any way to disable clicking of the event dots? I find that tapping on the event dots which changes the colour of the day is distracting the user in my case. I would like to make dayClick as the default action when tapping on the day.
Thanks.

**Comment by mattlewis92** [comment]
Sorry I'm a bit confused, do you mean the highlighting of the day when you hover over the dot?

![screen shot 2017-03-03 at 12 52 36](https://cloud.githubusercontent.com/assets/6425649/23551795/59506d2c-0010-11e7-83ba-afd699e2f098.png)

**Comment by kianliang-iium** [comment]
Yes, that's right. Sorry for the confusion...

**Comment by mattlewis92** [comment]
You can do this via a CSS rule:
```
.cal-cell {
  background-color: white !important;
}
```

Hope that helps!
