### ISSUE TITLE
When [daysInWeek] is set week view always starts at Tuestay!

### ISSUE THREAD

**Issue by sapabg** [mattlewis92/angular-calendar#1563]
**Describe the bug**

I am using the "Responsive Week View" example at https://mattlewis92.github.io/angular-calendar/#/responsive-week-view
Event there the view starts on Tuesday! It ignores weekStartsOn and it is not behaving nicely with excludeDays too!

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/angular-99podh?file=demo/template.html

  [weekStartsOn]="3" and it still starts on Tuesday no matter what I put here!

**Screenshots**

**Versions**

 "angular-calendar": "^0.28.28",

**Comment by brakim** [comment]
The code inside [calendar-week-view.component.ts](https://github.com/mattlewis92/angular-calendar/blob/311464356151c2c053c88538a67233c04547854c/projects/angular-calendar/src/modules/week/calendar-week-view.component.ts) states

```
/**
   * The number of days in a week. Can be used to create a shorter or longer week view.
   * The first day of the week will always be the `viewDate` and `weekStartsOn` if set will be ignored
   */
  @Input() daysInWeek: number;

```

**Comment by sapabg** [comment]
> if you would like a 5 day week to starts on a monday is to self calculate the date for monday and pass as [viewDate] param.

Can you show me an example that has daysInWeek set and the week does not start on Tuesday?

**Comment by brakim** [comment]
> > if you would like a 5 day week to starts on a monday is to self calculate the date for monday and pass as [viewDate] param.
> 
> Can you show me an example that has daysInWeek set and the week does not start on Tuesday?

https://stackblitz.com/edit/angular-ivy-xhadhk?file=src/app/demo/component.ts

**Comment by sapabg** [comment]
> > > if you would like a 5 day week to starts on a monday is to self calculate the date for monday and pass as [viewDate] param.
> > 
> > 
> > Can you show me an example that has daysInWeek set and the week does not start on Tuesday?
> 
> https://stackblitz.com/edit/angular-ivy-xhadhk?file=src/app/demo/component.ts

Thanks! That worked for displaying it correctly. 

Apparently, I have to do something with CalendarPreviousViewDirective and CalendarNextViewDirective because, in my opinion, the behavior is not correct:
1. Week starts at Monday and has 2-day long week (not because it is actually that long but because the display is small)
2. Exclude Sunday (because I need to);
3. When I press Next (CalendarNextViewDirective) it does not go to Wednesday but skips the whole week and goes to Monday again.
4. Same with previous - skips whole week, not the amount of daysInWeek.
Maybe it is by design but I don't like it...

I made it scroll horizontally on smaller screens instead.

Thanks again for the help! I really, really appreciate it!

**Comment by sapabg** [comment]
> > > if you would like a 5 day week to starts on a monday is to self calculate the date for monday and pass as [viewDate] param.
> > 
> > 
> > Can you show me an example that has daysInWeek set and the week does not start on Tuesday?
> 
> https://stackblitz.com/edit/angular-ivy-xhadhk?file=src/app/demo/component.ts

That worked perfectly! Thanks!
