### ISSUE TITLE
Blank white screen

### ISSUE THREAD

**Issue by dananvaro** [mattlewis92/angular-calendar#1567]
**Describe the bug**
Whenever I add the html code I get a blank white screen and it happens to all my pages in my app.

It only happens when I add the html code. I am not sure if it is how my app is setup or what. But it only happen when I add the html code in.

**Minimal reproduction of the problem with instructions**

**Screenshots**

**Versions**

- `@angular/core`: 5.2.7
- `angular-calendar`: 0.24.1
- Browser name and version: chrome:latest

**Comment by AlexanderKlement** [comment]
Do you have some console output? Or some example code? This is quite sparse information

**Comment by dananvaro** [comment]
I fixed it. But do you have a solution to get capital using the international calendar
