### ISSUE TITLE
Header names editable/modifiable or usable with locale

### ISSUE THREAD

**Issue by Wandang** [mattlewis92/angular-calendar#157]
### Bug description / Feature request:
The names/label of the calendarheader seem to be hardcoded into the according directive. 
For example:
```
<button
  mwlCalendarNextView
  [(viewDate)]="viewDate"
  [view]="view">
  Next
</button>
```
in here: src/directives/calendarNextView.directive.ts

I wanted to change the name Next to the language of my clients. Since the directive does not contain this as an Input() this seems to be discouraged for now. (Maybe I am missing something)

Would be nice if this could be used with Locale as well!

### Versions
Calendar library: 
0.7.2

**Comment by mattlewis92** [comment]
`mwlCalendarNextView` is a directive not a component which means it has no template. You'd just translate it the same way as any other button, e.g. if you took the calendar stuff away you'd just have `<button>Next</button>` which you could then translate via angulars built in i18n support / ng2-translate etc. Hope that helps!
