### ISSUE TITLE
All Day events in RTL

### ISSUE THREAD

**Issue by Alirz** [mattlewis92/angular-calendar#1583]
**Describe the bug**

Hi
Thanks for your very beautiful component,
I upgrade to latest version(0.29.0) to have RTL feature for my holidays events
unfortunately in RTL form you set negative margin right and that's doesn't work for our web application my entire body is RTL and I don't know why those event with negative margin don't shown in Calendars box and they fall out of my screen
I saw your example and that's work properly can you help me to fix it also you can change the calculation in week view template to set it positive.

**Screenshots**

![pic](https://user-images.githubusercontent.com/6630086/172008570-13afaa7c-feae-439e-80cd-39396ecc17b6.png)
![pic1](https://user-images.githubusercontent.com/6630086/172008572-e00f7e07-88d0-4add-a795-3c7800311da4.png)

**Versions**

12.1.4- `@angular/core`:
0.29.0- `angular-calendar`:

**Comment by mattlewis92** [comment]
Hey there! I just ran into this myself and pushed a fix in `0.30.0`. Please can you give it a go and let me know if it works for you? Thanks! 🙌

**Comment by Alirz** [comment]
Thank you,
it worked properly but I had to update my angular to 14.
