### ISSUE TITLE
i18n / translations

### ISSUE THREAD

**Issue by IterationCorp** [mattlewis92/angular-calendar#159]
Hello,

Thanks for this nice work. 

I have just a "question / Feature request" -> is there a was to have the calendar in several languages? 
If not, can we helps?

Thanks

**Comment by mattlewis92** [comment]
There is baked in support for i18n, you can see an example of it here: https://mattlewis92.github.io/angular-calendar/demos/#/i18n

Hope that helps! 😀

**Comment by IterationCorp** [comment]
Yeah sorry for my non-consistent message, I was checking only the navigation pane (Previous / Today / next) and (Month / week / day), it that something that should be overwritten ? Cause in French those are not translated...

**Comment by mattlewis92** [comment]
They're not actually part of the calendar, you can just translate them however you translate the rest of your app.

**Comment by IterationCorp** [comment]
ok thanks

**Comment by agustin18** [comment]
Sorry for re-open but how can i translate to spanish and change format to Mon-Sun. Instead Sun-Sat
