### ISSUE TITLE
Provide a way of overriding each components templates

### ISSUE THREAD

**Issue by mattlewis92** [mattlewis92/angular-calendar#16]
Plan of action:
- [x] move calendarDayViewEventComponent business logic up into the parent day view component. All child components will now be "dumb" and easier to pass a custom template in
- [x] refactor month view header into its own component
- [x] refactor week view header into its own component
- [x] make all dumb child components accept a custom template [like this](https://github.com/mattlewis92/angular-confirmation-popover/blob/master/src/confirmationPopoverWindow.component.ts#L17-L53)
- [x] expose all child components from the module entry point - this will let users use component inheritance to extend any of the components

Additional demos to add:
- [x] custom templates
- [x] group month view events

**Comment by enyachoke** [comment]
Hi thanks for porting this to angular 2 we were using it in angular on and we are now upgrading. We could like to add labels to the event dots. Like include counts or some custom text. Is this possible yet.

**Comment by mattlewis92** [comment]
You can [customise the tooltips](https://mattlewis92.github.io/angular-calendar/demos/#/disable-tooltips) but not the actual templates yet.

**Comment by enyachoke** [comment]
@mattlewis92 thanks. It is not really a showstopper but it would be nice to have.

**Comment by mattlewis92** [comment]
I aim on getting it done in the next month or so 😄

**Comment by enyachoke** [comment]
@mattlewis92  I believe for us to have this feature angular 4.x.x will be a hard dependency or do you plan on getting away to support 2.x.x

**Comment by mattlewis92** [comment]
Yeah I realised we'd have to wait for angular 4 to drop (in 2 weeks time). However the upgrade should be seamless for most users so I don't consider it a big deal.

**Comment by mattlewis92** [comment]
Custom templates are now available as of 0.9.0! 🎉  You can either extend the main components to override the entire template or for most use cases just a specific part of the component with the `<template>` tag. There is a demo of how to do that [here](https://mattlewis92.github.io/angular-calendar/#/custom-templates) for the month cell, for all places you can pass a template in see the [commits on the changelog](https://github.com/mattlewis92/angular-calendar/blob/master/CHANGELOG.md#090-2017-03-21). Please feedback to me if this meets enough use cases 😄

**Comment by DerZyklop** [comment]
This is awesome! Thank you! 

[Here](https://github.com/mattlewis92/angular-calendar/issues/16#issuecomment-286356390) you said, that you need to wait for angular 4 to make this possible. But your component looks like its built on 2.3.x. I‘m confused. What is the correct dependency to use custom templates?

**Comment by mattlewis92** [comment]
In the end I landed on a solution that uses v2, so you should be able to use it seamlessly 😀
