### ISSUE TITLE
Can't import angular-calendar SASS files in an Angular project v15

### ISSUE THREAD

**Issue by LoganDupont** [mattlewis92/angular-calendar#1627]
**Describe the bug**

Can't import library SASS files in an Angular project. Getting the following error:
```
./apps/home/src/css/main.scss - Error: Module build failed (from ./node_modules/css-loader/dist/cjs.js):
Error: Package path ./css/angular-calendar.css is not exported from package <Path>\node_modules\angular-calendar (see exports field in <Path>\node_modules\angular-calendar\package.json)

./apps/home/src/css/main.scss?ngGlobalStyle - Error: Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
HookWebpackError: Module build failed (from ./node_modules/css-loader/dist/cjs.js):
Error: Package path ./css/angular-calendar.css is not exported from package <Path>\node_modules\angular-calendar (see exports field in <Path>\node_modules\angular-calendar\package.json)
```

https://github.com/angular/angular-cli/blob/main/CHANGELOG.md#angular-devkitbuild-angular-4
In @angular/cli v15.0.0 Deprecated support for tilde import has been removed. Please update the imports by removing the ~

What should we use now?

**Minimal reproduction of the problem with instructions**

Create an empty Angular project that imports the SASS file in the app styles.scss by using:

@import 'angular-calendar/css/angular-calendar.css'

**Versions**

- `@angular/core`: ^15.0.2
- `@angular/cli`: ~15.0.0
- `angular-calendar`: ^0.30.1

**Comment by mattlewis92** [comment]
Hi there! 

I tried to reproduce your issue but was unable to following your instructions:
https://github.com/mattlewis92/angular-15-angular-calendar/blob/main/src/styles.scss

Please can you make a minimal repro on github that shows your problem, thanks!

**Comment by LoganDupont** [comment]
I just had a better look at it seems that I did `@import 'angular-calendar/css/angular-calendar.css`' instead of `@import 'angular-calendar/scss/angular-calendar'`.

**Comment by mattlewis92** [comment]
OK great, will close this out then!
