### ISSUE TITLE
Week view only navigate between month weeks

### ISSUE THREAD

**Issue by fredowashere** [mattlewis92/angular-calendar#1652]
**Is your feature request related to a problem? Please describe**

We have a validate week logic in our app and it would be nice to just see the week of the month the user is going to validate even if it is just one day week.

As it is now:
![image](https://user-images.githubusercontent.com/117639221/224302272-c3308f3a-fd7b-4e0a-b9d2-c53683ddb2f2.png)

**Describe the solution you'd like**

I would like to only see the days of the current month as first week of the month, and going to the previous month last week with the back button.

As I would like:
![image](https://user-images.githubusercontent.com/117639221/224302316-ca78a442-ddef-4341-bf55-843dccd6d151.png)

And when navigating back to see:
![image](https://user-images.githubusercontent.com/117639221/224303617-daf9eff5-cc56-4537-baa4-56acfed85641.png)

**Describe your use case for implementing this feature**

It will be used to provide consistency between what the user sees and the validate week logic of our app.

**Additional context**

(Your bot is closing a ton of legit issues)

**Comment by billyjov** [comment]
@fredowashere You can use the logic of `exludeDays` to archieve this, when user navigate to a month

https://mattlewis-github.com/angular-calendar/#/exclude-days
