### ISSUE TITLE
Error: Can't bind to 'cellTemplate' since it isn't a known property of 'mwl-calendar-week-view'.

### ISSUE THREAD

**Issue by DerZyklop** [mattlewis92/angular-calendar#166]
mwl-calendar-week-view doe’s not accept cellTemplate.

Not sure if this feature is missing (bug) or was never planned (new feature).

**Comment by mattlewis92** [comment]
`cellTemplate` is only for the month view component. The only template you can pass to the week view is the [customise the header](https://github.com/mattlewis92/angular-calendar/blob/master/src/components/week/calendarWeekView.component.ts#L122). For anything else I'd recommend just extending the `CalendarWeekViewComponent` that's exposed from the module and overriding the template there e.g. 
```
@Component({
  selector: 'my-week-view',
  template: 'My custom template, copy / adapt from the parent component'
})
class MyWeekViewComponent extends CalendarWeekViewComponent {}
```

Hope that helps!
