### ISSUE TITLE
Search in Documentation

### ISSUE THREAD

**Issue by DerZyklop** [mattlewis92/angular-calendar#167]
The links of search-results at the [angular-calendar documentation](https://mattlewis92.github.io/angular-calendar/docs/) is broken. 

Example: 

Results always link to 

[domain]/components/Something.html

correct would be

[domain]**/angular-calendar/docs**/components/Something.html

**Comment by mattlewis92** [comment]
Thanks for reporting, I've opened an issue over at compodoc to track the issue: https://github.com/compodoc/compodoc/issues/132
