### ISSUE TITLE
Can't access the documentation

### ISSUE THREAD

**Issue by psedwards99** [mattlewis92/angular-calendar#1675]
**Describe the bug**

Could you fix the links to the documentation please. There's some sort of security issue with the site/pages (SSL certs? Protocol version ?) Anyhow, it's currently not possible to access the documentation using Chrome or Safari.

Thanks!

**Minimal reproduction of the problem with instructions**

Click on the link to the documentation

**Screenshots**

**Versions**

- `@angular/core`: any
- `angular-calendar`: any
Safari 16.5.1, Chrome 114

**Comment by EgoPlacebo** [comment]
are you still having trouble with this? I am able to access the docs ok here: https://mattlewis92.github.io/angular-calendar/docs/ using chrome

**Comment by psedwards99** [comment]
Hi there,Unfortunately, yes. Unable to access using Safari or Chrome from my Mac, iPhone or iPadSent from my iPhoneOn 3 Jul 2023, at 04:05, Ego Placebo ***@***.***> wrote:﻿
are you still having trouble with this? I am able to access the docs ok here: https://mattlewis92.github.io/angular-calendar/docs/ using chrome

**Comment by lisandrogreco** [comment]
I have the same issue can't access the documentation or the demo

**Comment by aXaleiiin** [comment]
Same issue here. With Brave, removing the "s" so it's http only and then going back at least opens the docs and demo page - kitchen sink. But the other pages within the demo or docs can't be opened.

**Comment by Galileon-venta** [comment]
If you check e.g. https://global.sitesafety.trendmicro.com/result.php the URL is flagged for phishing and might be blocked by some filter list in your environments...

**Comment by mattlewis92** [comment]
> If you check e.g. [global.sitesafety.trendmicro.com/result.php](https://global.sitesafety.trendmicro.com/result.php) the URL is flagged for phishing and might be blocked by some filter list in your environments...
> 
> Maybe @mattlewis92 wants to clear this up?

Thank you for letting me know! I have no idea why but anything hosted on https://mattlewis92.github.io/ has been flagged as phishing 😭 I've used that trendmicro link to request that it's re-evaluated and hopefully that fixes it 🙏 They said it can take 48 hours for a response

**Comment by mattlewis92** [comment]
I received a response today that the classification has changed but I don't know how long it will take to propagate:
<img width="966" alt="CleanShot 2023-08-17 at 09 14 42@2x" src="https://github.com/mattlewis92/angular-calendar/assets/6425649/c029634c-c16b-45c5-ba98-ad738b64cff8">

**Comment by mattlewis92** [comment]
I have no idea how long it will take for the site to be unblocked by various ISPs (my own ISP is blocking it as well), so in the meantime I've setup a custom domain to host the [demos](https://mattlewis-github.com/angular-calendar/) + [docs](https://mattlewis-github.com/angular-calendar/docs/).

Thanks for letting me know!
