### ISSUE TITLE
Can't refresh the calendar with async

### ISSUE THREAD

**Issue by Swyn** [mattlewis92/angular-calendar#169]
Hi, 

I've been trying to get this fixed by myself but I can't figure out why it's not working...

Here is my plunker :
https://plnkr.co/edit/4am3IFjBlfAStfQAMGTq?p=catalogue

I get my datas from a request.
When the page load I can't get the events to be displayed inside the calendar but they do get display correctly inside the edit event section.... (title / date / colors are ok). 

Sorry the component code isn't very clean I tried several things.

**Comment by mattlewis92** [comment]
Hello, it looks like you're missing some files in your plunker?

**Comment by mattlewis92** [comment]
Gave it some more thought, based on the files you provided, I think if you use the async pipe for passing your events to the calendar it should solve the issue (when you call refresh angular's change detection hasn't yet picked up that the events array has changed so it still thinks events is undefined). There is a demo of how to use it here: https://mattlewis92.github.io/angular-calendar/#/async-events Hope that helps!

**Comment by WouterVanherck** [comment]
Heya! I've been boxing against the same issue. My calendar doesn't refresh after filling the events array via an async way. Have tried the above and the easy workarounds of Issue #82 and #103.

**TS-File**:
```
export class CalendarComponent implements OnInit {
  ...
  refresh: Subject<any> = new Subject();
  allEvents: SpikesEvent[] = [];
  events: SpikesEvent[];

  ngOnInit() {
    this.loadEvents();
    ...
    this.events = this.allEvents;
    this.refresh.next();
  }

  loadEvents(): void {
    this._feedService.getAllFeeds().subscribe(
      (allFeeds: Feed[]) => {
        for (let news in allFeeds) {
          this.allEvents.push({
            start: startOfDay(allFeeds[news].created),
            title: allFeeds[news].description,
            color: colors.yellowsunflower,
            type: "newsItem",
            id: (allFeeds[news].id).toString(),
          });
        }
      });
  }
}
```

HTML-File is almost the same as the kitchen-sink <br>(I removed the above events$ way because it was not updating)

**Comment by mattlewis92** [comment]
`this.allEvents.push` doesn't create a new array and angular doesn't deep watch arrays for changes so it never knows anything has changed. After
```
for (let news in allFeeds) {
          this.allEvents.push({
            start: startOfDay(allFeeds[news].created),
            title: allFeeds[news].description,
            color: colors.yellowsunflower,
            type: "newsItem",
            id: (allFeeds[news].id).toString(),
          });
        }
```

You need to call `this.refresh.next();` or create a new array before adding the event like so:
```
this.allEvents = [];
for (let news in allFeeds) {
          this.allEvents.push({
            start: startOfDay(allFeeds[news].created),
            title: allFeeds[news].description,
            color: colors.yellowsunflower,
            type: "newsItem",
            id: (allFeeds[news].id).toString(),
          });
        }
```

**Comment by WouterVanherck** [comment]
I've tried them both without results. I understand that` this.allEvents` isn't a "new" array but I'm copying that array to `this.events` in `ngOnInit`. I think this way, the events array could be seen as "new" by Angular and it should update?

**Comment by mattlewis92** [comment]
It will only be seen as new when the component is initialised. loadEvents is async so will be called after you assign the variable so angular never knows the value has changed. This should work:

```
export class CalendarComponent implements OnInit {
  ...
  refresh: Subject<any> = new Subject();
  allEvents: SpikesEvent[] = [];
  events: SpikesEvent[];

  ngOnInit() {
    this.events = [];
    this.loadEvents();
  }

  loadEvents(): void {
    this._feedService.getAllFeeds().subscribe(
      (allFeeds: Feed[]) => {
        this.events = [];
        for (let news in allFeeds) {
          this.events.push({
            start: startOfDay(allFeeds[news].created),
            title: allFeeds[news].description,
            color: colors.yellowsunflower,
            type: "newsItem",
            id: (allFeeds[news].id).toString(),
          });
        }
      });
  }
}
```

**Comment by WouterVanherck** [comment]
I'm using the array `allEvents` because I have multiple methods that load events and I don't want them to override each other. However, if I was only using one method, this wouldn't work for me 'cause my log showed that `this.events` was null after trying this out.

**Comment by mattlewis92** [comment]
Glad you got it sorted 😄

**Comment by adamhrosenberg** [comment]
this.refresh.next() worked for me. thank you.

**Comment by chanaka725** [comment]
this.refresh.next() is not working in angular 5 what should i do?

**Comment by belkashehaj** [comment]
this.refresh.next() worked for me :)

**Comment by TaimoorRana** [comment]
My problem was the start and end time as well. I Fixed those and events now shows on the calendar

**Comment by dev7asp** [comment]
Hi @mattlewis92,
Hope you are doing well. I am using the calendar to display appointments  in "day view scheduler", getting records from server end and binding event to calendar but I am facing a issue to load data in view when page loads or when I insert new event and it is showing if i do next or previous but not first time when data load. I have tried to figure out it with the help of this.refresh.next() or by calling change detector when data loads and add to calendar events but no luck.
Please suggest me any event or the way so that I can able to see my data in calendar view on page loads or whenever new data added.
Thanks

**Comment by RogerBrad** [comment]
this.refresh.next() worked for me too.  Thank you !!!

**Comment by abbasogaji** [comment]
this.refresh.next() doesnt work are me after making an api on my async events

**Comment by AliciaD2018** [comment]
> 

same
