### ISSUE TITLE
Feature Request: Add a class for selected day in Month View

### ISSUE THREAD

**Issue by thielCole** [mattlewis92/angular-calendar#170]
### Feature request:

When you are playing with month view, the selected day has no special class that would allow the calendar to highlight the day selected. This is particularly useful when extending the calendar to be a date picker or for contextual information on a mobile device.

Either adding a class when selected, or outputting the target on the (dayClicked) output event so that someone could programmatically add the class on click.

**Comment by mattlewis92** [comment]
You can actually do this already, there's a demo of how to do it here: https://mattlewis92.github.io/angular-calendar/#/selectable-month-day

p.s. I saw your blog post on this calendar, I thought that was really cool, thank you! 😄

**Comment by thielCole** [comment]
Np, I guess I can then delete my pull request. I didn't see it automatically in the documentation as an output, but that's just because of the automation. Maybe I'll make a pull request for just the documentation update? 

Thanks! I'm very happy with this calendar! Currently extending it as a material design esq date-picker in ionic. If I get some great feedback I might even make a component for that specifically.

<img width="324" alt="screen shot 2017-03-27 at 10 15 27 am" src="https://cloud.githubusercontent.com/assets/7246257/24371448/a726408a-12df-11e7-8012-a6a45c4bc5da.png">

**Comment by mattlewis92** [comment]
Ah yeah it looks like I only documented it in the [`dayModifier`](https://github.com/mattlewis92/angular-calendar/blob/master/src/components/month/calendarMonthView.component.ts#L110) option, but not in the [`dayClicked`](https://github.com/mattlewis92/angular-calendar/blob/master/src/components/month/calendarMonthView.component.ts#L150) output. A PR would be great!

Interesting to see this being used as a datepicker, I never thought of that!
