### ISSUE TITLE
Custom template for a week view event

### ISSUE THREAD

**Issue by ilianiv** [mattlewis92/angular-calendar#171]
### Feature request:
It will be very useful if there is a way to customize template for events in week view. At this point only background colour can be modified and the event title is the only information can be displayed. I have an additional data for an event like type, user, priority etc. that I want to visualize.

![image](https://cloud.githubusercontent.com/assets/3925630/24444578/83194296-146f-11e7-9c22-2c5b709daca2.png)

### Versions

Angular: 2.4.10

Calendar library: 0.9.0

Browser name and version: Chrome 57

**Comment by ilianiv** [comment]
:sparkles: Thanks for the fastest issue closing commit ever

**Comment by mattlewis92** [comment]
No probs, it was a 5 minute job 😄 Just running the release script now, should be up at 0.11.0 in a few minutes

**Comment by senthilm-optisol** [comment]
how can i show week view like this(https://fullcalendar.io/) calendar week view.
