### ISSUE TITLE
Issue Drag to create event

### ISSUE THREAD

**Issue by c3d28** [mattlewis92/angular-calendar#1721]
**Describe the bug**

Hello
I copy the code from this page : https://mattlewis-github.com/angular-calendar/#/drag-to-create-events

but when i want to launch the server i have this issue :

```
Error: src/app/residence/residence-calendar/residence-calendar.component.ts:124:18 - error TS2769: No overload matches this call.
  Overload 1 of 5, '(observer?: PartialObserver<Event> | undefined): Subscription', gave the following error.
    Argument of type '(mouseMoveEvent: MouseEvent) => void' is not assignable to parameter of type 'PartialObserver<Event> | undefined'.
  Overload 2 of 5, '(next?: ((value: Event) => void) | undefined, error?: ((error: any) => void) | undefined, complete?: (() => void) | undefined): Subscription', gave the following error.
This error is from the mouseEvent in the subscribe part:
```
This error is from the mouseEvent in the subscribe part:

```
.subscribe((mouseMoveEvent: MouseEvent) => {
        const minutesDiff = ceilToNearest(
          mouseMoveEvent.clientY - segmentPosition.top,
          30
        );
```
Can you help me please ? I cant use Event instead of MouseEvent because clientY doesnt exist for Event.

Thank for your help.
**Screenshots**

**Versions**

- `@angular/core`:    "~15.2.10",
    "angular-calendar": "^0.31.1",
- Browser name and version: Chrome

**Comment by mattlewis92** [comment]
Hey, I think if you do `fromEvent<MouseEvent>(document, 'mousemove')` it should cast to the correct type

**Comment by c3d28** [comment]
Hi , perfect thank you , 

its working 

but i have an other issue after : 
./node_modules/angular-calendar/css/angular-calendar.css - Error: Module build failed (from ./node_modules/@angular-devkit/build-angular/node_modules/postcss-loader/dist/cjs.js):
TypeError: Cannot read properties of undefined (reading '500')
