### ISSUE TITLE
Is comptible with Angular 2?

### ISSUE THREAD

**Issue by aebmknrl** [mattlewis92/angular-calendar#175]
### Bug description / Feature request:
I have this error:

```
node_modules/angular-calendar/dist/esm/src/providers/calendarMomentDateFormatter.provider.d.ts(1,10): error TS2305: Module '"C:/No
deJS/project-oak/cayena-front-end/node_modules/@angular/core/index"' has no exported member 'InjectionToken'.
node_modules/angular-resizable-element/dist/esm/src/resizable.directive.d.ts(1,10): error TS2305: Module '"C:/NodeJS/project-oak/c
ayena-front-end/node_modules/@angular/core/index"' has no exported member 'Renderer2'.
node_modules/angular-resizable-element/dist/esm/src/resizeHandle.directive.d.ts(1,10): error TS2305: Module '"C:/NodeJS/project-oa
k/cayena-front-end/node_modules/@angular/core/index"' has no exported member 'Renderer2'.
```
This i when i start my program with: npm start

![image](https://cloud.githubusercontent.com/assets/5152002/24754156/49c2b484-1aa3-11e7-8d6c-3c5db8da04b6.png)

Is this comptible with AG2?

### Versions

Angular: 2.2.2

Calendar library: 0.12.0

Browser name and version: 
Chrome 57

**Comment by mattlewis92** [comment]
The last version that's compatible with angular 2 is 0.9.1, the latest version requires angular 4.0.0 or above. Upgrading angular from 2 to 4 should only be a 5 minute job though 😀

**Comment by aebmknrl** [comment]
Thanks my friend. I already update Angular and every its ok. Wherever, **i recommend to put this on your documentation or FAQ**.
Best Regards,

**Comment by mattlewis92** [comment]
It's already on the first line of the readme and you should get a peer dependency warning when you install it via npm 😀
