### ISSUE TITLE
Question: Is posible to add custom data to a event?

### ISSUE THREAD

**Issue by aebmknrl** [mattlewis92/angular-calendar#176]
### Bug description / Feature request:
Is posible to ad custom data to a event? I need to override or add more data to manage my custom characteristics on events... Is possible?

### Versions

Angular: 4

Calendar library: 0.12.0 

Browser name and version: Chrome 57

**Comment by mattlewis92** [comment]
Yup, you need to extend the interface, demo here: https://mattlewis92.github.io/angular-calendar/#/additional-event-properties

**Comment by aebmknrl** [comment]
Thanks for your answer, excuse my ignorance but i don't see how to do this... What steps i nee to follow? Where can start? Thanks

**Comment by aebmknrl** [comment]
My bad. Forget. On the plunker is the lines:

```
interface MyEvent extends CalendarEvent {
  id: number;
}
```
Sorry and thanks for the help.

**Comment by mattlewis92** [comment]
In the component.ts tab you'll see how to extend the interface

**Comment by aebmknrl** [comment]
Yes... I had not seen it. Thanks a lot.
