### ISSUE TITLE
On the demo Kitchen sink the date is not set properly

### ISSUE THREAD

**Issue by aebmknrl** [mattlewis92/angular-calendar#177]
### Bug description / Feature request:
On the demo Kitchen sink if i set a date adding a new event, is added for another month that i selected.
Please do this steps:

1) Click on "Add new" button
2) Try to set the start date "2017-04-11" --> The calendar sets the date and adds a month (by +1)
3) If you keep open the start date datepicker and select a day always picks a wrong month.

### For bugs only, a link to minimally working plunker that reproduces the issue (you can fork a starter from any of the demos)

https://mattlewis92.github.io/angular-calendar/#/kitchen-sink

### Versions

Angular: 4.0+

Calendar library: the last one i supposed 

Browser name and version: My browser is Chrome 57.

**Comment by mattlewis92** [comment]
Thanks, fixed!
