### ISSUE TITLE
can i have context menu on an event

### ISSUE THREAD

**Issue by KaranSaldhana** [mattlewis92/angular-calendar#178]
![rightclick](https://cloud.githubusercontent.com/assets/27000453/24791934/aa38228a-1b99-11e7-8963-40c3729e503e.jpg)

**Comment by etwillbefine** [comment]
I'm pretty sure this duplicates https://github.com/mattlewis92/angular-calendar/issues/172#issuecomment-291795671

**Comment by mattlewis92** [comment]
That issue was about adding a context menu on each row of the table, it's currently not possible to provide a template to day view events, it's kind of tricky to implement but I'll have a go 😄

**Comment by KaranSaldhana** [comment]
Thanks @mattlewis92  :)

**Comment by mattlewis92** [comment]
Found a way to do it and released it as 0.13.0. It should work pretty much the same as the [context-menu demo](https://mattlewis92.github.io/angular-calendar/#/context-menu) but you'll just need to provide a custom template for the `eventTemplate` input instead 😄

**Comment by KaranSaldhana** [comment]
Hello @mattlewis92 

I have cloned a new repo and followed these steps

git clone https://github.com/mattlewis92/angular-calendar.git
git checkout be4d5eee6c6ba500be90ae603d0834233fc6a50b
git checkout -b calendar
npm start
then i m getting this error 
![console-error](https://cloud.githubusercontent.com/assets/27000453/24847148/c668e63e-1ddc-11e7-8314-84d5b43e4706.jpg)

**Comment by mattlewis92** [comment]
Oh it's because the path separators are different from unix systems, fixed here: https://github.com/mattlewis92/angular-calendar/commit/c44c626c2c1f25889674ef359b6ea4dabfb99ef1

**Comment by KaranSaldhana** [comment]
Hello @mattlewis92 ,

As per the screenshot shared in the previous post i.e. 
![aa38228a-1b99-11e7-8963-40c3729e503e](https://cloud.githubusercontent.com/assets/27000453/24855637/de258552-1dff-11e7-81db-50a8385318ba.jpg)

For e.g. When i perform a right click on a blank row I get context menu "Add event", and on click of that "New Event" is created.

Now when I right click on "New Event" once again I need context menu. As shown in image.

Thanks alot for help once again :)

**Comment by mattlewis92** [comment]
You need to provide a custom template for the events as well and then add the context menu to it, [like this](http://plnkr.co/edit/jKg0iw2hSTlSqtKOuRNA?p=preview)

**Comment by KaranSaldhana** [comment]
Thanks alot :) Cheers

**Comment by Sushma-tiwari** [comment]
I need a context menu on the right-click of the **event**, not on the **hour segment**.
![image](https://user-images.githubusercontent.com/66738000/97442158-889c7d80-194f-11eb-9472-43032444a05c.png)
