### ISSUE TITLE
Day view - Not clickable link in title if you have more event in same time or similir time

### ISSUE THREAD

**Issue by petrbalat** [mattlewis92/angular-calendar#179]
### Bug description
Not clickable link in day view in title if you have more event in same time or similir time. 
Example is demo version see https://mattlewis92.github.io/angular-calendar/#/kitchen-sink
It can not be clickable in day view on first event (3 day event).

### Versions
0.13.2

**Comment by mattlewis92** [comment]
Thanks, fixed in 0.13.3! 🎉
