### ISSUE TITLE
[Day view] responsive event width on multiple parallel events

### ISSUE THREAD

**Issue by Giuseppe01** [mattlewis92/angular-calendar#181]
### Feature request for day view

When there are multiple events at the same time the box events no resize with the container and no all events are viewed. The eventWidth param set the width for all event, it's not possible set the different width for each event. For example on mobile is not possible show more then 2 events with the same time.
If I use a customTemplate I can't obtain the aspected result.

Thanks

**Comment by mattlewis92** [comment]
This library isn't really designed to be responsive or work on mobile devices, for a component as complex as a calendar I think it's better to use a dedicated calendar with a completely different UX on smaller devices. The day view currently scrolls horizontally if there are too many events on one row which is about the best I can really offer I'm afraid.

**Comment by renilbabu03** [comment]
@mattlewis92  : I need this feature in my project... Do you  have that buggy code so that I can implement it .
