### ISSUE TITLE
Drag event issue on mouse scroll

### ISSUE THREAD

**Issue by rajkotgire** [mattlewis92/angular-calendar#184]
### Versions

Angular: 1.5.5

Calendar library: 

Browser name and version: 

Hi,
My calendar day view time is divided for 15 min slots and because of that in 24 hours my day view looks very long so i tried giving custom height say 250px now up to this everything is fine, but now I want to move event from top to bottom so I have to scroll to go to bottom time and drop my event there, while scrolling pointer and event seems to lost somewhere. Please find attach plunker for more detail.

To reporduce this issue. 
http://plnkr.co/edit/aThLNdZjvV2rSRkITC53?p=preview
go to Day view and start dragging the event and try to drop @ 10.00 PM  you would get to know my problem.
Thank you.

**Comment by mattlewis92** [comment]
This repo is for the angular 4 version of the calendar, I've moved the issue across to https://github.com/mattlewis92/angular-bootstrap-calendar/issues/578

**Comment by itafraji** [comment]
I have the same issue with Angular 5. Is there any solution for that. I can not find the new issue raised from the link.
