### ISSUE TITLE
Plunker Clickable days demo broken

### ISSUE THREAD

**Issue by svict4** [mattlewis92/angular-calendar#186]
### Bug description / Feature request:
Hi Matt, the ['Clickable days'](https://mattlewis92.github.io/angular-calendar/#/clickable-days) plunker demo is broke. It's missing the component `./demo/component`. Not that this is a big issue because there is the `Selectable month day` demo to work from!

**Comment by mattlewis92** [comment]
Thanks, fixed 😄
