### ISSUE TITLE
CalendarDatePipe

### ISSUE THREAD

**Issue by ThomasKientz** [mattlewis92/angular-calendar#187]
Hi, 

I'm unable to use the pipe like in the demo: 

`<h3>{{ viewDate | calendarDate:(view + 'ViewTitle'):'en' }}</h3>`

I got the error :

> `this.dateFormatter[method] is not a function`

Did I need to import something else than "CalendarModule" in my NgModule like a provider ?

Thanks for the calendar, it ROCKS.

**Comment by mattlewis92** [comment]
The date pipe is basically a pass through to [this class](https://github.com/mattlewis92/angular-calendar/blob/master/src/providers/calendarNativeDateFormatter.provider.ts). I'm guessing the value of `view` is either undefined or not equal to `month` | `week` | `day`. Doing something like `<h3 *ngIf="view">{{ viewDate | calendarDate:(view + 'ViewTitle'):'en' }}</h3>` should work. Hope that helps!

**Comment by ThomasKientz** [comment]
Yes it was undefined, feelling stupid it was obvious... 

Thanks a lot :)
