### ISSUE TITLE
Bug when resize event with eventSnapSize

### ISSUE THREAD

**Issue by al37350** [mattlewis92/angular-calendar#188]
### Bug description:
When we change the default eventSnapSize in order to be more precise, resizing event modifications are amplified.

http://plnkr.co/edit/mtAi9urPRKTDzQstUJc9?p=preview

### Versions

Angular: v4

Calendar library: 13.5

Browser name and version: Chrome/firefox

**Comment by mattlewis92** [comment]
Nice find, I will get that fixed up in the next version 😄

**Comment by mattlewis92** [comment]
Fixed in 0.13.6 🎉  Thanks for reporting!
