### ISSUE TITLE
Feature Request- Disable Event Toolbar in Month View and better mobile support

### ISSUE THREAD

**Issue by maitham1** [mattlewis92/angular-calendar#189]
Feature request:

Ability to disable the events toolbar in Month View:
<img width="431" alt="screen shot 2017-04-19 at 00 14 08" src="https://cloud.githubusercontent.com/assets/15156137/25156874/62a4606e-2495-11e7-9d9c-e4eb8735398c.png">

Also i'm using this within an ionic project on mobile. I'm having to almost double click on the calendar to get it to change views from month view to day view.I've followed the example you've provided but it still seems a bit sticky when changing views on mobile. In browser its perfect just not on mobile.

Is there a possibility to change each day rendered in the month view to a button?

**Comment by svict4** [comment]
Which example are you using exactly?
The toolbar is activated by [`activeDayIsOpen = true;`](https://mattlewis92.github.io/angular-calendar/docs/components/CalendarMonthViewComponent.html)
So if you look at the kitchensink demo in the `dayClicked` function on `component.ts`, you can see that the toolbar closes when there are no events: `events.length === 0` or opens if there are events.

**Comment by mattlewis92** [comment]
What @svict4 said is correct, if you never define the `activeDayIsOpen` input the slidebox will never open. As for removing the click delay you can just use [fastclick for this](https://www.joshmorony.com/how-to-remove-the-300ms-tap-delay-in-html5-mobile-apps/).

**Comment by maitham1** [comment]
I cant use fast click with ionic 2, as it overrides their implementation of fast click! Is there another method ?

**Comment by mattlewis92** [comment]
When you initialise fastclick you pass it a dom element, instead of the document.body you should be able to pass the parent element that contains the calendar components so fastclick will only be scoped to the calendar.
