### ISSUE TITLE
Can we use for Angular 2?

### ISSUE THREAD

**Issue by dainhan90** [mattlewis92/angular-calendar#190]
Can we use for Angular 2?

**Comment by al37350** [comment]
The last version that's compatible with angular 2 is 0.9.1. But it's very easy to upgrade from 2 to 4.

**Comment by mattlewis92** [comment]
What @al37350 is correct. The upgrade from 2 to 4 is just a matter of [changing the dependencies in your package.json](https://github.com/mattlewis92/angular2-tv-tracker/commit/9439e3cec40293b2a86bc2222f610ee6ad4b5229) and [adding the `angular/animations` module](https://github.com/mattlewis92/angular2-tv-tracker/commit/9fe0e3158290c2612d20e4c0f54d2204fb70791e)
