### ISSUE TITLE
Bug: resize in week mode pushes other events along

### ISSUE THREAD

**Issue by DoctorU** [mattlewis92/angular-calendar#191]
### Bug description

In week view
WHEN there are two events side-by-side
AND the left-most event is resizable
AND the first event is on Monday
AND the second event is on Wednesday
THEN
resizing the first event to also cover Tuesday will cause the second event to appear on Thursday until the resize event is complete.

### For bugs only, a link to minimally working plunker that reproduces the issue (you can fork a starter from any of the demos)
http://plnkr.co/edit/7dzQkwFTl9PX0VAZQOXJ?p=preview (fork of issue 1 plunker)

### Versions

Angular: 4.0.2

Calendar library: 0.13.5

Browser name and version: Google Chrome Version 57.0.2987.133 (64-bit) MacOS Sierra v10.12.4 (16E195)

**Comment by mattlewis92** [comment]
Good catch! I will get that sorted in the next version 😄

**Comment by mattlewis92** [comment]
Apologies for the delay on fixing this one, it took me a while to thing of a good solution. The fix just landed in 0.17.0 😄
