### ISSUE TITLE
Translation Issue

### ISSUE THREAD

**Issue by aebmknrl** [mattlewis92/angular-calendar#194]
### Bug description / Feature request:

On a weekend view, the title generated is on English and not spanish. This won't happen on Month view and Day view.

![image](https://cloud.githubusercontent.com/assets/5152002/25319216/36c08c5c-2869-11e7-823e-330aeb674403.png)

![image](https://cloud.githubusercontent.com/assets/5152002/25319227/4d8d23fa-2869-11e7-9d9e-633f42530711.png)

### For bugs only, a link to minimally working plunker that reproduces the issue (you can fork a starter from any of the demos)

I use your main sample. The only thing that i change is:

From
`<h3>{{ viewDate | calendarDate:(view + 'ViewTitle'):'en' }}</h3>`
to:
`<h3>{{ viewDate | calendarDate:(view + 'ViewTitle'):'es' }}</h3>`

### Versions

Angular: 4.0.1

Calendar library: 0.12.0

Browser name and version: 

Chrome

**Comment by aebmknrl** [comment]
Ok i can fix this with this sample: https://mattlewis92.github.io/angular-calendar/#/i18n

Only one question... this example is only for change (or do a override) the week title?

**Comment by mattlewis92** [comment]
The week view title is a bit of a weird one as it's the only title that can't be translated via the browser i18n api so you need to override the provider, everything else can be done through the browser i18n api though.
