### ISSUE TITLE
Hour Segment not available for week view

### ISSUE THREAD

**Issue by amitgaur208** [mattlewis92/angular-calendar#195]
### Bug description / Feature request:
I need to display hour slots in calendar week view but not working.

### Versions

Angular:  4.0.0

Calendar library:  0.14.0

Browser name and version: All Browser

**Comment by mattlewis92** [comment]
There is no support for that in this library, please see: https://github.com/mattlewis92/angular-calendar#the-month-week-or-day-view-doesnt-meet-my-project-requirements-but-the-other-views-do
