### ISSUE TITLE
ExpressionChangedAfterItHasBeenCheckedError

### ISSUE THREAD

**Issue by andreroggeri** [mattlewis92/angular-calendar#196]
### Bug description / Feature request:

I'm getting a `ExpressionChangedAfterItHasBeenCheckedError` when I put the `mwl-calendar-week-view` inside a container using the below css configuration and hover the event.

```
html, body, .container {
  margin: 0;
  width: 100%;
  height: 100%;
}
```

### For bugs only, a link to minimally working plunker that reproduces the issue (you can fork a starter from any of the demos)

I couldn't reproduce the issue on plunkr, so I made a [this repo](https://github.com/andreroggeri/angular-calendar-material-issue).

Just do npm install and ng serve and hover the event.

![](http://g.recordit.co/p2fMdaF1sv.gif)

### Versions

Angular: 4.0.0

Calendar library: 0.14.0

Browser name and version: Chrome 58 (Windows 10 64bits)

**Comment by mattlewis92** [comment]
I can't reproduce this unfortunately, I believe it might have been caused by a bug with angular itself rather than this lib. If after upgrading all dependencies to the latest versions you're still getting the error, could you add a `yarn.lock` file (`npm install -g yarn && yarn`) to the project so I can make sure we're on the exact same versions of everything. Thanks!
<img width="1369" alt="screen shot 2017-04-30 at 10 34 14" src="https://cloud.githubusercontent.com/assets/6425649/25563284/94eee86a-2d90-11e7-8a4a-6a804a5d67c8.png">

**Comment by andreroggeri** [comment]
Dependencies up to date and I added the yarn file.

I'll dig more, if I find something useful, I'll post here

**Comment by andreroggeri** [comment]
It seems that the initial screen width is smaller (1897 vs 1918).

This difference is because of the scrollbar that is displayed when I hover the event.

Using `margin: 1px` fixes for now.

I hope this help you to find the problem.

Thanks !

**Comment by nbickel** [comment]
i have the same issue. but in my complex template margin: 1px; does not fix it. same versions as andreroggeri.

**Comment by mattlewis92** [comment]
Ah I finally managed to reproduce this, I will cut a release shortly with the fix. Thank you both @andreroggeri and @nbickel for your help with finding the source of the issue 😄

**Comment by mattlewis92** [comment]
Should be fixed now in 0.15.0, please let me know if you're still experiencing issues. Thanks!

**Comment by andreroggeri** [comment]
I've just checked on the latest version and its fixed !

Thank you very much ! 🥂

**Comment by mattlewis92** [comment]
Great to hear, thanks for the confirmation! 😄

**Comment by blaur** [comment]
I am getting this exact exception in my week view. I am on the latest version and it happens when having two stacked events in the right most column.

**Comment by mattlewis92** [comment]
@blaur can you make a minimal repo / plunker that reproduces your issue? It's really hard to track down these kinds of errors without one. Thanks!

**Comment by nbickel** [comment]
The issue came back. i am quite sure that it was fixed. but now with v18.3 and v19 i have the same error message again. turning off the weekTooltip-workaround still works.
