### ISSUE TITLE
Error on plunkr of recurrent event

### ISSUE THREAD

**Issue by aebmknrl** [mattlewis92/angular-calendar#197]
### Bug description / Feature request:

The demo on plunkr of recurrent events not work.

![image](https://cloud.githubusercontent.com/assets/5152002/25565490/cfbd8370-2d95-11e7-9328-9fd761328f9a.png)

On my project when i put this import:

`import * as RRule from 'rrule';`

is marked with "Cannot find module rrule"

### Versions

Angular: 4.0.1

Calendar library: 0.12.0

Browser name and version: Chrome

**Comment by mattlewis92** [comment]
Thanks for reporting, fixed now!
