### ISSUE TITLE
using customCellTemplate for event images, I loose my tooltips

### ISSUE THREAD

**Issue by grimace** [mattlewis92/angular-calendar#198]
I'm on angular 4.0.0 and have created a customCellTemplate to display images instead of colored circles (successfully).   In the process tho, I've lost the tooltip for the events.  I'm wondering if there is a way to get them back, or do I need to implement using another method?  The cell template was taken from the demo provided and modified:

```
<ng-template #customCellTemplate let-day="day" let-locale="locale">
  <div class="cal-cell-top">
    <span class="cal-day-badge" *ngIf="day.badgeTotal > 0">{{ day.badgeTotal }}</span>
    <span class="cal-day-number">{{ day.date | calendarDate:'monthViewDayNumber':locale }}</span>
  </div>
  <div class="cal-day-events">
    <span class="cal-day-event" *ngFor="let event of day.events">
      <img class="cal-day-icon" src="{{ event.icon }}">
    </span>
  </div>
  <!-- <small style="margin: 5px">There are {{ day.events.length }} events on this day</small> -->
</ng-template>

```

**Comment by mattlewis92** [comment]
Ah sorry the docs aren't too great on this, if you add 
```
[mwlCalendarTooltip]="event.title | calendarEventTitle:'monthTooltip':event"
[tooltipPlacement]="tooltipPlacement"
```

on your events it should bring back the tooltips. For reference, here's the  [original source of the template](https://github.com/mattlewis92/angular-calendar/blob/master/src/components/month/calendarMonthCell.component.ts#L8-L27). Hope that helps! 😄

**Comment by grimace** [comment]
totally did the trick!  To be clear for anyone else looking... this goes on the 'customTemplate', not on the <mwl-calendar-month-view>.   Thx!

**Comment by MukunthKarthikeyan** [comment]
Hi,

Is there any example available. For adding custom template into mwl-calendar-open-day-events.

**Comment by AhHa45** [comment]
@mattlewis92 I noticed that many of your links to your examples/sources in your comments are dead, could you update them?

**Comment by mattlewis92** [comment]
I'm afraid there are over 500 closed issues on this repo and this is something I work on in my spare time so it's not something I can commit to.
