### ISSUE TITLE
Unable to add 42 days on the monthly calendar 

### ISSUE THREAD

**Issue by sandeepsparity** [mattlewis92/angular-calendar#199]
I'm not able to display 42 days on the monthly calendar . Is there any way to add 42 days on the monthly calendar ?

I need to see 6 weeks on the monthly calendar .

Appreciate if some help me to fix this issue and need to get start and end date of the month

Regards, 
Sann

### Versions

Angular: 

Calendar library: 

Browser name and version:

**Comment by sandeepsparity** [comment]
I need to get the start date and end date for the calendar which is displayed on the screen. If it's for the specific month then we will get by using startOfMonth and endOfMonth but, In my scenario, the past month days and current month days are displaying.I need to get past month start date and current month end date.

**Comment by mattlewis92** [comment]
Ah ok, in which case wrap the start/end of month calls with startOfWeek and endOfWeek

**Comment by mattlewis92** [comment]
I've just cut 0.15.0 which now allows you to get this behaviour, there is a demo of how to use it here: https://mattlewis92.github.io/angular-calendar/#/extra-month-view-weeks
