### ISSUE TITLE
Component mwl-calendar-day-view depends on external CSS (box-sizing:border-box) to render correctly

### ISSUE THREAD

**Issue by gustavoramos00** [mattlewis92/angular-calendar#201]
### mwl-calendar-day-view depends on external CSS (box-sizing:border-box) to render correctly

The component "mwl-calendar-day-view" renders calendar events correctly only if the CSS property "box-sizing:border-box" is provided. As BOOTSTRAP has this property as default, the demos works fine. But if other (or none) CSS framework is being used the events may be rendered bigger than should be.

### Versions

Angular:  4.0.0

Calendar library:  0.14.0

Browser name and version: Chrome 57

**Comment by mattlewis92** [comment]
Thanks, fixed!
