### ISSUE TITLE
Event (eventClicked) is not fired in mobile for draggable events

### ISSUE THREAD

**Issue by theunreal** [mattlewis92/angular-calendar#203]
### Bug description / Feature request:
Event click event not working in mobile

### For bugs only, a link to minimally working plunker that reproduces the issue (you can fork a starter from any of the demos)

All events with property draggable set to `true` are not executing the `(eventClicked)` event.

### Versions

Angular: 4

Calendar library: 0.14.0

Browser name and version: Chrome

**Comment by mattlewis92** [comment]
I can reproduce, thanks for reporting, will get it fixed up soon 😄 (in the meantime I wonder if adding [fastclick](https://github.com/ftlabs/fastclick) to your project fixes the issue?)

**Comment by theunreal** [comment]
@mattlewis92 I will check and update, btw I didnt' dive into the library but I wonder if it's worth trying to use HammerJS (tap) instead of (click) if you did use (click).

**Comment by mattlewis92** [comment]
I know angular has some built in support for hammerjs but I'm not 100% sure how it'd work for libraries as I wouldn't want to add a dependency on hammerjs for all users of this lib. I'll do some digging and see what I can come up with.

**Comment by mattlewis92** [comment]
Gave this some more thought and I've solved it by creating a custom click directive that uses hammerjs's `tap` event and falls back to `click` if hammer is not loaded. Does this work for you?

**Comment by adammedford** [comment]
I'm actually having this same issue, but on desktop in Chrome.

'eventTimesChanged' fires on clicking draggable events in all views. The only way I've managed to get eventClicked to work when both are present is to double click the event, but even that is inconsistent and still attempts to reschedule the event first.

**Comment by mattlewis92** [comment]
@adammedford I'm not able to reproduce your issue, can you see the same problem on any of the demos?

**Comment by adammedford** [comment]
I've not been able to reproduce it outside of my own code; although my code is basically a patchwork of different demos. Seems likely its being caused by something external but if I can track it down I will let you know. Thanks for the prompt response.

**Comment by AbhiTiwari1289** [comment]
**Bug**
1- Open Kitchen-sink demo in chrome browser
2- Select day view
3- Click on the draggable event
You will notice that the eventClicked is not firing, only eventTimesChanged fires.

**Comment by realshadow** [comment]
I have the same problem, it happens in Safari and Firefox as well so I dont think its browser related. What happens in my case is that `eventTimesChanged ` is always fired, even on click. I solved it by checking diff in minutes between new and old date
