### ISSUE TITLE
Multiple days in the month view

### ISSUE THREAD

**Issue by molot1989** [mattlewis92/angular-calendar#207]
Hi Matt, thanks for library.

How create events to span multiple days(like on the image, long event) in the month view?

ps. I used custom template but if event few days it's repeat every day

![screenshot-1](https://cloud.githubusercontent.com/assets/6584864/26033790/08a99b44-38bb-11e7-9414-13588758bc8a.png)

**Comment by mattlewis92** [comment]
Sorry there's no support for this UX, please see this answer for more details: https://github.com/mattlewis92/angular-calendar/issues/202#issuecomment-300455178
