### ISSUE TITLE
Week view with hours grid

### ISSUE THREAD

**Issue by VitaliiZhukov** [mattlewis92/angular-calendar#208]
### Feature request:

Hi!
I'm looking for a way to render week view with an hour grid under the each day. Like on next image
![untitled-1](https://cloud.githubusercontent.com/assets/10582247/26038054/58e386f4-3908-11e7-90d2-6276b2a19530.jpg)

I tried to use seven DAY views within one page but in this case event cells layout is broken. Probably there is a more proper way to implement it.
Thanks!

### Versions

Angular: @4.1.0

Calendar library: angular-calendar@0.14.0

**Comment by mattlewis92** [comment]
There's no support for this and it's not something I plan on implementing in this library as having several implementations of the same component in one library is a maintenance nightmare. You could however [build your own week view component](https://github.com/mattlewis92/angular-calendar#the-month-week-or-day-view-doesnt-meet-my-project-requirements-but-the-other-views-do) that functions how you want it to and use it as a replacement for the week view this library provides.

**Comment by blaur** [comment]
@VitaliiZhukov  Did you go ahead and implement this? Or maybe another plugin? Not having hours in a week view in a calendar seems very confusing from a users point of view.

**Comment by VitaliiZhukov** [comment]
@blaur 
Hi! I'm currently working on this issue. The idea is to place 7 day views within one page. Each view for separate day.
It works well actually, but I have some problems with layout of "event" blocks. Working on it right now

**Comment by bm-software** [comment]
@VitaliiZhukov Any updates about your implementation?

**Comment by blaur** [comment]
@VitaliiZhukov I am also very interested in your findings. I am wanting to implement the same but have not yet had the time.

**Comment by itafraji** [comment]
Any progress. Im interested too.

**Comment by bm-software** [comment]
I've create my own component that I actually use in my web app.
Here is a gist -> [Link](https://gist.github.com/bm-software/3b8539d82f7e633ff3894c3922aa0731)

It's still to improve in some parts (expecially the mobile support) but it works fine on browser.

Let me know what you think about this :)

**Comment by itafraji** [comment]
It seems good. Now just have to add drag and resize functionality to be completed.

**Comment by bm-software** [comment]
@itafraji Yes you're right! I've not enough time to do that for now. If you will implement drag&drop functionality please share your code when you've done :)

**Comment by olihou** [comment]
@bm-software I'm interrested too, you could create a repo if you want, we could share the work load to finish this :)
Btw : thank you very much to share your code

**Comment by bm-software** [comment]
@olihou [Here](https://github.com/bm-software/angular-calendar-scheduler) is the repo. I've created it on the fly so I haven't had enough time to test if it works. Could you check it and let me know?

Moreover, I'm experiencing some issues with `packagr` and `date-fns` required module and I'm not able to build a package to be published on npm. 
I'll be very glad if you can help me :)

**Comment by diegofsza** [comment]
Hi, sadly I found this comments too late, after I decided to build my own week view component. In case it is of use to any of you, or anyone interested in improving it, it is called [angular-calendar-week-hours-view](https://www.npmjs.com/package/angular-calendar-week-hours-view). This is [the repo](https://github.com/Innqube/angular-calendar-week-hours-view).

**Comment by itrethan** [comment]
@mattlewis92 

Hey Matt, I think you might want to reconsider this issues. It doesn't seems to be a rare use case for a calendar. For example, I am using this to create course schedule for schools. 

Users of this repo have implemented multiple versions of this feature, but all poorly supported. 

Having a build-in one would benefit both this project and its user.

Thanks,

**Comment by mattlewis92** [comment]
@itrethan - I'm not a company or software house - just one person hacking away on open source in my spare time for fun 😉 As I say in the readme, people are more than welcome to publish alternate week views on npm as complementary packages to this library, but it's not something I have the time or motivation to do myself.

**Comment by Digit1se** [comment]
Please can you consider removing the hours on the week view demo?
I feel like it's incredibly misleading to display something as a demo that is not actually available in the package.

**Comment by mattlewis92** [comment]
@Digit1se this is actually supported now in the core package, as of version `0.26.0` 😄

**Comment by Digit1se** [comment]
> @Digit1se this is actually supported now in the core package, as of version `0.26.0` 😄

Appreciate the effort. Thank you.
