### ISSUE TITLE
Question: How to use the periodicity?

### ISSUE THREAD

**Issue by aebmknrl** [mattlewis92/angular-calendar#209]
### Bug description / Feature request:

I only want to use this demo:
https://mattlewis92.github.io/angular-calendar/#/recurring-events
Can you teach me how to use a little bit this rrule with your calendar component?
I would like to use it with a custom things... How i can start? Thanks

**Comment by mattlewis92** [comment]
The idea behind using rrule is to use it to generate an array of events that this calendar displays (to keep the calendar as "dumb" and un-opinionated as possible). You can see from the demo how this happing can work, it may help you to read the rrule documentation which explains a bit more about how it works: https://github.com/jakubroztocil/rrule I don't know its API all that well though as I have no need for recurring events in our application.
