### ISSUE TITLE
Error displaying time on day view

### ISSUE THREAD

**Issue by aebmknrl** [mattlewis92/angular-calendar#212]
### Bug description / Feature request:

If the calendar locale is set on 'es' then the time on day view is displaying only numbers and without "AM/PM" or '23:00' format.

### For bugs only, a link to minimally working plunker that reproduces the issue (you can fork a starter from any of the demos)

![captura de pantalla 2017-05-18 a la s 5 07 34 p m](https://cloud.githubusercontent.com/assets/5152002/26223556/9fca1434-3bec-11e7-8c67-96a9c278ae89.png)

### Versions

Angular:  4.0.1

Calendar library: 0.12.0

Browser name and version: Chrome 53

**Comment by mattlewis92** [comment]
There doesn't seem to be a way to solve this that will work well with all locales so you'll have to provide your own date formatter like so: http://plnkr.co/edit/f4So2XnCkKa4HCBeLon2?p=preview
