### ISSUE TITLE
Question: Is any way to exclude a certain days like a holydays?

### ISSUE THREAD

**Issue by aebmknrl** [mattlewis92/angular-calendar#213]
### Bug description / Feature request:

Is just an urgent question... Is any way to exclude from one event or all events certain days like holydays? 
Can you help me? Thanks a lot for your hard work!

### Versions

Angular: 4.0.1

Calendar library: 0.12.0

Browser name and version: Chrome 53

**Comment by mattlewis92** [comment]
You could use the dayModifier option to disable certain days like so: https://mattlewis92.github.io/angular-calendar/#/min-max-date
