### ISSUE TITLE
calendarDate pipe not translating week

### ISSUE THREAD

**Issue by blaur** [mattlewis92/angular-calendar#215]
The following does not translate my week-view:
`<h3>{{ viewDate | calendarDate:(view + 'ViewTitle'):'da' }}</h3>`

All other other views titles are translated correct. Also, the actual days of the week are correct just not the title.

Any ideas?

**Comment by blaur** [comment]
And I just found the answer... A bit to quick. Sorry guys!

https://mattlewis92.github.io/angular-calendar/#/i18n

**Comment by can-kara** [comment]
blaur this is not working  TR culture
