### ISSUE TITLE
Preselect day

### ISSUE THREAD

**Issue by Enitnelav** [mattlewis92/angular-calendar#216]
Hi, i would like to pre-select a day on the month view but 'viewdate' doesn't work.

**Comment by mattlewis92** [comment]
Using the selected day as a started point, you just need to set the selected date like so: http://plnkr.co/edit/4FFMLdV1vu8sVXBJTm1c?p=preview 

If loading the selected date from the server then you'll need to refresh the calendar like in this example: https://mattlewis92.github.io/angular-calendar/#/refreshing-the-view
