### ISSUE TITLE
I need to combine async events and recurrent events

### ISSUE THREAD

**Issue by dfhincapiem** [mattlewis92/angular-calendar#217]
Hello, I would like to know if is there any way to integrate recurrent events and async events in a single calendar, I have seen several examples but can't find a useful code for this problem.

Thank you

**Comment by mattlewis92** [comment]
When you map your events from the API like this: https://github.com/mattlewis92/angular-calendar/blob/master/demos/demo-modules/async-events/component.ts#L62-L69 you'll need to repeat them to make them recurring this like: https://github.com/mattlewis92/angular-calendar/blob/master/demos/demo-modules/recurring-events/component.ts#L75-L88

If you can share some code of what you've done so far I'd be happy to help more 😄

**Comment by GeekNickson** [comment]
@dfhincapiem Did you find a solution?
