### ISSUE TITLE
How do I show the selected day in week view?

### ISSUE THREAD

**Issue by SteveDunlap13** [mattlewis92/angular-calendar#222]
I see the class cal-today applied if its the current day (and other class applied to the other days in the week view).
How do I apply a different class to a selected day (background-color)?
i.e.
[class.cal-today]="day.isToday"

**Comment by mattlewis92** [comment]
Sorry about the late reply on this one! I've just released 0.18.1 which should now let you do this. I've put together a plunker that demonstrates how to use the API here: http://plnkr.co/edit/xbRlY64TuCIIL1ZDKgoj?p=preview

Hope that helps! 😄

**Comment by SteveDunlap13** [comment]
Txs.  Exactly what I needed.
