### ISSUE TITLE
ERROR TypeError: Cannot read property 'edge' of null

### ISSUE THREAD

**Issue by Wandang** [mattlewis92/angular-calendar#225]
### Bug description / Feature request:
If two events touch each other and you try to resize them the calendar will crash.

### For bugs only, a link to minimally working plunker that reproduces the issue (you can fork a starter from any of the demos)
Just using your demo: https://mattlewis92.github.io/angular-calendar/#/kitchen-sink

* Switch to day view
* Create a second draggable/resizeable event (just a new event will have those attributes)
* Set the first event to end at some time like 06:30 AM
* Set the second event to start at 06:30 AM
* Try to resize any event at the touching line (my guess is, that this case is never anticipated, resizing two events at the same time)
* Not only does the calendar crash, the events will be thrown somewhere (your first event might start at a different time then before, even if the start time was never touched)

Crashlog:
```
core.es5.js:1084 ERROR TypeError: Cannot read property 'edge' of null
    at e.resizeEnded (calendarDayView.component.ts:333)
    at Object.eval [as handleEvent] (e.ngfactory.js:141)
    at Object._ [as handleEvent] (core.es5.js:11914)
    at Object.handleEvent (core.es5.js:12617)
    at He (core.es5.js:8814)
    at core.es5.js:10742
    at t.object.o [as _next] (core.es5.js:3863)
    at t.__tryOrUnsub (Subscriber.js:238)
    at t.next (Subscriber.js:185)
    at t._next (Subscriber.js:125)
```

Expected outcomes:
a) Both events will resize along the moved line
b) A random event will resize (Making it possible to take a second chance at resizing the right event, and then resizing the second to fix)
c) As b) but always top or always bot event will be resized to have consistency

### Versions

Angular: your demo version

Calendar library: your demo version

Browser name and version: Chrome 58.0.3029.110 (64-bit)

**Comment by Wandang** [comment]
Added info that this was encountered in day view (since you seem to be fixing it for week view at the moment)

**Comment by mattlewis92** [comment]
I realised the bug was present in both the week and day views so wanted to fix it in both places, unfortunately I ran out of time the other day so didn't have time to fix it in the day view as well. I've just cut 0.17.1 which has the fix in it. Hope that helps! 😄
