### ISSUE TITLE
Add the option for rendering the current hour in day view.

### ISSUE THREAD

**Issue by tusharice** [mattlewis92/angular-calendar#234]
### Feature request: 

Currently, we can set the viewDate for displaying the current date on Calendar. Provide an option to set the current hour first hour in day view component.

### Versions

Angular: 

Calendar library: 0.16.0

Browser name and version:

**Comment by mattlewis92** [comment]
Sorry I'm not quite sure I follow you, would you mind explaining a bit more? Thanks!

**Comment by mattlewis92** [comment]
Closing due to lack of response
