### ISSUE TITLE
Range selector

### ISSUE THREAD

**Issue by maxliguge** [mattlewis92/angular-calendar#235]
### **Feature request**:
Not sure if it's really a feature request but here is the main plot:
I've started using the calendar as an important component of my application (kind of reservation-system).
At the beginning I was just using the main feature already provided by the calendar, but right now I need to do a range selector on the "month" view. After some time of research since I didn't found this kind of feature I've started building my own. But then I found out the Angular1 version of the calendar(well yeah since I'm not using Angular1 I kinda ignored it) and I've noticed that it was implemented in the first version of the calendar [here](https://mattlewis92.github.io/angular-bootstrap-calendar/#!?example=select-range). So is there any plan of adding it to the angular4 version and if not, any idea on how to process?

### Versions

Angular: 4.1.3

Calendar library: 0.15.4

Browser name and version: pretty much all of them^^

**Comment by mattlewis92** [comment]
One of the goals of the rewrite of this calendar was to make everything extensible and provide as little in the core of it as possible (as it becomes a maintenance burden when you have a large API surface). You can add this feature yourself with the existing API by taking advantage of angulars component inheritance. I put together a plunker so you can see how it can work here: http://plnkr.co/edit/e6KcKl5ncmcIWADdcWHO?p=preview

Hope that helps! 😄

**Comment by maxliguge** [comment]
Ok, I can see the main idea behind this 😄;
But at the end we ended up doing the date range only by selecting the start and end date of our event. Because the event will often be displaying on 2 separate month we tough that it will be a better experience for the user to proceed like that since it will be easier and a better user-friendly experience. 

Thanks for the reply! 😄

**Comment by kotmatpockuh** [comment]
Hi, @mattlewis92. Is it possible to show week calendar with time rows? like in fullcalendar?

**Comment by mattlewis92** [comment]
There is no component for that, however you could build your own to replace the week view that's part of this lib!

**Comment by maxliguge** [comment]
I don't think there is an option to do so at that time.
For me the best idea would be to use the [minute precision](https://mattlewis92.github.io/angular-calendar/#/week-view-minute-precision) and display the hour on the event like [here ](https://mattlewis92.github.io/angular-calendar/#/show-dates-on-titles), it's not exactly like in fullCalendar, but depending on what you need, it can do the trick.
