### ISSUE TITLE
Error on Day view

### ISSUE THREAD

**Issue by aebmknrl** [mattlewis92/angular-calendar#238]
### Bug description / Feature request:
My calendar component suddenly only show the events from a day to another day. Events that start on the same day and finnished on the same day are not displaying.

I override the CalendarEvent:

```
export interface CayenaEvent extends CalendarEvent {
    id: number,
    colorEvent?: string,
    comment?: string,
    periodicityRule?: any,
    category?:EventCategory,
    customCategory?: CustomEventCategory
    priority?: EventPriority,
    eventAttachment?: [EventAttachment],
    untilDate?: Date,
    hold?: boolean,
    check?: boolean,
    completeEvents?: [CompleteEvents],
    description?:string,
    isTask:boolean

}
```
On the month and week view are display normally.

### For bugs only, a link to minimally working plunker that reproduces the issue (you can fork a starter from any of the demos)
See the result for a month:

![image](https://user-images.githubusercontent.com/5152002/26860033-b4a1fd82-4b09-11e7-850c-627dfe2eb65b.png)

The week:

![image](https://user-images.githubusercontent.com/5152002/26860044-c5c3eb3e-4b09-11e7-8253-52e39a349cec.png)

A day:

![image](https://user-images.githubusercontent.com/5152002/26860051-d36a480a-4b09-11e7-8e40-9f0daaa3d835.png)

Please note that the only event displaying are a event that last from a day to another one.

### Versions

Angular: 4.0.1
Calendar library: 0.17.0 

Browser name and version: Chrome 53

**Comment by mattlewis92** [comment]
Please follow the issue template and attach a plunker that reproduces your problem as I can't remotely debug issues in someone else's code from a screenshot.
