### ISSUE TITLE
Clickable hours on viewDay

### ISSUE THREAD

**Issue by Numalama** [mattlewis92/angular-calendar#240]
Hello,

Does any events like dayClicked for hours in DayviewDay exist?

I would like to create events on users's click actions.

I found this: https://mattlewis92.github.io/angular-bootstrap-calendar/#!?example=select-range

But I work on an Ionic 3 project and the angular version is not compatible.

Thank you

**Comment by mattlewis92** [comment]
You can use the `hourSegmentClicked` output for this: https://github.com/mattlewis92/angular-calendar/blob/master/src/components/day/calendarDayView.component.ts#L210
