### ISSUE TITLE
dayClicked giving me undefinend parameter 

### ISSUE THREAD

**Issue by uraees** [mattlewis92/angular-calendar#242]
I am using angulart 2 calendar in my project and I have an issue with trapping the dayClicked method. Here is my code and my action script function

ionic HTML code

<mwl-calendar-month-view 
[viewDate]="today" 
[headerTemplate]="headerTemp" 
(dayClicked)="dayClicked(calendarDay)" 
[dayModifier]= "dayModifier">
action script code

dayClicked = (day) => {

alert(JSON.stringify(day));
if (this.selectedDay) {
  delete this.selectedDay.cssClass;
}
day.cssClass = 'cal-day-selected';
this.selectedDay = day;
}

When I run the browser ionic emulator , I am getting the function dayClicked invoked but the parameter is coming out as “undefined”. I am stuck and any help is appreciated

Thanks
Raees

**Comment by mattlewis92** [comment]
The only magic variable available to angular outputs is '$event', hence why calendarDay is undefined.

**Comment by mattlewis92** [comment]
If you can make a minimal repo that reproduces your issue I'm happy to debug more, but I don't know how to fix your problem without having something I can hack on to work out what's going wrong 😀

**Comment by uraees** [comment]
Matt,


Here is my repository  https://github.com/uraees/AngularCalendarIonicTest/ and my files are here https://github.com/uraees/AngularCalendarIonicTest/tree/master/src/pages/home

[https://avatars2.githubusercontent.com/u/6796513?v=3&s=400]<https://github.com/uraees/AngularCalendarIonicTest/tree/master/src/pages/home>

uraees/AngularCalendarIonicTest<https://github.com/uraees/AngularCalendarIonicTest/tree/master/src/pages/home>
github.com
AngularCalendarIonicTest - testing angular calendar with ionic



Thanks for helping me out here


Raees

[https://avatars2.githubusercontent.com/u/6796513?v=3&s=400]<https://github.com/uraees/AngularCalendarIonicTest/tree/master/src/pages/home>

uraees/AngularCalendarIonicTest<https://github.com/uraees/AngularCalendarIonicTest/tree/master/src/pages/home>
github.com
AngularCalendarIonicTest - testing angular calendar with ionic





________________________________

**Comment by mattlewis92** [comment]
I can't see anything referencing this lib in that repo?

**Comment by uraees** [comment]
Matt,


Sorry , can you check now; looks like the changes are updated now


thanks

Raees


Raees Uzhunnan
________________________________


________________________________

**Comment by mattlewis92** [comment]
The variable you pass here: https://github.com/uraees/AngularCalendarIonicTest/blob/master/src/pages/home/home.html#L29

Should be called $event not day

**Comment by uraees** [comment]
Wow it worked.  sorry for bothering you this much for such a simple fix man .. looks like I got side tracked with the cellClicked function signature.  I remember trying this and getting errors .. but now good


Once again appreciate greatly !


Raees


Raees Uzhunnan
________________________________


________________________________
