### ISSUE TITLE
feature request: hours inside week view

### ISSUE THREAD

**Issue by jgpATs2w** [mattlewis92/angular-calendar#243]
### Feature request:
Option for viewing hours inside week view.
I.e. https://fullcalendar.io/, if you select week view, you can see the hours.

Any workaround?
Thanks!

**Comment by mattlewis92** [comment]
Sorry there's no support for that in the lib, wysiwyg on the demos. I have no plans of adding support for it, but you could build your own version of it and use it as a replacement for this libraries week view component.
