### ISSUE TITLE
How to remove the "Event action occurred" windows in a clean way

### ISSUE THREAD

**Issue by IterationCorp** [mattlewis92/angular-calendar#245]
Hello,

Thanks for this nice work on angular-calendar. I just noticed my version of the calendar also come with the "Event action occurred" information windows cause I was based on your demo.

I just want to remove it, but in a clean way (remove all unnecessary line of code, but don't compromise the fonctionnent of clicking on event or day). 

In the HTML file I should remove this:

```
<ng-template #modalContent let-close="close">
  <div class="modal-header">
    <h5 class="modal-title">Event action occurred</h5>
    <button type="button" class="close" (click)="close()">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="modal-body">
    <div>
      Action:
      <pre>{{ modalData?.action }}</pre>
    </div>
    <div>
      Event:
      <pre>{{ modalData?.event | json }}</pre>
    </div>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-secondary" (click)="close()">OK</button>
  </div>
</ng-template>
```

What about  HandleEvent ? did I still need it?

```
  handleEvent(action: string, event: CalendarEvent): void {
    this.modalData = {event, action};
    this.modal.open(this.modalContent, {size: 'lg'});
  }
```

**Comment by mattlewis92** [comment]
Yup just remove anything that references modals, it might help to view another demo that doesn't use modals such as: https://mattlewis92.github.io/angular-calendar/#/async-events

**Comment by IterationCorp** [comment]
Thanks for your help!
