### ISSUE TITLE
Defina properties for start/end/title/...

### ISSUE THREAD

**Issue by mythjuha** [mattlewis92/angular-calendar#246]
### Bug description / Feature request:
Feature request

### Versions
Angular: 4.2.3
Calendar library: 0.17

Is it possible to define which properties hold the start time, end time and titles of an event? Trying to use the calendar on an existing API.

**Comment by mattlewis92** [comment]
This isn't possible but you can implement it very easily with a .map as can be seen here: https://mattlewis92.github.io/angular-calendar/#/async-events
