### ISSUE TITLE
How to start

### ISSUE THREAD

**Issue by hmuschett** [mattlewis92/angular-calendar#247]
### Bug description / Feature request:
I have installed the module and it works I can see the component
```
  <Mwl-calendar-month-view
   [ViewDate] = "viewDate"
   [Events] = "events">
</ Mwl-calendar-month-view>
```
  But I want to start using it but I do not understand the documentation, I copied the codes of the demos and it does not work, it can teach us how to start using this great module thanks

### Versions

Angular: 
^4.0.0
Calendar library: 
^0.17.3
Browser name and version: 
firefox 54

**Comment by mythjuha** [comment]
What i think is deffinatly missing from the documentation, but can be 'taken' from the demo's, is what yout 'event' data should look like.

Do you have a variable 'events' on your component, that is an array of objects such as this:
```
{
title: "my title",
start: new Date() // Start date here,
end: new Date() // end date here
color: blue // See the const 'colors' in the demo
}
```

**Comment by hmuschett** [comment]
That is in case of an event I, what I want is to modify the views I copied the html and all the code of the demos and it does not work

**Comment by mattlewis92** [comment]
@hmuschett if you can share some code via a plunker or github repo of what you've got so far and what you're trying to do, I'd be happy to help you debug further 😄 

@mythjuha good shout, I have added a link to the `CalendarEvent` schema in the API docs (you can always ctrl + click in your IDE on any typescript interface though to be taken to its definition for quick access while you're working)

**Comment by mattlewis92** [comment]
Closing due to lack of response, happy to help debug more if you're still stuck and can share some code! 😄
