### ISSUE TITLE
Unexpected token import with angular-universal

### ISSUE THREAD

**Issue by benlegault** [mattlewis92/angular-calendar#248]
### Bug description / Feature request:
Should this work with angular-universal? I've seen an issue but the solution was with asp.net so I don't know if the same fix apply to a node.js project.  

When trying to run a project with angular-universal and angular-calendar, I gent the following:

/Users/studio7/Documents/Projets/angular/universal/jolishack-universal/dist/ngfactory/node_modules/angular-calendar/dist/esm/src/directives/calendarTooltip.directive.ngfactory.ts:9
import * as i0 from '@angular/core';
^^^^^^
SyntaxError: Unexpected token import
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/Users/studio7/Documents/Projets/angular/universal/jolishack-universal/node_modules/ts-node/src/index.ts:376:14)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
 

### Versions

Angular: 4.0.0

Calendar library: 0.17.4

**Comment by mattlewis92** [comment]
It should work with with universal, it looks to me like an issue with your build configuration rather than this library. If you can put together a minimal repo that demonstrates the issue I'd be happy to help you more 😀

**Comment by benlegault** [comment]
Thanks for the answer, that's what I'll do today.

**Comment by benlegault** [comment]
Ok I've started a new project (ng new project), modified the project for universal and run it, works fine.  Installed the package angular-calendar, declare it in app.module.js and I have the same error.

app.module.ts
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

import { AppComponent } from './app.component';
import { CalendarModule } from 'angular-calendar';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule.withServerTransition({appId: 'calendarTest'}),
    CalendarModule.forRoot()
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
package.json
{
  "name": "angular-calendar-universal",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "prestart": "ng build --prod && ngc",
    "start": "ts-node src/server.ts",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^4.2.4",
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/platform-server": "^4.2.4",
    "@angular/router": "^4.0.0",
    "angular-calendar": "^0.17.4",
    "core-js": "^2.4.1",
    "rxjs": "^5.1.0",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular/cli": "1.1.2",
    "@angular/compiler-cli": "^4.0.0",
    "@angular/language-service": "^4.0.0",
    "@types/jasmine": "2.5.45",
    "@types/node": "~6.0.60",
    "codelyzer": "~3.0.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "protractor": "~5.1.2",
    "ts-node": "~3.0.4",
    "tslint": "~5.3.2",
    "typescript": "~2.3.3"
  }
}
I'll continue investigating but if this rings you a bell or you might have a clue, would be very appreciated.  ng serve works fine.

**Comment by mattlewis92** [comment]
Seems like a tooling issue rather than something wrong with this lib. I just forked a universal demo and added the calendar and it's working fine for me:

https://github.com/mattlewis92/ng-universal-demo/commit/0c484bda65ddfc3d8759eaabb3304b69eb20f22f

<img width="1413" alt="screen shot 2017-06-22 at 16 11 41" src="https://user-images.githubusercontent.com/6425649/27441520-b100ea0e-5765-11e7-8cc0-90f6fdab8969.png">

I don't actually use universal myself so am not familiar with its nuances, I'd recommend asking on stackoverflow and creating a minimal, runnable repo that reproduces your issue and I'm sure someone with better knowledge than me will be able to help you more 😄

**Comment by benlegault** [comment]
ok I see.  I'll look at your form.  It might be somehting simple then and will follow your recommendation (stackoverflow), thanks!!!
