### ISSUE TITLE
angular-calander  mwl-demo-utils-date-time-picker not working

### ISSUE THREAD

**Issue by KamleshNada** [mattlewis92/angular-calendar#251]
mwl-demo-utils-date-time-picker not working in angular calendar it shows Error: Template parse errors:
'mwl-demo-utils-date-time-picker' is not a known element:
1. If 'mwl-demo-utils-date-time-picker' is an Angular component, then verify that it is part of this module.
2. If 'mwl-demo-utils-date-time-picker' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.

**Comment by mattlewis92** [comment]
That component is only meant to be used in the demo, just delete it from your code.

**Comment by KamleshNada** [comment]
Thanks for reply,

If i want to use it in my application ,can i possible? or if i want to get Date and time both from Day View Selection and get time on click event on multiple hours like 12 AM and 12.30 AM.can it possible.?

**Comment by mattlewis92** [comment]
To use the date / time pickers in your app you'll need to use them from this library: https://ng-bootstrap.github.io/#/getting-started
