### ISSUE TITLE
Screen not updating

### ISSUE THREAD

**Issue by arborinfelix** [mattlewis92/angular-calendar#252]
I have started a clean project where I get my data to my application from a standard angular http call  from my service like this:

```
getDays() {
return this.http.get(URL).map((response: Response) => response.json() 
}
```
On my component I call the http get like this:

```
this.myService.getDays().subscribe((response: Day[]) => {
                                                          this.days = response ;
                                                          console.log(this.days); });
```

On the html side I display the array in a simple *ngFor loop like this:
```
<ul>
  <li *ngFor="let day of days">{{day}}</li>
</ul>
```

It works! Very simple.....
Then I have followed the steps shown on the "Getting started" to install the calendar. I also tried some of the provided calendar examples and they did work. But now the very simple http call's results are not showing like they should. The array of days comes after the http call and the results are correctly displayed in the console but it doesn't show up on the screen in the html list element until I click on one of the days on the calendar.

Is there something that the calendar does to the other elements which are not related to the calendar?

this is my package.json
```
{
  "name": "fluggiland",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^4.2.4",
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/router": "^4.0.0",
    "angular-calendar": "^0.17.4",
    "core-js": "^2.4.1",
    "rxjs": "^5.1.0",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular/cli": "1.0.2",
    "@angular/compiler-cli": "^4.0.0",
    "@types/jasmine": "2.5.38",
    "@types/node": "~6.0.60",
    "codelyzer": "~2.0.0",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.0.0",
    "karma-cli": "~1.0.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "protractor": "~5.1.0",
    "ts-node": "~2.0.0",
    "tslint": "~4.5.0",
    "typescript": "~2.2.0"
  }
}
```

Thank you

Angular:
^4.0.0
Calendar library:
^0.17.4
Browser name and version:
IE 11 and Chrome Version 58.0.3029.110 (64-bit)

**Comment by mattlewis92** [comment]
Please follow the issue template and provide a plunker that reproduces your issue, as it's impossible to remotely debug issues in other peoples apps without something I can hack on. Thanks! 😄
