### ISSUE TITLE
Error when import the modules

### ISSUE THREAD

**Issue by rosehashmi** [mattlewis92/angular-calendar#253]
I am facing lots of parse errors when i include the module into the ionic3 application .
Some of them are in the following screenshot.
![angular-calendar-errors](https://user-images.githubusercontent.com/15095426/27496792-fc3af792-5870-11e7-91cd-780f7264356f.png)

**Comment by mattlewis92** [comment]
You need to upgrade typescript to >= 2.3, please see https://github.com/mattlewis92/angular-calendar/issues/221 for more info
