### ISSUE TITLE
A way to set a min length to be displayed on mobile

### ISSUE THREAD

**Issue by IterationCorp** [mattlewis92/angular-calendar#254]
During my search I understand that you don't support displaying the calendar view on mobile. I think I have no chance to change your mind ;-) but I want your opinion on a "workaround".

In landscape mode on iPhone 6-7 the result is ok. Is it possible to setup a minimal length so the calendar will not collapse? What will be the best practice? I mean in CSS or JS not iFrame ;-)

Thanks

**Comment by mattlewis92** [comment]
Sorry I'm not quite sure I follow you, what do you mean by it not collapsing?

**Comment by IterationCorp** [comment]
Sorry for my broken English. I mean not having the calendar being display like this:
![img_0694](https://user-images.githubusercontent.com/6637470/27506545-2e92507a-58ba-11e7-9509-854c84c69965.PNG)

But instead maybe having a horizontal scroll bar activated so the calendar can be displayed correctly.

**Comment by mattlewis92** [comment]
Thanks for explaining more. You can workaround this by adding some custom CSS to just make everything a bit smaller, there is a good article on how to do this here: https://thielcole.github.io/ionic2/2017/02/03/Ionic2-Calendar.html

**Comment by IterationCorp** [comment]
Thanks will do it!
