### ISSUE TITLE
Set weekend days

### ISSUE THREAD

**Issue by theunreal** [mattlewis92/angular-calendar#255]
Couldn't find any documentation about changing the weekend days.
In my country, the weekend days are Friday and Saturday.

I noticed that in the Angular 1.x version this feature is possible.

Any idea how to change that?

**Comment by mattlewis92** [comment]
It was hard coded before and I've made it configurable now in 0.18.0. You can see a demo of how to use it here: https://mattlewis92.github.io/angular-calendar/#/i18n 

Hope that helps! 😄

**Comment by lironzaa** [comment]
works well
