### ISSUE TITLE
I need your previous angular 2 calendar

### ISSUE THREAD

**Issue by KabilanKamaraj** [mattlewis92/angular-calendar#259]
I have currently doing angular 2 project 75% completed now need your angular 2 calendar I can not upgrade angular 4 because conflict older modules

**Comment by mattlewis92** [comment]
You can just downgrade to 0.9.1 which is the last version that supports angular 2 https://github.com/mattlewis92/angular-calendar/blob/master/CHANGELOG.md#091-2017-03-23

**Comment by KabilanKamaraj** [comment]
thanks @mattlewis92
