### ISSUE TITLE
Customizing cell template for day view

### ISSUE THREAD

**Issue by shaliadiga** [mattlewis92/angular-calendar#261]
How to customize cell template for day view? We have several events for the same time that needs to be displayed.  These events are shown as badge in month view for mobile using cellTemplate. How do we achieve this in day view? There is no property to customize the cell template for day view. Please provide examples if possible.
Thank you

**Comment by mattlewis92** [comment]
You should be able to use the `hourSegmentTemplate` input for this, it might be tricky implementing your use case though as the hour segment logic is separate from events. Here's a plunker for you that shows how to use the option: http://plnkr.co/edit/R8nb2pmhCGB0TTypkOJV?p=preview Hope that helps! 😄

**Comment by shaliadiga** [comment]
Thank you. While trying to the use hourSegmentTemplate, I get the error 'Can't bind to 'hourSegmentTemplate' since it isn't a known property of 'mwl-calendar-day-view'. Am I missing something? This is how I am using it
<mwl-calendar-day-view *ngSwitchCase="'day'"
                               [viewDate]="viewDate"
                               [refresh]="refresh"
                               [events]="events"
                               [hourSegments]="4"
                               [dayStartHour]="8"
                               [hourSegmentTemplate]="hourSegmentTemplate"
                               [dayEndHour]="17" >
        </mwl-calendar-day-view>


<template #hourSegmentTemplate let-segment="segment" let-locale="locale">
    <div class="cal-cell-top"
        [class.cal-hour-start]="segment.isStart"
        [class.cal-after-hour-start]="!segment.isStart"
        [ngClass]="segment.cssClass">
        <span class="cal-time">
            {{ segment.date | calendarDate:'dayViewHour':locale }}
        </span>
        This is some custom content
    </div>
</template>

**Comment by mattlewis92** [comment]
It was only added in [0.12.0](https://github.com/mattlewis92/angular-calendar/blob/master/CHANGELOG.md#0120-2017-04-05), it sounds like you're on an older version.

**Comment by shaliadiga** [comment]
Thank you

**Comment by mattlewis92** [comment]
np, happy to help 😄

**Comment by shaliadiga** [comment]
Upgraded to  "angular-calendar": "0.12.0" to make use of the hourSegmentTemplate. But now the below error message comes
(SystemJS) Unexpected token <↵	SyntaxError: Unexpected token <↵	    at eval (<anonymous>)↵	

Debugging , found that the error is from js file for animation not getting loaded. @angular/animation is for Angular 4.0 . We are using angular 2.4, how do we handle ?

Thank you

**Comment by mattlewis92** [comment]
You'll need to upgrade your version of angular to use the latest version of this lib. It should only be a 5 minute job of [upgrading the dependencies in package.json](https://github.com/mattlewis92/angular2-tv-tracker/commit/9439e3cec40293b2a86bc2222f610ee6ad4b5229) and [adding the browser animations module](https://github.com/mattlewis92/angular2-tv-tracker/commit/9fe0e3158290c2612d20e4c0f54d2204fb70791e).

**Comment by harsimerkaur** [comment]
Hi @sabb123, How did you achieve to alter design for your use case? I also have a scenario where I have many events at same time/hour.

**Comment by TinyJoy20** [comment]
@mattlewis92  can you give me a n example of how to customize cell template for month view as i wanted to show the title in the event.

**Comment by auroitsoft** [comment]
can you give me one example for refreshing the dayStartHour and DayEndHour with dynamic values from api

**Comment by rahul0755** [comment]
Can't bind to 'dayEndHour' since it isn't a known property of 'mwl-calendar-month-view',
Can't bind to 'dayEndHour' since it isn't a known property of 'mwl-calendar-month-view'.
I'm facing this issue. How to solve it.
