### ISSUE TITLE
Cell highlighting when using context menus

### ISSUE THREAD

**Issue by mgween** [mattlewis92/angular-calendar#262]
### Bug description / Feature request:

I recently added context menu functionality as shown in the 'Context menu' demo. Everything else seems to be working correctly, but cells on the month view now no longer highlight with the event's secondary color when an event is hovered over. How would I achieve this functionality while using the `#monthCellTemplate` from the demo?

### Versions

Angular:

```
@angular/cli: 1.1.1
node: 8.0.0
os: win32 x64
@angular/animations: 4.2.2
@angular/common: 4.2.2
@angular/compiler: 4.2.2
@angular/core: 4.2.2
@angular/forms: 4.2.2
@angular/http: 4.2.2
@angular/material: 2.0.0-beta.7
@angular/platform-browser: 4.2.2
@angular/platform-browser-dynamic: 4.2.2
@angular/router: 4.2.2
@angular/cli: 1.1.1
@angular/compiler-cli: 4.2.2
@angular/language-service: 4.2.2
```

Calendar library: 

0.17.3

Browser name and version:

Google Chrome Version 58.0.3029.110 (64-bit)

**Comment by mattlewis92** [comment]
It works for me: http://plnkr.co/edit/xgTEoXZ4BVRGEbLsIgUh?p=preview

**Comment by mgween** [comment]
I have noticed that the problem is that the grey color for the currently hovered cell is being applied over the event color. You can see in the image below how on a multi-day event, the event color is properly applied to all days except for the currently hovered one.

![image](https://user-images.githubusercontent.com/18710736/27804148-584c0d0a-5ffb-11e7-8f20-a467a4772d8e.png)

**Comment by mattlewis92** [comment]
Ah, it's the `call-cell` class that's applied to make the top box fill the height, removing it fixes the issue: http://plnkr.co/edit/xgTEoXZ4BVRGEbLsIgUh?p=preview

**Comment by mgween** [comment]
That did the trick. Thanks for the assistance.
