### ISSUE TITLE
Generic type 'CalendarEvent<MetaType, any>' requires 2 type argument(s)

### ISSUE THREAD

**Issue by aavelyn** [mattlewis92/angular-calendar#263]
### Bug description / Feature request:

I'm getting over 30 TypeError messages due to CalendarEvent<MetaType, any>. 
I started a new project using the latest angular-cli and followed your implementation guide.
(install npm library, add css to cli conifg, import browseranimation and calender module)

ERROR in /Users/hanche/Desktop/Development/calender/node_modules/angular-calendar/dist/esm/src/providers/calendarEventTitleFormatter.provider.d.ts (27,18): Generic type 'CalendarEvent<MetaType, any>' requires 2 type argument(s).

ERROR in /Users/hanche/Desktop/Development/calender/node_modules/angular-calendar/dist/esm/src/providers/calendarEventTitleFormatter.provider.d.ts (31,25): Generic type 'CalendarEvent<MetaType, any>' requires 2 type argument(s).

ERROR in /Users/hanche/Desktop/Development/calender/node_modules/angular-calendar/dist/esm/src/providers/calendarEventTitleFormatter.provider.d.ts (35,17): Generic type 'CalendarEvent<MetaType, any>' requires 2 type argument(s).

ERROR in /Users/hanche/Desktop/Development/calender/node_modules/angular-calendar/dist/esm/src/providers/calendarEventTitleFormatter.provider.d.ts (39,24): Generic type 'CalendarEvent<MetaType, any>' requires 2 type argument(s).

ERROR in /Users/hanche/Desktop/Development/calender/node_modules/angular-calendar/dist/esm/src/providers/calendarEventTitleFormatter.provider.d.ts (43,16): Generic type 'CalendarEvent<MetaType, any>' requires 2 type argument(s).

ERROR in /Users/hanche/Desktop/Development/calender/node_modules/angular-calendar/dist/esm/src/providers/calendarEventTitleFormatter.provider.d.ts (47,23): Generic type 'CalendarEvent<MetaType, any>' requires 2 type argument(s).

ERROR in /Users/hanche/Desktop/Development/calender/node_modules/calendar-utils/dist/calendar-utils.d.ts (31,41): ',' expected.

ERROR in /Users/hanche/Desktop/Development/calender/node_modules/calendar-utils/dist/calendar-utils.d.ts (28,16): Generic type 'CalendarEvent<MetaType, any>' requires 2 type argument(s).

ERROR in /Users/hanche/Desktop/Development/calender/node_modules/calendar-utils/dist/calendar-utils.d.ts (31,43): Type parameter name cannot be 'any'

ERROR in /Users/hanche/Desktop/Development/calender/node_modules/calendar-utils/dist/calendar-utils.d.ts (47,12): Generic type 'CalendarEvent<MetaType, any>' requires 2 type argument(s).

ERROR in /Users/hanche/Desktop/Development/calender/node_modules/calendar-utils/dist/calendar-utils.d.ts (58,13): Generic type 'CalendarEvent<MetaType, any>' requires 2 type argument(s).

ERROR in /Users/hanche/Desktop/Development/calender/node_modules/calendar-utils/dist/calendar-utils.d.ts (68,12): Generic type 'CalendarEvent<MetaType, any>' requires 2 type argument(s).

ERROR in /Users/hanche/Desktop/Development/calender/node_modules/calendar-utils/dist/calendar-utils.d.ts (79,19): Generic type 'CalendarEvent<MetaType, any>' requires 2 type argument(s).

ERROR in /Users/hanche/Desktop/Development/calender/node_modules/calendar-utils/dist/calendar-utils.d.ts (90,12): Generic type 'CalendarEvent<MetaType, any>' requires 2 type argument(s).

ERROR in /Users/hanche/Desktop/Development/calender/node_modules/calendar-utils/dist/calendar-utils.d.ts (103,14): Generic type 'CalendarEvent<MetaType, any>' requires 2 type argument(s).

ERROR in /Users/hanche/Desktop/Development/calender/node_modules/calendar-utils/dist/calendar-utils.d.ts (112,14): Generic type 'CalendarEvent<MetaType, any>' requires 2 type argument(s).

ERROR in /Users/hanche/Desktop/Development/calender/node_modules/calendar-utils/dist/calendar-utils.d.ts (122,14): Generic type 'CalendarEvent<MetaType, any>' requires 2 type argument(s).

ERROR in /Users/hanche/Desktop/Development/calender/node_modules/angular-calendar/dist/esm/src/interfaces/calendarEventTimesChangedEvent.interface.d.ts (6,12): Generic type 'CalendarEvent<MetaType, any>' requires 2 type argument(s).

ERROR in /Users/hanche/Desktop/Development/calender/node_modules/angular-calendar/dist/esm/src/components/day/calendarDayView.component.d.ts (37,13): Generic type 'CalendarEvent<MetaType, any>' requires 2 type argument(s).

ERROR in /Users/hanche/Desktop/Development/calender/node_modules/angular-calendar/dist/esm/src/components/day/calendarDayView.component.d.ts (98,16): Generic type 'CalendarEvent<MetaType, any>' requires 2 type argument(s).

ERROR in /Users/hanche/Desktop/Development/calender/node_modules/angular-calendar/dist/esm/src/components/day/calendarDayView.component.d.ts (163,21): Generic type 'CalendarEvent<MetaType, any>' requires 2 type argument(s).

ERROR in /Users/hanche/Desktop/Development/calender/node_modules/angular-calendar/dist/esm/src/components/month/calendarMonthView.component.d.ts (28,13): Generic type 'CalendarEvent<MetaType, any>' requires 2 type argument(s).

ERROR in /Users/hanche/Desktop/Development/calender/node_modules/angular-calendar/dist/esm/src/components/month/calendarMonthView.component.d.ts (91,16): Generic type 'CalendarEvent<MetaType, any>' requires 2 type argument(s).

ERROR in /Users/hanche/Desktop/Development/calender/node_modules/angular-calendar/dist/esm/src/components/month/calendarMonthView.component.d.ts (136,31): Generic type 'CalendarEvent<MetaType, any>' requires 2 type argument(s).

ERROR in /Users/hanche/Desktop/Development/calender/node_modules/angular-calendar/dist/esm/src/components/month/calendarMonthView.component.d.ts (140,44): Generic type 'CalendarEvent<MetaType, any>' requires 2 type argument(s).

ERROR in /Users/hanche/Desktop/Development/calender/node_modules/angular-calendar/dist/esm/src/components/week/calendarWeekView.component.d.ts (34,13): Generic type 'CalendarEvent<MetaType, any>' requires 2 type argument(s).

ERROR in /Users/hanche/Desktop/Development/calender/node_modules/angular-calendar/dist/esm/src/components/week/calendarWeekView.component.d.ts (86,16): Generic type 'CalendarEvent<MetaType, any>' requires 2 type argument(s).

### Versions

Angular: ^4.0.0

Calendar library: 0.18.3

Browser name and version: Chrome 59.0.3071.115 (Official Build) (64-bit)

**Comment by etwillbefine** [comment]
Upgrade you typescript version to >= 2.3.
See [here](https://github.com/mattlewis92/angular-calendar/issues/221) for more help
