### ISSUE TITLE
Open time slots

### ISSUE THREAD

**Issue by sabb123** [mattlewis92/angular-calendar#264]
One of our requirements is to show available calendar which should show only available open slots ( time slots in the calendar that do not have  any events ).
How do we approach this, basically we need to show calendar listing of all time slots for every day that do not have events?
Thank you

### Versions

Angular: 

Calendar library: 

Browser name and version:

**Comment by mattlewis92** [comment]
You can get this effect with the `beforeViewRender` output: http://plnkr.co/edit/owbi5P3pqfzJ79KPPk0o?p=preview
