### ISSUE TITLE
Year view on angular - 4 version.

### ISSUE THREAD

**Issue by gmerabishvili** [mattlewis92/angular-calendar#268]
Is there any year view mode on angular -4 version?

**Comment by mattlewis92** [comment]
Please read the readme / see examples, all of these questions are answered there: https://github.com/mattlewis92/angular-calendar#how-come-theres-no-year-view-like-the-ng1-version

**Comment by fergalddaly** [comment]
Would find a year view very useful.

**Comment by gowsikk** [comment]
i need year view
