### ISSUE TITLE
Tooltips appearing offset from the events when calendar is embedded in a table

### ISSUE THREAD

**Issue by ntsiatinis** [mattlewis92/angular-calendar#270]
## I'm submitting a ...

<pre>
[x] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit a support request here, please ask on https://stackoverflow.com/
</pre>

### Bug description / Feature request

Hi there.
New to Angular etc, but trying to build a calendar based app using angular-calendar. 
I'm embedding the calendar in a table so I can have a list of resources in the left hand column and the calendar relating to the resource in the right. I've implemented the 'kitchen sink' demo as pure boilerplate to test it out, but I'm finding that when I hover over an event in the month or week views the tooltip is offset from the event.

Any assistance gratefully received :)

### Minimal reproduction of the problem with instructions
Try this plunker - http://plnkr.co/edit/rMRImQYHQeW6znoN9vtA?p=preview

You may find that it works as expected initially. If so, resize the preview pane and you should see the tooltips are offset

### Versions

Angular: 4.2.6
Bootstrap: 4.0.0-alpha.6
Calendar library: 0.18.3

Browser name and version: Chrome 59.0.3071.115

**Comment by mattlewis92** [comment]
Weird bug! Thanks for the repro, I will look into it as soon as I have some spare time 😄

**Comment by ntsiatinis** [comment]
I appreciate that, thanks :)

**Comment by mattlewis92** [comment]
I'm not sure exactly why this is happening, but if you upgrade to 0.19.0 and pass `[tooltipAppendToBody]="false"` and make sure your container element has `position: static` set to it then it should work ok 😄

**Comment by ntsiatinis** [comment]
That seems to work like a charm, thanks for sorting it :)
