### ISSUE TITLE
Week View 

### ISSUE THREAD

**Issue by yusuf99** [mattlewis92/angular-calendar#271]
Please let me know if there a way to display time on left side in week view similar to day view.

Also in month view , we have something CustomCellTemplate to customize the cell template.
Is there something similar in Week view to customize the cell?

Thanks

**Comment by mattlewis92** [comment]
Sorry there is no support for this alternate week view, please see this answer for more info: https://github.com/mattlewis92/angular-calendar/issues/208#issuecomment-301404367

The week view doesn't have a concept of cells like the month view, but you can customise the header or event templates in a similar fashion: https://github.com/mattlewis92/angular-calendar/blob/master/src/components/week/calendarWeekView.component.ts#L132-L140

**Comment by yusuf99** [comment]
Thanks for the response.

I tried eventTemplates but getting below error

Can't bind to 'eventTemplate' since it isn't a known property of 'mwl-calendar-week-view'.


   <mwl-calendar-week-view *ngSwitchCase="'week'"
                                [viewDate]="viewDate"
                                [events]="events"
                                [excludeDays]="excludeDays"
                                [eventTemplate]="customeCellTemplate"
                                [refresh]="refresh">
        </mwl-calendar-week-view>

**Comment by mattlewis92** [comment]
Make sure you're on the latest version of this lib

**Comment by yusuf99** [comment]
Thank you.

I upgraded to latest version

Please find attached screen shot for default week view calendar without implementing eventTemplate.
 
![weekview](https://user-images.githubusercontent.com/25913270/28184417-2e2e4856-67c8-11e7-8719-5e1fae71afd6.png)


Events are not rendering properly  on the row. When I looked into CSS its Margin-left: 20% that is causing the issue.

If I remove the margin-left for Wednesday , Thursday and Friday events it render on 1 row as expected.

Thanks

**Comment by yusuf99** [comment]
Screen shot for Day View generated

![dayview](https://user-images.githubusercontent.com/25913270/28184981-71d3bb84-67ca-11e7-9189-64570b192c94.PNG)

Thanks

**Comment by mattlewis92** [comment]
Please can you make a plunker which reproduces your issue, it's really hard to work out what's going wrong from a screenshot 😉

**Comment by EdwardMCastrillon** [comment]
@mattlewis92 Do you know any implementation of the week view with hours?

**Comment by mattlewis92** [comment]
Not that I know of I'm afraid!

**Comment by blaur** [comment]
@EdwardMCastrillon You can try to follow https://github.com/mattlewis92/angular-calendar/issues/208#issuecomment-301404367 where one of the guys informed a few months back that he was working on something like this.

I'm afraid I'll be moving away from this calendar. I have not been able to customize and make it work and a calendar without hours in a weekview is really not very useable.

If you ever get it to work then please let me know. If seems very difficult to customize though.

**Comment by PerNissila** [comment]
How can i get the title of an event when using a custom eventTemplate?

**Comment by maxprais1** [comment]
@PerNissila You use {{ weekEvent.event.title }}

**Comment by sudhir360** [comment]
i need to add column Header on day view can please hlep me @mattlewis92  please share me source code.
