### ISSUE TITLE
UI not updating after async call

### ISSUE THREAD

**Issue by tommykennedy** [mattlewis92/angular-calendar#272]
Hi Matt,

I was wondering if you could help me with an issue I having with an async call whereby the UI was not updating after returning an observable. 

https://stackoverflow.com/questions/45108254/angular-calendar-not-updating-ui-from-http-request

Tom

**Comment by mattlewis92** [comment]
I can't see anything obviously wrong with the code you shared, are you able to share a runnable plunked that reproduces your problem? The async example might help: https://mattlewis92.github.io/angular-calendar/#/async-events

**Comment by tommykennedy** [comment]
I will try and do the plunker. I have tested aspects and I think that the issue is with the subscribe method. The events array gets updated but it doesnt reflect in the UI. When I print the array out on the html page the this.events shows an empty array. However when I click on the day view button it shows on the screen

     this._swapService.getSwapEvents('one').subscribe((resData) => {
           this.events = resData;
      });

**Comment by tommykennedy** [comment]
Hi Matt,

I think I may have narrowed it down to incorrect date formats. The below highlights the differences

_date properties set in subcribe method by constructing event object. This displays_
end: Sun Jul 16 2017 09:10:51 GMT+0100 (BST)
start: Sat Jul 15 2017 09:10:51 GMT+0100 (BST)

_date properties returned from API. This does not display_
end:"2017-07-16T08:10:51.541Z"
start:"2017-07-15T08:10:51.541Z"

I will close this once tested.

Tom

**Comment by mattlewis92** [comment]
Ah that would make sense, the calendar only works on date objects and not strings. Mapping the events and wrapping the date strings in new Date() should be enough.

**Comment by tommykennedy** [comment]
Thanks. The date format was the issue. Great component by the way

**Comment by abbasogaji** [comment]
@mattlewis92 hi mahn, am getting thesame issue and my date object is correct
