### ISSUE TITLE
Use Week View Style on Month View

### ISSUE THREAD

**Issue by hsuanweifu** [mattlewis92/angular-calendar#275]
## I'm submitting a ...

<pre>
[ ] Bug report 
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit a support request here, please ask on https://stackoverflow.com/
</pre>

### Bug description / Feature request

Will this package support resize and block scheduling (Week view) instead of dots on the Month view? If not how would I approach this task?

Thanks

### Versions

Angular:

Calendar library: 

Browser name and version:

**Comment by mattlewis92** [comment]
Sorry there's no support for this, the library is pretty much done and I have no plans to add any new features. I recommend just [building your own component](https://github.com/mattlewis92/angular-calendar#the-month-week-or-day-view-doesnt-meet-my-project-requirements-but-the-other-views-do) that suits your needs.
