### ISSUE TITLE
Missing CSS 

### ISSUE THREAD

**Issue by FullStackDeveloper11** [mattlewis92/angular-calendar#277]
I am using the latest version of calendar. After downloading and using it in the project I see that there are few css class that is used in the calendar HTML like "cal-hour", "cal-events" are missing from angular-calendar.css.

Please let me know if this missing CSS will create any problem in the future.

Thanks

**Comment by mattlewis92** [comment]
You need to include the calendars CSS: `node_modules/angular-calendar/dist/css/angular-calendar.css` somewhere in your app.

**Comment by FullStackDeveloper11** [comment]
I am looking at the file  node_modules/angular-calendar/dist/css/angular-calendar.css  

but still I see that few css class are missing in the file.

1. cal-hour
2. cal-events
3. cal-event-container

version v0.18.3

Please find the attachment, I have renamed .css to .txt

[angular-calendar.txt](https://github.com/mattlewis92/angular-calendar/files/1157003/angular-calendar.txt)

**Comment by mattlewis92** [comment]
Those are just for semantic purposes, so if you wanted to, you would be able to write your own CSS rules that targets those elements.
