### ISSUE TITLE
Day View event width 

### ISSUE THREAD

**Issue by di3orlive** [mattlewis92/angular-calendar#278]
###  I'm submitting a ...
[x] Feature request

### Feature request
can you please add some new variable for day view (like isFullWidth) 
so if true event will be with 100% width 
like here
http://prntscr.com/fxovhl

**Comment by mattlewis92** [comment]
The calendar is designed around events being fixed sizes so this would break dragging and resizing so its not something I would add in the lib, but you could probably fix it in your app by adding
```
.cal-day-view .cal-event-container {
  width: 100% !important;
}
```

Although if you have 2 events that display at the same time as each other, then only one would display.

**Comment by di3orlive** [comment]
its like a сrutch
we have margin-left
so if width 100% scroll appears 
we can fix if using overflow 
but this is second сrutch

**Comment by mattlewis92** [comment]
What about `width: calc(100% - 70px)`?

**Comment by di3orlive** [comment]
@mattlewis92 
lol forgot about calc
tnx
