### ISSUE TITLE
week view localization

### ISSUE THREAD

**Issue by FallenRiteMonk** [mattlewis92/angular-calendar#279]
## I'm submitting a ...

<pre>
[X] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit a support request here, please ask on https://stackoverflow.com/
</pre>

### Bug description / Feature request
Using the following:
```{{ today | calendarDate:(view + 'ViewTitle'): 'de' }}```
results in:
```Week 29 of 2017```
but should be:
```Woche 29 von 2017```

The static text should also be localized

**Comment by mattlewis92** [comment]
You have to implement this logic yourself, there is a demo of how to do that here: https://mattlewis92.github.io/angular-calendar/#/i18n

**Comment by FallenRiteMonk** [comment]
Sorry thanks
