### ISSUE TITLE
CSS Issue

### ISSUE THREAD

**Issue by mani3202** [mattlewis92/angular-calendar#280]
![screenshot 120](https://user-images.githubusercontent.com/28927591/28435992-fcd56492-6db2-11e7-87b0-177be98b0aa7.png)

How to resolve below issue.

If i hover my mouse to any of the date the corresponding row will be appear with some background color how can i resolve this ?
For reference please see above image.(I have hover my mouse to 5 remaing row will be having some background color)

**Comment by mattlewis92** [comment]
This is the css rule you need to override to remove the behaviour: https://github.com/mattlewis92/angular-calendar/blob/master/scss/month-view.scss#L8

**Comment by mani3202** [comment]
Thanks Its working fine for me now.
