### ISSUE TITLE
Grouping Events

### ISSUE THREAD

**Issue by mani3202** [mattlewis92/angular-calendar#281]
![capture](https://user-images.githubusercontent.com/28927591/28439407-67319796-6dbf-11e7-9f17-9bee5d9c28d9.PNG)

How can I group multiple events into one single event.
can you please help me to solve this issue.

Thanks in Advance.

**Comment by MPVogelPaint** [comment]
There is a demo for what I think you're trying to do: https://mattlewis92.github.io/angular-calendar/#/group-month-view-events

**Comment by mattlewis92** [comment]
What @MPVogelPaint said 😄

**Comment by mani3202** [comment]
I am getting this issue Property 'Entries' does not exist on type ObjectConstructor.

**Comment by mattlewis92** [comment]
You'll need a polyfill for Object.entries like https://github.com/es-shims/Object.entries or you can rewrite the code to ES5 not to use Object.entries
