### ISSUE TITLE
Allow custom templates for mwl-calendar-open-day-events

### ISSUE THREAD

**Issue by MPVogelPaint** [mattlewis92/angular-calendar#282]
## I'm submitting a Feature Request
<pre>
[ ] Bug report 
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit a support request here, please ask on https://stackoverflow.com/
</pre>

### Bug description / Feature request
Allow the mwl-calendar-open-day-events to support custom templates for each event.
I didn't see an option for this in the demo or documentation, but if I missed it let me know.

### Versions

Angular: 4.3.0

Calendar library: 0.19.0

Browser name and version: Chrome 61.0.3161.0

**Comment by mattlewis92** [comment]
It's there: https://github.com/mattlewis92/angular-calendar/blob/master/src/components/month/calendarMonthView.component.ts#L154 just not very well documented 😄 You can [use this](https://github.com/mattlewis92/angular-calendar/blob/master/src/components/month/calendarOpenDayEvents.component.ts#L19-L37) as a starting template. Hope that helps!
