### ISSUE TITLE
reg:- days naming

### ISSUE THREAD

**Issue by simandi434** [mattlewis92/angular-calendar#283]
For my requirement I need to show only first two letters of the days. So guide me the proper way to change the names of the days.

![calander](https://user-images.githubusercontent.com/20299297/28439696-8cefd424-6dc0-11e7-96b8-02e9339a1866.PNG)

Instead of those full names I need only first two letters of them. How can I Change them.

Thank you.

**Comment by MPVogelPaint** [comment]
I think this demo would work for what you're trying to do: https://mattlewis92.github.io/angular-calendar/#/customise-date-formats

**Comment by mattlewis92** [comment]
What @MPVogelPaint said 😄

**Comment by simandi434** [comment]
Hai MPVogelPaint,

Its working well for First three letters. But I need only first two letters of the weekdays.

Thank you.

**Comment by mattlewis92** [comment]
You can use substr for this:
```
public monthViewColumnHeader({date, locale}: DateFormatterParams): string {
    return new Intl.DateTimeFormat(locale, {weekday: 'short'}).format(date).substr(0, 2);
  }
```

**Comment by simandi434** [comment]
Thank you @mattlewis92.

Its working fine.
