### ISSUE TITLE
Reg: Events display

### ISSUE THREAD

**Issue by simandi434** [mattlewis92/angular-calendar#286]
As this calendar shows Badge number on the top of the date and event at the bottom. For my requirement I need badge number to be shown at the bottom. I don't need to display events anymore.

Thank you.

**Comment by mattlewis92** [comment]
You can either use CSS to hide and re-position the elements or for a more fine grained control use a custom cell template: https://mattlewis92.github.io/angular-calendar/#/custom-templates In the future please use stackoverflow for support requests as this tracker is for bug reports / feature requests only. Thanks! 😄
