### ISSUE TITLE
Day View Hour Segment

### ISSUE THREAD

**Issue by FullStackDeveloper11** [mattlewis92/angular-calendar#287]
I am using [hourSegments]="4",  it displays hours as 8AM , 9AM,....
Is there a way to display hoursegment as 8AM, 8.15, 8.30, 9AM......

Thanks

**Comment by mattlewis92** [comment]
This is possible, copied from https://github.com/mattlewis92/angular-calendar/issues/78 http://plnkr.co/edit/INtKoU2Tony08Soqy8x7?p=preview

In the future please use stackoverflow for support requests as this issue tracker is for bugs and features only. Thanks! 😄

**Comment by FullStackDeveloper11** [comment]
@mattlewis92

I just check even though it is displaying the hours in 15 mins, I am unable to locate any code or setting in the plunkr. 

Sorry to bother you with stupid question.



![hours](https://user-images.githubusercontent.com/30269667/28485941-2595514c-6e32-11e7-839b-e1b2abb57c2e.PNG)


![dayview2](https://user-images.githubusercontent.com/30269667/28486023-d718c200-6e32-11e7-9861-31637cee321c.PNG)

**Comment by mattlewis92** [comment]
You're looking in the wrong files, check `demo/module.ts` (for changing the time formatting) and `index.html` (for adding the styling to force displaying all times)

**Comment by FullStackDeveloper11** [comment]
Thanks Matt, I was looking for the change in index.html  

.cal-day-view .cal-hour-segment.cal-after-hour-start .cal-time {
        display: block;
      }

**Comment by cyphercodes96** [comment]
Hello Mattlewis.

I was recently attempting to implement this based on the plunkr you shared.
I added CustomDateFormatter class, and i was providing it in the imported CalendarModule.forRoot()
My previous Calendar had this: 
 CalendarModule.forRoot({
      provide: DateAdapter,
      useFactory: adapterFactory,
    })
I added it like this:
 CalendarModule.forRoot({
      provide: DateAdapter,
      useFactory: adapterFactory,
    }, {
      dateFormatter: {
        provide: CalendarDateFormatter,
        useClass: CustomDateFormatter
      }
    })
I also added the css style on the app.component + index.html and it failed to force display it

NPM: 6.2.0
cypher@cypher-Lenovo-ideapad-110-15ISK:~/Desktop/BiDirection/cloudclinic/ccdesk-ng$ ng --version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 6.1.1
Node: 10.9.0
OS: linux x64
Angular: 6.1.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.7.1
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.7.1
@angular-devkit/schematics        0.7.1
@angular/cdk                      6.4.2
@angular/cli                      6.1.1
@angular/flex-layout              6.0.0-beta.17
@angular/material                 6.4.2
@ngtools/webpack                  6.0.8
@schematics/angular               0.7.1
@schematics/update                0.7.1
rxjs                              6.2.2
typescript                        2.7.2
webpack                           4.8.3

**Comment by cyphercodes96** [comment]
Okay it worked!
My problem was simple.

The css class i was assigning inside my calendar.component.css && index.html wasn't taking place.
Had to declare it in the styles.css

Worked perfectly fine :D 
I was wondering, is there a turn around to have this on the week view aswell?

**Comment by kunalkakkad** [comment]
By follow 

> This is possible, copied from #78 http://plnkr.co/edit/INtKoU2Tony08Soqy8x7?p=preview
> 
> In the future please use stackoverflow for support requests as this issue tracker is for bugs and features only. Thanks! 😄

Hello,

as per the plunkr, it is showing divison of hours of 30 mins instead of 15 minutes.
Cna you please guide me for the same.

![image](https://user-images.githubusercontent.com/11589908/50507105-07010d80-0aa2-11e9-97b2-e483fd6b0ec4.png)

**Comment by nmatz** [comment]
> By follow
> 
> > This is possible, copied from #78 http://plnkr.co/edit/INtKoU2Tony08Soqy8x7?p=preview
> > In the future please use stackoverflow for support requests as this issue tracker is for bugs and features only. Thanks! 😄
> 
> Hello,
> 
> as per the plunkr, it is showing divison of hours of 30 mins instead of 15 minutes.
> Cna you please guide me for the same.
> 
> ![image](https://user-images.githubusercontent.com/11589908/50507105-07010d80-0aa2-11e9-97b2-e483fd6b0ec4.png)

Finally you can ? I need do the same

**Comment by kunalkakkad** [comment]
Hell

> > By follow
> > > This is possible, copied from #78 http://plnkr.co/edit/INtKoU2Tony08Soqy8x7?p=preview
> > > In the future please use stackoverflow for support requests as this issue tracker is for bugs and features only. Thanks! 😄
> > 
> > 
> > Hello,
> > as per the plunkr, it is showing divison of hours of 30 mins instead of 15 minutes.
> > Cna you please guide me for the same.
> > ![image](https://user-images.githubusercontent.com/11589908/50507105-07010d80-0aa2-11e9-97b2-e483fd6b0ec4.png)
> 
> Finally you can ? I need do the same

Hello,

Yes I have achieved it successfully.
Kindly follow the plnkr link provided and look for 2 files `demo/module.ts` and `index.html`.
This 2 files contains the magic to appear as smaller time interval.

**Comment by nmatz** [comment]
> Hello,
> 
> Yes I have achieved it successfully.
> Kindly follow the plnkr link provided and look for 2 files `demo/module.ts` and `index.html`.
> This 2 files contains the magic to appear as smaller time interval.

Thanks! I tried to modify modules.ts file but is just to do a date format.

I found a solution modifying [hourSegments] in html and works to show smaller time interval but when add event the hour is incorrect and it'snt the same of the view.

Here I add a event that end to 9:45 but is saved with different hour

![captura2](https://user-images.githubusercontent.com/42099944/52788694-7fb32d80-3040-11e9-96bc-908c5c3a2882.PNG)

Saved to Mon Mar 04 2019 **11:00:02** GMT-0300 (hora de verano de Chile) not to **09:45**

![captura](https://user-images.githubusercontent.com/42099944/52788738-9d809280-3040-11e9-96ba-38e9b7175b90.PNG)

Thanks for you time !

**Comment by nmatz** [comment]
> Hell
> 
> > > By follow
> > > > This is possible, copied from #78 http://plnkr.co/edit/INtKoU2Tony08Soqy8x7?p=preview
> > > > In the future please use stackoverflow for support requests as this issue tracker is for bugs and features only. Thanks! 😄
> > > 
> > > 
> > > Hello,
> > > as per the plunkr, it is showing divison of hours of 30 mins instead of 15 minutes.
> > > Cna you please guide me for the same.
> > > ![image](https://user-images.githubusercontent.com/11589908/50507105-07010d80-0aa2-11e9-97b2-e483fd6b0ec4.png)
> > 
> > 
> > Finally you can ? I need do the same
> 
> Hello,
> 
> Yes I have achieved it successfully.
> Kindly follow the plnkr link provided and look for 2 files `demo/module.ts` and `index.html`.
> This 2 files contains the magic to appear as smaller time interval.

Thanks! I tried to modify modules.ts file but is just to do a date format.

I found a solution modifying [hourSegments] in html and works to show smaller time interval but when add event the hour is incorrect and it'snt the same of the view.

Here I add a event that end to 9:45 but is saved with different hour

![captura2](https://user-images.githubusercontent.com/42099944/52788694-7fb32d80-3040-11e9-96bc-908c5c3a2882.PNG)

Saved to Mon Mar 04 2019 **11:00:02** GMT-0300 (hora de verano de Chile) not to **09:45**

![captura](https://user-images.githubusercontent.com/42099944/52788738-9d809280-3040-11e9-96ba-38e9b7175b90.PNG)

Thanks for you time !

**Comment by kaboomdev** [comment]
> > Hell
> > > > By follow
> > > > > This is possible, copied from #78 http://plnkr.co/edit/INtKoU2Tony08Soqy8x7?p=preview
> > > > > In the future please use stackoverflow for support requests as this issue tracker is for bugs and features only. Thanks! 😄
> > > > 
> > > > 
> > > > Hello,
> > > > as per the plunkr, it is showing divison of hours of 30 mins instead of 15 minutes.
> > > > Cna you please guide me for the same.
> > > > ![image](https://user-images.githubusercontent.com/11589908/50507105-07010d80-0aa2-11e9-97b2-e483fd6b0ec4.png)
> > > 
> > > 
> > > Finally you can ? I need do the same
> > 
> > 
> > Hello,
> > Yes I have achieved it successfully.
> > Kindly follow the plnkr link provided and look for 2 files `demo/module.ts` and `index.html`.
> > This 2 files contains the magic to appear as smaller time interval.
> 
> Thanks! I tried to modify modules.ts file but is just to do a date format.
> 
> I found a solution modifying [hourSegments] in html and works to show smaller time interval but when add event the hour is incorrect and it'snt the same of the view.
> 
> Here I add a event that end to 9:45 but is saved with different hour
> 
> ![captura2](https://user-images.githubusercontent.com/42099944/52788694-7fb32d80-3040-11e9-96bc-908c5c3a2882.PNG)
> 
> Saved to Mon Mar 04 2019 **11:00:02** GMT-0300 (hora de verano de Chile) not to **09:45**
> 
> ![captura](https://user-images.githubusercontent.com/42099944/52788738-9d809280-3040-11e9-96ba-38e9b7175b90.PNG)
> 
> Thanks for you time !

Hello! Can you tell me how did you divide the segments like in your screenshot? I am searching for this solution for a long time already. Would really appreciate, thank you in advance!!

**Comment by kunalkakkad** [comment]
> > Hell
> > > > By follow
> > > > > This is possible, copied from #78 http://plnkr.co/edit/INtKoU2Tony08Soqy8x7?p=preview
> > > > > In the future please use stackoverflow for support requests as this issue tracker is for bugs and features only. Thanks! 😄
> > > > 
> > > > 
> > > > Hello,
> > > > as per the plunkr, it is showing divison of hours of 30 mins instead of 15 minutes.
> > > > Cna you please guide me for the same.
> > > > ![image](https://user-images.githubusercontent.com/11589908/50507105-07010d80-0aa2-11e9-97b2-e483fd6b0ec4.png)
> > > 
> > > 
> > > Finally you can ? I need do the same
> > 
> > 
> > Hello,
> > Yes I have achieved it successfully.
> > Kindly follow the plnkr link provided and look for 2 files `demo/module.ts` and `index.html`.
> > This 2 files contains the magic to appear as smaller time interval.
> 
> Thanks! I tried to modify modules.ts file but is just to do a date format.
> 
> I found a solution modifying [hourSegments] in html and works to show smaller time interval but when add event the hour is incorrect and it'snt the same of the view.
> 
> Here I add a event that end to 9:45 but is saved with different hour
> 
> ![captura2](https://user-images.githubusercontent.com/42099944/52788694-7fb32d80-3040-11e9-96bc-908c5c3a2882.PNG)
> 
> Saved to Mon Mar 04 2019 **11:00:02** GMT-0300 (hora de verano de Chile) not to **09:45**
> 
> ![captura](https://user-images.githubusercontent.com/42099944/52788738-9d809280-3040-11e9-96ba-38e9b7175b90.PNG)
> 
> Thanks for you time !

Hello,

Kindly put following thing in your global css(style.css) or index,html:

.cal-day-view .cal-hour-segment.cal-after-hour-start .cal-time {
display: block;
}

**Comment by auroitsoft** [comment]
@mattlewis92  
![calender](https://user-images.githubusercontent.com/45762466/58399716-b4d70f00-8076-11e9-8e3b-369f5f2bd3e2.PNG)
its woks fine even after adding the css in index.html it was not good how to overcome it sir

**Comment by auroitsoft** [comment]
is there any way to give the hours in range and also in dynamic?

**Comment by samvimes01** [comment]
For new versions of angular and library, there is one minor change. But still, the solution is valid.
https://stackoverflow.com/questions/52447261/hour-display-hoursegments-angular-calendar/57291647#57291647

**Comment by ericwork002** [comment]
@mattlewis92 Hi Matt, plnkr demo is working buy I am using  "^0.27.18" , I bind component in ngmodule like this. CalendarModule.forRoot(
        {
            provide: DateAdapter,
            useFactory:  adapterFactory,
        },
        {
          dateFormatter :
            {
                provide: CalendarDateFormatter,
                useClass: WeeklyViewSideDateFormatter
            }
        }


It does not work, couldyou please provide a new example?  Thank you very much

**Comment by HectorDavila** [comment]
Hi! Is there a way to display hoursegment as 8 am, 8:40 am , 9:20 am , 10 am? (40 minutes segments)

**Comment by kuroza** [comment]
Instead of the day-hour-time displaying 1am, 2am, 3am.. I want to have a fixed 50 minutes time slots like this.. Does anybody know how?

Time in the morning:
07.50am - 08.40am
08.50am - 09.40am
09.50am - 10.40am
10.50am - 11.40am
11.50am - 12.40pm

Time in the afternoon:
02.10pm - 03.00pm
03.10pm - 04.00pm
04.30pm - 05.20pm
05.30pm - 06.20pm
