### ISSUE TITLE
not working demo https://mattlewis92.github.io/angular-calendar

### ISSUE THREAD

**Issue by johnpaulmanoza** [mattlewis92/angular-calendar#289]
## I'm submitting a ...

<pre>
[ ] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit a support request here, please ask on https://stackoverflow.com/
</pre>

### Versions

Angular: 

Calendar library: 

Browser name and version:

**Comment by mattlewis92** [comment]
Oops, sorry about that, was just working on adding AoT to the demo and accidentally broke the site. Should be fixed now 😄
