### ISSUE TITLE
Background color

### ISSUE THREAD

**Issue by pieterlouw1974** [mattlewis92/angular-calendar#291]
[ ] Bug report 
[x ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit a support request here, please ask on 

### Bug description / Feature request
Set background-color as a CalendarEvent ?

### Versions

Angular:  4.2.6

Calendar library:  0.19.0

Browser name and version: Chrome 59.
![capture](https://user-images.githubusercontent.com/5118546/28513493-aa9cdce0-7056-11e7-9d7b-0abcffb9f3e3.PNG)

**Comment by mattlewis92** [comment]
You can use the `before-view-render` hook to add classes to cells that style the background color: https://mattlewis92.github.io/angular-calendar/#/before-view-render
