### ISSUE TITLE
Unable to drag event on the same day and the next day

### ISSUE THREAD

**Issue by ShubhamVohra** [mattlewis92/angular-calendar#292]
I am trying to drag the event on the same day but it is not showing in the calendar.Though it is showing when I am doing it in the month and week view.

But if I am trying to do it for the yesterday or day before yesterday.Than it is showing up.

**Comment by mattlewis92** [comment]
Please follow the issue template and provide a plunker that reproduces your issue. Thanks! 😄

**Comment by ShubhamVohra** [comment]
Here is my html file:


`<div class="row">

  <div class="col-md-3">
    <div class="card">
      <div class="card-block">
        <ul>
          <li
            *ngFor="let event of externalEvents"
            mwlDraggable
            [dropData]="{event: event}"
            style="position:relative; z-index: 10">
            <a
              href="javascript:;"
              [style.color]="event.color.primary">
              {{ event.title }}
            </a>
          </li>
        </ul>
      </div>
    </div>
  </div>

  <div class="col-md-9">
    <mwl-demo-utils-calendar-header
      [(view)]="view"
      [(viewDate)]="viewDate">
    </mwl-demo-utils-calendar-header>

    <div [ngSwitch]="view">
      <mwl-calendar-month-view
        *ngSwitchCase="'month'"
        [viewDate]="viewDate"
        [events]="events"
        [activeDayIsOpen]="activeDayIsOpen"
        [refresh]="refresh"
        (eventTimesChanged)="eventDropped($event)">
      </mwl-calendar-month-view>
      <mwl-calendar-week-view
        *ngSwitchCase="'week'"
        [viewDate]="viewDate"
        [events]="events"
        [refresh]="refresh"
        (eventTimesChanged)="eventDropped($event)">
      </mwl-calendar-week-view>
      <mwl-calendar-day-view
        *ngSwitchCase="'day'"
        [viewDate]="viewDate"
        [events]="events"
        [dayStartHour]="9"
        [dayEndHour]="18"
        [refresh]="refresh"
        (eventTimesChanged)="eventDropped($event)">
      </mwl-calendar-day-view>
    </div>
  </div>

</div>`


and here is my typescript file:

`export class SchedboardComponent implements OnInit {
  view: string = 'day';
  viewDate: Date = new Date();
  state:string;
  size:number;
  
  requests:[{
    actype:string,
    capacity:string,
    reqtype:string,
    date:string,
    clientid:string,
    reqdesc:string,
    createdate:string,
    status:string,
    address:{
      geometry:{
        type:string,
        coordinates:{
          lat:number,
          lng:number
        }
      }
    },
    location:string
  }
  ];

  externalEvents:  CalendarEvent[]=[];
  events: CalendarEvent[] = [];
  activeDayIsOpen: boolean = false;
  obj: any;
  
  refresh: Subject<any> = new Subject();

  constructor(private requestservice:RequestService,public zone:NgZone) { 
  }

  ngOnInit() {
     this.state = null;
      this.requestservice.getRequests(this.state).subscribe((requests)=>{
      this.requests = requests; 
      this.size = this.requests.length;
      for(var i=0;i<this.size;i++){
         this.obj = {
          title: this.requests[i].reqdesc,
          start:new Date(this.requests[i].date),
          color:colors.yellow,
          end:new Date(this.requests[i].date),
          draggable:true
        }
      }
      
      this.externalEvents.push(this.obj);
      this.refresh.next();
      console.log(this.externalEvents);
    }); 
  }



  ngAfterViewInit(){
    
  }



  // eventTimesChanged({event,newStart,newEnd}: CalendarEventTimesChangedEvent): void {
  //   event.start = newStart;
  //   event.end = newEnd;
  //   this.refresh.next();
  // }

  eventDropped({event,
    newStart,
    newEnd
  }: CalendarEventTimesChangedEvent): void {
    const externalIndex: number = this.externalEvents.indexOf(event);
    if (externalIndex > -1) {
      this.externalEvents.splice(externalIndex, 1);
      this.events.push(event);
    }
    event.start = newStart;
    console.log(newStart);
    if (newEnd) {
      event.end = newEnd;
    }
    this.viewDate = newStart;
    this.activeDayIsOpen = true;
    this.refresh.next();
  }

}
  
`

**Comment by mattlewis92** [comment]
Please can you put in into a runnable plunker / or repo that I can actually run and debug, thanks!
