### ISSUE TITLE
Ical Integration

### ISSUE THREAD

**Issue by FullStackDeveloper11** [mattlewis92/angular-calendar#295]
I'm submitting a ...
[ ] Bug report 
[X ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit a support request here, please ask on https://stackoverflow.com/

Bug description / Feature request

Can we have the feature to export or import to ICal?

Or if you could suggest how we can integrate ICal into this calendar control.

Versions

Angular: 2+

**Comment by mattlewis92** [comment]
You would need to use a lib like https://www.npmjs.com/package/ical to parse and stringify events to and from an ical file into the format this lib expects. It's a similar concept to how you would read and format events from an API.

**Comment by Hg347** [comment]
I also interested this feature. I also stumbled upon the same ical API. I'm forking this project to give it a try. Anyone else interested in implementing this feature, please let me know.
