### ISSUE TITLE
Sync with google calendar API 

### ISSUE THREAD

**Issue by rdelriods01** [mattlewis92/angular-calendar#296]
## I'm submitting a ...

[ ] Bug report 
[x ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit a support request here, please ask on https://stackoverflow.com/

### Bug description / Feature request
Is there a way to sync this to my google calendar? 

### Versions

Angular: 4.0.0

Calendar library: 

Browser name and version: Chrome -v 59.0.3071.115

**Comment by mattlewis92** [comment]
There is no support for this as it's outside the scope of this library (the components goal is simply to display a list of events from an API). You would need to have your API read + write events from googles calendar with a module like: https://www.npmjs.com/package/node-google-calendar and then pass them through to your frontend and display them with this calendar.
