### ISSUE TITLE
Error to write in cli "npm start" 

### ISSUE THREAD

**Issue by vipulupadhyay** [mattlewis92/angular-calendar#298]
> angular-calendar1@0.19.0 start C:\Users\spfarmadmin\Desktop\angular-calendar-m
aster
> webpack-dev-server --open

Error: listen EACCES 127.0.0.1:8000
    at Object.exports._errnoException (util.js:1016:11)
    at exports._exceptionWithHostPort (util.js:1039:20)
    at Server.setupListenHandle [as _listen2] (net.js:1290:19)
    at listenInCluster (net.js:1355:12)
    at GetAddrInfoReqWrap.doListen (net.js:1481:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:96:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-calendar1@0.19.0 start: `webpack-dev-server --open`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-calendar1@0.19.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\spfarmadmin\AppData\Roaming\npm-cache\_logs\2017-07-31T11_
32_33_101Z-debug.log

**Comment by mattlewis92** [comment]
It looks like something is already listening on port 8000, you could try changing the port here: https://github.com/mattlewis92/angular-calendar/blob/master/webpack.config.ts#L76 and see if it helps.

**Comment by vipulupadhyay** [comment]
Now this way I'm getting error on page

Failed to compile.

  Error: Child compilation failed:
  Module build failed: Error: Cannot find module 'ejs'
  
  - module.js:11 require
    internal/module.js:11:18
  
  - index.js:1 Object.<anonymous>
    [angular-calendar-master]/[ejs-compiled-loader]/index.js:1:11
  
  - module.js:11 require
    internal/module.js:11:18
  
  - loadLoader.js:13 loadLoader
    [angular-calendar-master]/[loader-runner]/lib/loadLoader.js:13:17
  
  - LoaderRunner.js:169 iteratePitchingLoaders
    [angular-calendar-master]/[loader-runner]/lib/LoaderRunner.js:169:2
  
  - LoaderRunner.js:165 iteratePitchingLoaders
    [angular-calendar-master]/[loader-runner]/lib/LoaderRunner.js:165:10
  
  
  - Error: Cannot find module 'ejs'
  
  - compiler.js:76 
    [angular-calendar-master]/[html-webpack-plugin]/lib/compiler.js:76:16
  
  - Compiler.js:304 compile
    [angular-calendar-master]/[webpack]/lib/Compiler.js:304:11
  
  - Compiler.js:520 applyPluginsAsync.err
    [angular-calendar-master]/[webpack]/lib/Compiler.js:520:14
  
  - Tapable.js:184 next
    [angular-calendar-master]/[tapable]/lib/Tapable.js:184:11
  
  - CachePlugin.js:62 Compiler.<anonymous>
    [angular-calendar-master]/[webpack]/lib/CachePlugin.js:62:5
  
  - Tapable.js:188 Compiler.applyPluginsAsyncSeries
    [angular-calendar-master]/[tapable]/lib/Tapable.js:188:13
  
  - Compiler.js:517 compilation.seal.err
    [angular-calendar-master]/[webpack]/lib/Compiler.js:517:11
  
  - Tapable.js:177 Compilation.applyPluginsAsyncSeries
    [angular-calendar-master]/[tapable]/lib/Tapable.js:177:46
  
  - Compilation.js:654 self.applyPluginsAsync.err
    [angular-calendar-master]/[webpack]/lib/Compilation.js:654:19
  
  - Tapable.js:177 Compilation.applyPluginsAsyncSeries
    [angular-calendar-master]/[tapable]/lib/Tapable.js:177:46
  
  - Compilation.js:645 self.applyPluginsAsync.err
    [angular-calendar-master]/[webpack]/lib/Compilation.js:645:11
  
  - Tapable.js:177 Compilation.applyPluginsAsyncSeries
    [angular-calendar-master]/[tapable]/lib/Tapable.js:177:46
  
  - Compilation.js:640 self.applyPluginsAsync.err
    [angular-calendar-master]/[webpack]/lib/Compilation.js:640:10
  
  - Tapable.js:177 Compilation.applyPluginsAsyncSeries
    [angular-calendar-master]/[tapable]/lib/Tapable.js:177:46
  
  - Compilation.js:636 sealPart2
    [angular-calendar-master]/[webpack]/lib/Compilation.js:636:9
  
  - Tapable.js:177 Compilation.applyPluginsAsyncSeries
    [angular-calendar-master]/[tapable]/lib/Tapable.js:177:46

**Comment by vipulupadhyay** [comment]
Above problem solution is below
npm install ejs

[https://stackoverflow.com/questions/7754799/error-cannot-find-module-ejs ]

**Comment by mattlewis92** [comment]
Sounds like a bug with npm, make sure you're on the latest version and it should install fine `npm install -g npm@latest`
