### ISSUE TITLE
how can divide day view hour segments horizontal??

### ISSUE THREAD

**Issue by junyung1261** [mattlewis92/angular-calendar#300]
## I'm submitting a ...

<pre>
[ ] Bug report 
[x ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit a support request here, please ask on https://stackoverflow.com/
</pre>

### Bug description / Feature request

i am trying to implement like this planner '10 min segemts' 
and each event's time can be edited by drag each colors

![tt](https://user-images.githubusercontent.com/19746397/28933480-237bbc58-78b8-11e7-97ed-eade7b2af853.png)

![1213](https://user-images.githubusercontent.com/19746397/28933650-d8d88ad6-78b8-11e7-8c49-a4d577afb74b.png)

this is when it done and thanks for your efforts!

### Versions

Angular: 4.1.3

Calendar library: 

Browser name and version:

**Comment by mattlewis92** [comment]
I think the UX for this deviates too much from this libraries day view, you'd probably be better off building your own day view component from scratch that implements this.
