### ISSUE TITLE
Optimal width for events in dayview

### ISSUE THREAD

**Issue by AlexKolesnik** [mattlewis92/angular-calendar#301]
## I'm submitting a ...

<pre>
[ ] Bug report 
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit a support request here, please ask on https://stackoverflow.com/
</pre>

### Bug description / Feature request
It would be nice in my opinion if events could be arranged in the dayview not with a fixed width but with respect to the screen width and to collisions with other events.

I have tried to implement an idea from 
https://stackoverflow.com/questions/11311410/visualization-of-calendar-events-algorithm-to-layout-events-with-maximum-width
and would like to ask if you would integrate that into your calendar?

Attached ist my implementation, where I had to substitute your CalendarUtils-Provider and changed the events widths with the aforementioned algorithm.

Thanks
Alex

### Versions

Angular: 
4.0.3
Calendar library: 
0.17.0

Browser name and version: 

[mattlewisCalenderUtils.ts.txt](https://github.com/mattlewis92/angular-calendar/files/1200169/mattlewisCalenderUtils.ts.txt)
[eventLayouter.ts.txt](https://github.com/mattlewis92/angular-calendar/files/1200171/eventLayouter.ts.txt)
![image](https://user-images.githubusercontent.com/13681086/28966658-bfbe8352-7917-11e7-9750-25124db6a3e4.png)

**Comment by mattlewis92** [comment]
Hi there, this looks really cool! I deliberately allow you to override the calendar-utils provider so you can implement logic like this yourself to change the behaviour of the calendar to suit your apps purpose. I'd prefer this way rather than having every option baked into the core, otherwise the codebase becomes huge and unmaintainable. I'd prefer to keep the default behaviour as it is, as this component is primarily designed for desktop, and having full width events on the day view with a wide screen isn't a great UX imo.

**Comment by ratidzidziguri** [comment]
@AlexKolesnik  this is really interesting approach would you please share your experience how this would work outside ionic and how i can integrate it in a regular web app?

**Comment by ratidzidziguri** [comment]
@AlexKolesnik  well you are importing platform which is ionic specific and looks like it is to some earlier version compatible  if possible, kindly asking to share sample  repo with example of this customization.

**Comment by AlexKolesnik** [comment]
Oh, I see. The platform was for determining the width of the screen. I am sure there are other ways to do so. In app.module.ts the CalendarModule is configured to use the adapted utils

    @NgModule({
      declarations: [
        ...pages,
        ...components
      ],
    imports: [
     CalendarModule.forRoot({
      utils: MattlewisCalenderUtils
    }),

Here the updated source. This is all I can help with.

[source.zip](https://github.com/mattlewis92/angular-calendar/files/2392882/source.zip)

**Comment by ratidzidziguri** [comment]
@AlexKolesnik  Thank you very much looks like in addition i have to install calendar-utils lib inside main project. I will adopt this codebase now.

**Comment by AlexKolesnik** [comment]
Yes. Definitly. I have these imports...

import { CalendarModule, CalendarUtils } from 'angular-calendar';

**Comment by ratidzidziguri** [comment]
Well I am dropping this idea thank you for your answers it is just different version now and things are different calendar-utils npm package does not provide modules while angular-calendar changed a lot and this is kind of not easy staff to go with :(

**Comment by ratidzidziguri** [comment]
@mattlewis92  Becasue library got updated all this process became not not usable anymore so and there is no easy way to integrate this. like should application install calendar-utils npm separatly how to addopt it etc.

**Comment by mattlewis92** [comment]
You can actually hack the new api in `0.26` to work this way, take a look at [this demo](https://stackblitz.com/edit/angular-hdpk64?file=demo/template.html). Hope that helps! 😄

**Comment by ratidzidziguri** [comment]
mm not sure because what happens of there are more events overlapping?

**Comment by ratidzidziguri** [comment]
[daysinweek] is not known property :(

**Comment by mattlewis92** [comment]
They will squash down into separate columns to fix if they overlap. You need to make sure you're using version `0.26.0` or above and the property is called `daysInWeek` not `daysinweek`.

**Comment by Cyberuben** [comment]
@mattlewis92 Why isn't it possible to include this behavior with the day view? The logic seems to be there, it's in the week view calendar.

I'm creating a planner that shows one column per entity, and each entity has their own events. Events can overlap, and they should stack. The default behavior is that they either overlap, or they move to the next column. This behavior makes it seem like my events are in someone else's column while that shouldn't happen. 

How difficult would it be to create a `addColumn` method (or a `columns[]` array) that basically does the same as week-view, but with each column being the same day?
