### ISSUE TITLE
Disable the animation for the slide down box of events for the active day?

### ISSUE THREAD

**Issue by baptistecosta** [mattlewis92/angular-calendar#302]
Hi,
Is there a way to disable the animation for the slide down box of events for the active day?
Thanks,
Baptiste.

**Comment by mattlewis92** [comment]
Please see this demo 😄  https://mattlewis92.github.io/angular-calendar/#/disable-slide-animation

**Comment by baptistecosta** [comment]
Thanks, missed this one ;)
