### ISSUE TITLE
ExpressionChangedAfterItHasBeenCheckedError On Week View

### ISSUE THREAD

**Issue by antoineCMI** [mattlewis92/angular-calendar#303]
Bug report 

Angular-Calendar Version : 0.20
Angular Version :  4.3.1
Browser: Google Chrome Version 59.0.3071.115

Description:
When I change the view to week or everytime the event tooltip appears in week view, the ExpressionChangedAfterItHasBeenCheckedError appear in the console.

Error: 
![image](https://user-images.githubusercontent.com/30807325/29038305-43a41a24-7b75-11e7-8c08-e46288288557.png)

**Comment by mattlewis92** [comment]
I can't reproduce this on any of the demos, would you be so kind as to make a minimal repo / plunker that reproduces the issue? Thanks! 😄

**Comment by antoineCMI** [comment]
I can't reproduce the bug with pluker.
 After viewing this bug #196 and disable the tooltip in the week view (https://mattlewis92.github.io/angular-calendar/#/disable-tooltips ).  
The error ExpressionChangedAfterItHasBeenCheckedError  don't happen after the event tooltip appears. 

But, I alway get the bug when I change to week view.

**Comment by antoineCMI** [comment]
I just found the bug happens when I change the day to week view.

**Comment by mattlewis92** [comment]
Finally managed to reproduce this, should be fixed now in 0.21.1 😄
