### ISSUE TITLE
custom template event column span

### ISSUE THREAD

**Issue by antb-developer** [mattlewis92/angular-calendar#304]
## I'm submitting a ...

<pre>
[ ] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit a support request here, please ask on https://stackoverflow.com/
</pre>

### Bug description / Feature request
There is no option to span columns if event repeat for days.
`<ng-template #customCellTemplate let-day="day" let-locale="locale">
<span  *ngFor="let event of day.events"></span>
</ng-template>`

It results in 
[http://prntscr.com/g5pqhh](url)
it should be like:
[http://prntscr.com/g5praz](url)

There is only on box for event if event repeat for number of days , then it should be  column span and one title on full span (like i shown in red color)

I managed some part of this issue,
[http://prntscr.com/g5pt29](url)
When repeating event in a particular , i matched the day date , start date and end date
if its start = day , the span has left border and margin with event title - showing like new event is started
if start = end , the span has right border and margin with no event title - showing like event end
if middle - then no border and no margin with no event title

then another issue with event object array in particular day , date events array are unsorted with date 
[http://prntscr.com/g5px80](url)

I sorted the event object array with starting date , and its like
[http://prntscr.com/g5pzan](url)

### Versions

Angular: 

Calendar library: 

Browser name and version:

**Comment by mattlewis92** [comment]
You've run into the exact reason why this calendar doesn't display events spanning multiple days like this, I tried it myself when implementing this lib and it became too complicated and buggy to implement, so I settled on the original implementation from the ng1 version, whereby if you hover over an event it highlights the other days it spans. I get that its not a perfect UX, but it's the most reliable implementation I could come up with 😞
