### ISSUE TITLE
Need a calendar to display charts

### ISSUE THREAD

**Issue by Papamilo** [mattlewis92/angular-calendar#305]
Hi team ! First of all congrats for the great job you did wooow amazing !

It's not an issue but I didn't know where to post it ===> sorry for that

I need a calendar in my Angular 4 app to display some charts (using highcharts api [here's a link to highcharts](http://api.highcharts.com/) , the datas from the charts could be changed depending on a calendar. The datas are comming back from a Json using http module and observables, do you think your calendar could do the job? 

A part of the interface bellow:

![image](https://user-images.githubusercontent.com/17986987/29127335-13aa6096-7d21-11e7-89dd-f0271313318e.png)

Thanks in advance and greetings again for all the open source projects you did..if you need more infos feel free to ask..

**Comment by mattlewis92** [comment]
It sounds like you might be better off using a date picker rather than this lib: https://ng-bootstrap.github.io/#/components/datepicker/examples

**Comment by Papamilo** [comment]
Thank you so much @mattlewis92  and greetings again for the job I'll try to use some of your project :+1:
