### ISSUE TITLE
month view as full screen in mobile 

### ISSUE THREAD

**Issue by junyung1261** [mattlewis92/angular-calendar#307]
## I'm submitting a ...

<pre>
[ ] Bug report 
[x ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit a support request here, please ask on https://stackoverflow.com/
</pre>

### Bug description / Feature request

how can make full screen in this situation? I did my best but i cant found solution..
I wanna make full screen calendar in container and fit height automatically
I found flex in css but it was not help me. 
checked spaces are extra space.

![123](https://user-images.githubusercontent.com/19746397/29252783-a28b0808-80a8-11e7-9aff-cc4d5fabfe45.png)

### Versions

Angular: 

Calendar library: 

Browser name and version:

**Comment by mattlewis92** [comment]
Sorry this isn't really possible with this component, as the month view is designed to expand dynamically as events are added / the slide box is opened or closed, so its not possible to have it fill the height. If you're using ionic I'd suggest using a dedicated mobile component like: https://twinssbc.github.io/Ionic2-Calendar/demo/
