### ISSUE TITLE
Unexpected value 'ResizableModule' imported by the module 'CalendarModule'.

### ISSUE THREAD

**Issue by yelhouti** [mattlewis92/angular-calendar#310]
## I'm submitting a ...

<pre>
[x] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit a support request here, please ask on https://stackoverflow.com/
</pre>

### Bug description / Feature request

I'm trying to use the calendar with Ionic:
### Minimal reproduction of the problem with instructions
Create an Ionic app
add the dependency
add two line as described in the getting started: 
+ `import { CalendarModule } from 'angular-calendar';`
+ `CalendarModule.forRoot();`

https://stackblitz.com/edit/ionic-mjrf8r?file=app%2Fapp.module.ts

I also tried importing: 
+BrowserAnimationsModule
+BrowserAnimationsModule,
+CommonModule,
+FormsModule,
+NgbDatepickerModule.forRoot(),
+NgbTimepickerModule.forRoot(),
+CalendarModule

none of them helped I keep getting: 
Unexpected value 'ResizableModule' imported by the module 'CalendarModule'. Please add a @NgModule annotation
### Versions

Angular: 4.1.3

Calendar library: 0.20.1

Browser name and version: 
Chrome...

**Comment by mattlewis92** [comment]
Are you seeing this error locally as well or just on stackblitz?

**Comment by yelhouti** [comment]
My bad, problem only happening in stackblitz. I couldn't test earlier in my laptop.
