### ISSUE TITLE
Custom cell template

### ISSUE THREAD

**Issue by Vartex05** [mattlewis92/angular-calendar#311]
Hi iam having trouble to implement custom cell template. I need to display events label in day cell, but i have no clue how to do this. Can anyone give me example?

**Comment by swungdash** [comment]
You could do something like this and include the customCellTemplate in the [cellTemplate] of your mwl-calendar-month-view for example.

<ng-template #customCellTemplate let-day="day">
            <div class="fill-height" [contextMenu]="basicMenu" [contextMenuSubject]="day.date">
            <div class="cal-cell-top">
                <span class="cal-day-badge" *ngIf="day.badgeTotal > 0">{{ day.badgeTotal }}</span>
                <span class="cal-day-number">{{ day.date | calendarDate:'monthViewDayNumber':locale }}</span>
            </div>
            <div type="text" style="font-size: smaller" *ngFor='let event of day.events'>
                    {{ event.title }}
            </div>
            </div>
</ng-template>

**Comment by mattlewis92** [comment]
Thanks @swungdash for the good answer 😄
