### ISSUE TITLE
[Feature Request] Event title components

### ISSUE THREAD

**Issue by AlanCrevon** [mattlewis92/angular-calendar#312]
## I'm submitting a ...

<pre>
[ ] Bug report 
[X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit a support request here, please ask on https://stackoverflow.com/
</pre>

### Bug description / Feature request

Use a custom component as an event title. 

In my app, event edition is a 3 step process. I'd like to be able to provide (mateial2 styled) buttons to go to a specific step from the event title.

For now, CalendarEventTitleFormatter only handles strings as titles.

### Versions

Angular: 

Calendar library: 

Browser name and version:

**Comment by AlanCrevon** [comment]
By the way, thanks for this awesome library :+1:

**Comment by mattlewis92** [comment]
This seems reasonable, it should be a case of allowing [this component](https://github.com/mattlewis92/angular-calendar/blob/master/src/components/common/calendarEventTitle.component.ts) to accept a custom template like the others. Would you like to make a PR with the change? [This is an example commit](https://github.com/mattlewis92/angular-calendar/commit/149b605) showing how to do it for a different child component, but the same concept applies here as well 😄

**Comment by AlanCrevon** [comment]
I'll try that as soon as my current project (which uses angular-calendar :) ) is online. Time is running out...

Unless someone else does it first, which would be awesome ;)

**Comment by mattlewis92** [comment]
No worries, I'll try and get to it at some point in the next week or so :)

**Comment by AlanCrevon** [comment]
Thank you so much @mattlewis92 :+1:

**Comment by mattlewis92** [comment]
np, happy to help 😄
