### ISSUE TITLE
IE 11 not showing events from service

### ISSUE THREAD

**Issue by FARHANE** [mattlewis92/angular-calendar#313]
## I'm submitting a ...

<pre>
[x] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit a support request here, please ask on https://stackoverflow.com/
</pre>

### Bug description / Feature request
The calendar work's fine on Firefox, but not on IE 11.
I retrieve my events from database using a service, I can see my events on FireFox but not on IE 11.
I import all pollyfils:
import 'core-js/es6/symbol';
import 'core-js/es6/object';
import 'core-js/es6/function';
import 'core-js/es6/parse-int';
import 'core-js/es6/parse-float';
import 'core-js/es6/number';
import 'core-js/es6/math';
import 'core-js/es6/string';
import 'core-js/es6/date';
import 'core-js/es6/array';
import 'core-js/es6/regexp';
import 'core-js/es6/map';
import 'core-js/es6/set';

import 'classlist.js'; 
import 'web-animations-js';
import 'core-js/es6/reflect';
import 'core-js/es7/reflect';

### Versions
angular/cli: 1.3.0
node: 6.11.1
os: win32 x64
angular/animations: 4.1.3
angular/common: 4.1.3
angular/compiler: 4.1.3
angular/core: 4.1.3
angular/forms: 4.1.3
angular/http: 4.1.3
angular/platform-browser: 4.1.3
angular/platform-browser-dynamic: 4.1.3
angular/platform-server: 4.1.3
angular/router: 4.1.3
angular/cli: 1.3.0
angular/compiler-cli: 4.1.3

Calendar library: 4.0+

Browser name and version:  IE 11.0.9600.18697

**Comment by mattlewis92** [comment]
Can you share a screenshot or something of what you're seeing? Thanks!

**Comment by FARHANE** [comment]
Thank you for your response.
FireFox  : 
![001](https://user-images.githubusercontent.com/7517235/29448609-c8c40be4-83f7-11e7-854a-57b5c94d095a.PNG)
IE 11: 
![002](https://user-images.githubusercontent.com/7517235/29448652-fa14b518-83f7-11e7-90d1-3a888bcaae77.PNG)

**Comment by mattlewis92** [comment]
Ah I believe this is probably a bug with flexbox in IE11. It should probably be quite easily fixable with CSS.

**Comment by FARHANE** [comment]
Thank you for your quick response I will try it.

**Comment by FARHANE** [comment]
Hello, It's me again.
I forgot to say that with static data IE work perfectly, when I get data from server the div with class ="cal-events" is not rendered.
FireFox : 
![001](https://user-images.githubusercontent.com/7517235/29450676-e7e82782-83ff-11e7-9f34-de179cf1c8d1.PNG)
IE 11 : 
![002](https://user-images.githubusercontent.com/7517235/29450683-f102d402-83ff-11e7-9eb7-03f8cdb4e53e.PNG)

**Comment by mattlewis92** [comment]
Oh thats weird, does this demo work for you in IE11 (sorry I have a mac so cant try myself): https://mattlewis92.github.io/angular-calendar/#/async-events

**Comment by FARHANE** [comment]
Yes it works

**Comment by mattlewis92** [comment]
Ah OK, maybe it's just a bug with zone's or whatever not triggering change detection. If you use the manual refresh option to force re-rendering of the view does it work? https://mattlewis92.github.io/angular-calendar/#/refreshing-the-view

**Comment by FARHANE** [comment]
Thanks a lot but still have the same problem.

**Comment by FARHANE** [comment]
Component : 
```
ngOnInit() {
    this.events$ = this.http
      .get('URL')
      .map(res => {
        return this.getSessionFromResponse(res.json());
      }
      );
  }
getSessionFromResponse(response) {
    let sessionEvents = [];
    for (let session of response[0].sessions) {
      sessionEvents.push({
        title: session.titre,
        start: new Date(session.dateEffet),
        end: new Date(session.dateEffet),
        color: colors.yellow,
      });
    }
    return sessionEvents;
  }
refreshView(): void {
    this.refresh.next();
  }
```
Template : 
```

  <button (click)="refreshView()">refresh</button>
  <div *ngIf="events$ | async; else loading; let events">
  <div [ngSwitch]="view">
    <mwl-calendar-month-view
      *ngSwitchCase="'month'"
      [viewDate]="viewDate"
      [events]="events"
      [activeDayIsOpen]="activeDayIsOpen"
      (dayClicked)="dayClicked($event.day)"
      (eventClicked)="eventClicked($event.event)">
    </mwl-calendar-month-view>
    <mwl-calendar-week-view
      *ngSwitchCase="'week'"
      [viewDate]="viewDate"
      [events]="events"
      (eventClicked)="eventClicked($event.event)">
    </mwl-calendar-week-view>
    <mwl-calendar-day-view
      *ngSwitchCase="'day'"
      [viewDate]="viewDate"
      [events]="events"
      (eventClicked)="eventClicked($event.event)">
    </mwl-calendar-day-view>
  </div>
</div>
</div>
<ng-template #loading>
  <div class="text-center">
    <i class="fa fa-spin fa-spinner fa-5x"></i>
    <br>
    Loading events...
  </div>
</ng-template>
```

**Comment by mattlewis92** [comment]
I need an actual runnable plunker please that I can use to debug what's going on, thanks!

**Comment by FARHANE** [comment]
Hello,
Sorry I can not :(

**Comment by FARHANE** [comment]
just an other remark, when I use your url "https://api.themoviedb.org/3/discover/movie" its work perfeclty in IE 11, you think it's something wrong with my service ?
![001](https://user-images.githubusercontent.com/7517235/29518206-bdaf95ba-8678-11e7-9143-188a73ec52b8.PNG)

**Comment by mattlewis92** [comment]
I have no idea I'm afraid, if you do a regular http request to your API with angular are you able to log the output to the console?

**Comment by FARHANE** [comment]
yes I am able to log the output correctly.

**Comment by mattlewis92** [comment]
Ah ok, it's probably not an issue with your API then. I'm afraid without a runnable plunker it's impossible for me to really know what's happening. Happy to dig in more for you though if you can provide one for me 😄

**Comment by ryangeorgebrown** [comment]
I had this same issue and the culprit was the start date, in the example docs you are using new Date(), this will always work in IE,  but when I started using dates from my API I began to have issues with IE.  I solved this by using moment.js to format the date from my api and once this was formtted with moment the month view began showing dates.  moment(obj.eventDueDate).toDate()

**Comment by kalyanik9** [comment]
I have same issue not able to show events in week view in internet explorer and edge browser.

**Comment by stex1984** [comment]
Hello, on ie11 loading async is not working. Your demo show always loading div on ie11. In my app, i call refresh.next() after updating my object events array after get http call, that pass on input of mwl-calendar-week-view on [events]="eventi" and [refresh]="this.refresh.asObservable()", but ie11 not render events and crash. Same code works fine on Chrome.

**Comment by jaganchoccy** [comment]
event.returnValue = false;
![image](https://user-images.githubusercontent.com/37062981/74633997-f9d53100-5130-11ea-9778-2428307e011b.png)
