### ISSUE TITLE
Build error: Error in bail mode: [at-loader] node_modules\calendar-utils\dist\calendar-utils.d.ts:31:41     TS1005: ',' expected.

### ISSUE THREAD

**Issue by alex7egli** [mattlewis92/angular-calendar#314]
## I'm submitting a ...

<pre>
[ ] Bug report 
[ ] Feature request
[* ] Documentation issue or request
[ ] Support request => Please do not submit a support request here, please ask on https://stackoverflow.com/
</pre>

### Bug description / Feature request
I'm using webpack to build my project, typescript 2.2.2. When I run build after including the calendar in my project I get this error:
https://github.com/mattlewis92/angular-calendar/tree/master/build-tool-examples

Is webpack supported as a build tool? I didn't see any examples for it in the build examples folder, but it's such a prominent dev tool that I thought you just didn't need to include an example for it since you basic steps of including it in a module should be sufficient.

### Minimal reproduction of the problem with instructions
* Run npm install --save angular-calendar, in an angular2 project using webpack to build
* Run webpack
* Expected project to build correctly, instead saw build error above

### Versions

Angular: 4.0.0

Calendar library: 0.20.1

Webpack: 2.2.1

Typescript: 2.2.2

Browser name and version: N/A

**Comment by mattlewis92** [comment]
Hi there, you need to upgrade your typescript version to v2.3 as this lib uses features only supported in that version of typescript.

**Comment by alex7egli** [comment]
Thanks, I ran npm list --depth=0 and found the warning. Upgraded to 2.3.4 and all is good!
