### ISSUE TITLE
Option to have a current hour pointer

### ISSUE THREAD

**Issue by df-gvasconcelos** [mattlewis92/angular-calendar#317]
## I'm submitting a ...

<pre>
[ ] Bug report 
[ ] Feature request
[X] Documentation issue or request
[ ] Support request => Please do not submit a support request here, please ask on https://stackoverflow.com/
</pre>

### Bug description / Feature request

I'd be great to have a way to highlight (red bottom, or green background or something else) the current hour. Like Google Calendar does. It doesn't need to be minute specific I believe, but it'd be great to have current half-hour block highlighted somehow.

If there is already a way to select via CSS or something, please let me know. I couldn't find a way.

Good job on this Calendar. I appreciate it.

**Comment by mattlewis92** [comment]
Hi there, you can implement this via the `beforeViewRender` output. I've put together a demo of how to do this here: http://plnkr.co/edit/4ink65f9L1Z1CbUJnqRx?p=preview Hope that helps! 😄

**Comment by df-gvasconcelos** [comment]
Excellent! Thanks @mattlewis92
