### ISSUE TITLE
dayClicked called on event click Month View

### ISSUE THREAD

**Issue by guilhermerecife** [mattlewis92/angular-calendar#318]
## I'm submitting a ...

<pre>
[x] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit a support request here, please ask on https://stackoverflow.com/
</pre>

Angular-Calendar Version : 0.20
I have differents events to eventClicked and dayClicked but when I click on event both are triggered. I think it would be eventClicked triggered only.

### Versions

Angular: 4.1.3

Calendar library: 0.20

Browser name and version: Opera 47.0

**Comment by mattlewis92** [comment]
Are you using hammerjs by any chance?

**Comment by guilhermerecife** [comment]
Yes, hammerjs  2.0.8

**Comment by mattlewis92** [comment]
Ah, finally found a fix for this, will cut a new release shortly 😄

**Comment by guilhermerecife** [comment]
:D thanks

**Comment by mattlewis92** [comment]
Released as 0.21.0, let me know if that works ok for you 😄

**Comment by guilhermerecife** [comment]
It' work fine now. Thanks a lot!

**Comment by quangtvdevnet** [comment]
Hi,

I still have this issue.
Please let me know how to fix it

**Comment by guilhermerecife** [comment]
Uptade to latest version, for me it works when i update.

**Comment by quangtvdevnet** [comment]
Hmm, In my side when I use custom event template, the issue is still exists.
I just did a work around to fix this. I used a typescript variable to check whether or not the event is actually clicked
