### ISSUE TITLE
Provide a decent demo site that matches the ng1 version

### ISSUE THREAD

**Issue by mattlewis92** [mattlewis92/angular-calendar#32]
- [x] Kitchen sink
- [x] Optional event end dates
- [x] Editable / deletable events
- [x] Draggable events
- [x] Resizable events
- [x] Badge total
- [x] Recurring events
- [x] Custom event class
- [x] Clickable events
- [x] Timespan click
- [x] Day view start and end time
- [x] Day view minute split
- [x] Navigating between views
- [x] Cell modifier
- [x] Internationalisation
- [x] Draggable external events
- [x] All day events
- [x] Change date formats
- [x] Show dates on event titles
- [x] Disable tooltips
- [x] Async events -> https://api.themoviedb.org/3/discover/movie?primary_release_date.gte=2017-01-01&primary_release_date.lte=2017-02-01&api_key=0ec33936a68018857d727958dca1424f
- [x] Additional event properties
- [x] Selectable month view day

**Comment by mattlewis92** [comment]
Also need a nice recurring events example that uses the rrule lib to generate recurring events (although this won't be in the core of the calendar)

**Comment by thomasjosephgreco** [comment]
I referenced this in #41. My apologies for not seeing that before hand! Anyways, let me know if you'd like me to host the site!

**Comment by mattlewis92** [comment]
Need to also document how to use this module with all the popular build tools - webpack / system / rollup

**Comment by krisklosterman** [comment]
Yea I am having trouble getting it working with a webpack project :/

**Comment by mattlewis92** [comment]
What kind of problems are you having? There is now a full set of examples here for all popular build tools: https://github.com/mattlewis92/angular-calendar/tree/master/examples

**Comment by krisklosterman** [comment]
Getting errors like

`XCEPTION: Uncaught (in promise): Error: Error in ./EventCalendarComponent class EventCalendarComponent - inline template:2:2 caused by: Cannot read property 'filter' of undefined
TypeError: Cannot read property 'filter' of undefined
    at getEventsInPeriod (http://localhost:4200/main.bundle.js:82910:18)
    at getMonthView (http://localhost:4200/main.bundle.js:82983:25)
    at CalendarMonthViewComponent.refreshBody (http://localhost:4200/main.bundle.js:84123:112)
    at CalendarMonthViewComponent.ngOnChanges (http://localhost:4200/main.bundle.js:84094:18)
    at Wrapper_CalendarMonthViewComponent.detectChangesInInputProps (/CalendarModule/CalendarMonthViewComponent/wrapper.ngfactory.js:95:20)
    at _View_EventCalendarComponent0.detectChangesInternal (/AppModule/EventCalendarComponent/component.ngfactory.js:45:44)
    at _View_EventCalendarComponent0.AppView.detectChanges (http://localhost:4200/main.bundle.js:60364:14)
    at _View_EventCalendarComponent0.DebugAppView.detectChanges (http://localhost:4200/main.bundle.js:60469:44)
    at _View_EventCalendarComponent_Host0.AppView.detectViewChildrenChanges (http://localhost:4200/main.bundle.js:60390:19)
    at _View_EventCalendarComponent_Host0.detectChangesInternal (/AppModule/EventCalendarComponent/host.ngfactory.js:33:8)`

I installed angular-calendar
I loaded it in my app.module.ts

`import { CalendarModule } from 'angular-calendar';`

and 

`CalendarModule.forRoot() -- in imports`

then I added the

`viewDate: Date = new Date();
events = [];`

to my component class

and added 

`<mwl-calendar-month-view
  [viewDate]="viewDate"
  [events]="events">
</mwl-calendar-month-view>`

to my html for the component

**Comment by krisklosterman** [comment]
I got it kind of working with the examples you provided. In your examples you do not include the CSS file though?

**Comment by mattlewis92** [comment]
It is included, just buried a bit due to the nuances of the tooling
https://github.com/mattlewis92/angular-calendar/blob/master/examples/rollup/app/app.component.ts#L1

https://github.com/mattlewis92/angular-calendar/blob/master/examples/angular-cli/angular-cli.json#L21

https://github.com/mattlewis92/angular-calendar/blob/master/examples/systemjs/index.html#L7

**Comment by krisklosterman** [comment]
Which was is more supported, the way you have it done in your angular-cli example. Or the way I attempted it by doing an import at the top of the styles.css file

`@import url('../node_modules/angular-calendar/dist/css/angular-calendar.css');`

**Comment by mattlewis92** [comment]
I'm not too familiar with the CLI but I'd say that both are probably equal.

**Comment by gaurav517** [comment]
I am trying your demo but getting a problem. I posted the question on stackoverflow:

http://stackoverflow.com/questions/40580297/404-when-a-js-file-requires-another-js-file-without-js-extension

Can you please have a look. Thanks a lot..
