### ISSUE TITLE
Background color for individual columns in month view

### ISSUE THREAD

**Issue by simandi434** [mattlewis92/angular-calendar#320]
Hello,

How to set background color for Fryday and Saturday column in month view.

Thank you.

![calendarsnip](https://user-images.githubusercontent.com/20299297/29935146-64c64ee6-8e9b-11e7-924e-a08b34c62caf.PNG)

**Comment by mattlewis92** [comment]
You can use some creative CSS to get this effect:
```
.cal-month-view .cal-days .cal-cell-row :nth-child(6),
.cal-month-view .cal-days .cal-cell-row :nth-child(7) {
  background-color: #dfe0e1;
}
```

Demo:
http://plnkr.co/edit/KBhowJVluqSKvlRwnj1J?p=preview

Alternatively you could use the [`beforeViewRender`](https://mattlewis92.github.io/angular-calendar/#/before-view-render) hook to add a css class to those days.

Hope that helps! 😄

**Comment by simandi434** [comment]
@mattlewis92 ,

Its changing all the columns background color when i am trying to do that for Sunday, Fryday and Saturday.
I tried like,
.cal-month-view .cal-days .cal-cell-row :nth-child(1),
.cal-month-view .cal-days .cal-cell-row :nth-child(6),
.cal-month-view .cal-days .cal-cell-row :nth-child(7) {
  background-color: #dfe0e1;
}
Its working fine for all other columns but only creating mess with sunday.
Thank you.

**Comment by mattlewis92** [comment]
That's weird, maybe its a bug with chrome? This seems to work though:

```
.cal-month-view .cal-days .cal-cell-row .cal-cell:nth-child(1),
.cal-month-view .cal-days .cal-cell-row .cal-cell:nth-child(6),
.cal-month-view .cal-days .cal-cell-row .cal-cell:nth-child(7) {
        background-color: #dfe0e1;
}
```

http://plnkr.co/edit/KBhowJVluqSKvlRwnj1J?p=preview

**Comment by simandi434** [comment]
Its working with .cal-cell before nth-child(1).

Thank you.
