### ISSUE TITLE
Console error: this.engine.setProperty is not a function

### ISSUE THREAD

**Issue by craftpip** [mattlewis92/angular-calendar#321]
## I'm submitting a ...

<pre>
[x] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit a support request here, please ask on https://stackoverflow.com/
</pre>

### Bug description / Feature request
This does not impact the functionality of the plugin, however
When clicking on date to open the kitchen sink, this error appears in console. 
![image](https://user-images.githubusercontent.com/4782473/30001184-e91e1200-90a3-11e7-86af-e3412979965a.png)
I obviously must have missed something, please correct me.

### Minimal reproduction of the problem with instructions
Minimal setup shown in the documentation, 
Also i've tried importing NoopAnimationsModule or BrowserAnimationsModule but same error

### Versions

Angular: 4.2.5
Calendar library: 0.21.1
Browser name and version: Chrome Version 60.0.3112.113 (Official Build) (64-bit) Windows

Thank you, this is a great plugin!

**Comment by mattlewis92** [comment]
It looks like a bug with angular itself, googling that error returns the same issue for lots of libraries. It seems like upgrading to the latest angular will fix it for you: https://stackoverflow.com/questions/45116240/getting-type-error-using-angular-material

**Comment by craftpip** [comment]
Thank you, that solved the problem! 👍
