### ISSUE TITLE
Multiple months in page

### ISSUE THREAD

**Issue by maxborgatti** [mattlewis92/angular-calendar#322]
Is it possible to place e.g. three months in a page? I did give it a try adding multiple mwl-calendar-month-view but with no luck

i did post same question (my mistake) here: https://github.com/mattlewis92/angular-bootstrap-calendar/issues/641#issuecomment-325780051

i'm looking for any similar solution typescript/ang4 based

thanks in advance for any help on this

**Comment by mattlewis92** [comment]
You could probably create a virtualised scrolling component that dynamically renders month views from this library as the user scrolls. However it's outside of the scope of this calendar as its [primarily aimed at desktop users](https://github.com/mattlewis92/angular-calendar#does-this-calendar-work-with-mobile).
