### ISSUE TITLE
Display hours in week view

### ISSUE THREAD

**Issue by baptistecosta** [mattlewis92/angular-calendar#323]
Is there a way I can display hours in the week view? Basically I want the same as day view but from monday to sunday.

Something like that:
![image](https://user-images.githubusercontent.com/6499062/30151249-f4404636-93ae-11e7-870e-54e9bb258099.png)

**Comment by mattlewis92** [comment]
Sorry there is no baked in support for this, but you could use pieces from this calendar to build your own replacement week view that works the way you want it to: https://github.com/mattlewis92/angular-calendar/issues/319#issuecomment-325914732
