### ISSUE TITLE
Month view - limit to one week

### ISSUE THREAD

**Issue by mmackiew** [mattlewis92/angular-calendar#324]
<pre>
[ ] Bug report
[X] Feature request
[ ] Documentation issue or request
[ ] Support request
</pre>

### Bug description / Feature request
I'd like to use monthly view of calendar but present only selected week.
Example for w26 y2017 calendar should look like this:
![mojawsb - ionic lab 2017-09-08 08-04-08](https://user-images.githubusercontent.com/3731133/30198248-f9e773ca-946c-11e7-8711-4108d64d8c03.png)
I can't find any feature like this. I can't find any template to use to get this. I can hide cells but empty row is still visible even if hide min-height css property.

Using it in ionic2 framework.

Thanks for any help.

**Comment by mattlewis92** [comment]
In the same way that you can [add extra weeks](https://mattlewis92.github.io/angular-calendar/#/extra-month-view-weeks) you can take them away as well. Demo here: http://plnkr.co/edit/GEixSfhlRjQTXkfmkCcj?p=preview Hope that helps! 😄

**Comment by mmackiew** [comment]
Thanks.

**Comment by jphearse** [comment]
In my calendar I have a day, week, and month view. Is there a way to use this limited month view as my week view instead, while still having the option to view the full month view?

**Comment by habib786** [comment]
Can I remove extra weeks and days from the calendar? I only want to show single month calendar, now past month's weeks and days!

**Comment by mattlewis92** [comment]
You could use the `cal-out-month` css selector to hide the contents of these days, something like:
```
.cal-out-month {
  .cal-cell-top,
  .cal-events {
    display: none;
  }
}
```

**Comment by chitgoks** [comment]
With this solution, is it possible to only apply this for a specific month view component? e.g. i have 2 month view components. 1 is full month view, while the other is this month view per week.
