### ISSUE TITLE
January 2018 starts on the wrong date

### ISSUE THREAD

**Issue by keeperofchem** [mattlewis92/angular-calendar#325]
## I'm submitting a ...

<pre>
[ x ] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit a support request here, please ask on https://stackoverflow.com/
</pre>

### Bug description / Feature request

January 1st, 2018 and December 31st, 2017 appear on the same date, all dates appearing after December 31st, 2017 need to be shifted over. 

### Versions

Angular: 4.3.0

Calendar library: 0.21.2

Browser name and version: Chrome

**Comment by mattlewis92** [comment]
Hi, I'm not able to reproduce this, are you able to share a plunker / screenshot of what you mean? Also what timezone are you in?

<img width="1371" alt="screen shot 2017-09-09 at 10 13 17" src="https://user-images.githubusercontent.com/6425649/30238841-8a28e31c-9547-11e7-87b3-33c9a8bd688f.png">

**Comment by keeperofchem** [comment]
Hi, upon further inspection of your demo, it is actually user error on my part. Instead of using the mwlCalendarNextView directive, I had written my own logic (incrementing/decrementing the month and year). Sorry for the confusion.
