### ISSUE TITLE
dayClicked event not allways working

### ISSUE THREAD

**Issue by FallenRiteMonk** [mattlewis92/angular-calendar#326]
## I'm submitting a ...

<pre>
[X] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit a support request here, please ask on https://stackoverflow.com/
</pre>

### Bug description / Feature request
Having the following montView and open day tmplate:
```
<mwl-calendar-month-view *ngSwitchCase="'month'" [headerTemplate]="headerTemp" [openDayEventsTemplate]="openDayEventsTemplate"
          [weekStartsOn]="1" [viewDate]="viewDate" [events]="events" [refresh]="refresh" [activeDayIsOpen]="activeDayIsOpen"
          (dayClicked)="dayClicked($event.day)"></mwl-calendar-month-view>

<ng-template #openDayEventsTemplate>
        <div *ngFor="let event of viewDateEvents" (click)="handleEvent(event)">
          <span class="cal-event" [style.background-color]="event.color.primary"></span>
          <a class="cal-event-title bold">{{ event.title }}</a>
          <small *ngIf="!event.allDay">{{ event.start | amDateFormat: getAmDateFormat(event.start) }} - {{ event.end | amDateFormat: getAmDateFormat(event.end) }}</small>
          <small *ngIf="event.allDay">{{ 'BOARD.APPOINTMENTS.CALENDAR.ALL_DAY' | translate }}</small>
        </div>
      </ng-template>
```
It sometimes happens that clicking on a day does not fire the dayClicked event.

CAUTION: im using ionic!!! version bellow.
This only seems to be happening on android. Version info below.

### Minimal reproduction of the problem with instructions
Opening the calendar view, clicking on 1. Oct:
![screenshot_20170909-134403](https://user-images.githubusercontent.com/8779846/30239997-25967600-9568-11e7-884a-eae2202eac8e.png)

and then clicking on a day that has some events:
![screenshot_20170909-134433](https://user-images.githubusercontent.com/8779846/30240000-3494efe2-9568-11e7-8b00-eae10b457da3.png)

the open day event is not fired and open day eventstemplate is not shown.
Then clicking on a other day proves that it does work normally:
![screenshot_20170909-140208](https://user-images.githubusercontent.com/8779846/30240016-63074fc8-9568-11e7-9661-b4fd23fd5f57.png)

### Versions

Angular:  4.1.3

Calendar library: 0.21.2

Browser name and version: Chrome Mobile 60.0.3112

Ionic info command output:
```
cli packages: (<PROJECT_PATH>/app/node_modules)

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 7.0.1 

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : android 6.2.3 ios 4.4.0
    Ionic Framework    : ionic-angular 3.6.1

System:

    Android SDK Tools : 26.0.2
    Node              : v6.11.2
    npm               : 5.4.0 
    OS                : Linux 4.12
```

**Comment by mattlewis92** [comment]
As this only occurs intermittently on android for you, it sounds like a bug with the actual browser itself rather than anything this library is doing. I know on a lot of android devices the stock browsers are pretty buggy, maybe give [crosswalk](https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview) a try and see if it fixes it for you.
