### ISSUE TITLE
Available dates

### ISSUE THREAD

**Issue by ptauk** [mattlewis92/angular-calendar#327]
## I'm submitting a ...
<pre>
[ ] Bug report 
[X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit a support request here, please ask on https://stackoverflow.com/
</pre>

### Feature request
I want to create a day view that shows only times that have no events. So times that have an event are greyed out (disabled) and times that are available are white. Is it possible to create a day view that is this or something similar?

### Versions

Angular: 4.0.2

Calendar library: 0.13.5

Browser name and version: Chrome 59.0.3071.115

**Comment by mattlewis92** [comment]
You can use the `beforeViewRender` output to add a `cssClass` to rows on the calendar like so: http://plnkr.co/edit/4ink65f9L1Z1CbUJnqRx?p=preview

**Comment by ptauk** [comment]
That worked very nicely. Thanks for the quick response.
