### ISSUE TITLE
CSS for two Calendars in same project

### ISSUE THREAD

**Issue by simandi434** [mattlewis92/angular-calendar#328]
Hello @mattlewis92,

How to apply different css styles for two different calendars in same project.?

I have two different calendars in same project. I have used two different components for two calendars. But I can able to apply only one css file for them. 

Kindly let me know applying different css styles for different calendars.

**Comment by mattlewis92** [comment]
You can workaround this by adding a class to the calendar component:
```html
<mwl-calendar-month-view class="calendar-1"></<mwl-calendar-month-view>
<mwl-calendar-month-view class="calendar-2"></<mwl-calendar-month-view>
```

```css
.calendar-1 {
  // calendar one styles
}

.calendar-2 {
  // calendar two styles
}
```
