### ISSUE TITLE
Database for backend info

### ISSUE THREAD

**Issue by azmatzuberi** [mattlewis92/angular-calendar#329]
## I'm submitting a ...

<pre>
[ ] Bug report 
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit a support request here, please ask on https://stackoverflow.com/
</pre>

### Bug description / Feature request
What and where is the database for this located. I saw code referring to lite-server but where are the dates, timings, etc located? I checked the plunker, but couldn't find the backend.

I am a bit new to Angular, so excuse my ignorance.

### Versions

Angular: 4

Calendar library: 

Browser name and version: Chrome 60.0.3112.113 (Official Build) (64-bit)

**Comment by mattlewis92** [comment]
This is just a UI component for displaying events, there isn't a backend part to this. You have to load the events yourself from an API via the angular http service. You can see an example of how to do that here: https://mattlewis92.github.io/angular-calendar/#/async-events
