### ISSUE TITLE
Allow to hide previous/next month days in month view

### ISSUE THREAD

**Issue by dgadelha** [mattlewis92/angular-calendar#330]
## I'm submitting a ...
<pre>
[ ] Bug report 
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit a support request here, please ask on https://stackoverflow.com/
</pre>

### Bug description / Feature request
It would be nice if we could hide the days of previous and next months in the month view.

Something just like that (made on Paint):

![image](https://user-images.githubusercontent.com/10081640/30480333-a4830c9a-99ef-11e7-973e-964a75ddfa25.png)

Extra question: is it possible to disable all those unnecessary hover effects in calendar without messing up with styles?

### Additional details

Tried to do something related to [this](https://mattlewis92.github.io/angular-calendar/#/extra-month-view-weeks):

```
export class MyCalendarUtils extends CalendarUtils {
    getMonthView(args: GetMonthViewArgs): MonthView {
        args.viewStart = startOfMonth(args.viewDate);
        args.viewEnd = endOfMonth(args.viewDate);
        return getMonthView(args);
    }
}
```

But no luck.

### Versions

Angular: 4.3.6

Calendar library: 0.21.2

Browser name and version: Mozilla Firefox 57.0a1

**Comment by mattlewis92** [comment]
You can do this with CSS:
```
.cal-out-month .cal-cell-top {
  display: none;
}
```

Plunker: http://plnkr.co/edit/nEZZnr4DFyt5bnGkNPPR?p=preview

**Comment by Littlesingh** [comment]
can't we add any setting like  showNonCurrentDates=false kind off
