### ISSUE TITLE
Focus in a particular day with a event ?

### ISSUE THREAD

**Issue by lmichailian** [mattlewis92/angular-calendar#331]
Hi! 

Can open detail and focus in a particular day with a event (in month view) ? 

Thanks!

Versions

Angular: 4.2.2

Calendar library: 0.21.0

Browser name and version: Chrome

**Comment by mattlewis92** [comment]
You can do this by setting the `viewDate` input to the day you want to open and the `activeDayIsOpen` input to true. You can see this in action on the demo: https://mattlewis92.github.io/angular-calendar/#/kitchen-sink
