### ISSUE TITLE
Styles and components fail

### ISSUE THREAD

**Issue by agustin18** [mattlewis92/angular-calendar#332]
## I'm submitting a ...

<pre>
[ ] Bug report 
[ X ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit a support request here, please ask on https://stackoverflow.com/
</pre>

### Bug description / Feature request
Sorry for my level of English and programming, I am very new to both. My problem is I can't replicate the behavior of Kitchen Sink. I don't know what I'm doing wrong, since I've been reading the demonstrations for several hours and I'm sorry to be useless. Please if you can help me, I'll send you a capture of what it looks like. I add the css file to index.html

[https://image.prntscr.com/image/vqSIdjVNQTu2eBQvfQDhQQ.png](url)
[https://image.prntscr.com/image/MT5OdcvZSzaFtpkeJha3Pg.png](url)

### Versions

Angular: 4

Calendar library:  angular-calendar

Browser name and version:  Firefox Lastest

**Comment by mattlewis92** [comment]
You're getting this issue as the demo uses bootstraps styles, however it's designed not to be tied to any particular framework and adapt to your apps styles. Including the bootstrap css should do the trick for you: https://getbootstrap.com/
