### ISSUE TITLE
help me plz, mwlCalendarPreviousView && mwlCalendarNextView not work for me

### ISSUE THREAD

**Issue by chavachons** [mattlewis92/angular-calendar#333]
<img width="757" alt="screen shot 2560-09-16 at 11 52 38 pm" src="https://user-images.githubusercontent.com/13815775/30514170-26af13b2-9b3a-11e7-898a-6533da3e0f43.png">
<img width="752" alt="screen shot 2560-09-16 at 11 47 09 pm" src="https://user-images.githubusercontent.com/13815775/30514114-641ae538-9b39-11e7-8323-bd8f8a90f3ba.png">

When i click "next month". The calendar shows double months not only the month that i want it to show.

**Comment by mattlewis92** [comment]
Wow that's weird, are you able to share a plunker or something similar that reproduces your issue? Thanks!

**Comment by chavachons** [comment]
http://plnkr.co/edit/xY5F815OhFhNZaMfesPP?p=preview
I try custom your plunker with my code in `domo/component.ts` and `demo/template.html` is work. But in my project not work.

**Comment by mattlewis92** [comment]
It sounds like there is an issue with your project rather than this library, more than likely there is another part of your projects code interfering with this calendar which is causing the weird behaviour you're experiencing.
