### ISSUE TITLE
Multiples start and finish times for same event

### ISSUE THREAD

**Issue by agustin18** [mattlewis92/angular-calendar#335]
## I'm submitting a ...

<pre>
[ ] Bug report 
[x ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit a support request here, please ask on https://stackoverflow.com/

### Bug description / Feature request

Hello again, in the previous problem I did not thank enough for this wonderful tool and the help provided.

Today I have another problem, I want my events to have two start times and two end times like turns. I don't know if this can be possible without modifying the API.

I apologize for the ignorance and show captures.

Here I reused the components but as it is the same, if I modify the end time of one, the other is modified as well.

Thank you

### Minimal reproduction of the problem with instructions

https://image.prntscr.com/image/5aNv2k-0Rc6-jTZ_3vDGRg.png

https://image.prntscr.com/image/X_7sTuV5QBKjpP4H35Zu_w.png

**Comment by mattlewis92** [comment]
One of the core assumptions of this calendar is that an event has a defined start and optional end time. Adding multiple start / end times is non trivial and would require the entire lib to be rewritten. What you could do though is duplicate events and give them the same title so they would appear as one.
