### ISSUE TITLE
Events title on month view instead of badges

### ISSUE THREAD

**Issue by juanpicuervo** [mattlewis92/angular-calendar#336]
## I'm submitting a ...
<pre>
[ ] Bug report 
[X] Feature request
[ ] Documentation issue or request
[ ] Support request

### Feature request
Hello, is there any possibility to show in calendar month view the title of the events instead of the badges? And also make then clickeable?

Thanks for this awesome tool

**Comment by mattlewis92** [comment]
You could probably do this with a custom month cell template: https://mattlewis92.github.io/angular-calendar/#/custom-templates

**Comment by niraj-avya** [comment]
![image](https://user-images.githubusercontent.com/61489474/76405508-3e5d9080-63ae-11ea-82bb-e05e77a21b29.png)
How to show this type of Tittle Please Help me

**Comment by freelancers2020** [comment]
Hi,

Can u pls help me for displaying the events titles instead of badges in month view ????
