### ISSUE TITLE
List of browser compatibility?

### ISSUE THREAD

**Issue by RGTGT** [mattlewis92/angular-calendar#337]
## I'm submitting a ...
<pre>
[ ] Bug report 
[ ] Feature request
[x ] Documentation issue or request
[ ] Support request => Please do not submit a support request here, please ask on https://stackoverflow.com/
</pre>

### Bug description / Feature request
I think the component is compatible with evergreen browsers and recent versions of IE. It would seem that it's not compatible IE9. 
It would be nice to have a list of browsers this component intent to support.

**Comment by mattlewis92** [comment]
Good point, its anything that supports flexbox which is basically IE10+. It may be possible to use a flexbox polyfill to make it work in IE9 but it's not something I've ever tried: https://github.com/jonathantneal/flexibility
