### ISSUE TITLE
next seven days view ?

### ISSUE THREAD

**Issue by lmichailian** [mattlewis92/angular-calendar#338]
## I'm submitting a ...

<pre>
[ ] Bug report 
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit a support request here, please ask on https://stackoverflow.com/
</pre>

### Bug description / Feature request
A custom week view with a next seven days starting to current day, and when next or previous clicked change current day selection, is this posible ? 

@mattlewis92 I Can build this but I need some guide 

### Versions

Angular:  4.2.2 

Calendar library:  0.21.2

Browser name and version: MacOS 10  Versión 60.0.3112.113 (Build oficial) (64 bits)

**Comment by mattlewis92** [comment]
Sorry this isn't possible with the current API, the week view is designed with the assumption of a week having 7 days. The easiest way to do this would just be to build a completely custom week view separate from this library.
