### ISSUE TITLE
Is there a way to add a new column on monthly view?

### ISSUE THREAD

**Issue by paulogr** [mattlewis92/angular-calendar#339]
I'm trying to add a new column to the monthly view without success.

Anyone know how to accomplish that?

It's like one new column on the beginning of each week.

Thank you!

**Comment by mattlewis92** [comment]
You could extend the month view component to add a custom column in the root component template, I threw this together quite quick but hopefully you get the idea 😄 http://plnkr.co/edit/utxkgrjgS7pCJnwYBhhD?p=preview
