### ISSUE TITLE
[npm link issue] has anyone managed to npm link this project on a angular-cli base ?

### ISSUE THREAD

**Issue by RenaudROHLINGER** [mattlewis92/angular-calendar#340]
<pre>
[ ] Bug report 
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit a support request here, please ask on https://stackoverflow.com/
</pre>

Hello,

I'm trying hard to link angular-calendar on my angular-cli projet but it's been now 2 days and i got a lots of problems with peerDependencies, webpack, dependencies versions compatibility, export and lots of not fun stuff.

I tried to follow the instructions on the angular-cli wiki, with no success : 
https://github.com/angular/angular-cli/wiki/stories-linked-library

(If the projet is not an angular-cli base and you managed to npm link angular-calendar, I'm also interested in)

Errors examples :
`
scripts.bundle.js:2 Uncaught SyntaxError: 
Unexpected token export -->
export * from './providers/calendarEventTitleFormatter.provider';
`
or
`Uncaught Error: Unexpected value '[object Object]' imported by the module 'AppModule'. Please add a @NgModule annotation. (CalendarModule)`

So if someone have an idea on how to npm link, i would appreciate a lot.

Otherwise i will just import all the files in my project...

Angular: 4.4.3
Angular-calendar: 0.21.2
Typescript: 2.5.2

**Comment by mattlewis92** [comment]
I’ve tried to do something similar before in the past and couldn’t get it to work properly either, this lib doesn’t do anything particularly special so I don’t think there’s anything actionable here, I think the issues is cli/webpack related. 

I’m curious as to why you need to link the project into your own? The API is designed so you can customise pretty much every part of the calendar so you shouldn’t need to fork any of it. Happy to give pointers if you’re struggling 😀

**Comment by RenaudROHLINGER** [comment]
Yeah the ng-template is a really nice feature to customise the calendar.
The problem is that I would like to add dayStartHour and dayEndHour and hourSegments on the week and month view. Furthemore, i would like to add the possibility to show a view of 3 days.

If you had any advice on how to do that properly on your librairy, that could be really cool !

**Comment by mattlewis92** [comment]
Ah ok, that sounds like quite a deviation indeed from the core. When I built this I deliberately extracted most of the business logic out into separate modules (which are dependencies of this lib) so you may find some of them useful in building a custom component that implements your needs. You could also use es6 class inheritance to extend the root components and use a completely custom template for the month and week views. Here is a very basic example of how to do this that I built the other day for another issue: http://plnkr.co/edit/utxkgrjgS7pCJnwYBhhD?p=preview

**Comment by RenaudROHLINGER** [comment]
Ok, thank you, that help me a lot !
