### ISSUE TITLE
Display Hour Segments in weekview

### ISSUE THREAD

**Issue by shaolinshaosson** [mattlewis92/angular-calendar#341]
## I'm submitting a ...

<pre>
[ ] Bug report 
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit a support request here, please ask on https://stackoverflow.com/
</pre>

### Bug description / Feature request

I'v been scanning the docs to find out if it's possible to display hours for the whole day in week-view (like fullcalendar.io in week-view) but can't find that feature/setting, have I missed something or is it not currently possible?
If not, do you plan to implement it in the near future?

**Comment by mattlewis92** [comment]
Sorry there is no support for this, but you could use pieces from this calendar to build your own replacement week view that works the way you want it to: https://github.com/mattlewis92/angular-calendar/issues/319#issuecomment-325914732
