### ISSUE TITLE
open-events panel remains opened in month view

### ISSUE THREAD

**Issue by grreeenn** [mattlewis92/angular-calendar#342]
## I'm submitting a ...

<pre>
[x ] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit a support request here, please ask on https://stackoverflow.com/
</pre>

### Bug description
In month view, when switching months, open-events panel remains opened under the same row that it was on the previous month, even if there are no more events to show. 

### Minimal reproduction of the problem with instructions
Go to the Kitchen Sink demo, select one of the days that have events, go to next month - you'll see an empty brown stripe in the middle of the calendar

### Versions

Angular: 4.3.6

Calendar library: 0.21.2

Browser name and version: Chrome 61.0.3163.100, FF 55.0.3

![image](https://user-images.githubusercontent.com/13204857/30973057-d869cf6e-a474-11e7-930f-ebae9274d376.png)

**Comment by mattlewis92** [comment]
Oops, fixed. Thanks for reporting!
