### ISSUE TITLE
Problem on resoliving angular-calendar.scss in the module

### ISSUE THREAD

**Issue by Himura59** [mattlewis92/angular-calendar#343]
## I'm submitting a ...

<pre>
[ ] Bug report 
[ x ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit a support request here, please ask on https://stackoverflow.com/
</pre>

### Bug description / Feature request

I'm getting an error while compiling : 
<pre>
ERROR in ./~/angular-calendar/dist/esm/src/index.umd.js
Module not found: Error: Can't resolve './../scss/angular-calendar.scss' in 'C:\git\IPPS-App\frontend\professional\node_modules\angular-calendar\dist\esm\src'
 @ ./~/angular-calendar/dist/esm/src/index.umd.js 1:0-41
 @ ./src/app/ipps-app/ipps-shared-module/ipps-shared-module.module.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:4200 ./src/main.ts
</pre>
### Versions

Angular: 4

Calendar library: angular-calendar

Browser name and version: chrome latest

**Comment by mattlewis92** [comment]
It looks like somehow your build config is pointing to `angular-calendar/dist/esm/src/index.umd.js` instead of `angular-calendar/dist/esm/src/index.js`.
