### ISSUE TITLE
Day view with horizontal hours

### ISSUE THREAD

**Issue by Herb-sh** [mattlewis92/angular-calendar#344]
**Feature request**
Currently on Day View hours are listed vertically nevertheless horizontal hours are a pretty common use case. I was not able to find this functionality. Is it currently possible to show hours horizontally? 

  9AM  |  10 AM  |   11AM  |  12PM  |  1PM  |  2PM  |  3PM  |  4PM  |  5PM
.
.
.

If not do you see this as possible and as a potential new feature?

Thank you so much for this wonderful calendar. This is by far the most flexible and well documented calendar I have ever used. 
Cheers!

**Comment by mattlewis92** [comment]
I'm afraid there is no support for this, as it deviates so far from the UX of the provided day view. For your use case I would [recommend building a replacement day view](https://github.com/mattlewis92/angular-calendar#the-month-week-or-day-view-doesnt-meet-my-project-requirements-but-the-other-views-do) and then using the other views from this calendar for the week and month views. Sorry I couldn't be of more help! 😞

**Comment by ShaileshInfyom** [comment]
@Herb-sh any solution for that?

**Comment by diogobsb81** [comment]
no solution to date?

**Comment by harleenarora** [comment]
any solution?
