### ISSUE TITLE
Compilation issue when using --prod flag

### ISSUE THREAD

**Issue by rhino5oh** [mattlewis92/angular-calendar#345]
<pre>
[X ] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit a support request here, please ask on https://stackoverflow.com/
</pre>

### Bug description / Feature request
When doing an "ng build --prod", I get the following error:

ERROR in C:/Users/Ryan/test/src/$$_gendir/node_modules/angular-calendar/dis                                           t/esm/src/components/month/calendarMonthView.component.ngfactory.ts (15,21): Can                                           not find module './calendarOpenDayEvents.component.ngfactory'.
ERROR in C:/Users/Ryan/test/src/$$_gendir/node_modules/angular-calendar/dis                                           t/esm/src/calendar.module.ngfactory.ts (11,21): Cannot find module './directives                                           /calendarTooltip.directive.ngfactory'.
ERROR in C:/Users/Ryan/test/src/$$_gendir/node_modules/angular-calendar/dis                                           t/esm/src/components/day/calendarDayView.component.ngfactory.ts (16,21): Cannot                                            find module './calendarDayViewEvent.component.ngfactory'.
ERROR in C:/Users/Ryan/test/src/$$_gendir/node_modules/angular-calendar/dis                                           t/esm/src/components/day/calendarDayView.component.ngfactory.ts (18,21): Cannot                                            find module './calendarDayViewHourSegment.component.ngfactory'.
ERROR in C:/Users/Ryan/test/src/$$_gendir/node_modules/angular-calendar/dis                                           t/esm/src/components/month/calendarMonthView.component.ngfactory.ts (10,21): Can                                           not find module './calendarMonthCell.component.ngfactory'.
ERROR in C:/Users/Ryan/test/src/$$_gendir/node_modules/angular-calendar/dis                                           t/esm/src/components/day/calendarDayView.component.ngfactory.ts (10,21): Cannot                                            find module './calendarAllDayEvent.component.ngfactory'.
ERROR in C:/Users/Ryan/test/src/$$_gendir/node_modules/angular-calendar/dis                                           t/esm/src/components/month/calendarMonthView.component.ngfactory.ts (17,21): Can                                           not find module './calendarMonthViewHeader.component.ngfactory'.
ERROR in C:/Users/Ryan/test/src/$$_gendir/node_modules/angular-calendar/dis                                           t/esm/src/components/week/calendarWeekView.component.ngfactory.ts (14,21): Canno                                           t find module './calendarWeekViewEvent.component.ngfactory'.
ERROR in C:/Users/Ryan/test/src/$$_gendir/node_modules/angular-calendar/dis                                           t/esm/src/components/week/calendarWeekView.component.ngfactory.ts (17,21): Canno                                           t find module './calendarWeekViewHeader.component.ngfactory'.
ERROR in C:/Users/Ryan/test/src/$$_gendir/app/calendar/calendar.module.ngfa                                           ctory.ts (11,21): Cannot find module '../../../$$_gendir/node_modules/angular-ca                                           lendar/dist/esm/src/directives/calendarTooltip.directive.ngfactory'.
ERROR in C:/Users/Ryan/test/src/$$_gendir/app/app.module.ngfactory.ts (37,2                                           2): Cannot find module '../../$$_gendir/node_modules/angular-calendar/dist/esm/s                                           rc/directives/calendarTooltip.directive.ngfactory'.

**Note:**  This only occurs when doing a prod build that performs AOT compilation.  A regular "ng build" has no issues.

### Minimal reproduction of the problem with instructions
do an "ng build --prod" with the versions of angular/angular-cli listed below

### Versions
I am using version 0.21.2 of angular-calendar, and the following versions of angular/angular-cli:

angular/cli: 1.4.5
node: 6.9.5
os: win32 x64
angular/animations: 5.0.0-rc.1
angular/cdk: 2.0.0-beta.11
angular/cli: 1.4.5
angular/common: 5.0.0-rc.1
angular/compiler: 5.0.0-rc.1
angular/core: 5.0.0-rc.1
angular/forms: 5.0.0-rc.1
angular/http: 5.0.0-rc.1
angular/material: 2.0.0-beta.11
angular/platform-browser: 5.0.0-rc.1
angular/platform-browser-dynamic: 5.0.0-rc.1
angular/platform-server: 5.0.0-rc.1
angular/router: 5.0.0-rc.1
angular/compiler-cli: 5.0.0-rc.1
typescript: 2.5.3

Angular: 5.0.0-rc.1

Calendar library:  0.21.2

Browser name and version: N/A

**Comment by mattlewis92** [comment]
My gut says this is a bug with angular 5.x, as this lib works fine with AoT + angular 4.x. I will do some digging and see if I can find a related bug on the angular issue tracker.

**Comment by rhino5oh** [comment]
I was kinda thinking it may be an angular bug as well, however, the rest of
my (somewhat large) application compiles correctly.  Im only having an
issue with the calendar currently.  Thanks for looking into it!

**Comment by mattlewis92** [comment]
I believe this PR will fix it, if it’s still an issue once it’s merged and released, let me know 😀 https://github.com/angular/angular/pull/19601
