### ISSUE TITLE
Empty month view

### ISSUE THREAD

**Issue by Benkevych** [mattlewis92/angular-calendar#348]
## I'm submitting a ...

<pre>
[x] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit a support request here, please ask on https://stackoverflow.com/
</pre>

### Bug description / Feature request
No days displayed in month view, but week and day view working perfect.

### Versions

Angular: 4 

Calendar library:  0.21.2

Browser name and version: N/A

**Comment by mattlewis92** [comment]
Sorry but it's impossible to know what's going on without a plunker that reproduces your issue, happy to debug more if you can provide one. Thanks!
