### ISSUE TITLE
css class for selected date in month view

### ISSUE THREAD

**Issue by simandi** [mattlewis92/angular-calendar#349]
Hello @mattlewis92 ,

I want to add some styles to the selected date in month view. Can you provide css class for the selected date in month view.

Thank you.

**Comment by mattlewis92** [comment]
There isn't any notion of selecting dates baked into the calendar, you have to implement this yourself. You can see a demo of this here: https://mattlewis92.github.io/angular-calendar/#/selectable-month-day
