### ISSUE TITLE
Displaying specific group events

### ISSUE THREAD

**Issue by jphearse** [mattlewis92/angular-calendar#350]
Is there a way to only show a specifics groups events?

Example: 
When I click on the yellow badge, is is possible to just have only events 1 and 2 in the dropdown?
![image](https://user-images.githubusercontent.com/14226072/31392023-cbed4e50-ad9d-11e7-87dd-447d5b1faa11.png)

**Comment by mattlewis92** [comment]
You can do this with a custom slide box template: http://plnkr.co/edit/fs6KBRECl76pebgpd6pF?p=preview
