### ISSUE TITLE
Error Angular-Calendar- Uncaught TypeError: Cannot read property 'core' of undefined

### ISSUE THREAD

**Issue by victordemorais** [mattlewis92/angular-calendar#351]
Hello there i'm using angular calendar and I have a problem listed below: 
Uncaught TypeError: Cannot read property 'core' of undefined
    at webpackUniversalModuleDefinition (scripts.bundle.js:4481)
    at scripts.bundle.js:4482
webpackUniversalModuleDefinition @ scripts.bundle.js:4481
(anonymous) @ scripts.bundle.js:4482

How doing to resolve this problem? 

## I'm submitting a ...

<pre>
[ ] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit a support request here, please ask on https://stackoverflow.com/
</pre>

### Versions

Angular: 

Calendar library: 

Browser name and version:

**Comment by mattlewis92** [comment]
It sounds like your webpack config is misconfigured and is not loading this package correctly.
