### ISSUE TITLE
showTimesOnWeekView For Week View

### ISSUE THREAD

**Issue by jmrapp1** [mattlewis92/angular-calendar#353]
On the other version of this repo for Angular 1 there is a flag `showTimesOnWeekView` in the CalendarConfig that allows you to show the hourly times on the week view. I have been searching for how to do this with the Angular 4 version but can not find anything online or in the source relating to this. Is this supported?

**Comment by mattlewis92** [comment]
Sorry there's no support for this, having 2 different modes on the same view was a maintenance nightmare in the angularjs version and I didn't want to repeat that here. I would recommend just building your own week view component and using it in place of the one provided by this lib: https://github.com/mattlewis92/angular-calendar#the-month-week-or-day-view-doesnt-meet-my-project-requirements-but-the-other-views-do
