### ISSUE TITLE
Empty Event Title Bar

### ISSUE THREAD

**Issue by AustinGomez** [mattlewis92/angular-calendar#354]
## I'm submitting a ...

<pre>
[x ] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit a support request here, please ask on https://stackoverflow.com/
</pre>

### Bug description / Feature request

When the month view is loaded without any events on the current date, or you delete all the events. The grey title bar remains and is empty. Similar to https://github.com/mattlewis92/angular-calendar/issues/342

### Minimal reproduction of the problem with instructions

Open the month view with no events on the current date

OR

Delete all events for the selected date in the month view

### Versions

Angular: 4.4.1

Calendar library: 0.21.2

Browser name and version: Chrome OS X

**Comment by mattlewis92** [comment]
Please see my previous answer here that explains the reasoning for this: https://github.com/mattlewis92/angular-calendar/issues/346#issuecomment-335131865
