### ISSUE TITLE
Bug with dates rendering for october month in https://mattlewis92.github.io/angular-calendar/#/kitchen-sink

### ISSUE THREAD

**Issue by pcharithareddy** [mattlewis92/angular-calendar#356]
Looks like there's a bug with the way dates are rendered for the month of october in the kitchen sink example(https://mattlewis92.github.io/angular-calendar/#/kitchen-sink). This works fine in safari but not on chrome.
Weekdays start from Sunday for all the months except October.

Because of this, events are not falling on proper dates. For example there's an event 'A long event that spans 2 months' for which the start date is 28thOct. But, it shows this event for the date 27th Oct.

**Comment by mattlewis92** [comment]
Unfortunately I'm unable to reproduce this: 
<img width="997" alt="screen shot 2017-10-16 at 12 17 30" src="https://user-images.githubusercontent.com/6425649/31609425-04f31a86-b26c-11e7-8086-db7b2480a38a.png">

**Comment by pcharithareddy** [comment]
I think its a problem with the timezone. Can you try changing your computer's timezone to Melbourne/Australia?

**Comment by KamaKAzii** [comment]
I too am having a problem with October dates and i am in Sydney/Australia (similar timezone to @pcharithareddy )

My October (and onwards) dates are out by a day.
