### ISSUE TITLE
Events in calendar with Observable and subscribe

### ISSUE THREAD

**Issue by ibagaric** [mattlewis92/angular-calendar#357]
I have service where I fetch data as observable,

`    getVacations(): Observable<CalendarEventExtended[]> {
        return this.http
            .get(this.vacationsUrl)
            .map((response: Response) => <CalendarEventExtended[]>response.json());
    }`

then in the component, I subscribe to that method

`export class CalendarComponent implements OnInit {

    view: string = 'month';
    viewDate: Date = new Date();
    events: CalendarEventExtended[];
    weekStartsOn: number = DAYS_OF_WEEK.MONDAY;
    errorMessage: string;

    constructor(private filterService: FilterService, private vacationService: VacationsService) { }

    ngOnInit(): void {
        this.getVacations();
    }

    //Get status for filter
    getStatus(): void {
        this.filterService
            .getStatus()
            .subscribe(vacationStatus => this.vacationStatus = vacationStatus, error => this.errorMessage = <any>error);
    }

    //Get vacations for listing in calendar
    getVacations() {
        this.vacationService
            .getVacations()
            .subscribe(vacations => this.events = vacations, error => this.errorMessage = <any>error);
    }

}`

**event variable is loaded but it is not displayed in calendar**, but what is strange on week view there is some loaded event? I use custom cell template for month view

Is this good way to load events in the calendar? 

here is my view:

`
<ng-template #customCellTemplate let-day="day" let-locale="locale">
    <div class="cal-cell-top">
        <span class="cal-day-badge" *ngIf="day.badgeTotal> 0">{{ day.badgeTotal }}</span>
        <span class="cal-day-number">{{ day.date | calendarDate:'monthViewDayNumber':locale }}</span>
    </div>

    <div class="cal-events" *ngIf="day.events.length> 0">
        
        <div class="cal-event"
             *ngFor="let event of day.events | vacationStatus: selectedVacationStatus"
             [ngClass]="event.cssClass">
            <span>
                {{event.title}}
            </span>
        </div>
    </div>
</ng-template>

<div [ngSwitch]="view">
    <mwl-calendar-month-view *ngSwitchCase="'month'"
                             [viewDate]="viewDate"
                             [events]="events"
                             [locale]="locale"
                             [weekStartsOn]="weekStartsOn"
                             [weekendDays]="weekendDays"
                             [cellTemplate]="customCellTemplate">
    </mwl-calendar-month-view>
    <mwl-calendar-week-view *ngSwitchCase="'week'"
                            [viewDate]="viewDate"
                            [events]="events"
                            [locale]="locale"
                            [weekStartsOn]="weekStartsOn"
                            [weekendDays]="weekendDays">
    </mwl-calendar-week-view>
    <mwl-calendar-day-view *ngSwitchCase="'day'"
                           [viewDate]="viewDate"
                           [events]="events"
                           [locale]="locale">
    </mwl-calendar-day-view>
</div>`

**Comment by mattlewis92** [comment]
Please follow the issue template and attach a runnable plunker that reproduces your issue. The async events example might help solve your problem as its trying to accomplish the same thing: https://mattlewis92.github.io/angular-calendar/#/async-events Thanks! 😄

**Comment by ibagaric** [comment]
Tnx, Matt I follow async events, here is plunker, https://plnkr.co/edit/PoiZIzvP5wnaap8oDJwi?p=preview.
Also, how can I filter events by status that I put in CalenderEvent[] as property

tnx in advance

**Comment by mattlewis92** [comment]
Thanks for the plunker, I can see what's going on, your event start + end fields need to be date objects rather than strings. Here's your plunker fixed: https://plnkr.co/edit/0ypa3UDUQ8wBzyKLLYB3?p=preview

Re-opening as a reminder to add some code that will throw an exception if start and end dates aren't date objects.

**Comment by mattlewis92** [comment]
Closing in favour of https://github.com/mattlewis92/angular-calendar/issues/362
