### ISSUE TITLE
calendarDate internationalization

### ISSUE THREAD

**Issue by zszep** [mattlewis92/angular-calendar#359]
`{{ viewDate | calendarDate:(view + 'ViewTitle'):'hr' }}`
returns 'Week 42 of 2017'. The same applies to all other international codes (i.e. "de"). Is there a way to fix this. I looked at the source code and it seems to be a fixed constant.

**Comment by mattlewis92** [comment]
Please see the [i18n demo](https://mattlewis92.github.io/angular-calendar/#/i18n) for how to do this, there's no browser API to translate this and I didn't want to include a set of locale files for a single header 😄
