### ISSUE TITLE
Allow overriding of segment height in day view

### ISSUE THREAD

**Issue by emulvihill** [mattlewis92/angular-calendar#360]
## I'm submitting a ...

<pre>
[ ] Bug report 
[X ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit a support request here, please ask on https://stackoverflow.com/
</pre>

### Bug description / Feature request

Allow customizing of Calendar Day segment height. Currently although the height can be overridden with CSS, the interaction with events makes it unusable, because Event sizing is controlled by 
const SEGMENT_HEIGHT: number = 30;

Use case:  I need more granular control of event drop time, so I need more segments per hour. To fit this on the browser page the height needs to be shrunk accordingly.

PS Thank you, your calendar is brilliant!

### Versions

Angular: 4.0

Calendar library: angular-calendar

Browser name and version: Chrome

**Comment by mattlewis92** [comment]
This should be possible, btw if you need more segments per hour this is already possible: https://mattlewis92.github.io/angular-calendar/#/day-view-hour-split
