### ISSUE TITLE
Swipe

### ISSUE THREAD

**Issue by johnmikelridz** [mattlewis92/angular-calendar#363]
## I'm submitting a ...

<pre>
[ ] Bug report 
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit a support request here, please ask on https://stackoverflow.com/
</pre>

### Bug description / Feature request

Swiping

### Minimal reproduction of the problem with instructions
Is it possible to include swiping functionalities with the angular-calendar? I'm currently using Ionic and it would be nice to have this feature included as well.

### Versions

Angular: 4

Calendar library: latest

Browser name and version: Chrome v61

**Comment by mattlewis92** [comment]
I'm not really sure where you would include swiping gestures, as the layout is pretty much static. If using ionic I would recommend using a calendar that has been built from the ground up to work with it, such as this: https://github.com/twinssbc/Ionic2-Calendar

**Comment by johnmikelridz** [comment]
Thanks Matt.

We've had a look at this one before. Angular 4 Calendar's learning curve is not that steep 😄
