### ISSUE TITLE
customize days format in month view

### ISSUE THREAD

**Issue by Dhaferdhib** [mattlewis92/angular-calendar#368]
Hello, 
I am using a month view calendar and i am searching for a way to customize days format, for example display only 3 letters of the day name. 
Thank you

**Comment by mattlewis92** [comment]
You can see an example of how to do this in the demos: https://mattlewis92.github.io/angular-calendar/#/customise-date-formats

**Comment by naveenatti** [comment]
if i want to display on first letter of days name how it is possible @mattlewis92  can you please provide the solution
