### ISSUE TITLE
How do I include the default openDayEventsTemplate while having my custom openDayEventsTemplate?

### ISSUE THREAD

**Issue by XhitHub** [mattlewis92/angular-calendar#370]
After going through the documentations, I have the following unsolved questions:

1. How do I include the default openDayEventsTemplate (which shows the details about the events in a list) into my own custom openDayEventsTemplate component?
2. How do I access the event objects in my own custom openDayEventsTemplate component?

"Issues" is probably not the place to go for this post but sorry that I can't find a more fitting place.

Thanks a lot.

**Comment by sureshdotariya** [comment]
You need to use 'openDayEventsTemplate' input() property which will accept template reference as parameter.

------
<mwl-calendar-month-view [@.disabled]="true" [viewDate]="viewDate" [events]="events" [refresh]="refresh" 
        [activeDayIsOpen]="false"  (eventClicked)="handleEvent('Clicked', $event.event)"
        [openDayEventsTemplate]="openDayEventsTemplate">
      </mwl-calendar-month-view>
-----

<ng-template #openDayEventsTemplate> <span>Display day events details</span></ng-template>

**Comment by mattlewis92** [comment]
The only way to do this is to copy the markup in your template and adapt as appropriate. You can use this as a starter:
```
<ng-template
      #openDayEventsTemplate
      let-events="events"
      let-eventClicked="eventClicked">
      <div
        *ngFor="let event of events"
        [ngClass]="event?.cssClass"
        mwlDraggable
        [dropData]="{event: event}"
        [dragAxis]="{x: event.draggable, y: event.draggable}">
        <span
          class="cal-event"
          [style.backgroundColor]="event.color.primary">
        </span>
        <mwl-calendar-event-title
          [event]="event"
          [customTemplate]="eventTitleTemplate"
          view="month"
          (mwlClick)="eventClicked.emit({event: event})">
        </mwl-calendar-event-title>
        <mwl-calendar-event-actions [event]="event"></mwl-calendar-event-actions>
      </div>
    </ng-template>
```
