### ISSUE TITLE
Display Flex Issue In Intenet Explorer

### ISSUE THREAD

**Issue by Hulk-Tron** [mattlewis92/angular-calendar#372]
## Display:flex issue in Internet Explorer 11

<pre>
Used this library in my project in every browser the calendar is looking fine but in internet explorer 11 the calender is messed up big time.
</pre>

![calenderissue](https://user-images.githubusercontent.com/8166090/32244870-be490c94-be9b-11e7-9874-36cd91d316a1.png)

**Comment by mattlewis92** [comment]
<img width="1365" alt="screen shot 2017-11-02 at 14 17 03" src="https://user-images.githubusercontent.com/6425649/32330607-8971cec8-bfd8-11e7-966a-e2e6aefc3e10.png">

The demos works fine for me in IE11, it looks like you're using some custom CSS which may be causing your issue. Make sure the [min-height](https://github.com/mattlewis92/angular-calendar/blob/master/scss/month-view.scss#L47) on the cells aren't be overridden, without a runnable repo it's hard to say more.
