### ISSUE TITLE
Cant delete events when draggable set to true

### ISSUE THREAD

**Issue by Emildall** [mattlewis92/angular-calendar#373]
The issue is as following.

When a event has "draggable" set to true, it is not deletable in the Week and Day view. 
It dosent run the events at all in those views.

Everything works in the Month view. 

Image that shows the two events.
![image](https://user-images.githubusercontent.com/21078201/32275630-477e8c44-bf0c-11e7-8338-97a3b04594ba.png)

Image that shows the action for the events.
![image](https://user-images.githubusercontent.com/21078201/32275773-ce92667e-bf0c-11e7-9187-119178efa1f1.png)

Image that shows the html for the different views.
![image](https://user-images.githubusercontent.com/21078201/32275740-b510298e-bf0c-11e7-9281-3a9e20c9dedb.png)

**Comment by mattlewis92** [comment]
Ah, I can reproduce in the demo, I will try and get that fixed up!

**Comment by Emildall** [comment]
Thanks, for the quick reply!

**Comment by mattlewis92** [comment]
Apologies for the late reply on this, I've not had much time for open source lately, should be fixed now in `0.22.3` 😄
