### ISSUE TITLE
Angular 4 Calendar styles not applying 

### ISSUE THREAD

**Issue by achirashamal** [mattlewis92/angular-calendar#374]
I'm working with angular 4 and trying to include angular-calendar component into my app. But there is an issue with styling. I think css file in not being imported. even though I have no error in the console or anywhere. Here is what the calendar looks like:

![image](https://user-images.githubusercontent.com/28665549/32310151-681e99bc-bfb6-11e7-8aeb-99d15fbc40cf.png)

**Comment by lblower** [comment]
Did you included .css file   ?

I included angular-calendar.css in .angular.cli.json in styles array. (w.r.t my node modules folder) and restart the server.

"styles": [
              "../node_modules/angular-calendar/dist/css/angular-calendar.css"
      ],

**Comment by mattlewis92** [comment]
@lblower is correct, it looks like you're not including the stylesheet in your app.

**Comment by sakthivelsubbarayan** [comment]
I have a same problem. I try to include the css in my angular.cli.json file like

`
  "styles": [
      "styles.css",
      "../node_modules/angular-calendar/css/angular-calendar.css"
    ]`

But it not working.Still the css not apply to the component.
![screenshot from 2018-05-05 11-01-49](https://user-images.githubusercontent.com/30147172/39660024-e0240392-5053-11e8-9afa-84ac726fea9b.png)
