### ISSUE TITLE
How to get all the events of a month / year ?

### ISSUE THREAD

**Issue by lblower** [mattlewis92/angular-calendar#375]
Hi,
How can we get all the events of months like November with single click or calling a function ?

i have a requirement like , user clicks on any day and i add/remove event on the day as per my logic  and at end i have a save button. 

## I'm submitting a ...

<pre>
[ ] Bug report 
[ ] Feature request
[x ] Documentation issue or request
[ ] Support request => Please do not submit a support request here, please ask on https://stackoverflow.com/
</pre>

### Versions

Angular: 

Calendar library: 

Browser name and version:

**Comment by mattlewis92** [comment]
You can use date-fns to do this:
```
const date = new Date();
const start = startOfMonth(date); // https://date-fns.org/v1.29.0/docs/startOfMonth
const end = endOfMonth(date); // https://date-fns.org/v1.29.0/docs/endOfMonth
const filteredEvents = events.filter(event => event.start > start && event.end < end);
```

**Comment by Ashab31** [comment]
Hi,
 Even i have the same requirement, but I couldn't get the solution which has been suggested.
Can I get some more description of the solution with Plunker if possible. Thanks in advance.
