### ISSUE TITLE
async-events '.map' undefined 

### ISSUE THREAD

**Issue by mattijsing** [mattlewis92/angular-calendar#377]
Hi

When using angluar-cli: v1.4.9 and the the demo 'async-events' i get the error :

> **Cannot read property 'map' of undefined**

`    this.events$ = this.http
      .get('http://localhost:5000/api/Movie/')
      .map<any,any>(({ results }: { results: Movie[] }) => {
        return results.map((film: Movie) => {
          return {
            title: film.name,
            start: new Date(film.start),
            end: new Date(film.end),
            color: colors.blue,
            meta: {
              film
            }
          };
        });
      });`

+ I had to specify the mapping (.map<any,any>)

An other user posted it on stackoverflow: [https://stackoverflow.com/questions/46112408/error-typeerror-cannot-read-property-map-of-undefined](url)

thanks

**Comment by mattlewis92** [comment]
The answer was already provided in that stackoverflow post: https://stackoverflow.com/a/46112509/2075582

I will update the docs to use the new rxjs lettable operators instead which should make this a bit more obvious.

**Comment by nicogaldo** [comment]
Re-open this issue. I get the error when changing the url of http.get in the async example for my localhost database (mongodb - expressjs)

`ERROR TypeError: Cannot read property 'map' of undefined at MapSubscriber.eval`

I create a [post in stackoverflow](https://stackoverflow.com/questions/49645426/angular-calendar-async-http-map-of-undefined) for mas details.

Thanks!
