### ISSUE TITLE
Use calendar with moment

### ISSUE THREAD

**Issue by jbojcic1** [mattlewis92/angular-calendar#378]
Is it possible to use calendar completely with moment? Currently in doc I can see that there is moment formatter but it's not clear to me if it's possible to make everything work with moment. I mean dayclicked would return moment instead of the native date etc.

**Comment by mattlewis92** [comment]
You are correct in that the only bit of moment that the calendar supports is to format dates (to prevent having to load the intl polyfill if you're already using moment in your app). For everything else you can just use `moment() / .toDate()` to convert back and forth between pure JS dates and moment objects.

**Comment by frknsgt** [comment]
Hi Mat.
If today is wednesday it is showing on the calendar as thursday how can i fix it. Is it have example for that?
