### ISSUE TITLE
Custom styles?

### ISSUE THREAD

**Issue by kerimdragolj** [mattlewis92/angular-calendar#381]
The only way I could influence look of calendar is by adding css to core css file (angular-calendar.css) in node modules. I dont think thats right way to do it, is that the only way to do it?

**Comment by mattlewis92** [comment]
You can take advantage of the cascading effect of CSS to accomplish this (assuming you are using the angular CLI)
```
"styles": [
        "../node_modules/angular-calendar/dist/css/angular-calendar.css",
        "styles.css"
],
```

In `styles.css` you can add some custom rules which override the defaults provided.
