### ISSUE TITLE
Event appears above hours

### ISSUE THREAD

**Issue by StifMaster7** [mattlewis92/angular-calendar#383]
Hello,

In the view day the events appears above the hours with a blank space:

[https://i.imgur.com/X0h0MdQ.png](https://i.imgur.com/X0h0MdQ.png)

My component code:

events: CalendarEvent[] = [
      {
        title: 'An event',
        color: colors.yellow,
        start: new Date()
      }
      
    ];

My html code:

<mwl-calendar-day-view
[viewDate]="viewDate"
[events]="events"></mwl-calendar-day-view>

what is the problem?

My version is:

Angular core: 4.2.4

Calendar library: 0.21.3

Browser name and version: Chrome version 61

**Comment by mattlewis92** [comment]
Please can you make a runnable plunker that reproduces your issue, as it's impossible to know what's going on otherwise without some code that demonstrates the problem. Thanks!
