### ISSUE TITLE
Add support for Angular 5

### ISSUE THREAD

**Issue by damiandennis** [mattlewis92/angular-calendar#384]
## I'm submitting a ...

<pre>
[ ] Bug report 
[ ] Feature request
[ ] Support request => Please do not submit a support request here, please ask on https://stackoverflow.com/
</pre>

### Versions

Angular: 

Calendar library: 

Browser name and version:

**Comment by mattlewis92** [comment]
Already done 😄 https://github.com/mattlewis92/angular-calendar/blob/master/CHANGELOG.md#0213-2017-10-21
