### ISSUE TITLE
slide in view month

### ISSUE THREAD

**Issue by dovalgomes** [mattlewis92/angular-calendar#385]
Hello everyone, I would suggest for development the use of slide to pass and rewind the calendar months. I'm using the component with ionic 2 for multiplatform development and I believe it would be very productive for this component to use a slide to advance the months.

**Comment by mattlewis92** [comment]
As explained in the [readme](https://github.com/mattlewis92/angular-calendar#does-this-calendar-work-with-mobile), the primary purpose of this lib is to work on desktop, to provide a great experience on mobile I'm of the opinion that its better to create a dedicated mobile specific calendar component built from ionic components, a bit like this: https://github.com/twinssbc/Ionic2-Calendar
