### ISSUE TITLE
Disabling hours in dayView and days in monthView.

### ISSUE THREAD

**Issue by johnmikelridz** [mattlewis92/angular-calendar#386]
## I'm submitting a ...

<pre>
[ ] Bug report 
[x] Feature request
[ ] Support request => Please do not submit a support request here, please ask on https://stackoverflow.com/
</pre>

### Bug description / Feature request
Is it possible to disable hours in the dayView and dates in monthView basing on some data that we will have to construct / pull from FireStore? The idea we are working on is to disable some dates and some days where a user's selected service can no longer be accommodated (it will compare his chosen service to all the data in FireStore).

I hope this made sense.

### Versions

Angular: 4

Calendar library: 

Browser name and version:

**Comment by mattlewis92** [comment]
This is possible via the `beforeViewRender` hook. Example for the month view [here](https://mattlewis92.github.io/angular-calendar/#/min-max-date) and the day view [here](https://github.com/mattlewis92/angular-calendar/issues/185#issuecomment-294483309). Hope that helps!

**Comment by johnmikelridz** [comment]
Thanks!

**Comment by johnmikelridz** [comment]
Sorry, Matt. I think the [hourSegmentModifier] input directive is already deprecated? I'm getting an error when I implement it in the template. It's saying that mwl-calendar-day-view component has no property of 'hourSegmentModifier'.

Hope this made sense. :D

**Comment by johnmikelridz** [comment]
I think we will need an export of CalendarDayViewHourSegment to implement this.

**Comment by caiquevallim** [comment]
> I think we will need an export of CalendarDayViewHourSegment to implement this.

solved?
