### ISSUE TITLE
custom styles for Cal-day-badge and make it draggable.

### ISSUE THREAD

**Issue by simandi** [mattlewis92/angular-calendar#389]
Hello @mattlewis92,

Can I make cal-day-badge around the date. Like below Image.

https://user-images.githubusercontent.com/19929339/32732875-da54dbbc-c8b3-11e7-8af3-51461e8645a7.PNG

where border around the date 25 is an event badge and that need to be draggable.

Thank you.

**Comment by mattlewis92** [comment]
Please ask questions like this on stackoverflow, thanks!
