### ISSUE TITLE
calendar-utils

### ISSUE THREAD

**Issue by pieterlouw1974** [mattlewis92/angular-calendar#390]
## I'm submitting a ...

<pre>
[ ] Bug report 
[ ] Feature request
[x ] Support request => 
get this error
ERROR in node_modules/angular-calendar/dist/esm/src/components/day/calendarDayView.component.d.ts(2,87): error TS2307: Cannot find module 'calendar-utils'.

How do i fix this in Angular5, in 4 it works beautifull

### Versions

Angular:  5

Calendar library:  0.21.3

Browser name and version: Chrome Version 61.0.3163.100

**Comment by mattlewis92** [comment]
Hi there, it sounds like an issue with your build tool rather than this lib as I'm using it successfully with angular 5. If you can make a minimal repo that reproduces your problem I'd be happy to help debug more! 😄

**Comment by pieterlouw1974** [comment]
Good day Matt

I deleted my node_modules folder and that sorted it out.

Thanks
