### ISSUE TITLE
Changing dots of events to hiphens 

### ISSUE THREAD

**Issue by EssenKh** [mattlewis92/angular-calendar#391]
Customizing the API, hiphens (-) instead of dots to represent events 

Regards

**Comment by mattlewis92** [comment]
You can probably do this with a [custom template](https://github.com/mattlewis92/angular-calendar#how-do-i-use-a-custom-template) for the [slide box](https://github.com/mattlewis92/angular-calendar/blob/master/src/components/month/calendar-open-day-events.component.ts) and [month cell](https://github.com/mattlewis92/angular-calendar/blob/master/src/components/month/calendar-month-cell.component.ts) templates
