### ISSUE TITLE
Incorrect time gets displayed

### ISSUE THREAD

**Issue by FullStackDeveloper11** [mattlewis92/angular-calendar#392]
Hi,

I am getting the time from my API as "2017-11-01T08:00:00"

Calendar displays the time as "01:00:00"

Please let me know why 8:00 AM is getting converted to 1:00 AM .

Thanks,
Yusuf

**Comment by mattlewis92** [comment]
It's probably your timezone, `2017-11-01T08:00:00` has no timezone encoded in it so it defaults to your local timezone. If you do `new Date('2017-11-01T08:00:00')` in the console you'll see it gets offset by your timezone.

**Comment by FullStackDeveloper11** [comment]
Date & time received from API is already in MST time
but still  new Date('2017-11-01T08:00:00') gets changed to  '2017-11-01T01:00:00; MST.

This issue is only in iOS and Android.

**Comment by etwillbefine** [comment]
I also saw this behaviour few days ago. We decided to switch to momentjs as we had a lot of these problems also in our own app. That fixed the issue but the ordering of events is still wrong. I was only able to reproduce this issue on an old android tablet via chrome.

**Comment by mattlewis92** [comment]
Ah that would make sense, I've experienced several browser bugs with date objects myself on old versions of safari and chrome. I guess moment abstracts over them, but AFAIK date-fns doesn't. The only solution I can really think of is to create dates with the moment constructor as @etwillbefine recommended.

**Comment by FullStackDeveloper11** [comment]
Thanks @etwillbefine and @mattlewis92  , I was able to solve the issue partly with momentjs.

Now it works on all browser  except in secret mode.
I have Samsung galaxy note 3 on which I have Samsung browser.
If I open the browser in normal mode dates are displaying fine, but when I open the browser in secret mode dates are incorrectly displayed, for example,  8.00 am is displayed as 6.00pm.

Any help or suggestion will be much appreciated.

Thanks

**Comment by etwillbefine** [comment]
How do you construct dates with moment? I was using `moment.utc(myDateString).utcOffset(offset)`. But you might need to take care about timezones (eg because of DST) instead of plain offsets.

Also you should consider returning Zulu Time from your API. Eg: `2017-11-01T08:00:00Z` representing UTC Time.
