### ISSUE TITLE
Metadata version mismatch for module

### ISSUE THREAD

**Issue by andreroggeri** [mattlewis92/angular-calendar#397]
## I'm submitting a ...

<pre>
[X] Bug report 
[ ] Feature request
[ ] Support request => Please do not submit a support request here, please ask on https://stackoverflow.com/
</pre>

### Bug description / Feature request
It's not possible to upgrade to 0.22.0. The build fails with the following error: 

`ERROR in Metadata version mismatch for module E:/Projetos/angular-calendar-test/node_modules/angular-calendar/index.d.ts, found version 4, expected 3`

### Minimal reproduction of the problem with instructions
 - Start a new angular 4 application using angular-cli 
 - Install angular-calendar
 - Add the import to the CalendarModule in the app.module
 - ng serve

### Versions

Angular:  4.4.6

Calendar library:  0.22.0

Browser name and version: N/A

**Comment by KittisakChitmun** [comment]
have a same problem

**Comment by mattlewis92** [comment]
Ah, it looks like apps compiled with angular 5 don't work with angular 4, the workaround is to either upgrade to angular 5 (should be as simple as updating your package.json file) or stick with 0.21.x for now, as I don't have time to revert all the angular 5 changes right now.

**Comment by andreroggeri** [comment]
Do you plan to support Angular 4 or the 0.21.X version is the last to do it ?

Maybe we could add a note in the changelog or in the readme for this

**Comment by mattlewis92** [comment]
It was a mistake, 0.22 should support angular 4.

**Comment by mattlewis92** [comment]
Cutting 0.22.1 now 😄
