### ISSUE TITLE
Plunker broken due to bad resource URLs

### ISSUE THREAD

**Issue by arimus** [mattlewis92/angular-calendar#398]
## I'm submitting a ...

<pre>
[X] Bug report 
[ ] Feature request
[ ] Support request => Please do not submit a support request here, please ask on https://stackoverflow.com/
</pre>

### Bug description / Feature request
Plunker is current broken for at least the Kitchen Sink example

### Minimal reproduction of the problem with instructions
Edit in plunker and you'll see that it doesn't load, 404 for some resources. Looks like:

```'angular-calendar': 'npm:angular-calendar@0.22.0/dist/umd/angular-calendar.js',```

should be

```'angular-calendar': 'npm:angular-calendar@0.22.0/umd/angular-calendar.js',```

and a similar change for the angular-calendar.css resource. Seemed to load just fine after that.

Modified plunk: http://plnkr.co/edit/198gKQEtAVe3WsIgO4zs?p=preview

### Versions

Angular: 

Calendar library: 

Browser name and version: 
Chrome latest on OSX

**Comment by mattlewis92** [comment]
Thanks, fixed! 😄
