### ISSUE TITLE
How to highlight hour segment clicked

### ISSUE THREAD

**Issue by hinduasish** [mattlewis92/angular-calendar#400]
Hi,

Thanks for your Angular Calendar, it is great :) I am trying to highlight the hour segment clicked similar to the selectable month day in [ https://mattlewis92.github.io/angular-calendar/#/selectable-month-day ]

I have gotten it to the point where I call hourSegmentClicked and pass in a date object, but I do not know how to change the css of the hour selected. Any help with this would be appreciated.

Thanks

**Comment by hinduasish** [comment]
BTW I have solved this if anyone is wondering, create variable

  body: DayViewHour[] = [];

then on beforeviewrender, pass in the argument view and set this.body = view.body

hopee that helps :)

**Comment by mattlewis92** [comment]
This has come up quite a few times, so I've updated the docs to show how to do this for the day view as well, hope that helps! 😄 

https://mattlewis92.github.io/angular-calendar/#/selectable-period

**Comment by hamzapoly** [comment]
![image](https://user-images.githubusercontent.com/13818732/77860352-ae6d7280-7206-11ea-98c7-f9551ea88add.png)
Whenever I call the event (hourSegmentClicked) I get this error. Are there any requirements ?
