### ISSUE TITLE
Change month view using custom drop down instead of back and previous buttons?

### ISSUE THREAD

**Issue by raviayadav** [mattlewis92/angular-calendar#404]
## I'm submitting a ...

<pre>
[ ] Bug report 
[x] Feature request
[ ] Support request => Please do not submit a support request here, please ask on https://stackoverflow.com/
</pre>

### Feature request
I want to implement a dropdown in the calendar header to select the month view instead of the previous and next buttons. For example, if I clicked on the the dropdown it would give me the twelve options to choose the month view. Is there a way it can be achieved? Please guide me which code to look into to get started with that.

**Comment by mattlewis92** [comment]
The nav header isn't actually part of this library, you're free to just copy and paste the source from the demo and change the buttons to a dropdown. The value of each item in the dropdown would be a date that you bind to the value that you pass to the `viewDate` input of the calendar month view component.
