### ISSUE TITLE
Want to use clickable day feature of the calendar

### ISSUE THREAD

**Issue by pkarunakar2006** [mattlewis92/angular-calendar#406]
Hi,

I am new to Angular development. I want use the clickable days feature of this calendar. I installed it with npm, included the css and wrote the import statements in app.module.ts file as mentioned in the documentation. 
But when i write 
import { DemoUtilsModule } from '../demo-utils/module';
 getting an error "cannot find module."

can someone please advice on how to include it in my project and use this feature.

Thanks 
Karunakar

## I'm submitting a ...

<pre>
[ ] Bug report 
[ ] Feature request
[ ] Support request => Please do not submit a support request here, please ask on https://stackoverflow.com/
</pre>

### Versions

Angular: 

Calendar library: 

Browser name and version:

**Comment by mattlewis92** [comment]
That code is simply for the purposes of the demo (hence the name) and not part of this package. You can just remove the references to it in your own code.
