### ISSUE TITLE
No exported member Opaque Token 

### ISSUE THREAD

**Issue by Meistercoach83** [mattlewis92/angular-calendar#407]
## I'm submitting a ...
[X] Bug report 

### Bug description / Feature request
When I add the angular-calendar to my app, I get the following error:

> ERROR in node_modules/angular-calendar/dist/esm/src/providers/calendarMomentDateFormatter.provider.d.ts(1,10): error TS2305: Module '"D:/sfw/node_modules/@angular/core/core"' has no exported member 'OpaqueToken'.

### Versions
Angular: 
cli: 1.6.0-rc.2
core: 5.0.5

typescript: 2.6.2
Calendar library: 0.5.0-beta.4

Browser name and version: Chrome & Firefox

**Comment by mattlewis92** [comment]
Sounds like you're on a really old version of this lib, try upgrading to 0.22.1
