### ISSUE TITLE
Error with Angular Universal (ssr)

### ISSUE THREAD

**Issue by Agranom** [mattlewis92/angular-calendar#408]
## I'm submitting a ...
<pre>
[x] Bug report 
[ ] Feature request
[ ] Support request => Please do not submit a support request here, please ask on https://stackoverflow.com/
</pre>

### Bug description / Feature request
I try to run calendar with server side rendering, but this error shows up:
```
Error: StaticInjectorError[n]: 
  StaticInjectorError[n]: 
    NullInjectorError: No provider for n!
    at _NullInjector.get (/home/vitalii/ncube/angular-calendar/dist/server.js:1264:19)
    at resolveToken (/home/vitalii/ncube/angular-calendar/dist/server.js:1552:24)
    at tryResolveToken (/home/vitalii/ncube/angular-calendar/dist/server.js:1494:16)
    at StaticInjector.get (/home/vitalii/ncube/angular-calendar/dist/server.js:1365:20)
    at resolveToken (/home/vitalii/ncube/angular-calendar/dist/server.js:1552:24)
    at tryResolveToken (/home/vitalii/ncube/angular-calendar/dist/server.js:1494:16)
    at StaticInjector.get (/home/vitalii/ncube/angular-calendar/dist/server.js:1365:20)
    at resolveNgModuleDep (/home/vitalii/ncube/angular-calendar/dist/server.js:11154:25)
    at NgModuleRef_.get (/home/vitalii/ncube/angular-calendar/dist/server.js:12382:16)
    at resolveDep (/home/vitalii/ncube/angular-calendar/dist/server.js:12880:45)

```

### Minimal reproduction of the problem with instructions
Launch Angular Calendar with Angular Universal
### Versions

Angular:  5.1.0

Calendar library: 0.22.1

Browser name and version: Chrome 62

**Comment by mattlewis92** [comment]
Please can you attach a minimal repo that demonstrates your problem, thanks!

**Comment by Agranom** [comment]
https://github.com/Agranom/calendar.git

npm install
npm run build:ssr && npm run serve:ssr

**Comment by mattlewis92** [comment]
Perfect, thank you! Will try and dig in and work out whats going on when I have some free bandwidth

**Comment by AvanPhilipp** [comment]
Hello!
I've  found something that may help:

```
WARNING in ./node_modules/angular-calendar/dist/esm/src/providers/calendarMomentDateFormatter.provider.js
2:24-35 "export 'OpaqueToken' was not found in '@angular/core'
```
and later: 
```ERROR in node_modules/angular-calendar/dist/esm/src/providers/calendarMomentDateFormatter.provider.d.ts(1,10): error TS2305: Module '"/home/fealoce/Projects/queueWeb/node_modules/@angular/core/core"' has no exported member 'OpaqueToken'.
```

related:
https://github.com/PillowPillow/ng2-webstorage/pull/72
"OpaqueToken was deprecated with v4 and has been completely removed in v5."

Hope it helps.

**Comment by Agranom** [comment]
@AvanPhilipp which version do you use? Because I can’t find that path

**Comment by AvanPhilipp** [comment]
"angular-calendar": "^0.3.3",

Updated because of an other issue. ( #68 )

**Comment by Agranom** [comment]
the lates version is 0.22.1

**Comment by mattlewis92** [comment]
This turned out to be a bit of a rabbit hole, but I think this is fixed now. Please can you give the beta version a try please? `npm i angular-calendar@beta`. Thanks! 😄

**Comment by mattlewis92** [comment]
Finally had some free time tonight and can confirm that the beta is working nicely with universal now. Will publish 0.23.0 final tomorrow when travis is working again.

**Comment by Agranom** [comment]
Great work! Thanks a lot
