### ISSUE TITLE
Multiple Columns for Users in Day

### ISSUE THREAD

**Issue by renilbabu03** [mattlewis92/angular-calendar#409]
Angular-calender is an awesome component for calender that I came across. I am having problem in implementing multiple columns for user in the day of the calender. The following image shows my requirement.
![issue](https://user-images.githubusercontent.com/18526147/33925908-087dcb74-e002-11e7-909d-d77d2d40cd13.png)

When the user sees the day section of the calender , it should show the events of all the users.
Can you please help.! It would help me a lot in my project. !

**Comment by mattlewis92** [comment]
You can get most of the way there by using a custom template, see https://github.com/mattlewis92/angular-calendar/issues/269 for an example. If that doesn't work for you, then I'd recommend just building your own day view component instead of trying to get a square peg to fit in a round hole.
