### ISSUE TITLE
node_modules/calendar-utils/dist/calendar-utils.d.ts (146,16): In ambient enum declarations member initializer must be constant expression.

### ISSUE THREAD

**Issue by Mean563** [mattlewis92/angular-calendar#410]
## I'm submitting a ...

<pre>
[ ] Bug report 
[ ] Feature request
[ ] Support request => Please do not submit a support request here, please ask on https://stackoverflow.com/
</pre>

### Versions

Angular: 

Calendar library: 

Browser name and version:

**Comment by mattlewis92** [comment]
Sounds like you might be on an old version of typescript, it's impossible to say more without something that reproduces your issue though 😞

**Comment by brestmoor** [comment]
It's happening to me too
