### ISSUE TITLE
No events founds label

### ISSUE THREAD

**Issue by minimalifestyle** [mattlewis92/angular-calendar#411]
There's a way `onInit` to check if there's an event and, if not, put a simple text 'No events found for this day' or 'No events found for this week' where events usually render?

Thanks in advance

**Comment by mattlewis92** [comment]
This isn't currently particularly easy to implement, I have a few ideas on how to improve the API to make this easy to do though: https://github.com/mattlewis92/angular-calendar/issues/418

**Comment by mattlewis92** [comment]
Please give 0.23.x a try, this is now pretty easy to implement: https://mattlewis92.github.io/angular-calendar/#/no-events-label
