### ISSUE TITLE
Add Image in CalendarEvent 

### ISSUE THREAD

**Issue by shorabhd** [mattlewis92/angular-calendar#413]
## I'm submitting a ...

<pre>
[ ] Bug report 
[X] Feature request
[ ] Support request => Please do not submit a support request here, please ask on https://stackoverflow.com/
</pre>

### Bug description / Feature request

I want to add an image in a calendar event. Is there a way we can do that? 

### Versions

Angular: 2/4

Calendar library: 

Browser name and version: Chrome Latest

**Comment by mattlewis92** [comment]
You can add html in the event title with the image, or use a [custom template](https://github.com/mattlewis92/angular-calendar#how-do-i-use-a-custom-template) to do this. Hope that helps! 😄

**Comment by shorabhd** [comment]
Sorry, actually I wanted to add an image to the calendar itself like where it displays a bullet for an event. So instead of bullet I want to show an image.

**Comment by mattlewis92** [comment]
You can still do this with a [custom template](https://github.com/mattlewis92/angular-calendar#how-do-i-use-a-custom-template) for [this component](https://github.com/mattlewis92/angular-calendar/blob/master/src/modules/month/calendar-open-day-events.component.ts).
