### ISSUE TITLE
Change Slider Template

### ISSUE THREAD

**Issue by ToxicToast** [mattlewis92/angular-calendar#414]
## I'm submitting a ...

<pre>
[ ] Bug report 
[ ] Feature request
[x] Support request => Please do not submit a support request here, please ask on https://stackoverflow.com/
</pre>

### Bug description / Feature request
I need some help with the Slider Template - it seems that i cant change the Look of the Slider when i click on a Date with Events.

### Versions

Angular:  CLI (1.6.1)

Calendar library: Newest Push

Browser name and version: 
Chrome - also newest

**Comment by mattlewis92** [comment]
You need to follow the instructions [here](https://github.com/mattlewis92/angular-calendar#how-do-i-use-a-custom-template) for [this component](https://github.com/mattlewis92/angular-calendar/blob/master/src/modules/month/calendar-open-day-events.component.ts). Hope that helps! 😄
