### ISSUE TITLE
Extend 'Selectable Period' to 'Select Range'

### ISSUE THREAD

**Issue by visweswaranr** [mattlewis92/angular-calendar#415]
## I'm submitting a ...

<pre>
[ ] Bug report 
[x] Feature request
[ ] Support request => Please do not submit a support request here, please ask on https://stackoverflow.com/
</pre>

### Bug description / Feature request
Can the "Selectable period" be extended to the "Select range" like in the [AngularJS version](https://mattlewis92.github.io/angular-bootstrap-calendar/#!?example=select-range)? Are there plans for it? Just curious to know why you havent supported it in the initial version for Angular 2+.

It would be really great to have that, especially in the day view of the calendar. :) 

### Versions

Angular: 4/5

Calendar library: 0.22.1

Browser name and version: Google Chrome

**Comment by mattlewis92** [comment]
I didn't want to bake too many features into the core as it then becomes a maintenance library, instead you can extend the base components to add this functionality yourself. This is how you do it for the month view: https://github.com/mattlewis92/angular-calendar/issues/235#issuecomment-307570924 and you can adapt as appropriate for the day view component.

**Comment by visweswaranr** [comment]
Awesme, thanks!
