### ISSUE TITLE
Display week numbers on the side

### ISSUE THREAD

**Issue by SimonOliver123** [mattlewis92/angular-calendar#416]
## I'm submitting a ...
<pre>
[ ] Bug report 
[x] Feature request
[ ] Support request => Please do not submit a support request here, please ask on https://stackoverflow.com/
</pre>

### Feature request
Is it possible to have week numbers on the left side of the month view? It would be great to be able to switch it on and off. 
e.g [http://prntscr.com/hqet4h](http://prntscr.com/hqet4h)

### Versions

Angular: 4/5

Calendar library: 0.22.1

Browser name and version: Google Chrome

**Comment by mattlewis92** [comment]
You can implement this yourself in user land by using a custom template for the month view, I threw together a quick example for you here that you can build off: http://plnkr.co/edit/U2oVyc61dix9YmoT8fHv?p=preview Hope that helps! 😄

**Comment by SimonOliver123** [comment]
Hi,
Thank you for your response, the example helped me sort it out.
Cheers
