### ISSUE TITLE
Angular v5 minimum

### ISSUE THREAD

**Issue by mattlewis92** [mattlewis92/angular-calendar#417]
- [x] Revert https://github.com/mattlewis92/angular-calendar/commit/f5e500a392b832d36651bd2bcdafb437af4971f5
- [x] Set peer dependencies, docs etc to v5+
- [x] Make the [default date formatter](https://github.com/mattlewis92/angular-calendar/blob/master/src/modules/common/calendar-date-formatter.provider.ts) the angular one
- [x] import [DOCUMENT](https://github.com/mattlewis92/angular-calendar/blob/master/src/modules/common/calendar-tooltip.directive.ts#L17) from `@angular/common`
- [x] Remove v4 version check [here](https://github.com/mattlewis92/angular-calendar/blob/master/src/modules/common/calendar-angular-date-formatter.provider.ts#L74)
- [x] Use ng-packagr: https://github.com/dherges/ng-packagr
- [x] Revert https://github.com/mattlewis92/calendar-utils/commit/020a81de7659374ade51adbd1c7fc4692384c835
- [x] Revert https://github.com/mattlewis92/angular-calendar/commit/c4d6abc
- [x] Upgrade draggable and droppable libs to 2.0

**Comment by RbkGh** [comment]
hello please have you released it yet? we need it for angular 5 . Currently,version 0.22.3 still depends on version 4.4 of angular instead of version 5 miniumum.Please when will this be released?

**Comment by RbkGh** [comment]
is it possible you add me to the project so that i can add minor changes and release when you do not have time readily?I need this for a project I'm working on currently.

**Comment by mattlewis92** [comment]
Hi there, this lib already works just fine with angular v4 and v5, this issue is just for making it work with v5 only. All the changes are already done here: https://github.com/mattlewis92/angular-calendar/pull/420 and available on the beta tag on npm.

**Comment by Kumfert** [comment]
FWIW.  I upgraded to Angular v5 and angular-calendar 0.22.3 and encountered a regression where external drag-n-drop stopped working (eventTimesChanged event wasn't firing.)  #420 fixed it for me.  Thanks.
