### ISSUE TITLE
Day View in Bottom of the Week View

### ISSUE THREAD

**Issue by baljinder981** [mattlewis92/angular-calendar#421]
Hello Mattlewis92,

I want to show day view bottom of the week view with events. 

Like this : 

![image](https://user-images.githubusercontent.com/19308483/34405020-fb05571a-ebd6-11e7-8163-5ffc06a74551.png)

Please help me how can i create the same week view.

Thanks for advance!

**Comment by mattlewis92** [comment]
Sorry there's no support for this type of week view component in this package and I have no intention of building it.
