### ISSUE TITLE
Inject Template in Weekly View

### ISSUE THREAD

**Issue by baljinder981** [mattlewis92/angular-calendar#422]
Hello mattlewis92,

I want to inject new template under week view.so please help me how can i implement same.
If I'm using same approach which you mentioned in month view this approach is not working in weekly view.

[cellTemplate]="customCellTemplate"

So please let me know how can i do this.

Thanks in advance!

**Comment by mattlewis92** [comment]
Please see the guide in the readme for how to do this: https://github.com/mattlewis92/angular-calendar#how-do-i-use-a-custom-template You will need to adapt it for the week view, the template inputs are different because the names don't make sense across the month / week / day components
