### ISSUE TITLE
Issue while updating both date and time together

### ISSUE THREAD

**Issue by amittrehan44** [mattlewis92/angular-calendar#423]
## I'm submitting a ...

<pre>
[x ] Bug report 
[ ] Feature request
[ ] Support request => Please do not submit a support request here, please ask on https://stackoverflow.com/
</pre>

### Bug description / Feature request
While trying to update both date and time at same time for event.start using mwl-demo-utils-date-time-picker, if time is update after date the date will be set to the original value 
Steps to reproduce:
1)	Scroll to Edit Events  
2)	Update date
3)	Then Update time
4)	Issue: date will be set to original date 
Vice a versa: if you update time before date the time will be set to original when date is updated 

### Minimal reproduction of the problem with instructions
http://plnkr.co/edit/5JkPbe1wA0N50FHwwKh0?p=preview
Example: 
![calendar_datetime issue](https://user-images.githubusercontent.com/31450039/34458449-56c8ea46-ed88-11e7-9d76-a48b7bee202a.png)
Update “3 Day Event” date from 2017-12-29 to 2017-12-30 and then update time and you will notice date is set back to 2017-12-29 on background
That’s why I have displayed events.start under  event.start using mwl-demo-utils-date-time-picker

### Versions

Angular: 5.0.1 (pinkr: 4.4.6)

Calendar library: 0.21.3 

Browser name and version: Chrome Version 62.0

**Comment by mattlewis92** [comment]
Thanks for reporting, this should be fixed now 😄

**Comment by amittrehan44** [comment]
Thank you :)
