### ISSUE TITLE
calendar grid not loaded (angular 5)

### ISSUE THREAD

**Issue by neo-xy** [mattlewis92/angular-calendar#425]
as in instructions I added:
CalendarModule.forRoot() to ngModule->imports
and then to make it very simple I added to html:
`
<mwl-calendar-month-view
  [viewDate]="viewDate">
</mwl-calendar-month-view>`

and in ..component.ts
`viewDate = new Date()`
but I-m not getting calendar table and only values in a column like shown'below'
(what am I missing:s ?)
'bellow':
Sunday
Monday
Tuesday
Wednesday
Thursday
Friday
Saturday
31
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
....

**Comment by danailvidev** [comment]
@neo-xy You need to import angular-calendar.css from node_modules/angular-calendar/css/angular-calendar.css

**Comment by neo-xy** [comment]
@danailvidev ahhh added that to styleUrls in my component instead of ading it to angular-cli.json :S
thank you  (y)
