### ISSUE TITLE
adding a button to a cell without loosing any funcionalities...

### ISSUE THREAD

**Issue by neo-xy** [mattlewis92/angular-calendar#426]
hi, trying to add a "add"-button to a cells of month-view
 - as in demos I created a custom template and made referance to it trough [cellTemplate] and there I added a button.  everything is cool but 'badges' are gone now and with them ofc functionalities like drag and drop. what is the easiest way to keep everything as it is in default Tamplate and add some kind of a button somwhere in the top left that ads new events instead of having add-event button outside month-view...?

**Comment by mattlewis92** [comment]
You can copy paste the original template and use it as a base: https://github.com/mattlewis92/angular-calendar/blob/master/src/modules/month/calendar-month-cell.component.ts#L13-L47
