### ISSUE TITLE
Adding click event to hour in day view

### ISSUE THREAD

**Issue by Gamerakki** [mattlewis92/angular-calendar#427]
Hi,

Firstly very nice and helpful plugin made by you. I have query how can we add click event on the hours timeline in day view for adding event according to the hour.

**Comment by mattlewis92** [comment]
Please use stackoverflow for all support requests like this, thank you! 😄

**Comment by Gamerakki** [comment]
how can i ask support if the plugin doesnt support that..

**Comment by mattlewis92** [comment]
It does support that, it's all in the documentation: https://mattlewis92.github.io/angular-calendar/docs/components/CalendarDayViewComponent.html#hourSegmentClicked
