### ISSUE TITLE
Missing locale data for the locale

### ISSUE THREAD

**Issue by sysmat** [mattlewis92/angular-calendar#431]
- [x] Bug report
- [ ] Feature request
- [ ] Support request 

### Bug description 
When I use latest version ^0.23.1 and using different locale then en then I get error, but with version ^0.22.2 it is working fine

- Missing locale data for the locale fr
- Monthly view is not working

### Minimal reproduction of the problem with instructions

```
<mwl-calendar-month-view *ngSwitchCase="'month'" [locale]="fr" [viewDate]="viewDate" [events]="events" [refresh]="refresh"
        [activeDayIsOpen]="activeDayIsOpen" (dayClicked)="dayClicked($event.day)" (eventClicked)="handleEvent('Clicked', $event.event)"
        [weekStartsOn]="weekStartsOn" [weekendDays]="weekendDays" [cellTemplate]="customCellTemplate">

    </mwl-calendar-month-view>
    <mwl-calendar-week-view *ngSwitchCase="'week'" [locale]="fr" [viewDate]="viewDate" [events]="events" [refresh]="refresh"
        (eventClicked)="handleEvent('Clicked', $event.event)" [weekStartsOn]="weekStartsOn"
        [weekendDays]="weekendDays">
    </mwl-calendar-week-view>

```

### Versions

Angular:  5.1.3

Calendar library: 0.23.1

Browser name and version:  chrome 63.0.3239.84

**Comment by ToxicToast** [comment]
Can reproduce this
ive got the same Error.

**Comment by mattlewis92** [comment]
I've added a note to the changelog with how to handle this, please see the i18n demo for an e2e example: https://mattlewis92.github.io/angular-calendar/#/i18n Hope that helps! 😄

**Comment by cyrinegh** [comment]
hello please i want to develop a  backend to the angular calendar the problem  : my data from database and rest API on json form  i dont know how it can be solved any solution please!!

**Comment by cyrinegh** [comment]
![capture](https://user-images.githubusercontent.com/27626501/37840627-e00a7394-2ebd-11e8-8a89-71e998662236.PNG)

**Comment by leenMalka** [comment]
@mattlewis92  
First thank you your work is amazing

Second- I tried to make calendar in Hebrew
I had tried to set `he` but without success...

https://stackblitz.com/edit/angular-6su8pq-tfqsqw?file=demo/component.ts

**Comment by mattlewis92** [comment]
You need to register the hebrew locale data in `module.ts` (like for the other languages):
```
import localeHe from '@angular/common/locales/he';
registerLocaleData(localeHe);
```

https://stackblitz.com/edit/angular-6su8pq-uxnpeg?file=demo/module.ts

**Comment by leenMalka** [comment]
@mattlewis92 thanks so much

**Comment by leenMalka** [comment]
@mattlewis92 I have tried to restyle the event and to set some text on in it the only way I found is to use javascript  

```
this.matches = document.querySelectorAll("mwl-calendar-month-cell .cal-event");
.
.
.
this.matches[i].innerText = "some text from events property";
```


**Do there is another way to do that (as some attribute)??**

**Comment by mattlewis92** [comment]
You can use a [custom template](https://github.com/mattlewis92/angular-calendar#how-do-i-use-a-custom-template) for the month cell to change the html.

**Comment by leenMalka** [comment]
@mattlewis92  This is cell template I want text on event 
(I restyle the circle event as in image with css and now I want to add text from the data of the event)

![image](https://user-images.githubusercontent.com/37149321/57010811-5fd6e300-6c07-11e9-8948-b7a0f0a69057.png)
