### ISSUE TITLE
week view problem

### ISSUE THREAD

**Issue by hugocaldeira** [mattlewis92/angular-calendar#432]
Hi,
When a duration of an event is longer than one day and if the ending hour is earlier than the starting hour, in the week view the event doesn't span to the last day. Please see the attached images.

![ok](https://user-images.githubusercontent.com/17253989/34721265-0287a67a-f53a-11e7-9f8f-d21b4b5f9639.png)

![notok](https://user-images.githubusercontent.com/17253989/34721269-0742cc30-f53a-11e7-9205-200a7c4510c3.png)

Am I doing anything wrong?

HC

**Comment by mattlewis92** [comment]
It seems like a timezone issue to me, `new Date('2018-01-12 14:00:00')` will default to UTC and adjust to your local timezone, so unless your browsers timezone is UTC you'll get weird issues like this. Instead you should encode timezones in the string you pass to new Date() in an ISO format like `2018-01-09T15:02:13+00:00` (where the `+00:00` at the end is the timezone offset of your date)

**Comment by hugocaldeira** [comment]
Hi,
I have tried with your examples and it is the same.
![3](https://user-images.githubusercontent.com/17253989/34773502-cc88b04e-f603-11e7-8541-fe3cca6d21b3.png)

HC

**Comment by mattlewis92** [comment]
Ah, thanks, I can reproduce, will look into it when I have some free bandwidth. Or if you wanted to take a stab at fixing it yourself you could add a failing test with those dates [here](https://github.com/mattlewis92/calendar-utils/blob/master/test/calendar-utils.spec.ts#L174) and then fix the problem in the `getWeekViewEventSpan` function [here](https://github.com/mattlewis92/calendar-utils/blob/master/src/calendar-utils.ts#L211). (Maybe changing line 233 to `span = differenceInDays(addDays(endOfDay(event.end), 1), begin) * SECONDS_IN_DAY;`)

**Comment by hugocaldeira** [comment]
Yes, it worked. Problem solved!
Thank you, Matt

Hugo.

**Comment by mattlewis92** [comment]
Fixed in 0.23.2, thanks for reporting! 😄
