### ISSUE TITLE
Can't get "this.view.period" in emitBeforeViewRender()  

### ISSUE THREAD

**Issue by IrinaGrev** [mattlewis92/angular-calendar#434]
<pre>
[+] Bug report 
[ ] Feature request
[ ] Support request => Please do not submit a support request here, please ask on https://stackoverflow.com/
</pre>

### Bug description / Feature request

Can't get this.view.period in the emitBeforeViewRender(). Only for 0.23.1v.
 
 
 
![image](https://user-images.githubusercontent.com/34774749/34872241-dfc6729a-f798-11e7-8e86-60b9090f5a1b.png)

### Versions

Angular: 5.2.0

Calendar library: 0.23.1

Browser name and version: Chrome, 63

**Comment by mattlewis92** [comment]
Any repro via plunker / stackblitz etc? It works in the [tests](https://github.com/mattlewis92/angular-calendar/blob/master/test/calendar-day-view.component.spec.ts#L1034-L1055) and on the [demo](https://mattlewis92.github.io/angular-calendar/#/no-events-label).

**Comment by IrinaGrev** [comment]
@mattlewis92 I don't have any code to present right now, but the issue is still reproduce. Maybe value of this helps you.
![image](https://user-images.githubusercontent.com/34774749/34877212-d5a50a78-f7ad-11e7-88bd-7552bf7d7b82.png)

**Comment by mattlewis92** [comment]
Sorry but that's not of any value to me, without a runnable plunker or something that clearly reproduces the problem I'm unable to work out what's going wrong. Will close this for now, if you're able to make a runnable repro then I'd be more than happy to help further 😄
