### ISSUE TITLE
Disable weekday programmatically 

### ISSUE THREAD

**Issue by justmelnyc** [mattlewis92/angular-calendar#435]
## I'm submitting a ...

<pre>
[ ] Bug report 
[x] Feature request
[ ] Support request => Please do not submit a support request here, please ask on https://stackoverflow.com/
</pre>

### Versions

Angular: 

Calendar library: 

Browser name and version: 

I want to be able to disable a weekday, without hardcoding it in.

**Comment by mattlewis92** [comment]
You can use the `excludeDays` input for this, demo here: https://mattlewis92.github.io/angular-calendar/#/exclude-days

**Comment by justmelnyc** [comment]
I meant disable the day, not remove it completely

**Comment by mattlewis92** [comment]
Oh ok, you can use the `beforeViewRender` output to add a css class to certain days to disable them. Something a bit like: https://mattlewis92.github.io/angular-calendar/#/min-max-date
