### ISSUE TITLE
When using a http get to get calendar reserved days I have to click on calendar for it to render

### ISSUE THREAD

**Issue by dolson334** [mattlewis92/angular-calendar#437]
## I'm submitting a ...

<pre>
[X] Bug report 
[ ] Feature request
[ ] Support request => Please do not submit a support request here, please ask on https://stackoverflow.com/
</pre>

### Bug description / Feature request

In my beforeMonthViewRender method I make a web cal to get reserved days. I then want to color the days reserved as gray. It seems to work but then the calendar renders as all days white until I click on a day and then the days are properly colored. Really stuck here and I assume this has worked somehow for others. 

### Versions

Angular: 

Calendar library: 

Browser name and version:

**Comment by mattlewis92** [comment]
You could use the `refresh` input to force the view to re-render, there's a demo [here](https://mattlewis92.github.io/angular-calendar/#/refreshing-the-view)

**Comment by dolson334** [comment]
Yes I tried that. I think the issue is I am using an async with an await on
my web call.
