### ISSUE TITLE
Wrong event position

### ISSUE THREAD

**Issue by yoomury** [mattlewis92/angular-calendar#440]
## I'm submitting a ...

<pre>
[x] Bug report 
[ ] Feature request
[ ] Support request => Please do not submit a support request here, please ask on https://stackoverflow.com/
</pre>

### Bug description / Feature request

I'm trying to show an event on the day view. The event is shown in a wrong date time range as you can see in the  screenshots.

https://cl.ly/22463P3G0Y3V

This is the event: https://cl.ly/1Y3T0G2g0i2i.
And this is the template: https://cl.ly/3i1b0c3N2v0y

### Minimal reproduction of the problem with instructions

I tried to create a separate repo or plunker for this, but I can't reproduce it there. I know that would help a lot and the screenshots are really vague, but maybe you have an idea.

### Versions

Angular: 5.2.1

Calendar library: 0.23.2

Browser name and version: Chrome 63.0.3239.132

**Comment by yoomury** [comment]
Including bootstrap didn't helped.

**Comment by mattlewis92** [comment]
It sounds like a timezone issue as your dates don't have timezones encoded into them, so UTC is assumed and will adjust to your local timezone: https://github.com/mattlewis92/angular-calendar/issues/428#issuecomment-355498487

**Comment by yoomury** [comment]
Tried that, did not helped.

**Comment by yoomury** [comment]
For some reason the hour segment has the height with '-1'px that the one I set. So for a `hourSegmentHeight=40` the actual height is 39. This '-1'px operation does not happen in my app, so the hackish solution was to set the height manually to 39px in `mwl-calendar-day-view-hour-segment, .cal-hour-segment`

**Comment by rubenheymans** [comment]
I have the same issue even when I set the dates like this:  start: new Date('Mon Jun 04 2018 11:00:00 GMT+0200 (Romance Daylight Time)')

How can we modify the position of the events?
What is we want a custom styled calendar how can we adjust the dayview height of the events (without using hourSegments)?

**Comment by sdstmi88** [comment]
Is it possible to use the week-view calendar completely independently of the client's time zone, that is, to use a specific time zone so that the start/end dayHour (00-23) refer to the local time of that defined time zone, not to the client's zone? 
Also I expect to get events mapped properly according to the specific time zone.

**Comment by fzs1994** [comment]
Why this issue is closed? I'm facing this issue in group events in day view. I'm using custom size for hour segment and my events are showing off the calendar
