### ISSUE TITLE
Customize the week view `.cal-header` and title

### ISSUE THREAD

**Issue by kuncevic** [mattlewis92/angular-calendar#441]
Currently the week view [looking like that ](https://mattlewis92.github.io/angular-calendar/#/kitchen-sink)
![acal1](https://user-images.githubusercontent.com/1283734/35313479-a92aae42-0114-11e8-9f96-ff5222737c08.png)

But I want that to looks like:
![acal2](https://user-images.githubusercontent.com/1283734/35313505-d31ae94c-0114-11e8-8327-ae9cbd3d0934.png)

I can't see a way to customize the `.cal-header` to take out the month from that as it is represents by like `<span>Jan 21</span>`  also wonder how to cusomize calendar title so I can display the current month or months range that appear on the current week view instead of showing `Wek Number of Year`.

**Comment by mattlewis92** [comment]
You can implement this by using a [custom template](https://github.com/mattlewis92/angular-calendar#how-do-i-use-a-custom-template) for the [week view header](https://github.com/mattlewis92/angular-calendar/blob/master/src/modules/week/calendar-week-view-header.component.ts). Hope that helps! 😄

**Comment by salimchami** [comment]
> You can implement this by using a [custom template](https://github.com/mattlewis92/angular-calendar#how-do-i-use-a-custom-template) for the [week view header](https://github.com/mattlewis92/angular-calendar/blob/master/src/modules/week/calendar-week-view-header.component.ts). Hope that helps!

Hi mattlewis92, thanks your response but the second link is broken. Can you fix it please ? thanks !

**Comment by mattlewis92** [comment]
Sure thing, the updated link is here: https://github.com/mattlewis92/angular-calendar/blob/master/projects/angular-calendar/src/modules/week/calendar-week-view-header.component.ts
