### ISSUE TITLE
previous-directive subFn is not a function

### ISSUE THREAD

**Issue by sch3bal** [mattlewis92/angular-calendar#442]
## I'm submitting a ...

<pre>
[x] Bug report 
[ ] Feature request
[ ] Support request => Please do not submit a support request here, please ask on https://stackoverflow.com/
</pre>

### Bug description

[https://stackoverflow.com/questions/48223713/angular-calendar-subfn-is-not-a-function](https://stackoverflow.com/questions/48223713/angular-calendar-subfn-is-not-a-function)

Error: `subFn is not a function` on click button with the `mwlCalendarPreviousView` directive

### Versions

Angular:
5

Calendar library: 
0.23.2

Browser name and version: 
Chrome 63

**Comment by mattlewis92** [comment]
It sounds like the value you're passing through to the `[view]` input of the directive is invalid, make sure you're passing one of `month`, `week` or `day`

**Comment by sch3bal** [comment]
It is `week`. With `month` and `day` it does not work either...

**Comment by sch3bal** [comment]
ok. I fixed it. Damn typos. 
Thank you for helping.

**Comment by DeanWilliamMills** [comment]
I am also getting this error. Using Angular 6 & angular-calendar 0.25.2. I checked if there were any typos, but nothing. Actually copied and paste the demo code

**Comment by DeanWilliamMills** [comment]
I found the issue and it fixed my problem:
https://stackoverflow.com/a/50436954/2081043

**Comment by YurkoUA** [comment]
@DeanWilliamMills Thanks, but I've already resolved it. I didn't pay attention that it's case sensitive.
