### ISSUE TITLE
use `trackBy` to prevent full DOM refresh and performance improvement

### ISSUE THREAD

**Issue by volser** [mattlewis92/angular-calendar#444]
<pre>
[ ] Bug report 
[x] Feature request
[ ] Support request => Please do not submit a support request here, please ask on https://stackoverflow.com/
</pre>

I noticed, when I d&d events DOM are totally refreshed, maybe use `trackBy` to prevent full DOM refresh and performance improvement?
http://recordit.co/yC4LF8jqFT

**Comment by mattlewis92** [comment]
I've considered this before as well. The problem is that events have no unique id property to track by, do you have any idea if the value returned by the track by function can be an object i.e. the event itself?

**Comment by volser** [comment]
I believe, by default angular use object instance to identify item. 

default:
`const trackByIdentity = (index: number, item: any) => item;`
https://github.com/angular/angular/blob/c8a1a14b87e5907458e8e87021e47f9796cb3257/packages/core/src/change_detection/differs/default_iterable_differ.ts



So you can add id property (optional) to event object, like fullcalendar did
https://fullcalendar.io/docs/event_data/Event_Object/

and return event.id ? event.id: event;

**Comment by mattlewis92** [comment]
Please give `0.23.3` a go, everything should now use ngFor's. Thanks for the suggestion! 😄
