### ISSUE TITLE
Calendar Event only match in correct space when putting calendar in full page size 

### ISSUE THREAD

**Issue by kevinding0218** [mattlewis92/angular-calendar#445]
Hello, first of all thank you very much for providing such wonderful calendar in angular 5! It was one of the amazing calendar I've seen so far! While I am exploring it in the real-world application, I found something interesting about the calendar events position in the calendar. The calendar events sit very well when you placed the calendar in full page size e.g, <div class="col-12">, however if you put it in partial of the view e.g <div class="col-9">, the position of the events seems like sitting in the wrong position, and if you drag and drop an event in that view, it will disappear. Is there anyone having same issue with me? Please feel free to share with your solution, thank you very much for looking into that!

**Comment by mattlewis92** [comment]
Hi there, please can you follow the issue template and attach a plunker or something similar that reproduces your issue, as without one it's impossible to help debug further. Thank you! 😄
