### ISSUE TITLE
change background of .cal-month-view .cal-open-day-events

### ISSUE THREAD

**Issue by 009topersky** [mattlewis92/angular-calendar#447]
Good Day sir.!

The Angular Calendar is a great tool ..
just a question..

is there a way i can change the background stated on Screenshot below.

![image](https://user-images.githubusercontent.com/5698315/35609811-db4325d2-0699-11e8-8baf-d14b224219c1.png)

FYI: i edit the background using chrome Inspect..

![image](https://user-images.githubusercontent.com/5698315/35609852-10bfd89a-069a-11e8-939c-63ac6528f273.png)

Thanks

Regards,
Topher

**Comment by mattlewis92** [comment]
It sounds like you've already solved your problem, you just need to add a global CSS rule to change the color 😄 
```
mwl-calendar .cal-open-day-events {
  background-color: hotpink;
}
```

**Comment by 009topersky** [comment]
how can i change the CSS each time i change my Toggle
Instance 1:
if its on the left the background should be Green
if its on the right the background should be Yellow 

I want to code it logically..

is there a way?? 

Thanks,
Topher

**Comment by mattlewis92** [comment]
You can do this by adding a CSS class to the root component:
```
<mwl-calendar-month-view class="yellow-slide-box">

mwl-calendar-month-view.yellow-slide-box .cal-open-day-events {
  background-color: yellow;
}
```
