### ISSUE TITLE
Safari issue

### ISSUE THREAD

**Issue by onurcelikeng** [mattlewis92/angular-calendar#448]
Hi,

Cell total info of calendar is not working on Safari browser.

**Comment by mattlewis92** [comment]
It works for me:
![screen shot 2018-01-31 at 12 26 10](https://user-images.githubusercontent.com/6425649/35623054-f3908ca0-0681-11e8-8d29-15010488dc16.png)

Please attach screenshots / a runnable repo that reproduces your issue and I'd be happy to debug more. Thanks! 😄
