### ISSUE TITLE
@ng-bootstrap - will it work with Angular 4+

### ISSUE THREAD

**Issue by kiranuidev** [mattlewis92/angular-calendar#449]
Is ng-bootstrap/bootstrap compatible with angular 4+? From https://ng-bootstrap.github.io/#/getting-started -  It says minimum requirement is  angular 5+, if so can you please provide a alternate for ng-bootstrap to be used with Angular 4+. Would be very grateful if you could provide me a working demo for angular-calendar 0.22.3 with 4.x. 

I am getting a error which say's mwl-demo-utils-date-time-picker is not a angular component. 

PS: I could implement the same in 5.x successfully, but my requirement is for 4.x. 

Thanks in advance!!

## I'm submitting a ...

<pre>
[ ] Bug report 
[ ] Feature request
[ ] Support request => Please do not submit a support request here, please ask on https://stackoverflow.com/
</pre>

### Versions

Angular: 

Calendar library: 

Browser name and version: 

- [ ]

**Comment by mattlewis92** [comment]
Hi there! ng-bootstrap isn't actually a dependency of this library, it's solely used for the demo (hence the error you get when you try and use the `mwl-demo-utils-*` component in your app). The last version of ng-bootstrap to support angular 4 is [`1.0.0-beta.6`](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CHANGELOG.md#100-beta6-2017-12-01)
