### ISSUE TITLE
datepicker functionality

### ISSUE THREAD

**Issue by jl91** [mattlewis92/angular-calendar#451]
Hi guys, morning. So let me ask you guys one thing. This module can provides me functionalities like a "jquery-datepicker" for example? I'm searching for a ng4+ component that provides me a datepicker. 

So if it can provides me a datepicker functionality, let me know! Thx see yah!

**Comment by mattlewis92** [comment]
I wouldn't really recommend using this lib as a datepicker, it's meant to be used more as a scheduling tool. I would recommend something like this instead: https://github.com/mattlewis92/angularx-flatpickr
