### ISSUE TITLE
How to set initial date as dayClicked

### ISSUE THREAD

**Issue by linflux** [mattlewis92/angular-calendar#452]
Hi, i'd like to know how to set initial date as selected day.
I already know and use the output dayClicked but what i need is to set the initial date with same fomat (cal-day-selected CSS class).
There is a way to convert a Date into CalendarMonthViewDay?
PS: Don't find nothing on stackoverflow.

Using:
Angular 4.4.6
angular-calendar 0.22.3

**Comment by mattlewis92** [comment]
You can use the `beforeViewRender` output to access an array of all the days in the current view and extract the one you want from there. There is a demo here: https://mattlewis92.github.io/angular-calendar/#/before-view-render Hope that helps! 😄
