### ISSUE TITLE
In ambient enum declarations member initializer must be constant expression

### ISSUE THREAD

**Issue by cdanisuarez** [mattlewis92/angular-calendar#453]
Hi, I'm installing the _angular-calendar_, but this error appears:

`ERROR in /home/danielas/Documentos/thundera/thundera-frontend-obranza/node_modules/calendar-utils/dist/calendar-utils.d.ts (164,16): In ambient enum declarations member initializer must be constant expression.
ERROR in /home/danielas/Documentos/thundera/thundera-frontend-obranza/node_modules/calendar-utils/dist/calendar-utils.d.ts (165,28): In ambient enum declarations member initializer must be constant expression.
ERROR in /home/danielas/Documentos/thundera/thundera-frontend-obranza/node_modules/calendar-utils/dist/calendar-utils.d.ts (166,28): In ambient enum declarations member initializer must be constant expression.
ERROR in /home/danielas/Documentos/thundera/thundera-frontend-obranza/node_modules/calendar-utils/dist/calendar-utils.d.ts (167,26): In ambient enum declarations member initializer must be constant expression.
ERROR in /home/danielas/Documentos/thundera/thundera-frontend-obranza/node_modules/calendar-utils/dist/calendar-utils.d.ts (168,23): In ambient enum declarations member initializer must be constant expression.
`

**Comment by mattlewis92** [comment]
It sounds like you might be running an older version of typescript, please sure you are using at least typescript 2.4 or above 😄
