### ISSUE TITLE
Custom Calendar view for Day, Week and Month with Image

### ISSUE THREAD

**Issue by 009topersky** [mattlewis92/angular-calendar#454]
Good Day sir!

is the Angular Calendar module can be customized like this.

Month View 
![image](https://user-images.githubusercontent.com/5698315/35718365-18f45672-081f-11e8-9923-e6fde108072a.png)

Week View
![image](https://user-images.githubusercontent.com/5698315/35718416-6759e890-081f-11e8-951f-7261751e2200.png)

Day View:
![image](https://user-images.githubusercontent.com/5698315/35718432-7fd7372e-081f-11e8-94fb-8049502caedd.png)

FYI: this changes is made by Paint

Regards, 
topher .

**Comment by mattlewis92** [comment]
I think this should be possible by using [custom templates](https://github.com/mattlewis92/angular-calendar#how-do-i-use-a-custom-template) for these 3 components:
* https://github.com/mattlewis92/angular-calendar/blob/master/src/modules/month/calendar-open-day-events.component.ts
* https://github.com/mattlewis92/angular-calendar/blob/master/src/modules/week/calendar-week-view-event.component.ts
* https://github.com/mattlewis92/angular-calendar/blob/master/src/modules/day/calendar-day-view-event.component.ts
