### ISSUE TITLE
Unable to create week and day custom view

### ISSUE THREAD

**Issue by anurag1209** [mattlewis92/angular-calendar#456]
Hi. I have an issue that i am struggling with and I am new to angular 4 . As provided in the image i need week and day to have the time on the left side of the calendar with cells. I have seen issue #269 but was unable to replicate the same as I am using angular cli in my project. In the [plunker](http://plnkr.co/edit/e3cFy9Nb2xsLx4Txv4NV?p=preview) that you provided you were using the keyword **[cellTemplate]="customCellTemplate"** and in the documentation of custom template [doc](https://mattlewis92.github.io/angular-calendar/#/custom-templates) it mentions another keyword(**[cellTemplate]="customCellTemplate"**). I am little confused on what to do. 
The following is the image that I need to achieve the below for both week view and day view.  I would really appreciate if you could help me out in this issue. If possible a solution in angular cli.

Thanks
![pro](https://user-images.githubusercontent.com/18526147/35766944-22ac3394-0908-11e8-9ced-e810b926b9c5.png)

**Comment by ambujsharma23** [comment]
Yeah I too want week custom view having timeline (like day view) on the left. Can It be worked around ?

**Comment by mattlewis92** [comment]
Please see this answer on how you might go about implementing your own custom week view: https://github.com/mattlewis92/angular-calendar/issues/319#issuecomment-325914732

**Comment by anurag1209** [comment]
I have implemented the plunkr that you provided and it did the job but its giving an error of some interface problem due to which i am not able to create a build for the project. Can you pls look
Error: `Property 'users' doesn't exist on type DayView`. Same error when `ng build --prod`
![proman](https://user-images.githubusercontent.com/18526147/35798277-4d141b34-0a88-11e8-86dc-06cc4497d9bc.png)

**Comment by mattlewis92** [comment]
You can try using the escape hatch in TS `view['users']` instead

**Comment by ankitjs** [comment]
@mattlewis92  This worked. Overall it worked for me . Thanks . But there is one problem i am currently facing. If the user adds two events on same date and same time, it gets overlapped . I have tried my best with css but not working. Can you please suggest an idea

**Comment by jdudleyie** [comment]
@ankitjs were you able to complete this? If so it would be very useful if you are happy to share the result - thanks.
