### ISSUE TITLE
Events displayed under the incorrect day

### ISSUE THREAD

**Issue by IterationCorp** [mattlewis92/angular-calendar#457]
## I'm submitting a ...

<pre>
[x] Bug report 
[ ] Feature request
[ ] Support request => Please do not submit a support request here, please ask on https://stackoverflow.com/
</pre>

### Bug description / Feature request
Some days are displayed 2 twice : on the correct day and on the next day. 

### Minimal reproduction of the problem with instructions
Injecting
start : Sat Feb 03 2018 22:00:00 GMT+0100 (CET) 
end : Sat Feb 03 2018 23:00:00 GMT+0100 (CET)

This event is displayed under the 3 and the 4 Feb.

### Versions

Angular: 5.2.2

Calendar library: 0.23.3

Browser name and version: Google Chrome 63

[Please see here...](https://www.dropbox.com/s/tc2g7mi6t6ot3d6/Screen%20Shot%202018-02-03%20at%2022.20.46.png?dl=0)

**Comment by mattlewis92** [comment]
Hi there, unfortunately I was unable to reproduce your problem from the information provided:
<img width="1153" alt="screen shot 2018-02-04 at 15 27 52" src="https://user-images.githubusercontent.com/6425649/35779131-0dff22ae-09c0-11e8-999c-16882bd79a59.png">

Please follow the issue template a provide a runnable plunker that reproduces your issue and I would be happy to help debug more. Thanks! 😄
