### ISSUE TITLE
Day view cannot scroll using ipad

### ISSUE THREAD

**Issue by penny-loh** [mattlewis92/angular-calendar#458]
When I try the demo day view, I cannot scroll when I click within the hours portion using ipad. Please advise. Thanks

**Comment by mattlewis92** [comment]
Thanks for reporting, should be fixed now in `0.23.4`

**Comment by AstRonin** [comment]
Same behavior on v. 0.26.4 and even on [official page](https://mattlewis92.github.io/angular-calendar)
