### ISSUE TITLE
angular-calendar.d.ts.ɵk.html:18 ERROR TypeError: Cannot read property 'primary' of undefined (Angular 5.1)

### ISSUE THREAD

**Issue by woonandez** [mattlewis92/angular-calendar#460]
This error occurs with status front end data, or with observable usage.  

The data is properly formatted.  

I noticed this issue occurred in previous versions of Angular, and Angular Calendar.  

Any help for this would be greatly appreciated!

angular-calendar.d.ts.ɵk.html:18 ERROR TypeError: Cannot read property 'primary' of undefined
    at Object.eval [as updateRenderer] (angular-calendar.d.ts.ɵk.html:21)
    at Object.debugUpdateRenderer [as updateRenderer] (core.js:14727)
    at checkAndUpdateView (core.js:13841)
    at callViewAction (core.js:14187)
    at execEmbeddedViewsAction (core.js:14145)
    at checkAndUpdateView (core.js:13837)
    at callViewAction (core.js:14187)
    at execEmbeddedViewsAction (core.js:14145)
    at checkAndUpdateView (core.js:13837)
    at callViewAction (core.js:14187)

**Comment by mattlewis92** [comment]
It sounds like one or more of your events is missing the `color` object. Every event needs to have one set like:
```
color: {
    primary: '#ad2121',
    secondary: '#FAE3E3'
}
```

**Comment by etwillbefine** [comment]
For consideration: In our project we load based on users settings a different style template. I think it would be cool to add some default values to the events (whatever looks nice when using a "non-customized" calendar) 
In our case we wouldn't need to specify some "random colors" and override them later on via css and on the other side people don't need to configure colors if not needed (imagine the event dto looks similar besides the colors... :D)

**Comment by woonandez** [comment]
Hey guys thank you for the support.  I was missing the color object.  When I added a default color to each item it rendered (without errors).

I think it would be cool to add some default values to the event to our project too

**Comment by Worthy7** [comment]
Can we make a better error - or at change the interface:
`color?: EventColor;`
to be 
`color: EventColor`
