### ISSUE TITLE
Day view not showing event name if the event is of 5 minutes

### ISSUE THREAD

**Issue by ymkh99** [mattlewis92/angular-calendar#462]
I am using this calendar to show the meetings and the meetings can be minimum of 5 minutes.
Please find the attached image and let me know if you have any suggestion.

![dayview](https://user-images.githubusercontent.com/36424356/36121737-0992dee2-103f-11e8-905f-3d8899359f36.PNG)

Thanks

**Comment by mattlewis92** [comment]
This is kind of by design, as the height is relative to the events duration. You could add a min height to the event to workaround this:
```
.cal-day-view .cal-event {
  min-height: 30px;
}
```

Hope that helps! 😄
