### ISSUE TITLE
Getting Error : rrule_1.default is not a constructor

### ISSUE THREAD

**Issue by prashant-shilimkar** [mattlewis92/angular-calendar#463]
Getting following error : 
core.js:1440 ERROR TypeError: rrule_1.default is not a constructor

Error is generated by code snippet,
```
const rule: RRule = new RRule(
  Object.assign({}, recurringEvent.rrule, {
     dtstart: startDate,
      until: endDate
  })
);
```

And also it it showing error for following line,
```
rrule: {
     freq: RRule.WEEKLY,   // core.js:1440 ERROR TypeError: Cannot read property 'WEEKLY' of undefined
     bymonthday: 5
 }
```
I have referred following plunker and there it seems to be working,
[https://plnkr.co/edit/?p=preview](url)

How I can fix this issue?

I am using,

Angular : 5.2.0
rrule: 2.2.0,
angular-calendar: 0.23.6

**Comment by mattlewis92** [comment]
It sounds like the rrule import is wrong, try
```
import * as RRule from 'rrule';
```

instead of 
```
import RRule from 'rrule';
```

**Comment by prashant-shilimkar** [comment]
Thanks ;) it worked.
