### ISSUE TITLE
Changing name of the day from Monday to Mon

### ISSUE THREAD

**Issue by AnkitaNN** [mattlewis92/angular-calendar#465]
I want to change the name of the day like Monday, Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday should be displayed as Mon,Tue,Wed,Thu,Fri,Sat,Sun. Please provide a solution to do the same.

**Comment by itafraji** [comment]
Check the examples. Custom date format is exactly what you need.

**Comment by AnkitaNN** [comment]
Thank you.
