### ISSUE TITLE
Removing color key from events: CalendarEvent[] 

### ISSUE THREAD

**Issue by AnkitaNN** [mattlewis92/angular-calendar#468]
In events: CalendarEvent[] we have colors,start,end,title,etc but I don't want colors in the keys. Is it possible to do so?

**Comment by mattlewis92** [comment]
The color property is required as without it events wouldn't display as they would be transparant.

**Comment by etwillbefine** [comment]
What about a default color which fits to the current theme (eg: blue/green from calendar header) as mentioned here https://github.com/mattlewis92/angular-calendar/issues/460#issuecomment-364757759. 

I'm also happy to do these changes if its desired.

**Comment by mattlewis92** [comment]
@etwillbefine yeah sure I'm open to this, I think it should be as simple as adding some additional css to the sass files with some default colors and then making the `color` property optional in the `CalendarEvent`. Would you be so kind as to send a PR? 😄

**Comment by etwillbefine** [comment]
Sure. Might take a few days (2-5) to find some free time.
