### ISSUE TITLE
I need to add angular-calendar in my systemjs.config.js file as it is throwing a error Error: Fetch error: 404 Not Found   Instantiating http://localhost:3000/angular-calendar   Loading http://localhost:3000/app/app.module.js   Loading app     at system.src.js:1475     at ZoneDelegate.invoke (zone.js:388)     at Zone.run (zone.js:138)     at zone.js:858     at ZoneDelegate.invokeTask (zone.js:421)     at Zone.runTask (zone.js:188)     at drainMicroTaskQueue (zone.js:595)     at <anonymous>

### ISSUE THREAD

**Issue by teja-315** [mattlewis92/angular-calendar#469]
## I'm submitting a ...

<pre>
[ ] Bug report 
[ ] Feature request
[ ] Support request => Please do not submit a support request here, please ask on https://stackoverflow.com/
</pre>

### Versions

Angular: 

Calendar library: 

Browser name and version:

**Comment by mattlewis92** [comment]
Please see the system.js example: https://github.com/mattlewis92/angular-calendar/tree/master/build-tool-examples/systemjs
