### ISSUE TITLE
Feature request for drag and drop external events  & custom header template for Week View

### ISSUE THREAD

**Issue by kaushikparmar** [mattlewis92/angular-calendar#471]
## I'm submitting a ...

<pre>
[ ] Feature request
</pre>

### Feature request

We are having requirement for drag and drop external event in "week view".

Every time we need to drag event and drop event on date, on header.

(1) I require that dropping should be possible under the date below header.
     Right now it is not possile.
  (Here I am talking about WeekView only)

  Visit the following link and check under WeekView
https://mattlewis92.github.io/angular-calendar/#/draggable-external-events

(2) Currently, row is created under the header when event is droped.
   I require a column structure instead.

(3) Also require custom template for header design modification for the Week View

(4) When adding calendar template, we provide single date in ViewDate  like: [viewDate]="viewDate"
     and calendar header is generated for the week.
     Instead of that I want to provide Range of date like start-date and end-date and header should 
     cover that much of dates only in the header from range (not entire week).

- For example: we have following scenario, see the attached image.

![1](https://user-images.githubusercontent.com/4065424/37079208-cdace79e-2207-11e8-8c2c-fe0648fd7777.PNG)

### Versions

Angular: 5.0.3

Calendar library: 0.22.3 or above

Browser name and version: Google Chrome  64.0.3282.186 (Official Build) (64-bit)

**Comment by mattlewis92** [comment]
I think you would have a hard time implementing these requirements with this calendar, you would probably be better of building your own substitute week view component to use in place of the one provided by this calendar.

**Comment by kaushikparmar** [comment]
Yes. You are right. I faced lots of difficulties.
