### ISSUE TITLE
DayView as scheduler aka. timeline (days on X axis, groups on the left)

### ISSUE THREAD

**Issue by lordgreg** [mattlewis92/angular-calendar#476]
## I'm submitting a ...
<pre>
[ ] Bug report 
[X] Feature request
[ ] Support request => Please do not submit a support request here, please ask on https://stackoverflow.com/
</pre>

### Bug description / Feature request
I've almost broke my keyboard trying to figure our custom templating for different views. My issue is I'd like to create a custom view for DAY view where X axis should show hours (quarter based) and the left side- groups (group A, B, C etc.).

This is something Fullcalendar calls [Timeline view](https://fullcalendar.io/docs/timeline-custom-view-demo)

Can something like this be achieved? So far, I didn't find any customizings on a daily view basis.

### Versions
Angular: 5.2.0
Calendar library: 0.23.6
Browser name and version: any

**Comment by Zahid-Ashiq** [comment]
Hi @mattlewis92 
i also want something like. In future, is coming any release? or guide me how is it possible to achieved this view? On X-axis showing resource and y-axis day time.  

![image](https://user-images.githubusercontent.com/11837524/37642681-ed9b6ea8-2c3f-11e8-8f6f-6ba76ec80652.png)

Thanks

**Comment by etwillbefine** [comment]
In previous issues the solution was to introduce your own component using the dynamic templates. The reason is that the owner doesn't want to increase complexity. The calendar is customizable in a really good way.

See also: https://github.com/mattlewis92/angular-calendar/issues/319#issuecomment-325914732
