### ISSUE TITLE
Lost 1 hour for 25 March 2018 in day view

### ISSUE THREAD

**Issue by lespons** [mattlewis92/angular-calendar#477]
### Bug description / Feature request
Lost 1 hour for 25 March 2018 in day view;
![image](https://user-images.githubusercontent.com/4096429/37349821-92dd6e66-26d7-11e8-860d-d8139659fbe7.png)

### Minimal reproduction of the problem with instructions
I have Belgium local on my PC
Go to https://mattlewis92.github.io/angular-calendar/#/kitchen-sink and select 25 March 2018

### Versions

Angular: 

Calendar library: 

Browser name and version: Google Chrome Version 64.0.3282.186 (Official Build) (64-bit)

**Comment by etwillbefine** [comment]
Pretty sure this is desired and due to the timeshift on 25. march. (+1 hour, from 2am to 3am).

**Comment by lespons** [comment]
@etwillbefine I understand. But It's normal behaviour?

**Comment by etwillbefine** [comment]
Hmm thinking about it twice .. logically it makes sense but to the end-user it doesnt. It also doesnt seem to be a common thing. 

Here is a failing test case: https://github.com/mattlewis92/calendar-utils/compare/dst-change-in-hour-grid?expand=1

The dates set in each of the hour grids are timezone dependent (2 is skipped). Theoretically if you use UTC as `viewDate` you should be able to see the missing hour (haven't tried it yet).

**Comment by mattlewis92** [comment]
I just had a check on other calendars and they don't work like this either, I wonder if there's an easy way to fix this with date-fns rather than hacking in a solution to add fake hours

**Comment by mattlewis92** [comment]
`0.26` is now out and allows you to use moment instead of date-fns. You can then set the timezone to `Utc` which will avoid any DST issues. I put together an example of this for you here: https://stackblitz.com/edit/angular-cbxyqr?file=demo/component.ts Hope that helps! 😄

**Comment by mattlewis92** [comment]
This is now (finally) solved out the box in version `0.27.18` 🎉

**Comment by horsebuzz** [comment]
For some reason current time marker becomes unavailable when `moment` is used. Even on the documentation demo current time marker does not work. (Use moment)[https://mattlewis92.github.io/angular-calendar/#/moment]

Is there a way to fix it or any workaround it
