### ISSUE TITLE
question about use angular-bootstrap-calendar in angular1

### ISSUE THREAD

**Issue by Ayana7** [mattlewis92/angular-calendar#478]
<mwl-calendar
    view="$ctrl.calendarView"
    week-days="[1,2,3,4,5,6,7]"
    view-date="$ctrl.viewDate"
    events="$ctrl.events"
    view-title="$ctrl.calendarTitle"
    on-event-click="$ctrl.eventClicked(calendarEvent)"
    on-event-times-changed="$ctrl.calendarEvent.startsAt = calendarNewEventStart; calendarEvent.endsAt = calendarNewEventEnd"
    custom-template-urls="{calendarMonthCell: '/client/app/common/calendar/_template/month.html'}"
    cell-modifier="$ctrl.cellModifier(calendarCell)"
    slide-box-disabled="true">
</mwl-calendar>

cellModifier(cell) {
    if (this.eventData){
      console.log(0)
      Object.assign(cell, {
        isHoliday: false,
        isWorkDay: false,
        eventData: []
      }, this.checkHoliday(cell.date));
    }
  }

  checkHoliday(date) {
    console.error(1)
    if (this.eventData){
      const day1 = date.format('YYYY-MM-DD');
      const day2 = date.format('YYYY-M-D');
      return {
        isHoliday: this.Holiday.indexOf(day1) > -1 || this.Holiday.indexOf(day2) > -1,
        isWorkDay: this.Workday.indexOf(day1) > -1 || this.Workday.indexOf(day2) > -1,
        eventData: this.dataF(this.eventData, day1)
      };
    }
  }

  dataF(data, day1){
    console.log(2)
    if(data){
      for (let aa of data) {
        if (moment.unix(aa.day).format('YYYY-MM-DD') == day1) {
          console.log(aa)
          return aa
        }
      }
    }
  }

about my question is:
"cellModifier(calendarCell)" function when will it be executed，can I trigger him to change? because the this.eventData data is obtained from the interface。Thanks

**Comment by etwillbefine** [comment]
Sorry, I can't really understand your question. This repository is for the new angular5+ calendar only. The old [bootstrap calendar](https://github.com/mattlewis92/angular-bootstrap-calendar) is no longer maintained.
