### ISSUE TITLE
How can i bind events based in results from API

### ISSUE THREAD

**Issue by joaolori** [mattlewis92/angular-calendar#479]
Hello
How can i bind events based in results from API?
I have created same model (start/end/title)
But its saying i should convert start/end to javascript date.

angular-calendar.js:39 angular-calendar Event `start` property should be a javascript date object. Do `new Date(event.start)` to fix it. {title: "Booking", start: "2018-03-18T15:00:00", end: "2018-03-18T16:00:00"}

**Comment by etwillbefine** [comment]
The error is very clear. The result from your API is a **string** representing a date. To convert it into a js date use `new Date("date string from API")`

If you need more help I recommend that you take a look into the [documentation](https://mattlewis92.github.io/angular-calendar/#/async-events). As mentioned in the issue template please use stackoverflow for general questions.
