### ISSUE TITLE
Duplicate/missing day in month view for local with DST

### ISSUE THREAD

**Issue by mikljacq** [mattlewis92/angular-calendar#481]
### Bug description / Feature request

The bug only occurs with IE.

When the calendar is in month view with a regional setting having DST (FR for example), the day DST is applied is duplicated or missing.

For 2018, the 25th March is duplicated and the 28th October is missing.

![capture](https://user-images.githubusercontent.com/37588109/37697341-a118e734-2cdc-11e8-8c9c-c044ae9ef9fd.PNG)

### Versions

Angular: 5.1.0

Calendar library: 0.23.7

Browser name and version: IE11 and IE Edge

**Comment by mattlewis92** [comment]
This sounds like a bug with IE / edges `Date` implementation, I'm not sure if it's possible to fix it here, but I'll see what I can do 😄

**Comment by mattlewis92** [comment]
`0.26` now allows you to use moment instead of date-fns which should fix this issue. You can see an example of how to use moment here: https://mattlewis92.github.io/angular-calendar/#/moment Hope that helps!
