### ISSUE TITLE
 Class 'CalendarPage' incorrectly implements interface 'OnInit'

### ISSUE THREAD

**Issue by KaliName** [mattlewis92/angular-calendar#484]
Hi there,

![image](https://user-images.githubusercontent.com/36970533/37826340-f0fcf4c0-2e8a-11e8-9b92-f0c800905845.png)
 
For some reason it complain on OnInit.

I'm trying to build it in ionic.

**Comment by mattlewis92** [comment]
Hi there, you need to either remove the interface or implement the `ngOnInit` method. For more info checkout the angular docs on this: https://angular.io/guide/lifecycle-hooks Hope that helps! 😄
