### ISSUE TITLE
All day event in week view

### ISSUE THREAD

**Issue by IterationCorp** [mattlewis92/angular-calendar#486]
## I'm submitting a ...
<pre>
[x ] Feature request
</pre>

### Bug description / Feature request
Please display "all day" event in "week" view also. I can see "All day" events in month and day view, but not in week view, why? Or is there a "workaround"?

**Comment by mattlewis92** [comment]
Sorry I'm not sure I follow you, please would you mind explaining a bit more? Thanks! 😄

**Comment by IterationCorp** [comment]
![alldayevent](https://user-images.githubusercontent.com/6637470/37866210-b514efaa-2f87-11e8-95d7-9a29cc84b07f.jpg)
Maybe a picture will help... same event of "all day" type, displayed in day and month view, can't see it in week view...

**Comment by mattlewis92** [comment]
Strange, it works for me, are you able to share a runnable repro via plunker etc?
![screen shot 2018-03-26 at 10 46 59](https://user-images.githubusercontent.com/6425649/37899291-0d7968d6-30e3-11e8-83a2-f87ba5fc7ae0.png)

**Comment by IterationCorp** [comment]
Hello, 
I hosted it here : http://www.thecars.ch/sagenda/
You can let "One day of all day" in the dropdownlist and switch between "Month / Week / Day", week give nothing...

**Comment by mattlewis92** [comment]
hmm I can reproduce it on your live app, but not on a plunker: https://plnkr.co/edit/Wat7L0ZPZUfHYk8viBW5?p=preview

Can you reproduce it via a plunker? Without some actual code to run, it's really hard to debug otherwise. Thanks! 😄

**Comment by IterationCorp** [comment]
I found it, if I set a "end" date, it works in month and day, but not in week! I just set "end" if "allDay" is false and then it's ok. A bit strange behavior, I can understand that we should not set "end" date but in this case it shouldn't work at all (not in Month nor in day view). Thanks anyway.

**Comment by mattlewis92** [comment]
Odd it still works for me with or without the end date set. Oh well I'm glad you found a solution 😄
