### ISSUE TITLE
Drag and drop an event on the same day

### ISSUE THREAD

**Issue by cosf87** [mattlewis92/angular-calendar#487]
## I'm submitting a ...
<pre>
[x] Bug report
[ ] Feature request
[ ] Support request => Please do not submit a support request here, please ask on https://stackoverflow.com/
</pre>

### Bug description / Feature request
Calendar month view
If you drag an event and drop it on the same day, day click event is fired after drop event. 
It works fine when you drag and drop an event from one day to another day, because only drop event is fired.

### Versions

Angular: 5.2.9

Calendar library: 0.23.7

Browser name and version: Google Chrome 65.0.3325.181

**Comment by mattlewis92** [comment]
Ah I can reproduce, will try and find a fix, thanks! 😄
