### ISSUE TITLE
Day view empty for async events

### ISSUE THREAD

**Issue by ozhovnir** [mattlewis92/angular-calendar#488]
I'm building on foundations of the demo for async events - https://mattlewis92.github.io/angular-calendar/#/async-events, however, my day view is empty, just like it is in the demo. Is there a reason why day view with async shows no events, even though they are shown in monthly and weekly templates?

**Comment by mattlewis92** [comment]
Hi there, it works for me, please can you attach a runnable repro? Thanks!
<img width="996" alt="screen shot 2018-03-27 at 17 02 28" src="https://user-images.githubusercontent.com/6425649/37979498-a897357a-31e0-11e8-9e60-46e62250e9ab.png">

**Comment by ozhovnir** [comment]
Hmm, for me the day view of the async demo has no events, I tried on multiple browsers and devices. Am I missing something? - https://mattlewis92.github.io/angular-calendar/#/async-events

**Comment by mattlewis92** [comment]
That's odd, what timezone are you in?

**Comment by ozhovnir** [comment]
America/New_York (eastern time zone). You're actually seeing events in the day view of the async demo?

**Comment by mattlewis92** [comment]
Yes I can see events on that demo (see the screenshot here: https://github.com/mattlewis92/angular-calendar/issues/488#issuecomment-376580268)

**Comment by ozhovnir** [comment]
That's very odd, especially considering that I am able to see day view events in other demos. I'm sure I'm not the only one having this problem, what do you think the issue is?

**Comment by mattlewis92** [comment]
Ah it is a timezone issue, if I change my local timezone to new york time then the events don't appear. I would imagine it's because the async events demo doesn't have timezones encoded as it does `new Date('2018-03-29')`. I will mess about and see what I can come up with 😄

**Comment by ozhovnir** [comment]
Not sure when you plan on working on this, but could you let me know what needs to be done to get this fixed up and maybe I can do that for you?

**Comment by mattlewis92** [comment]
Finally had the time to look into this one, it's caused by there being no timezone in the value passed to `new Date()` so it defaults the timezone to UTC and because your timezone is behind the events effectively end up on the previous day. I've just added this to the demo which will force all events into your local timezone: https://github.com/mattlewis92/angular-calendar/commit/b0ebcd54e4762b192789992adcf1cde37797b80e Hope that helps! 😄

**Comment by hmedhe** [comment]
Hello,
I am using the same syntax but still day view is empty,

here the console  data,

end: Wed Nov 20 2019 17:00:00 GMT+0530 (India Standard Time) {}
resizable: {beforeStart: true, afterEnd: true}
start: Sat Nov 16 2019 16:00:00 GMT+0530 (India Standard Time) {}

![image](https://user-images.githubusercontent.com/38524958/69223127-c1a96b00-0ba0-11ea-9cc8-2939efc7885e.png)
