### ISSUE TITLE
How Can I add another event paramter beside the title ?

### ISSUE THREAD

**Issue by mohabnadim** [mattlewis92/angular-calendar#490]
How Can I add another event paramter beside the title that appears on day click event

**Comment by etwillbefine** [comment]
You can use the `meta` property. You can even use typings for your additional data.

```
interface MyData {
  prop: string
//...
}

const evt = new CalendarEvent<MyData>();
evt.meta.prop = "my string"
```

**Comment by mohabnadim** [comment]
![screen shot 2018-04-05 at 11 10 05 pm](https://user-images.githubusercontent.com/26406524/38392143-c2607b36-3926-11e8-978b-58a4cf8d45e4.png)


I would like it to be added beside the name that appears on clicking an event

**Comment by etwillbefine** [comment]
Use the meta property in combination with the [EventTitleFormatter](https://mattlewis92.github.io/angular-calendar/docs/classes/CalendarEventTitleFormatter.html)
