### ISSUE TITLE
how to define custom event template in week view

### ISSUE THREAD

**Issue by amineparis** [mattlewis92/angular-calendar#492]
how to get event attributes in the template ?

**Comment by mattlewis92** [comment]
Please see the readme for how to create a custom template for any component: https://github.com/mattlewis92/angular-calendar#how-do-i-use-a-custom-template

**Comment by sapabg** [comment]
@mattlewis92 there is only custom cell template for month view shown in the example page you've posted...
How do we get the event in the week or day templates? I've tried let-day="day" let-event="event"...any help? I think that's what @chaouiy ment too...

<ng-template
  #eventTemplate 
  let-events="events"
  let-event="event"
  let-day="day"
  let-eventClicked="eventClicked">
  <div>
    {{ day | json }} {{ events | json }} {{ event | json }}
  </div>
</ng-template>

<mwl-calendar-week-view
    *ngSwitchCase="CalendarView.Week"
    [eventTemplate]="eventTemplate"
    ......
></mwl-calendar-week-view>

none of the variables are accessable and there is nothing shown...

**Comment by temaisgod** [comment]
As addicional info this are properties to set a event-template to day and week view:

https://github.com/mattlewis92/angular-calendar/blob/a5fe1f975ecf332c96797326f48081e5d02d264d/projects/angular-calendar/src/modules/day/calendar-day-view-event.component.ts#L11-L52

**Comment by temaisgod** [comment]
for example:

`
<mwl-calendar-week-view
       ...
      [eventTemplate]="templatePlan"
    >
    </mwl-calendar-week-view>
    <mwl-calendar-day-view
      ...
      [eventTemplate]="templatePlan"
    >
    </mwl-calendar-day-view>

<ng-template #templatePlan let-weekEvent="weekEvent">
  <div (click)="debugConsole(weekEvent)">
    Evento es: {{weekEvent ? weekEvent.title : null}}
  </div>
</ng-template>

`
