### ISSUE TITLE
css issue doc fix

### ISSUE THREAD

**Issue by miramardesign** [mattlewis92/angular-calendar#496]
**Next include the CSS file somewhere into your app:

node_modules/angular-calendar/css/angular-calendar.css**

Should probably read: 

**@import "../node_modules/angular-calendar/css/angular-calendar.css";
at a low level such as styles.css  in the root directory:**

 _and not at the component level. (i was trying forever to add it to a component file) 
new to angular component scoped css. (which flies in the face of css convention)_

## I'm submitting a ...

<pre>
[ ] Bug report 
[ ] Feature request
[ ] Support request => Please do not submit a support request here, please ask on https://stackoverflow.com/
</pre>

### Versions

Angular: 

Calendar library: 

Browser name and version:

**Comment by mattlewis92** [comment]
Thanks for the suggestion, I've updated the readme now :)
