### ISSUE TITLE
undefined on eventClicked

### ISSUE THREAD

**Issue by MarcoBatista** [mattlewis92/angular-calendar#497]
Angular: 5

Calendar library: 0.23.7 

Hello, I don't know if is a bug or just a bad implementation.
When I try to access to meta in CalendarEvent meta is undefined

Fatal Error!
An unresolved error has occured. Do you want to reload the page to correct this?
Error: undefined is not an object (evaluating 'event.meta')

And I can access the property id on meta object

=== Code

events: Array<CalendarEvent<{ evento: Agenda }>>;
(.....)
loadEvents(){

      let dataInicio = new Date(this.viewDate.getFullYear(), this.viewDate.getUTCMonth(), 1,);
      let dataTermo = new Date(this.viewDate.getFullYear(), this.viewDate.getUTCMonth()+1, 0);
     
      this.calendarService.GetAllEvents(beginDate, endDate).
          subscribe(
              results=> this.onDataSucessFullLoad(results), 
              error=>this.onDataLoadFailed(error, "erroooooorrrrr")
            );
       
    }

onDataSucessFullLoad(results: Agenda[]){

        this.events = [];
        let i =0;
        for ( i =0; i<results.length; i++){
          let evento = results[i];
          this.events.push(
            {
              start: new Date(evento.start),
              //end: new Date (results[evento].end),
              title: evento.title,
              color: colors.yellow, 
              meta: {
                evento
              }
            });
        }
       
        this.refresh.next();      
    }

    eventClicked(event: CalendarEvent<{ evento: Agenda }>): void {
   
      console.log(event); // 1 see console output
      console.log(typeof(event)); // object
      console.log(typeof(event.meta)); // undefined
  
    }

1) Console output 
event: Object
color: {primary: "#e3bc08", secondary: "#FDF1BA"}
meta: Object
|-evento: Object
|-|-	id: 1
start: Sat Mar 03 2018 13:02:13 GMT+0000 (WET)
title: "Title"

**Comment by etwillbefine** [comment]
Your first console output shows the `eventto` object under `meta`?!
Can you please create a runnable plunker which reproduces this? You might be accessing the meta object somewhere else when its undefined in your code

**Comment by MarcoBatista** [comment]
Problem solved, 
The problem was in the view. 
instead (eventClicked)="eventClicked($event.event)" it was (eventClicked)="eventClicked($event)"
