### ISSUE TITLE
Build --prod Error with normal Angular ng(not ionic)

### ISSUE THREAD

**Issue by Jiraci** [mattlewis92/angular-calendar#500]
Hey! In our project we are using your calendar, building gives us an error, any ideas?
We need to get it back up ruinning
building without --prod and serving works just fine
`ng build --prod`

ERROR in ./src/app/app.module.ngfactory.js
Module not found: Error: Can't resolve 'angular-draggable-droppable/dist/esm/src/drag-and-drop.module' in 'D:\infi\infi\public\infi\src\app'
ERROR in ./src/app/app.module.ngfactory.js
Module not found: Error: Can't resolve 'angular-draggable-droppable/dist/esm/src/draggable-helper.provider' in 'D:\infi\infi\public\infi\src\app'
ERROR in ./src/app/app.module.ngfactory.js
Module not found: Error: Can't resolve 'angular-resizable-element/dist/esm/src/resizable.module' in 'D:\infi\infi\public\infi\src\app'

**Comment by mattlewis92** [comment]
Hi there, sorry but I can't tell what's going wrong just from the stack trace you posted, if you would be so kind as to attach a minimal running repo that reproduces your problem I would be more than happy to jump in and see what I can do to help 😄

**Comment by m00dy** [comment]
I have the same issue with this. Any solutions ?
