### ISSUE TITLE
Event overflowing Day on Month View in Internet Explorer

### ISSUE THREAD

**Issue by JonDosmann** [mattlewis92/angular-calendar#501]
## I'm submitting a ...

<pre>
[X] Bug report 
[ ] Feature request
[ ] Support request => Please do not submit a support request here, please ask on https://stackoverflow.com/
</pre>

### Bug description
When running the calendar in IE, anytime you have more events than can fit on a single line, it over flows the day box.
Pic: https://i.imgur.com/GUQW0be.png

### Minimal reproduction of the problem with instructions
Open the plunker in IE
https://plnkr.co/edit/V0NP3Jr56c7THFtfqmt7?p=preview
Click Add New 11+ times on a single day. 
Observe overflow.

### Versions

**Angular**: 5 (latest) 

**Calendar library:** 
0.23.6

**Browser name and version:** 
Internet Explorer 11.309

**Comment by JonDosmann** [comment]
I should note that I did find a work around:
`.cal-month-view .cal-day-cell {
    display: block !important;
}`

**Comment by mattlewis92** [comment]
Thanks for the suggested fix, I will make sure that's incorporated into the next version 😄
