### ISSUE TITLE
adding range (from / to) to selectable period

### ISSUE THREAD

**Issue by IterationCorp** [mattlewis92/angular-calendar#505]
## I'm submitting a ...
[x] Feature request

### Bug description / Feature request
When we want to select a period (from to) we can only select on day.
https://mattlewis92.github.io/angular-calendar/#/selectable-period

Would it be possible to add a range (from day 1 to day 1+n)? And all day in bewteen would be selected. 

A bit like here : 
https://fullcalendar.io/releases/fullcalendar/3.9.0/demos/selectable.html

Thanks

**Comment by mattlewis92** [comment]
This is possible by extending the root component to add the functionality yourself, please take a look at this comment: https://github.com/mattlewis92/angular-calendar/issues/235#issuecomment-307570924

Hope that helps 😄
