### ISSUE TITLE
adding new keys to calender event like beginTime and endTime for events

### ISSUE THREAD

**Issue by Ashab31** [mattlewis92/angular-calendar#507]
Hi,
I want to make changes in the Calendar Event. I want to add few more keys like beginTime and endTime for events. How can I do that, please help.

**Comment by etwillbefine** [comment]
You can store the time in start and end date of the events. Besides that you can store any additional properties using the `meta` property. 
Eg: `myEvent.meta.beginTime = '10:00';`
