### ISSUE TITLE
Pushing data to events: CalendarEvent[]

### ISSUE THREAD

**Issue by sunildipun** [mattlewis92/angular-calendar#508]
Hi, 
I am getting data from firebase and arranging the data in objects of arrays.
**[{…}, {…}, {…}, {…}]**
{title: "hello", start: "Mon, 16 Apr 2018 20:05:09 GMT", end: "Mon, 16 Apr 2018 21:05:09 GMT"}
{title: "chat test", start: "Tue, 17 Apr 2018 08:08:34 GMT", end: "Tue, 17 Apr 2018 09:08:34 GMT"}

This array, I am using in events: CalendarEvent[]
But i am facing some warning with this
**angular-calendar Event `start` property should be a javascript date object. Do `new Date(event.start)` to fix it. **
How should i proceed with

**Comment by etwillbefine** [comment]
Your date is of type **string**. You need to do something like this to map the string to a valid date representation:

```
events.map(e => ({
   start: new Date(e.start),
   end: new Date(e.end),
   ...
}));
