### ISSUE TITLE
Displaying the list of  all events for the month selected on top of month view calendar

### ISSUE THREAD

**Issue by Ashab31** [mattlewis92/angular-calendar#510]
Hi,
 I wanted a feature to display the list of events present in a month on click of a button called list, and this list should be displayed on top of month view of calendar. 
The list should display, event name, date and time of  all events.

**Comment by mattlewis92** [comment]
If you take a look at this demo: https://mattlewis92.github.io/angular-calendar/#/no-events-label You can see an example of how to hook into getting the current events for each view. The `period?.events` variable will contain all events for the current view.
