### ISSUE TITLE
RxJS upgrade request

### ISSUE THREAD

**Issue by vitormsilva** [mattlewis92/angular-calendar#512]
## I'm submitting a ...
<pre>
[ ] Bug report 
[x] Feature request
[ ] Support request => Please do not submit a support request here, please ask on https://stackoverflow.com/
</pre>

### Feature request
How far away are you from update to the last version of RxJS 6.0.0.
This will affect other modules, like angular-draggable-droppable;

### Versions

Angular: 6.0.0

Thank you;

**Comment by mattlewis92** [comment]
Once angular / rxjs 6 are all out of release candidate I will do a mass upgrade of all my packages. In the meantime you can just use the rxjs-compat package for rxjs v5 compatibility.

**Comment by jcrecio** [comment]
I imagine you talk about the same here for this error: Prerendering failed because of error: Error: Cannot find module "rxjs/operators/map"

even though I still don´t know how to fix it by using rxjs-compat, I included it in packajes.json but further do not know what else I can do

**Comment by agil-NUBBA** [comment]
Hi,

Just tried to run my project, these are the related errors:

```
node_modules/angular-calendar/modules/day/calendar-day-view.component.d.ts(3,10): error TS2305: Module '"my-project/node_modules/rxjs/Subject"' has no exported member 'Subject'.
node_modules/angular-calendar/modules/day/calendar-day-view.component.d.ts(4,10): error TS2305: Module '"my-project/node_modules/rxjs/Subscription"' has no exported member 'Subscription'.
node_modules/angular-calendar/modules/month/calendar-month-view.component.d.ts(3,10): error TS2305: Module '"my-project/node_modules/rxjs/Subject"' has no exported member 'Subject'.
node_modules/angular-calendar/modules/month/calendar-month-view.component.d.ts(4,10): error TS2305: Module '"my-project/node_modules/rxjs/Subscription"' has no exported member 'Subscription'.
node_modules/angular-calendar/modules/week/calendar-week-view.component.d.ts(2,10): error TS2305: Module '"my-project/node_modules/rxjs/Subject"' has no exported member 'Subject'.
node_modules/angular-calendar/modules/week/calendar-week-view.component.d.ts(3,10): error TS2305: Module '"my-project/node_modules/rxjs/Subscription"' has no exported member 'Subscription'.
```

```
"angular-calendar": "0.24.0",
"@angular/*": "6.0.0",
"rxjs": "^6.1.0",
"typescript": "2.7.2"
```

**Comment by volser** [comment]
angular 6 is released

**Comment by nitinht1988** [comment]
Hey.. any update on this issue?

**Comment by pgarzina** [comment]
interested as well

**Comment by JaxonWright** [comment]
@mattlewis92 awesome! Thanks for the update

**Comment by eugenioghio** [comment]
Hi @mattlewis92
Thank you for your work.

Unfortunately, I have an error with calendar-utils has no exported member WeekViewEvent. And when I try to get your angular-calendar@beta, I get this error.

`npm i angular-calendar@beta`

> npm ERR! code ETARGET
> npm ERR! notarget No matching version found for angular-calendar@beta
> npm ERR! notarget In most cases you or one of your dependencies are requesting
> npm ERR! notarget a package version that doesn't exist.

@angular/cli => 7.2.4
 @angular/core => 7.2.5

**Comment by mattlewis92** [comment]
@eugenioghio that dist tag is from a while ago and was deleted, just install the latest version

**Comment by Dinesh-Yalamuri** [comment]
`import { GetMonthViewArgs, MonthView, GetWeekViewHeaderArgs, WeekDay, GetWeekViewArgs, GetDayViewArgs, DayView, GetDayViewHourGridArgs, DayViewHour, WeekView } from 'calendar-utils';
`

In the latest version of calendar utils, i cant able to use these `DayView, GetDayViewHourGridArgs, DayViewHour,`.
In the old version i can able access but  for angular 14+ i cant able to access
`    "angular-calendar": "^0.30.1",`
`    "date-fns": "^2.29.3",`
