### ISSUE TITLE
Smooth drag and drop events 

### ISSUE THREAD

**Issue by inspirassion** [mattlewis92/angular-calendar#516]
Is it possible to drag&drop events smoothly in the week view like[ the original library](https://fullcalendar.io/docs/event-constraint-demo) ?

**Comment by majoryuk1** [comment]
I'm interested too.

**Comment by alessandromaffei** [comment]
I did it by defining a custom template for the event and adding the mwlDraggable and mwlDroppable on the cal-event. In this way you can apply your own logic to drag and drop without any grid-snap limitation.

es for week event custom template


`<ng-template #customWeekEventTemplate let-weekEvent="weekEvent">`
 ` <div (click)="selectEvent(weekEvent.event)">`
`    <div mwlDraggable [dropData]="weekEvent.event" (dragStart)="startDrag(weekEvent.event)"` `(dragEnd)="dragEnd(weekEvent.event)"  mwlDroppable (dragEnter)="dragEnter(weekEvent.event)"`
`(dragLeave)="dragLeave(weekEvent.event)"`
      `class="cal-event"  [style.backgroundColor] = "weekEvent.event.color.secondary"` `[style.borderColor]="weekEvent.event.color.primary">`
     ` <a class="cal-event-title">`
       ` <b>{{weekEvent.event.start | date : 'HH:mm'}}</b> {{weekEvent.event.title}}`
  `    </a>`
`    </div>`
`  </div>`
`</ng-template>`

**Comment by sayjavajava** [comment]
I am unable to create new issue . what the hell 

> This issue has been closed automatically as it did not follow the issue template. Please open a new issue that follows the bug report or feature request template. Thank you! ✌️

**Comment by AhHa45** [comment]
I need it to snap the grid, is that somehow configurable? @mattlewis92 ?

**Comment by mattlewis92** [comment]
@AhHa45 It's possible in `0.26` by setting `snapDraggedEvents="false"` on the week or day view components. Info on how to use the `0.26` release can be found over at the PR: https://github.com/mattlewis92/angular-calendar/pull/589
