### ISSUE TITLE
[WeekView] No way to group 2 events on separate event rows

### ISSUE THREAD

**Issue by 555ea** [mattlewis92/angular-calendar#517]
## I'm submitting a ...

<pre>
[] Bug report 
[x] Feature request
[ ] Support request => Please do not submit a support request here, please ask on https://stackoverflow.com/
</pre>

### Bug description / Feature request

view.eventRows in WeekView are grouped by start and end date. The event is placed on a 2nd row only if it overlaps with some kind of other event. There is no way to place Monday 00:00 - 12:00 and Tuesday 00:00 - 12:00 events on two separate rows!

What I'm trying to achive is to have Event1 on row1 on Monday and Tuesday, Event2 on row2 on Wednesday and Event3 on row3 on Thursday. Right now all of them will be on a same row

### Minimal reproduction of the problem with instructions

```
<mwl-calendar-week-view
          [viewDate]="viewDate"
          [events]="events">
        </mwl-calendar-week-view>
```

Where events are

```
    const start = new Date();
    start.setHours(0);
    start.setMinutes(0);
    const end = new Date();
    end.setHours(18);
    end.setMinutes(0);

    const start1 = new Date();
    start1.setDate(27);
    start1.setHours(0);
    start1.setMinutes(0);
    const end1 = new Date();
    end1.setDate(27);
    end1.setHours(18);
    end1.setMinutes(0);

    this.events = [
      {
        start: start,
        end: end,
        title: 'Event 1',
        meta: 0
      },
      {
        start: start1,
        end: end1,
        title: 'Event 2',
        meta: 1
      },
    ]
```

### Versions

Versions
Angular: ^5.2.0

Calendar library: ^0.24.0

Browser name and version: Google Chrome 65.0.3325.181

**Comment by mattlewis92** [comment]
Hi there,

You can implement this by overriding the business logic that generates the week view to position events in this way.

```
// extended from https://github.com/mattlewis92/angular-calendar/blob/master/src/modules/common/calendar-utils.provider.ts
class MyCalendarUtils extends CalendarUtils {
  getWeekView(args: GetWeekViewArgs): WeekView {
    // write custom logic here that positions events as you need
    // this can be a starting point: https://github.com/mattlewis92/calendar-utils/blob/c915a4fbc84a69286f734dfb14619db0e5e8960d/src/calendar-utils.ts#L408-L507
  }
}
```

and then use it when declaring the calendar module:
```
CalendarModule.forRoot({
  calendarUtils: {
    provide: CalendarUtils,
    useClass: MyCalendarUtils
  }
})
```

Hope that helps! 😄
