### ISSUE TITLE
activeDayIsOpen = false when change date 

### ISSUE THREAD

**Issue by inspirassion** [mattlewis92/angular-calendar#519]
This way we don't get empty bar when changing month

**Comment by mattlewis92** [comment]
When designing this component I deliberately left this logic up to the end user to implement as there are some cases where you might not want this. You can close the open day yourself by setting it to false when the user changes the view. There is an example of that in [the demo](https://github.com/mattlewis92/angular-calendar/blob/master/demos/demo-modules/kitchen-sink/template.html#L31). Hope that helps! 😄
