### ISSUE TITLE
Wrap Event Title vertically for week view

### ISSUE THREAD

**Issue by PrasannaKolla** [mattlewis92/angular-calendar#520]
Is there any way that I can wrap my titles vertically in week view and horizontally in day view.

I have my title lengthy and its getting truncated for week view and day view. Attached the screenshots
![weekview](https://user-images.githubusercontent.com/18333501/39440945-1455b42a-4c72-11e8-856d-d555c7c2d9f4.PNG)

I am using angular 5

**Comment by mattlewis92** [comment]
Unfortunately there's no trivial way to do this, there are tooltips that the user can mouse over to see the full title though. You might be able to get something working by using a [custom template](https://github.com/mattlewis92/angular-calendar#how-do-i-use-a-custom-template) and some additional styling for the [week view event component](https://github.com/mattlewis92/angular-calendar/blob/master/src/modules/week/calendar-week-view-event.component.ts).

**Comment by tgoode** [comment]
This comes two years late, but if anyone else has this issue I achieved event title word wraps (where vertical space is available) using the CalendarEvent _cssClass_ property based on Matt's demo [here](https://angular-calendar.com/#/custom-event-class).

![image](https://user-images.githubusercontent.com/48938778/86122688-97972e80-bb1b-11ea-972a-67a0d71d457c.png)

#### calendar.component.ts
Define a custom class by adding your own css class name to the event's _cssClass_ property.
```typescript
events: CalendarEvent[] = [
    {
      title: 'Has custom class',
      color: colors.yellow,
      start: new Date(),
      cssClass: 'my-custom-class',
    },
  ];
```

#### styles.css
Add the css class to your global _styles.css_ file with the following style change.
```css
.my-custom-class span{
    white-space: normal !important;
}
```

**Comment by igoragueme** [comment]
> This comes two years late, but if anyone else has this issue I achieved event title word wraps (where vertical space is available) using the CalendarEvent _cssClass_ property based on Matt's demo [here](https://angular-calendar.com/#/custom-event-class).
> 
> ![image](https://user-images.githubusercontent.com/48938778/86122688-97972e80-bb1b-11ea-972a-67a0d71d457c.png)
> 
> #### calendar.component.ts
> Define a custom class by adding your own css class name to the event's _cssClass_ property.
> 
> ```ts
> events: CalendarEvent[] = [
>     {
>       title: 'Has custom class',
>       color: colors.yellow,
>       start: new Date(),
>       cssClass: 'my-custom-class',
>     },
>   ];
> ```
> 
> #### styles.css
> Add the css class to your global _styles.css_ file with the following style change.
> 
> ```css
> .my-custom-class span{
>     white-space: normal !important;
> }
> ```


I think it would be a good idea to have an example of this solution in the documentation..

**Comment by Tahir-zaman** [comment]
please help me how design this type of calender
