### ISSUE TITLE
Shorted localization not working in Chrome??

### ISSUE THREAD

**Issue by kerimdragolj** [mattlewis92/angular-calendar#524]
I'm having issue with localization on chrome. It works fine for normal full version of day names http://prntscr.com/jfa3yw but when I try to shorten day names it goes back to english http://prntscr.com/jfa4nr (just on chrome, firefox works just fine). This is the code that does it: 

```
export class CustomDateFormatter extends CalendarDateFormatter {
  public monthViewColumnHeader({date, locale}: DateFormatterParams): string {
    return new Intl.DateTimeFormat(locale, {weekday: 'short'}).format(date);
  }
}

```
So shorted version of localization doesnt work on Chrome? Anything that could be done around it?
Firefox works just fine (http://prntscr.com/jfa5zy).

### Versions

Angular: 5.2.3

Calendar:  "angular-calendar": "^0.23.6",

Browser name and version: Chrome Version 66.0.3359.139 (Official Build) (64-bit)

**Comment by mattlewis92** [comment]
Hi there, unfortunately I wasn't able to reproduce your problem, it works fine for me in chrome: https://stackblitz.com/edit/angular-juggcw?file=demo/custom-date-formatter.provider.ts

<img width="1326" alt="screen shot 2018-05-13 at 11 35 47" src="https://user-images.githubusercontent.com/6425649/39966331-f048b8cc-56a1-11e8-89a4-aca85656ad2a.png">

If you can attach a runnable stackblitz that reproduces your problem I'd be happy to debug more. Thanks! 😄

**Comment by kerimdragolj** [comment]
yea it works fine for me too with 'en' ... try using 'bs' (bosnian) locale ... anyways i 'fixed' it by using serbian locale which is pretty much same language...

**Comment by mattlewis92** [comment]
Thanks for the repro 😄 I think it's because you're using the Intl API for doing the translation which is buggy in some browsers. If you use the new API in v5 in your custom formatter, it should do the trick: https://stackblitz.com/edit/angular-juggcw-22neir?file=demo/custom-date-formatter.provider.ts Hope that helps 😄

**Comment by kerimdragolj** [comment]
Yup, that did it. Thanks a lot! Cheers
