### ISSUE TITLE
Events not displaying on week/day view..

### ISSUE THREAD

**Issue by kerimdragolj** [mattlewis92/angular-calendar#527]
I'm getting events from db and running them through loop and storing into array just for calendar: 

```
this.events.push(
          {
            title: res.data[i].title,
            start: new Date(res.data[i].starts),
            end: new Date(res.data[i].ends),
            color: { primary: '#e3bc08', secondary: '#FDF1BA' },
          },
```

in case u think its date problem, i tried this also

 ```
this.events.push(
          {
            title: res.data[i].title,
            start: new Date(),
            end: new Date(),
            color: { primary: '#e3bc08', secondary: '#FDF1BA' },
          },
```

They work just fine for month view as u can see here http://prntscr.com/jfvpvh ... but not for week or day view:  http://prntscr.com/jfvq3k (week view) http://prntscr.com/jfvqe0 (day view). Any ideas what it might be? And here is the html code: 

```
<div class="kalendar" [ngSwitch]="view">
            <mwl-calendar-month-view class="calendar-2" *ngSwitchCase="'month'" 
                          [viewDate]="viewDate" 
                          [events]="items" [refresh]="refresh"
                          [locale]="locale" [weekStartsOn]="weekStartsOn" 
                          [weekendDays]="weekendDays" 
                          [activeDayIsOpen]="activeDayIsOpen"
                          (dayClicked)="dayClicked($event.day)">
            </mwl-calendar-month-view>
            <mwl-calendar-week-view *ngSwitchCase="'week'" 
                       [viewDate]="viewDate" 
                       [events]="events" [refresh]="refresh" 
                       [locale]="locale"
                       (eventClicked)="handleEvent('Clicked', $event.event)">
           </mwl-calendar-week-view>
           <mwl-calendar-day-view *ngSwitchCase="'day'" 
                        [viewDate]="viewDate" 
                        [events]="events" [refresh]="refresh" 
                        [locale]="locale"
                       (eventClicked)="handleEvent('Clicked', $event.event)">
           </mwl-calendar-day-view>
</div>
```

### Versions

Angular: 5.2.3

Calendar: "angular-calendar": "^0.23.6",

Browser name and version: any

**Comment by fahadali6767** [comment]
Hey i need your help . i have same problem.How did you fixed this issue?

**Comment by fahadali6767** [comment]
Issue Solved
i just need to change
this to this.


for(var i=0;i<this.dataevent.length;i++){
  this.obj = {
  title: this.dataevent[i].title,
  start:  new Date(this.dataevent[i].start),
  color:this.dataevent[i].color,
  end:new Date(this.dataevent[i].end),
  draggable:true
  }
  this.events.push(this.obj);
  }
  this.refresh.next();
        console.log(this.events +'arrtyyu');
      });
}

**Comment by yash5862** [comment]
Not working for me on MAC machine. fine on ubuntu and windows. month view is good but day view doesn't show any items in there. tried this.refresh.next() while pushing the events.

**Comment by rahul0755** [comment]
i have do that but after clicking on pervious or next data will be double show in calendar. How can I solve this
