### ISSUE TITLE
How to drag an event from one day view into an adjacent day view?

### ISSUE THREAD

**Issue by Jelle1** [mattlewis92/angular-calendar#532]
Hi. Is it possible to drag an event out of one mwl-calendar-day-view and into an adjacent mwl-calendar-day-view? If so, how?

Thanks

p.s. Why multiple day views you ask? To support the partitioning of events (for the same day) into multiple columns, where each column represents the physical location of the calendar event.

**Comment by Jelle1** [comment]
The answer is yes, it is possible. By default, the mwl-calendar-day-view component does not allow dragging across the x-axis. However, it is possible to rewrite the component to achieve this, e.g.:

`[dragAxis]="{x: dayEvent.event.draggable, y: dayEvent.event.draggable}"`

**Comment by temp5** [comment]
Perhaps this could be an option?

Something like:
https://github.com/mattlewis92/angular-calendar/blob/73d00c01352029e793be2fe0c60d7b0f89d6e24c/src/modules/day/calendar-day-view.component.ts#L176

That would be much nicer than rewriting the component to support this use case.
