### ISSUE TITLE
css not working anymore

### ISSUE THREAD

**Issue by IsiHund** [mattlewis92/angular-calendar#534]
**Describe the bug**

**Minimal reproduction of the problem with instructions**

**Screenshots**

**Versions (please complete the following information):**
 - `@angular/core`: 
 - `angular-calendar`
 - Browser name and version

**Comment by IsiHund** [comment]
The css import does not work.

**Comment by mattlewis92** [comment]
Hi there, please follow the issue template and attach a runnable stackblitz / repo that reproduces your problem, as without it, it's impossible to know what's going on. Thanks!

**Comment by ilicc** [comment]
I had the problem with import css. It only worked when I created new style sheet and copy all css data to new file or when I implemented css by <link> in index.html file.
I realised that sometimes VSC installed on my PC doesn't see new files that I've just added to project by terminal. To see new added files my VSC has to be restared. Everything works fine after that.
