### ISSUE TITLE
Not sorted events in month view.

### ISSUE THREAD

**Issue by KaliName** [mattlewis92/angular-calendar#535]
Hi there, 

I've noticed that events in mwl-calendar-open-day-events is not sorted. Is it meant to be? 

thank you.

**Comment by mattlewis92** [comment]
They are displayed in whatever order you give them in. Some people might want them sorted by start time, others by type, others by title etc, so I deliberately left them as is so you can implement the sorting yourself. Hope that helps! 😄

**Comment by Hila1** [comment]
I'm trying to sort the events in mwl-calendar-open-day-events by start time and couldn't find the correct place in the code to add my filtering.
I added:
`        events = events.sort((a, b) => (a.start < b.start) ? -1 : 1)`
 to the method: `dayClicked() ` but I'm still getting the exact same order.
any advice?
