### ISSUE TITLE
feature request for day view

### ISSUE THREAD

**Issue by 4dri-wtf** [mattlewis92/angular-calendar#536]
**Is your feature request related to a problem? Please describe.**

Feature request: I'm bulding a shift planner using this package and when there's a change of employee from morning to afternoon they are shown in the same column. I'd like to tag events so the don't share their colum with unrelated events.

**Describe the solution you'd like**

 I'd like to tag events so the don't share their colum with unrelated events

**Describe your use case for implementing this feature**

 I'm bulding a shift scheduler using this package and when there's a  change of employee from morning to afternoon they are shown in the same column

**Additional context**

with this feature each color would have it's own column so only green and blue would have two events in theirs column

![recal](https://user-images.githubusercontent.com/15342203/40243731-469f0668-5ac1-11e8-8081-e64bab9f7e0b.PNG)

**Comment by mattlewis92** [comment]
You can mostly implement this via a custom template, please see https://github.com/mattlewis92/angular-calendar/issues/269 for an example. Hope that helps! 😄

**Comment by 4dri-wtf** [comment]
Yay!
I just had to overwrite the calenderUtils in the component section!

This tool is great bro! keep it up!
![captura](https://user-images.githubusercontent.com/15342203/40430511-93345838-5ea5-11e8-8b49-2ca80670a828.PNG)
