### ISSUE TITLE
beforeMonthViewRender with information pulled from database

### ISSUE THREAD

**Issue by KaliName** [mattlewis92/angular-calendar#540]
Hi there, 

I am trying to render calendar view with custom template like in a example for grouping events in a month view. Data comes from database. I was able to display them. However, I need to click on a calendar for it to update the view and when I open **calendar-open-day-events** they disappear. Please find attached screen shot.

Database: Firebase

![image](https://user-images.githubusercontent.com/36970533/40287615-8ae63d96-5ca6-11e8-9b93-135a4d444f0a.png)

**Day clicked method:**
```
  dayClicked({ date, events }: { date: Date; events: CalendarEvent[] }): void {
    if (isSameMonth(date, this.viewDate)) {
      if (
        (isSameDay(this.viewDate, date) && this.activeDayIsOpen === true) ||
        events.length === 0
      ) {
        this.activeDayIsOpen = false;
      } else {
        this.activeDayIsOpen = true;
        this.viewDate = date;
        this.monthEvents = events;
      }
    }
  }
```

**Rendering method:**
```
  beforeMonthViewRender({ body }: { body: CalendarMonthViewDay[] }): void {
    
    body.forEach(day => {
      this.afDatabse.list(`/data/day.date`).valueChanges().subscribe(data => {
        this.dayReadings = data;      
        for (let i = 0; i < this.dayReadings.length; i++) { 
          this.sum += this.dayReadings[i];
        };
        day['sum'] = this.sum.toFixed(2);
        this.sum = 0;
      });
    });
    //this.refresh.next();
  }
```
**My template:**
```
      <ng-template #customCellTemplate let-day="day" let-locale="locale">
        <div class="cal-cell-top">
          <span class="cal-day-badge" *ngIf="day.badgeTotal > 0">{{ day.badgeTotal }}</span>
          <span class="cal-day-number">{{ day.date | calendarDate:'monthViewDayNumber':locale }}</span>
        </div>
        <div class="cal-events" *ngIf="day.events.length > 0">
          <div class="cal-event"
               *ngFor="let event of day.events"
               [style.backgroundColor]="event.color"
               [ngClass]="event?.cssClass"
               [mwlCalendarTooltip]="event.title | calendarEventTitle:'monthTooltip':event"
               (mwlClick)="handleEvent($event, event)">
          </div>
        </div>
        <div>
         <small> {{ day.sum }} </small>
          <div *ngIf="day.sum < 9"></div>
          <div *ngIf="day.sum > 9"></div>
        </div>       
      </ng-template>
```

```
          <div *ngSwitchCase="'month'">
            <mwl-calendar-month-view *ngSwitchCase="'month'"
                                     [viewDate]="viewDate"
                                     [events]="events$"
                                     [cellTemplate]="customCellTemplate"
                                     [refresh]="refresh"
                                     (beforeViewRender)="beforeMonthViewRender($event)"
                                     (dayClicked)="dayClicked($event.day)"
                                     (eventClicked)="handleEvent('Clicked', $event.event)">
            </mwl-calendar-month-view>
            <mwl-calendar-open-day-events class="cal-month-view"
                                          [isOpen]="activeDayIsOpen && monthEvents.length > 0"
                                          [events]="monthEvents"
                                          [customTemplate]="openDayEventsTemplate"
                                          (eventClicked)="handleEvent('Clicked', $event.event)">
            </mwl-calendar-open-day-events>
          </div>
```

Is there a way I can do this in constructor and then refresh.next()?

**Comment by KaliName** [comment]
Seems like it renders the view all the time. Is there a way I can access it this information in a constructor and save **day["sum"]** there for all days in a calendar?

**Comment by mattlewis92** [comment]
I actually use a really similar pattern in our application. The logic you want is:

1. User changes view / clicks next or last buttons
2. Load all totals from the api, save the data on the component controller
3. On complete call `this.refresh.next`, this will call `beforeMonthViewRender` where you can map the totals from the api to the data you just loaded. There is a `meta` property of type `any` where you can store this data on each `CalendarMonthViewDay`

Hope that helps! 😄

**Comment by saurabhmankar** [comment]
> Hi there,
> 
> I am trying to render calendar view with custom template like in a example for grouping events in a month view. Data comes from database. I was able to display them. However, I need to click on a calendar for it to update the view and when I open **calendar-open-day-events** they disappear. Please find attached screen shot.
> 
> Database: Firebase
> 
> ![image](https://user-images.githubusercontent.com/36970533/40287615-8ae63d96-5ca6-11e8-9b93-135a4d444f0a.png)
> 
> **Day clicked method:**
> 
> ```
>   dayClicked({ date, events }: { date: Date; events: CalendarEvent[] }): void {
>     if (isSameMonth(date, this.viewDate)) {
>       if (
>         (isSameDay(this.viewDate, date) && this.activeDayIsOpen === true) ||
>         events.length === 0
>       ) {
>         this.activeDayIsOpen = false;
>       } else {
>         this.activeDayIsOpen = true;
>         this.viewDate = date;
>         this.monthEvents = events;
>       }
>     }
>   }
> ```
> **Rendering method:**
> 
> ```
>   beforeMonthViewRender({ body }: { body: CalendarMonthViewDay[] }): void {
>     
>     body.forEach(day => {
>       this.afDatabse.list(`/data/day.date`).valueChanges().subscribe(data => {
>         this.dayReadings = data;      
>         for (let i = 0; i < this.dayReadings.length; i++) { 
>           this.sum += this.dayReadings[i];
>         };
>         day['sum'] = this.sum.toFixed(2);
>         this.sum = 0;
>       });
>     });
>     //this.refresh.next();
>   }
> ```
> **My template:**
> 
> ```
>       <ng-template #customCellTemplate let-day="day" let-locale="locale">
>         <div class="cal-cell-top">
>           <span class="cal-day-badge" *ngIf="day.badgeTotal > 0">{{ day.badgeTotal }}</span>
>           <span class="cal-day-number">{{ day.date | calendarDate:'monthViewDayNumber':locale }}</span>
>         </div>
>         <div class="cal-events" *ngIf="day.events.length > 0">
>           <div class="cal-event"
>                *ngFor="let event of day.events"
>                [style.backgroundColor]="event.color"
>                [ngClass]="event?.cssClass"
>                [mwlCalendarTooltip]="event.title | calendarEventTitle:'monthTooltip':event"
>                (mwlClick)="handleEvent($event, event)">
>           </div>
>         </div>
>         <div>
>          <small> {{ day.sum }} </small>
>           <div *ngIf="day.sum < 9"></div>
>           <div *ngIf="day.sum > 9"></div>
>         </div>       
>       </ng-template>
> ```
> ```
>           <div *ngSwitchCase="'month'">
>             <mwl-calendar-month-view *ngSwitchCase="'month'"
>                                      [viewDate]="viewDate"
>                                      [events]="events$"
>                                      [cellTemplate]="customCellTemplate"
>                                      [refresh]="refresh"
>                                      (beforeViewRender)="beforeMonthViewRender($event)"
>                                      (dayClicked)="dayClicked($event.day)"
>                                      (eventClicked)="handleEvent('Clicked', $event.event)">
>             </mwl-calendar-month-view>
>             <mwl-calendar-open-day-events class="cal-month-view"
>                                           [isOpen]="activeDayIsOpen && monthEvents.length > 0"
>                                           [events]="monthEvents"
>                                           [customTemplate]="openDayEventsTemplate"
>                                           (eventClicked)="handleEvent('Clicked', $event.event)">
>             </mwl-calendar-open-day-events>
>           </div>
> ```
> Is there a way I can do this in constructor and then refresh.next()?

can u share the code how u customized openday custom template

**Comment by saurabhmankar** [comment]
Can u share the Opendatcustom template code

**Comment by webdevelopersbc** [comment]
hello @mattlewis92 I need add custom template for day view ... cloud you please help me
I wanted to display events like
https://prnt.sc/1bqeobu
in this format on day view, could you please help me
