### ISSUE TITLE
Week view render

### ISSUE THREAD

**Issue by KaliName** [mattlewis92/angular-calendar#542]
Hi Guys,

How to access day element in a week view similar to the one below ( month day ) 
https://mattlewis92.github.io/angular-calendar/#/refreshing-the-view

Thank you

**Comment by KaliName** [comment]
Found solution. @mattlewis92  can please add it to examples. People might find it useful. Thank you.
```
beforeWeekViewRender({ header }: { header: WeekDay[] }): void {
    header.forEach(day => {

 });
}
```

**Comment by nmatz** [comment]
@KaliName You import WeekDay from calendar-utils ?

I can't get the events through week. It's looks like this:
![now](https://user-images.githubusercontent.com/42099944/53096285-88eb4100-34fd-11e9-825d-c59431a76211.PNG)

And I need this but view in week:
![mes](https://user-images.githubusercontent.com/42099944/53096430-ea131480-34fd-11e9-8972-63e40a38be3e.PNG)

I tried with CalendarWeekViewAllDayEvent too but didn't work

**Comment by nmatz** [comment]
> Found solution. @mattlewis92 can please add it to examples. People might find it useful. Thank you.
> 
> ```
> beforeWeekViewRender({ header }: { header: WeekDay[] }): void {
>     header.forEach(day => {
> 
>  });
> }
> ```

@KaliName You import WeekDay from calendar-utils ?

I can't get the events through week. It's looks like this:
![now](https://user-images.githubusercontent.com/42099944/53096285-88eb4100-34fd-11e9-825d-c59431a76211.PNG)

And I need this but view in week:
![mes](https://user-images.githubusercontent.com/42099944/53096430-ea131480-34fd-11e9-8972-63e40a38be3e.PNG)

I tried with CalendarWeekViewAllDayEvent too but didn't work
