### ISSUE TITLE
Need to pass extra data to the day (or to the whole component)

### ISSUE THREAD

**Issue by g41n** [mattlewis92/angular-calendar#547]
Hello to all,
I need to manage a limit on the events in a day, and I need to print out availability for every single day.

I've overrided the template with success, I can print out `day.events.length` that is good, but I also need to print out the availability. I think it can be done in such a manner
```
<span>{{ myLimit - day.events.length }} seats available.</span>
```
where `myLimit` is present in the parent component but I don't know how to make it visible/pass it to the day.

Here there is how I'm trying to manage it passing data with events. It's obviously the *wrong way* and is *not fully working* because I have no limit (and no span) in days with no events.
```
<span *ngIf="day.events.length">{{ day.events[0].meta.myLimit - day.events.length }} seats available.</span>
```

What do you think about?
Can be useful to have extra data in day and/or in component?

It would be cool having `day.meta.myLimit` or something similar...

Thanks in advance for patience and support  :)

**Comment by mattlewis92** [comment]
I'm guessing you're using an `ng-template`, these aren't like angularjs templates and they have access to the scope of the parent component, so you should be able to use the `myLimit` variable in there. If you're still getting stuck, if you can make a minimal repro on stackblitz that I can debug further I'd be happy to help more 😄

**Comment by g41n** [comment]
You're right!
Don't know what was wrong with my first try... :thinking: 

Thank you very much for the support! :smile:
