### ISSUE TITLE
How to access day view through month and week view?

### ISSUE THREAD

**Issue by mcb10** [mattlewis92/angular-calendar#551]
**Is your feature request related to a problem? Please describe.**
I am looking to access the day view through clicking on a particular month cell or week view tab.
I am currently using the 'dayClicked' and 'dayHeaderClicked' event in my 'app.component.html'.

**Describe the solution you'd like**
I would like to be able to click on the month cell and the day view of that selected date appear.
Similar to the week week, you select a 'Monday' or 'Saturday' and the day-view for the selected date appears.

**Describe your use case for implementing this feature**
I plan to use this feature to quickly identify events on a particular date no matter view view I am using.

**Comment by mattlewis92** [comment]
This isn't actually possible to do, as each of the day / week / month view components are independent from each other, the only way to do it is via the way you suggested, it's only a couple lines of code to do: https://stackblitz.com/edit/angular-xjsytw?file=demo/template.html

**Comment by mcb10** [comment]
Thank you @mattlewis92 this is perfect. Works as intended!
