### ISSUE TITLE
Does the calendar support Hijri ?

### ISSUE THREAD

**Issue by amt123** [mattlewis92/angular-calendar#562]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe your use case for implementing this feature**

**Additional context**

**Comment by mattlewis92** [comment]
I'm afraid there's no support for this, as the underlying library that powers this calendar (date-fns) doesn't support the Hijri calendar.

**Comment by MohammedAldosari** [comment]
I've developed Hijri adapter that seamlessly integrates both the Hijri and Gregorian calendars, offering a comprehensive solution for diverse calendrical needs.

[Hijri-Angular-Calendar](https://github.com/MohammedAldosari/hijri-angular-calendar#hijri-angular-calendar)
