### ISSUE TITLE
does it support RTL

### ISSUE THREAD

**Issue by amt123** [mattlewis92/angular-calendar#566]
Hello,

thanks for the great work. what I'm trying to make this calendar read from right to left such below screenshot . can you help me with that?
![image](https://user-images.githubusercontent.com/15020172/40706473-9a981618-63f6-11e8-80e8-55bdba247051.png)

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe your use case for implementing this feature**

**Additional context**

**Comment by mattlewis92** [comment]
There's no support for this out the box, but I think you could use CSS to flip the order of elements: https://css-tricks.com/almanac/properties/f/flex-direction/
