### ISSUE TITLE
Month-View with custom days

### ISSUE THREAD

**Issue by Failender** [mattlewis92/angular-calendar#570]
**Is your feature request related to a problem? Please describe.**

I need to use a custom calendar, with 12 month, 30 days each, and another month with only 5 days

**Describe the solution you'd like**

Another input parameter for the month-component, that allows to customize the displayed month, 
**Describe your use case for implementing this feature**

I am planning to show a calendar in my application that will contain events for a pen&paper universe, where calculation of time is a bit different

**Additional context**

**Comment by mattlewis92** [comment]
Sorry there's no support out the box for anything like this, you could maybe get this working by [overriding the helper function](https://mattlewis92.github.io/angular-calendar/#/extra-month-view-weeks) that generates the month view to behave as you want.
