### ISSUE TITLE
A way to customize event(calendar) view

### ISSUE THREAD

**Issue by axiom88-guru** [mattlewis92/angular-calendar#580]
**Is your feature request related to a problem? Please describe.**
 Is there any way to customize calendar view?

**Describe the solution you'd like**
When I click on a calendar day that has events, it slides down a box. I want to get rid of that box, and instead, have a card(view) appear over top of the calendar with the details.

**Additional context**
This image shows what i want to implement.
https://drive.google.com/open?id=1CcU06oenuiy7PIgZmkyXsereTCAxY32l

![untitled picture](https://user-images.githubusercontent.com/19179511/41077646-94a406e2-6a20-11e8-91c6-ca664adfad47.png)

**Comment by mattlewis92** [comment]
You can probably implement this with a custom template, here's a demo that's quite close to what you want: https://mattlewis92.github.io/angular-calendar/#/context-menu Hope that helps! 😄
