### ISSUE TITLE
Change format date to dd/mm/YYYY and locale in italian

### ISSUE THREAD

**Issue by fabiofebo** [mattlewis92/angular-calendar#583]
**Describe the bug**
Hi,
I am trying to change the calendar language to italian and change format date in dd-mm-yyyy.
I tried changing the local string from eng to it in the calendar-header-component

export class CalendarHeaderComponent {
  @Input() view: string;

  @Input() viewDate: Date;

  @Input() locale: string = 'it';

  @Output() viewChange: EventEmitter<string> = new EventEmitter();

  @Output() viewDateChange: EventEmitter<Date> = new EventEmitter();
}
but still nothing is changing, am I missing something?

On the format date, I am not understanding how to use the CalendarDateFormatter class properly

**Minimal reproduction of the problem with instructions**

**Screenshots**

**Versions:**

 - `@angular/core`: Angular: 5.2.11
 - `angular-calendar` : angular 5.0+ calendar
 - Chrome 66.0.3359.181

**Comment by RignonNoel** [comment]
You have a section of the demo about the I18N : https://mattlewis92.github.io/angular-calendar/#/i18n

You will need to add some code in your `module.ts`
```
import { registerLocaleData } from '@angular/common';
import localeFr from '@angular/common/locales/fr';
[...]

registerLocaleData(localeFr);

[...]
```

**Comment by mattlewis92** [comment]
@RignonNoel is on the right track with this, these 2 demos should give you what you need:
https://mattlewis92.github.io/angular-calendar/#/i18n
https://mattlewis92.github.io/angular-calendar/#/customise-date-formats
