### ISSUE TITLE
Getting errors with draggable-dropable on click

### ISSUE THREAD

**Issue by GreamDesu** [mattlewis92/angular-calendar#585]
**Describe the bug**
Getting a lot of errors in console,
`ERROR TypeError: Object(...) is not a function at DraggableDirective.push../node_modules/angular-draggable-droppable/fesm5/angular-draggable-droppable.js.DraggableDirective.ngOnInit (angular-draggable-droppable.js:155) at checkAndUpdateDirectiveInline (core.js:12362) at checkAndUpdateNodeInline (core.js:13886) at checkAndUpdateNode (core.js:13829) at debugCheckAndUpdateNode (core.js:14722) at debugCheckDirectivesFn (core.js:14663) at Object.eval [as updateDirectives] (CalendarOpenDayEventsComponent.html:6) at Object.debugUpdateDirectives [as updateDirectives] (core.js:14648) at checkAndUpdateView (core.js:13795) at callViewAction (core.js:14146)`

`ERROR TypeError: this.removeListener is not a function at ClickDirective.push../node_modules/angular-calendar/fesm5/angular-calendar.js.ClickDirective.ngOnDestroy (angular-calendar.js:852) at callProviderLifecycles (core.js:12705) at callElementProvidersLifecycles (core.js:12666) at callLifecycleHooksChildrenFirst (core.js:12649) at destroyView (core.js:14015) at callWithDebugContext (core.js:15049) at Object.debugDestroyView [as destroyView] (core.js:14600) at ViewContainerRef_.push../node_modules/@angular/core/esm5/core.js.ViewContainerRef_.remove (core.js:11490) at common.js:2606 at DefaultIterableDiffer.push../node_modules/@angular/core/esm5/core.js.DefaultIterableDiffer.forEachOperation (core.js:7406)`

**Minimal reproduction of the problem with instructions**
Clicking on the date on calendar

**Screenshots**

![image](https://user-images.githubusercontent.com/8704874/41104177-9c7c962e-6a8c-11e8-8a39-bd7f86444417.png)
![image](https://user-images.githubusercontent.com/8704874/41104302-de23e44c-6a8c-11e8-93dc-d322b38609ec.png)

**Versions:**
 - `@angular/core`: 5.2.1
 - `angular-calendar` latest
 - Browser name and version: Chrome 67

**Comment by mattlewis92** [comment]
Please see https://github.com/mattlewis92/angular-calendar/issues/543#issuecomment-391101589, thanks!
