### ISSUE TITLE
Module not found: Error: Can't resolve 'date-fns/add_days'

### ISSUE THREAD

**Issue by woodm1** [mattlewis92/angular-calendar#590]
**Description**
I am unable to compile the application with ng serve after adding Angular-Calendar to the app module as per instructions. The following errors are output:

> ERROR in ./node_modules/calendar-utils/dist/calendar-utils.js
> Module not found: Error: Can't resolve 'date-fns/add_days' in 'C:\Users\Matt\Source\Repos\CPanel\node_modules\calendar-utils\dist'
> ERROR in ./node_modules/calendar-utils/dist/calendar-utils.js
> Module not found: Error: Can't resolve 'date-fns/add_hours' in 'C:\Users\Matt\Source\Repos\CPanel\node_modules\calendar-utils\dist'
> ERROR in ./node_modules/calendar-utils/dist/calendar-utils.js
> Module not found: Error: Can't resolve 'date-fns/add_minutes' in 'C:\Users\Matt\Source\Repos\CPanel\node_modules\calendar-utils\dist'
> ERROR in ./node_modules/calendar-utils/dist/calendar-utils.js
> Module not found: Error: Can't resolve 'date-fns/add_seconds' in 'C:\Users\Matt\Source\Repos\CPanel\node_modules\calendar-utils\dist'
> ERROR in ./node_modules/calendar-utils/dist/calendar-utils.js
> Module not found: Error: Can't resolve 'date-fns/difference_in_days' in 'C:\Users\Matt\Source\Repos\CPanel\node_modules\calendar-utils\dist'
> ERROR in ./node_modules/calendar-utils/dist/calendar-utils.js
> Module not found: Error: Can't resolve 'date-fns/difference_in_minutes' in 'C:\Users\Matt\Source\Repos\CPanel\node_modules\calendar-utils\dist'
> ERROR in ./node_modules/calendar-utils/dist/calendar-utils.js
> Module not found: Error: Can't resolve 'date-fns/difference_in_seconds' in 'C:\Users\Matt\Source\Repos\CPanel\node_modules\calendar-utils\dist'
> ERROR in ./node_modules/calendar-utils/dist/calendar-utils.js
> Module not found: Error: Can't resolve 'date-fns/end_of_day' in 'C:\Users\Matt\Source\Repos\CPanel\node_modules\calendar-utils\dist'
> ERROR in ./node_modules/calendar-utils/dist/calendar-utils.js
> Module not found: Error: Can't resolve 'date-fns/end_of_month' in 'C:\Users\Matt\Source\Repos\CPanel\node_modules\calendar-utils\dist'
> ERROR in ./node_modules/calendar-utils/dist/calendar-utils.js
> Module not found: Error: Can't resolve 'date-fns/end_of_week' in 'C:\Users\Matt\Source\Repos\CPanel\node_modules\calendar-utils\dist'
> ERROR in ./node_modules/calendar-utils/dist/calendar-utils.js
> Module not found: Error: Can't resolve 'date-fns/get_day' in 'C:\Users\Matt\Source\Repos\CPanel\node_modules\calendar-utils\dist'
> ERROR in ./node_modules/calendar-utils/dist/calendar-utils.js
> Module not found: Error: Can't resolve 'date-fns/is_date' in 'C:\Users\Matt\Source\Repos\CPanel\node_modules\calendar-utils\dist'
> ERROR in ./node_modules/calendar-utils/dist/calendar-utils.js
> Module not found: Error: Can't resolve 'date-fns/is_same_day' in 'C:\Users\Matt\Source\Repos\CPanel\node_modules\calendar-utils\dist'
> ERROR in ./node_modules/calendar-utils/dist/calendar-utils.js
> Module not found: Error: Can't resolve 'date-fns/is_same_month' in 'C:\Users\Matt\Source\Repos\CPanel\node_modules\calendar-utils\dist'
> ERROR in ./node_modules/calendar-utils/dist/calendar-utils.js
> Module not found: Error: Can't resolve 'date-fns/is_same_second' in 'C:\Users\Matt\Source\Repos\CPanel\node_modules\calendar-utils\dist'
> ERROR in ./node_modules/calendar-utils/dist/calendar-utils.js
> Module not found: Error: Can't resolve 'date-fns/set_hours' in 'C:\Users\Matt\Source\Repos\CPanel\node_modules\calendar-utils\dist'
> ERROR in ./node_modules/calendar-utils/dist/calendar-utils.js
> Module not found: Error: Can't resolve 'date-fns/set_minutes' in 'C:\Users\Matt\Source\Repos\CPanel\node_modules\calendar-utils\dist'
> ERROR in ./node_modules/calendar-utils/dist/calendar-utils.js
> Module not found: Error: Can't resolve 'date-fns/start_of_day' in 'C:\Users\Matt\Source\Repos\CPanel\node_modules\calendar-utils\dist'
> ERROR in ./node_modules/calendar-utils/dist/calendar-utils.js
> Module not found: Error: Can't resolve 'date-fns/start_of_minute' in 'C:\Users\Matt\Source\Repos\CPanel\node_modules\calendar-utils\dist'
> ERROR in ./node_modules/calendar-utils/dist/calendar-utils.js
> Module not found: Error: Can't resolve 'date-fns/start_of_month' in 'C:\Users\Matt\Source\Repos\CPanel\node_modules\calendar-utils\dist'
> ERROR in ./node_modules/calendar-utils/dist/calendar-utils.js
> Module not found: Error: Can't resolve 'date-fns/start_of_week' in 'C:\Users\Matt\Source\Repos\CPanel\node_modules\calendar-utils\dist'

Versions:
 - `@angular/core`: 5.0.2 (CLI 1.7.4)
 - `angular-calendar`: 0.23.1 (also tried 0.24.1)
 - Browser name and version: n/a

I found the following thread which seems to have the same error, the solution there was to install a version of date-fns above 2.x which I've done to no effect. [](https://github.com/dmtrKovalenko/material-ui-pickers/issues/349)

Help appreciated :)

**Comment by luis-28b** [comment]
Try running
npm i date-fns

It works for me
