### ISSUE TITLE
Fetch Data from database and show it in calendar

### ISSUE THREAD

**Issue by bhavingoldfish** [mattlewis92/angular-calendar#595]
Hello Mattlewis,

I have successfully Implemented UI of Angular Calendar in Angular-5.
Now, I want to fetch data from database and show it in calendar.

So, for that I have check this demo,
https://mattlewis92.github.io/angular-calendar/#/async-events

But I'm not able to find how it's check for specific date / week / month.
I have seen some functions like subDays , addDays , startOfDay etc. But is there any documentation that how these functions will be used ??

Because I have date wise data in response from database but in UI how can I check for specific date.
Please suggest me how to implement this functionality.

I know this calendar is only for UI perspective but please spend some time for it. My only concern is how we can check for date from above functions.

Regards,
Bhavin

**Comment by mattlewis92** [comment]
You can use the `beforeViewRender` output to get the start and end of the current view which you can then pass to your API to load dates for that specific date range. You can see an example of how to do this here: https://mattlewis92.github.io/angular-calendar/#/no-events-label Hope that helps! 😄

**Comment by bhavingoldfish** [comment]
Thank you Mattlewis, 

Your suggested link works, 
I have to just pass date in "YYYY-MM-DD" in start and end and it worked. 

Thank you again. 
I must tell this calendar is Very developer friendly ;)

**Comment by athiraaravindan** [comment]
help 
save events from the calendar and display that events

**Comment by dineshpaliwal** [comment]
I want to add event in database can u privide that
