### ISSUE TITLE
(Custom) Tooltip for day view with custom event not showing

### ISSUE THREAD

**Issue by AhHa45** [mattlewis92/angular-calendar#610]
**Describe the bug**

The day view with a custom template doesn't show a (custom) tooltip.
_Note:_ Stackblitz has error: `StaticInjectorError(BootstrapModule)[DroppableDirective -> ElementRef]`

(Demo Stackblitz from here: https://mattlewis92.github.io/angular-calendar/#/day-view-start-end also shows this error, how to fix this?) 

Can anyone help me out with this? I have looked at so many examples now, but it seems only to work with the cellTemplate for the Month View?

**Minimal reproduction of the problem with instructions**

```
<mwl-calendar-day-view class="hub-calendar-day-view"
                                   [tooltipPlacement]="'right'"
                                   [viewDate]="day"
                                   [events]="events"
                                   [dayStartHour]="dayStartHour"
                                   [dayEndHour]="dayEndHour"
                                   [hourSegmentTemplate]="customHourSegmentTemplate"
                                   [eventTemplate]="customEventTemplate"s
                                   [hourSegmentHeight]="24">
                <ng-template #customHourSegmentTemplate>
                    <div class="customHourSegment"></div>
                </ng-template>

                <ng-template #customEventTemplate
                             let-dayEvent="dayEvent"
                             mwlCalendarTooltip="true"
                             [tooltipEvent]="dayEvent"
                             [tooltipTemplate]="cellTooltipTemplate"
                             [tooltipPlacement]="'top'">
                    <div class="custom-event" [ngClass]="dayEvent.event.meta.post.channel">
                        <mat-icon class="icon" [svgIcon]="'icon-' + dayEvent.event.meta.post.channel"></mat-icon>
                        <p class="time">{{ getFormattedTime(dayEvent.event.start) }}</p>
                        <p class="desc">{{ dayEvent.event.title }}</p>
                    </div>
                </ng-template>

                <ng-template #cellTooltipTemplate
                             let-event="event">
                    <div class="cal-tooltip" [ngClass]="'cal-tooltip-' + placement">
                        <div class="cal-tooltip-arrow"></div>
                        <div class="cal-tooltip-inner">
                            {{event.start | date: 'HH:mm'}} - {{event.end | date: 'HH:mm'}}
                        </div>
                    </div>
                </ng-template>
            </mwl-calendar-day-view>
```

https://stackblitz.com/edit/day-event-tooltip?file=src/app/event-week/event-week.component.ts

**Versions**

- `@angular/core`: "6.0.0"
- `angular-calendar`: "^0.24.x"
- Browser name and version:  67.0.3396.87 64Bit

**Comment by mattlewis92** [comment]
Ah damn, I thought I'd fixed the stackblitz issue, weirdly the demo does run if you hit the update dependencies button on the left hand panel. I think the issue you're having is because you're trying to use the tooltip on an `ng-template` which isn't a real element, only the contents of the template are actually added to the DOM. Something like

```
 <ng-template #customEventTemplate
                             let-dayEvent="dayEvent"
                             >
                    <div class="custom-event" 
mwlCalendarTooltip="true"
                             [tooltipEvent]="dayEvent"
                             [tooltipTemplate]="cellTooltipTemplate"
                             [tooltipPlacement]="'top'"[ngClass]="dayEvent.event.meta.post.channel">
                        <mat-icon class="icon" [svgIcon]="'icon-' + dayEvent.event.meta.post.channel"></mat-icon>
                        <p class="time">{{ getFormattedTime(dayEvent.event.start) }}</p>
                        <p class="desc">{{ dayEvent.event.title }}</p>
                    </div>
                </ng-template>
```

should work?

**Comment by AhHa45** [comment]
Hey mattlewis,
Thanks for your reply. 
Yes I figured this already out. Thank you very much. 

However, styling the tooltip is extremely hard as it dissappears as soon as the mouse isn't on the element anymore and gets removed from the DOM. 
Thus inspecting the element is not possible, adding pseudo classes doesn't help neither. 

I know I missuse the tooltip functionality but we need it to be as simple as possible and also similar to outlook calendar. 
Is it somehow possible to keep the tooltip opened? Or open on click?
BecauseButtons etc in a tooltip

**Comment by mattlewis92** [comment]
It looks like you can fire a fake mouse enter event in the console to trigger the tooltip to display: https://groups.google.com/forum/#!topic/mozilla.dev.developer-tools/i4ma6Anvy0Q

**Comment by AhHa45** [comment]
Thanks for your reply.
What about:

> Is it somehow possible to keep the tooltip opened? Or open on click?
> Because buttons etc in a tooltip are not clickable as the tooltip disappears immediately.

?

Cheers :)
