### ISSUE TITLE
How to customize event text color?

### ISSUE THREAD

**Issue by iSeeJay** [mattlewis92/angular-calendar#612]
**Describe the bug**

   I have been trying to customize the color of the text within an event in the week view of the calendar however all my attempts at editing the templates to achieve this behavior have either resulted in nothing changing or the calendar breaking. Is there any way to customize the color of the text within an event?

**Minimal reproduction of the problem with instructions**

**Screenshots**

<img width="231" alt="screen shot 2018-06-20 at 2 16 35 pm" src="https://user-images.githubusercontent.com/7929924/41676841-b35563aa-7494-11e8-90f7-639f621ccd7b.png">

The text within the boxes are blue, but i want to be able to customize it. 

**Versions**

- `@angular/core`:"^6.0.4"
- `angular-calendar`:"^0.25.2"
- Browser name and version: Google Chrome v.67.0.3396.87

**Comment by mattlewis92** [comment]
You can use some global CSS for this, if you add a `cssClass` to the event and then add this to your global styles:
```
.event-class .cal-event-title {
  color: black;
}
```

Hope that helps! 😄

**Comment by Goufoux** [comment]
Hello,

Is it possible to add a text color property, in my case the background colors are set dynamically and it doesn't allow me to go through a class in order to set the color?
