### ISSUE TITLE
Stackblitz generation is broken

### ISSUE THREAD

**Issue by mattlewis92** [mattlewis92/angular-calendar#613]
**Describe the bug**
Stackblitz generation is broken on the demos (again)

**Comment by Danielg212** [comment]
+1

Error: StaticInjectorError(BootstrapModule)[DraggableDirective -> ElementRef]: 
StaticInjectorError(Platform: core)[DraggableDirective -> ElementRef]: 
NullInjectorError: No provider for ElementRef!

**Comment by mattlewis92** [comment]
Finally got a robust fix for this, should be fixed shortly! 😄
