### ISSUE TITLE
when first opened month-view

### ISSUE THREAD

**Issue by minekucukal** [mattlewis92/angular-calendar#624]
**Describe the bug**
When first opened month-view does not show the correct time. But after click any button show correct time in timepicker.

**Minimal reproduction of the problem with instructions**
https://mattlewis92.github.io/angular-calendar/#/kitchen-sink

**Screenshots**
http://prntscr.com/k2hu0x -> first open
http://prntscr.com/k2hv51 -> after click any button

**Comment by mattlewis92** [comment]
Thanks for reporting, should be fixed now! 😄
