### ISSUE TITLE
Make *first day of week* a part of the spec

### ISSUE THREAD

**Issue by ahall-medullan** [mattlewis92/angular-calendar#625]
**Is your feature request related to a problem? Please describe**
Yes, I would like to always start the week view calendar with todays date. Is it possible to simply set a firstDayOfWeek property to an index like 2 to start on Tuesday.

**Describe the solution you'd like**
If today is Tuesday January 1, the week view should be ordered as follows:
Today, Wednesday, Thursday, Friday, Saturday, Sunday, Monday

**Describe your use case for implementing this feature**
An appointment scheduling feature where the current day is highlighted and is always the first item

**Additional context**

**Comment by mattlewis92** [comment]
Hi there, this is actually already possible with the `weekStartsOn` option. You can see a demo of it working here: https://mattlewis92.github.io/angular-calendar/#/i18n Hope that helps! 😄

**Comment by ahall-medullan** [comment]
Thanks for quick feedback.
