### ISSUE TITLE
Invalid time value error

### ISSUE THREAD

**Issue by teodoramalec** [mattlewis92/angular-calendar#636]
Hi, 
I have intalled angular-calendar and all its dependencies and after using 
```
<mwl-calendar-month-view
  [viewDate]="viewDate"
  [events]="events">
</mwl-calendar-month-view>
```
I get some errors with the same message "Invalid time value at Date.toISOString " at this line from the angular-calendar.js 
`var trackByWeekDayHeaderDate = function (index, day) { return day.date.toISOString(); };`

**Minimal reproduction of the problem with instructions**

https://stackblitz.com/run

**Screenshots**
![image](https://user-images.githubusercontent.com/23343764/42631123-e4f6fe38-85e1-11e8-8f82-60ac5158e5a4.png)
and it seems that the problem is here
![image](https://user-images.githubusercontent.com/23343764/42631140-f214f0fc-85e1-11e8-8301-93f5f55960e9.png)

**Versions**

- `@angular/core `: 5.0.0
- `angular-calendar`:0.24.1
- Browser name and version: Chrome

What do I do wrong?

**Comment by mattlewis92** [comment]
This error is triggered when passing an invalid date to the calendar (type `new Date('invalid').toISOString()` in the chrome console and you'll see), my guess is that the value you're passing to `viewDate` is an invalid date.

**Comment by teodoramalec** [comment]
Right, it says Ivalid time value. How do I fix it?

**Comment by mattlewis92** [comment]
The value that you're passing to `new Date` isn't a valid date time string, if you can share some code via stackblitz etc I can point you to where you're going wrong 😄

**Comment by teodoramalec** [comment]
Here is my code: 
https://stackblitz.com/edit/angular-ad8nzw 

Thanks a lot! :)

**Comment by mattlewis92** [comment]
It sounds like your `viewDate` is invalid, if you do `console.log(this.viewDate, typeof this.viewDate)` what do you get?

**Comment by db10101** [comment]
I'm getting the exact same error after initial setup, where would you suggest I put that line? When I put it into my main, it says this.viewDate is invalid.
