### ISSUE TITLE
Transfer an event between two calendars

### ISSUE THREAD

**Issue by AleksGouin** [mattlewis92/angular-calendar#637]
Hello :)

**Describe the bug**

I don't know if it's a bug, but i'm experiencing some problems. 

Let's say I have two users, with events assigned to each others. 
I want to display the events of the first user in the first calendar, and the events of the second user in the second calendar. 
But I want to be able to transfer an event from a calendar to the other one thanks to the drag and drop.

Everything is working fine in the "month" view, as I am able to drag and drop an event from a calendar to the other, without any problem.
But with the "week" view I'm not able to do it anymore.

I think the problem come from the "dropData" parameter, that is defined when I define the list outside of the calendar. (ExternalEvents from the html, like in your exemple)

I don't know how to make my events list with this [dropData] parameter or if their's a way around.

**Minimal reproduction of the problem with instructions**

Here's a link to StackBlitz where I put an exemple of what I want to do: https://p5utsb.run.stackblitz.io

**Screenshots**

![image](https://user-images.githubusercontent.com/25389880/42635737-25bc4338-85e7-11e8-8a13-f0a057986052.png)

![image](https://user-images.githubusercontent.com/25389880/42635746-2d25bf6e-85e7-11e8-99dc-ab6ef2d2fc07.png)

**Versions**

- `@angular/core`: "^6.0.0"
- `angular-calendar`: "^0.25.2"
- Browser name and version: Chrome Version 67.0.3396.99

**Comment by mattlewis92** [comment]
Drag and drop has been completely overhauled in the new version and it should fix the problems you're experiencing, please give the beta a try and let me know if it works for you! 😄 See https://github.com/mattlewis92/angular-calendar/pull/589 for how to try it and how to migrate

The [external events demo](https://github.com/mattlewis92/angular-calendar/tree/0.26/demos/demo-modules/draggable-external-events) has also been updated which should give you a good starting point.

**Comment by AleksGouin** [comment]
Hi, 

It seems to work just as I need ! 

Thanks you very much ! 

If I encounter any more problems I'll come back to you :)
