### ISSUE TITLE
DayView: Columns for a color/X-Position of an Event

### ISSUE THREAD

**Issue by JonasJW** [mattlewis92/angular-calendar#640]
**Is your feature request related to a problem? Please describe**

**Describe the solution you'd like**

At the moment when you add a event in the dayView it gets places from left to right. Meaning when there is an event for that time it gets placed next to this event. Like columns that get filled left to right.

I would like to have a cloumns for each color. So when you add a red event it gets places in the red column and a blue event gets placed in the blue column.

There is no option for positioning the events on the x-Axis, right? Is there a good way to accomplish this behavior?

**Describe your use case for implementing this feature**

I would like to create a calendar for multiple persons where every person has one color and the events for each person are displayed in the proper column

**Additional context**

**Comment by mattlewis92** [comment]
Hey, this is possible by using a custom day view template, for more info and an example check this issue: https://github.com/mattlewis92/angular-calendar/issues/269 Hope that helps! 😄
