### ISSUE TITLE
Increase Badge Count based on an action

### ISSUE THREAD

**Issue by PrasannaKolla** [mattlewis92/angular-calendar#642]
I have given an ability to cancel an event, when an event is cancelled, the color should be changed (I have represented my events status based on colors) and Badge count should get updated dynamically. Dont want to make an API call to load the data upon cancelling an event.

**Additional context**

![image](https://user-images.githubusercontent.com/18333501/42768053-1f0b7978-88e4-11e8-98d1-37b0e540d28f.png)

**Comment by mattlewis92** [comment]
You can manually refresh the view to do this, please see this demo: https://mattlewis92.github.io/angular-calendar/#/refreshing-the-view

**Comment by PrasannaKolla** [comment]
Thanks for the reply. 
this.refresh.next() is not working. When I moved to the next cell, the values are getting updated. Can I call 
beforeMonthViewRender(Body) from the place where I am deleting an event?

**Comment by PrasannaKolla** [comment]
Nevermind, I haven't put refresh in html. Its working after modifying html. Thank you for all your time and support.

**Comment by WarayAmine** [comment]
I am trying to add two other cell badges, so i can have a cell for each type of event. But i am having a hard time with that, and i saw now that you are doing almost the same thing but with different badges. Could you please share how did you add those two bagdes the their count ? Thanks
