### ISSUE TITLE
Disable an explicit day in the future

### ISSUE THREAD

**Issue by marticrespi** [mattlewis92/angular-calendar#648]
**Is your feature request related to a problem? Please describe**

I want to disable an explicit future day, for example, because the next wednesday is a national holiday day.

**Describe the solution you'd like**

I would like to can include an array of days to be disabled.

**Describe your use case for implementing this feature**

I want to discard but include it/hem in the view, It would be like excludeDays but I want to see them in the calendar.

**Comment by mattlewis92** [comment]
You can implement this using the existing api, by hooking into the `beforeViewRender` hooks and manually marking those days as disabled yourself. You can see an example of how to do it here: https://mattlewis92.github.io/angular-calendar/#/min-max-date Hope that helps! 😄
