### ISSUE TITLE
How to display more months

### ISSUE THREAD

**Issue by teodoramalec** [mattlewis92/angular-calendar#652]
**Describe the bug**

Hi. I've managed to implement angular-calendar in my page and I need to display more than one calendar-component at once. For example,  I select an interval from nov 2016 to apr 2017 and I want to see all these 6 months.
Basically, I have 4 dropdowns, 2 for years, 2 for months, and after clicking "show" button a number of calendars should be desplayed.

**Minimal reproduction of the problem with instructions**

I have put my code here, not sure if work in stackblitz, but for you to understand what I am using.

https://stackblitz.com/edit/angular-hladws-vvoum8 
**Screenshots**
![image](https://user-images.githubusercontent.com/23343764/42951869-e1a7881c-8b7f-11e8-8b60-5890fe0f90fe.png)

For the moment, it displays a number of months that i have selected, but only the current one.

**Versions**

- `@angular/core`:5
- `angular-calendar`:0.24.1
- Browser name and version:Chrome

**Comment by mattlewis92** [comment]
You need to pass a different `viewDate` to each calendar instance for this to work. i.e. the july calendar you would pass `new Date('2018-07-01T00:00:00.000Z')` as the `viewDate` input, for june you would pass `new Date('2018-06-01T00:00:00.000Z')` etc.

p.s. for future support questions like this please ask on stackoverflow instead where you'll have a bigger amount of people available that can help you. Thanks! ✌️

**Comment by coolmonster** [comment]
@teodoramalec  please share the code snippet that worked for you. i have been stuck on this for a week now
