### ISSUE TITLE
Calendar not showing when adding new event

### ISSUE THREAD

**Issue by coolmonster** [mattlewis92/angular-calendar#658]
no calendar popup on while adding new event it shows present date only plus there is some extra data showing at the end you can view the bug in StackBlitz as well 

**Minimal reproduction of the problem with instructions**

![screenshot from 2018-07-25 16-31-09](https://user-images.githubusercontent.com/20675609/43198873-c5d40b08-902d-11e8-80fb-301fcdd5456d.jpg)

**Versions**

6.0.9- `@angular/core`:
0.25.2- `angular-calendar`:
 chrome 67.0.3396.99 - Browser name and version:

**Comment by mattlewis92** [comment]
Thanks for reporting, it should be fixed now on the demo site. To fix the issue in your app you just need to import the flatpickr stylesheets (`node_modules/flatpickr/dist/flatpickr.css`) somewhere in your apps global css.

**Comment by mRAJENDRAKUMAR-droid** [comment]
> Thanks for reporting, it should be fixed now on the demo site. To fix the issue in your app you just need to import the flatpickr stylesheets (`node_modules/flatpickr/dist/flatpickr.css`) somewhere in your apps global css.
Thanks a lot it's working now..............

**Comment by DivekJohns** [comment]
For me it was fixed by adding       [editing] ="true" in HTML 
<mwl-calendar-week-view
    *ngSwitchCase="CalendarView.Week"
    [viewDate]="viewDate"
    [events]="events"
    [refresh]="refresh"
     [editing] ="true"
    (eventClicked)="handleEvent('Clicked', $event.event)"
    (eventTimesChanged)="eventTimesChanged($event)"
  >
  </mwl-calendar-week-view>
