### ISSUE TITLE
Event resizable under modal

### ISSUE THREAD

**Issue by dkaakati** [mattlewis92/angular-calendar#662]
**Describe the bug**

When I open a modal to edit an event, I can resize an other event under this modal.

**Minimal reproduction of the problem with instructions**

1 . Go to https://mattlewis92.github.io/angular-calendar/#/kitchen-sink
2.  click on day view  
3. click on the edit icon 
4. resize an event under the modal opened 
**Screenshots**

![image](https://user-images.githubusercontent.com/9569011/43309246-8a865d78-9184-11e8-9807-4a9481a1a194.png)

**Versions**

- `@angular/core`: "^6.0.3"
- `angular-calendar`: "^0.25.2",
- Browser name and version: Chrome Version 65.0.3325.146 (Build officiel) (64 bits)

**Comment by mattlewis92** [comment]
Thanks for reporting! This should be fixed now in the latest beta, install instructions and how to migrate are here: https://github.com/mattlewis92/angular-calendar/pull/589 Let me know if that works ok for you 😄
