### ISSUE TITLE
Search appointment in calendar based on appEvent.title

### ISSUE THREAD

**Issue by cyphercodes96** [mattlewis92/angular-calendar#668]
**Is your feature request related to a problem? Please describe**

Not really

Consider the calendar is filled with over 1k+ appointments on a level, and there is a customer calling the company that is using this calendar asking when was his appointment taken? Ofcourse i doubt anyone working in that company won't have the appointment date memorized, so searching for it won't be as much as efficient.

**Describe the solution you'd like**
input search option that'll allow the users to search through appEvents, filtering or highlighting the available results.

**Comment by mattlewis92** [comment]
I think it's outside the scope of the lib itself to do this, but you could implement it relatively easily in your own app. I put together a demo to show you how to do this here: https://stackblitz.com/edit/angular-t9ijbk?file=demo/template.html Hope that helps! 😄

**Comment by mattlewis92** [comment]
It's doable with a custom template: https://github.com/mattlewis92/angular-calendar/issues/269

**Comment by cyphercodes96** [comment]
Well done my friend, thank you for the reference, hard work, and this amazing calendar package!

Goodluck and have a great day ahead.
