### ISSUE TITLE
Translation missing in AngularDateFormatter

### ISSUE THREAD

**Issue by MBcom** [mattlewis92/angular-calendar#670]
**Describe the bug**
"week of" is hard coded in https://github.com/mattlewis92/angular-calendar/blob/7e44faf9442379f4598baedb39e543b52cf4286f/src/modules/common/calendar-angular-date-formatter.provider.ts#L62  this does not change if you change locale

**Minimal reproduction of the problem with instructions**

`{{ viewDate | calendarDate:(view + 'ViewTitle'):'de' }}` does not have in view=week the expected behavior

**Screenshots**

**Versions**

- `@angular/core`: ^6.0.3
- `angular-calendar`:  ^0.25.2
- Browser name and version: not browser related

**Comment by mattlewis92** [comment]
There's currently no way of changing this via the angular locale apis so you need to override it yourself like this: https://mattlewis92.github.io/angular-calendar/#/i18n

I think I'm going to change the default week view title in the next version though to something that can be translated automatically to something like `Jul 30 - Aug 5`
