### ISSUE TITLE
Week view hourly events left values are wrong

### ISSUE THREAD

**Issue by mattlewis92** [mattlewis92/angular-calendar#675]
**Describe the bug**
<img width="1018" alt="screen shot 2018-08-05 at 17 06 23" src="https://user-images.githubusercontent.com/6425649/43691473-f1fdd19e-98d1-11e8-9b08-745ab8ecaf44.png">

**Comment by AhHa45** [comment]
Wouldn't it make sense to add a input property (with a default value) that limits the number of events in a cell? If the limit is reached add a "(# more events)/ (show more)" segment to the cell and clicking on it would open a tooltip where the other events are displayed in a column.

Here is an example:

<img width="285" alt="more events example" src="https://user-images.githubusercontent.com/4215561/43704536-2f908eaa-9960-11e8-803d-12924e5282a4.png">

**Comment by AhHa45** [comment]
I totally understand.
As you can see, it is possible to do it manually in the month view.
However, it was not possible in the week-view, because the grouped events (set in the beforeViewRender function) were not accessible in the template.
I will give it another try now with the 0.26beta-1
