### ISSUE TITLE
Text is cut off on days on mwl-calendar-month-view at lower screen resolutions and sizes

### ISSUE THREAD

**Issue by JamboBuenna** [mattlewis92/angular-calendar#677]
**Is your feature request related to a problem? Please describe**

The title days of mwl-calendar-month-view part of the calendar don't render nicely on small screens or when specified to display at a smaller resolution properly as the day names overlap or are hidden.
It would be great to be able to specify whether or not to render with short day names, without it is difficult to use the calendar as lower resolutions.

**Describe the solution you'd like**
Preferably specifying whether the mwl-calendar-month-view should render days as full day names or shortened day names would just be a config in mwl-calendar-month-view. 

**Describe your use case for implementing this feature**

Showing the calendar on mobile, or smaller than normal as an advanced date picker in our app.

**Additional context**

Apologies if didn't spot how to do this, was looking through documentation, especially here...
https://mattlewis92.github.io/angular-calendar/docs/components/CalendarMonthViewComponent.html

Great component and thanks for all the work you've done on it.

**Comment by JamboBuenna** [comment]
![image](https://user-images.githubusercontent.com/2864327/43713907-24967a56-9973-11e8-9415-d466095ce88c.png)

**Comment by JamboBuenna** [comment]
We used CSS, but it would be far nicer to solve the issue programatically, so don't have todo tricks to stop mobiles browsers from initally rendering the text at full size then breaking the layout.

![image](https://user-images.githubusercontent.com/2864327/43725190-cb111d12-9993-11e8-9ba5-2f7d9ad2b923.png)

**Comment by mattlewis92** [comment]
This is possible via a custom date formatter: https://mattlewis92.github.io/angular-calendar/#/customise-date-formats

You can read more about my reasoning for not supporting mobile out the box [here](https://github.com/mattlewis92/angular-calendar#does-this-calendar-work-with-mobile) tl;dr I'm not a ux designer and getting this to work great out the box on mobile and desktop is hard. Hope that helps! 😄

**Comment by JamboBuenna** [comment]
Thanks :-) If you want I can share styling back to the community to get this to work responsively when done.

**Comment by mattlewis92** [comment]
Yeah if you could that would be awesome! 😄  You can base your work off the [0.26 branch](https://github.com/mattlewis92/angular-calendar/tree/0.26) as that's where all new dev work is going on right now.

**Comment by thangviet222** [comment]
> Thanks :-) If you want I can share styling back to the community to get this to work responsively when done.

Hello, can you share me style your calendar. I try to change css in my component but it not work. 
I want to change size cell day in month view. Thank you so much .

**Comment by MarcioMercuri** [comment]
Boa noite, Gostaria de saber se tem como tirar o numeral "1" em vermelho do calendário !!!

**Comment by MarcioMercuri** [comment]
![image](https://github.com/mattlewis92/angular-calendar/assets/80365072/2ec0cb35-4013-4934-b1c3-752ab78c8db4)
