### ISSUE TITLE
The module last day segemento 24:00

### ISSUE THREAD

**Issue by rafaxplayer** [mattlewis92/angular-calendar#679]
**Is your feature request related to a problem? Please describe**
When I establish 6 segments in the day view.
The last one is the hour 23:45,

**Describe the solution you'd like**
For the functionality, my application would be necessary for it to be 24:00, since I have left this quarter of an hour without being able to use it.

**Describe your use case for implementing this feature**
I do not know if this is because the view always starts at 12:00 am and in my case it would need the opposite to end at 24:00 or 12:00 PM, with this I would have the solution.
Is there any way to get this?

**Additional context**

**Comment by mattlewis92** [comment]
Unfortunately, this isn't possible to do, as `24:00` isn't a valid time (it's midnight of the next day). The day view is designed to only ever show one day at a time, hence why the maximum time it can go to is `23:59`.
<img width="440" alt="screen shot 2018-08-07 at 20 44 36" src="https://user-images.githubusercontent.com/6425649/43815084-bba9269a-9a82-11e8-9118-8396865449f5.png">

**Comment by rafaxplayer** [comment]
ok, I understand, thanks for your reply
