### ISSUE TITLE
Calendar Modal does not appear

### ISSUE THREAD

**Issue by eduardogoncalves01** [mattlewis92/angular-calendar#681]
**Describe the bug**

When I try to select a date and open the calendar, it just does not open and the values ​​below appear as a string.

Sorry for ignorance if I'm forgetting something

**Screenshots**
![image](https://user-images.githubusercontent.com/30847816/43923971-b2070936-9bf9-11e8-8b17-95458eeb93bc.png)

**Versions**

- `@angular/core`: "6.0.0"
- `angular-calendar`: "^0.25.2"
- Browser name and version: Chrome version 67.0.3396.87

**Comment by eduardogoncalves01** [comment]
![image](https://user-images.githubusercontent.com/30847816/43923929-982abe9a-9bf9-11e8-99bf-8d834e46382d.png)

**Comment by mattlewis92** [comment]
Looks like you're missing the flatpickr stylesheet: https://github.com/mattlewis92/angular-calendar/blob/master/demos/demo-modules/kitchen-sink/module.ts#L1 Hope that helps! 😄

**Comment by eduardogoncalves01** [comment]
Oh thanks, sorry , and thanks for that, this works perfectly
