### ISSUE TITLE
Alternate Monthly View

### ISSUE THREAD

**Issue by shastaxc** [mattlewis92/angular-calendar#682]
**Is your feature request related to a problem? Please describe**
Yes, I think it has to do with the way views are switched using viewChange.emit()

**Describe the solution you'd like**
The problem I'm having is in implementing a custom view. The problem I'm running into is that it seems switching view is done by calling viewChange.emit('string') on button click. When changing the string to anything besides 'month', 'week', or 'day' I get an error:
```
ERROR TypeError: this.dateFormatter[method] is not a function
    at CalendarDatePipe.push../node_modules/angular-calendar/fesm5/angular-calendar.js.CalendarDatePipe.transform
```

I want to be able to use the name 'alt-month' with the current implementation of ngSwitchCase to switch to my new view without running into date formatting errors.

**Describe your use case for implementing this feature**
I want to add an additional monthly view while also retaining the current monthly view. I want to be able to give the user the option to view the default monthly calendar or click a button to switch the view to my custom view.

**Additional context**

**Comment by mattlewis92** [comment]
It'll be because of the value you're passing to the `calendarDate` pipe to render your title: https://github.com/mattlewis92/angular-calendar/blob/master/demos/demo-modules/kitchen-sink/template.html#L51

```{{ viewDate | calendarDate:((view === 'alt-month' ? 'month' : view) + 'ViewTitle'):'en' }}```

should fix it. Hope that helps!

**Comment by shastaxc** [comment]
You're right of course! Afterward, I also ran into this issue https://github.com/mattlewis92/angular-calendar/issues/442

This might be a good thing to add to your FAQ. But I finally got it all working. Thank you very much!

**Comment by mattlewis92** [comment]
`0.26` actually ships with an enum that you can use to prevent these types of errors: https://github.com/mattlewis92/angular-calendar/blob/0.26/demos/demo-modules/kitchen-sink/component.ts#L51
