### ISSUE TITLE
Displaying of interval time format in day view

### ISSUE THREAD

**Issue by Vineethgs91** [mattlewis92/angular-calendar#683]
**Is your feature request related to a problem? Please describe**

**Describe the solution you'd like**

**Describe your use case for implementing this feature**

**Additional context**

![capture](https://user-images.githubusercontent.com/34769784/43945007-7ff3eb26-9c9e-11e8-8668-6bdf15549c71.PNG)

i need a view like this .Can this implemented in the day view?

can anyone help?

**Comment by mattlewis92** [comment]
This is possible via a custom date formatter and showing the times that are hidden with css. Demo here: https://stackblitz.com/edit/angular-sdaqta?file=demo/component.ts Hope that helps! 😄
