### ISSUE TITLE
mwl-calendar-month-view day list

### ISSUE THREAD

**Issue by lwazevedo** [mattlewis92/angular-calendar#686]
**Is your feature request related to a problem? Please describe**
 Customize mwl-calendar-month-view in list mode
 I can not find a solution for customizing the layout I want.
     

**Describe the solution you'd like**
I would like to implement the month view in list. as shown:

 
**Describe your use case for implementing this feature**
Implementation example
![selecao_010](https://user-images.githubusercontent.com/17619473/44062676-c38fdfe2-9f33-11e8-9d21-4098ead6b0d8.png)

**Additional context**

**Comment by mattlewis92** [comment]
There's no support for anything like that in this library, but you could [build your own component](https://github.com/mattlewis92/angular-calendar#the-month-week-or-day-view-doesnt-meet-my-project-requirements-but-the-other-views-do) to replace the month view provided. Sorry I couldn't be of more help! 😢

**Comment by lwazevedo** [comment]
Its component is of excellent quality ...
It's a shame not this support, but thanks for the feedback ...
Thank you
