### ISSUE TITLE
Customizing the text in the header buttons

### ISSUE THREAD

**Issue by shanafme** [mattlewis92/angular-calendar#689]
**Is your feature request related to a problem? Please describe**

I'd like to be able to change the button text on the calendar's header.  
![image](https://user-images.githubusercontent.com/765569/44463921-41840680-a5e7-11e8-9016-72cc8b244d52.png)

I'd like to be able to customize the text on these three buttons to match user requests/requirements.  Similar to the way that titles and column headers can be customized through a provider, it would be nice to be able to customize button text as well.

We have an application that uses angular-calendar that it would make more sense for the user to see the word "current" instead of "today" on the button text (especially in the month view).

**Comment by mattlewis92** [comment]
Those buttons aren't actually part of the calendar component, they're just in the demo code, you can change them completely to whatever you want. Hope that helps! 😄

**Comment by shanafme** [comment]
D'oh, Sorry!!  I found the change I need to make.  I'm just learning Angular, so apologies for the silly request.  Thank you for your help!
