### ISSUE TITLE
Exclude Weekends and Holidays for Work based scheduling calendar

### ISSUE THREAD

**Issue by GenuineRex** [mattlewis92/angular-calendar#692]
**Is your feature request related to a problem? Please describe**

I am using angular-calendar in a work scheduling application and the business I am targeting rarely works weekends.  I would like to exclude weekends and holidays unless an exception for a specific day is added.

**Describe the solution you'd like**

Add a flag to the event to Ignore weekend days.
Add an array to the event for weekend/holiday days to include for this event.
Add an array for holidays to the calendar view.

**Describe your use case for implementing this feature**

Most events in my application would not show up on weekends and holidays indicating that the job (event) was not being worked that day.  This would be more clear for all users as they evaluated what work was happening on what days.  

**Additional context**

I believe this would be a common scenario for any line of business type application.

**Comment by mattlewis92** [comment]
Excluding weekends is possible via the `excludeDays` option, you can see a demo of that working here: https://mattlewis92.github.io/angular-calendar/#/exclude-days

You could disable public holidays by adding a css class on those days to indicate that it's a public holiday, you can see an example of how to do that here: https://mattlewis92.github.io/angular-calendar/#/min-max-date

Hope that helps! 😄
