### ISSUE TITLE
Drag and Drop using custom template in Month view

### ISSUE THREAD

**Issue by sachin-samel** [mattlewis92/angular-calendar#698]
**Describe the bug**
I am using angular-calendar with month view in our project.

I am using custom-template to display count.

I have kept **drag: true** in events.

Please see below code for reference:
https://stackblitz.com/edit/angular-wd9jzf-vt4peu?file=demo%2Fcomponent.ts

Is it possible to apply drag and drop functionality on custom template?

Thanks.

**Minimal reproduction of the problem with instructions**

**Screenshots**

**Versions**

- `@angular/core`: 6.0.4
- `angular-calendar`:  0.25.2
- Browser name and version: Chrome 68.0.3440.106

**Comment by AhHa45** [comment]
I have the same issue.

**Comment by einsuas** [comment]
I have the same issue

**Comment by mattlewis92** [comment]
You need to apply the [draggable directive](https://github.com/mattlewis92/angular-draggable-droppable) to the events you want to make draggable. If you take a look at the source for the template you'll see it in action [here](https://github.com/mattlewis92/angular-calendar/blob/master/src/modules/month/calendar-month-cell.component.ts#L42-L44). Hope that helps! 😄

**Comment by sachin-samel** [comment]
Thanks.

**Comment by einsuas** [comment]
The link https://github.com/mattlewis92/angular-calendar/blob/master/src/modules/month/calendar-month-cell.component.ts#L42-L44 is not working

**Comment by einsuas** [comment]
I am using angular 4, and in the week and day view its work fine but in the month view not working, I am not have instaled angular 6.0+ drag and drop, so how it works on the week and day view

**Comment by mattlewis92** [comment]
Oops, when I merged in the latest release it broke the link, here you go:
https://github.com/mattlewis92/angular-calendar/blob/188022e19e9c85e4660797968a7f33b372c2d8e8/projects/angular-calendar/src/modules/month/calendar-month-cell.component.ts#L43-L47

**Comment by giolongo** [comment]
Hi, I used this solution, thanks.

I have the problems, when i click on day I open a NgbPopover, with [autoClose] = "'outside'" property, but if in the container there is mwlDraggable directive, the new popover will be open, but the others remains opened, it's like i click inside the other popover or i not click.
