### ISSUE TITLE
how to connect firebase

### ISSUE THREAD

**Issue by macorifice** [mattlewis92/angular-calendar#702]
**Is your feature request related to a problem? Please describe**

**Describe the solution you'd like**
Hi. I'm making my own angular calendar and I would like to connect firebase.

**Describe your use case for implementing this feature**
For read & write calendar event.

**Additional context**

**Comment by mattlewis92** [comment]
You can use the async events example as a starting point: https://mattlewis92.github.io/angular-calendar/#/async-events and then instead of the http library for fetching events, you can use firebase. Hope that helps!
