### ISSUE TITLE
Javascript recurring dates library

### ISSUE THREAD

**Issue by thefliik** [mattlewis92/angular-calendar#711]
So angular-calendar is awesome :)

I'm using it in a project I'm working on with some rather complex recurring schedules. I ended up making a new javascript (typescript) recurrence library which implements the ICAL spec to handle it: [rSchedule](https://gitlab.com/john.carroll.p/rschedule). 

This is really just an FYI, but I wanted to call out the fact that I think it pairs particularly well with your library for two reasons:

#### 1.
After creating a recurring schedule, the library can [automatically return ordered recurrences by "calendar month".](https://gitlab.com/john.carroll.p/rschedule/wikis/usage/calendar-class) This can either be grouped by the start and end of the actual month, or by the start of the first week of the month and end of the last week of the month (which can include dates in the preceding and next months). This makes it easy to get dates for the month view of `angular-calendar`.

```typescript
const calendar = new Calendar({
  schedules: new RRule({
    start: new Date(),
    frequency: 'DAILY',
    byDayOfWeek: ['MO']
  })
})

const iterator = calendar.collections({
  granularity: 'MONTHLY',
  weekStart: 'MO'
})

for (const collection of iterator) {
  // yields a collection object containing all the dates for that month

  for (const date of collection.dates) {
    // do stuff
  }
}

// or just get the next collection

const collection = calendar.collections({
  start: new Date()
  granularity: 'MONTHLY'
  weekStart: 'MO'
}).next().value
```

#### 2.

Like angular-calendar, rSchedule makes use of a [`DateAdapter` interface](https://gitlab.com/john.carroll.p/rschedule/wikis/date-adapter/date-adapter-interface) so that it is date library agnostic. DateAdapters for the standard javascript `Date` object, as well as `Moment` and luxon `DateTime` objects exist. When using moment-timezone or luxon date adapters, rSchedule has full time zone support.

Anyway, thanks so much for your work maintaining angular-calendar!!!

## [You can learn more about rSchedule over in it's repo.](https://gitlab.com/john.carroll.p/rschedule)

**Is your feature request related to a problem? Please describe**

**Describe the solution you'd like**

**Describe your use case for implementing this feature**

**Additional context**

**Comment by thefliik** [comment]
Oh also, almost forgot, you might be interested in how I implemented my date adapters as they basically do all the same stuff as your date adapters, yet they require the end user to implement way less if they're creating a custom date adapter.

What I did:

I created a [generic `DateTime` object](https://gitlab.com/john.carroll.p/rschedule/blob/master/packages/rschedule/src/lib/date-time.ts) with equivalent functionality to everything you have in your date adapter interface (i.e. it has `setHours`, `addHours`, etc methods) .

If a user creates a custom date adapter, they extend my date adapter base class which provides methods like `setHours`.

When `setHours` is called on a custom child date adapter, the child date adapter returns `super.setHours(this)`.

In the super call the date adapter instance is passed into a `DateTime` instance, the datetime extracts all the time info (`year`, `month`, `day`, `hour`, `minute`, `second`, `millisecond`) and instantiates a new UTC date with that time info `new Date(Date.UTC())`. It then manipulates the date however it needs to be manipulated (in this example, `addHours`) and then passes the new `year`, `month`, `day`, `hour`, `minute`, `second`, `millisecond` back to the custom child date adapter which uses the values to instantiate a new date object using whatever javascript date library is appropriate for that date adapter (e.g. `Moment`), replacing the old value. This allows me to provide most all the necessary date adapter functionality for the end user, *greatly* reducing the number of methods an end user needs to implement in a custom date adapter.

You can check out my base date adapter here: https://gitlab.com/john.carroll.p/rschedule/blob/master/packages/rschedule/src/lib/date-adapter/date-adapter-base.ts

The individual, non-base, date adapters which I provide (e.g. [MomentDateAdapter](https://gitlab.com/john.carroll.p/rschedule/blob/master/packages/moment-date-adapter/src/lib/moment-tz-date-adapter.ts)) are kept in separate packages within the mono-repo.

**Comment by mattlewis92** [comment]
Hey! Thanks for sharing your lib, it looks really great 😄  I'm curious as to the advantages of your lib over [rrule](https://github.com/jakubroztocil/rrule)?

**Comment by mattlewis92** [comment]
Sweet, thanks for taking the time to explain that, it makes a lot of sense! I've added a link to your lib in the recurring demo as an alternative to rrule ✌️

**Comment by thefliik** [comment]
@meiuqer when you say "this library," are you referring to `angular-calendar` or `rSchedule`?

**Comment by meiuqer** [comment]
I'm sorry i meant for rSchedule. Just a simple recurring event made with rSchedule implemented in the angular-calender.

**Comment by thefliik** [comment]
@meiuqer so here's a simple stackblitz example which may help:
https://stackblitz.com/edit/github-zmc1k2?file=src/app/app.component.ts

Take a look at the `app.component.ts` file.

I based it off the [`angular-calendar` angular-cli build-tool-example](https://github.com/mattlewis92/angular-calendar/tree/master/build-tool-examples/angular-cli). Unfortunately, there appears to be a bug in the current angular-cli build-tool-example which prevents it from working in stackblitz (simply importing the angular-cli example, without making any changes, produces an error for me in stackblitz). This problem seems to be unrelated to rSchedule and I'll open a separate issue about it.

Anyway, this bug means that the stackblitz example doesn't actually work. I *think* the example will work if you build it locally though, and regardless, hopefully you get the idea. If you need help using rSchedule "in general," you should [check out the docs for it](https://gitlab.com/john.carroll.p/rschedule/wikis/home).

**Comment by meiuqer** [comment]
Thanks! I will check it out! But it's a great addition to your already great post! 👍
