### ISSUE TITLE
Is there any way to set the calendar timezone independent from the locale ?

### ISSUE THREAD

**Issue by daneshmandi** [mattlewis92/angular-calendar#714]
**Is your feature request related to a problem? Please describe**

I need to change the timezone of the calendar at run-time and it needs to be independent from the locale. Is there any way to do this ?

**Describe the solution you'd like**

If we can bind it the way we can bind locale like [timezone]="MyTimeZone" would be good.

**Describe your use case for implementing this feature**

I am implementing an scheduler app that requires to change the timezone on the fly and see the scheduled event in that specific timezone.

**Additional context**

**Comment by mattlewis92** [comment]
I do the same thing in my app as well, you can use [moment](https://mattlewis92.github.io/angular-calendar/#/moment) instead of date-fns and then [set the timezone](https://stackoverflow.com/questions/17697696/set-global-timezone-with-momentjs) via `moment-timezone`. Hope that helps! 😄

**Comment by daneshmandi** [comment]
Does this applies the updated timezone to be used inside CalendarMomentDateFormatter after it was initialized with different timezone?

**Comment by andrewryan1906** [comment]
Everyone,

I'd like to use this solution, but if I change the timezone via the global property, it changes it across my application. In my use case, I have one specific component that needs to work in a different timezone. I'm building an event scheduler and it needs to work in the timezone of the event; so if I'm building a schedule for an event in Australia, 10:00 am neesds to be 10:00 am in Australia.

Any suggestions?

**Comment by pjuzeliunas** [comment]
If you use UTC time, then it can be converted to timezoned time using `utcToZonedTime` function from `date-fns-tz` package.

```
import { utcToZonedTime } from 'date-fns-tz';
```

```
let utcDate = new Date(yourOriginalTimestamp)
let adjustedDate = utcToZonedTime(utcDate, "Europe/Vilnius")
```

Then you just pass the `adjustedDate` to your `CalendarEvent`.

Read more in this [doc](https://github.com/marnusw/date-fns-tz#time-zone-helpers).

**Comment by siva-geddada** [comment]
We have an issue with the date format using moment in Chrome

Initally i am coding like this way 
 const agentdate = moment
        .utc(val.begins_at)
        .subtract(pre_duration, 'm')
        .tz('America/Los_Angeles')
        .format('hh:mm a- MMM DD, yyyy');

Chrome is not supporting the above date format , Firefox will work 

This Format will work Both Chrome and FireFox as well 
const agentdate = moment
        .utc(val.begins_at)
        .subtract(pre_duration, 'm')
        .tz('America/Los_Angeles')
        .format('MMM dd, yyyy - hh:mm a');

**Comment by sdstmi88** [comment]
Is it possible to use the week-view calendar completely independently of the client's time zone, that is, to use a specific time zone so that the start/end dayHour (00-23) refer to the local time of that defined time zone, not to the client's zone? 
Also I expect to get events mapped properly according to the specific time zone.

**Comment by nishikantHbox** [comment]
I'm not able to set the calendar time-zone as @mattlewis92 suggested. Please help
