### ISSUE TITLE
Recurring events bug

### ISSUE THREAD

**Issue by dani1993** [mattlewis92/angular-calendar#717]
**Describe the bug**

On recurring events mode, the calendar loses one day and then marks the event on the wrong day.

In November the recurrence returns to be correct.

**Minimal reproduction of the problem with instructions**

**Screenshots**

![2018-09-08 15_36_01-angular 6 0 calendar](https://user-images.githubusercontent.com/16021162/45256948-3e866580-b39e-11e8-824f-f6322bb87845.png)

**Versions**

- `@angular/core`: 6+
- `angular-calendar`: 0.26
- Browser name and version: chrome

**Comment by mattlewis92** [comment]
Ah, it's an issue with DST changes. You can work around it by using moment and setting your timezone to UTC so all date operations will ignore timezone changes. I've updated the demo to work this way, thanks for the bug report! 😄

**Comment by JoelMacKenzie** [comment]
Has this been fixed, or is the workaround still needed?
