### ISSUE TITLE
Click-drag-release event creation

### ISSUE THREAD

**Issue by milospantic** [mattlewis92/angular-calendar#719]
**Is your feature request related to a problem? Please describe**

No.

**Describe the solution you'd like**

When you click-drag and release it should add event with dragged time.

**Describe your use case for implementing this feature**

User can add event easily by clicking and dragging - no need for clicking to add event then click again to adjust time.

**Additional context**

![clickdragrelease](https://user-images.githubusercontent.com/37027795/45301377-21be6f00-b511-11e8-8986-03c4ff120244.gif)

**Comment by rubenheymans** [comment]
would be nice if you could restrict the click-drag to certain hours/days

**Comment by mattlewis92** [comment]
I've [added an example to the docs](https://mattlewis92.github.io/angular-calendar/#/drag-to-create-events) to show how you can use a custom template to hook into the mousedown event on the week view and then implement this logic yourself. Hope that helps! 😄
