### ISSUE TITLE
New event start date based on chosen day 

### ISSUE THREAD

**Issue by piotreksko** [mattlewis92/angular-calendar#721]
**Is your feature request related to a problem? Please describe**

Hello, I am still using AngularJS version of this calendar, but hopefully this is very similar. 
Not really a feature request, but a question related to the way the calendar works.
Is it is possible to fetch the date that I choose on calendar (for example click on 20th of September) and then have that date as a starting date for a new event? Where should I find the data about clicked date?

**Describe the solution you'd like**

Get/find the information about date clicked on calendar

**Describe your use case for implementing this feature**

I have a seperate dialog box for a new event. When I chose a date on main calendar I want to have that date as a starting date for a new event.

**Additional context**

--

**Comment by mattlewis92** [comment]
You can use this demo as a starting point: https://mattlewis92.github.io/angular-bootstrap-calendar/#!?example=timespan-click Hope that helps!
