### ISSUE TITLE
Header clicked on day in month view

### ISSUE THREAD

**Issue by agilob** [mattlewis92/angular-calendar#722]
**Is your feature request related to a problem? Please describe**

Week view has `dayHeaderClicked`, but month view doesn't. 

**Describe the solution you'd like**

I would like to select all days in a column, by getting a callback from the header cell which contains days [Monday, Tuesday, ...]

**Describe your use case for implementing this feature**

User would like to create events on every Monday until 2 years from now, clicking on day header should provide a feedback which day was clicked. `dayHeaderClicked` is available in week view, but month view doesn't have it, implementation looks inconsistent. Callback would return integer, 0 for Sunday, 6 for Saturday = consistent with settings `excludeDays: number[] = [0, 6];`

**Comment by mattlewis92** [comment]
This sounds like a reasonable request, would you like to make a [make a pull request](http://makeapullrequest.com/)?

**Comment by mattlewis92** [comment]
I finally had time to finish and release `0.27`, thanks for your contribution! 😄
