### ISSUE TITLE
Subdivide Day View by Group

### ISSUE THREAD

**Issue by Geux** [mattlewis92/angular-calendar#727]
**Is your feature request related to a problem? Please describe**
I'm frustrated

**Describe the solution you'd like**
Is it possible to subdivide Day View (on mwl-calendar-day-view) by groups (e.g. group1, group2, group3) for the same day ?

One other option is maybe to get x instance of mwl-calendar-day-view as I get x groups, but I find it very ugly.

Any ideas are welcome,

Thanks a lot.

**Describe your use case for implementing this feature**

**Additional context**

**Comment by mattlewis92** [comment]
Please see this thread for an example of how to do this via a custom template: https://github.com/mattlewis92/angular-calendar/issues/269
