### ISSUE TITLE
Time Format in CalendarDayView

### ISSUE THREAD

**Issue by Geux** [mattlewis92/angular-calendar#729]
**Is your feature request related to a problem? Please describe**
I'm frustrated

**Describe the solution you'd like**
Is it possible to print time format in 24 hours format instead of 12 hours in the calendar-day-view ?
I'm trying to juggle with locale without succes (e.g. my time is 17:44 but my calendar still print 5 PM :()

Thanks a lot.

**Describe your use case for implementing this feature**

**Additional context**

**Comment by mattlewis92** [comment]
Sorry to hear you're having trouble, if you check out this demo of how to use a custom date formatter it has an example of what you need: https://mattlewis92.github.io/angular-calendar/#/customise-date-formats Hope that helps! 😄

**Comment by Geux** [comment]
Thank you a lot, it's working like a charm.
