### ISSUE TITLE
Uncaught (in promise): Error: Cannot assign to a reference or variable!

### ISSUE THREAD

**Issue by coolmonster** [mattlewis92/angular-calendar#731]
**Describe the bug**
I am creating a multiple instance of the calendar like 3 month view 6 month view and 12 month view by using structural directive ngFor but when i am assigning the date value in mwlCalendarNextView directive then it throws the error Cannot assign to a reference or variable!

`<div class="calenderWrap" *ngFor="let date of viewDates" > 
 {{ viewDate }} {{ date }}
                          <div class="content">
                            <div class="text-center custmMontDetail"><span class="prevArrow spriteSheet"><</span>{{ viewDate | calendarDate:(view + 'ViewTitle'):'en' }}<span  mwlCalendarNextView
                                [(viewDate)]="date"
                                 [view]="view"class="spriteSheet nextArrow">></span></div>
                            <mwl-calendar-month-view
                            [weekStartsOn]="weekStartsOn"
                            [weekendDays]="weekendDays"
                            [viewDate]="date"
                            [events]="events"
                            [cellTemplate]="customCellTemplate">
                          </mwl-calendar-month-view>
                          </div>
                    </div>
`

**Minimal reproduction of the problem with instructions**
this is the plunker which show some code i have written i hope you get the idea from the plunker
https://plnkr.co/edit/M8lQGeccErWfJHL544Rx?p=catalogue

**Screenshots**
![screenshot from 2018-09-13 16-33-34](https://user-images.githubusercontent.com/20675609/45485014-b922fc80-b773-11e8-8a27-a967ead30dc1.png)

**Versions**

- `@angular/core`:6.0.3
angular-calendar`:0.26.0
- Browser name and version:Chrome latest

**Comment by mattlewis92** [comment]
I think your issue is caused by invalid html `[view]="view"class="spriteSheet nextArrow"` should be `[view]="view" class="spriteSheet nextArrow"` (note the space between the properties)
