### ISSUE TITLE
Option to hide time grid in week view

### ISSUE THREAD

**Issue by kamihamiha123** [mattlewis92/angular-calendar#735]
**Is your feature request related to a problem? Please describe**

Yes, I use only allDay events in week view, time grid takes place while it's empty

**Describe the solution you'd like**

Having a boolean input for week view component  to hide or show time grid

**Describe your use case for implementing this feature**

this input would be set to true when we use only all day events

**Additional context**

nothing

**Comment by mattlewis92** [comment]
You can use CSS to hide it:
```
.cal-time-events {
  display: none;
}
```

Hope that helps! 😄

**Comment by kamihamiha123** [comment]
TY, I did this, but I need also to hide the first column, It needs a lot of hacks to achieve, it would be better to have a proper way to do it
