### ISSUE TITLE
can we use this in angular 5 project ?

### ISSUE THREAD

**Issue by shubhabairav** [mattlewis92/angular-calendar#740]
**Is your feature request related to a problem? Please describe**

**Describe the solution you'd like**

**Describe your use case for implementing this feature**

**Additional context**

**Comment by AhHa45** [comment]
yes it's also compatible with angular 6

**Comment by mattlewis92** [comment]
Please see [here](https://github.com/mattlewis92/angular-calendar#does-this-library-work-with-angular-5x), thanks!

**Comment by Assdi** [comment]
I think this link is outdated @mattlewis92  .
