### ISSUE TITLE
Double click on day in month view

### ISSUE THREAD

**Issue by wutkaru** [mattlewis92/angular-calendar#741]
**Is your feature request related to a problem? Please describe**
`dayClicked ` only single click 

**Describe the solution you'd like**
`dblDayClick`
I would like to catch click and double click event in month view.
 
**Describe your use case for implementing this feature**
dayClick, once-click to do some function a() 
dblDayClick, double click to do some function b()

**Comment by mattlewis92** [comment]
You can implement this by using a custom event template for the month cell. I've put together an example of how to do that [here](https://stackblitz.com/edit/angular-2gnxfv?file=demo/component.ts). Hope that helps! 😄

**Comment by vicky-rain** [comment]
I want to double click event in dayClicked. What can I do?
