### ISSUE TITLE
wrong dependencies in calendarUtils.provider.ts

### ISSUE THREAD

**Issue by Geux** [mattlewis92/angular-calendar#742]
**Is your feature request related to a problem? Please describe**
I'm still trying to customize the Day View of your calendar.
I follow your recommendations in the section "How do I use a custom template?", and I imported your code from your repo on Github.

Unfortunatly, the calendarUtils.provider.ts class won't compile because of WeekViewEventRow which is not recognized. 
Any idea of the problem ? 
I'm running Angular CLI 6.2.1 and angular-calendar 0.26.0

Thanks a lot.

![bug](https://user-images.githubusercontent.com/1436279/45616987-46ff3000-ba71-11e8-9bf9-7343df3d4138.jpg)

**Describe the solution you'd like**

**Describe your use case for implementing this feature**

**Additional context**

**Comment by AhHa45** [comment]
Can you please tell me what kind of customization you are trying to achieve?
I will do my best to help you then.

**Comment by Geux** [comment]
@AhHa45 : I'm trying so subdivide a day by a meta property (like in https://github.com/mattlewis92/angular-calendar/issues/269).

I need a custom header first and then a custom "body" view.

**Comment by mattlewis92** [comment]
If you have a look at the breaking changes section [here](https://github.com/mattlewis92/calendar-utils/commit/c4170abb97a1fe236b650eefab2c7c79e4b1a974) it details how to migrate. Will try and find some time soon to update that demo to the latest version and add it as an "official" demo to the demos (so it will stay up to date with each version)

**Comment by Geux** [comment]
Hi @mattlewis92 
Thanks a lot for the link about migration ! :+1: 

Oddly, I was forced to add "@Input() dateAdapt: DateAdapter;" at the beginning of the CalendarDayViewComponent in calendar-day-view.component.ts to make refreshHourGrid and refreshView working.

![Uploading Untitled 1.jpg…]()

Is was working on your side ?

Anyway, I've still another error on emitBeforeViewRender()

![untitled 2](https://user-images.githubusercontent.com/1436279/45681975-3a490d80-bb3f-11e8-9ac0-be3d31709176.jpg)

Any idea ?


Thanks a lot :)

**Comment by mattlewis92** [comment]
Finally had some free time this weekend to upgrade the plunker and add it to the examples: https://mattlewis92.github.io/angular-calendar/#/day-view-scheduler Threw this together quite quickly so there might be issues, if you find any or can think of improvements feel free to [send a PR](http://makeapullrequest.com)! 😄
