### ISSUE TITLE
Ordering of calendar events

### ISSUE THREAD

**Issue by maxprais1** [mattlewis92/angular-calendar#743]
**Describe the bug**

I am building a calendar where there are two types of events: built-in events, like Christmas, and events that are user-created, like a holiday. 

I am ordering my events array with the built-in events first in the hope that they will appear at the top of the calendar, but there seems to be no logic to the order in which they are rendered. 

So my question: **Is there a way to guarantee the order of the events as they are rendered to the calendar?** 

**Versions**

- `@angular/core`: 6.1.4
- `angular-calendar`: 0.26.0
- Browser name and version: Chrome Version 68.0.3440.106

**Comment by mattlewis92** [comment]
There's nothing in the code that re-orders events, it should render them in the order you provide, can you share a stackblitz that shows your issue so I can see what's going wrong? Thanks! 😄

**Comment by AhHa45** [comment]
we extended the month view and in our custom template we do it like this

```
<div *ngFor="let event of getSortedEvents(day.events); let i = index;"
                 dragActiveClass='cal-drag-active'>
(...)
            </div>
(...)
```

with the function getSortedEvents(day.events) like:

```
public getSortedEvents(events: CalendarEvent[]) {
        return events.sort((a, b) => {
                return new Date(a.start).getTime() - new Date(b.start).getTime();
        });
    }
```

**Comment by maxprais1** [comment]
Hi @mattlewis92 the week view is broken in the Stacckblitz on your website
https://stackblitz.com/run?file=demo/component.ts. There is an error with the bootstrap that I think is causing the week view events to not be displayed

**Comment by maxprais1** [comment]
@mattlewis92 To elaborate a little more without the stackblitz. I am trying to establish an order for `allDay` events in relation to your latest version 0.26. I have played a little more with the events; ordering them alphabetically for example, and there is still no change in how they appear in the week view as `allDay`.

**Comment by mattlewis92** [comment]
Ah right I see, the all day events are actually bucket sorted to insert them into the optimal positions, otherwise you get a bad UX where every event needs to be on it's own line to display (this was actually the original behaviour way back in the angular 1 version but loads of people complained so I changed it). An example of what you're trying to achieve here would be really helpful to see if it's possible to tweak the bucket sort algorithm to meet your use case. You can [use this](https://stackblitz.com/edit/angular-grhyfa?file=demo/component.ts) as a starter.

**Comment by maxprais1** [comment]
Hi @mattlewis92 I have created a demo for you here: https://stackblitz.com/edit/angular-calendar-events-demo?file=demo/component.ts

- My feature uses only the `allDay` events. I hide the calendar times.
- The 'calendarEvent' type (in the event meta data), which have the bullet points, are all meant to be at the top, and you will see that I have ordered the events array in that way.

The problem, as I have demonstrated, is that events do appear to be ordered by date:
![image](https://user-images.githubusercontent.com/26567064/46081313-24b59280-c194-11e8-8525-9151cfd20cf4.png)

You can the event titled `Calendar event starting during a holiday event` is ordered below the event `An event that is the same length as the one above`, seemingly because it starts later than the one above.

So sorting algorithm solution needs to take more care over the order of the events array.

Thank you so much for your helpful response, I can feel we are getting closer to a solution 😄 Let me know if you need me to clarify anything.

**Comment by mattlewis92** [comment]
Thanks for the repro, that's really helpful to see what you're trying to achieve 😄  Just so we're clear you would expect the order to be:
```
A 3 day event
Calendar event starting during a holiday event
An event the same length as the one above
Another event | a long event that spans 2 months
```

**Comment by maxprais1** [comment]
Exactly, that's what I'm looking for! Let me know if I can help in any other way

**Comment by leemorris** [comment]
@maxprais1,
 I am looking for the same functionality as you are. 
You said:

> My feature uses only the allDay events. I hide the calendar times.

How did you go about doing that?
Thanks

**Comment by mattlewis92** [comment]
Sorry about the late reply on this one, I've been travelling a lot the past few weeks. If you override the `getWeekView` function you can implement the splitting of events yourself by creating 2 separate views and then merging the results together. I've put together a demo of how this can work [here](https://stackblitz.com/edit/angular-calendar-events-demo-upyrjz?file=demo%2Fmodule.ts). Hope that helps! 😄

**Comment by maxprais1** [comment]
@mattlewis92 Thank you so much it works perfectly!
