### ISSUE TITLE
Unable to build after Angular Calendar update

### ISSUE THREAD

**Issue by pisix** [mattlewis92/angular-calendar#744]
**Describe the bug**

After migrating Angular Calendar to 0.26.0, I'm unable to build project.

**Screenshots**

<img width="973" alt="capture d ecran 2018-09-17 a 17 57 37" src="https://user-images.githubusercontent.com/1443226/45635026-387e3c00-baa4-11e8-9a98-15cb6dcd6af0.png">

**Versions**

```
-Angular CLI: 6.2.2
- Node: 8.9.4
- OS: darwin x64
- Angular: 6.1.7
- angular-calendar: 0.26.0
```
Any way to fix ?

**Comment by mattlewis92** [comment]
I've seen this happen before when you upgrade dependencies and import paths change which confuses webpack, if you cancel the build and restart the cli it should start working. Failing that, please attach a minimal repo that reproduces your issue and I'd be happy to debug further! 😄
