### ISSUE TITLE
No provider for DateAdapter

### ISSUE THREAD

**Issue by arbinoy** [mattlewis92/angular-calendar#745]
**Describe the bug**

Getting an error for DateAdapter, it says there's no provider for it even though I declared it on the app.module. 

**Minimal reproduction of the problem with instructions**

**Screenshots**

![image](https://user-images.githubusercontent.com/38565588/45664211-492ec080-bb3d-11e8-977a-c2a610119667.png)
![image](https://user-images.githubusercontent.com/38565588/45664230-59df3680-bb3d-11e8-8356-12d82d5de331.png)
![image](https://user-images.githubusercontent.com/38565588/45664257-6f546080-bb3d-11e8-9144-bac3dff39837.png)

**Versions**

- `@angular/core`: 6.1.7
- `angular-calendar`: 0.26.1
- Browser name and version: Chrome

**Comment by arbinoy** [comment]
Never mind. I tried restarting the everything and it worked. Apparently it had something to do with updating the dependencies.

**Comment by Nikola-Andreev** [comment]
I have the same error. I updated my angular version to 7.0.4 and boom.  

![error](https://user-images.githubusercontent.com/19424332/48553611-ba43e780-e8e4-11e8-9132-2180d3bdff7a.png)  

"@angular/core": "^7.0.4",  
"angular-calendar": "^0.26.4",  

Does someone has idea how to fix it?

**Comment by Nikola-Andreev** [comment]
Problem solved. I have forgot to import it this way in one of the modules:

```
CalendarModule.forRoot({
            provide: DateAdapter,
            useFactory: adapterFactory
        }),
```
