### ISSUE TITLE
Moving the tail of an event that spans across two days in monthly view changes the event source start.

### ISSUE THREAD

**Issue by daneshmandi** [mattlewis92/angular-calendar#746]
**Describe the bug**

Drag and dropping the tail of an event (that spans across two days ) in the same day in monthly view will changes the start and end of the source event.

**Minimal reproduction of the problem with instructions**

Consider you have an event that spans across two days. Fore instance the event starts at _2018/09/18 11:00 PM_ and will finish by _2018/09/19 03:00 AM_. Then in the monthly view drag the tail part of the event that appears on 2018/09/19 and drop it again in the same day (2018/09/19). Then you would see that the event source will increment by one day. In this case, it will becomes _2018/09/19 11:00 PM_ to _2018/09/20 03:00 AM_.

**Screenshots**

NA

**Versions**

- `@angular/core`: 6.0.0
- `angular-calendar`: 0.26.0
- Browser name and version: Chrome 68.0.3440.106

**Comment by mattlewis92** [comment]
Thanks for reporting! Would you like to make a PR with a fix? If you add the day to the drop data [here](https://github.com/mattlewis92/angular-calendar/blob/master/projects/angular-calendar/src/modules/month/calendar-month-cell.component.ts#L46) and then pass it to the drop event [here](https://github.com/mattlewis92/angular-calendar/blob/master/projects/angular-calendar/src/modules/month/calendar-month-view.component.ts#L347) you can check if the day it was dropped on and the day it was dragged from are different and if so then do nothing.

**Comment by daneshmandi** [comment]
@mattlewis92 Sure! I would be glad to. Although I haven't done any Pull Request in github before.

**Comment by mattlewis92** [comment]
No worries, there's a great learning resource for it here: http://makeapullrequest.com/

**Comment by mattlewis92** [comment]
This should be fixed now in `0.26.2`, thanks for reporting! 😄
