### ISSUE TITLE
hiding time grid in week view properly

### ISSUE THREAD

**Issue by kamihamiha123** [mattlewis92/angular-calendar#748]
**Describe the bug**

I use only allDay events in weekView, so I need to hide time grid. I added the following css rules :
```
cal-time-events {
    display: none !important;
  }
.cal-week-view .cal-day-headers {
    padding-left: 0 !important;
}
  .cal-week-view .cal-all-day-events .cal-time-label-column {
    display: none !important;
}

.cal-week-view .cal-time-label-column {
    width: 0px;
}
```
Time grid is now hidden but events are not in the right position. I have tried to shift events with some hard-coded number of pixels but it doesn't work since it depends on some internal logic of event positioning.

**Minimal reproduction of the problem with instructions**

**Screenshots**

Screenshot : https://prnt.sc/kwofz3

**Versions**

 "angular-calendar": "^0.26.1",

- `@angular/core`:
- `angular-calendar`:
- Browser name and version:

**Comment by mattlewis92** [comment]
Looks like you nearly got it, you need to add this as well:

```
.cal-week-view .cal-events-row {
  margin-left: 0 !important;
}
```

https://stackblitz.com/edit/angular-shzmu1?file=index.html

Hope that works for you! 😄

**Comment by arorakanav11** [comment]
hi @mattlewis92 thanks for the solution but I think for hiding time coloum we just need
```
.cal-week-view .cal-time-label-column {
  display: none !important;
}

.cal-week-view .cal-day-headers {
  padding-left: 0;
}

.cal-week-view .cal-events-row {
  margin-left: 0 !important;
```
and not 
```
.cal-week-view .cal-time-events,
 .cal-week-view .cal-time-label-column {
   display: none !important;
 }

 .cal-week-view .cal-day-headers {
   padding-left: 0;
 }

 .cal-week-view .cal-events-row {
   margin-left: 0 !important;
 }
```
we dont have to hide `.cal-week-view .cal-time-events,`  beacuse it hides the whole grid
