### ISSUE TITLE
List views

### ISSUE THREAD

**Issue by Tankske** [mattlewis92/angular-calendar#749]
**Is your feature request related to a problem? Please describe**

Scaling a calendar in general is difficult for mobile devices. It would be nice to be able to switch to more mobile friendly components.

**Describe the solution you'd like**

There are multiple solutions that could be applied:
- Switching to CalendarDayView (what I'm currently using as it is available)
- Switching to a week view that consists of multiple CalendarDayViews below each other. Perhaps showing more days if you keep on scrolling downwards..
- Swithcing to a list view could be useful as well. rfr [google calendar app](https://coolmomtech.com/wp-content/uploads/sites/2/2015/03/google-calendar-app-review.jpg) The list view could show only one column adding days behind each other. Another possibility is to display a week as multiple lists next to each other.

**Describe your use case for implementing this feature**

My preference would be to switch view depending on size of screen, but some people might prefer the list-view. If developers can define their own event component that is listed, this could be a very powerful utility.

**Additional context**

I understand this could be a large request, but perhaps you've already thought about this. I couldn't find any documentation about future plans with this library of which I'm a big fan!

**Comment by mattlewis92** [comment]
Thanks for opening an issue! I [agree completely](https://github.com/mattlewis92/angular-calendar#does-this-calendar-work-with-mobile) that it's impossible to provide a responsive calendar component that works with a great UX on both desktop and mobile. I think the use case you're describing could actually be built as an extension on top of this package, where you could use some of the components from this package and add the list view you've described. I'd rather not add it to the core library itself as I don't really want to maintain it. Sorry I couldn't be of more help!

**Comment by Tankske** [comment]
Hi Matt,

No problem. I understand. When I build such a component, pull the project and start working with existing components. I could then push the result to this package or as a separate branch, as you prefer. Could you agree to this? Could I also count on your support if I have questions. I want to avoid mis-using certain components you've build with a certain purpose, in other words forbl the component architecture.

Kind regards,
Yves
On 25 Sep 2018, at 23:47, Matt Lewis <notifications@github.com<mailto:notifications@github.com>> wrote:

Thanks for opening an issue! I agree completely<https://nam03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmattlewis92%2Fangular-calendar%23does-this-calendar-work-with-mobile&data=02%7C01%7C%7C344769846cdd4193967508d623308602%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636735088638620272&sdata=ZPBmXJXo3C7CKLKic6fkVD5ldmziTu%2FXFBFmUjXXQs0%3D&reserved=0> that it's impossible to provide a responsive calendar component that works with a great UX on both desktop and mobile. I think the use case you're describing could actually be built as an extension on top of this package, where you could use some of the components from this package and add the list view you've described. I'd rather not add it to the core library itself as I don't really want to maintain it. Sorry I couldn't be of more help!

**Comment by mattlewis92** [comment]
I *think* you could actually build a separate package on top of the components provided by this lib without having to change anything here, something like `angular-calendar-responsive`. If it gets mature and stable enough we could perhaps look at merging it back in here in the future. I'm moving between 3 continents at the moment so don't have a huge amount of free time, but would be happy to jump on a short hangout or something to try and answer any questions you might have.

**Comment by Tankske** [comment]
OK, great! Sounds like a good plan. I don't have questions at the moment, but it's good to know that we can interact/align on the current components if needed so the new library can be qualitative.
On 28 Sep 2018, at 01:39, Matt Lewis <notifications@github.com<mailto:notifications@github.com>> wrote:

I think you could actually build a separate package on top of the components provided by this lib without having to change anything here, something like angular-calendar-responsive. If it gets mature and stable enough we could perhaps look at merging it back in here in the future. I'm moving between 3 continents at the moment so don't have a huge amount of free time, but would be happy to jump on a short hangout or something to try and answer any questions you might have.
