### ISSUE TITLE
cssClass

### ISSUE THREAD

**Issue by hugocaldeira** [mattlewis92/angular-calendar#750]
**Describe the bug**

In the example for Custom event class, the CSS is
`.my-custom-class a {
        color: #ff3d7f !important;
      }`
but, in the new version 0.26.1, the CSS should be
`.my-custom-class span {
        color: #ff3d7f !important;
      }`

**Versions**

- `@angular/core`: 6.1.4
- `angular-calendar`: 0.26.1
- Browser name and version: Chrome 69.0

**Comment by mattlewis92** [comment]
Thanks for reporting! Would you like to [make a pull request](http://makeapullrequest.com) with the fix? The line to change in the source is [here](https://github.com/mattlewis92/angular-calendar/blob/master/src/app/demo-modules/custom-event-class/component.ts#L17)

**Comment by hugocaldeira** [comment]
Ok! I'm going to try. Never done a pull request before.

Thanks, Matt.
