### ISSUE TITLE
Angular Calaendar dayClicked is not getting triggered in mobile/ipad devices

### ISSUE THREAD

**Issue by deveshkrsingh** [mattlewis92/angular-calendar#753]
I have kept debugger at function which is getting called on angular calendar day click.It is getting called in web browser but not getting called on iphone/iPad view(in chrome).
 ```
<div [ngSwitch]="view">
              <mwl-calendar-month-view *ngSwitchCase="'month'" [viewDate]="viewDate" [events]="events" [refresh]="refresh" (dayClicked)="dayClicked($event.day)"
                (eventClicked)="handleEvent('Clicked', $event.event)" (beforeViewRender)="beforeMonthViewRender($event)">
              </mwl-calendar-month-view>

            </div>
```

```
dayClicked({ date, events }: { date: Date; events: CalendarEvent[] }): void {
    debugger;
   }
```

**Minimal reproduction of the problem with instructions**

**Screenshots**

**Versions**

- `@angular/core`:
- `angular-calendar`:
- Browser name and version:

**Comment by mattlewis92** [comment]
It works for me in chrome on ios on the demo site, it sounds like you might need to include [hammerjs](https://hammerjs.github.io/) for touch events to work properly.
