### ISSUE TITLE
Wrong inflection of month names in polish

### ISSUE THREAD

**Issue by jaruszewskiG** [mattlewis92/angular-calendar#757]
**Describe the bug**

The translation of months to polish doesn't seem to work properly. It changes the inflection of the word needlessly. I'm doing everything, just like in [this example](https://mattlewis92.github.io/angular-calendar/#/i18n)

For example:

"January" is translated to "stycznia" instead of "styczeń"
"February" is translated to "lutego" instead of "luty"
etc... all months have wrong inflection.

**Versions**

- `@angular/core`: 6.0.3
- `angular-calendar`: 0.25.2
- Browser name and version: 69.0.3497.100

**Comment by jaruszewskiG** [comment]
Hi, thanks for quick reply. Yes, only the months are wrong. I've changed 
`{{ viewDate | calendarDate:(view + 'ViewTitle'): locale }}` 
to 
`{{ viewDate | calendarDate:('day' + 'ViewTitle'): locale }}` 
and it looks exactly as you've written in your example: `sobota, stycznia 27, 2018`

**Comment by Shumatsu** [comment]
Month - Day - Year format isn't really used in Polish language. Day - Month - Year is the most used format.

**Comment by mattlewis92** [comment]
This should be fixed now in `0.26.2`, please let me know if I missed off any other places 😄
