### ISSUE TITLE
angular-calendar/date-adapters/date-fns module not found 

### ISSUE THREAD

**Issue by shajunr88** [mattlewis92/angular-calendar#761]
When installing this library in angular 5, it shows the error 'has no exported member DateAdapter' in line
import { CalendarModule, DateAdapter } from 'angular-calendar'; and Cannot find module 'angular-calendar/date-adapters/date-fns' in 
import { adapterFactory } from 'angular-calendar/date-adapters/date-fns';

**Comment by shajunr88** [comment]
When installing this library in angular 5, it shows the error 'has no exported member DateAdapter' in line
import { CalendarModule, DateAdapter } from 'angular-calendar'; and Cannot find module 'angular-calendar/date-adapters/date-fns' in
import { adapterFactory } from 'angular-calendar/date-adapters/date-fns';

**Comment by Assdi** [comment]
getting same issue :( in angular 5 .
