### ISSUE TITLE
date-adapters module not found

### ISSUE THREAD

**Issue by shajunr88** [mattlewis92/angular-calendar#762]
**Describe the bug**
I am using angular-calender version 0.24.1 in my angular 5.2 project by using command npm install --save angular-calendar@0.24.1 date-fns.But after installing,cannot find modules import { adapterFactory } from 'angular-calendar/date-adapters/date-fns';
and DateAdapter.I checked the nodemodules/angular-calender,but it does not contain the folder /date-adapters.

**Minimal reproduction of the problem with instructions**

**Screenshots**

**Versions**

- `@angular/core`:5.2
- `angular-calendar`:0.24.1
- Browser name and version:Mozilla

**Comment by mattlewis92** [comment]
That was a new API introduced in version `0.26.0`, you need to either upgrade to angular 6 and the latest version or check [the docs](https://github.com/mattlewis92/angular-calendar/tree/v0.24.1) for `0.24.1`. Hope that helps! 😄
