### ISSUE TITLE
Issue on main "Kitchen sink" demo

### ISSUE THREAD

**Issue by andrii-sokolskyi** [mattlewis92/angular-calendar#763]
**Describe the bug**
If you add several events starting almost at the same time they will overlap each other.
https://mattlewis92.github.io/angular-calendar/#/kitchen-sink

**Minimal reproduction of the problem with instructions**
1. add new event for current day starting at 02:00 AM
2. add new event for current day starting at 02:05 AM
3. add new event for current day starting at 02:10 AM

**Screenshots**
http://prntscr.com/l3marw

**Versions**

- `@angular/core`: Angular: 6.1.9
- Latest for Angular 6 (0.26.1)
- Chrome 69.0.34

**Comment by mattlewis92** [comment]
Thanks for reporting! This is now fixed in `0.26.3` 😄
