### ISSUE TITLE
i want to get the start date and end date after view date changed

### ISSUE THREAD

**Issue by fengybl** [mattlewis92/angular-calendar#770]
**Is your feature request related to a problem? Please describe**
how can i get a week start date and end date when the view changed?
now i use 'beforeViewRender' attribute,but i found the times of the trigger was not i want
![image](https://user-images.githubusercontent.com/18284232/46776267-6bcb8800-cd3d-11e8-872e-de43cc111206.png)
![image](https://user-images.githubusercontent.com/18284232/46776274-738b2c80-cd3d-11e8-817c-311c9f21d4f7.png)

**Describe the solution you'd like**
can u create a new output attribute?

**Describe your use case for implementing this feature**

**Additional context**

**Comment by mattlewis92** [comment]
The beforeViewRender output fires whenever the view is re-rendered, so when you re-assign the events inside the output it caused the infinite loop you're experiencing. You can work around this by storing the last period and checking it's changed. I put together a quick example of how to do this [here](https://stackblitz.com/edit/angular-qnccfb?file=demo/component.ts). Hope that helps! 😄

**Comment by MohammedYaseen** [comment]
@mattlewis92  Thanks a lot for the workaround, it helped me after spending a lot of time in order to solve the problem.
