### ISSUE TITLE
Slow when using lots of events

### ISSUE THREAD

**Issue by Worthy7** [mattlewis92/angular-calendar#772]
**Describe the bug**
Calendar change (next week/previous week) is slow when there are many events. Mouseover and scroll down the page also lags sometimes.

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/angular-djwqqo

**Versions**

- `@angular/core`: 6.2
- `angular-calendar`: v0.26.3
- Browser name and version: Chrome  69.0.3497.100

**Comment by mattlewis92** [comment]
If you remove the event editor at the bottom it gets [a lot faster](https://stackblitz.com/edit/angular-djwqqo-cj61sf?file=demo/template.html). I've already spent a lot of time optimising the calendar as much as I possibly can, but you're always going to get some lag when rendering 5000 DOM nodes to the page as the DOM is slow. My suggestion would be to implement some kind of local filtering / searching on the calendar to limit the amount of events visible, as a calendar with 5000 events on it isn't a particularly great UX.

**Comment by Worthy7** [comment]
Are they actually rendered even if they are not displayed? For example by
using ExcludeDays etc?

**Comment by Worthy7** [comment]
Never mind, going back in time to where there are no events is faster,
which means it is already probably optimized best it can be. Hmm.
