### ISSUE TITLE
Not able to integrate the Angular calendar in my project.

### ISSUE THREAD

**Issue by tmpathak** [mattlewis92/angular-calendar#776]
**Describe the bug**

I want to integrate the calendar control in my current project. I have added the files from the app/calendar-modules and calender.component and module files.

Have also installed the related dependencies. Find the snapshoot for the in detail description of the error.

Can't bind to 'view' since it isn't a known property of 'div'. ("<div class="col-md-4"> <div class="btn-group"> <div class="btn btn-primary" mwlCalendarPreviousView [ERROR ->][view]="view" [(viewDate)]="viewDate"> Previous </div> <div class="btn btn-outline-secondary" mwlCale"): ng:///SonarpulseCalendarModule/AppCalendarComponent.html@0:650
Can't bind to 'viewDate' since it isn't a known property of 'div'. ("l-md-4"> <div class="btn-group"> <div class="btn btn-primary" mwlCalendarPreviousView [view]="view" [ERROR ->][(viewDate)]="viewDate"> Previous </div> <div class="btn btn-outline-secondary" mwlCalendarToday [(vi"): ng:///SonarpulseCalendarModule/AppCalendarComponent.html@0:664
Can't bind to 'viewDate' since it isn't a known property of 'div'. ("w" [(viewDate)]="viewDate"> Previous </div> <div class="btn btn-outline-secondary" mwlCalendarToday [ERROR ->][(viewDate)]="viewDate"> Today </div> <div class="btn btn-primary" mwlCalendarNextView [view]="view" "): ng:///SonarpulseCalendarModule/AppCalendarComponent.html@0:761
Can't bind to 'view' since it isn't a known property of 'div'. ("alendarToday [(viewDate)]="viewDate"> Today </div> <div class="btn btn-primary" mwlCalendarNextView [ERROR ->][view]="view" [(viewDate)]="viewDate"> Next </div> </div> </div> <div class="col-md-4"> <h3>{{ viewDa"): ng:///SonarpulseCalendarModule/AppCalendarComponent.html@0:848
Can't bind to 'viewDate' since it isn't a known property of 'div'. ("(viewDate)]="viewDate"> Today </div> <div class="btn btn-primary" mwlCalendarNextView [view]="view" [ERROR ->][(viewDate)]="viewDate"> Next </div> </div> </div> <div class="col-md-4"> <h3>{{ viewDate | calendarD"): ng:///SonarpulseCalendarModule/AppCalendarComponent.html@0:862
The pipe 'calendarDate' could not be found ("View [view]="view" [(viewDate)]="viewDate"> Next </div> </div> </div> <div class="col-md-4"> <h3>{{ [ERROR ->]viewDate | calendarDate:(view + 'ViewTitle'):'en' }}</h3> </div> <div class="col-md-4"> <div class="b"): ng:///SonarpulseCalendarModule/AppCalendarComponent.html@0:943
    at syntaxError (compiler.es5.js?524d:1690)
    at TemplateParser.parse (compiler.es5.js?524d:12814)
    at JitCompiler._compileTemplate (compiler.es5.js?524d:26966)
    at eval (compiler.es5.js?524d:26886)
    at Set.forEach (<anonymous>)
    at JitCompiler._compileComponents (compiler.es5.js?524d:26886)
    at eval (compiler.es5.js?524d:26773)
    at Object.then (compiler.es5.js?524d:1679)
    at JitCompiler._compileModuleAndComponents (compiler.es5.js?524d:26772)
    at JitCompiler.compileModuleAsync (compiler.es5.js?524d:26701)

**Screenshots**

![image](https://user-images.githubusercontent.com/11422256/47075363-0d5d4880-d21a-11e8-93cf-ee0ebb4bd3be.png)

**Versions**

- `@angular/core`:
- `angular-calendar`: "angular-calendar": "^0.26.3",
- Browser name and version: Chrome

**Comment by tmpathak** [comment]
Resolved issue by follo

**Comment by cargallo** [comment]
So what was the solution?

**Comment by yy808** [comment]
So what was the solution?
