### ISSUE TITLE
Async (Kitchen Sink demo) - issue with daylight savings time

### ISSUE THREAD

**Issue by riyadali** [mattlewis92/angular-calendar#778]
**Describe the bug**

No movies displayed for a day when switching from daylight savings to standard time.  I am in New York and on Nov 4 we go back 1 hour.  No movies are displayed for any days after the switch over (from Nov 4 onwards). 

**Minimal reproduction of the problem with instructions**
The kitchen sink async demo shows the problem.  The issue is that the timezoneOffset calculations is based on "today" and is one hour off (UTC-4:00 instead of UTC - 5:00) for dates after the switch over.  This causes the "start" date for an event to be one hour off. So instead of the start date being midnight of the currently selected day, it is saved as 11:00PM of the previous day.  Therefore nothing is displayed for the current day (if the date is after the time changeover).  This bug can also been seen in the week view where all events after the time changeover (Nov 4 for NY) shows at the 11pm hour instead of the midnight slot.

This problem can be fixed by doing the timezone offset calculations dynamically based on the current date rather than having a fixed offset calculation using today's date.  The following are the changes required for a possible fix.

1) In fetchEvents() set the start date as follows
``` 
start: new Date(film.release_date + this.getOffset(this.vwDate))
```

2) Add the following code for the getOffset method
```getOffset(date: Date): string {
    var timezoneOffset = new Date(date.getTime()).getTimezoneOffset();
    /*const hoursOffset = String(Math.floor(Math.abs(timezoneOffset / 60))).padStart(
        2,
        '0'
      ); */
    var hoursOffset = String(Math.floor(Math.abs(timezoneOffset / 60))).length==1? 
      '0' + String(Math.floor(Math.abs(timezoneOffset / 60))) : 
      String(Math.floor(Math.abs(timezoneOffset / 60)));

    /*const minutesOffset = String(Math.abs(timezoneOffset % 60)).padEnd(2, '0')*/
    var minutesOffset = String(Math.abs(timezoneOffset % 60)).length==1? 
      '0' + String(Math.abs(timezoneOffset % 60)) : 
      String(Math.abs(timezoneOffset % 60));
    const direction = timezoneOffset > 0 ? '-' : '+';
    return `T00:00:00${direction}${hoursOffset}${minutesOffset}`;
  }
```

Please note that this code doesn't completely fix the problem.  Since the changeover occurs at 2:00am, on the day of the changeover (Nov 4 for NY) the time is off by an hour for this day only.  So instead of showing as 12 midnight, it is displayed in the 1am slot.  Not a big deal.  However, I think this will bite when we gain an hour in the spring time and then the event times for the day of the changeover would be 1 hour off and this may result in a start date of 11:00PM on the day prior to the changeover.  I think a more complete fix may be to pass a date to getOffset with the time set to midday (which would be after the changeover). 
 

**Screenshots**

**Versions**

- `@angular/core`:
- `angular-calendar`:
- Browser name and version:

**Comment by riyadali** [comment]
I am leaving this issue open since the solution does not work for all cases.  But, there is no urgency at all to find a fix.

**Comment by mattlewis92** [comment]
Thanks a lot of the detailed explanation, that made fixing this really easy! I've just pushed out a fix for this demo, let me know if that works for you 😄

**Comment by riyadali** [comment]
Thanks for the quick fix and really a nice job in putting these calendar
features together.  It works.  I guess you are changing other things as
well because it displays a bit differently for the week and day views.
Instead of listing the movies in the 12:00 midnight time slot for each day,
a block is shown before the hourly schedule with all of the movies for that
day -- see attached screenshot

Riyad

**Comment by mattlewis92** [comment]
Yeah I realised it kind of made no sense to display them on midnight as they're really all day events.
