### ISSUE TITLE
Month and week view strange behaviour after Angular 7 upgrade

### ISSUE THREAD

**Issue by Herb-sh** [mattlewis92/angular-calendar#780]
After an angular upgrade to 7. I noticed some issues with WeekView and MonthView.
I have attached some image links, hope they are of help.

Week View in angular 6.1
https://prnt.sc/l8wzwu

Week View after angular 7 upgrade
https://prnt.sc/l8wyxj  (Notice the hourly timeline has shown out of nowhere)

Month View in angular 6.1
https://prnt.sc/l8x084

Month View after angular 7 upgrade
https://prnt.sc/l8x0l1

In `mwl-calendar-week-view` for instance I noticed that `cal-events-row` are not rendered anymore because `view.allDayEventRows` is empty.

I could not find errors of any kind and was wondering if you have any idea
on what may cause this strange behaviour.

Thank you for your time!

Cheers,
Herbi

**Comment by mattlewis92** [comment]
Sorry to hear that you're having issues, angular 7 doesn't really have any breaking changes or anything that should affect this, please can you make a minimal runnable repro that shows your issue via stackblitz or similar. You can use this as a starter: https://stackblitz.com/edit/angular-gbwqze?file=demo/component.ts Thanks! 😄

**Comment by Herb-sh** [comment]
I realised that these Issues came from 0.26 upgrade and not angular upgrade. I realised that  particular version had some breaking issues which I have to adjust. Therefore I am closing this ticket.

**Comment by odedshr** [comment]
I'm having a similar issue with having allDayEventRows.length===0,
I tried to reverse-engineer where it's been filled and by what criteria (anything but `allDay:true`?) but couldn't find what. should mention that start and end time are midnights on with 24hours apart.
