### ISSUE TITLE
Multiple events overlap in Week view

### ISSUE THREAD

**Issue by Seb69** [mattlewis92/angular-calendar#784]
**Describe the bug**

In week view, event does not display properly. 
First event takes half width instead of 1/3. 

**Minimal reproduction of the problem with instructions**

https://stackblitz.com/edit/angular-sykqgb?embed=1&file=demo/component.ts

**Screenshots**

![image](https://user-images.githubusercontent.com/14105342/47558074-8d6a6900-d912-11e8-990e-bfee0b11e42f.png)

**Versions**

- `@angular/core`: 6.1.8
- `angular-calendar`: 0.26.3

**Comment by mattlewis92** [comment]
Thanks for reporting! Should be fixed now in `0.26.4`
