### ISSUE TITLE
Calendar Text Translation

### ISSUE THREAD

**Issue by felipefsv** [mattlewis92/angular-calendar#786]
Hi !

Is it possible to change the language? I've successfully downloaded this component and it works good.

**Is your feature request related to a problem? Please describe**

**Describe the solution you'd like**

**Describe your use case for implementing this feature**

**Additional context**

**Comment by mattlewis92** [comment]
Sure thing! 😄  You can check the i18n demo for how to do this: https://mattlewis92.github.io/angular-calendar/#/i18n
