### ISSUE TITLE
The precision attribute in wl-calendar-week-view component is not supported anymore.

### ISSUE THREAD

**Issue by yginieys** [mattlewis92/angular-calendar#788]
**Describe the bug**

The "minutes" value for the "precision" attribute of the &lt;wl-calendar-week-view&gt; component does not seem to have any effect.

**Minimal reproduction of the problem with instructions**
Open the "Week view minute precision" demo page at https://mattlewis92.github.io/angular-calendar/#/week-view-minute-precision
The display is not what it was used to be in previous version (see attached screenshot).

On stackblitz, open https://angular-igfppt.stackblitz.io and edit "template.html", change "precision" attribute from "minutes" to "days" and the other way round. The view stays the same.

**Screenshots**
Previous version display was : 
![weekviewminuteprecision](https://user-images.githubusercontent.com/1614646/47719462-8d88a280-dc4b-11e8-95b3-4f7d2a0162c3.JPG)

**Versions**

- `@angular/core`: 6.1.10
- `angular-calendar`:  0.26.3
- Browser name and version: Chrome  69.0.3497.100

**Comment by mattlewis92** [comment]
Ah, looks like I need to update the demo for that, you need to mark events as `allDay` to get them to appear at the top now: https://stackblitz.com/edit/angular-f8aysk?file=demo/component.ts

**Comment by yginieys** [comment]
Thanks for your help. It solves our issue.
