### ISSUE TITLE
Tooltip delay

### ISSUE THREAD

**Issue by Jelle1** [mattlewis92/angular-calendar#790]
**Is your feature request related to a problem? Please describe**

Is it possible to add a delay before showing or hiding the tooltip for a calendar event?

**Describe the solution you'd like**

For example: https://material.angular.io/components/tooltip/overview#show-and-hide-delays

**Describe your use case for implementing this feature**

To avoid the flicker of tooltips when mousing over a calendar full of events.

**Additional context**

**Comment by mattlewis92** [comment]
There's currently no support for this but I would happily [accept a PR](http://makeapullrequest.com) to add it. The source of the tooltip directive is [here](https://github.com/mattlewis92/angular-calendar/blob/master/projects/angular-calendar/src/modules/common/calendar-tooltip.directive.ts) and then you would need to pass through the new `tooltipDelay` option down through the day / week / month components like [this](https://github.com/mattlewis92/angular-calendar/blob/master/projects/angular-calendar/src/modules/month/calendar-month-view.component.ts#L74). Let me know if you need any more info.

**Comment by mattlewis92** [comment]
Thanks to the work of @mikebaum this is now possible in the latest beta 🎉 

```
npm i angular-calendar@next
```

and then just pass `[tooltipDelay]="200"` in your month, week or day components 😄

**Comment by mattlewis92** [comment]
Added in `0.27`! 🎉

**Comment by fzs1994** [comment]
How to add hide delay?
