### ISSUE TITLE
Change type of MonthViewDay#badgeTotal to number or string

### ISSUE THREAD

**Issue by pherklotz** [mattlewis92/angular-calendar#792]
**Is your feature request related to a problem? Please describe**

I want to display not only a number but also an additional label in the day badge.

Example: 
Now: it shows only a number like "1"
Wish: it shows: "1 Appointment" 

**Describe the solution you'd like**

Change the type of MonthViewDay#badgeTotal to "number | string". This solution should provide downward compatibility. The badge will work with additional text (see screenshot below).

**Describe your use case for implementing this feature**

With this feature I didnt have to mess arround with CSS after-pseudo-elements to add an additional Label to my badge.

**Additional context**

Example of the outcome:
![image](https://user-images.githubusercontent.com/1645312/47849981-ebe08d00-ddd3-11e8-9ddb-865970bce13b.png)

Please dont hesitate to contact me for additional information.

**Comment by mattlewis92** [comment]
I'd rather avoid modifying the interface as the api does always return a number and it's confusing otherwise. You can workaround typescript by either extending the interface yourself:

```
interface CustomMonthViewDay extends MonthViewDay {
  badgeTotal: number | string;
}
```

Or just casting to any:
```
(day as any) = `${daybadgeTotal} Termin`;
```

Hope that helps! 😄
