### ISSUE TITLE
Grid in Week View is missing - angular 5

### ISSUE THREAD

**Issue by mojo2405** [mattlewis92/angular-calendar#794]
**Describe the bug**
Using angular 5, only in Week view, the grid is missing (though I can see the events)
Day view and Month view are fine.

**Minimal reproduction of the problem with instructions**
Just go to week view

**Screenshots**
![image](https://user-images.githubusercontent.com/19651791/47962555-34dc4f80-e027-11e8-950d-adb4633b155e.png)

**Versions**

- `@angular/core`:5.2.5
- `angular-calendar`:0.24.1
- Browser name and version:chrome / firefox

**Comment by mattlewis92** [comment]
This was only added in [`0.26`](https://github.com/mattlewis92/angular-calendar/blob/master/CHANGELOG.md#0260-2018-09-03) you'll need to upgrade.

**Comment by mojo2405** [comment]
@mattlewis92 That means that I have to update to angular 6  ?

**Comment by mattlewis92** [comment]
Yup, but it shouldn't take more than a few minute via [`ng update`](https://angular.io/cli/update)
