### ISSUE TITLE
Drop multiple items into an event

### ISSUE THREAD

**Issue by IamSef** [mattlewis92/angular-calendar#795]
**Is your feature request related to a problem? Please describe**

**Describe the solution you'd like**

**Describe your use case for implementing this feature**

I need to add more info into an event by dropping an item into it. For example I created a meeting event and I want to drag participants into that event from an external card. I need their profile pic displayed after I drag it. So basically an event that can handle drag and drop.

**Comment by mattlewis92** [comment]
Hi there, so sorry about the late reply! This is actually possible with the current API, I'd be more than happy to put together a demo for you to show how to do it, if it's still something you need, please just write a reply below and I'll get to work on it. Thanks! 😄
