### ISSUE TITLE
DateAdapter Conflict

### ISSUE THREAD

**Issue by Acraciel** [mattlewis92/angular-calendar#797]
**Describe the bug**

Conflict with the name of the class "DateAdapter", occurs when having DateAdapter configured of @ angular / material, because the classes are called equal and their use is necessary when you need to have a custom DateAdapter configured for the Datepicker of Angular Material

**Minimal reproduction of the problem with instructions**
 Install [Angular Material](https://material.angular.io/guide/getting-started)
When u try to add in app.module.ts you have the conflict.
`// Material Design`
`import { DateAdapter } from '@angular/material'; `
`import { CustomDateAdapter } from './custom-date.adapter'; `
`//AngularCalendar`
`import { CalendarModule, DateAdapter } from 'angular-calendar';`
`import { adapterFactory } from 'angular-calendar/date-adapters/date-fns';`

**Screenshots**

Does not apply

**Versions**

- `@angular/core`: "^7.0.2"
- `angular-calendar`: "^0.26.4"
- Browser name and version: "Chrome Versión 70.0.3538.77"

**Comment by mattlewis92** [comment]
You can workaround this by renaming the import:
```
import { DateAdapter as AngularCalendarDateAdapter } from 'angular-calendar';
```

**Comment by haiddablitz** [comment]
> You can workaround this by renaming the import:
> 
> ```
> import { DateAdapter as AngularCalendarDateAdapter } from 'angular-calendar';
> ```

Can confirm. This works :-)
Had the same problem a few minutes ago.
