### ISSUE TITLE
Time format not compatible with "A" parameter

### ISSUE THREAD

**Issue by IterationCorp** [mattlewis92/angular-calendar#800]
**Describe the bug**
I implemented your Customise date formats such as explained here : https://mattlewis92.github.io/angular-calendar/#/customise-date-formats

It work very well with 'HH:mm'.

```
  public dayViewHour({ date, locale }: DateFormatterParams): string {
    return new DatePipe(locale).transform(date, 'HH:mm', locale);
  }
```
But if we enter : "h:mm A" or "g:i A" what is a standard time format for 12:00 AM/PM it doesn't work we got a "A" following the time.

**Minimal reproduction of the problem with instructions**

```
  public dayViewHour({ date, locale }: DateFormatterParams): string {
    return new DatePipe(locale).transform(date, 'h:mm A', locale);
  }
  public dayViewHour({ date, locale }: DateFormatterParams): string {
    return new DatePipe(locale).transform(date, 'g:i A', locale);
  }
```

**Screenshots**

![image](https://user-images.githubusercontent.com/6637470/48287382-03b9b000-e469-11e8-8b1c-549eba04a7ad.png)

**Versions**

- `@angular/core`: 7.0.3
- `angular-calendar`: 0.26.3
- Browser name and version: Chrome 70

**Comment by mattlewis92** [comment]
Please see the docs for the angular [date pipe](https://angular.io/api/common/DatePipe), I think you want `a` or `aa`
