### ISSUE TITLE
Hours segment repeats twice on the daylight saving day.

### ISSUE THREAD

**Issue by daneshmandi** [mattlewis92/angular-calendar#801]
**Describe the bug**

Hours segment repeats twice for the hour "1 AM" on the daylight saving day for the day view and week view.

**Minimal reproduction of the problem with instructions**

For my case daylight saving day is Nov. 4th, So when I check this day on calendar I see the "1 AM" has repeated twice on this day for both day view and week view. As I checked the Demo at https://mattlewis92.github.io/angular-calendar/#/kitchen-sink act the same, too. 

**Screenshots**
[https://imgur.com/81XomWP](https://imgur.com/81XomWP)

**Versions**

- `@angular/core`: 7.0.2
- `angular-calendar`: 0.26.4
- Browser name and version: Chrome Version 70.0.3538.77 (Official Build) (64-bit)

**Comment by mattlewis92** [comment]
Unfortunately date-fns doesn't have a UTC mode (yet) so the only way to workaround this is by using moment and setting the timezone to UTC. See https://github.com/mattlewis92/angular-calendar/issues/477#issuecomment-418202991 for an example.
