### ISSUE TITLE
Colouring issues

### ISSUE THREAD

**Issue by yannickboy15** [mattlewis92/angular-calendar#804]
**Describe the bug**

I've got a dark themed website, but the calendar stays white. Tried modifying it myself with CSS, but the normal month overview works out fine. The week and day overview continue to stay white even though the other things become the dark themed colours.

**Minimal reproduction of the problem with instructions**

Get a custom themed website. It won't colour along.

**Screenshots**

https://i.gyazo.com/1fe1710755195c69bf47566d75b9cf4f.png

Week:
https://i.gyazo.com/b59c1d0f11500d19cb6eb59bca472555.png

Day:
https://i.gyazo.com/4f5000a25e012400b4983df125b9986f.png

**Versions**

- `@angular/core`: As supplied by the readme
- `angular-calendar`: As supplied by the readme
- Browser name and version: Chrome

**Comment by mattlewis92** [comment]
It sounds like your CSS is getting overridden by the calendars, if you use the browser dev tools to inspect the styles you'll see which rules are being overridden and can copy the selector to make it more specific, or as a quick hack use `!important` on your styles.
