### ISSUE TITLE
Is there a way to display Holidays? Is there some sample code anywhere that shows this? 

### ISSUE THREAD

**Issue by bostondevin** [mattlewis92/angular-calendar#809]
**Is your feature request related to a problem? Please describe**

**Describe the solution you'd like**

**Describe your use case for implementing this feature**

**Additional context**

**Comment by lukekoko** [comment]
You can display holidays as an event. You can get the holiday dates from a holiday library.

**Comment by JaxonWright** [comment]
I do this by having all-day events with a special type in the meta declaring it as a holiday. How you get these holidays is really up to you to figure out, however.

**Comment by pavlovmilen** [comment]
Alternativelly you can display the holidays alongside your events - I have achived this by using 
beforeWeekViewRender to paint the calendar segments that are within my holiday times in red. 
![image](https://user-images.githubusercontent.com/20510797/72428383-76b56980-3785-11ea-9717-7f5fbf20ab86.png)
Sample code here https://mattlewis92.github.io/angular-calendar/#/before-view-render

**Comment by mattlewis92** [comment]
Just added a [new demo](https://angular-calendar.com/#/public-holidays) showing how you can use [holidayapi.com](https://holidayapi.com/) to fetch holidays, hope that helps! 😄

**Comment by Vliesie** [comment]
Cant seem to Track down the Demo Mentioned Above Has the URL changed at all?

**Comment by mattlewis92** [comment]
Ah, the domain changed, give this a go! https://mattlewis92.github.io/angular-calendar/#/public-holidays
