### ISSUE TITLE
Pass custom data down to event

### ISSUE THREAD

**Issue by mlindhout** [mattlewis92/angular-calendar#814]
Hi, I have an application with multiple calendars besides each other, one for each user.

I have a custom mwl-calendar-day-view-hour-segment template in which I need to access some 'calendar level' data to make an API call once clicked on the segment. For example, having this template:
```
<td *ngFor="let agenda of agendas" width="{{90/agendas.length}}">
      <mwl-calendar-day-view 
         [events]="agenda.appointments"
         [hourSegmentTemplate]="myCustomTemplate"
         [otherProps]="here">
      </mwl-calendar-day-view>
</td>
```
So in the 'myCustomTemplate' I need to access the agenda variable. Is that possible? As far as I can see, only segment, locale and segmentHeight are passed down to the template.

I'd like to pass down custom variables to the calendar templates, like this

```
<td *ngFor="let agenda of agendas" width="{{90/agendas.length}}">
      <mwl-calendar-day-view 
         [events]="agenda.appointments"
         [customData]="{agenda: agenda}"
         [hourSegmentTemplate]="myCustomTemplate"
         [otherProps]="here">
      </mwl-calendar-day-view>
</td>
```

**Additional context**
No

**Comment by mattlewis92** [comment]
Any `ng-template` has access to the parents scope as well so you can access any variable there, so you should just be able to use the `agendas` variable in the template already 😄

**Comment by mlindhout** [comment]
Yes, I can access the agendas (plural) but not the single agenda... what am I missing?

**Comment by mattlewis92** [comment]
You need to move your `ng-template` inside the ngFor so it has access to the ngFor's scope: https://stackblitz.com/edit/angular-3cwisj?file=src/app/app.component.html

**Comment by mlindhout** [comment]
Shame on me :-( Thanx!
