### ISSUE TITLE
Resize event in Day view scheduler

### ISSUE THREAD

**Issue by Inetsis** [mattlewis92/angular-calendar#817]
**Describe the bug**

Hello

On the "Day view scheduler" live demo, we can't resize event however event is marked as resizable
We have the good cursor but we can't drag bottom
I have this usecase so how can i do this ?

Thx

**Minimal reproduction of the problem with instructions**

On live demo
https://mattlewis92.github.io/angular-calendar/#/day-view-scheduler

**Screenshots**

n/a

**Versions**

latest

**Comment by Inetsis** [comment]
Did you look at this bug ?
Please

**Comment by Inetsis** [comment]
It's ok with new version 0.26.6
Thanks a lot

**Comment by hugocaldeira** [comment]
Hi,
I'm using the version 0.26.6 but the problem persists.
@Inetsis , can you tell how you fixed it?

Hugo.

**Comment by Inetsis** [comment]
Hello @hugocaldeira 

You must merge your code with changed made by the creator
For exemple, in day-view-scheduler.component.html there are breaking changes on [resizeSnapGrid], [validateResize] or dragPointerDown

Good luck

**Comment by mattlewis92** [comment]
Sorry about that, I've just fixed up the demo now to work with resizing 😄
