### ISSUE TITLE
DayView event title has drag&drop container referenced to it

### ISSUE THREAD

**Issue by ungureanuu** [mattlewis92/angular-calendar#818]
<img width="1680" alt="screen shot 2018-11-26 at 12 36 28" src="https://user-images.githubusercontent.com/17099777/49009044-2097f800-f178-11e8-9ecf-1a484127c5e1.png"> 
Drag a tool to this reference of the event is the workflow that I am looking for. Can u please guide me to a solution?

**Is your feature request related to a problem? Please describe**
I need to add tools to an event instance using drag/drop.

**Describe the solution you'd like**
The solution would be to implement a new property to events (similar to actions). For examples "tools"and this to represent a container div where you can drag/drop the tool

**Describe your use case for implementing this feature**
The use case is when someone needs to personalise an event with extended tools

**Comment by mattlewis92** [comment]
Hi there, so sorry about the late reply! This is actually possible with the current API, I'd be more than happy to put together a demo for you to show how to do it, if it's still something you need, please just write a reply below and I'll get to work on it. Thanks! 😄
