### ISSUE TITLE
Prohibit drop of event on hour segment

### ISSUE THREAD

**Issue by mlindhout** [mattlewis92/angular-calendar#819]
I can't prohibit the drop of events on certain segments in the calendar-day-view.

I'd like to have the possibility of a visual indication to prohibit the drop of an event, because in my case not all slots are available. There is a `validateDrag` method, but it's internal. 

Not all hour segments are available in our case.

**Additional context**

**Comment by mattlewis92** [comment]
Hi there, so sorry about the late reply! This is actually possible with the current API, I'd be more than happy to put together a demo for you to show how to do it, if it's still something you need, please just write a reply below and I'll get to work on it. Thanks! 😄
