### ISSUE TITLE
How can I add a routerlink when I click a day in recurring events

### ISSUE THREAD

**Issue by ReneI** [mattlewis92/angular-calendar#823]
**Describe the bug**
when a click a day I would like to display a window below that says add your report this week and a routerlink
https://mattlewis92.github.io/angular-calendar/#/recurring-events
**Versions**

    @angular/core: 6.1.10
    angular-calendar: 0.26.4
    Browser name and version: Google Chrome 70

**Comment by mattlewis92** [comment]
Hi there, so sorry about the late reply! This is actually possible with the current API, I'd be more than happy to put together a demo for you to show how to do it, if it's still something you need, please just write a reply below and I'll get to work on it. Thanks! 😄
