### ISSUE TITLE
Would like to have feature that could change the background in the weeksview for the hoursegments in a specific time range 

### ISSUE THREAD

**Issue by Joelastrand** [mattlewis92/angular-calendar#825]
**Is your feature request related to a problem? Please describe**
Hey!
I am using the week view and going to use two different type av times, one time is available time for the user and the other time is booked time. So for instance, the user has available time between 8AM and 4 PM, this time range would displayed in the week view by changing the background color in the hoursegment. When the user has an event 12PM-1PM ( in my case I refer it to booked time ) the event should be displayed at this time as usual. The problem today is if you create two events on the same time both get decreased.

**Describe the solution you'd like**

I would like have the feature such as event works today, you set the time interval, which type it is and a color but the instead of creating an event it changing the background color for the time of interval .

**Describe your use case for implementing this feature**

Is this already possible today? I know I can change the whole week view background through the calendar-week-view-hour-segment.component.ts but I don't know how to change the the background in a specific time range.

**Additional context**

Thanks in advance!
Regards
Joel

**Comment by mattlewis92** [comment]
Hi there, so sorry about the late reply! This is actually possible with the current API, I'd be more than happy to put together a demo for you to show how to do it, if it's still something you need, please just write a reply below and I'll get to work on it. Thanks! 😄

**Comment by Joelastrand** [comment]
@mattlewis92  No worries, understand if you have things to do, awesome work with the calendar btw:) 
Sounds perfect if there is already a API for this, please do a demo if you can!:)  Have you another demo that showing a way to have several calendars next to each other? :)

**Comment by Joelastrand** [comment]
@mattlewis92 Hey again! Did you have the time to make the demo and in that case where can I find it?:) Regards, 
Joel

**Comment by mattlewis92** [comment]
Sorry I'm drowning in issues at the moment and don't have a lot of spare time, what you want is to use the [beforeViewRender output](https://mattlewis92.github.io/angular-calendar/docs/components/CalendarWeekViewComponent.html#beforeViewRender) on the week view to add a custom CSS class to style up the time range you want. If you import `CalendarWeekViewBeforeRenderEvent` from `angular-calendar` it will give you the shape of the `$event` object. There's an example of how to do it for the month view [here](https://mattlewis92.github.io/angular-calendar/#/before-view-render). I hope that gives you enough pointers 😄

**Comment by mattlewis92** [comment]
Finally had some time to loop back to this, I've updated the demo here to show how to do it, thanks for your patience! 😄 https://mattlewis92.github.io/angular-calendar/#/before-view-render
