### ISSUE TITLE
Fixed header with scrollable body in week view component

### ISSUE THREAD

**Issue by meiuqer** [mattlewis92/angular-calendar#828]
**Is your feature request related to a problem? Please describe**

When scrolling the scheduler in week view it would be recommended that the header stays on top so that you can still read the date and day of week.

**Describe the solution you'd like**

Scrolling through week view should only scroll the body, not the header.

**Describe your use case for implementing this feature**

Maybe add an input, so that the user can choose between fixed header or not?

**Additional context**

Google Calendar uses this behavior as I desribed.

**Comment by sandord** [comment]
It would also be very nice if a default vertical offset could be configured. For example, this would cause the view start at 5:00 AM but still allow for scrolling up all the way to 12:00 AM.

This would help keeping the part of the calendar where most events are in view for applications that have that kind of data.

**Comment by IamSef** [comment]
Agree, this will be very useful.

**Comment by IamSef** [comment]
> It would also be very nice if a default vertical offset could be configured. For example, this would cause the view start at 5:00 AM but still allow for scrolling up all the way to 12:00 AM.
> 
> This would help keeping the part of the calendar where most events are in view for applications that have that kind of data.

Were you able to figure how to do this?

**Comment by sandord** [comment]
Honestly, I haven't tried.

**Comment by mattlewis92** [comment]
Apologies on the late reply on this, you can actually add a few lines of CSS to make the body scrollable, I intentionally don't bake anything in as every app is different, maybe you want the calendar to fill the height, or be a fixed height, or maybe you want the all day events to be scrollable and the time events to be as well. 

I put together a demo showing you how you can use CSS to do this, hope that helps! 😄 https://stackblitz.com/edit/angular-w4urnk?file=index.html

**Comment by meiuqer** [comment]
Thanks for the effort! Only one problem, and this is where i also struggled: I have a calendar that doesn't fit the browser on 1920*1080 resolution so I need scrollbars, but screens with a height of > 1080 it fits completely so no scrollbars. 

With your solution the header and the calendar body will be offset if there is no scrollbar. I fixed this with javascript, but I wonder if there is a CSS solution for this?

**Comment by mattlewis92** [comment]
I'm not too sure, my css skills are pretty basic

**Comment by PBhanwal** [comment]
I got the scroll with above CSS but it's from 12 AM. I wanna have a default scroll value to 9 am and the before time should be scrollable. Any idea how to do that?

**Comment by FrankL-git** [comment]
Thanks so much! Your calendar is a masterpiece!

**Comment by AbiramVJ** [comment]
.calendar-container {
  position: relative;
  height: 100vh;
  overflow: hidden;
}

.cal-day-headers {
  position: sticky;
  top: 0;
  z-index: 10;
  background-color: white; 
}

.calendar-content {
  overflow-y: auto;
  height: calc(100vh - 40px); 
}
you can use this css

**Comment by adrielstar** [comment]
Is there a way to make it scroll also by resizing from an event? 

Right now with this fix by resizing of an event when it reach bottom of the container you need to scroll manually to continuous the resizing of the event.

**Comment by Melikyan005** [comment]
`.cal-week-view {
  position: relative;
  max-height: 600px;
  overflow-y: scroll;
}

.cal-day-headers {
  position: sticky;
  top: 0;
  right: 0;
  z-index: 2;
  background-color: white;
  width: 100%;
  min-height: 35px;
}`
