### ISSUE TITLE
If number of events are more than specific number then they should not appear in same line instead should wrap in next line.

### ISSUE THREAD

**Issue by harsimerkaur** [mattlewis92/angular-calendar#830]
Hi @mattlewis92,
 
Greetings!!

I have a requirement to show events in a certain way on calendar view. Please suggest solution for the same.

Requirement:
Calendar Day view:
In case I have more than certain number (say 5) events for one particular instant of time (5:00 PM) then they appear in same line.  As per my requirement, it should wrap up in the next line.

Calendar week view:
Similarly in week view if number of events are more than 2 or 3 for particular hour, they start  overlapping/compressing into single block. My requiremement is that they appear in the next line and hour block should keep expanding.

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/angular-vacxfb?file=demo%2Fcomponent.ts
**Screenshots**
<img width="961" alt="events-day-view" src="https://user-images.githubusercontent.com/38556673/49726527-418e3c00-fc94-11e8-8313-93f69c8e8816.PNG">
<img width="958" alt="event-week-view" src="https://user-images.githubusercontent.com/38556673/49726545-49e67700-fc94-11e8-9d25-6695255f77f0.PNG">
<img width="961" alt="events-day-view" src="https://user-images.githubusercontent.com/38556673/49726616-700c1700-fc94-11e8-83cd-c64ac2b47970.PNG">

**Versions**

- `Angular 7`:
- `angular-calendar 0.26.4`:
- Google chrome:

**Comment by mattlewis92** [comment]
Hi there, so sorry about the late reply! This is actually possible with the current API, I'd be more than happy to put together a demo for you to show how to do it, if it's still something you need, please just write a reply below and I'll get to work on it. Thanks! 😄

**Comment by gggiiia** [comment]
need that! any exemple of how is it possible?
