### ISSUE TITLE
Wrong width size when events overlap

### ISSUE THREAD

**Issue by Seb69** [mattlewis92/angular-calendar#833]
**Describe the bug**

Events does not display properly or can be space optimized.

**Minimal reproduction of the problem with instructions**

https://stackblitz.com/edit/angular-sykqgb

**Screenshots**

![image](https://user-images.githubusercontent.com/14105342/49950316-e066a280-fef7-11e8-861e-2891783f1d3c.png)

Would be nice to have A and B take the 66% width. 

**Versions**

- `@angular/core`: 6.1.10
- `angular-calendar`: 0.26.4

**Comment by polaroi8d** [comment]
I have similar issue, there is any workaround? 

![image](https://user-images.githubusercontent.com/9247788/52535504-9101ee80-2d4f-11e9-8e20-bbac0b5c4efe.png)

**Comment by mattlewis92** [comment]
Fixed in `0.27.5`! Thanks for reporting 😄 

> I have similar issue, there is any workaround?
> 
> ![image](https://user-images.githubusercontent.com/9247788/52535504-9101ee80-2d4f-11e9-8e20-bbac0b5c4efe.png)

Looks like a different issue (maybe styling related?). Please make a runnable stackblitz that reproduces the problem if it's still an issue. Thanks!

**Comment by polaroi8d** [comment]
Thanks @mattlewis92 i will check it
