### ISSUE TITLE
Get the position of current cell

### ISSUE THREAD

**Issue by IamSef** [mattlewis92/angular-calendar#846]
**Is your feature request related to a problem? Please describe**

I have a requirement where I need to display 8AM by default but would still need to scroll earlier dates. If I set the start time to 8AM, earlier dates cannot be seen on the calendar. As per my requirement I would still need those time available on the calendar but the default is 8AM.

**Describe the solution you'd like**

An API that can be used to access cell position.

**Describe your use case for implementing this feature**

**Additional context**

**Comment by mattlewis92** [comment]
Hi there, so sorry about the late reply! This is actually possible with the current API, I'd be more than happy to put together a demo for you to show how to do it, if it's still something you need, please just write a reply below and I'll get to work on it. Thanks! 😄

**Comment by IamSef** [comment]
Yes, I'll appreciate it if you can send me a demo how to use it. Plunkr will do :)

Thank you!

**Comment by mattlewis92** [comment]
Each segment is 30px high, and by default there are 2 segments per hour, so to calculate where to scroll to, it's just hours * 60. I put together a demo for you showing how to do this, hope that helps! 😄 https://stackblitz.com/edit/angular-w4urnk-yhbyh5?file=demo%2Fcomponent.ts
