### ISSUE TITLE
day view clicked

### ISSUE THREAD

**Issue by CisManar** [mattlewis92/angular-calendar#850]
hello

i want to make event click **(eventClicked)="eventClicked($event)"**
on container box instead of event title in day view
how i can do it ??
note: for version 0.24.1

thanks

**Describe the bug**

**Minimal reproduction of the problem with instructions**

**Screenshots**

**Versions**

- `@angular/core`:
- `angular-calendar`:
- Browser name and version:

**Comment by mattlewis92** [comment]
You want the `hourSegmentClicked` output: https://mattlewis92.github.io/angular-calendar/docs/components/CalendarWeekViewComponent.html#hourSegmentClicked
