### ISSUE TITLE
drag and drop to different month

### ISSUE THREAD

**Issue by andreisrob** [mattlewis92/angular-calendar#852]
**Is your feature request related to a problem? Please describe**

Cannot drag an event to a different month, other than the few days at the beginning or the end of the current month (and only when the month begins/ends midweek)

**Describe the solution you'd like**

See below

**Describe your use case for implementing this feature**

Allow the user to move events from one month to another month using drag and drop

**Additional context**

**Comment by andreisrob** [comment]
I would like to add that I am building a schedule application for a mid-size, fast-growing company, and working with your calendar has been a great experience.

I have an idea, but I will implement and test first.

Thanks for all your work.

**Comment by andreisrob** [comment]
Here is my solution:

I added a button to my page that toggles between single-month and multi-month views.  When the user chooses multi-view, I generate an array of `viewDate` values, and `ngFor` to create my calendars.  I had to make my own `next` and `previous` directives to navigate while viewing multiple calendars at once, and some tinkering with the css, but that's it. 

Although each calendar is agnostic to the others, I am feeding the same events array to all of them, so I can drag from one month to the next and both update appropriately.

What do you think?

**Comment by mattlewis92** [comment]
This is exactly how I would have implemented it if this were a requirement in my app, I always intended these components here to be lower level building blocks so you can build cool customisations like this on top 😄
