### ISSUE TITLE
Override Link In Details

### ISSUE THREAD

**Issue by pconley** [mattlewis92/angular-calendar#86]
First of all... thanks, very useful component.  When in month view and I click on a day it opens the dark section that shows all the events for that day.  The title of the event is a link... and examining the source code it has an href of "javascript:;".  Is there a way to override that href so that I can use it to jump to my event details?  I know I can do that with the associated "actions and icons", but the link seems to obvious thing for users to try first.  Your thoughts?

**Comment by mattlewis92** [comment]
You can use the `eventClicked` output to do this: https://mattlewis92.github.io/angular-calendar/docs/classes/calendarmonthviewcomponent.html#eventclicked

Hope that helps 😄

**Comment by francisrod01** [comment]
> You can use the `eventClicked` output to do this: https://mattlewis92.github.io/angular-calendar/docs/classes/calendarmonthviewcomponent.html#eventclicked
> 
> Hope that helps

The current link for that is:
https://angular-calendar.com/docs/components/CalendarMonthViewComponent.html#eventClicked
