### ISSUE TITLE
bug while using custom template for openDayEventsTemplate

### ISSUE THREAD

**Issue by razeniraj** [mattlewis92/angular-calendar#860]
**Describe the bug**

the events are being populated in all the rows while using custom template.

**Minimal reproduction of the problem with instructions**

<mwl-calendar-month-view *ngSwitchCase="CalendarView.Month" [openDayEventsTemplate]="customOpenDayEventsTemplate" [viewDate]="viewDate" [events]="currentEvents" [refresh]="refresh" [activeDayIsOpen]="activeDayIsOpen" (dayClicked)="dayClicked($event.day)"
            (eventClicked)="handleEvent('Clicked', $event.event)" (eventTimesChanged)="eventTimesChanged($event)">
        </mwl-calendar-month-view>

<ng-template #customOpenDayEventsTemplate let-events="events" let-eventClicked="eventClicked" let-isOpen="activeDayIsOpen">
        <ion-item-group [@collapse]>
            <div *ngFor="let event of events;  trackBy:trackByEventId;" [ngClass]="event?.cssClass" mwlDraggable [dropData]="{event: event}" [dragAxis]="{x: event.draggable, y: event.draggable}">
test
</div>
        </ion-item-group>

    </ng-template>

**Screenshots**
![50655440_590880728022222_4968931150316699648_n](https://user-images.githubusercontent.com/28684522/51535571-f52c4380-1e70-11e9-972c-c5e1691279d5.jpg)

**Versions**

- `@angular/core`: 6.0.9
- `angular-calendar`: ^0.26.4
- Browser name and version:

**Comment by mattlewis92** [comment]
Please can you add a runnable stackblitz that reproduces your problem? You can fork a starter from any of the demos pages. Thanks! 😄

**Comment by razeniraj** [comment]
please check out the stackblitz ([https://stackblitz.com/edit/angular-jqsjdc](https://stackblitz.com/edit/angular-jqsjdc)). click on any day with events and you will figure out the issue i was mentioning.

**Comment by arorakanav11** [comment]
Hi, i am facing the same issue with `angular-calendar:` ^0.26.0 and `@angular/core`: 7.1.0

**Comment by WarayAmine** [comment]
Hi, same here. I just tried to use this custom template and it's the same behavior.
@razeniraj i need to display my events almost the same way you do, what did you use for that ? Thanks.

**Comment by mattlewis92** [comment]
Ahh, I see what happened here, I think you might have copied the template from an older issue, please see the latest template source [here](https://github.com/mattlewis92/angular-calendar/blob/master/projects/angular-calendar/src/modules/month/calendar-open-day-events.component.ts#L32-L69), here's your example fixed: https://stackblitz.com/edit/angular-jqsjdc-gahtmy?file=demo/component.ts Hope that helps! 😄

**Comment by razeniraj** [comment]
> Ahh, I see what happened here, I think you might have copied the template from an older issue, please see the latest template source [here](https://github.com/mattlewis92/angular-calendar/blob/master/projects/angular-calendar/src/modules/month/calendar-open-day-events.component.ts#L32-L69), here's your example fixed: https://stackblitz.com/edit/angular-jqsjdc-gahtmy?file=demo/component.ts Hope that helps! 😄

Oh my mistake! Thanks for the help :)
