### ISSUE TITLE
BeforeViewRender asynchronus

### ISSUE THREAD

**Issue by jesdagonpasdev** [mattlewis92/angular-calendar#861]
Hi, im trying to "paint" the days in "mwl-calendar-month-view" component, depending on http request. I get some dates from it, and i want to paint the day-cells (cssClass) if this dates and the day-cells are equals.
But the "beforeViewRender" method dont get it my request.
How can i do?

**Comment by mattlewis92** [comment]
Hi there, please re-open a new issue filling out the issue template with the requested information, as without the information required by the issue template, it's impossible to really know what's going wrong with your app. Thank you! 😄
