### ISSUE TITLE
manipulate month calendar dimension

### ISSUE THREAD

**Issue by Raven5650** [mattlewis92/angular-calendar#862]
Hi,
im tring to use the month calendar but im finding some difficulty.
the height of the cell is always the same even if i override it with angular in the ngAfterViewInit event.
should there be an other strategy?
Thanks for the replay.

**Comment by mattlewis92** [comment]
Hi there, please re-open a new issue filling out the issue template with the requested information, as without the information required by the issue template, it's impossible to really know what's going wrong with your app. Thank you! 😄
