### ISSUE TITLE
Hour click on mobile platform

### ISSUE THREAD

**Issue by AstRonin** [mattlewis92/angular-calendar#864]
I use Sumsung Galaxy Tab S2 with Crome
Version:  0.26.4
Angular: ^6

Calendar type: [day-view-scheduler](https://mattlewis92.github.io/angular-calendar/#/day-view-scheduler)

When I click to hour sometimes event triggered, sometimes not.
Maybe click event conflict with drag event...

**Comment by mattlewis92** [comment]
Hi there, please re-open a new issue filling out the issue template with the requested information, as without the information required by the issue template, it's impossible to really know what's going wrong with your app. Thank you! 😄
