### ISSUE TITLE
change monthly view by week

### ISSUE THREAD

**Issue by czechk** [mattlewis92/angular-calendar#866]
**Is your feature request related to a problem? Please describe**

Possibility of changing monthly view by using a week. Currently monthly view as name 
suggests operates on months, which means if we provide a [viewDate] to mwl-calendar-month-view, it starts/ends on particular month we provided in date.

**Describe the solution you'd like**

Would like to have a way to change monthly view by using a week as a unit or possibility to have additional bindings maybe [startDate] [endDate] to better customize monthly view.

**Describe your use case for implementing this feature**

Smoothly "scrolling" of monthly view

**Comment by mattlewis92** [comment]
You can do this with the current api, please checkout this demo: https://mattlewis92.github.io/angular-calendar/#/extra-month-view-weeks Hope that helps! 😄

**Comment by kisielm** [comment]
I've tried that and it works like a charm. I've modified your example and added clickable events to a calendar like in here https://8fz3th.run.stackblitz.io/
And after clicking on an event 31.01 I'm moved to previous month/calendar page. Can I turn off that behaviour? I would like to stay on the same calendar page, can it be done somehow?
