### ISSUE TITLE
drag&drop with scroll on mobile/pad Chrome

### ISSUE THREAD

**Issue by AstRonin** [mattlewis92/angular-calendar#867]
**Describe the bug**

Calendar type: [day-view-scheduler](https://mattlewis92.github.io/angular-calendar/#/day-view-scheduler)
There does not work expectable Drag&Drop (up and down) with Scroll on mobile/pad Chrome. (About iPad/iPhone I don't know because I have not these).
- On Demo and my site drag&drop works but scroll not works.
- On my sample (look link below) drag&drop and scroll work both at one time.

**Minimal reproduction of the problem with instructions**

Please look to test page:
https://angular-lrkesj.stackblitz.io
And you can find on your demo site:
https://mattlewis92.github.io/angular-calendar/#/day-view-scheduler

**Versions**

- "@angular/core": "6.1.9",
- "angular-calendar": "^0.26.4",
- Android 7.0
- Chrome 71

**Note**

On this page
https://fullcalendar.io/releases/fullcalendar-scheduler/1.9.4/demos/vertical-resource-view.html
you can find how it should work: drag&drop activate after LongType on screen, before works scroll...
Do you use long type events https://fullcalendar.io/docs/touch?

**Comment by AstRonin** [comment]
ok..., I just seen https://github.com/mattlewis92/angular-calendar#does-this-calendar-work-with-mobile ...

**Comment by AstRonin** [comment]
I found something, if I remove (mwlClick) from mwl-calendar-day-view-hour-segment, then scroll works better
![image](https://user-images.githubusercontent.com/2378239/51632434-bd082c00-1f68-11e9-92e1-371938b25c24.png)

**Comment by mattlewis92** [comment]
The issue is caused by hammerjs adding these properties to all clickable elements:
<img width="242" alt="screenshot 2019-02-03 at 11 28 52" src="https://user-images.githubusercontent.com/6425649/52172662-e9148000-27a6-11e9-812a-0f033b75ddf5.png">

If you use your own CSS to override them then it should fix the issue. Or if you remove hammerjs it will also fix it, but then you lose the responsiveness on click. I spent a _long_ time fiddling about with this trying to find a solution to this issue that works out the box, but couldn't find anything. If you can work out a solution and could send a PR that would be amazing! 😄

**Comment by mattlewis92** [comment]
Looks like @wendlandreas found a solution here for anyone that's interested: https://github.com/mattlewis92/angular-calendar/issues/724#issuecomment-469046618

**Comment by AstRonin** [comment]
I am not sure what understand how I can use it... Can you please put it to [Day Schedule Example](https://mattlewis92.github.io/angular-calendar/#/day-view-scheduler)?

**Comment by mattlewis92** [comment]
Sure, I just added it to the demo. To use it

1/ Upgrade to the latest version of the calendar: `npm i angular-calendar@0.26.9`
2/ Add [this](https://github.com/mattlewis92/angular-calendar/blob/master/projects/demos/app/hammer-config.ts) to the providers of your [root app module](https://github.com/mattlewis92/angular-calendar/blob/master/projects/demos/app/demo-app.module.ts#L303-L308)

I just tested it on chrome on ios and it's working pretty well now 😄

**Comment by fquirozjara** [comment]
Hi! @mattlewis92 thanks a lot for that fix, but i have some trouble when i try to use `(press)="something()"` on ios, all works fine until i use that press function and i lost scrolling again,

**Comment by mattlewis92** [comment]
Sorry I don't really do a lot of mobile development or use hammerjs myself, that solution was copied from another user

**Comment by AstRonin** [comment]
@fquirozjara For mobile platform I use [Context Menu](https://mattlewis92.github.io/angular-calendar/#/context-menu) as temp and acceptable solution (I'm not implemented this fix yet for me)
