### ISSUE TITLE
Examples work on Chrome and Firefox but not on Safari.

### ISSUE THREAD

**Issue by danielptm** [mattlewis92/angular-calendar#87]
Thanks for this awesome project! The examples seem to work just fine on firefox and chrome on my 2011 macbook pro. But do not work on safari 9.1. I realize now that this is not the latest version of safari. I am updating now and will try on that in a few minutes.

This is the error message on Safari Version 9.1.1.

> [Error] EXCEPTION: Error in ./CalendarMonthViewComponent class CalendarMonthViewComponent - inline template:3:67 caused by: Can't find variable: Intl
	g (localhost:68:175)
	handleError (main.bundle.js:41885)
	next (main.bundle.js:26573:94)
	(anonymous function) (main.bundle.js:28086)
	__tryOrUnsub (main.bundle.js:4036)
	next (main.bundle.js:3985)
	_next (main.bundle.js:3938)
	next (main.bundle.js:3902)
	next (main.bundle.js:7815)
	emit (main.bundle.js:28078)
	triggerError (main.bundle.js:28892)
	onHandleError (main.bundle.js:28871)
	handleError (main.bundle.js:78809)
	runTask (main.bundle.js:78730)
	drainMicroTaskQueue (main.bundle.js:78974)
	invoke (main.bundle.js:78912)
[Error] ORIGINAL EXCEPTION: Can't find variable: Intl
	g (localhost:68:175)
	handleError (main.bundle.js:41887)
	next (main.bundle.js:26573:94)
	(anonymous function) (main.bundle.js:28086)
	__tryOrUnsub (main.bundle.js:4036)
	next (main.bundle.js:3985)
	_next (main.bundle.js:3938)
	next (main.bundle.js:3902)
	next (main.bundle.js:7815)
	emit (main.bundle.js:28078)
	triggerError (main.bundle.js:28892)
	onHandleError (main.bundle.js:28871)
	handleError (main.bundle.js:78809)
	runTask (main.bundle.js:78730)
	drainMicroTaskQueue (main.bundle.js:78974)
	invoke (main.bundle.js:78912)
[Error] ORIGINAL STACKTRACE:
	g (localhost:68:175)
	handleError (main.bundle.js:41890)
	next (main.bundle.js:26573:94)
	(anonymous function) (main.bundle.js:28086)
	__tryOrUnsub (main.bundle.js:4036)
	next (main.bundle.js:3985)
	_next (main.bundle.js:3938)
	next (main.bundle.js:3902)
	next (main.bundle.js:7815)
	emit (main.bundle.js:28078)
	triggerError (main.bundle.js:28892)
	onHandleError (main.bundle.js:28871)
	handleError (main.bundle.js:78809)
	runTask (main.bundle.js:78730)
	drainMicroTaskQueue (main.bundle.js:78974)
	invoke (main.bundle.js:78912)
[Error] monthViewColumnHeader@http://localhost:4200/main.bundle.js:46917:24
transform@http://localhost:4200/main.bundle.js:64621:42
[native code]
http://localhost:4200/main.bundle.js:18900:24
detectChangesInternal
detectChanges@http://localhost:4200/main.bundle.js:59376:35
detectChanges@http://localhost:4200/main.bundle.js:59481:48
detectContentChildrenChanges@http://localhost:4200/main.bundle.js:59394:32
detectChangesInternal
detectChanges@http://localhost:4200/main.bundle.js:59376:35
detectChanges@http://localhost:4200/main.bundle.js:59481:48
detectViewChildrenChanges@http://localhost:4200/main.bundle.js:59402:32
detectChangesInternal
detectChanges@http://localhost:4200/main.bundle.js:59376:35
detectChanges@http://localhost:4200/main.bundle.js:59481:48
detectContentChildrenChanges@http://localhost:4200/main.bundle.js:59394:32
detectChangesInternal
detectChanges@http://localhost:4200/main.bundle.js:59376:35
detectChanges@http://localhost:4200/main.bundle.js:59481:48
detectViewChildrenChanges@http://localhost:4200/main.bundle.js:59402:32
detectChangesInternal
detectChanges@http://localhost:4200/main.bundle.js:59376:35
detectChanges@http://localhost:4200/main.bundle.js:59481:48
detectViewChildrenChanges@http://localhost:4200/main.bundle.js:59402:32
detectChangesInternal
detectChanges@http://localhost:4200/main.bundle.js:59376:35
detectChanges@http://localhost:4200/main.bundle.js:59481:48
detectContentChildrenChanges@http://localhost:4200/main.bundle.js:59394:32
detectChangesInternal
detectChanges@http://localhost:4200/main.bundle.js:59376:35
detectChanges@http://localhost:4200/main.bundle.js:59481:48
detectViewChildrenChanges@http://localhost:4200/main.bundle.js:59402:32
detectChangesInternal
detectChanges@http://localhost:4200/main.bundle.js:59376:35
detectChanges@http://localhost:4200/main.bundle.js:59481:48
detectChanges@http://localhost:4200/main.bundle.js:42981:33
http://localhost:4200/main.bundle.js:26738:97
forEach@[native code]
tick@http://localhost:4200/main.bundle.js:26738:45
http://localhost:4200/main.bundle.js:26679:109
invoke@http://localhost:4200/main.bundle.js:78805:31
onInvoke@http://localhost:4200/main.bundle.js:28850:43
invoke@http://localhost:4200/main.bundle.js:78804:40
run@http://localhost:4200/main.bundle.js:78687:49
run@http://localhost:4200/main.bundle.js:28740:65
next@http://localhost:4200/main.bundle.js:26679:84
http://localhost:4200/main.bundle.js:28086:56
__tryOrUnsub@http://localhost:4200/main.bundle.js:4036:20
next@http://localhost:4200/main.bundle.js:3985:34
_next@http://localhost:4200/main.bundle.js:3938:30
next@http://localhost:4200/main.bundle.js:3902:23
next@http://localhost:4200/main.bundle.js:7815:29
emit@http://localhost:4200/main.bundle.js:28078:80
checkStable@http://localhost:4200/main.bundle.js:28818:44
setHasMicrotask@http://localhost:4200/main.bundle.js:28889:25
onHasTask@http://localhost:4200/main.bundle.js:28862:46
hasTask@http://localhost:4200/main.bundle.js:78866:42
_updateTaskCount@http://localhost:4200/main.bundle.js:78883:33
invokeTask@http://localhost:4200/main.bundle.js:78843:42
runTask@http://localhost:4200/main.bundle.js:78727:57
drainMicroTaskQueue@http://localhost:4200/main.bundle.js:78974:42
invoke@http://localhost:4200/main.bundle.js:78912:44
	g (localhost:68:175)
	handleError (main.bundle.js:41891)
	next (main.bundle.js:26573:94)
	(anonymous function) (main.bundle.js:28086)
	__tryOrUnsub (main.bundle.js:4036)
	next (main.bundle.js:3985)
	_next (main.bundle.js:3938)
	next (main.bundle.js:3902)
	next (main.bundle.js:7815)
	emit (main.bundle.js:28078)
	triggerError (main.bundle.js:28892)
	onHandleError (main.bundle.js:28871)
	handleError (main.bundle.js:78809)
	runTask (main.bundle.js:78730)
	drainMicroTaskQueue (main.bundle.js:78974)
	invoke (main.bundle.js:78912)

**Comment by mattlewis92** [comment]
You're missing the Intl polyfill which safari < 10 doesn't have (and angular requires for its date pipe): https://github.com/andyearnshaw/Intl.js/
