### ISSUE TITLE
Cant change to spanish

### ISSUE THREAD

**Issue by Creativosplus** [mattlewis92/angular-calendar#874]
I'm using this demo https://mattlewis92.github.io/angular-calendar/#/i18n to change de language of the calendar to spanish.

I'm chaning this `locale: string = 'fr';` to this `locale: string = 'es';` and it's not working.

How could i change that?

**Comment by sgabb** [comment]
Check the demo [here](https://stackblitz.com/run?file=demo%2Fmodule.ts), specifically the module.ts
You will need to import and register the locale:
`import { registerLocaleData } from '@angular/common';`
`import localeEs from '@angular/common/locales/es';`
`registerLocaleData(localeEs);
`
