### ISSUE TITLE
Translation issue

### ISSUE THREAD

**Issue by Creativosplus** [mattlewis92/angular-calendar#875]
**Is your feature request related to a problem? Please describe**

I'm using this demo https://mattlewis92.github.io/angular-calendar/#/i18n to change de language of the calendar to spanish.

I'm chaning this `locale: string = 'fr';` to this `locale: string = 'es';` and it's not working.

How could i change that?

**Describe the solution you'd like**

Just to put 'es' on locale variable.

**Describe your use case for implementing this feature**

Need spanish support.

**Additional context**

None

**Comment by mattlewis92** [comment]
It sounds like you're not importing the spanish locale, check the `module.ts` tab under the demo and you'll see:

```
import localeFr from '@angular/common/locales/fr';
registerLocaleData(localeFr);
```

You need to do the equivalent for spanish.
