### ISSUE TITLE
It would be awesome if this would work with Angular Material!

### ISSUE THREAD

**Issue by devchris** [mattlewis92/angular-calendar#880]
**Is your feature request related to a problem? Please describe**

I am using Angular Material in my App and wanted to implement the angular-calendar. The only thing holding me back from it is that it requires Bootstrap.

**Describe the solution you'd like**

Switching the styling from Bootstrap to use angular material 🚀 

I'm sure that many more would use your calendar if it would be available without bootstrap 👍

**Comment by mattlewis92** [comment]
Hey, there's actually no dependency on bootstrap, I just use it for the demo. I designed this to just respond to your apps styles, if you take out bootstrap you'll see it still works: https://stackblitz.com/edit/angular-s5woar?file=index.html You just might have to apply some additional CSS to it to make it match the material design look. Hope that helps! 😄

**Comment by devchris** [comment]
Thanks for the feedback! I'd probably also have to replace the `NgbModalModule` since this depends on bootstrap styling as well

**Comment by mattlewis92** [comment]
Yup, for sure, material gives its own implementation of tabs, modals etc that the demo uses so you can just swap those out, there's nothing in the core `angular-calendar` package that has any dependency on bootstrap
