### ISSUE TITLE
Async events do not work on safari

### ISSUE THREAD

**Issue by crispaez** [mattlewis92/angular-calendar#883]
**Describe the bug**
the events do not appear in safari when the asynchronous event pattern is followed, however identify the problem in the function "getTimezoneOffsetString", apparently safari does not support the format that this function gives us.

**Minimal reproduction of the problem with instructions**
follow the async events demo

https://mattlewis92.github.io/angular-calendar/#/async-events

try safari

**Comment by mattlewis92** [comment]
Looks like safari doesn't like that date format, the function here looks like it fixes it: https://stackoverflow.com/a/42151174 PR's welcome, [this line](https://github.com/mattlewis92/angular-calendar/blob/master/projects/demos/app/demo-modules/async-events/component.ts#L86-L88) needs to be changed to use the linked function.
