### ISSUE TITLE
can you please show me how to change the week view's header ?

### ISSUE THREAD

**Issue by maaqoul** [mattlewis92/angular-calendar#887]
**Is your feature request related to a problem? Please describe**

i would like to be able to change the week view's header so it can only show days of the week without the month

**Comment by mattlewis92** [comment]
Hi there, you can use a [custom date formatter](https://mattlewis92.github.io/angular-calendar/#/customise-date-formats) for this and override the `weekViewColumnHeader` function to perform as you desire. Hope that helps! 😄

**Comment by khyati1984** [comment]
I would like to change weekly view same as monthly view. I need to show date and  number of events per day in weekly view same as monthly view.
And each day click functionality same as month

Kindly help me on this.
