### ISSUE TITLE
Schematics!

### ISSUE THREAD

**Issue by mattlewis92** [mattlewis92/angular-calendar#888]
It would be super cool if you could do 

```
ng add angular-calendar
```

and then it would:
* prompt if you want to use date-fns or moment
* install the required dependencies (`angular-calendar`, `date-fns` or `moment`)
* add the calendar module (to the root module or one passed as `--module=module`)
* add the global style sheet to angular.json

Resources:
https://brianflove.com/2018/12/15/ng-add-schematic/
https://github.com/ng-bootstrap/schematics

**Comment by Worthy7** [comment]
'--module=module' to change which module it appends to (same as the 'ng g component...'!

**Comment by billyjov** [comment]
I will work on this

**Comment by mattlewis92** [comment]
@billyjov thanks, that would be awesome! I already setup the boilerplate the other day on this branch so you can work off there: https://github.com/mattlewis92/angular-calendar/commits/schematics

and then for each of the actions it needs to do, can be copied from here: https://brianflove.com/2018/12/15/ng-add-schematic/

Let me know if you need any other guidance! 😄
