### ISSUE TITLE
Merge day and week view

### ISSUE THREAD

**Issue by mattlewis92** [mattlewis92/angular-calendar#889]
I kind of just realised that with the changes in 0.26, the day view is now just a week view with `[daysInWeek]="1"`. The day view could just become a very thin wrapper over the week view with that option set and the header hidden and it would allow a lot of code to be deleted and make maintenance a lot easier. Unless people are doing really advanced customisations it shouldn't even be breaking for most users 😄

**Comment by JaxonWright** [comment]
I was just thinking about this. Would eliminate a lot of unneeded code.

**Comment by rosostolato** [comment]
I have an implementation of [day view scheduler](https://mattlewis92.github.io/angular-calendar/#/day-view-scheduler). How could I do it now after this merge?

My main problem is in `CalendarUtils` extends, I used `super.getDayView(args)` and there is no method near to that now.

**Comment by mattlewis92** [comment]
I updated the demo for that in the 0.28 branch: https://github.com/mattlewis92/angular-calendar/tree/0.28/projects/demos/app/demo-modules/day-view-scheduler
