### ISSUE TITLE
4 minute event, rendering incorrectly - On Day View Calendar 

### ISSUE THREAD

**Issue by jgrant95** [mattlewis92/angular-calendar#894]
I am currently having an issue, where I have set the 'hourSegments' input on my day view calendar to 12, to provide for 5min slots on the day calendar. 

Everything is working okay, but I have come across an anomaly. I have a 4min long event, which appears smaller than it should (like its the height of a 3min event). Precision is important for what I'm trying to use this for.

However, after some debugging of the calendar-utils I came across what I think may be the issue, but am unsure why this is happening...

During the `getDayView()` function, the event has a startDate of:  `Mon Feb 25 2019 09:31:00 GMT+0000 (Greenwich Mean Time)`

and an endDate of: 

`Mon Feb 25 2019 09:35:00 GMT+0000 (Greenwich Mean Time)`.

So just 4 minutes between them. However, the line:

`var height = differenceInMinutes(endDate, startDate);` seems to be returning `3` for some reason as the difference in minutes. No idea why, but this is clearly why my issue is happening. Below is a screenshot of my debugging finding.

![issue_calendar_2](https://user-images.githubusercontent.com/10797587/53098759-42f1a580-351c-11e9-8112-450cd681fcb1.PNG)

Also worth noting that have tried with various versions of moment, does not seem to help. When doing the exact same code outside of the calendar-utils, inside my own angular project, the minutes returned is correct too.

**Minimal reproduction of the problem with instructions**

This is how the issue appears on the calendar, the event pointed too should be right next to the following event. Clearly it is not 4mins long:

![issue_calendar](https://user-images.githubusercontent.com/10797587/53098932-a085f200-351c-11e9-8ea1-d7b972f83de3.PNG)

**Versions**

- `@angular/core`: 7.1.4
- `angular-calendar`: 0.26.6
- Browser name and version: Chrome, Version 72.0.3626.109 (Official Build) (64-bit)

**Comment by mattlewis92** [comment]
Any chance you could make a minimal repro on stackblitz etc that shows your problem? You can fork a starter from any of the demos by hitting the stackblitz button. Thanks! 😄
