### ISSUE TITLE
Provide an easier way of passing custom date formatters to the forRoot method

### ISSUE THREAD

**Issue by mattlewis92** [mattlewis92/angular-calendar#90]
Needs to be AOT compatible

**Comment by thatONEjustin** [comment]
what's the status of this? I want to do a basic formatting of the month view column headers and the [locale] attribute seems to only affect the calendarHeader, and importing the components into my controller seems to give me a very limited scope of interacting with the overall calendar. 

getting pretty frustrated.

**Comment by mattlewis92** [comment]
Sorry to hear you're getting frustrated, I will do what I can to help! 

It's actually possible with the current API to override the date formatter to change the column headers. You can see an example of how to do this [here](https://github.com/mattlewis92/angular-calendar/issues/78#issuecomment-256573939). I hope that helps!
