### ISSUE TITLE
The animated div expands before collapsing in month view

### ISSUE THREAD

**Issue by gaurav517** [mattlewis92/angular-calendar#91]
Steps to reproduce:

In month view:
1. click on a day with 3 events. 3 events for the day will appear.
2. click on a day with 1 event. 1 event for the day will appear.
3. click on a day with no event. The events will disappear but before disappearing:
- The animated div will resize from 1 event to 3 events before collapsing. This would look quite evident if animation is slowed down a bit.

Expected: The animated div should collapse without first resizing from 1 even to 3 events.
Please ask me in case of any questions. Thanks.

**Comment by mattlewis92** [comment]
This is something I'm aware of and spent several hours trying to fix. My conclusion was that it was an issue with angular / web animations API itself and I don't think there's anything I can do my end to fix it.
