### ISSUE TITLE
Week View Time Column

### ISSUE THREAD

**Issue by sarialon** [mattlewis92/angular-calendar#911]
**Describe the bug**

The attached image shows the problem.
the time column doesnt render as a sperate column.
![week_view](https://user-images.githubusercontent.com/1830931/53693042-c2943580-3da2-11e9-8aa2-bc0e7b98bcc7.png)

**Minimal reproduction of the problem with instructions**

**Screenshots**

**Versions**

- `@angular/core`:
- `angular-calendar`:
- Browser name and version:

**Comment by mattlewis92** [comment]
To get it to work with RTL you'll need to override the base week view template and tweak it as appropriate. This is an example for an older version of the calendar so you can see how it works: https://github.com/mattlewis92/angular-calendar/issues/664#issuecomment-408715719

The source of the most up to date version of the week view template is here: https://github.com/mattlewis92/angular-calendar/blob/master/projects/angular-calendar/src/modules/week/calendar-week-view.component.ts#L80-L348

Hope that helps! 😄
