### ISSUE TITLE
i have to send the events of multiple array of objects and i have to print in on ng-template  but its repating for n number of objects

### ISSUE THREAD

**Issue by chaitanyagupta412** [mattlewis92/angular-calendar#912]
**Is your feature request related to a problem? Please describe**

**Describe the solution you'd like**

**Describe your use case for implementing this feature**

**Additional context**

**Comment by mattlewis92** [comment]
Please follow the issue template and include a stackblitz or something that reproduces the issue you're experiencing, as without that I can't provide any further assistance. Thanks!
