### ISSUE TITLE
Sticky date header and time segment

### ISSUE THREAD

**Issue by IamSef** [mattlewis92/angular-calendar#914]
**Is your feature request related to a problem? Please describe**

My UI design only shows the first two days of the week (i.e. Mon and Tue). It is enclosed in a scrollable div.

I need a feature where the header is fixed even if I scroll to the bottom time (i.e 11PM). I still need to see what day I am on.

Same with the time segment,  I need it fixed when I scroll to the right. I still need to see what time I am on.

**Comment by mattlewis92** [comment]
You can add some global CSS to make only parts of the calendar scrollable, I put together a demo here to show you how: https://stackblitz.com/edit/angular-w4urnk?file=index.html Hope that helps! 😄

**Comment by infantito** [comment]
I need it fixed when I scroll to the right too. But it's complicated because of time events are in the same level of days column.

@IamSef , How did you get it?

**Comment by Leccho** [comment]
> You can add some global CSS to make only parts of the calendar scrollable, I put together a demo here to show you how: https://stackblitz.com/edit/angular-w4urnk?file=index.html Hope that helps! 😄

This looks better with:
```css
.cal-day-headers {
  padding-right: 17px;
}
```

**Comment by tbelmega** [comment]
> You can add some global CSS to make only parts of the calendar scrollable, I put together a demo here to show you how: https://stackblitz.com/edit/angular-w4urnk?file=index.html Hope that helps! 😄

Thanks for your inspiration!
Your demo has the slight disadvantage that you are fixing the height of the scrollable part (to 400px).
Since my app should work on large PC screens as well as small phones, I want the srollable part to fill all the vertical space that's left over from the sticky header.

Inspired by your solution, I created my own solution using flexbox.

CSS:
```
.calendar-container {
  display: flex;
  flex-direction: column;
  height: 100vh; # Container fills 100% of the screen
}
.sticky-header {
  flex-shrink: 0; # Header must not shrink, takes as much space as it needs
}
.scrollable-content {
  flex-shrink: 1; # Shrink to fit into the remaining space of the container
  overflow-y: auto;
} 
```

HTML:
```
<div class="calendar-container">
  <div class="sticky-header">
    <!-- header content... -->
  </div>

  <div *ngIf="events$ | async; else loading; let events" class="scrollable-content">
     <!-- calendar views, as before... -->
  </div>
</div>
```
