### ISSUE TITLE
eventClick does not work when a Custom Template is ds

### ISSUE THREAD

**Issue by suprfunwifmi** [mattlewis92/angular-calendar#918]
**For the Week and Day View I have set two seperate custom templates, so more data can be displayed on the event. My issue is I also want to have a Modal Window pop up, once you click on a Event. Problem is with the eventTemplate set the Output eventClicked does not work**

**Minimal reproduction of the problem with instructions**

**Screenshots**
This works and would display the modal window.
![image](https://user-images.githubusercontent.com/20042823/53948435-15822b80-40c8-11e9-9bc4-871fade5fd02.png)

This does not work and does not even go throught the method placed in eventClicked.
![image](https://user-images.githubusercontent.com/20042823/53948528-4febc880-40c8-11e9-9bed-f50d4349796a.png)

Is there a way I can get a custom event Template to be clickable?

**Versions**

- `@angular/core`: 7.0.0
- `angular-calendar`: 0.26.6
- Browser and version: Google Chrome 72.0.3626.96

**Comment by mattlewis92** [comment]
It's working for me: https://stackblitz.com/edit/angular-uow6pz?file=demo/component.ts Can you make a stackblitz that reproduces your issue? Thanks! 😄
