### ISSUE TITLE
New events not showing after adding using Async loading

### ISSUE THREAD

**Issue by Moneyba** [mattlewis92/angular-calendar#921]
**Describe the bug**

Hi there! I'm trying to load some events in my calendar using the example of Async Events. So far, the events load properly, but the main problem is, whenever I create a new event, even tho I re-load the events from the http request, they don't show up in the calendar till I click on other day or till I manually refresh the web page. How can I solve this to get the new events refreshed in real time without performing any manual action? Thanks in advance!

**Minimal reproduction of the problem with instructions**

 https://stackblitz.com/edit/angular-ulfoku

**Versions**

- `@angular/core`: 7.3.0
- `angular-calendar`: 0.26.6
- Chrome 72.0.3626.119

**Comment by mattlewis92** [comment]
Your stackblitz doesn't run for me so I can't reproduce your problem, can you fix it please? Thanks! 😄

**Comment by Moneyba** [comment]
So, I fixed my stackblitz, but still, events won't load since I don't have a public API (I'm using a localhost backend for now)
https://stackblitz.com/edit/angular-rxyzbe-1hsufk?file=demo/component.ts

Thing is still the same, whenever I close my modal I call the function to 'manually' refresh my events, but they won't appear till I click on some event in the calendar. They don't refresh 
when this function is called. I don't know what I am doing wrong. I have tried with the async aproach as well but I have the exact same issue. After closing the modal the function is called and the
array is also updated, but seems that the calendar doesn't follow up. I hope you can help me with this! Thanks in advance!

**Comment by mattlewis92** [comment]
Thanks for that, I see your issue now, when you push to an array it doesn't change its object reference in javascript, so angular doesn't know the array has been updated and nothing will update. If you change your code to something that creates a new array reference it should work for you:

```
this.events = backendWorkdays.map(backendWorkday => {
      const calendarEventToAdd: CalendarEvent = {
        start: backendWorkday.start_workday,
        end: backendWorkday.end_workday,
        title: this.getCalendarEventTitleFromWorkday(backendWorkday),
        meta: {
          pauseTime: backendWorkday.paused_time.getMinutes(),
          notes: backendWorkday.notes,
          reason: backendWorkday.editReason,
          workdayId: backendWorkday.workday_id,
        }
      };
      return calendarEventToAdd;
    });
```
