### ISSUE TITLE
Hijri calendar support

### ISSUE THREAD

**Issue by HKTemp** [mattlewis92/angular-calendar#923]
Hello, I've looked at the demos and documentation, but I couldn't find if you support the Islamic Hijri calendar? From what I've seen it looks like it is not supported? 

Support for the Islamic Hijri calendar is a requirement for me to be able to use the calendar.

**Comment by MohammedAldosari** [comment]
I've developed Hijri adapter that seamlessly integrates both the Hijri and Gregorian calendars, offering a comprehensive solution for diverse calendrical needs.

[Hijri-Angular-Calendar](https://github.com/MohammedAldosari/hijri-angular-calendar#hijri-angular-calendar)
