### ISSUE TITLE
calendarDate not taking into account weekStartsOn in week view

### ISSUE THREAD

**Issue by Beckilicki** [mattlewis92/angular-calendar#926]
**Describe the bug**

In my project week starts on monday, when switching to week view I can see current week (monday 18.3.2019 through sunday 24.3.2019) but date shown in the header shows march 17th - march 23rd.

**Minimal reproduction of the problem with instructions**

https://stackblitz.com/edit/angular-awmwgk

**Screenshots**

![calendar](https://user-images.githubusercontent.com/33659070/54592750-4d289600-4a2d-11e9-81b5-ab558c30f178.jpg)

**Versions**

- `@angular/core`: 6.1.4
- `angular-calendar`: 0.26.4 (bug tested on demo stackblitz of kitchensink)
- Browser name and version: Google Chrome 72.0.3626.121

**Comment by mattlewis92** [comment]
Whoops, sorry about that, there's a small mistake with the demo. If you pass the `weekStartsOn` value to the calendarDate pipe it should fix your issue: ` {{ viewDate | calendarDate:(view + 'ViewTitle'):locale:weekStartsOn }}`. Hope that helps! 😄

**Comment by Beckilicki** [comment]
That did the trick. Thanks a lot. Is it possible to get full month name from the pipe in the week view? At the moment I'm getting shortened name: mar 18 - mar 24, 2019 and I'm looking for mart 18 - mart 24, 2019.

**Comment by mattlewis92** [comment]
Sure, you can override the `weekViewTitle` method using a custom date formatter: https://mattlewis92.github.io/angular-calendar/#/customise-date-formats

**Comment by Beckilicki** [comment]
Thanks a lot.

**Comment by DelRioOscar** [comment]
@mattlewis92 
I have a problem with weekStartsOn... Can be a bug calendar.

this is my code.

HTML
<div [ngSwitch]="view">

        <mwl-calendar-month-view *ngSwitchCase="'month'" [viewDate]="viewDate" [events]="events"
           [activeDayIsOpen]="activeDayIsOpen" (dayClicked)="dayClicked($event.day)"
          (eventClicked)="handleEvent('Clicked', $event.event)" (eventTimesChanged)="eventTimesChanged($event)">
        </mwl-calendar-month-view>

        <mwl-calendar-week-view *ngSwitchCase="'week'" [viewDate]="viewDate" [events]="events"
        [weekStartsOn]="weekStartsOn"
        [weekendDays]="weekendDays" (eventClicked)="handleEvent('Clicked', $event.event)"
          (eventTimesChanged)="eventTimesChanged($event)">
        </mwl-calendar-week-view>

        <mwl-calendar-day-view *ngSwitchCase="'day'" [viewDate]="viewDate" [events]="events"
           (eventClicked)="handleEvent('Clicked', $event.event)"
          (eventTimesChanged)="eventTimesChanged($event)">
        </mwl-calendar-day-view>

      </div>

TS:
weekStartsOn: number = DAYS_OF_WEEK.MONDAY;
weekendDays: number[] = [DAYS_OF_WEEK.FRIDAY, DAYS_OF_WEEK.SATURDAY];

When i set this: <div class="col-md-4">
          <h3>{{ viewDate | calendarDate:(view + 'ViewTitle'):'en':weekStartsOn }}</h3>
        </div>

there is not any change :(

**Comment by wautersj** [comment]
I also can't get the 'weekStartsOn' to work.

It works in the stackblitz demo, as I can so.
But doing the very same in a fresh and clean setup, but the view didn't change.

**Comment by nectorosales** [comment]
used in app.module 
import {adapterFactory} from 'angular-calendar/date-adapters/date-fns';
You're probably just using moment
