### ISSUE TITLE
Angular calendar has not exported member 'DateAdapter' in angular 5 

### ISSUE THREAD

**Issue by Assdi** [mattlewis92/angular-calendar#928]
**Describe the bug**

I have installed this module using this command in my angular 5 application.
`npm install --save angular-calendar@0.24.1 date-fns`

**Getting this error**

**Screenshots**
![image](https://user-images.githubusercontent.com/16256206/54604497-ae218f80-4a68-11e9-9f0d-6cba8052a1f4.png)

**Versions**

- `@angular/core:5`
- `angular-calendar:0.24.1`
Is there any docs for angular 5 ?

**Comment by mattlewis92** [comment]
The error you're having is because there were some breaking changes in later versions. You can view the old getting started guide for that version here: https://github.com/mattlewis92/angular-calendar/tree/v0.24.1 Hope that helps!

**Comment by Assdi** [comment]
@mattlewis92  I have imported it correctly by reading READMe.md file  but how to use it in component file. the docs you given is for 6 . [https://mattlewis92.github.io/angular-calendar/#/kitchen-sink](url)

**Comment by mattlewis92** [comment]
The sources for the demos are all available on that branch e.g. for the kitchen sink: https://github.com/mattlewis92/angular-calendar/tree/v0.24.1/demos/demo-modules/kitchen-sink

**Comment by Assdi** [comment]
Thank you for your time and support , I will look into it . (y) @mattlewis92

**Comment by mattlewis92** [comment]
No problem, happy to help! Out of curiosity, what is it that's stopping you from upgrading from angular 5 to the latest version?

**Comment by Assdi** [comment]
actually my application is big enough , I'm little afraid to update thinking I might disturb something . What you recommend @mattlewis92 , should I update ? is it easy ?

**Comment by mattlewis92** [comment]
The angular team actually made it super easy in v6+ to upgrade via the awesome `ng update` command that does all the heavy lifting for you. If you follow the instructions [here](https://update.angular.io/) it'll show you everything you need to do

<img width="840" alt="Screenshot 2019-03-26 at 18 27 14" src="https://user-images.githubusercontent.com/6425649/54990067-cf4c2800-4ff4-11e9-9bd6-aa87424833f1.png">

**Comment by Assdi** [comment]
Thank you so much for your time @mattlewis92  :) will surely do
