### ISSUE TITLE
Minimum height of event in week view not respecting hour segment height

### ISSUE THREAD

**Issue by mitchjarvis1967** [mattlewis92/angular-calendar#929]
In the week view, if you change the hourSegmentHeight to something other than 30 (default) the minimum isn't calculated correctly. For example, if the height is set to 20 with 4 segments per hour, the minimum is calcuated to be 22.5 minutes instead of 15 minutes.

Problem is in the getMinimumEventHeightInMinutes function in util.ts:
  return (MINUTES_IN_HOUR / (hourSegments * hourSegmentHeight)) * 30;
should be changed to
  return (MINUTES_IN_HOUR / (hourSegments * hourSegmentHeight)) * hourSegmentHeight;

**Minimal reproduction of the problem with instructions**

Use angular-calendar showing week view. Add [hourSegmentHeight]="20" (or something other than 30)
Then try to shrink an event to the minimum possible. Automatically sized the event to the incorrect height.

I did this with the Kitchen sink demo.

https://stackblitz.com/edit/angular-rserut

I can make the change and create a pull request if you'd like. It's so simple I didn't know if you'd like to make it yourself without all the hassle of the pull request, etc..

Thanks - awesome component!

**Screenshots**

**Versions**

- `@angular/core`: 7.2.9
- `angular-calendar`: 0.26.11
- Browser name and version: Chrome 73.0.3683.75

**Comment by mattlewis92** [comment]
Thanks for reporting, this is now fixed in `0.27`! 🎉
