### ISSUE TITLE
Not working in Angular2-seed

### ISSUE THREAD

**Issue by brightonhall** [mattlewis92/angular-calendar#93]
I'm trying to integrate this into my Angular2-seed project and I'm getting the following errors:

    src\client\app\calendar\bhcalendar.component.ts(19,3): error TS2305: Module '"C:/Websites/MEAN/schoolsite/node_modules/angular2-calendar/dist/esm/src/index"' has no exported member 'CalendarEventTimesChangedEvent'.
    src\client\app\calendar\bhcalendar.component.ts(144,5): error TS2322: Type '({ start: Date; end: Date; title: string; color: any; actions: EventAction[]; } | { start: Date; ...' is not assignable to type 'CalendarEvent[]'.   Type '{ start: Date; end: Date; title: string; color: any; actions: EventAction[]; } | { start: Date; t...' is not assignable to type 'CalendarEvent'.  Type '{ start: Date; end: Date; title: string; color: any; actions: EventAction[]; resizable: { beforeS...' is not assignable to type 'CalendarEvent'. Object literal may only specify known properties, and 'resizable' does not exist in type 'CalendarEvent'.
    src\client\app\calendar\bhcalendar.component.ts(154,24): error TS7017: Index signature of object type implicitly has an 'any' type.
    src\client\app\calendar\bhcalendar.component.ts(166,24): error TS7017: Index signature of object type implicitly has an 'any' type.

The "resizable" error fails on this code, line 144:

    }, {
      start: addHours(startOfDay(new Date()), 2),
      end: new Date(),
      title: 'A resizable event',
      color: colors.yellow,
      actions: this.actions,
      resizable: {
        beforeStart: true,
        afterEnd: true
      }
    }];

... and the "Index signature of Object..." errors fail on this code, line 154:

    increment(): void {
    
      const addFn: any = {
        day: addDays,
        week: addWeeks,
        month: addMonths
      }[this.view];
    
      this.viewDate = addFn(this.viewDate, 1);
    }
    
    decrement(): void {
    
      const subFn: any = {
        day: subDays,
        week: subWeeks,
        month: subMonths
      }[this.view];
    
      this.viewDate = subFn(this.viewDate, 1);
    }

After I npm installed the angular2-calendar into my project, I created a calendar set of files (.ts, html, css, module, etc) and copied your DemoComponent code into my component, and set the required module definitions.  I know I'm missing something, I'm just not sure what.

Any ideas?

**Comment by brightonhall** [comment]
I just noticed that in my installed node_modules folder for angular2-calendar, in the angular2-calendar/src/dist/esm/interfaces/ folder, there is only calendarDateFormatter.interface.d.ts. 

calendarEventTimesChangedEvent.interface.d.ts is missing.

**Comment by brightonhall** [comment]
The import reference to it, is also missing in the node_modules ... index.d.ts file.

Also, the calendar-utils@0.0.35 is missing the resizable property.  It seems @0.0.36 is used in your demo application but it's not included with the npm package.

The installed 'data-fns' are at version date-fns@^1.3.0 and not date-fns@^1.11.1.

I'll see if I can update my versions to make it all work.

**Comment by mattlewis92** [comment]
It sounds like you're on an old version of this lib - `0.0.35` of calendar utils is used in 0.3.x which doesn't have resizing of events. To migrate in your package.json change
```
"angular2-calendar": "^0.3.0"
```

to 

```
"angular-calendar": "^0.4.0"
```

(note that the package name changed as well)
