### ISSUE TITLE
weekStartOn is not working

### ISSUE THREAD

**Issue by orioldev** [mattlewis92/angular-calendar#930]
**Describe the bug**

The propiety [weekStartOn] is not working, it keeps showing me monday as the first day of the week.

**Minimal reproduction of the problem with instructions**

```
<mwl-calendar-week-view 
    [viewDate]="viewDate" 
    [events]="events" 
    [weekStartsOn]="2" 
    [daysInWeek]="daysInWeek" 
    [weekendDays]="[0,6]"
    [dayEndHour]="19" 
    [locale]="locale" 
    [dayStartHour]="8" 
    [hourSegmentHeight]="27" 
    (eventClicked)="eventClicked($event)" 
    [refresh]="refresh">
    </mwl-calendar-week-view>
```

**Versions**

0.26.11

- `@angular/core`:
- `angular-calendar`:
- Browser name and version: Google Chrome

**Comment by orioldev** [comment]
I still have the problem, I just saw that this happend when I combine `daysInWeek `with `weekStartsOn`. When I combine both of them, `weekStartsOn `is not applying for some reason.

**Comment by mattlewis92** [comment]
Whoops, sorry that should be documented, when you set `daysInWeek` then `weekStartsOn` is ignored as you may want a 10 day week which would include 2 of the same day. When `daysInWeek` is set, the `viewDate` is used as the first day of the week. I've just updated the docs to reflect this, thanks for opening an issue! 😄

**Comment by rubenheymans** [comment]
is there a way to change this behavior? I just need the daysInWeek for a responsive weekview but the max will allways be 7, and the first day of the week should always be monday

**Comment by sapabg** [comment]
[weekStartsOn]="1" is not working for me neither...

<div [ngSwitch]="view">
  <mwl-calendar-month-view
    *ngSwitchCase="CalendarView.Month"
    [viewDate]="viewDate"
    [events]="filteredEvents$ | async"
    [refresh]="refresh"
    [weekStartsOn]="1"
    [openDayEventsTemplate]="customCellTemplate"
    [activeDayIsOpen]="activeDayIsOpen"
    (dayClicked)="dayClicked($event.day)"
    (eventClicked)="viewEvent($event.event)"
    (eventTimesChanged)="eventTimesChanged($event)"></mwl-calendar-month-view>

  <mwl-calendar-week-view
    *ngSwitchCase="CalendarView.Week"
    [viewDate]="viewDate"
    [eventTemplate]="weekEventTemplate"
    [events]="filteredEvents$ | async"
    [refresh]="refresh"
    [dayStartHour]="'8'"
    [dayStartMinute]="'0'"
    [dayEndHour]="'20'"
    [dayEndMinute]="'0'"
    [weekStartsOn]="1"
    (hourSegmentClicked)="hourClicked($event)"
    (eventClicked)="viewEvent($event.event)"
    (eventTimesChanged)="eventTimesChanged($event)"></mwl-calendar-week-view>

  <mwl-calendar-day-view
    *ngSwitchCase="CalendarView.Day"
    [viewDate]="viewDate"
    [events]="filteredEvents$ | async"
    [refresh]="refresh"
    [dayStartHour]="'8'"
    [dayStartMinute]="'0'"
    [dayEndHour]="'20'"
    [dayEndMinute]="'0'"
    [eventTemplate]="dayEventTemplate"
    (hourSegmentClicked)="hourClicked($event)"
    (eventClicked)="viewEvent($event.event)"
    (eventTimesChanged)="eventTimesChanged($event)">
  </mwl-calendar-day-view>
</div>

it is always ignored in my case.
