### ISSUE TITLE
Actions (edit or delete) with Drag and Drop 

### ISSUE THREAD

**Issue by rafi-dvp** [mattlewis92/angular-calendar#931]
**Describe the bug**

Drag and Drop action overrides edit or delete link actions. I can't click on edit or delete action without firing drag and drop action. 

**Minimal reproduction of the problem with instructions**
Go to Kitchen sink example
Switch to Week view
Drag and drop one of the events
Then try to edit the event
Keep clicking the edit icon, you will get edit modal one time and drag and drop modal some other times. Sometimes you get multiple drag and drop modals over each other. 

**Versions**
0.27

**Comment by mattlewis92** [comment]
Hi there, sorry to hear you're having problems, I tried to reproduce your issue, but it's working for me: https://imgur.com/a/zYwQZKt

Can you show me a recording or something of you having the issue? Also what browser are you using? Thanks! 😄
