### ISSUE TITLE
After view render

### ISSUE THREAD

**Issue by zolee** [mattlewis92/angular-calendar#932]
**Is your feature request related to a problem? Please describe**

I would like to change some properties (like height of the calendar component) after the view mode (Month, Week, Day) has been changed. My problem is that although there are events before the component render to modify some CSS classes (like `beforeMonthViewRender`, `beforeWeekViewRender`, `beforeDayViewRender`) but there are no available events triggered after the view mode has been changed and the component rendered.

This causes problems like the view mode already modified but the component not rendered meanwhile I try to modify some component styles directly.

Please see this StackBlitz demo. Look for the `setView(view: CalendarView)` function in `demo/component.ts`
[https://stackblitz.com/edit/angular-calendar-after-view-render](https://stackblitz.com/edit/angular-calendar-after-view-render)

I also tried to overcome on this issue using some Angular Lifecycle Hooks but with no luck.

**Describe the solution you'd like**

Maybe it can be solved easily by some Lifecycle Hook or maybe implement some functions similar the `beforeViewRender` methods like:

`afterMonthViewRender`
`afterWeekViewRender`
`afterDayViewRender`

**Describe your use case for implementing this feature**

Provide  some event after we can safely access the component structure when the view mode changed.

**Additional context**

Thank you very much for support. :)

**Comment by mattlewis92** [comment]
Hey, so you can actually do this by manually triggering a round of change detection when you change the view. If you call `detectChanges()` after changing the view, then angular will run change detection and the view will update, so then you can access the view's dom. I updated your example to show you how to do this here: https://stackblitz.com/edit/angular-calendar-after-view-render-dh96na?file=demo/component.ts Hope that helps! 😄

**Comment by zolee** [comment]
> Hey, so you can actually do this by manually triggering a round of change detection when you change the view. If you call `detectChanges()` after changing the view, then angular will run change detection and the view will update, so then you can access the view's dom. I updated your example to show you how to do this here: https://stackblitz.com/edit/angular-calendar-after-view-render-dh96na?file=demo/component.ts Hope that helps! 😄

Thank you very much. That does the trick. 👍
