### ISSUE TITLE
Disabled date d'nd

### ISSUE THREAD

**Issue by ssi-hu-tasi-norbert** [mattlewis92/angular-calendar#938]
**Describe the bug**
I have set min, max dates, i cannot click them however i can drop event onto the disabled days too. I cannot drag those events from disabled days, it works as expected.

Thank you!

**Minimal reproduction of the problem with instructions**

**Screenshots**

**Versions**

- `@angular/core`:
- `angular-calendar`:
- Browser name and version:

**Comment by mattlewis92** [comment]
Hey there, in the `eventTimesChanged` output you need to check if the event was in a disabled date range, and if so then don't change the times on the event. Hope that helps! 😄

**Comment by ssi-hu-tasi-norbert** [comment]
It works. Thanks you!
