### ISSUE TITLE
Week view localisation

### ISSUE THREAD

**Issue by sylvain-fr** [mattlewis92/angular-calendar#943]
In week view time on the left side is not displayed in a localised way, in (france is should 14:00 instead of 2pm).

**Minimal reproduction of the problem with instructions**

**Screenshots**

**Versions**

- `@angular/core`:
- `angular-calendar`:
- Browser name and version:

**Comment by mattlewis92** [comment]
Unfortunately angular's i18n solution doesn't provide a way to do this kind of translation automatically, so you need to provide a custom date formatter to add this behaviour. I updated the demo to show you how to do this. Hope that helps!
