### ISSUE TITLE
Multiday events with start and end time

### ISSUE THREAD

**Issue by brijeshborad** [mattlewis92/angular-calendar#947]
Hello,
I am adding events for multiple days. I wanted to create a event for 3 days with starting time 9 AM and ending time 6 PM for each day. When I am selecting with start and end date with time, it is showing like this
http://prntscr.com/na6t8f

Event is getting beyond of end-time selected by me. Can you let me know how can for each day with start and end time. It is kind of a show running for 3 days and its timing is from 3 PM to 6 PM

**Minimal reproduction of the problem with instructions**

**Screenshots**

http://prntscr.com/na6t8f

**Versions**

- `@angular/core`: 7.1.0
- `angular-calendar`: 0.26.4
- Browser name and version: Chrome - 73.0.3683.86

**Comment by mattlewis92** [comment]
Please can you provide a runnable stackblitz (you can fork one from any of the demo pages) that reproduces your issue, without seeing any code it's hard to really know what's going on from the information you provided. Thank you! 😄
