### ISSUE TITLE
Use angular2-calendar in ionic 2

### ISSUE THREAD

**Issue by loyalpocket** [mattlewis92/angular-calendar#95]
Hello, I am trying to use "angular2-calendar" in ionic 2.
In app.module.ts, added:
import { CalendarModule } from 'angular-calendar';
and imports:[...., CalendarModule.forRoot()]

It works fine in web browser with "ionic serve", however, when I try to build the project, I got following errors:

.tmp/pages/calendar/calendar.ngfactory.ts:714:44
Module ''*'' has no exported member 'Wrapper_CalendarMonthViewComponent'.
.tmp/pages/calendar/calendar.ngfactory.ts:766:42
Module ''*'' has no exported member 'Wrapper_CalendarDayViewComponent'.

Any ideas? Much appreciated!

**Comment by mattlewis92** [comment]
What version of angular / ionic / ionic-app-scripts are you using?

**Comment by loyalpocket** [comment]
Thanks a lot for your quick response. here are the details:

"dependencies": {
    "@angular/common": "2.1.1",
    "@angular/compiler": "2.1.1",
    "@angular/compiler-cli": "2.1.1",
    "@angular/core": "2.1.1",
    "@angular/forms": "2.1.1",
    "@angular/http": "2.1.1",
    "@angular/platform-browser": "2.1.1",
    "@angular/platform-browser-dynamic": "2.1.1",
    "@angular/platform-server": "2.1.1",
    "@ionic/storage": "1.1.6",
    "angular-calendar": "^0.4.1",
    "ionic-angular": "2.0.0-rc.3",
    "ionic-native": "2.2.3",
    "ionicons": "3.0.0",
    "rxjs": "5.0.0-beta.12",
    "zone.js": "0.6.26"
  }

**Comment by mattlewis92** [comment]
Ah, it's because of a bug with angular. You need to be using `2.1.2` or higher, and then AoT should work.

**Comment by loyalpocket** [comment]
I see. Thanks a lot! I will investigate! Nice calendar!

**Comment by abdulqadir93** [comment]
Hello. I got it to compile using ionic by updating following entries in my package.json:

```
"dependencies": {
  "@angular/common": "2.1.2",
    "@angular/compiler": "2.1.2",
    "@angular/compiler-cli": "2.1.2",
    "@angular/core": "2.1.2",
    "@angular/forms": "2.1.2",
    "@angular/http": "2.1.2",
    "@angular/platform-browser": "2.1.2",
    "@angular/platform-browser-dynamic": "2.1.2",
    "@angular/platform-server": "2.1.2",
    "ionic-angular": "2.0.0-rc.4",
},
"devDependencies": {
  "@ionic/app-scripts": "0.0.47"
}
```

So, basically, update angular to 2.1.2 as suggested by @mattlewis92, ionic-angular to rc4 and ionic-app-scripts to 0.0.47. And it'll build just fine using ionic-cli. Hope this helps anyone out there!
