### ISSUE TITLE
IE Hover flickering

### ISSUE THREAD

**Issue by eBitzu** [mattlewis92/angular-calendar#956]
**Describe the bug**

In IE 11 when you hover over an event there is a window flickering

**Minimal reproduction of the problem with instructions**

Open IE11
https://mattlewis92.github.io/angular-calendar/#/kitchen-sink
Go to week view and hover the event.
The screen will shake as the tool-tip appears

- `@angular/core`: 6.4.7
- `angular-calendar`: 0.26.6
- Browser name and version: IE 11

**Comment by mattlewis92** [comment]
I don't have an IE machine handy to test, but if you add `[tooltipAppendToBody]="true"` does it fix it?

**Comment by eBitzu** [comment]
@mattlewis92 Still no fix?

**Comment by mattlewis92** [comment]
I don't have a windows machine to test it on so don't have a way of reproducing it to work out the issue, if you wanted to checkout the library locally and try and work on a fix that would be awesome! 😄

**Comment by mattlewis92** [comment]
I just upgraded the positioning library which might fix the issue as a lot of things changed with it.
