### ISSUE TITLE
Event goes outside the calendar when dragging it down and up again (day view)

### ISSUE THREAD

**Issue by hugocaldeira** [mattlewis92/angular-calendar#958]
**Describe the bug**
Hello,
In this last release (0.27.5) it was added the support of scrolling when dragging events, though when I drag an event down so that the calendar scrolls down and then I drag it back up, the event exceeds the top line of the calendar. From what I can see this its only happening on the day view, because in the week view it works perfectly.

**Minimal reproduction of the problem with instructions**

This issue can be reproduced in both the demos "Day view scheduler" and in the day view of "Kitchen sink".

Example of issue on demo "Day view scheduler":
- Hold the event called "An event" at 5 AM and drag it down so the 12 AM line gets out of the view.
- Without letting it go, scroll back up with the event and it goes way past the top line of the column, exceeding the name "John smith".
Is it possible to limit the drag of the event until the first line of the day view? It works when the scroll is not used.
**Screenshots**

**Versions**

- `@angular/core`: 7.1.0
- `angular-calendar`: 0.27.5
- Browser name and version: Chrome 73.0.3683

**Comment by mattlewis92** [comment]
Oh how strange, weird that it works on one view but not the other! Workaround for now is to stick to the older version of the drag and drop lib or use the week view with `[daysInWeek]="1"` set to emulate the day view: https://stackblitz.com/edit/angular-j5kje1?file=demo/component.ts

**Comment by hugocaldeira** [comment]
Got it, thank you.
  
  
  

  
  
  
  
  
>

**Comment by mattlewis92** [comment]
Fixed in `0.27.7`!

**Comment by hugocaldeira** [comment]
Cool! Thank you!

*Hugo Caldeira*
Diretor Técnico | /Chief Technology Officer/
inventore : oficina de software
+351 226 181 557 <tel:+361226181557> ⚬ inventore.pt <https://inventore.pt>

*Porto*
Rua Francisco Carqueja, 179 2º esq.
4350-185 Porto

*Lisboa*
Rua José Saramago 5A - Sala E 53
1675-180 Pontinha
