### ISSUE TITLE
How to get event data from InMemoryDatabase?

### ISSUE THREAD

**Issue by danielptm** [mattlewis92/angular-calendar#96]
I am using the example for the angular CLI, and I am trying to get the events from the InMemoryDatabase. But this error is thrown when doing so.

EXCEPTION: Uncaught (in promise): Error: Error in ./Calendar class Calendar - inline template:34:6 caused by: undefined is not an object (evaluating 'events.filter')

What is the best way to get event data from the InMemoryDatabase or a real server for that matter?

**Comment by mattlewis92** [comment]
Would you mind sharing some code that reproduces your issue and I will help where I can 😀

**Comment by danielptm** [comment]
import { Component, OnInit } from '@angular/core';
import { CreateEvent } from "./create-event/create-event.component";
import { EditEvent } from "./edit-event/edit-event.component";
import { DatePipe } from "../pipes/date.pipe";

import {
  startOfDay,
  subDays,
  addDays,
  endOfMonth,
  isSameDay,
  isSameMonth,
  addWeeks,
  subWeeks,
  addMonths,
  subMonths,
  addHours
} from 'date-fns';
import { Subject } from 'rxjs/Subject';
import {
  CalendarEvent,
  CalendarEventAction,
  CalendarEventTimesChangedEvent
} from 'angular-calendar';
import {HttpService} from "../services/http.service"; // import should be from `angular-calendar` in your app

const colors: any = {
  red: {
    primary: '#ad2121',
    secondary: '#FAE3E3'
  },
  blue: {
    primary: '#1e90ff',
    secondary: '#D1E8FF'
  },
  yellow: {
    primary: '#e3bc08',
    secondary: '#FDF1BA'
  }
};

@Component({
  selector: 'calendar',
  styles: ["calendar.css"],
  templateUrl:"calendar.html"
})
export class Calendar implements OnInit{

  constructor(private ghttp:HttpService){}



  view: string = 'month';
  manageView:String = '';
  thisYear = new Date().getFullYear();
  nextYear = new Date().getFullYear()+1;
  viewDate: Date = new Date();
  refresh: Subject<any> = new Subject();

  //The json data is received from the In memory db, but causes the error mentioned.
	
  events;

  ngOnInit():void {
    this.ghttp.retrieveEvents("").then(eventData =>{
      var dataWithColors = this.applyColors(eventData);
      this.events = dataWithColors;
    });
  }

  // Uncommenting below and commenting out above, makes the calendar work as expected.
  // events = [
  //     {
  //     start: new Date(),
  //     end: new Date(),
  //     title: 'A 3 day event',
  //     color: colors.red,
  //     description:"Stuff about the event goes here.",
  //     recurring:"no"
  //   }, {
  //     start: new Date(),
  //     title: 'An event with no end date',
  //     color: colors.yellow,
  //     description:"Stuff about the event goes here."
  //     recurring:"1"
  //     }, {
  //     start: new Date(),
  //     end: new Date(),
  //     title: 'A long event that spans 2 months',
  //     color: colors.blue,
  //     description:"Stuff about the event goes here.",
  //     recurring:"7"
  //   }, {
  //     start: new Date(),
  //     end: new Date(),
  //     title: 'A resizable event',
  //     color: colors.yellow,
  //     description:"Stuff about the event goes here.",
  //     recurring:"no",
  //     resizable: {
  //       beforeStart: true,
  //       afterEnd: true
  //     }
  //   }
  // ];

  activeDayIsOpen: boolean = true;

  increment(): void {

    const addFn: any = {
      day: addDays,
      week: addWeeks,
      month: addMonths
    }[this.view];

    this.viewDate = addFn(this.viewDate, 1);

  }

  decrement(): void {

    const subFn: any = {
      day: subDays,
      week: subWeeks,
      month: subMonths
    }[this.view];

    this.viewDate = subFn(this.viewDate, 1);

  }

  today(): void {
    this.viewDate = new Date();
  }

  dayClicked({date, events}: {date: Date, events: CalendarEvent[]}): void {

    if (isSameMonth(date, this.viewDate)) {
      if (
        (isSameDay(this.viewDate, date) && this.activeDayIsOpen === true) ||
        events.length === 0
      ) {
        this.activeDayIsOpen = false;
      } else {
        this.activeDayIsOpen = true;
        this.viewDate = date;
      }
    }
  }

  eventTimesChanged({event, newStart, newEnd}: CalendarEventTimesChangedEvent): void {
    event.start = newStart;
    event.end = newEnd;
    this.refresh.next();
  }

  manage(view){
    this.manageView = view;
  }

  applyColors(eventData){
    for(var i=0; i<eventData.length; i++) {
      if(eventData[i].color=="red"){
        eventData[i].color = colors.red;
      }
      else if(eventData[i].color=="blue"){
        eventData[i].color = colors.blue;
      }
      else if(eventData[i].color =="yellow"){
        eventData[i].color = colors.yellow;
      }
    }
    return eventData;
  }
}

**Comment by danielptm** [comment]
Thanks, I am not too great with angular2, but it seems like the ngOnInit method should assign the json events data to this.events, and the calendar should work as expected, but the error I mentioned is thrown. On the other hand if I comment that section out and uncomment the events array, then the code works just as expected.

**Comment by danielptm** [comment]
I am closing this, issue because I never got it to work, and am going to find an alternative solution for my problem.

**Comment by mattlewis92** [comment]
Sorry about the late reply on this one, I was away on holiday this weekend. Your issue is because the `events;` array was initialised to undefined so the error was thrown as you can't filter on an undefined array. I've cut a new release which should stop this.

**Comment by danielptm** [comment]
Hey no worries, thanks for your help. I look forward to getting this calendar into my project!

**Comment by ShubhamVohra** [comment]
Here is my html file:

`<div class="row">

  <div class="col-md-3">
    <div class="card">
      <div class="card-block">
        <ul>
          <li
            *ngFor="let event of externalEvents"
            mwlDraggable
            [dropData]="{event: event}"
            style="position:relative; z-index: 10">
            <a
              href="javascript:;"
              [style.color]="event.color.primary">
              {{ event.title }}
            </a>
          </li>
        </ul>
      </div>
    </div>
  </div>

  <div class="col-md-9">
    <mwl-demo-utils-calendar-header
      [(view)]="view"
      [(viewDate)]="viewDate">
    </mwl-demo-utils-calendar-header>

    <div [ngSwitch]="view">
      <mwl-calendar-month-view
        *ngSwitchCase="'month'"
        [viewDate]="viewDate"
        [events]="events"
        [activeDayIsOpen]="activeDayIsOpen"
        [refresh]="refresh"
        (eventTimesChanged)="eventDropped($event)">
      </mwl-calendar-month-view>
      <mwl-calendar-week-view
        *ngSwitchCase="'week'"
        [viewDate]="viewDate"
        [events]="events"
        [refresh]="refresh"
        (eventTimesChanged)="eventDropped($event)">
      </mwl-calendar-week-view>
      <mwl-calendar-day-view
        *ngSwitchCase="'day'"
        [viewDate]="viewDate"
        [events]="events"
        [dayStartHour]="9"
        [dayEndHour]="18"
        [refresh]="refresh"
        (eventTimesChanged)="eventDropped($event)">
      </mwl-calendar-day-view>
    </div>
  </div>

</div>`

and here is my typescript file:

`import { Component, OnInit,ChangeDetectionStrategy,NgZone  } from '@angular/core';
import { CalendarEvent, CalendarEventTimesChangedEvent } from 'angular-calendar';
import { Subject } from 'rxjs/Subject';
import {colors} from './colors';
import {getTime,addHours,addDays} from 'date-fns';
import { RequestService } from '../../services/requests/request.service';
import { NgbDateStruct,NgbTimeStruct } from '@ng-bootstrap/ng-bootstrap';



@Component({
  selector: 'app-schedboard',
  templateUrl: './schedboard.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  styleUrls: ['./schedboard.component.css','../../../node_modules/angular-calendar/dist/css/angular-calendar.css']
})

export class SchedboardComponent implements OnInit {
  view: string = 'day';
  viewDate: Date = new Date();
  state:string;
  size:number;
  
  requests:[{
    actype:string,
    capacity:string,
    reqtype:string,
    date:string,
    clientid:string,
    reqdesc:string,
    createdate:string,
    status:string,
    address:{
      geometry:{
        type:string,
        coordinates:{
          lat:number,
          lng:number
        }
      }
    },
    location:string
  }
  ];

  externalEvents:  CalendarEvent[]=[];
  events: CalendarEvent[] = [];
  activeDayIsOpen: boolean = false;
  obj: any;
  
  refresh: Subject<any> = new Subject();

  constructor(private requestservice:RequestService,public zone:NgZone) { 
  }

  ngOnInit() {
     this.state = null;
      this.requestservice.getRequests(this.state).subscribe((requests)=>{
      this.requests = requests; 
      this.size = this.requests.length;
      for(var i=0;i<this.size;i++){
         this.obj = {
          title: this.requests[i].reqdesc,
          start:new Date(this.requests[i].date),
          color:colors.yellow,
          end:new Date(this.requests[i].date),
          draggable:true
        }
      }
      
      this.externalEvents.push(this.obj);
      this.refresh.next();
      console.log(this.externalEvents);
    }); 
  }



  ngAfterViewInit(){
    
  }



  // eventTimesChanged({event,newStart,newEnd}: CalendarEventTimesChangedEvent): void {
  //   event.start = newStart;
  //   event.end = newEnd;
  //   this.refresh.next();
  // }

  eventDropped({event,
    newStart,
    newEnd
  }: CalendarEventTimesChangedEvent): void {
    const externalIndex: number = this.externalEvents.indexOf(event);
    if (externalIndex > -1) {
      this.externalEvents.splice(externalIndex, 1);
      this.events.push(event);
    }
    event.start = newStart;
    console.log(newStart);
    if (newEnd) {
      event.end = newEnd;
    }
    this.viewDate = newStart;
    this.activeDayIsOpen = true;
    this.refresh.next();
  }

}
  
`
