### ISSUE TITLE
"Selectable Period" demo not working

### ISSUE THREAD

**Issue by Mattkins** [mattlewis92/angular-calendar#961]
**Describe the bug**

In the "Selectable Period" example, days that are selected are not updating with the correct class in the DOM when the dayClicked handler is executed.

The demo works fine, but the StackBlitz does not. Days do not have the selected class applied unless the view is switched, demonstrating that the class is being applied in beforeMonthViewRender(), but not dayClicked()

**Minimal reproduction of the problem with instructions**

To reproduce, just open the StackBlitz and click a day. It won't highlight when clicked, but will highlight if you switch views or go to another month and then come back to the original view.

**Screenshots**

**Versions**

- `@angular/core`:  7.2.14
- `angular-calendar`: 0.27.5
- Browser name and version: Chrome 73.0.3683.103

**Comment by Mattkins** [comment]
FYSA: The workaround in #959 also fixes this issue.

**Comment by mattlewis92** [comment]
Thanks for reporting, fixed in `0.27.6`!
