### ISSUE TITLE
Support date-fns v2.0.0 beta

### ISSUE THREAD

**Issue by rosostolato** [mattlewis92/angular-calendar#963]
**Is your feature request related to a problem? Please describe**
Version 2 of date-fns breaks angular-calendar code

**Describe the solution you'd like**
Change date-fns adapater codes to support new version

**Describe your use case for implementing this feature**
I wish to use newer version of date-fns because it brings me more functions and I cannot have two libraries of date-fns in my project, it will make the final bundle larger.

**Comment by mattlewis92** [comment]
While date-fns is in alpha I don't want to support it officially as they could introduce breaking changes to the api which would mean having to makes changes here. As soon as date-fns v2 is stable I'll update the calendar to support it. In the meantime you could write your own date adapter which uses v2, the only thing that needs to change is the `max` function changed: https://stackblitz.com/edit/angular-xzssvt?file=demo/date-fns-v2-adapter.ts
