### ISSUE TITLE
How to use ng-template in angular calendar week view to show certain day hours in different color

### ISSUE THREAD

**Issue by harsimerkaur** [mattlewis92/angular-calendar#966]
**Is your feature request related to a problem? Please describe**

I have to show certain hours on week view in separate color as blocked hours.

**Describe the solution you'd like**

Is there a ng-template option for cal-day-column so that we can mark certain hours in different color using CSS

**Describe your use case for implementing this feature**

My use case is that I am showing a calendar with some events and user for which it is shown could be able to block certain hours of the week.

**Additional context**

<img width="957" alt="custom-week-view" src="https://user-images.githubusercontent.com/38556673/57056569-f7e4d300-6cc0-11e9-986c-da99e5d7da2e.png">

In attached image grey out meant blocked hours of the day so on viewing those hours one could detect that events on that hour has to be canceled. That is my use case.

Thanks a ton

**Comment by mattlewis92** [comment]
Hi there, you can use the `beforeViewRender` output to add a css class to certain segments, checkout the demo how to do this here: https://mattlewis92.github.io/angular-calendar/#/before-view-render Hope that helps! 😄
