### ISSUE TITLE
Feature: Add the an option to show time increments in day and week view without creating custom templates.

### ISSUE THREAD

**Issue by jcanning** [mattlewis92/angular-calendar#969]
**Is your feature request related to a problem? Please describe**
It is frustrating to have to create custom day and week templates to just show the time increments in Day and Week view (i.e. 7 am, 7:30am, 8am etc)

**Describe the solution you'd like**
The ability to turn on and off the time increments for Day and Week view.

**Describe your use case for implementing this feature**
Creating a custom day and week component is not overly easy and you end up losing the current style/look and feel.

**Additional context**
It would be nice to have an option like [TimeIncrements]="1 hour" or = "30 minutes" or = "15 minutes" sort of thing.

**Comment by mattlewis92** [comment]
Hey John, so this is actually possible to do with the current API, every segment does have a time there, it's just hidden by default. If you add this to your global CSS, it will show them all:
```
.cal-week-view .cal-hour-segment.cal-after-hour-start .cal-time {
    display: block;
}

.cal-day-view .cal-hour-segment.cal-after-hour-start .cal-time {
    display: flex;
}
```

Then you need to use a custom date formatter to add the minutes and finally if you want more than 2 segments per hour you can use the `hourSegments` option on the day and week views.

Here's an e2e example of it working: https://stackblitz.com/edit/angular-vkx9ug?file=index.html Hope that helps! 😄

**Comment by jcanning** [comment]
Thanks again Matt. This worked great!
