### ISSUE TITLE
Day view event overlapping

### ISSUE THREAD

**Issue by Naresh4847** [mattlewis92/angular-calendar#979]
**Describe the bug**

Calendar day view events are overlapping each other when we set it to minimum time 

I created event like :

start time : 12:05 pm , end time : 12:10 pm ,
and 
start time 12:02 pm , end time : 12:03 pm..
at this moment events are overlapping each..

what we want ::

Side by Side events .. if it is one minute gap also ..

**Screenshots**
Issue in module ..

![actualmoduletestcase](https://user-images.githubusercontent.com/40490100/57569354-971c6f80-7411-11e9-9c5f-2b3d63f07c57.PNG)

https://stackblitz.com/run?file=demo/component.ts

My Issue::

![mytestcase](https://user-images.githubusercontent.com/40490100/57569360-a4395e80-7411-11e9-9d42-e24f973b921e.PNG)

**Versions**

- `@angular/core`:7.2.3 version 
- `angular-calendar`:0.26.6 version ..
- Browser name and version:Google Chrome , Firefox, Safari

**Comment by mattlewis92** [comment]
Hey, thanks for opening an issue, it looks like your stackblitz didn't save, please can you re-add it? Thanks!
