### ISSUE TITLE
Is there a way to make the events listed out by name on the actual date. 

### ISSUE THREAD

**Issue by xtianus79** [mattlewis92/angular-calendar#98]
Sorry, 

this may be in the documentation but I have yet to find it.  

I would like to list out the events on the page per date and forgo the animation drop down of events nested behind the calendar.  

Is there a straight forward way to do this?

**Comment by mattlewis92** [comment]
I'm afraid there is no way of disabling the slidebox animation, AFAIK there is no way in angular to conditionally disable an animation. Once [custom templates](https://github.com/mattlewis92/angular-calendar/issues/16) are implemented you'll be able to use your own template without the animation property set.

**Comment by xtianus79** [comment]
ok we are ok with keeping the animation... but is there a way to list out the events on the actual date for the month?

**Comment by mattlewis92** [comment]
Sorry I don't quite follow what you mean?

**Comment by xtianus79** [comment]
sorry... 

so on the month for each day... i.e. the 6th we want to list out the event on the particular day in the box for that day of the calendar.  The sub section and animation is fine but we would like to also list out the events per the day on the calendar ui box for that day.

**Comment by mattlewis92** [comment]
Oh as in retrieve the events that are listed on that day?

**Comment by xtianus79** [comment]
yes... well to retrieve them and put them on the calendar for the month to list out the events to the end user

**Comment by mattlewis92** [comment]
So for this example you'd want to get the "A 3 day event" event?

<img width="812" alt="screen shot 2016-12-07 at 17 01 47" src="https://cloud.githubusercontent.com/assets/6425649/20977919/e21bc45e-bc9e-11e6-9685-c98e1bb8f90b.png">

**Comment by xtianus79** [comment]
yes so for the 7th i want to see "A 3 day event" list out as a line on the 7th box.

**Comment by mattlewis92** [comment]
Oh do you mean for the events to span multiple days?
<img width="639" alt="screen shot 2016-12-07 at 17 10 32" src="https://cloud.githubusercontent.com/assets/6425649/20978250/162e234e-bca0-11e6-8e37-3306f929e08e.png">

**Comment by xtianus79** [comment]
not even multiple days... just the event for that day... but yes just like you show on the 8th

**Comment by mattlewis92** [comment]
Oh right, no there's not a way of doing this, you only have the colored dots. Once [custom templates](https://github.com/mattlewis92/angular-calendar/issues/16) are implemented you'll be able to do something like this yourself

**Comment by xtianus79** [comment]
ok do you know when that will be implemented... and if not very soon would this be a hard "adjustment/hack" to achieve from your perspective?

**Comment by mattlewis92** [comment]
I have no idea when it’ll be implemented, I work on this project (along with several dozen more) in my free time. For now you could just fork the library and implement the change you need, and then once custom templates are implemented use this lib again.

Because of the limitations of angular there is no way to currently hack this in without forking the library.

Kind regards,
Matt Lewis

**Comment by xtianus79** [comment]
true... Thank you @mattlewis92

**Comment by SamindaK** [comment]
Hi @mattlewis92 i made the changes on the same issue by forking it. is there a way for me to publish it to npm ?

**Comment by mattlewis92** [comment]
Change the package name in `package.json` and run `npm run release`

**Comment by SamindaK** [comment]
Thanks @mattlewis92 i did make the changes and used npm publish 
Thanks for the brilliant code. current calendar of mine 
![calendar](https://cloud.githubusercontent.com/assets/17622375/23159467/db350c64-f848-11e6-99c3-61fb611ae9d1.PNG)

**Comment by xtianus79** [comment]
@mattlewis92 and @SamindaK so is this available now in the current build?  What did you do to accomplish this?  thanks

**Comment by mattlewis92** [comment]
@xtianus79 it's currently not possible without forking the repo, I'm going to try and get custom templates done this week though as I have a clean way of implementing it now 😃

**Comment by kwilliams** [comment]
Can you re-open this ticket. This calendar is much better than the fullcalendar version in my opinion, but it's much harder to provide a birds eye view of events when limited to only viewing titles of the selected day. Also due to this resizing functionality is non existent from the monthly view.

**Comment by mattlewis92** [comment]
@kwilliams This is actually possible now in 0.9.0 onwards. If you follow the [custom templates](https://mattlewis92.github.io/angular-calendar/#/custom-templates) demo but use the `openDayEventsTemplate` input instead of `cellTemplate` you can pass a template in to customise the events list like so:
```
    <ng-template #customTemplate let-events="events" let-eventClicked="eventClicked">
      <div
        *ngFor="let event of events"
        [ngClass]="event?.cssClass">
        <span
          class="cal-event"
          [style.backgroundColor]="event.color.primary">
        </span>
        <mwl-calendar-event-title
          [event]="event"
          view="month"
          (click)="eventClicked.emit({event: event})">
        </mwl-calendar-event-title>
        <mwl-calendar-event-actions [event]="event"></mwl-calendar-event-actions>
      </div>
    </ng-template>

<mwl-calendar-month-view [openDayEventsTemplate]=""></mwl-calendar-month-view>
```

Hope that helps!

**Comment by kwilliams** [comment]
Thanks for the response this was helpful!

**Comment by kattakranthi** [comment]
Hi mattlewis92,

can you please confirm if span multiple days is available in Angular 5 version?

Thanks.

**Comment by bergmito** [comment]
<img src="https://cloud.githubusercontent.com/assets/6425649/20978250/162e234e-bca0-11e6-8e37-3306f929e08e.png">

@mattlewis92  Is this possible?

**Comment by ImenTaieb** [comment]
![](https://cloud.githubusercontent.com/assets/6425649/20978250/162e234e-bca0-11e6-8e37-3306f929e08e.png)

@mattlewis92  Please i need help i want to implement this solution with month view is this possible to use custom template ?

**Comment by AngularDe** [comment]
![image](https://user-images.githubusercontent.com/41523926/43708711-5fb81ee4-996b-11e8-931c-adf8c37464ef.png)
@mattlewis92  @ImenTaieb Were able to implement this or is it possible to do it using the custom template ? Thanks.

**Comment by BiStokeCity** [comment]
Hi everybody, i would like to add new event in @freetime (week view) and i expect result is event's color continuity but i receive striped (e.g: green, red, green, red). green freetime. red busy. Thank so much.

**Comment by BiStokeCity** [comment]
Event over event. Sr because my English not good.

**Comment by najah1501** [comment]
Im not able to show title instead of title being represented by dots in month view calendar. I want to show the title itself.How to achieve this. Anyone can help?
