### ISSUE TITLE
Vertical Time Slot 

### ISSUE THREAD

**Issue by Seb69** [mattlewis92/angular-calendar#980]
**Is your feature request related to a problem? Please describe**

Display time slots. 

**Describe the solution you'd like**

Vertical time slot. 

![img](https://user-images.githubusercontent.com/14105342/57600203-66dfe880-7559-11e9-8f12-3b489000656b.png)

**Describe your use case for implementing this feature**

Need to show time slot availabilities in order to set up meetings within them.

**Comment by mattlewis92** [comment]
I replied to your email 😄

**Comment by andofetra** [comment]
I saw a similar feature in a calendar we use in our society. It is very useful for example to differentiate exceptional events from standard events.
