### ISSUE TITLE
small html error in code of calendar-open-day-events.component.ts

### ISSUE THREAD

**Issue by xileftenurb** [mattlewis92/angular-calendar#984]
**Describe the bug**

I just found something that look like a bug in the code by browsing in it.
it does not appear to do anythings
in the file "https://github.com/mattlewis92/angular-calendar/blob/master/projects/angular-calendar/src/modules/month/calendar-open-day-events.component.ts" at the line 54 and 61 of the default template there is a character named "&ngsp;".
I think it should be "&nbsp;", or nothing, as "&ngsp;" is not (as far as I know?) a valid html character...
It does not seem to do anything (firefox just ignore the character).

**Minimal reproduction of the problem with instructions**

nothing to do, just check the code

**Screenshots**

**Versions**

branch:master
- `@angular/core`: (not applicable)
- `angular-calendar`: Branch:master.
- Browser name and version: (not applicable)

**Comment by mattlewis92** [comment]
Hey, thanks for opening an issue, this is actually part of angular, it's a special flag to the angular compiler to preserve the whitespace: https://angular.io/api/core/Component#preserveWhitespaces
