### ISSUE TITLE
ICS file import to calendar

### ISSUE THREAD

**Issue by nchetankumar** [mattlewis92/angular-calendar#993]
Do we have the option to import ICS file into an angular calendar?

**Is your feature request related to a problem? Please describe**

**Describe the solution you'd like**

**Describe your use case for implementing this feature**

**Additional context**

**Comment by mattlewis92** [comment]
There's nothing built in to support this, but you could use [another package](https://www.npmjs.com/package/ical) to parse ical files and then transform them into the format the calendar expects.

**Comment by tadzik** [comment]
If you're looking for inspiration, the Runbox7 Calendar based on angular-calendar implements that (and other things) using Mozilla's ICAL.js: https://github.com/runbox/runbox7/blob/master/src/app/calendar-app/runbox-calendar-event.ts#L149
