### ISSUE TITLE
dayClicked is not working

### ISSUE THREAD

**Issue by Andresxx** [mattlewis92/angular-calendar#995]
**Describe the bug**

**Minimal reproduction of the problem with instructions**

**Screenshots**

**Versions**

- `@angular/core`:
- `angular-calendar`:
- Browser name and version:

**Comment by mattlewis92** [comment]
Looks like there was an issue with [the demo](https://mattlewis92.github.io/angular-calendar/#/clickable-days) where it wasn't using all the click handlers, I've just updated it so I think that'll fix your problem 😄
